### ISSUE TITLE
Turf area makes very big errors

### ISSUE THREAD

**Issue by vicvolk** [Turfjs/turf#1000]
So, I have two arbitrary features. Feature 1 has such coordinates:

`[[[43.78399729326754,56.36157554846778],[43.78399729326754,56.4607222095473],[44.30413126543552,56.4607222095473],[44.30413126543552,56.36157554846778],[43.78399729326754,56.36157554846778]],[[43.931626077447234,56.417638450785546],[43.931626077447234,56.391042617567535],[43.972824807915984,56.391042617567535],[43.972824807915984,56.417638450785546],[43.931626077447234,56.417638450785546]]]`

And feature 2 has such coordinates:

`[[[43.993168711913626,56.46097807678447],[44.041233897460835,56.376663421623334],[43.95471656347676,56.40478907264034],[43.993168711913626,56.46097807678447]]]`

And feature 2 is significantly bigger, than feature 1. Though turf.area provides such numbers - 346028811.6820663 and 20363354.73796771 for the first and second feature respectively. So, turf area says, that feature 1 is more than 10 times bigger, than the second feature 2. Though, it must be smaller. So, what is wrong with that?

**Comment by vicvolk** [comment]
Oh, sorry! I see what is wrong with that! My fault.

**Comment by DenisCarriere** [comment]
🎉 Issue 1000, lol!
