### ISSUE TITLE
dissolve documentation ambiguity

### ISSUE THREAD

**Issue by kannes** [Turfjs/turf#1008]
http://turfjs.org/docs/#dissolve says

> Dissolves a FeatureCollection of polygons based on a property. Note that multipart features within the collection are not supported

a) A FeatureCollection of Features that have Polygon geometries is meant, right?

b) What is meant by "multipart features"? Features having Multi* geometries such as MultiPolygon?

**Comment by rowanwins** [comment]
Hi @kannes 

Yes are you are correct on both counts. Thanks for the report and we'll get the docs updated :)

**Comment by kannes** [comment]
Thanks!

Is support for MultiPolygons planned in the foreseeable future?

**Comment by rowanwins** [comment]
A rejig of the dissolve module to include multipolygons is on the cards, although we need to replace our union module first (on which dissolve depends) so it'll probably be a few months before we get to it.

**Comment by DenisCarriere** [comment]
Like @rowanwins mentioned, it would be best to update the `union` in the first place and then move towards supporting all the other GeoJSON geometry types such as MultiPolygon.

@kannes Thanks for the documentation input, TurfJS's documentation is auto-generated from the JSDocs found in each `index.js` files, feel free to submit a PR with documentation updates, this will greatly improve TurfJS to make it more understable.

https://github.com/Turfjs/turf/blob/master/packages/turf-dissolve/index.js#L8-L27
