### ISSUE TITLE
AGPL license issue with turf-isobands

### ISSUE THREAD

**Issue by brianreavis** [Turfjs/turf#1018]
Casual observation here: [turf-isobands](https://github.com/Turfjs/turf/tree/master/packages/turf-isobands) uses [marchingsquares-isobands.js](https://github.com/Turfjs/turf/blob/master/packages/turf-isobands/marchingsquares-isobands.js) which is AGPL and (as far as I know) not compatible with turf's MIT license?

**Comment by DenisCarriere** [comment]
This has already be discussed here:
https://github.com/RaumZeit/MarchingSquares.js/issues/3

With the modified license:
https://github.com/RaumZeit/MarchingSquares.js/commit/870f00630b739cf94aeb63b11197b0941bd8793f
