### ISSUE TITLE
Remove @turf/square-grid "completelyWithin"

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#1019]
@DenisCarriere I am working on [renaming](https://github.com/Turfjs/turf/issues/460#issuecomment-310360602) the `cellSide` parameter of `@turf/hex-grid` and I noticed we mentioned to add also a `completelyWithin` option, already [implemented](https://github.com/Turfjs/turf/pull/612) in `@turf/square-grid`.
However I was wondering if it makes sense to have that parameter, or if actually would be better to have, for both `@turf/hex-grid` and `@turf/square-grid`, always a centered output like for `@turf/point-grid`, where we just [removed](https://github.com/Turfjs/turf/issues/613) the `centered` parameter.
This would make the output of all the grid modules consistent.

**Comment by DenisCarriere** [comment]
👍 Also noticed the same, we should try to revamp all the `<type>-grid` modules to make them behave the same way, they should all have the same Options (or at least the same base options).

**Comment by stebogit** [comment]
All done in #1029
