### ISSUE TITLE
isobands documentation clarity

### ISSUE THREAD

**Issue by jpoynton** [Turfjs/turf#1021]
Isoband documentation states that it takes a "grid FeatureCollection of Point features with z-values and an array of value breaks and generates filled contour isobands.". Can you clarify docs to be clear that it requires a square or rectangular grid in order to work.  

The confusion came about because turf.pointGrid states that it "Creates a Point grid from a bounding box, FeatureCollection or Feature". And is close enough that implies that should be valid input to isobands. However, a pointGrid created from an irregular polygon mask will not work in isoband/isoline as the 2D matrix created is not valid. Turf.Isobands unfortunately doesn't tell you this through documentation or error, it just produces an isoband with no geometry. 

See https://jsfiddle.net/rzj3ge87/1/ for an example.

**Comment by stebogit** [comment]
@jpoynton thanks for the feedback.
You're absolutely right, we need to clarify the `@turf/isobands` docs and maybe also throw an error if the input is not a square matrix. Also `@turf/point-grid` docs might have a note about `isobands` compatibility.

BTW @DenisCarriere I find confusing though that `@turf/point-grid`
> "Creates a Point grid from a bounding box, FeatureCollection or Feature"

Why FeatureCollection or Feature are included? I'd say a bounding box should be the (only) correct input. Same for all the other grid modules.

**Comment by jpoynton** [comment]
@stebogit thanks. As for your question to @DenisCarriere I'll have a go at answering. I believe point grid will calculate the bounding box for you if you give it a featurecollection/feature. The other option of a masked point grid would also require a feature collection feature as it's input. And that's useful to me.  I'm generating isochrones using OSRM and use the grid points as my target destinations. If I use a polygon as a mask to point-grid then I can clip the points to a coastline or administrative boundary so that I don't bother looking for journey times that I know are not routeable.

**Comment by stebogit** [comment]
@jpoynton you are right, for `@turf/point-grid` a `Polygon` or `FeatureCollection` (of `Polygon`s only) make sense due to the mask option, however I'd say not for the other grid modules, which don't have the mask option.

**Comment by DenisCarriere** [comment]
@stebogit Good point, what if we make the input `bbox` only and use the `mask` option as `Feature<Polygon>` instead of boolean. That way it's easier to understand the process and have to guess "what happens when I enter a Polygon" as input.

**Comment by DenisCarriere** [comment]
Since we're already pushing for a breaking change, we should do this change now before we officially release `v5.0`

**Comment by stebogit** [comment]
> make the input bbox only and use the mask option as Feature<Polygon> instead of boolean

Perfect @DenisCarriere, will do

**Comment by DenisCarriere** [comment]
👍
