### ISSUE TITLE
hex-grid generates unexpected shapes at bounding box size greater than 180 degrees

### ISSUE THREAD

**Issue by mike-anderson** [Turfjs/turf#1035]
I'm attempting to generate a hex grid that meaningfully covers the world.

I am using an aribtrary hex cellDiameter parameter of 400 miles and generating the attached geojson files using the code below:

```
var hex180bbox = [-90,-75,90,75];
var hex270bbox = [-135,-75,135,75];
var hex360bbox = [-180,-75,180,75];

var output = turf.hexGrid(hex180bbox,400,'miles');
```

areas up to 180 degrees make undistorted hexes at the equator as expected. 

<img width="1135" alt="hex180" src="https://user-images.githubusercontent.com/209407/31857076-215d7e90-b691-11e7-82d3-0584a5a345db.png">

The side length appears to stretch however at 270 degrees.

<img width="1136" alt="hex270" src="https://user-images.githubusercontent.com/209407/31857079-27755bc2-b691-11e7-9f06-af73767cd48f.png">

No complete visible hexes are present at 360 degrees.

<img width="1136" alt="hex360" src="https://user-images.githubusercontent.com/209407/31857081-2c3057e8-b691-11e7-9748-44b344011f4a.png">

I suspect this related to issue #460 as the where the cell diameter is measured would determine the shape at different latitudes.

Geojson files are included at this gist https://gist.github.com/mike-anderson/80011f9a149b2c5010225c6713bf5ebb

**Comment by DenisCarriere** [comment]
@mike-anderson Great submited issue, we're actually working on that as we speak here: https://github.com/Turfjs/turf/pull/1029

The proposed change is to convert the grids to a Mercator projection that way the shapes would be "equal-distance" between each cellside. This new change will make it "look" better for world grids that are using Leaflet based maps (mercator projection).

👍 

> No complete visible hexes are present at 360 degrees.

Hexes that are greater than 360 degree might be problematic, but maybe once we convert it to a Mercator projection it will be easier to approach this.

**Comment by DenisCarriere** [comment]
## Related to PR https://github.com/Turfjs/turf/pull/1029 (close this issue when PR is merged)

**Comment by mike-anderson** [comment]
Thanks @DenisCarriere,
That's great to hear - I'll follow #1029

**Comment by rowanwins** [comment]
Closing as the referenced pull request has been merged
