### ISSUE TITLE
Boolean Overlap - doesn't overlap inside polygon

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1036]
## `@turf/boolean-overlap` - doesn't overlap inside polygon
@rowanwins I've been using `@turf/boolean-overlap` to apply a mask operation on the grid modules. Each grid polygon does the boolean-overlap method and should return `false/true`, however it seems like the polygon that are completely within (not touching the lines) are not counted as overlapping, is that the expected behavior? I would assume that the inner polys should still be overlapping the mask polygon.

@stebogit Thoughts? Since we're working on the grid modules.

## `@turf/triangle-grid`
![image](https://user-images.githubusercontent.com/550895/31858144-7c606b74-b6ad-11e7-8dde-5b74b8dac3fc.png)

## `@turf/square-grid`
![image](https://user-images.githubusercontent.com/550895/31858162-e817bd0e-b6ad-11e7-931e-f2908c9b24f2.png)

**Comment by stebogit** [comment]
@DenisCarriere from the docs `@turf-overlaps` 
> Compares two geometries of the same dimension and returns true if their intersection set results in _**a geometry different from both**_ but of the same dimension. It applies to Polygon/Polygon, LineString/LineString, Multipoint/Multipoint, MultiLineString/MultiLineString and MultiPolygon/MultiPolygon.

The intersection of the big polygon with the inner grid polygons is actually equal to the grid polygon, so they do not technically overlap (based on the definition).
I think here `@turf/boolean-contains` or `@turf/boolean-within` would be the appropriate one to use.

**Comment by rowanwins** [comment]
Hi @DenisCarriere 

This definition from the FME [docs ](http://docs.safe.com/fme/2015beta/html/FME_Desktop_Documentation/Subsystems/FME_Transformers/Content/Transformers/spatialrelations.htm)is also helpful here
> The interiors intersect, but neither feature is contained by the other, nor are the features equal.

So I think @stebogit is on the money with his recommendation, it might be worth a quick check to see if one or the other is more performant that than the other for this use case...

**Comment by DenisCarriere** [comment]
👍 Thanks for the answers, the FME docs are pretty good at explaining it, i'll use `@turf/boolean-contains` for what I'm trying to do.

> The interiors intersect, but neither feature is contained by the other, nor are the features equal.

**Comment by DenisCarriere** [comment]
I actually combined both `contains` + `overlap` to get the final result:

![image](https://user-images.githubusercontent.com/550895/31871303-36a5974c-b781-11e7-89ae-ad41f1c2a594.png)

Only using `contains` gave me this:

![image](https://user-images.githubusercontent.com/550895/31871323-5a7c1fb0-b781-11e7-9f99-876a43bbd0fa.png)

**Comment by stebogit** [comment]
I think `contains` + `overlap` is more similar to what you would expect out of this module. Good job! 👍

**Comment by rowanwins** [comment]
@DenisCarriere  `boolean-intersect` is probably what is required to get the proper result

**Comment by DenisCarriere** [comment]
@rowanwins Agreed, however it's not implemented yet 😄

**Comment by DenisCarriere** [comment]
I'm using `@turf/intersect` and it works out pretty good for this scenario.

![image](https://user-images.githubusercontent.com/550895/31888888-c57280d0-b7cb-11e7-80fd-4ab5e190be18.png)
