### ISSUE TITLE
Is there any module to fill a ring polygon ?

### ISSUE THREAD

**Issue by chaucerling** [Turfjs/turf#1037]
I know the `turf.mask()`  function can make a unmasked polygon to a ring polygon with holes. But conversely, if I want to fill the ring polygon, and get the unmasked polygon, is there any module help me to resolve this problem.

http://geojson.io/#id=gist:anonymous/ae1ca487f5bc83e8e14dac39b2a20c82&map=3/-26.98/130.00

**Comment by rowanwins** [comment]
Hi @chaucerling 

If I understand correctly you want to get the shape of the hole and turn it into a polygon, discarding the old outer polygon... 

Could you call this `holeToPolygon()`, does that describe what you're trying to do?

**Comment by chaucerling** [comment]
@rowanwins, Sorry for my poor English. I just want to get the outer polygon (the ring) combined with the inner polygon (the holes).

**Comment by rowanwins** [comment]
Ah so if I understand correctly you want to remove the holes from the polygon. Short answer is no there is nothing available. 

If you're just dealing with polygons (and not `MultiPolygons`) you should be able to do something like
````
   orig.geometry.coordinates.splice(1, orig.geometry.coordinates[0].length - 1)
````
This will leave you will the outer geometry and delete any holes

**Comment by amenadiel** [comment]
Actually you could do it with multipolígons too by playing with CCW and using the ring directions to determine they are holes.

**Comment by allthesignals** [comment]
You don't really need to detect CCW - just splice out the interior rings, no? They're always in a predictable position. MultiPolygons coordinates are just an array of Polygon coordinates.

**Comment by jayarjo** [comment]
@rowanwins @allthesignals can you elaborate on semantics of this?

```
orig.geometry.coordinates.splice(1, orig.geometry.coordinates[0].length - 1)
```

**Comment by kanadgupta** [comment]
> can you elaborate on semantics of this?
> 
> ```
> orig.geometry.coordinates.splice(1, orig.geometry.coordinates[0].length - 1)
> ```

Came across this issue a few years later — this StackOverflow answer breaks down the semantics quite well: https://stackoverflow.com/a/42556149
