### ISSUE TITLE
Proposal: Rename `@turf/clusters` to `@turf/find`

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1039]
## Proposal: Rename `@turf/clusters` to `@turf/find`

Someone at SotM mentioned it would be nice to have a `find` module, being able to find features based on properties within a FeatureCollection.

The `getCluster` from [`@turf/clusters`](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters) behaves exactly like that, except `clusters` as a name might not be very obvious for folks.

I'm proposing we rename the `@turf/clusters` module to `@turf/find`.

> **Note**: `@turf/clusters` has zero dependencies other than `@turf/meta` & `@turf/helpers`

## Method name changes

- `@turf/clusters` => `@turf/find`
- `getCluster` => `find`
- `clusterEach` => `findEach`
- `clusterReduce` => `findReduce`

## Dependant modules
- `@turf/clusters-kmeans`
- `@turf/clusters-dbscan`

## Votes

- 👎 @rowanwins 
- 👎 @DenisCarriere

**Comment by rowanwins** [comment]
Hmmm I kind of get the rationale but I think `find` is a bit of an ambiguous name, more ambiguous than `clusters` which at least kind of tells you what it's going to do.... 

I wonder if we could take some cues from the ArcGIS world, they have a toolset/category called `Spatial Statistics` and then a few tools, probably most similar would be one called [Grouping Analysis](http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/grouping-analysis.htm). I read that title and get a fair idea what it's going. I even read `clusters` and get a fair clue. Unfortunately I read `find` and I'm confused, it could mean a squillion things.

-1 from me

**Comment by DenisCarriere** [comment]
I agree with you @rowanwins.

👎 For my proposal, however we should find some clever names for this `clusters` module, some kind of grouping theme.

Going to keep `@turf/clusters` until we can find a new names for those methods.

**Comment by stebogit** [comment]
👎 
I like `cluster` and I think is appropriate 😄

**Comment by DenisCarriere** [comment]
lol! Fine then! I'll just close this Issue since we all agree on that name, just figure I'd bounce the idea around.
