### ISSUE TITLE
If numberOfSegments is integer, no need to plus 1 in line-chunk

### ISSUE THREAD

**Issue by xiongjiabin** [Turfjs/turf#1044]
if the line length is 100, and segment length is 10, the number of segments is just 10, no need to plus 1, otherwise will throw an exception later.  The right code works. 

![image](https://user-images.githubusercontent.com/1040542/32050280-d2e6db3e-ba15-11e7-918f-54d7839b4a6e.png)

**Comment by rowanwins** [comment]
Done in #1046
