### ISSUE TITLE
Question: how to get 1st intersected element

### ISSUE THREAD

**Issue by dhivehi** [Turfjs/turf#1048]
Given a straight line passing though some polygons, is there any turf function to find the 1st crossed (intersected) polygon?

**Comment by rowanwins** [comment]
Hi @dhivehi 

There is nothing available at the moment unfortunantly, depending on the exact requirements you could possibly cycle through a feature collections with `turf/boolean-intersects`

**Comment by DenisCarriere** [comment]
@rowanwins `@turf/boolean-intersect` doesn't exist yet ;) lol

We could... add a custom property `intersectIndex` to each feature in the `FeatureCollection<Point>` when `@turf/line-intersect`.

**Comment by rowanwins** [comment]
[@turf/boolean-intersects](https://www.npmjs.com/package/@turf/boolean-intersects) is now available so that would be a good candidate for this.
