### ISSUE TITLE
turf.js errors when running in node

### ISSUE THREAD

**Issue by ErrorStuff** [Turfjs/turf#1049]
Hello and thankyou for the awesome engine!

when i try to run the example from turf/turf-isobands i got several Errors:
This line: 
`var pointGrid = turf.pointGrid(extent, cellWidth, {units: 'miles'});`
throws this: "Error: units is invalid".

Changing it to 
`var pointGrid = turf.pointGrid(extent, cellWidth, 'miles');`
solves the issue. But when calling the turf.isobands() function the following Error occurs:

```
/srv/www/forecastmap/node_modules/grid-to-matrix/grid-to-matrix.js:1125
    if (!isObject(options)) throw new Error('options is invalid');
                            ^

Error: options is invalid
    at gridToMatrix (/srv/www/forecastmap/node_modules/grid-to-matrix/grid-to-matrix.js:1125:35)
    at module.exports (/srv/www/forecastmap/node_modules/@turf/isobands/index.js:63:18)
    at Object.<anonymous> (/srv/www/forecastmap/create_contours.js:64:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
```

I refer to this code: 
```
// create a grid of points with random z-values in their properties
var extent = [-70.823364, -33.553984, -69.823364, -32.553984];
var cellWidth = 5;
var pointGrid = turf.pointGrid(extent, cellWidth, {units: 'miles'});
for (var i = 0; i < pointGrid.features.length; i++) {
    pointGrid.features[i].properties.elevation = Math.random() * 10;
}
var breaks = [0, 5, 8.5];

var isobands = turf.isobands(pointGrid, breaks);
```
from [https://github.com/Turfjs/turf/tree/master/packages/turf-isobands](url)

Anything is working fine when i'am using turf.js in the browser. Other functions from turf are also working via node, i tried turf.intrpolate(), turf.isolines() and others. Maybe i'am doing something wrong with Node.js what I never used before. I tried these requirement-statments:
```
var turf = require('@turf/turf');
or 
var turf_interpolate = require('@turf/interpolate');
var turf_isobands = require('@turf/isobands');
var turf_pointGrid = require('@turf/point-grid');
 ```
I'am using node v.6.11.4, anything from turf in the newest version. I'am hunting this thing for while now and any help would be welcome. Thank you very much!

**Comment by rowanwins** [comment]
HI @ErrorStuff 

Unfortunately we're in an transition to v5 which see some syntax change, some modules have been changes and other have not. Fingers crossed this will all be resolved in the next week or so so please bare with us...

Cheers

**Comment by ErrorStuff** [comment]
Hi rowanwins and thanks for your reply. I assumed something like this, which is the reason why i started this issue. Is it possible to use an older version of turf? There are only two function i need to use, interpolate and isobands. 

thx

**Comment by rowanwins** [comment]
Depending on how you're incoporating turf you could either

In the browser you could target a specific version using npmcdn eg
`https://unpkg.com/@turf/turf@4.7.3/index.js`

or similar for installing a node pacakge you could do 
`npm install @turf/interpolate@4.7.3`

Hope that helps

**Comment by ErrorStuff** [comment]
Thanks man, one last wuestion. I want to use it via node but i'am not sure which version to use. The cangelog.md in the repo ends with 3.6.4. Can you suggest a version or should i just try?

**Comment by rowanwins** [comment]
I think v4.7.1 should be safe from any of the breaking changes so perhaps give that a whirl

**Comment by ErrorStuff** [comment]
I tried all versions listest by npm view @turf/isobands and the same error occurs. For version 4.5.2 and older the error is different: 

```
TypeError: Cannot read property 'commonProperties' of undefined
    at module.exports (/srv/www/forecastmap/node_modules/@turf/isobands/index.js:50:16)
    at PythonShell.<anonymous> (/srv/www/forecastmap/create_contours.js:25:20)
    at emitOne (events.js:96:13)
    at PythonShell.emit (events.js:188:7)
    at /srv/www/forecastmap/node_modules/python-shell/index.js:232:14
    at Array.forEach (native)
    at PythonShell.receive (/srv/www/forecastmap/node_modules/python-shell/index.js:231:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
Seems like I have to wait.

**Comment by DenisCarriere** [comment]
@ErrorStuff As for the changelog, we've been maintaining the new releases here:
https://github.com/Turfjs/turf/tree/master/releases

Also you can look at the new releases via the Issues:
https://github.com/Turfjs/turf/issues?q=is%3Aissue+label%3Arelease+is%3Aclosed

**Comment by DenisCarriere** [comment]
> Seems like I have to wait.

😢 Unfortunately we are in transition period, hopefully I can publish `v5.0` for all npm modules (except for `@turf/turf`).

**Comment by stebogit** [comment]
😢

**Comment by rowanwins** [comment]
This should now be resolved, let us know if you continue to have issues @ErrorStuff
