### ISSUE TITLE
Points/LineStrings/Polygons method proposal to @turf/helpers

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1061]
## Points/LineStrings/Polygons method proposal to `@turf/helpers`

When attempting to create FeatureCollections of Points or any Geometry it seemed like there was "too much" lines of code for this type of basic need. We use this type of syntax a lot in the JSDocs to define 3 points or 3 lines.

Pretty straightforward to use, it would act similar to `helpers.point()` except one Array higher by adding an `s` to all helper methods `helpers.points()` and the output will return a FeatureCollection of that Geometry type.

## Current syntax

```js
var pt1 = turf.point([0, 0]);
var pt2 = turf.point([0.5, 0.5]);
var pts = turf.featureCollection([pt1, pt2]);

// or...
var pts = turf.featureCollection([
  turf.point([0, 0]),
  turf.point([0.5, 0.5])
]);
```

## Proposed syntax

```js
var pts = turf.points([[0, 0], [0.5, 0.5]]);
```

## Votes

- 👍 @DenisCarriere 
- 👍 @stebogit

**Comment by stebogit** [comment]
@DenisCarriere great idea! 👏

**Comment by DenisCarriere** [comment]
Implemented

`multiPoints` could be added, however it's a bit of an overkill to implement those Multi Geometries.

**Comment by stebogit** [comment]
:+1:
