### ISSUE TITLE
[Question]Bezier curve returns wrong data 

### ISSUE THREAD

**Issue by StevanCakic** [Turfjs/turf#1063]
Hi,

I have a problem with returning the result for bezier curve function. 

PointFormat: [lng, lat] and for example for those points(this line) bezier function doesn't return correct result

StartP: [139.7731286197, 35.6669502038]
DestinationP: [-122.419, 37.7749]

When I call bezier(line, 10000, 1) I get this:
[139.7731286197, 35.6669502038]
[139.7723425676984, 35.66695652343349]
[139.76998650923062, 35.66697546547036]
[139.76606359060222, 35.66700700461521]
[139.7605769581187, 35.66705111557264]
[139.75352975808568, 35.66710777304726]
[139.74492513680866, 35.66717695174368]
[138.48703480246405, 35.67729003060642]
[138.4244584558949, 35.67779312655248]
[138.36044110138684, 35.678307807790624]
[137.94625200073224, 35.68163776981088]
[137.05472063017092, 35.688805427286994]
[136.96530315101077, 35.689524318269605]
...
[128.33440760076044, 35.75891425233037]
...
[115.45673422921544, 35.86244706661425]
...
[-122.30663913643279, 37.773996650762534]
[-122.32452221275746, 37.77414042558634]

So as you can see lng coords are decreased, but I want from bezier function to increase coords( go from the left to the right) and when it reaches 180, to change on -180, -179... to -122.32452221275746.

On image:
![image](https://user-images.githubusercontent.com/13205146/32222178-8d116224-be38-11e7-9e8d-df0c294e3394.png)

Bigger map:
![image](https://user-images.githubusercontent.com/13205146/32222478-b533be0e-be39-11e7-824e-2328e581b4c2.png)

I want something like this:
![image](https://user-images.githubusercontent.com/13205146/32222230-be2da6a6-be38-11e7-9230-d9a2c5277758.png)

Is there a problem because the line must go to "another map" (go through -180 lng to destination)?

This is also a general question. When I just try to draw simple line that exceeds lng (>180) route goes to different direction (longer) and in that case, all lng coords are in [-180, 180] interval

Maybe this is something with Mapbox? Maybe to extend bounds? Did anyone have the same issue? Any suggestions?

**Comment by DenisCarriere** [comment]
This is mostly an issue with the GeoJSON specification and you'd have to "hack" your way around the 180th Meridian, @tmcw explains the issue well in his blog ["More than you ever wanted to know about GeoJSON"](https://macwright.org/2015/03/23/geojson-second-bite#the-180th-meridian).

Have you tried defining your input with +180 longitudes, example:

-219.375
- **StartP**: `[139.7731286197, 35.6669502038]`
- **DestinationP**: `[237.581, 37.7749]`

> Note Longitude of US `destinationP` is 237.581 Degrees

**Comment by StevanCakic** [comment]
Yea, this works, so cool. Thanks a lot
