### ISSUE TITLE
# ❌ 👎 Extend `@turf/helpers` `featureCollection` proposal

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1065]
# ❌ 👎 Extend `@turf/helpers` `featureCollection` proposal

Noticed this handy method from `@turf/point-on-surface` which converts any GeoJSON `FeatureCollection`, `Feature` or `Geometry` => `FeatureCollection`.

This should be simple enough to extend the existing `featureCollection()` method from `@turf/helpers` to support this.

## Source Code

```js
/**
 * Normalizes any GeoJSON to a FeatureCollection
 *
 * @name normalize
 * @param {GeoJSON} geojson Any GeoJSON
 * @returns {FeatureCollection} FeatureCollection
 */
function normalize(geojson) {
    if (geojson.type !== 'FeatureCollection') {
        if (geojson.type !== 'Feature') {
            return featureCollection([feature(geojson)]);
        }
        return featureCollection([geojson]);
    }
    return geojson;
}
```

**Comment by rowanwins** [comment]
Could we simply extend the existing `featureCollection` method to accept geometries rather than creating a new method? 
Can still kinda see the benefit of this method although not sure I'd call it `normalize` as that has some statistical conotations, perhaps `standardize` might be better...?

**Comment by DenisCarriere** [comment]
Actually extending the `featureCollection` sounds like a better idea.

I guess the 3 valid inputs would be `Feature` | `FeatureCollection` | `Geometry` given in the Array.

**Comment by stebogit** [comment]
Cool! :+1:

**Comment by DenisCarriere** [comment]
Also this won't "break" any backwards compatibility, just extending it.

**Comment by DenisCarriere** [comment]
This won't be implemented this since this would require the `featureCollection()` method to iterate over each item in the Array to detect if it's a Feature or a FeatureCollection.

❌ 👎 This will never get implemented.
