### ISSUE TITLE
point-grid not accepting units as option

### ISSUE THREAD

**Issue by ssdhaliwal** [Turfjs/turf#1070]
var boxExtent = [mapExtent.bounds.southWest.lon, mapExtent.bounds.southWest.lat,
    mapExtent.bounds.northEast.lon, mapExtent.bounds.northEast.lat];
  var cellSide = 200;
  var options = {units: 'miles'};

  var bboxPoints = turf.pointGrid(boxExtent, cellSide, options); 

 when above statement is executed; following error is received Error: units is invalid  turf.min.js:1:13886; 

don't see the package point-grid causing this issue since it is passing options to distance(...).

**Comment by DenisCarriere** [comment]
Unfortunately we haven't published the newest `v5.0` build with the options param to `@turf/turf` (web bundle).

At the moment I'm pushing out the v5.0 for all the grid modules, try again in an hour or so.

**Comment by ssdhaliwal** [comment]
thanks for update; another item - i am working on it; point-grid does not work when co-ordinates cross meridian.  should i track and work on this as a separate issue?

**Comment by DenisCarriere** [comment]
> point-grid does not work when co-ordinates cross anti-meridian. should i track and work on this as a separate issue?

A separate issue would be good for that new topic. 👍

**Comment by DenisCarriere** [comment]
v5.0 has been published, point-grid should now accept units as options.
