### ISSUE TITLE
Testing v5.0 Web ES5 Bundle before release

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1073]
## Testing v5.0 Web ES5 Bundle before release

I've made some progress on bundling the entire `@turf/turf` library using only Browserify (since all dependencies are pure ES5).

The current bundle was created using the `master` branch and I'd be ready to publish the newest release once a few other people have confirmed it works on their end.

## Browserify + Uglify

The Web bundle is the same as v4.0, so we shouldn't have any big issues.

```bash
$ browserify main.js -s turf -o turf.js
$ uglifyjs turf.js -m -c -o turf.min.js
```
Browserify doesn't support ES6 (not easily), but using the Rollup CommonJS `main.js` file does a fairly good job. The new bundle is actually smaller than the previous v4.0 release by about 100KB (total size 748KB).

## Download [`turf.js`](https://gist.githubusercontent.com/DenisCarriere/06c4ff5c4a5d776db88a4d5f4a50b82b/raw/9f1419c15ce4f402930cb8743c6ce3c00b750b49/turf.js) or [`turf.min.js`](https://gist.githubusercontent.com/DenisCarriere/06c4ff5c4a5d776db88a4d5f4a50b82b/raw/9f1419c15ce4f402930cb8743c6ce3c00b750b49/turf.min.js)

I published the web bundles to Gist, please provide some feedback if the bundles don't work for you.

Or build them yourself on the `master` branch using the following:

```
$ cd ./packages/turf/
$ lerna bootstrap
$ npm run build
```

## Outstanding issues (to be fixed after v5.0 release)

- Rollup still isn't properly working with `jsts`, the bundle size is 4x bigger using Rollup since `jsts` isn't written in pure ES6 and Rollup has issues with the Tree Shaking thus creating new instances of `jsts` for each modules that depend on it (it's a total nightmare at the moment).

CC: @rowanwins @stebogit @tmcw @morganherlocker

**Comment by rowanwins** [comment]
Thanks @DenisCarriere , I'll take a look at this over the weekend and try and test it with the new docs. Sounds like it's been a prickly one to navigate (although it wouldn't be fun if it was too easy!).

**Comment by DenisCarriere** [comment]
👍 Thanks @rowanwins It's definitely been prickly, but I think we've cracked it now (finally 😓).

**Comment by rowanwins** [comment]
Woot woot - looking good from my testing so far!

**Comment by DenisCarriere** [comment]
👍 Sweet! Ok I'll push out the full `v5.0` release whenever I have 2-3 hours free, that way if all hell breaks I have some time to fix it right away.

Thanks @rowanwins for looking into this.
