### ISSUE TITLE
lineSplit seems unable to handle splitter points with nearly the same longitude

### ISSUE THREAD

**Issue by haoliangyu** [Turfjs/turf#1075]
I run into an edge case where two points with nearly the same longitude breaks `lineSplit()` (in turf v4.7.3). The coordinates are collected via GPS and the longitude difference is only 0.000001. You can see the geometry in this [Gist](https://gist.github.com/anonymous/eb6cced53f090033e11db9485d823aec).

When I try to split a line with these two points,

``` javascript
var turf = require('@turf/turf');

var line = turf.lineString([[-87.168433, 37.946093], [-87.168510, 37.960085]]);
var splitter = turf.multiPoint([[-87.168446, 37.947929], [-87.168445, 37.948301]]);
var split = turf.lineSplit(line, splitter);
```

they break `lineSplit()` and throw an error.

``` bash
/home/turf_test/node_modules/@turf/line-split/index.js:92
            results = results.filter(function (feature) { return feature.id !== closestLine.id; });
                                                                                           ^

TypeError: Cannot read property 'id' of undefined
    at /home/turf_test/node_modules/@turf/line-split/index.js:92:92
    at Array.filter (<anonymous>)
    at /home/turf_test/node_modules/@turf/line-split/index.js:92:31
    at featureEach (/home/turf_test/node_modules/@turf/meta/index.es5.js:358:13)
    at splitLineWithPoints (/home/turf_test/node_modules/@turf/line-split/index.js:73:5)
    at Object.module.exports [as lineSplit] (/home/turf_test/node_modules/@turf/line-split/index.js:52:16)
    at Object.<anonymous> (/home/turf_test/index.js:5:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
```

The problem is likely caused by the difference in the last decimal. It will work if I drop the 6th decimal or change the number to enlarge the difference. But I am not sure whether that is the correct way to avoid or fix the problem.

**Comment by DenisCarriere** [comment]
@haoliangyu See PR https://github.com/Turfjs/turf/pull/1078

**Comment by DenisCarriere** [comment]
This definitely caused some issue 👍 thanks for reporting this.

**Comment by haoliangyu** [comment]
@DenisCarriere Thanks for the quick fix!

In your PR, moving the point on the line is mentioned as a fixture. Can I consider it as a reliable way to avoid this issue for now and use `turf.pointOnLine()` to process the splitter beforehand?

**Comment by DenisCarriere** [comment]
> use turf.pointOnLine() to process the splitter beforehand?

👍 Yep that might be a good idea to use as the splitter since the `lineSplit` is fairly strict for position. Most of the applications do "snapping" which causes the point or cursor to snap on the line which then makes the splitter point exactly on the line.

Going to close this issue, however feel free to re-open or submit more fixtures that are failing.
