### ISSUE TITLE
coordEach indexing bug

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#1092]
I noticed this evening that when using `coordEach` that it doesn't really deal with holes properly.

So for example I pass in a poly with a hole like
````
[ [ [ 100, 0 ], [ 101, 0 ], [ 101, 1 ], [ 100, 1 ], [ 100, 0 ] ],
  [ [ 100.2, 0.2 ], [ 100.8, 0.2 ], [ 100.8, 0.8 ],[ 100.2, 0.8 ],[ 100.2, 0.2 ] ]
]
````
if I do something like
```js
    coordEach(poly, function (currentCoord, currentIndex, featureIndex, featureSubIndex) {
        console.log(currentCoord)
        console.log(currentIndex, featureIndex, featureSubIndex)
```
I get 
````
[ 100, 0 ]
0 0 0
[ 101, 0 ]
1 0 0
[ 101, 1 ]
2 0 0
[ 100, 1 ]
3 0 0
[ 100.2, 0.2 ]
4 0 0
````
So the hole get's the same featureIndex and featureSubIndex as the rest of the poly which means I can't detect that the coord belongs to a hole.

Would be great to add some polys with holes to the test fixtures to those `meta` modules.

**Comment by DenisCarriere** [comment]
👍 Agreed, I've added a 3rd index (`geometryIndex`) which indicates the index when iterating over the geometry (used in Polygon & MultiPolygon geometries).

There are 3 major index tiers which are broken down like so:
-  `featureIndex` => `multiFeatureIndex` => `geometryIndex`

Using those 3 indexes you should be able to find your way back to the exact geometry part of the feature.

```js
turf.coordEach(features, function (currentCoord, coordIndex, featureIndex, multiFeatureIndex, geometryIndex) {
  //=currentCoord
  //=coordIndex
  //=featureIndex
  //=multiFeatureIndex
  //=geometryIndex
});
```

@rowanwins Have a go at it and let me know if you are having any issues with the new update.

**Comment by rowanwins** [comment]
Thanks @DenisCarriere yeah I thought we meet need a new level. I'll try and get smooth close off this weekend which enable me to test it

**Comment by DenisCarriere** [comment]
👍 Sounds like a plan!

I think the NEXT major release we can re-organize those optional indexes using an Object.

Something like this =>

```js
coordEach(features, (currentCoord, indexes) => {
  //=currentCoord
  //=indexes.coordIndex
  //=indexes.featureIndex
  //=indexes.multiFeatureIndex
  //=indexes.geometryIndex
});
```

Which allows to do some cool deconstructing like this =>

```js
coordEach(features, (currentCoord, {geometryIndex}) => {
  //=currentCoord
  //=geometryIndex
})
```

This would allow us to retrieve any index without "guessing" the parameter position.

**Comment by rowanwins** [comment]
Unfortunantly we haven't quite nailed this for multipolygons with holes
eg input like
````
  { "type": "MultiPolygon",
    "coordinates": [
      [[[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]],
      [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
       [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]]
      ]
    }
````

leads to 
````
console.log(currentCoord, coordIndex, featureIndex, multiFeatureIndex, geometryIndex)

[ 102, 2 ] 0 0 0 0
[ 103, 2 ] 1 0 0 0
[ 103, 3 ] 2 0 0 0
[ 102, 3 ] 3 0 0 0
[ 100, 0 ] 4 0 1 0
[ 101, 0 ] 5 0 1 0
[ 101, 1 ] 6 0 1 0
[ 100, 1 ] 7 0 1 0
[ 100.2, 0.2 ] 8 0 1 0  <- Im a hole and so my geometryIndex should be equalling 1
````

**Comment by DenisCarriere** [comment]
@rowanwins Here's a breakdown of what the Indexes "should" look like for a MultiPolygon using `meta.coordEach()`:

```js
const multiPolyWithHole = multiPolygon([
    // MultiPolygon - FeatureIndex => 0
    // Polygon - MultiFeature Index => 0
    [
        // Outer Ring - Geometry Index => 0
        // Coord Index => [0, 1, 2, 3, 4] (Major Release Change v6.x)
        [[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]
    ],
    // Polygon with Hole - MultiFeature Index => 1
    [
        // Outer Ring - Geometry Index => 0
        // Coord Index => [0, 1, 2, 3, 4] (Major Release Change v6.x)
        [[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
        // Inner Ring - Geometry Index => 1
        // Coord Index => [0, 1, 2, 3, 4] (Major Release Change v6.x)
        [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]
    ]
]);
```

**Comment by DenisCarriere** [comment]
Patched in `v5.1.6` release

**Comment by rowanwins** [comment]
Thanks @DenisCarriere ! Every time I work with polys/multipolys/withholes I've been reminded how painful it is to cater for them, I reckon these fixes will make it far easier!

**Comment by DenisCarriere** [comment]
I know.. Handling Polygons with holes is brutal! Don't hesitate to test the other `@turf/meta` modules, we can do another big revamp at the next major release to make it easier to work with by returning Objects in the callbacks.
