### ISSUE TITLE
How to cite sources for various equations, etc?

### ISSUE THREAD

**Issue by muziejus** [Turfjs/turf#1104]
The modules I'm working on now demand (in my opinion) some kind of reference to the scholarly literature from which they emerged. This is I think useful both as a justification for why a module uses the equations it does and also as a point of interest for GIS students who might, like me, be attracted to turf because of its flexibility, freeness, and so on, but who also want to know more of where these ideas came from.

This feels like it should go in every module's README, but I get the sense that those READMEs are supposed to be quick and to the point, without a short bibliography at the end, say.

The issue is also a bit more relevant now because @DenisCarriere (and I?) has/have decided that `@turf/center-mean` will ignore weights that are <= 0. This is in line with how Esri measures the mean center in ArcMap, but _unlike_ how qGIS does it. I don't know…

**Comment by DenisCarriere** [comment]
@muziejus Great topic, most of the TurfJS descriptions are pretty straight forward for simplicity, however you can always add more documentation & citations if you decide to include it.

For example [`@turf/tin`](https://github.com/Turfjs/turf/blob/master/packages/turf-tin/index.js#L5-L14) has 7 lines of code dedicated in the description with a Wikipedia link for more reading.

Feel free to add as much documentation & citations as possible 👍

**Comment by muziejus** [comment]
Super. I looked at the tags for JSDoc and it looks like I could do something like:

```
For more on the standard deviational ellipse, @see {@link http://www.jstor.org/stable/490885|Yuill 1971, “The Standard Deviational Ellipse; An Updated Tool for Spatial Description.”}
```

**Comment by DenisCarriere** [comment]
👍 Sounds good to me!

**Comment by rowanwins** [comment]
Another alternative here might be to use the `@see` [tag ](http://usejsdoc.org/tags-see.html)in jsdocs, then we could put those references somewhere outside of the main description, for instance, in a modal or something? 

The main benefit I can see in this would be that we can split out the really technical references which limited ppl are probably interested in, from the general description (which is probably what most ppl want). Just another way to reducing cognitive overload in the docs.

**Comment by smallsaucepan** [comment]
Closing this issue with the intent to start using @see in JSDocs and update turf-www to render any new content appropriately.
