### ISSUE TITLE
@turf/nearest-point null property bug

### ISSUE THREAD

**Issue by jasonbellis** [Turfjs/turf#1106]
When the target featureCollection of points is being read, once the properties are examined the module fails when it reads a null input. It tries to check the length of the property and getting the length of a null value is not valid in Javascript.

The bug is quite easy to recreate bug with firing nearestPoint in version 5.0.4 with a featureCollection that contains a null property. Bug does exist in version 4.7.3.

[I built a JSFiddle of the bug here.](https://jsfiddle.net/Stooky/u6qcg205/7/)

**Comment by muziejus** [comment]
Repeat of #1095

The problem is how objects are handled in @turf/clone.

**Comment by DenisCarriere** [comment]
👍 @muziejus so this will be fixed in the next 5.1 release?

Would it be possible to add this as a simple test case that way we don't have it recreate the same error in the future.

**Comment by muziejus** [comment]
I put in a test for this here:

https://github.com/Turfjs/turf/commit/5dc6adb3ff36ddc241185c2c5f14999712b39614#diff-acc3e3b43263911ab3da2ec0e06e72bc

**Comment by DenisCarriere** [comment]
Didn't even notice that test 👍 Great job @muziejus

**Comment by muziejus** [comment]
I've added the null test on `@turf/nearest-point` now, too, but it seems… overkill? (it also fails because I'm not using future turf)

**Comment by DenisCarriere** [comment]
🤔 ... when you are using "new" features from the master branch you'll need to sync the repo using `lerna bootstrap`, that sync modules to the latest build.
