### ISSUE TITLE
How to use future turf?

### ISSUE THREAD

**Issue by muziejus** [Turfjs/turf#1110]
This is a straightforward question, I think, but I'm still new. I'd like to build a turf that is based on the current state of `master` so I can test a new feature that has other features that aren't released yet (like `@turf/ellipse`) as dependencies. 

When I tried running the lerna command in the contributing documentation, it made it look like it was pushing something to github so I freaked out and canceled.

But even so, features like `@turf/ellipse` aren't listed in `/packages/turf/`, so, if I understand correctly, they won't get built anyway.

I'll gladly follow a link to a tutorial on this, but I'm not even really sure what to google for.

Thanks! 🎉

**Comment by DenisCarriere** [comment]
😛 Yea... The docs are a bit lacking for creating new modules in Turf.

Before importing new modules between modules, I first need to publish them to `@turf`.

Afterwards you can import them like any other repo and then sync them from the master branch using `lerna bootstrap` (which syncs all repo using the master branch and NOT the actual npm release).

Let me publish your new modules and you'll understand it a bit more when you use `lerna bootstrap`.

**Comment by muziejus** [comment]
@DenisCarriere Thanks. I'll read up a bit more on lerna and follow the commits you're making to master to see how it all ties together.

**Comment by DenisCarriere** [comment]
👍 Don't hesitate to ask questions on the Turf Issues, folks are typically pretty responsive (you might of noticed by now).
