### ISSUE TITLE
Buffer is not passing steps options to jsts

### ISSUE THREAD

**Issue by ffflabs** [Turfjs/turf#1112]
As seen in

https://github.com/Turfjs/turf/blob/f8fe4c1c7d463a3ae49782419ba5d8d96fb74142/packages/turf-buffer/index.js#L115

The buffer is always called as

```js
var buffered = BufferOp.bufferOp(geom, distance);
```

Whereas the `steps` parameter should be passed as a third parameter:

```js
var buffered = BufferOp.bufferOp(geom, distance, steps);
```

Otherwise, the buffer will assume the `DEFAULT_QUADRANT_SEGMENTS` as steps, which are 8.

https://github.com/bjornharrtell/jsts/blob/1.4.0/src/org/locationtech/jts/operation/buffer/BufferParameters.js#L3

(I don't know where to find the source code for `jsts-es` so I'm just guessing it's pretty similar to the link above.

**Comment by geirsagberg** [comment]
Might I suggest that an eventual fix to this should also change the default steps from 64 to 8, to match the current behavior?

**Comment by shelbeniskb** [comment]
please fix 
`var buffered = BufferOp.bufferOp(geom, distance);`
to
`var buffered = BufferOp.bufferOp(geom, distance, steps);`

**Comment by SimonChatillon** [comment]
Please fix this and also add the endCapStyle option for the fourth parameter of the bufferOp call.
