### ISSUE TITLE
Unnecesary dependencies brought along with jsts-es

### ISSUE THREAD

**Issue by ffflabs** [Turfjs/turf#1114]
In modules `@turf/buffer`, `@turf/difference`, `@turf/intersect` and `@turf/union`, modules from  `jsts-es` are imported from the main module. E.g. in turf buffer:

```js
import { BufferOp, GeoJSONReader, GeoJSONWriter } from 'jsts-es';
```

It turns out that in `jsts-es/index.js`, when every submodule is exported

```js
export * from './src/org/locationtech/jts/geom'
export * from './src/org/locationtech/jts/algorithm'
export * from './src/org/locationtech/jts/densify'
export * from './src/org/locationtech/jts/dissolve'
export * from './src/org/locationtech/jts/geomgraph'
export * from './src/org/locationtech/jts/index'
export * from './src/org/locationtech/jts/io'
export * from './src/org/locationtech/jts/noding'
export * from './src/org/locationtech/jts/operation'
export * from './src/org/locationtech/jts/precision'
export * from './src/org/locationtech/jts/simplify'
export * from './src/org/locationtech/jts/triangulate'
export * from './src/org/locationtech/jts/linearref'
```

there are side effects that result in the whole (or most part) of `jsts-es` being brought along the required modules.

If I build `@turf/buffer` using rollup to ES6 module output, the final size is **898K** and the module includes (for example), JSTS definitions for classes (to name a few) `DouglasPeuckerLineSimplifier`,  `MonoValentEndPointBoundaryNodeRule`, `ConformingDelaunayTriangulationBuilder`, and many more that are not used at all by the Buffering operation.

If I instead require the modules directly as:

```js
import GeoJSONReader from 'jsts-es/src/org/locationtech/jts/io/GeoJSONReader.js';
import GeoJSONWriter from 'jsts-es/src/org/locationtech/jts/io/GeoJSONWriter.js';
import {
    BufferOp
} from 'jsts-es/src/org/locationtech/jts/operation/buffer.js';
```

The bundle size drops to **515Kb**

Now, I don't know if this is due to my `rollup.config.js` being misconfigured, But I'm pretty convinced this is because JSTS structure is somehow breaking Rollup's tree shaking.

**Comment by DenisCarriere** [comment]
JSTS has big problems when making it ES Module & CJS compatible.

The other major issue I found was the `extend()` method that JSTS uses copies the entire section of that source code. For example if we have 4 Turf modules that use JSTS, that means we will have 4x GeoJSONReader source code in the final Rollup bundle.

To solve this, I've been working on refactoring JSTS for the sole purpose of importing it in TurfJS.

https://github.com/DenisCarriere/turf-jsts

Once it's complete I'll replace the `jsts-es` module with that new code base.

**Comment by amenadiel** [comment]
That's good news.

**Comment by bjornharrtell** [comment]
@DenisCarriere your remark about extend seems surprising and unexpected to me. AFAIK I don't get that duplication when bundling as ES5 with rollup and babel.

**Comment by bjornharrtell** [comment]
As a side note, as I hope you know JSTS is transpiled Java. At one point I did actually transpile to ES6 classes instead of functions like it is now, but it actually had two drawbacks - it could not properly emulate the class inheritance from Java, and it added a significant negative performance hit when transpiled to ES5 (due to emulation of ES6 classes). If one would want an ES6 target, it might make sense to use classes where it works. My point is, that and other things can be done by adjusting the transpiler instead of manually refactoring the transpiled source.

**Comment by DenisCarriere** [comment]
@bjornharrtell That's because you're bundling in the same library, whenever multiple modules use `jsts` then that's when the duplicating starts.

I can look into it again, but removing `extend.js` from `jsts` solved the issue.

**Comment by DenisCarriere** [comment]
> adjusting the transpiler instead of manually refactoring the transpiled source.

Agreed! I'm never doing this manually 😄 However it got me familiar with the code base.

**Comment by mfedderly** [comment]
We're on turf-jsts at this point, going to close this ticket out.
