### ISSUE TITLE
New function `@turf/helpers.to180degreesRange`

### ISSUE THREAD

**Issue by jameslaneconkling** [Turfjs/turf#1124]
When calculating the midpoint between two points near the antimeridian, the output longitude is often greater than 180 or less than -180.  See [js fiddle](https://jsfiddle.net/jameslaneconkling/x9ugvp5w/).

```javascript
console.log(turf.midpoint([-178, 0], [176, 0]));

{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [
      -181,
      1.8361309540878913e-16
    ]
  }
}
```

A check to wrap longitudes would be pretty easy:

```javascript
  if (coordinates[0] > 180) {
    coordinates[0] = coordinates[0] % 180 - 180;
  } else if (coordinates[0] < -180) {
    coordinates[0] = coordinates[0] % 180 + 180;
  }
```

Can submit a PR if this is desired behavior.

**Comment by DenisCarriere** [comment]
👍 It would definitely be a useful module to convert all coordinates back within 180 degrees.

I've written a similar library that addressed this issue, you might want to have a look at the source code to handle the longitude: 
https://github.com/DenisCarriere/bbox-dateline/blob/master/index.js#L117-L137

Handling the latitude isn't much of an issue since +90 degrees isn't a valid coordinate.

This new module could be called `@turf/antimeridian` which would convert any GeoJSON's coordinates within 180 degrees.

> Please don't hesitate to propose a more "clever" module name if you have a better name for this module.

**Comment by DenisCarriere** [comment]
⚠️  This should not be added directly to `@turf/midpoint` since most of the web map applications do support coordinates greater than 180+ degrees, this could be published as it's own separate module and/or be an option to enable on/off that feature in `@turf/midpoint`

**Comment by stebogit** [comment]
@jameslaneconkling @DenisCarriere why not just add a method to `@turf/helpers`?

**Comment by DenisCarriere** [comment]
👍 Yep! `@turf/helpers` might be a good place for it, we could call it `helpers.antimeridian` ? or something else?

**Comment by stebogit** [comment]
What about `helpers.to180degreesRange`?

**Comment by DenisCarriere** [comment]
👍 That's not a bad name

@jameslaneconkling Any creative names you've got for this proposed method?

**Comment by jameslaneconkling** [comment]
In my current project I've called it `wrapOnAntimeridian`--not sure if that's more or less descriptive.

**Comment by DenisCarriere** [comment]
🤣 Agreed, it's not an easy method name.

**Comment by jameslaneconkling** [comment]
Took a first pass at this [here](https://github.com/jameslaneconkling/turf/blob/feature/to-180-degree-range/packages/turf-to180_degree_range/index.js).

Is this looking like something that's headed in the right direction?

Presumably, this is something that should be able to handle other features besides Points, yeah?

**Comment by stebogit** [comment]
@jameslaneconkling the code looks fine 👍 
I don't see this really applicable for anything else then a point; I would probably return an output consistent with the input, i.e. array -> array, point -> point, geometry -> geometry.
However, shouldn't this be a `@turf/helpers` function? In this case you should remove the module dependencies in there.

P.S. I'd change the title of this issue to like "new function proposal".

**Comment by diachedelic** [comment]
@DenisCarriere does having a longitude outside of -180/+180 violate the spec for WGS84, and hence GeoJSON?

**Comment by lukas-h** [comment]
@diachedelic As I understood, WGS 84does not define your coordinate boundaries, so GeoJSON doesn’t either. So it’s up to you and your project, what you want to use.

Mapbox geocoding APIs for example enforce the meridian/antimeridian boundaries.

**Comment by smallsaucepan** [comment]
Fairly sure [helpers/azimuthToBearing](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/README.md#azimuthtobearing) meets this need. Please reopen if not!

@jameslaneconkling @shreyas-jadhav @diachedelic @lukas-h
