### ISSUE TITLE
Document new ES6 Chrome import viability

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1126]
## ✅ Partial TurfJS modules work directly in Chrome

```js
<script type='module'>
  import { point } from "https://unpkg.com/@turf/helpers?module"
  console.log(point([1, 2]));
</script>
```

This works, in Chrome 61+!

Thanks @tmcw for the heads up! 👍 https://github.com/simple-statistics/simple-statistics/issues/263

## ❌  Current issues

- [x] `@turf/isolines` is making it crash when trying to import `@turf/turf`
- [x] `jsts-es` is also crashing
- [x] `turf-jsts` Drop `index.js` & `index` folders from repo, seems to be crashing the module import process.

> Might have to do JSTS's no-standard ES6 syntax (will attempt to replace `jsts-es` with `turf-jsts` to see if the problem persists)

**Comment by tmcw** [comment]
Though it costs some upgrade churn, documenting versioned URLs usually pays off by avoiding version breakage down the line - `https://unpkg.com/@turf/helpers?module` will redirect to `https://unpkg.com/@turf@9.0.0/helpers?module` when that day comes, and breaking changes will automatically enter into applications that don't expect them.

**Comment by DenisCarriere** [comment]
👍 That's true, good point, there has been quite a few breaking changes in the recent major release.

**Comment by DenisCarriere** [comment]
Using ES Modules directly in the browser works now 🎉 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>ES Modules</title>
  </head>
  <body>
  <script type='module'>
    import {point, greatCircle} from "https://unpkg.com/@turf/turf?module"

    console.log(greatCircle([0, 0], [100, 10]));
    console.log(point([100, 0]));
  </script>
  </body>
</html>
```
