### ISSUE TITLE
Document the differences between the 4 (5?) diff. `center*` functions

### ISSUE THREAD

**Issue by muziejus** [Turfjs/turf#1128]
@stebogit Brings up a good point that we now have a confusing set of four (or five) different measures for "center." This may make perfect sense to geographers, but is probably opaque to non-geographers. (I mean, I'm still not 100% on understanding `@turf/center-of-mass`!)

I've drafted some boilerplate language that can go in the READMEs for all of them. See #1122 and its README for that draft. It's just the beginning, however. I also think I could/should draft an infographic that shows what influences each calculation. The idea would be to include the infographic in all of the center functions' pages on the web documentation and/or in their READMEs?

**Comment by DenisCarriere** [comment]
> I also think I could/should draft an infographic that shows what influences each calculation. The idea would be to include the infographic in all of the center functions' pages on the web documentation and/or in their READMEs?

That's a great idea! 🎉 We should start including at least 1 infographic image for some modules which isn't a Map, sometimes it's hard to explain with a map and a graphic is much easier to represent conceptually what the module is intended to do.

👍

**Comment by muziejus** [comment]
![artboard 1](https://user-images.githubusercontent.com/827683/33585310-9596d15e-d931-11e7-901e-18f40a2b8cd7.png)

I created a draft diagram showing the four different center functions in turf. It turns out `@turf/centroid` behaves exactly as `@turf/center-mean` does, but the latter allows for weighting. I don't know if this diagram makes things any clearer, but maybe...

**Comment by DenisCarriere** [comment]
Holy moly! 🚀 That's a cool diagram! I'd say we can start adding images to each individual modules in the `images/*.(png|jpg)` folder, I have no issues adding the same diagram to each `@turf/center-*` module, we can make unique ones later down the road.

More about this in this https://github.com/Turfjs/turf/issues/1140#issuecomment-348132574

**Comment by rowanwins** [comment]
Before we do too many I'll try and come up with a rough style guide that fits with the Turf website, would be nice to have them looking vaguely consistent.

**Comment by stebogit** [comment]
Super cool @muziejus! 👏 👏 

> nice to have them looking vaguely consistent

Absolutely right @rowanwins! 👍 

Perhaps it could be useful keeping the "originating" drawing file (.psd, .pdn, google drawing or whatever) with layers and stuff, so we could improve/edit/update them if ever needed; otherwise it might become a problem in the future to use a picture if we ever change anything in the relative module.

**Comment by DenisCarriere** [comment]
>  be useful keeping also the "originating" drawing file (.psd, .pdn, google drawing or whatever)

Agreed! At the moment we can publish `.gif` / `.png` / `.jpg` and the other file formats will not be published since they won't have those file extensions.

Adding a diagram should be as easy as dropping an image in a folder and firing off `npm run docs`, no extra configurations needed (which is the current implementation https://github.com/Turfjs/turf/pull/1152)

**Comment by muziejus** [comment]
My idea was to create a multi-artboard file in Illustrator, where very graphic is its own artboard. Then styles can be unified, etc., over the project as a whole and updated appropriately. Then Illustrator can export each artboard separately as its own svg. This would conceivably break the "each module has its own images directory" rule, but it may be possible for travis to copy each svg to its appropriate location inside the module on commits or something?

**Comment by rowanwins** [comment]
Only downside I see with this is that Adobe Illustrator costs money and many contributors might not have access to it :(  I was thinking [Inkscape](https://inkscape.org/) although this obviously looses the ability to have unified styles. That said I think we need to be too fussy about styling, it would be nice if they were vaguely consistent but not the end of the world

**Comment by stebogit** [comment]
👍  I was just writing the same @rowanwins, cause I don't have Illustrator 😅 🤣 

Anyway I'd keep it simple, don't know how many JS programmers are also designers, and vice versa...

**Comment by muziejus** [comment]
Right. That was my concern, too. I'm lucky regarding access to software, I know. I'll have a look at inkscape; it should provide similar functionality, no?

**Comment by muziejus** [comment]
@rowanwins inconsistent styling just means a particularly picky contributor 🤔 will just go through the already existing graphics and provide them w/ visual consistency. That's why a drawing program might be best--no changes are permanent, etc.

**Comment by DenisCarriere** [comment]
As long as we can all easily modify and re-use the diagrams I'm ok with it.

@muziejus Is there a way you can create a Diagram with illustrator and also export it into a format that Inkscape or free online image editors such as [Pixlr](https://pixlr.com/editor/)

I personally use Google Drawings, MS PowerPoint, Keynote Presentation & Pixlr for making "doodles", however I wouldn't know which file format that would be best to share Multi-Artboard like you were mentioning.

👍 @muziejus Feel free to include Illustrator files in combination of exporting an additional image format that is compatible with most Open-Source editors.

**Comment by muziejus** [comment]
Move discussion to #1154.
