### ISSUE TITLE
Setting up OpenCollective for TurfJS contributors & community

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1143]
## Setting up ~Patreon~  OpenCollective for TurfJS contributors & community

CC: @Turfjs/ownership 

**Edited: 2017-11-30**

To help continue the growth & development of TurfJS which many volunteers have contributed countless amounts of hours improving this amazing & easy to use Open-Source Geospatial Analysis library for today's modern GIS Web developers using Javascript & the GeoJSON specification.

**Reason for Funding**

TurfJS is entirely community driven, which means there is no corporate entity directly funding any of the hours that any of the TurfJS contributors are devoting to improving this library.

**Goals**

Many of the active TurfJS contributors have full-time jobs & families to take care of, for those individuals that work after 10pm or on weekends to slowly improve this library is remarkable and inspirational. For large Patron donations & monthly subscribers, your funding will go directly to pay for one of the core TurfJS developers to "take a day off" of their day job and work entirely on TurfJS.

Secondly, the small amounts of funding will help build our TurfJS "Swag" collection which will increase over time as more and more Patrons sign up. Currently we have Stickers to share back to the community thanks to @morganherlocker & @DenisCarriere. The next swag item would be to create a TurfJS T-Shirt to share with all your friends, who knows what the next goal would be! 🚀

## First Tier (Point)

> We send you a premium TurfJS Sticker!

- [ ] Creating a Sticker Design (@DenisCarrier covered $57.75 on Fiver)
- [ ] Printing of Stickers (@morganherlocker covered the **?** cost)
- [ ] Sending stickers via mail (@morganherlocker covered the **?** cost)
- [ ] [Group Discussion of Logo Design](https://github.com/Turfjs/turf-www/issues/116)

## Voting 👍 / 👎 

If any one would oppose to us (TurfJS contributors & community) creating a Patreon account & promoting it, please indicate the reasons and your name to the list of voters (I've added contributors with +6 months of contributions to the list which all need to be unanimously 👍).

- 👍 @DenisCarriere
- 🤺 @rowanwins (a fencer for 'sitting on the fence')
- ❓ @tmcw 
- ❓ @morganherlocker 
- 👍 @stebogit 

### https://www.patreon.com/turfjs

**Comment by stebogit** [comment]
I aim for the T-shirt!!! 😃

**Comment by DenisCarriere** [comment]
👍 Me too!! I need some clothes to wear at work! 😛

**Comment by rowanwins** [comment]
I reckon aim higher, I think we should be aiming for funding work on this project. T-shirts are nice and all but I'd rather some of us are financially remunerated for the time that we put into this project in terms of maintenance, improvement and support etc.

I think most people presume Mapbox are doing most of the work around Turf, unfortunately that hasn't been the case for quite a while now (they are always welcome to get more involved of course!).

I for one would love it if I could take a couple of days off my normal job a month to work on Turf rather than having to do stuff at 10pm once I've worked a full day at work, been dad and husband as well as fulfilled other various life commitments. 

I also think we'd get more traction on a patreon campaign if people saw it was funding development and maintenance rather than swag. If I was supporting it I'd prefer my money going to a good cause rather than aiding @DenisCarriere tshirt collection :)

So I'm all for it, but I think funding swag is a bit lame and would rather see us collecting funds to support contributors.

**Comment by DenisCarriere** [comment]
Upon @rowanwins's comments:

Made some adjustments to add some higher tiered subscriptions which would essentially be used to help fund hired days for some of the core developers.

**200$/mo**
- 1x day paid for a TurfJS core developer!

**1000$/mo**
- 5x days paid for TurfJS core developer(s)!

**Comment by tcql** [comment]
👋 hey friends!

I know I haven't been active in Turf development for awhile, but I just wanted to drop my thoughts.

I think funding the project is a great idea. Y'all deserve some pay for the hard work and the ability to feel comfy taking time out of your regular jobs to do this. Patreon is a good enough platform for doing that. There's also Liberapay that works similarly, although fewer people know about it, so I'd expect less support there. Maybe do a combo approach and have more than one funding option.

My advice here would be to look for other software projects on Patreon/Kickstarter/whatever else for ideas on how to structure the page, how to set up the support tiers, and whether you want to do any other small rewards for backers. 

I found a few doing a cursory search:

- https://www.patreon.com/ubuntu_mate
- https://www.patreon.com/elementary
- https://www.patreon.com/photonstorm

**Comment by tmcw** [comment]
Hi! A few thoughts:

- **In general**, this sounds like a great idea, and I'm in support of it.
- **Not to bikeshed the site that we'd use** but [OpenCollective](https://opencollective.com/) has a bit more traction in OSS projects and more explicit systems for how people doing work can charge for their time and leadership can change. [webpack](https://opencollective.com/discover) is the top project, with 200k+/mo in funding.
- **Paying for people taking a day off**: does this mean literally taking a day off of work and taking a PTO/vacation day? For people whose jobs tolerate just working on an OSS project for a day - like mine did at Mapbox and probably would still at Observable - that would not be reimbursed, right?
- The thing about people thinking Mapbox is funding Turf might be hard to shake with [the cross-branding](https://www.mapbox.com/analysis/) - you'd need to reiterate it in the Medium post or wherever the funding appeal is initially published.

**Comment by DenisCarriere** [comment]
Thanks for sharing your insights @tmcw 

I really like how webpack structured their funding strategy. Looks like a better approach for larger organizations to be able to sponsor TurfJS and also have the ability for individuals to become backers (2$/mo).

https://opencollective.com/webpack

I will switch the crowdfunding approach to [Open Collective](https://opencollective.com/)

**Comment by stebogit** [comment]
That's very interesting, thanks @tmcw!

**Comment by stebogit** [comment]
I still want the T-shirt though... ahahah! 🤣

**Comment by DenisCarriere** [comment]
T-Shirt is still happening! We need to settle on a logo design for that since it's a bit of a bigger expense than stickers.

**Comment by DenisCarriere** [comment]
Set up OpenCollective contributing platform.

https://opencollective.com/turf
