### ISSUE TITLE
@turf/simplify - freeze window

### ISSUE THREAD

**Issue by dabajabaza** [Turfjs/turf#1144]
Just notice that **turf/simplify** freeze browser window in Google Chrome and Firefox (but not in IE11) if parameter **options** is undefined.

Tested in 

1. Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) 
2. Firefox Quantum 57.0
3. Internet Explorer 11

In [this example](https://codepen.io/ckpunmep/pen/LOBwVj?editors=1010) I comment out a freeze causing line.

**Comment by DenisCarriere** [comment]
Thanks @dabajabaza for reporting this issue & creating a web map example, this behavior has now stopped in `v5.1.x`.
