### ISSUE TITLE
docs#featureCollection

### ISSUE THREAD

**Issue by Spown** [Turfjs/turf#1146]
http://turfjs.org/docs#featureCollection: link to http://turfjs.org/Feature doesn't go nowhere, link to  FeatureCollection goes to this page (http://geojson.org/geojson-spec.html#feature-collection-objects) with bugged nav and "Obsolete" in the title.

Thank you

**Comment by rowanwins** [comment]
Thanks for reporting this @Spown . Unfortunately the geojson.org page seems a bit broken at the moment, not sure what's going on there...

**Comment by Spown** [comment]
http://turfjs.org/docs#clustersDbscan and here the supposed wikipedia link goes back to turfjs.org. I think it'S common problem with links in docs

**Comment by Spown** [comment]
``degreesToRadians`` nav menu item is broken - causes ``TypeError: _vm.module is undefined`` and doesn't load docs

![](https://drive.google.com/uc?id=1xA1YFM8N_7AUV4CcsUgg_yCCsc4pPgsV)

**Comment by rowanwins** [comment]
Thanks @Spown

**Comment by DenisCarriere** [comment]
👍 Thanks @Spown for reporting this, this is now fixed in the updated website.
