### ISSUE TITLE
Polygon centreline module

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#1151]
Came across this article the other day and thought it would be neat to have a polygon centreline module
http://itc.ktu.lt/index.php/ITC/article/view/12964/8078

The other commonly used approach apparently is based around Voronoi triangles, see example here
https://smathermather.com/2011/09/16/what-is-the-center-line-of-a-polygon-or-how-to-change-labeling-in-geoserver/

**Comment by DenisCarriere** [comment]
👍 The Voronoi approach might be the easiest to implement since we've already got `@turf/voronoi`.

After you've created your centre line from Polygon, one would want to simplify the line, we could elaborate a bit more on our `@turf/simplify` modules (ref: https://github.com/Turfjs/turf/issues/1085).

**Comment by rowanwins** [comment]
Note that the blog post for the Voronoi approach also has a few other articles about the subject. And if you google 'voronoi polygon centreline' you find a stack of things. It looks like this is the approach GRASS GIS takes https://grass.osgeo.org/grass72/manuals/v.voronoi.html

**Comment by JulesBlm** [comment]
I've been experimenting with making such functionality using d3-voronoi to some succes. I've adapted this [Observable by Noah Veltman on centerline labelling](https://observablehq.com/@veltman/centerline-labeling) to convert the centerline to a geoJSON LineString using turf.js. Here's my Observable: [https://observablehq.com/@julesblm/centerlines-from-geojson-polygon](https://observablehq.com/@julesblm/centerlines-from-geojson-polygon). It usually needs > 1000 points on the polygon perimeter to make a correct centerline, which makes it slow.

I've also been trying to replace d3-voronoi with the much faster d3-delaunay to less succes ([Centerlines from GeoJSON Polygon with d3-delaunay](https://observablehq.com/@julesblm/clean-centerlines)). 

Given the 2 and a half years of silence on this issue, it doesn't seem like this a much requested feature but still, I welcome any suggestions or ideas!

**Comment by smallsaucepan** [comment]
Been another few years without any movement on this, so closing for the time being. Please reopen if still of interest.
