### ISSUE TITLE
http://turfjs.org/ unusable in Firefox 56.0.2

### ISSUE THREAD

**Issue by sedot42** [Turfjs/turf#1155]
Hi, just wanted to let you know that the "Welcome to Turf.js" overlay on http://turfjs.org/ is in the wrong position so that I can't search use the documentation, see the screenshot. I am using Firefox 56.0.2. The issue does not occur in Chromium 62.0.3202.94.

![turfhomepage](https://user-images.githubusercontent.com/8765349/33656381-2ebbf5ea-da76-11e7-9858-ac751b768ab6.png)

**Comment by rowanwins** [comment]
Thanks for the report @sedot42 , appears to be across every browser except Chrome :(

**Comment by rowanwins** [comment]
Resolved by [this pull request](https://github.com/Turfjs/turf-www/pull/133)
