### ISSUE TITLE
Getting fill property not supported on IE11

### ISSUE THREAD

**Issue by estradamarkie** [Turfjs/turf#1157]
Hi,

I'm getting this error on IE11 using https://npmcdn.com/@turf/turf@5.0.4/turf.min.js

> Object doesn't support property or method 'fill'

Just wondering if this issue has been sorted for IE11 or anyone else is having this issue?

Thanks

**Comment by DenisCarriere** [comment]
🤔 ... I believe the `v5.0` isn't being compiled with Babel, it's using Browserify + Uglify to compile the final bundle.

@estradamarkie Can you try to pinpoint which module is causing this, we've got LOTS of dependencies and sub-modules.

Next release will 100% be compiled with Babel, so maybe we just have to wait out until the next release to have this fixed.

**Comment by DenisCarriere** [comment]
@estradamarkie You are correct that `Array.fill` is not supported by IE 11

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

Of course, our lovely `JSTS` repo has this 😓 ...
https://github.com/DenisCarriere/turf-jsts/search?utf8=%E2%9C%93&q=fill&type=

**Comment by estradamarkie** [comment]
@DenisCarriere Yeah `Array.fill()` is not compatible with IE, thought this would have been seen by other people who's using turf.js. 

Guessing this will be a major bug for the plugin? Are we expecting a fix soon?

**Comment by DenisCarriere** [comment]
Well `v5.0` wasn't using Babel to compile, I assumed that all dependencies didn't use any Polyfills.

By compiling the next minor release with Babel this "should" fix this.

**Comment by DenisCarriere** [comment]
Hopefully we won't have to include this Polyfill

https://github.com/bjornharrtell/jsts/blob/master/src/Array.js

**Comment by rowanwins** [comment]
Or maybe, just maybe, perhaps Martinez will be ready!

**Comment by DenisCarriere** [comment]
lol indeed! We can make that a major release, it's going to take sometime to get that released, I'm sure we will have few bugs to fix before we swap out JSTS for Martinez

**Comment by estradamarkie** [comment]
Is there a work-around for now while waiting for the official fix?

**Comment by DenisCarriere** [comment]
You can include the following Polyfills in your code before importing Turf.

- [Array.js](https://github.com/bjornharrtell/jsts/blob/master/src/Array.js)
- [Math.js](https://github.com/bjornharrtell/jsts/blob/master/src/Math.js)
- [Number.js](https://github.com/bjornharrtell/jsts/blob/master/src/Number.js)

The fix should be available soon, I'll try to push a release tonight (🤞 nothing goes wrong at publishing)

**Comment by DenisCarriere** [comment]
The Polyfills are now added in `v5.1`

https://npmcdn.com/@turf/turf@5.1.0/turf.min.js

This should be working again

**Comment by kuan-hsun** [comment]
Hello,

I also encountered the same problem in **IE11** and sloved it by using https://npmcdn.com/@turf/turf@5.1.6/turf.min.js.

But I'm getting the error on

>Object doesn't support property or method 'assign' 

I was fixed it by added the if statement from [here](https://stackoverflow.com/questions/35215360/getting-error-object-doesnt-support-property-or-method-assign) in the local file turf.js:


Thank you
