### ISSUE TITLE
@turf/turf/index.d.ts

### ISSUE THREAD

**Issue by Spown** [Turfjs/turf#1163]
Last seen in @5.0.4. Was this intentional/Where is it now?

**Comment by DenisCarriere** [comment]
Strange... 🤔 I guess it doesn't play well with Symbolic links.

https://github.com/Turfjs/turf/blob/master/packages/turf/index.d.ts

Good catch

**Comment by DenisCarriere** [comment]
@Spown Fixed in the latest release `v5.1.5`.

https://unpkg.com/@turf/turf@5.1.5/
