### ISSUE TITLE
"/main.mjs" returned instead of expected turf function on require (Webpack)

### ISSUE THREAD

**Issue by neil-morrison44** [Turfjs/turf#1165]
In my code (which is compiled via webpack) I have the line
```coffee
TurfPointsWithinPolygon = require("@turf/points-within-polygon").default
```
which was working on 5.0.4, but is broken in 5.1.0 as `require("@turf/points-within-polygon")` now returns the string `"/main.mjs"`

Most likely related to https://github.com/Turfjs/turf/commit/481dd5d5b652a47e33352f9b2abe74c56903574d

**Comment by contra** [comment]
I think I'm also hitting the same issue after upgrading to 5.1.0 - broke our production build with this error:

```
ERROR in components/charts/GeoJSON-aecf1eca03627deb802f.js from UglifyJs
Unexpected token: punc (,) [components/charts/GeoJSON-aecf1eca03627deb802f.js:74131,61]
```

Nothing changed other than upgrading turf, so almost 1000% sure

**Comment by DenisCarriere** [comment]
@contra @neil-morrison44 Try using the latest release `v5.1.5` which is now using `main.es.js` for `"module"` (PR https://github.com/Turfjs/turf/pull/1166)

Please don't hesitate to re-open this issue if the error persists.
