### ISSUE TITLE
pointGrid fails with multi-polygon mask (5.1.6)

### ISSUE THREAD

**Issue by jpoynton** [Turfjs/turf#1169]
Docs and validation for pointGrid state that can pass a multi-polygon as a mask, however multi-polygon fails as pointGrid relies on boolean-within to check if the point is within the mask. Boolean-within does not accept multi-polygon as valid input.

Simple recreation follow

```js
var multiPoly = turf.multiPolygon([
  [
    [
      [0, 50],
      [0, 10],
      [10, 10],
      [10, 0],
      [0, 0]
    ]
  ]
]);

var options = {
  units: 'miles',
  mask: multiPoly
}

var bbox = turf.bbox(multiPoly);
var pointGrid = turf.pointGrid(bbox, 50, options);
```

**Comment by DenisCarriere** [comment]
Thanks @jpoynton for reporting this, this is definitely a bug, should be relatively easy to fix so this can be patched soon.

**Comment by DenisCarriere** [comment]
@rowanwins This PR https://github.com/Turfjs/turf/pull/1171 should help do the trick.
