### ISSUE TITLE
⚠️ Publishing *.mjs file extension for "module" - TurfJS v6.0

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1170]
### ⚠️ Breaking Change - Major Release v6.x

To prevent any older Webpack configurations from being accidentally  broken, the `v5.x` release currently uses `*.js` file extension to publish `"module"`. In the next TurfJS major release, the pre-compiled `"module"` file extension will be using `*.mjs` which has already landed in Webpack 4 (https://github.com/webpack/webpack/issues/5686).

Ref: https://github.com/Turfjs/turf/issues/1165 & https://github.com/Turfjs/turf/issues/1133

**Comment by mfedderly** [comment]
We'll actually be sticking with .js for compatibility purposes.

**Comment by DenisCarriere** [comment]
Agreed, best use `.js`
