### ISSUE TITLE
New module proposal @turf/angle

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1172]
## New module proposal `@turf/angle`

A  module to find a specific angle between 3 points

```js
/**
 * Finds the angle between 3 points.
 *
 * @param {Coord} startPoint Start Point Coordinates
 * @param {Coord} midPoint Mid Point Coordinates
 * @param {Coord} endPoint End Point Coordinates
 * @return {number} angle
 * @example
 * turf.angle([5, 5], [5, 6], [3, 4])
 * //=45
 */
export default function angle (startPoint, midPoint, endPoint) {
```

**Comment by rowanwins** [comment]
ooo this would be handy, I've found myself doing things like this a bit with things like lineOffset.

**Comment by stebogit** [comment]
Nice suggestion @DenisCarriere 👍 
We could also replace [these lines](https://github.com/Turfjs/turf/blob/master/packages/turf-point-to-line-distance/index.js#L82-L84) with this new module.

**Comment by DenisCarriere** [comment]
👍 Perfect! I'll add this module, I've already got the implementation and the tests ready to go.

**Comment by DenisCarriere** [comment]
Implemented
