### ISSUE TITLE
error union polygon

### ISSUE THREAD

**Issue by Nikolya85** [Turfjs/turf#1178]
```
var polygons_data = [
[[[-150.46681563135994,-1.439821242368066],[-153.61494141185997,2.3379296942319727],[-151.8279192046993,0.19350304563917356],[-150.46681563135994,-1.439821242368066]]],
[[[-168.293895,0.815157],[-151.8456612595276,0.2147935114331218],[-159.178835,-0.599073],[-168.293895,0.815157]]]
];
var polygons = [];
for (var i=0; i<polygons_data.length; i++) {	
  polygons.push(turf.polygon(polygons_data[i]));  
}
console.log(turf.union(polygons[0], polygons[1]));
```

```
uncaught exception: TopologyException: found non-noded intersection between LINESTRING ( -150.46681563135994 -1.439821242368066, -151.8456612595276 0.21479351143312128 ) and LINESTRING ( -151.8456612595276 0.21479351143312186, -151.8279192046993 0.19350304563917356 )
```

[example](https://jsfiddle.net/nikolya/p9b3vtm5/11/).

**Comment by rowanwins** [comment]
Thanks for the use case @Nikolya85 - hmm those are interesting geometries. Our union function is currently provided by the jsts library which is known to struggle with edge cases. We're currently working on replacing this dependency so I'll use these inputs in my testing. 

Thanks

**Comment by Nikolya85** [comment]
Another mistake:
```TopologyException: no outgoing dirEdge found```

[example here](https://jsfiddle.net/nikolya/p9b3vtm5/14/)

if for example take a polygon from 0 to 10 and 60 to end positions:
```polygons.splice(10,60);```
then the error is repeated
```found non-noded intersection between LINESTRING```

**Comment by tmcw** [comment]
Closing; #88 is the tracking issue for JSTS.
