### ISSUE TITLE
id == 0 option ignored. 

### ISSUE THREAD

**Issue by Spown** [Turfjs/turf#1180]
``turf.point([1,2], {}, {id: 0})`` doesn't seem to apply id.

![](https://drive.google.com/uc?id=1DdpiivfT67cIMssV7zJ7cfAa4Buq1z8z)

I deduce there is simple troothy/falsy check (ie ``!options.id``) in place before the id application.

**Comment by stebogit** [comment]
Thanks @Spown, I created PR #1184 for this

**Comment by stebogit** [comment]
Fixed with #1184
