### ISSUE TITLE
@turf/turf/index.d.ts doesn't produce any intellisense.

### ISSUE THREAD

**Issue by Spown** [Turfjs/turf#1181]
turf@5.1.6

![](https://drive.google.com/uc?id=1Q9ZMk1E0chdA0kzZDxGHys015mQF_sR1)

I use the d.ts file in my pure js, browser-side script, via ``/// <reference path="../../../node_modules/@turf/turf/index.d.ts" />`` to enable intellisense in VSCode. In @^4 it did work, then it stopped (#1163). but now, after the #1163 is resolved its just doesn't do anything, despite the d.ts file clearly being consumed by intellisense without any errors. I presume previously it would create a global ``turf`` var but now it only assumes requirejs/ts import.

![](https://drive.google.com/uc?id=1kOU16YmNS4D-v9T9JSh7xwQ9w8ZNNDEX)

**Comment by DenisCarriere** [comment]
🤔 that's weird... let me look into that one:

Turf has never used Globals for the TypeScript definition,

Seems to work using ES6 syntax.

![image](https://user-images.githubusercontent.com/550895/34087710-ea989d18-e372-11e7-947c-3d697213955d.png)


Also works using ES5 syntax.

![image](https://user-images.githubusercontent.com/550895/34087706-d980a656-e372-11e7-8c51-2f2f8744ad2b.png)

Even importing the module directly from `node_modules` works.

![image](https://user-images.githubusercontent.com/550895/34087796-6fca2e84-e373-11e7-9513-ca5afee26e03.png)

@Spown Going to close this issue unless you can provide some clarity on your issue or propose a solution with a fix.

**Comment by Spown** [comment]
Yeah, you kinda never did in the module itself. I forgot I was using ``@types/turf`` first, which was deprecated around @3.5. After installing it again I can use Intellisense on turf without any imports.
![](https://drive.google.com/uc?id=18K1vitsAXWmEeFQuW0bAcYJIVEcCHzUu)
But the API is very old of course.

I'm not really good at .ts so I probably can't help you much. Just look at [how it was done earlier](https://github.com/slavovojacek/adbrain-typescript-definitions/blob/master/turf/turf.d.ts) - maybe you can extract the part that enables it...

Probably it would be a good idea to separate commonjs/ts type definitions (for ``@turf/turf/turf.es.js``) from web-based (``@turf/turf/turf.js`` and ``@turf/turf/turf.min.js``)?
