### ISSUE TITLE
turf-polyToLineString

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#119]
convert a polygon to a linestring

**Comment by rowanwins** [comment]
Gday @morganherlocker 

I've had a first crack at this and posted my code in (this repo)[https://github.com/rowanwins/turf-polyToLineString].

It's my first time writing a node module or any sort of js tests so fingers crossed I'm roughly on the right track but happy to take any feedback...

Let me know if you're happy to accept this and what the next steps would be.

Cheers
Rowan

**Comment by rowanwins** [comment]
Now implemented
https://github.com/Turfjs/turf/pull/646
