### ISSUE TITLE
Feature request: Pull String feature for line strings

### ISSUE THREAD

**Issue by dhivehi** [Turfjs/turf#1198]
I think it would be nice to have pull string feature for lineString. 
Having such a module would also be helpful to produce a better result in `turf.shortestPath`
![gqn0s](https://user-images.githubusercontent.com/18715293/34324287-f748e4e8-e88e-11e7-9656-33f7f58bb835.png)

**Comment by DenisCarriere** [comment]
👍 Seems useful.

How exactly would this proposed module be used? @dhivehi Could you draft up a quick JSDocs of what the `@params` would look like.

**Comment by dhivehi** [comment]
How about `turf.pullString(lineString, polygonObstacles, {minDistance: distance})` 
and this should return the line string when it's being pulled, i.e the shortest line possible.

**Comment by DenisCarriere** [comment]
@dhivehi Why don't we we simply improve `@turf/shortest-path` with that functionality?

**Comment by stebogit** [comment]
> simply improve `@turf/shortest-path`

I agree. @dhivehi how would you use this module in a case where you don't have obstacles?

**Comment by dhivehi** [comment]
improving @turf/shortest-path is much better. In case of no obstacles, a straight line will be returned.

**Comment by rowanwins** [comment]
Think we can close this in favour of #1211 which Im slowly working on and keeping updated. Basically Im working towards creating a visibility grid from polygons which we can then feed into an a-star algorithm for use in our shortest-path algorithm.
