### ISSUE TITLE
@turf/invariant proposal methods (first & last => coord & segment)

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1202]
## ~`@turf/meta`~ `@turf/invariant` proposal methods

A few helpful methods would be useful to have in the [`@turf/invariant`](https://github.com/Turfjs/turf/tree/master/packages/turf-invariant) collection.

### Proposed new methods

- [x] `invariant.firstCoord`
> Retrieve the first `Coordinate` of the GeoJSON as an `Array<number>`
- [x] `invariant.lastCoord`
> Retrieve the last `Coordinate` of the GeoJSON as an `Array<number>`
- [ ] `invariant.firstSegment`
> Retrieve the first `Segment` of the GeoJSON as a 2 vertex `Feature<LineString>`
- [ ] `invariant.lastSegment`
> Retrieve the last `Segment` of the GeoJSON as a 2 vertex `Feature<LineString>`

### Example

```js
const line = lineString([[10, 10], [50, 30], [30, 40]]);

invariant.firstCoord(line) // => [10, 10]
invariant.lastCoord(line) // => [30, 40]
invariant.firstSegment(line) // => Feature<LineString<[[10, 10], [50, 30]]>>
invariant.lastSegment(line) // => Feature<LineString<[[50, 30], [30, 40]]>>
```

**Comment by DenisCarriere** [comment]
## 1. Change method names

Or keep the naming schema consistent with the other `@turf/meta` methods names.

- `meta.coordFirst(geojson)`
- `meta.coordLast(geojson)`
- `meta.segmentFirst(geojson)`
- `meta.segmentLast(geojson)`

## 2. Change method parent to `@turf/invariant`

Possibly these methods would be more appropriate under `@turf/invariant` since they don't perform any iterations, this would sync well with other invariant methods like `getCoord()` & `getCoords()`.

**Comment by stebogit** [comment]
@DenisCarriere I'm sure you found a use case for these modules but I can't think of one at the moment, particularly regarding getting the first point of the first line of a `MultiLine` 🤔 .
Anyway, trying to contribute to your idea, I'd create:
- `invariant.start` and `invariant.end`, applied only to lines returning the corresponding point
- `invariant.first` and `invariant.last`, applied to lines and multilines, returning the first/last segment or line
- `invariant.lat` and `invariant.long` only for points, returning the named coordinate

If we made them right we could probably chain them like:
```js
var latitude = invariant.lat(invariant.start(invariant.first(multiline))); 
```
Just some thoughts 😄

**Comment by stebogit** [comment]
`first` and `last` could probably be extended to polygons (returning a linearring), multipolygons (returning a polygon) and multipoints (returning a point, although I'm not sure if the 'first' or 'last' point here have a particular meaning)

**Comment by DenisCarriere** [comment]
My use case is to be able to easily extract the following geometry attributes of a particular LineString (highway):

- First Coord (first road intersection)
- Last Coord (last road intersection)
- First Segment (to calculate the bearing of the initial highway direction)

![image](https://user-images.githubusercontent.com/550895/34366247-18163f2a-ea67-11e7-8a17-30a2d3896696.png)

The other Geometry types are kinda awkward, but I included them to support all Geometries instead of only supporting LineString.

> `first` and `last` could probably be extended to polygons

Looks interesting, however the method names seem a bit too generic on how these would get implemented based on the different Geometry types, also remember that eventually these methods will be included in `@turf/turf` which will lose some of it's invariant context. I think `start` & `last` is a bit too generic as a method name.

> var latitude = invariant.lat(invariant.start(invariant.first(multiline))); 

Don't think we would need `.lat` or `.lng` as a method, since you can just explode the Array and define the variable to anything you'd like.

```js
const [lng, lat] = firstCoord(line);
```

**Comment by stebogit** [comment]
I like exploding arrays! 💥 👍 😄

**Comment by DenisCarriere** [comment]
Implemented `findPoint` & `findSegment`
