### ISSUE TITLE
Module/Method proposal makeIterable()

### ISSUE THREAD

**Issue by muziejus** [Turfjs/turf#1203]
@DenisCarriere's new proposals in #1202 spurred me into starting to write this module, but I'm not having a lot of luck, and I want to talk it over w/ you all because maybe I'm stepping on discussions that you've already had.

Simply put, I don't like `turf.featureEach()`. I wish there were a way to do something like:

```
featureCollection = turf.makeIterable(turf.points([[0, 0], ... ]));

var namesArray = featureCollection.map(function(f){ return f.properties.name;});
featureCollection.forEach(function(f){ f.properties.fillColor = "#aa0000"; });
if(featureCollection.length > 100){ console.log("you have a big data set!");};
```

IIRC, in python, as long as the object responds to two hidden methods, it exposes the object to all of the enumerable methods. It seems like ES6 has something similar w/ `Symbol.iterator`, if not quite as flexible.

My suggestion then, is having `turf.makeIterable()` add a bunch of methods to a feature collection so we can use them like arrays. I don't know if this is a terrible idea, but in writing my modules, I certainly wished feature collections had, at least, `map()` and `filter()` methods. I know turf provides `turf.featureReduce()` in addition to `turf.featureEach()`.

Or would attaching methods to geojson objects cause compatibility problems?

**Comment by DenisCarriere** [comment]
We be introducing a newer way to iterate over features using the new [ES6 `generators/iterators`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function%2A). We won't be creating a new module for that, but we will introduce new methods with that new methodology.

Nothing announced on the proposal side, but it will look something like this (adding `Gen` at the end of each meta method):

```js
const features = meta.featureEachGen(geojson);

console.log(features.next().value); // => Feature<any>
console.log(features.next().value); // => Feature<any>
```

> Or would attaching methods to geojson objects cause compatibility problems?

Yes it will cause some slight compatibility problems with Internet Explorer since that browser doesn't support `generators`, however using Rollup you can exclude these methods from being introduced in your bundles. We could also make an ES6 minified bundles with these new ES6 methods (as a transition period we would have `turf.es6.js` & `turf.js` as web bundles).

**Comment by DenisCarriere** [comment]
> add a bunch of methods to a feature collection so we can use them like arrays.

@muziejus Why don't you simply use the Array that's built into a FeatureCollection?

```js
const geojson = points([[10, 30], [45, 30]]);

//= geojson.features.map
//= geojson.features.reduce
//= geojson.features.filter
//= geojson.features.forEach
//= geojson.features.reduce
//= geojson.features.sort
```

The list goes on...

```
a.concat                a.copyWithin            a.entries
a.every                 a.fill                  a.filter
a.find                  a.findIndex             a.forEach
a.includes              a.indexOf               a.join
a.keys                  a.lastIndexOf           a.length
a.map                   a.pop                   a.push
a.reduce                a.reduceRight           a.reverse
a.shift                 a.slice                 a.some
a.sort                  a.splice                a.unshift
```

**Comment by DenisCarriere** [comment]
@muziejus One enhancement that you could improve on would be to extend the `helpers.featureCollection`'s input to include more different inputs (eg. FeatureCollection, Geometry). That way you can add all sorts of data and it would return a  GeoJSON Spec `FeatureCollection` which is an Array that you can perform all those operations.

**Comment by muziejus** [comment]
@DenisCarriere Thanks. There isn't a good reason why I prefer `geojson.map` to `geojson.features.map` other than saving typing… but it's just odd to me that conceptually a "feature collection" is, y'know, a _collection_, not an object per se, but that takes us out of the realm of geojson.

Thanks for the suggestion. I'm still behind on the graphics task, but I'll have a look at `helpers.featureCollection`, too.

**Comment by rowanwins** [comment]
-1 from me sorry @muziejus although I understand the sentiment. I don't think we should be tinkering with the geojson object given that it is a recognised spec, it's a smidge unintuitive but not really that bad.

**Comment by muziejus** [comment]
Cheers, @rowanwins. I realized while typing out the issue that it was maybe overly idiosyncratic. While trying test cases w/ `Symbol.iterator`, I saw that the geojson was getting polluted w/ a new property.

**Comment by DenisCarriere** [comment]
The intention was good with `Symbol.iterator`, however we won't be tinkering with the GeoJSON object.

However we will be eventually adding iterators (apparently it will speed things up), I'll open a dedicated issue for just that.

Closing this issue.
