### ISSUE TITLE
turf is not defined (got this inside angular js framework application running on localhost)

### ISSUE THREAD

**Issue by ahmedshahab** [Turfjs/turf#1206]
Hi everyone,

I am building a model building extension of turf js. i.e. adding a new functionality(module) in turfjs. For that inside turf js library, I am accessing the existing turf functions e.g. buffer, intersect etc. by "turf.buffer(...)" , "turf.intersect(...)" etc. It works fine. But when I try to run it inside angular js application running on localhost. I get error inside turf js where I am accessing those turf functions by calling turf.buffer(). It says turf is not defined. Can someone kindly help me with that?

Thanks

**Comment by DenisCarriere** [comment]
@ahmedshahab Can you provide some sample code of the TurfJS section.

Sounds like your issue is with your AngularJS environment and not TurfJS itself.

Going to close issue for now unless there's an actual issue with TurfJS.

**Comment by ahmedshahab** [comment]
[turfjs_model_builiding_module.txt](https://github.com/Turfjs/turf/files/1589958/turfjs_model_builiding_module.txt)
![image](https://user-images.githubusercontent.com/32779767/34394673-1b6edbc4-eb5b-11e7-83e2-ccda1fa11a7b.png)
