### ISSUE TITLE
SquareGrid lower then bbox

### ISSUE THREAD

**Issue by winsento** [Turfjs/turf#1214]
SquareGrid lower then bbox:

- GeoJSON data [gist file](https://gist.github.com/anonymous/9069b251b6a883d9084854767a7a277a).
- Example [jsfiddle](http://jsfiddle.net/winsent/bh8mdefx/).

![image](https://user-images.githubusercontent.com/2316328/34667683-1d1c3812-f47b-11e7-911f-865c312ed1ac.png)

**Comment by rowanwins** [comment]
What exactly is the question @winsento ?

**Comment by winsento** [comment]
@rowanwins  Why  squareGrid lower then bbox?

**Comment by rowanwins** [comment]
`turf/square-grid` calculates how many cells will fit in your bbox according to the cell size that you pass, if it doesnt fit exactly then it centers things accordingly. 

If you want them to align exactly I'd suggest calculating the width of your bounding box first, and then adjusting the cell size accordingly.

Hope that helps

**Comment by winsento** [comment]
@rowanwins Yes, that helps. Thank you.

**Comment by stefanocudini** [comment]
hi,

I have the same problem and I find this behavior strange!

but would it be possible to pass the count of cells for each side instead of the size in kilometers/miles?
it should be a parameter that makes more sense

**Comment by mfnash** [comment]
Hi,
I have already calculate the width and height of bbox that must be fit with cell size, but the result is not.

![image](https://github.com/Turfjs/turf/assets/80686776/c2a41596-f236-4021-b9d6-1a89191a978d)

with this bbox, the grid can contain 10 columns and 3 rows, but the result is 9 columns and 2 rows (and the grid centered). 
how to solve this ?
