### ISSUE TITLE
SquareGrid mask does not filter correctly

### ISSUE THREAD

**Issue by winsento** [Turfjs/turf#1215]
SquareGrid mask does not filter correctly (see example and screenshot). If set a cell size larger - then everything is ok.

- GeoJSON data [gist file](https://gist.github.com/anonymous/9069b251b6a883d9084854767a7a277a).
- Example [jsfiddle](http://jsfiddle.net/winsent/bh8mdefx/14/).

![image](https://user-images.githubusercontent.com/2316328/34669313-0e40e9da-f482-11e7-8c48-5f14ff2654b6.png)

**Comment by rowanwins** [comment]
Hmm thats interesting, thanks for the test case @winsento , we'll do some digging and see if we can see whats going on.

**Comment by rowanwins** [comment]
grrr really need `turf/boolean-intersects` right about now, add it to the to-do list :)

**Comment by milafrerichs** [comment]
have the same issue. using a cellSize of `0.01`

<img width="741" alt="bildschirmfoto 2018-01-26 um 15 25 18" src="https://user-images.githubusercontent.com/688980/35443970-35bb7456-02ad-11e8-93ff-ad3428c957ef.png">

`0.02` seems to be working fine. 
<img width="641" alt="bildschirmfoto 2018-01-26 um 15 28 41" src="https://user-images.githubusercontent.com/688980/35444143-df04b96e-02ad-11e8-8818-fe6df006e5ed.png">

I tried to do it on my own using `turf.intersect` and got the same issue.

**Comment by winsento** [comment]
@milafrerichs i think this PR fix it https://github.com/Turfjs/turf/pull/1231

**Comment by DenisCarriere** [comment]
> i think this PR fix it #1231

This will most likely fix it, we don't have an expected timeline when those PR's will be merged and published in the next minor/major release.

**Comment by bribrah** [comment]
This is still an issue in latest version of turf
