### ISSUE TITLE
losing precision on cleanCoords results in invalid polygons

### ISSUE THREAD

**Issue by divya1c** [Turfjs/turf#1217]
Hi! 

I am trying to use cleanCoords while creating my polygon to avoid duplicate coordinates and I am running into issues. cleanCoords seems to be taking 2 as its precision. Is it possible for me to increase the precision of the cleanCoords operation or is there some other way I can clean my coordinates?  

Here's my polygon's coordinates: 
[-95.69222580565636, 29.62573526217787]
[-95.69222580565636, 29.62573526217787]
[-95.6918407231434, 29.62573526217787]
[-95.69145564062339, 29.62573526217787]
[-95.68991531056452, 29.62573526217787]
[-95.68798989799271, 29.62573526217787]
[-95.69222580565636, 29.62573526217787]

The reason I need cleanCoords is that I do a simplify and unkink later on the same polygon geometry and I want to avoid errors due to duplicate coordinates in these operations.

**Comment by rowanwins** [comment]
Hmm thats a bit unexpected, @stebogit might be able to provide a bit more info as to what is happening...

**Comment by stebogit** [comment]
@divya1c @rowanwins `@turf/clean-coords` does not alter the coordinates, it just compares the points and filters them if necessary.
I don't see any issue with the example:
https://jsfiddle.net/jStefano/bzqbm1e9/

Maybe something else is causing the issue. @divya1c you want to share more of your code so we can take a look?

**Comment by divya1c** [comment]
hi @stebogit thank you for the reply. i thought cleanCoords removes only duplicate coordinates. I understand now that it removes all unnecessary coordinates if its a linear geom. 
I assume that since its a polygon, many of the operations need the polygon to have atleast 4 coordinates. So, if I simplify it, operations like unkinkPolygon throw errors.
For example, in your jfiddle, if I run 
```
turf.unkinkPolygon(turf.cleanCoords({"type": "Feature","properties": {},"geometry": {"type": "Polygon","coordinates": [[
[-95.69222580565636,29.62573526217787],[-95.69222580565636,29.62573526217787],[-95.6918407231434,29.62573526217787],[-95.69145564062339,29.62573526217787],[-95.68991531056452,29.62573526217787],[-95.68798989799271,29.62573526217787],[-95.69222580565636,29.62573526217787]
]]}}));
``` 
It throws me an error:
```
turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1 Uncaught Error: Each LinearRing of a Polygon must have 4 or more Positions.
    at o (turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1)
    at Ls (turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1)
    at turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1
    at turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1
    at A (turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1)
    at F (turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1)
    at Object.t.unkinkPolygon (turf.min.self-361b6293e2b7c4e461b394bda34aa5a25e1e44d07d3b93b24ce26a6cbb9c3e4f.js?body=1:1)
    at <anonymous>:1:21
```
How can I avoid this? 

For more context, I have an application in which the user can free draw polygons, which means the user can also just draw a line which i convert into a polygon by linking the first and the last coordinates. I need to unkink the polygons inorder to use intersect. And inorder to unkink, I need to make sure the polygon doesn't have duplicate coordinates which I thought cleanCoords can help with.

**Comment by stebogit** [comment]
I believe a line can/should not be converted to a polygon like you do, therefore it should be treated as a special case, or forbidden; maybe you could require at least 3 points not all on the same line (you could use `@turf/point-on-line` to check) to be drawn by the user.

Even if there is no specific mention to this case in [the specs](https://tools.ietf.org/html/rfc7946#section-3.1.6), it says:
> A linear ring is the boundary of a surface or the boundary of a hole in a surface.

Now [a line has no area](https://github.com/Turfjs/turf/blob/master/packages/turf-area/index.js#L46-L50), so technically does not surround a surface, thus if converted (here by just renaming it) to a polygon would generate an invalid GeoJson.
It's like a segment with two identical points, I would say it's not a valid GeoJson [line](https://tools.ietf.org/html/rfc7946#section-3.1.4).

@DenisCarriere @rowanwins what do you think?

**Comment by DenisCarriere** [comment]
That's a head scratcher for sure, I support @stebogit 's comment by saying it would not be a valid GeoJSON LineString, definitely a special case to convert from Ring to LineString.

**Comment by erikh2000** [comment]
Another thought, @divya1c, do you need to call cleanCoords() on the geometry passed to unkinkPolygon()? Maybe an algorithm that works is run unkinkPolygon() and then call cleanCoords() on the returned polygons with a catch block. If an individual polygon throws inside of cleanCoords() with the error you described, just discard its geometry from consideration. My rationale is that if that polygon has less than 4 points, then it has no area to depict anyhow.

**Comment by divya1c** [comment]
thanks for all the comments @stebogit @DenisCarriere @erikh2000. My use case is that i get an intersection between the free draw polygon that is drawn by the user and an underlying layer. So, i can't really ignore the line that is drawn. I will have to show the user the underlying layer polygon that intersects with the line. And my product spec restricts me from forbidding the user from drawing a line.
I will try making a really small buffer to my line that may make it into a very thin polygon. Please do let me know if there's a better way to handle this case.

**Comment by rowanwins** [comment]
Hi @divya1c & @stebogit 

I've just pushed a new update #1260 to cleanCoords which will ensure that a cleaned polygon still has 4 coords (eg the minimum number of coords for a valid poly) otherwise it'll throw an error.

Do we still need this issue or can we close it?
