### ISSUE TITLE
How can I start isolines

### ISSUE THREAD

**Issue by guananny2** [Turfjs/turf#1219]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

![default](https://user-images.githubusercontent.com/22285339/34722444-ec32e874-f581-11e7-9f8e-a92223391171.png)
How can I use isolines ? I want to use isolines on the map ,but there is no demo i can use, do you has any simple example that I can get startted?

**Comment by DenisCarriere** [comment]
@guananny2 Thanks for the comment, `@turf/isolines` is a little tricky to use with custom data.

Here's the example that's listed using `@turf/point-grid`.

```js
// create a grid of points with random z-values in their properties
var extent = [0, 30, 20, 50];
var cellWidth = 100;
var pointGrid = turf.pointGrid(extent, cellWidth, {units: 'miles'});

for (var i = 0; i < pointGrid.features.length; i++) {
    pointGrid.features[i].properties.temperature = Math.random() * 10;
}
var breaks = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

var lines = turf.isolines(pointGrid, breaks, {zProperty: 'temperature'});
```

**Comment by guananny2** [comment]
Thanks for your reply~
I use the fiirst way to get start,but the firebug print the error log as "TypeError: turf.bbox is not a function"
what's wrong with me?
![default](https://user-images.githubusercontent.com/22285339/34768032-b14b8154-f634-11e7-8a3c-6235de9ab58a.png)

![default](https://user-images.githubusercontent.com/22285339/34768385-a4c6d216-f635-11e7-8776-4381a04acfd6.png)

**Comment by DenisCarriere** [comment]
@guananny2 You need to keep your Javascript code in the same code block.

```html
<script src="https://npmcnd.com/@turf/turf/turf.min.js">
  var bbox = turf.bbox(features);
</script>
```

**Comment by xiwangzhigu** [comment]
There are accuracy issues when using my own real data,i have random point pairs with longitude, latitude and value,do you have any idea or do you have any example of real data with this isolines method?

**Comment by stebogit** [comment]
@xiwangzhigu it's probably easier if you post an example of the issue you are having so we can take a look at it and see what's going on
