### ISSUE TITLE
@turf/difference throws error when removing a 'perfect fit' multipolygon from polygon

### ISSUE THREAD

**Issue by mfogel** [Turfjs/turf#1224]
It appears that when subtracting a multipolygon from a polygon, if one of the polygons of the multipolygon matches exactly, a `TopologyException: no outgoing dirEdge found`  will be thrown.

Here's a JS fiddle demonstrating the issue: https://jsfiddle.net/0t3oa3f1/3/

**Comment by rowanwins** [comment]
Hi @mfogel 

Yeah unfortunantly the difference module is currently provided by `jsts` which is known to have a range of issues. We're close-ish to replacing that dependency so hopefully we'll get there soon 🤞

**Comment by rowanwins** [comment]
Partially resolved since v6.2.0, now using polygon-clipping library, although the result returns null
