### ISSUE TITLE
Feature Request: Calculate area of circle and ellipse

### ISSUE THREAD

**Issue by jfuehner** [Turfjs/turf#1228]
Would love to have the ability to calculate the area of a circle and ellipse just as you can with polygons getting the results back in kilometers, meters, etc.

Thanks!

**Comment by stebogit** [comment]
@jfuehner did you try to use [`@turf/area`](https://github.com/Turfjs/turf/tree/master/packages/turf-area) and it didn't work?
Circles and ellipses are actually polygons, so by rights it should work fine.

**Comment by jfuehner** [comment]
I thought that area would work as well but it threw an error stating it required 4 or more points. I am using turf with Cesium’s CircleGeometry/EllipseGeometry which only provides me with the radius and center of a circle and the center and semi major/minor respectively.

**Comment by stebogit** [comment]
@jfuehner could you please post an example of the code you are using? It's not really clear why you get the error.

**Comment by rowanwins** [comment]
Hi @jfuehner 

Cesium's circleGeometry isn't geojson. Turf modules only work with geojson inputs. Im not sure if cesium offers you any ability to convert your geometries to geojson...

**Comment by stebogit** [comment]
Wise @rowanwins 😄 

I guess we can close this since `@turf/area` does work on circles or ellipses:
```js
var circle = turf.circle([0, 1], 1);
var a = turf.area(circle); // 3143571.061909825
```
