### ISSUE TITLE
Cannot find module '@turf/meta' when using version 6.0.0 in node.js

### ISSUE THREAD

**Issue by trygve-lie** [Turfjs/turf#1235]
When installing `@turf/meta` version 6.0.0 and using it in node.js, one get the following:

```sh
module.js:557
    throw err;
    ^

Error: Cannot find module '@turf/meta'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

It seems like the module is missing `index.js`. It only has a `index.mjs`. Version 6.0.0-beta.3 works and does contian a `index.js`.

**Comment by DenisCarriere** [comment]
@trygve-lie Thanks for reporting this, I submitted a patch to fix this.

The `index.js` is now present again.

https://unpkg.com/@turf/meta@6.0.1/
