### ISSUE TITLE
Dissolve failing

### ISSUE THREAD

**Issue by crpAnderson** [Turfjs/turf#1237]
The dissolve function is failing on certain polygons.
Simply run this in the Javascript console and you'll see what I mean.

var aSmallfeatureCollection = JSON.parse('{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"combine":"yes"},"geometry":{"coordinates":[[[13491093.994242366,1545200.1726017569],[13491093.97839715,1545179.455050879],[13491073.391762003,1545179.47098838],[13491052.805126857,1545179.4869100656],[13491032.218490599,1545179.502815821],[13491011.631854339,1545179.5187056481],[13490991.045218082,1545179.5345795436],[13490970.458581822,1545179.5504376267],[13490949.871945562,1545179.5662798923],[13490929.285308192,1545179.5821061141],[13490908.698671931,1545179.5979165214],[13490888.112034561,1545179.6137111145],[13490888.127720587,1545200.331264407],[13490867.541067634,1545200.3470431964],[13490867.525396075,1545179.6294896617],[13490846.938758703,1545179.645252394],[13490826.352120219,1545179.6609993114],[13490805.765481733,1545179.6767301848],[13490785.178843247,1545179.6924452425],[13490764.592204759,1545179.7081444862],[13490744.005566277,1545179.723827685],[13490723.418926677,1545179.7394950679],[13490702.832287077,1545179.7551465223],[13490682.24564748,1545179.7707821608],[13490661.65900788,1545179.7864018702],[13490641.07236717,1545179.8020056488],[13490620.485726459,1545179.8175936136],[13490599.899085747,1545179.8331656493],[13490599.914552478,1545200.5507222048],[13490620.501208775,1545200.5351499298],[13490641.087865071,1545200.5195618377],[13490661.674520252,1545200.503957703],[13490661.69003374,1545221.2215292982],[13490682.27670562,1545221.2059091057],[13490702.8633775,1545221.1902730996],[13490723.450048266,1545221.174621162],[13490723.434486916,1545200.4570502914],[13490744.021142097,1545200.4413826673],[13490744.036719037,1545221.1589532965],[13490764.623389801,1545221.1432695005],[13490785.21005946,1545221.1275698894],[13490785.19445135,1545200.409999743],[13490805.781105421,1545200.394284443],[13490826.367759492,1545200.3785533283],[13490826.383399881,1545221.0961229934],[13490846.970069537,1545221.080375707],[13490867.55673919,1545221.0646124925],[13490888.143407732,1545221.0488333465],[13490888.159095988,1545241.7664180503],[13490888.174783131,1545262.4840184015],[13490908.761483954,1545262.4682229587],[13490929.348183667,1545262.4524115855],[13490949.93488449,1545262.4365843988],[13490970.521584202,1545262.4207412808],[13490991.108283913,1545262.4048822336],[13491011.69498251,1545262.3890073707],[13491032.28168222,1545262.373116464],[13491052.868380819,1545262.3572098569],[13491052.884194866,1545283.0748240384],[13491052.900010025,1545303.792453871],[13491052.915824072,1545324.5100994655],[13491073.502570538,1545324.49417609],[13491073.486739794,1545303.776530736],[13491094.07346956,1545303.7605917852],[13491094.057623232,1545283.0429624373],[13491094.041778015,1545262.3253487379],[13491094.025932798,1545241.6077506857],[13491094.010087583,1545220.8901683975],[13491093.994242366,1545200.1726017569]]],"type":"Polygon"}},{"type":"Feature","properties":{"combine":"yes"},"geometry":{"coordinates":[[[13490599.945484824,1545241.9858823756],[13490599.930018093,1545221.2682944096],[13490579.343346212,1545221.2838511118],[13490558.756673219,1545221.2993917689],[13490558.772107664,1545242.0169802185],[13490558.787543228,1545262.7345843152],[13490558.802977672,1545283.4522040612],[13490558.818413235,1545304.1698395703],[13490538.231677901,1545304.1853653782],[13490538.247096764,1545324.9030167768],[13490517.660344733,1545324.918526895],[13490517.675749125,1545345.6361941847],[13490497.08898151,1545345.651688615],[13490497.104370315,1545366.3693719108],[13490517.691153517,1545366.3538772396],[13490538.27793783,1545366.3383666375],[13490538.262517853,1545345.6206838253],[13490558.849285468,1545345.6051576505],[13490558.864721028,1545366.3228402217],[13490579.45150423,1545366.307297876],[13490600.038287431,1545366.2917397148],[13490620.62507063,1545366.2761656237],[13490620.609586088,1545345.5584836612],[13490600.022819586,1545345.5740576251],[13490600.007351745,1545324.856391185],[13490599.991885016,1545304.1387403957],[13490599.976418285,1545283.4211053688],[13490620.563136918,1545283.4055322434],[13490620.547654605,1545262.687913105],[13490620.532172289,1545241.9703097313],[13490599.945484824,1545241.9858823756]]],"type":"Polygon"}},{"type":"Feature","properties":{"combine":"yes"},"geometry":{"coordinates":[[[13491032.344877183,1545345.243668283],[13491052.931639232,1545345.2277607103],[13491052.915824072,1545324.5100994655],[13491032.329077607,1545324.5260067966],[13491032.344877183,1545345.243668283]]],"type":"Polygon"}}]}');
var flattened = turf.flatten(aSmallfeatureCollection);
console.log(flattened);
var dissolved = turf.dissolve(flattened);
console.log(dissolved);
// Uncaught Error: features must be of the same type,... even though they are all Polygons

**Comment by rowanwins** [comment]
Hi @crpAnderson 

FIrst thing I noticed is your coords - Turf is designed to work with WGS coords in decimal degrees, if you could reproject your data that might make a difference... But that said Im not sure that it will. 

We've got a one or two other bug reports for `turf/dissolve` so we know there is some work required for this module, we're waiting on replacing our `union` module before we give it a full overhaul.

I'll try and dig further and work out what's going because it's not immediately obvious from my quick look.

**Comment by crpAnderson** [comment]
I actually tried it in both. The dissolve worked with other sets of polygons in both EPSG:3857 and EPSG:4326. After commenting here I did project my data to WGS and found a different way to 'dissolve' my features.
Something I did notice by stepping through the turf dissolve code though was that the logic requires both geometry types to be the same for each internal union operation and it i start with a flatten so its just a bunch of polygons then run dissolve on it. after just a few iterations of the loop some of the features are multipart polygons. Then when the loop comes around to joining the single part polygons with the newly created by the function multipart polygons it throws the error I mensioned above. I did not attempt to convert all the single part polygons to multipart before running the dissolve on them but I suspect that that would work.

**Comment by iandees** [comment]
Hello! I'm [doing some work that uses `turf/dissolve`](https://github.com/iandees/building-diff) as well and seem to be running into this same issue.

In this testcase, the test script will fail with the example geojson, but if you remove any of the features example it will run without problem.

```javascript
var turf = require('@turf/turf');
var fs = require('fs');

var features = JSON.parse(fs.readFileSync('test.geojson'));

var dissolved = turf.dissolve(features);
```

```json
{"type":"FeatureCollection","features":[
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.49609375,42.64507129879989],[-83.49609375,42.645576368740564],[-83.49540710449219,42.645576368740564],[-83.49540710449219,42.64507129879989],[-83.49609375,42.64507129879989]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.49609375,42.64456622475866],[-83.49609375,42.64507129879989],[-83.49540710449219,42.64507129879989],[-83.49540710449219,42.64456622475866],[-83.49609375,42.64456622475866]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.49609375,42.64052548480924],[-83.49609375,42.64103059165476],[-83.49540710449219,42.64103059165476],[-83.49540710449219,42.64052548480924],[-83.49609375,42.64052548480924]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.42674255371094,42.681930627802714],[-83.42674255371094,42.68243539838622],[-83.42605590820312,42.68243539838622],[-83.42605590820312,42.681930627802714],[-83.42674255371094,42.681930627802714]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.42193603515625,42.681930627802714],[-83.42193603515625,42.68243539838622],[-83.42124938964844,42.68243539838622],[-83.42124938964844,42.681930627802714],[-83.42193603515625,42.681930627802714]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.42262268066406,42.681930627802714],[-83.42262268066406,42.68243539838622],[-83.42193603515625,42.68243539838622],[-83.42193603515625,42.681930627802714],[-83.42262268066406,42.681930627802714]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.41850280761719,42.681930627802714],[-83.41850280761719,42.68243539838622],[-83.41781616210938,42.68243539838622],[-83.41781616210938,42.681930627802714],[-83.41850280761719,42.681930627802714]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.49609375,42.66880515319917],[-83.49609375,42.66931003040664],[-83.49540710449219,42.66931003040664],[-83.49540710449219,42.66880515319917],[-83.49609375,42.66880515319917]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.49540710449219,42.66830027189085],[-83.49540710449219,42.66880515319917],[-83.49472045898438,42.66880515319917],[-83.49472045898438,42.66830027189085],[-83.49540710449219,42.66830027189085]]]}},
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-83.49472045898438,42.66830027189085],[-83.49472045898438,42.66880515319917],[-83.49403381347656,42.66880515319917],[-83.49403381347656,42.66830027189085],[-83.49472045898438,42.66830027189085]]]}}
]}
```

**Comment by rowanwins** [comment]
Hi @iandees 

Thanks for the report and test case. 

I'm currently undertaking a fairly substantial overhaul related to #1432 - I'm hoping to release an update for `@turf/dissolve` as part of that - probably a little way of releasing though, perhaps in a fortnight or so there might be an alpha version out.

Cheers
Rowan

**Comment by andrewharvey** [comment]
Upgrading to dissolve from v7 alpha fixed my disolve issues. Well done @rowanwins !
