### ISSUE TITLE
Transform a Polygon to Circle/Radius

### ISSUE THREAD

**Issue by clakech** [Turfjs/turf#1241]
Hello,

I am a new turf user, I would like to know if it is possible to transform a polygon into a circle with a center and a radius ?

I have a list of points that represents à polygon and I would like to transform those points to a circle that embed this polygon.

I have the same question to transform a polygon to a rectangle.

Thanks for your project thats seems awesome and will help me for sure ;)

Cyril

**Comment by DenisCarriere** [comment]
@clakech Thanks posting your first question to TurfJS.

Ideally GitHub issues are not meant for providing custom solutions but for reporting bugs & issues with the current TurfJS implementation, however we can hopefully point you in the right direction.

## Possible useful TurfJS libraries

- http://turfjs.org/docs#centroid - To find the center/centroid coordinate of your polygon
- http://turfjs.org/docs#bbox - Convert Polygon into a BBox, you can then calculate the "diameter" using the corner coordinates for your BBox. I'm sure there's an alternate way to do this, but this is the first one that comes to mind.

**Comment by rowanwins** [comment]
Going to close this but hopefully @DenisCarriere have give you enough tips to get you on your way. If you need more help feel free to post another comment back, perhaps include a code snippet so we can see what you've got so far.

Cheers
