### ISSUE TITLE
Best way to work around the lack of booleanIntersects?

### ISSUE THREAD

**Issue by MartyMcMartface** [Turfjs/turf#1253]
I have a list of arbitrary features, including MultiPolygons and MultiPoints.

I have a rectangular viewing box, and would like to know which of the features intersect the viewing box.

I thought this would be a trivial operation for any geospatial library, but turf doesn't have a booleanIntersects function.

The only way I can think of achieving this with turf is to check for turf.booleanOverlaps(a,b) || turf.booleanContains(a,b) || turf.booleanContains(b,a), but it's not that simple, because booleanContains doesn't support MultiPolygons, so I'd have to iterate through each polygon doing the turf.booleanContains(a,b) || turf.booleanContains(b,a) on each.

I could also theoretically use the turf.intersect function but I imagine that would be an order of magnitude less efficient, as it actually builds intersecting geometries. It also only works with polygons, so I'd have to use it in combination with booleanPointInPolygon and iterate over MultiPolygons etc.

All of this seems very inefficient and it is being done client side in reaction to the user zooming or scrolling a map, so has to be near instantaneous for hundreds of geometries.

Why does turf not implement such a basic function? Has anyone built a reliable workaround using the most efficient combination of functions that are available?

Is there a more robust and full featured javascript geospatial library that I could use instead of turf? I spent a couple of hours investigating alternatives but most people seemed to recommend turf. Is there no equivalient of JTS in the javascript world?

Thanks for any insights, I feel like I must be overlooking a very simple solution.

**Comment by rowanwins** [comment]
Gday @MartyMcMartface 

You are correct that there currently isn't a booleanIntersects module. Unfortunately Turf is a labour of love by a few contributors who work on it after hours, it is on a long list of things I have to do. Much of the code for a booleanIntersects module probably exists in the other boolean modules, it's just a matter of someone having the time to pull it together.

There is [jsts](https://github.com/bjornharrtell/jsts) which is a javscript port of JTS, the downside is it is very large, a bit slow for some operations and the documentation isn't the easiest to navigate.

Of course new contributors are welcome :)

**Comment by stebogit** [comment]
Hey @MartyMcMartface and @rowanwins maybe this is stupid, but reading the [docs](http://edndoc.esri.com/arcsde/9.0/general_topics/understand_spatial_relations.htm) we take as [reference](https://github.com/Turfjs/turf/issues/1140)
> Intersects returns the exact opposite result of disjoint.

it seems to me that you could use [`@turf/boolean-disjoint`](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-disjoint) and negate the output. Couldn't you? 🤔 

If so, wouldn't it be super easy create `@turf/boolean-intersects` using that way under the hood? Would that just bad/sloppy/unprofessional? 😅

**Comment by MartyMcMartface** [comment]
Umm, !turf.booleanDisjoint seems to work perfectly. Not only that, it works with combinations of Polygon, MultiPolygon, MultiPoints etc.
@stebogit did you only just notice that? I wasted hours trying to figure out why booleanOverlap wasn't behaving as expected and looking for a workaround. If someone would be nice enough to implement booleanIntersects with a single line of code it might save someone else hours of frustration.

**Comment by MartyMcMartface** [comment]
Sorry @stebogit I forgot to say thanks!

**Comment by rowanwins** [comment]
I suspect there might be some minimal downsides in terms of performance but it is a handy shortcut :)

Alternatively someone can cut and paste the module and just change the order of the return statements, that should cut down on the work :)
