### ISSUE TITLE
cleanCoords() omits valid coords.

### ISSUE THREAD

**Issue by erikh2000** [Turfjs/turf#1255]
If you agree with me this is a bug, I can add a PR for a test case and maybe a fix.

```
const coords = {type:'Polygon', coordinates:[[[0,0],[2,2],[3,30],[3,30],[3,30],[4,4],[0,0]]]};
const expected = {type:'Polygon', [[[0,0],[2,2],[3,30],[4,4],[0,0]]]};
expect(cleanCoords(coords)).toEqual(expected); // Fails
```

The actual returned value is: ```{type:'Polygon', [[[0,0],[1,10],[2,2],[4,4],[0,0]]]}```

In other words, it omits the [3,30] point. The reason it does this is that there is a duplicate coordinate of ```3,30```. When ```isPointOnLineSegment()``` evaluates either of the two cases of ```3,30```, it correctly returns true. But if I understand the contract of ```cleanCoords()```, it should preserve one of the ```3,30``` coords.

And I think that would be a useful and expected contract to keep. Because then you can do things like @DenisCarriere 's earlier fix for ```intersect()``` which truncated the coord precision and then ran cleanCoords() to yank redundant points.

**Comment by rowanwins** [comment]
Indeed looks like a bug @erikh2000 - thanks for reporting

**Comment by SimonsUnikaNamn** [comment]
I am still getting this error, https://jsfiddle.net/eag6dvzk/1/
