### ISSUE TITLE
How to create a buffer with flat linecap?

### ISSUE THREAD

**Issue by mickeyjohn** [Turfjs/turf#1257]
Hi everyone,

Turf is a very nice geo lib. When using the .buffer function. It can create a nicely buffer polygon with a round linecap around the given polyline. My question is how to create a polyline with flat linecap with turf? Is there any way to achieve that?

Best Regards,
John

**Comment by rowanwins** [comment]
Hi @mickeyjohn 

At the moment it's not possible with Turf. Using the [jsts](https://github.com/bjornharrtell/jsts) lib (on which Turf currently relies) I believe it's doable.

We do already have an [item](#639) to support endcap strategies so Im going to close this in favour of that issue. We're currently trying to remove the dependency on jsts as it is a very large library but when we do we'll try and make sure we have those endcap options in place.

Cheers
Rowan
