### ISSUE TITLE
lineSliceAlong fails when startDist > length of the Feature; also lineString checks the same condition twice

### ISSUE THREAD

**Issue by karijkangas** [Turfjs/turf#1258]
Line 
https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.mjs#L295

if (!isNumber(coordinates[0][1]) || !isNumber(coordinates[0][1])) throw new Error('coordinates must contain numbers');

The check seems wrong.

**Comment by rowanwins** [comment]
Hi @karijkangas 

Can you explain why?

**Comment by karijkangas** [comment]
Hi @rowanwins 

It seems to do the same check twice. 

However, I think the real bug I was seeing is in:

https://github.com/Turfjs/turf/blob/7a044146c4939fc7ff2cc0978af2f84f85332b37/packages/turf-line-slice-along/index.js#L79

which, if the start distance is larger than the total length of the LineString feature, calls lineString with flat [x, y, z] array, hence triggering the exception.

**Comment by rowanwins** [comment]
Ah I see now the issue with the check - good pickup!

And yep looks like you've identified a bug in lineSliceAlong so thanks.

Feel free to send through some pull requests with the appropriate fixes otherwise we'll add it to the list of jobs for the core team.

Thanks,
Rowan

**Comment by karijkangas** [comment]
I think the lineSliceAlong bug is minor as I was seeing it only due to a bug in my code, and hence it's easily avoided. I changed the issue title to better reflect the actual bug so that it might help others while the bug is still around. Keep up the good work! 👍

**Comment by noncomputable** [comment]
I'm getting a related issue with lineSliceAlong: all the coordinates are numbers, but I get: "Error: coordinates must contain numbers".
