### ISSUE TITLE
Type Definitions seem broken on 5.16

### ISSUE THREAD

**Issue by pwilczynski** [Turfjs/turf#1265]
Looking at the typings, they seem totally messed up for both booleanWithin and intersect:

https://github.com/Turfjs/turf/blob/v5.1.6/packages/turf-boolean-within/index.d.ts
https://github.com/Turfjs/turf/blob/v5.1.6/packages/turf-intersect/index.d.ts

Intersect seems better on master, but boolean-within still seems wrong. I'm happy to fix them, but I don't know how to tag a release. Any thoughts?

**Comment by rowanwins** [comment]
Hi @pwilczynski 

@DenisCarriere is currently in the midst of refactoring some of those modules as he'd like to refactor the codebase to being typescript, previously we just had some typescript bindings. So @DenisCarriere is on it - he might be able to provide some direction if you'd like to help.

**Comment by DenisCarriere** [comment]
@pwilczynski Hopefully the last two PR's would fix any Typescript related issues.

https://github.com/Turfjs/turf/pull/1263
https://github.com/Turfjs/turf/pull/1250

These changes will not be published in any `v5.x` release, these will be published under `v6.x`

**Comment by pwilczynski** [comment]
Great - when does v6.x get published?

**Comment by pwilczynski** [comment]
@DenisCarriere -> how do I pick up the v6.x version?

**Comment by DenisCarriere** [comment]
Depends on which module, you would need to install them separately.

```bash
$ yarn add @turf/helpers
```

Will download v6.0.1 => https://unpkg.com/@turf/helpers@6.0.1/ 

```js
// CommonJS
const point = require('@turf/helpers').point;

// or ES6/Typescript
import {point} from '@turf/helpers';
```

**Comment by pwilczynski** [comment]
OK interesting ->  booleanWithin is grabbing 5.1.5, is that expected?

**Comment by DenisCarriere** [comment]
`@turf/boolean-within` hasn't be published as v6 yet, so it's still use `v5`.

**Comment by pwilczynski** [comment]
Okdoke! Thanks a bunch!

**Comment by DenisCarriere** [comment]
@pwilczynski just published v6 modules to npm.

Ref: https://github.com/Turfjs/turf/pull/1279

Re-open if you have any issues

**Comment by pwilczynski** [comment]
@DenisCarriere -> thanks so much, really appreciate the fast turn-around here.

**Comment by stebogit** [comment]
> @DenisCarriere -> thanks so much, really appreciate the fast turn-around here.

Yep, @DenisCarriere and @rowanwins are just super-duper! 😃
