### ISSUE TITLE
segmentEach Bug

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#1273]
`segmentEach` is currently buggy as it creates a segment between an interior and exterior ring

https://runkit.com/rowanwins/segmenteach-bug

Basically we need to watch for an increase in the geometryIndex.

**Comment by DenisCarriere** [comment]
👍 Agreed, we did the geometryIndex, it's strange that `segmentEach` passed the Travis Tests, I guess we don't have good enough tests for that use case.

**Comment by rowanwins** [comment]
Took a bit of a look at the tests and yeah they seem a little sparse.

**Comment by rowanwins** [comment]
Resolved by #1278
