### ISSUE TITLE
Running into issues when trying to use lerna to build a test release

### ISSUE THREAD

**Issue by adam3039** [Turfjs/turf#1281]
I'm not sure if the part about building in the contributor guide is up to date, but I'm running into some issues when trying to do a lerna publish.

I mainly just want to be able to test my new module within my existing application. Is there any way to do this without using lerna?

**Comment by rowanwins** [comment]
Hi @adam3039 

Sorry for the slow reply. To run the test for your module only you should only need to run `npm run test` in the directory of your module (eg turf-rectangle-grid). That shouldn't have anything to do with lerna hopefully.

Hopefully that works for you.

**Comment by adam3039** [comment]
Hi @rowanwins , not a problem at all, I appreciate the assistance.

I should have been more clear, by test I mean I'd like to bring the module into my existing Angular project to actually use it and test that way as well. Do I need to build anything to achieve that, or can I simply reference the module?

**Comment by rowanwins** [comment]
Ah I see! 

That was something I'd wondered about recently until I came across [this article](https://medium.com/@the1mills/how-to-test-your-npm-module-without-publishing-it-every-5-minutes-1c4cb4b369be) (short answer `npm link` to the rescue!).

Hope that helps

**Comment by adam3039** [comment]
I appreciate the tip @rowanwins , I was able to get npm link working and that will be super useful.

I'm still running into some issues though, mainly because I'm not sure which instructions in the contributing readme are good to use, and which aren't. As far as I can tell, my new module code isn't being included in the turf.js script, so I keep getting "is not a function" errors in my application. 

Would it be possible for you to take a peek at my fork?
https://github.com/adam3039/turf

**Comment by rowanwins** [comment]
To expose the module you'll need to add it to the [turf package](https://github.com/adam3039/turf/blob/master/packages/turf/index.mjs). Try give that a whirl and let me know how you get on. Normally when someone is submitting a new module @DenisCarriere takes care of that part so the contributor doesn't have to.

**Comment by adam3039** [comment]
Thanks @rowanwins , this was exactly what I was missing. Once I added my new module to the index.mjs as well as the d.ts file, I was able to successfully run it via npm link in my Angular application.

I'm still running into one strange issue. In my Angular application, once I've linked my local fork of turf, it seems to break the intersect functionality. I get an error on build that doesn't seem to be related to any of my application code, I've confirmed that by removing any of my application code related to turf, it seems to be an error with the turf package in general. I suspect it may have something to do with the link, but I can't be certain. My module functions the way it should, but if I do any intersects on the results I get some really odd behavior.

> ERROR in node_modules/turf/packages/turf/node_modules/@turf/line-intersect/index.ts(34,54): error TS2345: Argument of type 'G1 | FeatureCollection<G1, { [name: string]: any; }> | Feature<G1, { [name: string]: any; }>' is not assignable to parameter of type 'Geometry | GeometryCollection'.
>   Type 'FeatureCollection<G1, { [name: string]: any; }>' is not assignable to type 'Geometry | GeometryCollection'.
>     Type 'FeatureCollection<G1, { [name: string]: any; }>' is not assignable to type 'GeometryCollection'.
>       Types of property 'type' are incompatible.
>         Type 'string' is not assignable to type '"GeometryCollection"'.
> node_modules/turf/packages/turf/node_modules/@turf/line-intersect/index.ts(35,54): error TS2345: Argument of type 'G2 | FeatureCollection<G2, { [name: string]: any; }> | Feature<G2, { [name: string]: any; }>' is not assignable to parameter of type 'Geometry | GeometryCollection'.
>   Type 'FeatureCollection<G2, { [name: string]: any; }>' is not assignable to type 'Geometry | GeometryCollection'.
>     Type 'FeatureCollection<G2, { [name: string]: any; }>' is not assignable to type 'GeometryCollection'.
>       Types of property 'type' are incompatible.
>         Type 'string' is not assignable to type '"GeometryCollection"'.
> node_modules/turf/packages/turf/node_modules/@turf/line-intersect/index.ts(38,15): error TS2339: Property 'geometry' does not exist on type 'G1 | FeatureCollection<G1, { [name: string]: any; }> | Feature<G1, { [name: string]: any; }>'.
>   Property 'geometry' does not exist on type 'G1'.
> node_modules/turf/packages/turf/node_modules/@turf/line-intersect/index.ts(39,15): error TS2339: Property 'geometry' does not exist on type 'G2 | FeatureCollection<G2, { [name: string]: any; }> | Feature<G2, { [name: string]: any; }>'.
>   Property 'geometry' does not exist on type 'G2'.
> node_modules/turf/packages/turf/node_modules/@turf/line-intersect/index.ts(40,15): error TS2339: Property 'geometry' does not exist on type 'G1 | FeatureCollection<G1, { [name: string]: any; }> | Feature<G1, { [name: string]: any; }>'.
>   Property 'geometry' does not exist on type 'G1'.
> node_modules/turf/packages/turf/node_modules/@turf/line-intersect/index.ts(41,15): error TS2339: Property 'geometry' does not exist on type 'G2 | FeatureCollection<G2, { [name: string]: any; }> | Feature<G2, { [name: string]: any; }>'.
>   Property 'geometry' does not exist on type 'G2'.
> node_modules/turf/packages/turf/node_modules/@turf/line-to-polygon/index.ts(46,19): error TS2339: Property 'features' does not exist on type 'G | Feature<G, { [name: string]: any; }> | FeatureCollection<G, { [name: string]: any; }>'.
>   Property 'features' does not exist on type 'G'.
> node_modules/turf/packages/turf/node_modules/@turf/line-to-polygon/index.ts(51,40): error TS2345: Argument of type 'G | Feature<G, { [name: string]: any; }> | FeatureCollection<G, { [name: string]: any; }>' is not assignable to parameter of type 'G | Feature<G, { [name: string]: any; }>'.
>   Type 'FeatureCollection<G, { [name: string]: any; }>' is not assignable to type 'G | Feature<G, { [name: string]: any; }>'.
>     Type 'FeatureCollection<G, { [name: string]: any; }>' is not assignable to type 'Feature<G, { [name: string]: any; }>'.
>       Types of property 'type' are incompatible.
>         Type 'string' is not assignable to type '"Feature"'.
> node_modules/turf/packages/turf/node_modules/@turf/nearest-point-to-line/index.d.ts(11,36): error TS2307: Cannot find module '../turf/index'.

**Comment by rowanwins** [comment]
Going to close as this is superseded
