### ISSUE TITLE
NPM Packages don't have standard typings or builds

### ISSUE THREAD

**Issue by pwilczynski** [Turfjs/turf#1289]
Unlike many similar libraries (see https://github.com/palantir/blueprint) for an example, `@turfjs/boolean-overlap` and most of the other booleans seem to publish with raw `*.ts` files and no `.d.ts` typings. Because of this, the `tsc` compilation in a project that depends on turf will throw many errors if various `--alwaysStrict` is set because the compiler will try to compile the typescript in `node_modules`

In general, I'm getting a ton of compile errors in `tsc` when trying to depend on `@turfjs` and will do my best to work through them and submit upstream PRs.

**Comment by pwilczynski** [comment]
Example error:
```
ts-loader: Using typescript@2.6.2 and /Volumes/git/packages/gaia-app/tsconfig.json
node_modules/@turf/boolean-overlap/index.d.ts(1,10): error TS2305: Module '"@turf/helpers"' has no exported member 'Feature'.
```

**Comment by pwilczynski** [comment]
Also, if I don't add the `"noImplicitAny": false` flag in my tsconfig, I get close to a hundred errors like this:
`node_modules/@turf/boolean-within/index.ts(78,37): error TS7006: Parameter 'multiPoint' implicitly has an 'any' type.`

**Comment by DenisCarriere** [comment]
Agreed, there's going to be 1000+ errors, refactoring TurfJS to Typescript will be a long journey.

Options:
- Provide the `.d.ts` typings compiled by `tsc` (easiest solution)
- Enforce strict Typescript configs (requires a lot of refactoring)

**Comment by chrisgervang** [comment]
Option 1 should work great, and is the [recommended](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) solution from the TS team.

**Comment by pwilczynski** [comment]
Agreed. I’m happy to take a stab at this (and removing checked in
JavaScript) this week if you want!

**Comment by DenisCarriere** [comment]
👍 We can easily generate `.d.ts` typings from `tsc` (for now until all the errors are gone).

**Comment by mfedderly** [comment]
I think we're in a decent spot at this point. We can tighten up the typescript strictness some more but things are considerably more standardized than they were before.
