### ISSUE TITLE
Delaunay & voronoi

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#129]
More awesomeness from @mikolalysenko - this would be great with a quick turf/geojson wrapper
- https://github.com/mikolalysenko/delaunay-triangulate
- https://github.com/mikolalysenko/voronoi-diagram

**Comment by bricker0** [comment]
Hooray! I would love for this to exist too!

**Comment by AbelVM** [comment]
@bricker0 
* https://github.com/Turfjs/turf-tin-constrained
* https://github.com/Turfjs/turf-voronoi-constrained

**Comment by tmcw** [comment]
👍 keeping this as the add-ons
