### ISSUE TITLE
Feature request: prolong line functionality

### ISSUE THREAD

**Issue by tsamsiyu** [Turfjs/turf#1295]
Hello, today i have already spent half a day to find a functionality to prolong the specified line and I'm continuing to find a solution. So I wondered maybe you would be able to add this feature in library.
By 'prolong line' I mean to proportionally increase\decrease the edge(-s) of line.

**Comment by rowanwins** [comment]
Gday @tsamsiyu 

Thanks for the idea, does sound interesting, can I ask what your use case is?

In terms of actual functionality are you just talking about increasing the end segments, or are you increasing all segments equally?

Cheers
Rowan

**Comment by stebogit** [comment]
Hey @tsamsiyu have you tried `@turf/transform-scale`? Depending on your case it might do the trick. Please note you can define the origin as any point, i.e. the edge or the center of a segment and you can have positive or negative scale factor to obtain increased or decreased dimensions

**Comment by tsamsiyu** [comment]
Hi, thank you @stebogit, `transform-scale` is exactly what I was looking for! @rowanwins in my case I needed to prolong line to be sure that it intersects some another geometry, so `transform-scale` works great for me.

**Comment by rowanwins** [comment]
Good thinking @stebogit , glad you got it sorted @tsamsiyu
