### ISSUE TITLE
@turf/meta coordEach, Uncaught (in promise) TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Shooshte** [Turfjs/turf#1296]
I installed @turf/meta using npm. So I have the latest published version etc.

This is my code:
```js
import { coordEach } from "@turf/meta";

export const morphGeoJSON = (feature, bbox, width, height) => {
  coordEach(
    feature,
    (
      currentCoords,
      coordIndex,
      featureIndex,
      multiFeatureIndex,
      geometryIndex
    ) => {
      debugger;
    }
  );

  return feature;
};
```

The feature I am passing in is valid geojson (created by turf.polygon), so that should not be an issue. The function never gets to the debugger in the callback, but instead throws this error:

> Uncaught (in promise) TypeError: Object(...) is not a function
>     at morphGeoJSON (http://localhost:3000/static/js/bundle.js:244944:64)
>     at http://localhost:3000/static/js/bundle.js:241259:148
>     at Array.map (<anonymous>)
>     at AutomaticInputs._callee$ (http://localhost:3000/static/js/bundle.js:241258:49)
>     at tryCatch (http://localhost:3000/static/js/bundle.js:23340:40)
>     at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:23578:22)
>     at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:23392:21)
>     at step (http://localhost:3000/static/js/bundle.js:241081:191)
>     at http://localhost:3000/static/js/bundle.js:241081:361

**Comment by Shooshte** [comment]
Reverting the package to the previous version resolved the issue. Same for `@turf/helpers`. Leaving the issue open since this probably needs to be addressed?

**Comment by DenisCarriere** [comment]
@Shooshte Please provide more details about your data source, at the moment `meta.coordEach` does work as designed.

Seems like the issues is somewhere in your input data or your external code.
