### ISSUE TITLE
Cannot create buffer from multiPolygon

### ISSUE THREAD

**Issue by jfuehner** [Turfjs/turf#1299]
I have been successful creating buffers from circle (turf/circle), ellipse (turf/ellipse) and lineString (turf/helpers) and point (turf/helpers) objects.

However, I can't seem to create a buffer from a multiPolygon (turf/helpers) object. 

For example, I successfully create square (turf/square) and convert it to a multiPolygon (turf/helpers)...

```
import TurfSquare from '@turf/square'
import {multiPolygon as TurfPolygon} from '@turf/helpers'
import TurfBuffer from '@turf/buffer'

var square = TurfSquare(positions)
var feature = TurfPolygon(square)
```

However, when I call...

`var buffer = TurfBuffer(feature, 50, { units: 'meters' });`

I receive an error back stating...

TypeError: **"Cannot read property 'length' of undefined"**
at Ie.coordinates
at Ie.Polygon
at Ie.MultiPolygon
at Ie.read
at Ne.read
at bufferFeature
at buffer

Similarly, if I try to simply create a multiPolygon alone the buffer is not able to be created. However, in the instance of just trying to create a multiPolygon a error is not returned but there is nothing in the buffer. The polygon object created appears to be valid as I can use @turf/area to calculate the area of the polygon.

I'm sure I'm doing something wrong but, its not clear from the documentation what that might be. Any help would be great!

**Comment by rowanwins** [comment]
Hi @jfuehner 

Thanks for reporting this. `@turf/buffer` is using jsts under the hood which can be a bit funny sometimes with some inputs, Could you perhaps try using `@turf/flatten` to generate a collection of standard polygons and try and buffer those and see if that works?

A fuller code snippet might help us debug your problem a bit better.

Thanks,
Rowan

**Comment by jfuehner** [comment]
@rowanwins, I was able to get the extent/rectangle polygon to create a buffer successfully. Instead of the original code example I posted...

```
import TurfSquare from '@turf/square'
import {multiPolygon as TurfPolygon} from '@turf/helpers'
import TurfBuffer from '@turf/buffer'

var square = TurfSquare(positions)
var feature = TurfPolygon(square)
var buffer = TurfBuffer(feature, 50, { units: 'meters' });
```
I ended up having to do the following...

import TurfSquare from '@turf/square'
import TurfBBoxPolygon from '@turf/bbox-polygon'
import TurfBuffer from '@turf/buffer'

var square = TurfSquare(positions)
var feature = TurfBBoxPolygon (square)
var buffer = TurfBuffer(feature, 50, { units: 'meters' });

This created the buffer around the extent polygon as expected.

However, I still can't seem to get a direct multiPolygon (turf/helpers) object to work. 

With a direct multiPolygon whether I flatten the object as you suggested or send it in directly I get the same results. 

**Flattening code...**

```
import TurfSquare from '@turf/square'
import {multiPolygon as TurfPolygon} from '@turf/helpers'
import TurfFlatten from '@turf/flatten'
import TurfBuffer from '@turf/buffer'

var positions = [[[-117.225, 42.941], [-114.846, 41.660], [-116.813, 40.612], [-116.813, 40.612], [-116.813, 40.612], [-116.813, 40.612]]];
var poly = TurfPolygon(positions)
var feature = TurfFlatten(poly)
var buffer = TurfBuffer(feature, 50, { units: 'meters' });
```

**Regular multi...**

```
import TurfSquare from '@turf/square'
import {multiPolygon as TurfPolygon} from '@turf/helpers'
import TurfBuffer from '@turf/buffer'

var positions = [[[-117.225, 42.941], [-114.846, 41.660], [-116.813, 40.612], [-116.813, 40.612], [-116.813, 40.612], [-116.813, 40.612]]];
var feature = TurfPolygon(positions)
var buffer = TurfBuffer(feature, 50, { units: 'meters' });
```

Either of the above code samples produces the same result. The call to TurfBuffer is throwing an exception but when I examine the exception object returned in this case it is an empty object structure vs. what my original post exception that I was getting with the extent being sent in as a multiPolygon.

**Comment by rowanwins** [comment]
Hi @jfuehner 

So there appear to be a few things going on 
1. Your positions need to have the same first and last coordinate
    - side note we seem to be missing a check on this for multipolys @DenisCarriere 
2. Make sure you are passing in the right nest of things
     - multipolys require an additional set of brackets, again there was no check on this @DenisCarriere 

All in all your example should look like
````
import {multiPolygon} from '@turf/helpers'
import buffer from '@turf/buffer'

// Note the extra level of nesting and the matching coords at the end
var positions = [[[[-117.225, 42.941], [-114.846, 41.660], [-116.813, 40.612], [-116.813, 40.612], [-116.813, 40.612], [-116.813, 40.612],[-117.225, 42.941]]]];

var feature = multiPolygon(positions)
var buffer = buffer(feature, 50, { units: 'meters' });
````
Hopefully that helps get you on your way.

We make sure sure we throw a few more errors on the multipolygon helper

**Comment by jfuehner** [comment]
@rowanwins 

Adding the additional nesting actually didn't help my case. However, ensuring the same and first and last position were in the coordinate array fixed the polygon issue. Awesome, thanks for the help on that!

Any thought on my case with the extent polygon? As I mentioned the below code does work however, the buffer appears to be square in nature which when the extent is rectangular the buffer doesn't appear correct.

```
import TurfSquare from '@turf/square'
import TurfBBoxPolygon from '@turf/bbox-polygon'
import TurfBuffer from '@turf/buffer'

var square = TurfSquare(positions)
var feature = TurfBBoxPolygon (square)
var buffer = TurfBuffer(feature, 50, { units: 'meters' });

```

**Comment by rowanwins** [comment]
Hi @jfuehner 

Why are you passing your rectangle bbox into `@turf/square` if you don't want it to be square?

If you want a rectange you should just be able to do
````
import TurfBBoxPolygon from '@turf/bbox-polygon'
import TurfBuffer from '@turf/buffer'

var positions = [24.961, 5.199, 33.325, 8.470]
var feature = TurfBBoxPolygon(positions)
var buffer = TurfBuffer(feature, 50, { units: 'meters' });
````

**Comment by jfuehner** [comment]
@rowanwins, thanks! I'm still pretty new to Turf. I assumed because the docs say the input for a BBoxPolygon needed to be a BBox that I needed to pass it into a function that created a BBox such as square...

**Comment by rowanwins** [comment]
All good @jfuehner , glad you got it sorted :)
