### ISSUE TITLE
v6 publishing 

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#1301]
Gday @DenisCarriere 

So was just trying to make a [quick runkit demo](https://runkit.com/rowanwins/5aa1b6d3a31e920012fe3423) showing something related to one of the boolean modules and I was getting an error like the module function was undefined, basically the fix was that I had to call `moduleName.default`

eg
````
var booleanCrosses = require('@turf/boolean-crosses') // resolving v6

var test = booleanCrosses(feats.features[0], feats.features[1]) // Broken

var test = booleanCrosses.default(feats.features[0], feats.features[1]) // Works
````
I suspect #1296 was possibly related...

I'm not sure what your plans & timeframes are on getting this typescript stuff resolved, if you're not going to get there for a while can we revert the npm packages to the last working v5?

**Comment by DenisCarriere** [comment]
Just add `.default`

```js
var booleanCrosses = require('@turf/boolean-crosses').default
```

I've started removing the "hacks" that we were doing with our bundles.

Since we are using `export default`, the "proper" CommonJS syntax is:

```js
require('@turf/module').default
```

**Comment by DenisCarriere** [comment]
> npm packages to the last working v5

v6 is working, let me see if there's a Typescript config that can make it compatible without having to include `.default` (I doubt it, but maybe?).

Babel & Rollup will also "hack" this solution, the proper syntax for `export default` modules is to add `.default` for your CommonJS libraries.

**Comment by rowanwins** [comment]
Yeah I guess im just conscious that we dont have anything documented saying that that's what needs to happens, if adding `.default` is what we want as the answer then we should write it somewhere.

**Comment by DenisCarriere** [comment]
Unfortunately no, we don't have it documented. Maybe there's a TypeScript config we can modify to allow this behaviour, but I don't know any at the moment.
