### ISSUE TITLE
Turf lineDistance incorrectly throws error on options object

### ISSUE THREAD

**Issue by tetreault** [Turfjs/turf#1309]
Hello, I'm trying to use MapBox and Turf for a client project. Right now I'm just prototyping some functionality, and ran into a confusing error. I'll provide the basic code and geojson snippet: 

[geojson snippet](https://gist.githubusercontent.com/tetreault/88cb716f91a21461f9b139046f4ebd7e/raw/5abacf8bafeef1b4ea2f368eab42eaaffb0ddccc/gistfile1.txt) 

The snippet is very minimal, and all I'm doing at this point is calculating the line distance between two lat/long coordinates. 

So I have this line of code: `const lineDistance = turf.lineDistance(route1GeoJson.features[0], {units: 'kilometers'});`

The turf library client side *always* throws an error for `options is invalid`. So i did some digging in the library and see this is the function for length (aka lineDistance): 

```js
function length(geojson, options) {
    // Optional parameters
    options = options || {};
    if (!isObject(options)) throw new Error('options is invalid');

    // Input Validation
    if (!geojson) throw new Error('geojson is required');

    // Calculate distance from 2-vertex line segements
    return segmentReduce(geojson, function (previousValue, segment) {
        var coords = segment.geometry.coordinates;
        return previousValue + distance(coords[0], coords[1], options);
    }, 0);
}
```

So the issue is when I pass it `{units: 'kilometers'}` as the options param, it thinks that is not an object. Just so I know I'm not crazy I grabbed the `isObject` helper function from the Turf library and ran it clientside and when I do that it 100% returns true, because obviously `{units: 'kilometers'}` is an object. 

Is there something I'm missing here? This is a bug right? I was following along with this [simple MapBox example](https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/) and also noticed they're not passing an option at all as they're just doing this: `var lineDistance = turf.lineDistance(route.features[0], 'kilometers');`. 

If this experience I'm having isn't a bug, could someone just point out what I did wrong? Cause it seems correct to me, and the options param is not invalid. 

Thanks!

Notes: 
Turf version: https://cdn.jsdelivr.net/npm/@turf/turf@5/turf.js
Mapbox version: https://api.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js

**Comment by DenisCarriere** [comment]
@tetreault Thanks for the detailed issue 👍 

The module you are referencing (`@turf/line-distance`) is deprecated and has been renamed to `@turf/length`.

FYI: I've re-published `@turf/length` to use the latest release `v6`

You can try out your example with https://npm.runkit.com/@turf/length

**Comment by tetreault** [comment]
amazing response time thanks all :) 

I believe we can close this then, thanks again for the help!
