### ISSUE TITLE
lineArc() passes invalid options to destination() when units are specified

### ISSUE THREAD

**Issue by petschekr** [Turfjs/turf#1310]
When running the following code:

```
var center = turf.point([-75, 40]);
var radius = 5;
var bearing1 = 25;
var bearing2 = 47;

var arc = turf.lineArc(center, radius, bearing1, bearing2, { units: "meters" });
```

an error will be thrown saying that "options is invalid". Here, `options` is exactly as `lineArc()` expects. The problem is that it passes along the string "meters" [when calling `destination()` internally](https://github.com/Turfjs/turf/blob/master/packages/turf-line-arc/index.js#L62) which fails `destination()`'s check that its options must be an object.

This problem only arises when units are explicitly set which might explain how this slipped through testing ([none of the input test cases provide units](https://github.com/Turfjs/turf/tree/master/packages/turf-line-arc/test/in)). Providing default options `{}` makes `lineArc()` pass along `undefined` which causes `destination()` to set its own defaults.

**Comment by rowanwins** [comment]
Sorry for the slow reply but thanks for reporting this @petschekr , we'll get a patch out for this.

**Comment by vamshi29292** [comment]
@rowanwins Any idea why the travis is failing for #1368 ??

**Comment by rowanwins** [comment]
No not sure sorry, Travis is doing some weird things due to some higher level changes, so likely not your fault :)
