### ISSUE TITLE
Geometry properties lost

### ISSUE THREAD

**Issue by Oneil974** [Turfjs/turf#1311]
Hi,

Is there any way to keep properties of geometry after processing?

I'm always losing properties of geometry on any kinds of processing.

I haven't seen anything about this in processing's description.

Thanks.

**Comment by stebogit** [comment]
Hey @Oneil974, could you please post some code example so we can have a better idea of your issue?

**Comment by Oneil974** [comment]
in fact I'm using node-red module of TurfJS

[TurfJS node-red](https://flows.nodered.org/node/node-red-contrib-turf)

And I'm using code example like this

msg.payload = [ geojson, 0.01];
msg.topic = "buffer";

```
payload: object
    type: "Feature"
    geometry: object
    type: "MultiPolygon"
        coordinates: array[2]
            0: array[17]
            1: array[1]
    properties: object
        empty
```

Is the original version of TurfJS(not node-red) keeping properties?

Thanks

**Comment by rowanwins** [comment]
Hi @Oneil974

I suspect this is an issue with node-red (which I've never heard of sorry). Normally turf will retain properties, for example you can see that in [this example](https://runkit.com/rowanwins/props)

I'm going to close this issue and I'd suggest opening an issue with them.
