### ISSUE TITLE
index.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by mreilaender** [Turfjs/turf#1312]
`Module build failed: Error: /.../node_modules/@turf/convex/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

Convex package seems to be bundled to a `.ts` file which is not correct.
Convex version: `6.0.0`

Workaround:
`tsconfig.json`
```javascript
{
  // ...
  "include": [
    "src/",
    "node_modules/@turf/convex"
  ]
}
```

**Comment by rowanwins** [comment]
THanks for the report @mreilaender 

Yeah there are a few funky things happening, v6 isn't actually officially released yet, its currently some alpha testing. If you can roll back to the v5 series that's your best option at the moment.

**Comment by DenisCarriere** [comment]
Republished this module, should be working now `v6.0.1`
