### ISSUE TITLE
turf-helpers@6.1.0 package is missing lib/ files

### ISSUE THREAD

**Issue by whymarrh** [Turfjs/turf#1329]
Published recently, `@turf/helpers@6.1.0` doesn't include `lib/geojson.d.ts`, resulting in the following error when using it:

```
node_modules/@turf/helpers/index.d.ts(1,259): error TS2307: Cannot find module './lib/geojson'.
```

The `lib` entry was (accidentally?) dropped in 091eee9b04193be46a543b2fdfe2e2b87d51a104, from the looks of it.

The last three versions, for reference:

```
$ tar tf helpers-6.1.0.tgz 
package/package.json
package/index.d.ts
package/index.js
package/index.ts
package/LICENSE
package/README.md
```
```
$ tar tf helpers-6.0.1.tgz 
package/package.json
package/index.d.ts
package/index.js
package/index.mjs
package/LICENSE
package/README.md
package/lib/geojson.d.ts
```
```
$ tar tf helpers-6.0.0.tgz 
package/package.json
package/index.d.ts
package/index.js
package/index.mjs
package/LICENSE
package/README.md
package/lib/geojson.d.ts
```

**Comment by whymarrh** [comment]
Pinning `6.0.0` or `6.0.1` in dependent packages works fine as a temporary solution

**Comment by DenisCarriere** [comment]
Ops, you are correct, `lib` is missing, I'll republish `@turf/helpers`

**Comment by DenisCarriere** [comment]
@whymarrh Can you try again, i've published `v6.1.1` for helpers

**Comment by whymarrh** [comment]
I can confirm that 6.1.1 works, thanks!

**Comment by DenisCarriere** [comment]
@whymarrh Thanks for catching this error, updating `@turf/helpers` is a big refactoring update, however none of the code has changed, simply refactoring from ES Module to pure Typescript.

**Comment by shonderdos** [comment]
Might be related: Getting a error when trying to import helpers@6.1.1 in Angular. helpershelpers@6.0.0 works fine.

`import {lineString} from '@turf/helpers';`

`ERROR in ./node_modules/@turf/helpers/index.ts
Module build failed: Error: /Users/sergehonderdos/code/kartlaps/node_modules/@turf/helpers/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
`

**Comment by DenisCarriere** [comment]
🤔 Strange, I would of figured if the `index.d.ts` Types is provided we wouldn't have that issue anymore.

Let me include `files` in the `tsconfig.json` and republish.

It's odd because we're using Typescript default configuration (`tsc --init`)

**Comment by DenisCarriere** [comment]
> TS files in published libraries are often a sign of a badly packaged library. 

🤔 I guess this means we shouldn't include the `*.ts` files?...

**Comment by DenisCarriere** [comment]
I've re-published helpers `v6.1.2` with these changes => https://github.com/Turfjs/turf/pull/1349

**Comment by shonderdos** [comment]
@DenisCarriere No errors with v6.1.2. Thanks!

This also fixes a issue with including `lineIntersect` to my project (used `lineSplit` as a workaround)

**Comment by DenisCarriere** [comment]
@shonderdos Perfect, glad to hear it works with Angular, feel free to provide feedback like this if it breaks again.

I've updated https://github.com/Turfjs/turf/pull/1349/files all the current Typescript libraries (not published yet).

We currently don't have tests for Angular, I believe once we have a "strict" Typescript configuration we should be good for Angular support.
