### ISSUE TITLE
In the windows platform, the template test.js has a small bug.

### ISSUE THREAD

**Issue by zhuang-hao-ming** [Turfjs/turf#1331]
The template test.js uses the following code to change the in directory to out directory.
```javascript
     test('turf-center', t => {
    glob.sync(path.join(__dirname, 'test', 'in', '*.geojson')).forEach(filepath => {
         
        const out = filepath.replace(path.join('test', 'in'), path.join('test', 'out'))
        
    });
    t.end();
});
```
In windows, the filepath returned by glob uses '/' as path separator, but the path returned by path.join use ' \ ' as path separator which fails the filepath.replace method and make the test fail also.

I think that this is a noteworthy issue for windows users.
 We can solve it by changing path.join to path.posix.join or use other suitable methods. 

Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by maral** [comment]
There is one extra problem on Windows, after the initial build, every /package/*/dist/es/package.json contains `'{"type":"module"}'` (including the apostrophes) and the JSON is invalid. So the next step in the build fails:
```
index.mjs → turf.min.js...
[!] (plugin babel) SyntaxError: D:\DEV\Projects\turf\packages\turf-convex\dist\es\package.json: Error while parsing JSON - Unexpected token ' in JSON at position 0
..\turf-convex\dist\es\index.js
SyntaxError: D:\DEV\Projects\turf\packages\turf-convex\dist\es\package.json: Error while parsing JSON - Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\DEV\Projects\turf\node_modules\@babel\core\lib\config\files\package.js:55:20
    at D:\DEV\Projects\turf\node_modules\@babel\core\lib\config\files\utils.js:30:12
    at Generator.next (<anonymous>)
    at Function.<anonymous> (D:\DEV\Projects\turf\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at step (D:\DEV\Projects\turf\node_modules\gensync\index.js:261:32)
    at D:\DEV\Projects\turf\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (D:\DEV\Projects\turf\node_modules\gensync\index.js:223:11)
    at D:\DEV\Projects\turf\node_modules\gensync\index.js:189:28
```

For some reason this command in `/packages/*/package.json` is printing the apostrophes on Windows (PowerShell):
`"build:es": "tsc --outDir dist/es --module esnext --declaration false && echo '{\"type\":\"module\"}' > dist/es/package.json",`

**Comment by smallsaucepan** [comment]
Hi @maral. Would you mind testing this with the latest alpha? We don't use this approach any more, so would be good to know that Windows builds are working ok.

**Comment by maral** [comment]
Hi @smallsaucepan, I just tested the latest `master` and it seems the build finishes fine.

**Comment by twelch** [comment]
Thanks for reporting back. Let us know if any further issues. Closing as complete for now
