### ISSUE TITLE
Improve booleanOverlap docs

### ISSUE THREAD

**Issue by Stophface** [Turfjs/turf#1333]
I am having this polygon:

    const polygon = JSON.parse('{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[6.26950853,50.72473626],[6.26953794,50.72468996],[6.2695546,50.7246512],[6.26949169,50.72468741],[6.26948194,50.72469389],[6.26946154,50.72470787],[6.26949172,50.72474162],[6.26950853,50.72473626]]]}}');

and this bounding box:

    const bbox = JSON.parse('{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[6.511887823915231,50.950514414615334],[6.512896634823051,50.53594214902105],[5.98503728350704,50.53594214902105],[5.98604609441486,50.950514414615334],[6.511887823915231,50.950514414615334]]]}}');

I want to know if the polygon is intesecting the bounding box

I use [booleanOverlap][1]

    turf.booleanOverlap(polygon, bbox);

It returns `false`.

Why is that? That definetly is within the bounding box. As far as I understand it should return `true`?

  [1]: http://turfjs.org/docs#booleanOverlap,

**Comment by Stophface** [comment]
Ah, Ive got it. 
The documentation says 

"Compares two geometries of the same dimension and returns true if their intersection set results in a geometry different from both but of the same dimension. [...]" 

My polygon is completely withing the bounding box. As far as I know an *intersection* (as the documentation says) *encompasses* a polygon that is within another polygon. What `booleanOverlap` does is only checking whether it overlaps or not. I think documentation is a little missleading here because it lets users think that `booleanOverlap` includes a within.

**Comment by rowanwins** [comment]
Hi @Stophface 

Yeah I think we could improve the docs for some of the boolean modules are understanding their definitions can be a bit finicky. 

The following taken from the postgis docs is quite helpful
> Returns TRUE if the Geometries "spatially overlap". By that we mean they intersect, but one does not completely contain another.

Cheers
Rowan

**Comment by Stophface** [comment]
@rowanwins Yes. As far as I understand intersection

     return ((booleanWithin(polygon, bbox) || booleanOverlap(poylgon, bbox))

**Comment by rowanwins** [comment]
`booleanIntersects` does now [also exists](https://github.com/Turfjs/turf/blob/master/packages/turf-boolean-intersects/index.ts), it's only a recent addition and hasn't made it's way into the docs, but it is [available via npm](https://www.npmjs.com/package/@turf/boolean-intersects), that said it just returns the opposite of [booleanDisjoint](http://turfjs.org/docs/#booleanDisjoint).

**Comment by andrewharvey** [comment]
I just ran into this issue, I was thinking that booleanOverlap was an intersection, I can see here it's not. I think that once booleanIntersects makes it to the docs, this would clear up the issue as most people looking for intersects would use it rather than falsly trying to use overlap.

**Comment by rowanwins** [comment]
Documentation updated via #2133
