### ISSUE TITLE
Difference geometry collection

### ISSUE THREAD

**Issue by Oneil974** [Turfjs/turf#1335]
Hi,

 I just have a question, is there any way to difference a geometry collection with a polygon (or multipolygon)?

Or geometry collections between them.

Getting this error when I'm trying to.

Error: geojson must be a valid Feature or Geometry Object

Thanks.

[geom1.txt](https://github.com/Turfjs/turf/files/1850642/geom1.txt)
[geom2.txt](https://github.com/Turfjs/turf/files/1850643/geom2.txt)

**Comment by rowanwins** [comment]
Hi @Oneil974 

Difference operations currently only support inputting single geometries (either a polygon or a multi-polygon). So passing in collections wont work sorry, you'll need to iterate through your collection.

Hope that helps.

**Comment by Oneil974** [comment]
Ok thanks, I will try this.
