### ISSUE TITLE
Build standalone minified files in submodules

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#134]

**Comment by tchannel** [comment]
@morganherlocker is this still desired? Would the idea be that each module has a min.js generated and synced to it's git repo, so users could pull down the repo and use the .min.js for just that feature? Would we want to add a bower.json to each module then too?

**Comment by morganherlocker** [comment]
Users wanting submodules are most likely already using browserify + node, so I think this is good to close.
