### ISSUE TITLE
collect by hexgrid has the same properties

### ISSUE THREAD

**Issue by mysisi** [Turfjs/turf#1340]
hey, i have some trouble with collect api, when the first argument is a feature collection created from hexgrid, the result features have the same outProperty,  triangleGrid or squareGrid are ok...

**Comment by rowanwins** [comment]
Hi @mysisi 

Which version of turf are you using? I did [resolve this bug](https://github.com/Turfjs/turf/pull/1308) although the patch is currently only available in v6 with the [standalone module](https://www.npmjs.com/package/@turf/hex-grid). The bundled turf is still running as v5 and so the patch hasn't been incorporated yet.

Cheers

**Comment by hw2312** [comment]
I'm using mapbox-gl-js/v0.44.1 and running into the same issue where all properties are the same for hexgrids.

**Comment by rowanwins** [comment]
Hi @hw2312 

The same question for you as above - what version of turf/hexgrid are you using?

**Comment by hw2312** [comment]
@rowanwins I've been using the CDN script `<script src='https://npmcdn.com/@turf/turf/turf.min.js'></script>`. Is there a way to add turf as a standalone module for web purposes?

**Comment by mysisi** [comment]
im using the latest version 5.1.6

2018-03-29 18:13 GMT+08:00 Rowan Winsemius <notifications@github.com>:

**Comment by mysisi** [comment]
@rowanwins using the latest version  5.1.6

**Comment by rowanwins** [comment]
When using a single module in a browser application people are typically using them via a build tool like webpack, these build tools compile all the dependencies and make them browser ready. 

There are some fairly simple instructions on the [getting started pages](http://turfjs.org/getting-started) for how to generate a custom built browser-ready script using browserify (see section titled 'Creating custom builds for use in the browser').

Give those instructions a while and let me know how you get on

**Comment by mysisi** [comment]
im using like this:
var turf = require('@turf/turf')

var bbox = [-10,-10,10,10];
var cellSide = 300;
var options = {units: 'miles'};
var hexgrid = turf.hexGrid(bbox, cellSide, options);

var pt1 = turf.point([0,0], {population: 400});
var pt2 = turf.point([-1,-3], {population: 600});
var pointFC = turf.featureCollection([pt1, pt2, pt3, pt4, pt5]);

var collected = turf.collect(hexgrid, pointFC, 'population', 'values');

when you log collected you will see the feature properties collect will always be the same as the first feature properties.
