### ISSUE TITLE
How to create a shapeSource with a geoJSON polygon circle in react-native ?

### ISSUE THREAD

**Issue by Amalp** [Turfjs/turf#1352]
I am developing a react-native app

Does **http://turfjs.org/docs#circle** only supports web ?

I am currently using your repository **https://github.com/Turfjs/turf** which i think is correct for my react-native app

But why is there no circle option like in the link **http://turfjs.org/docs#circle**

code - `var circle = turf.circle(center, radius, options);`

I succeeded in creating a GeoJSON for polyline by the below code

```
import { lineString as makeLineString} from '@turf/helpers';
const myCoords = [
  [76.343981,10.279141],
  [76.364326,10.258381],
  [76.376372,10.176482],
]
const line = makeLineString(myCoords)
```
Please guide me to create a shapeSource with a geoJSON polygon circle in react-native

```
const center = [76.343981, 10.279141];
const radius = 40; // meters
// **Please give me this line of conversion**
```
And correct me if the repository i installed for react-native is wrong.

I used the following command `npm install --save @turf/helpers`

**Comment by rowanwins** [comment]
Hi @Amalp 

`@turf/circle` is not part of `@turf/helpers` so you'll need to `npm install @turf/circle`
and then
````
import circle from '@turf/circle'
````
Hope that helps get you on your way.
