### ISSUE TITLE
how to split polygon?

### ISSUE THREAD

**Issue by WoShiSunWuKong** [Turfjs/turf#1355]
how to split polygon?
 i have read some previous issues ，but can not find the module @turf/polygon-slice。

**Comment by rowanwins** [comment]
Hi @WoShiSunWuKong 

The short answer is that the module isn't complete yet unfortunately. If you look through the various issues you might get leads find you way to code, but nothing has been released because we don't yet have a stable solution.

**Comment by WoShiSunWuKong** [comment]
@rowanwins  thank you ,may be i need **@turf/polygon-slice**
