### ISSUE TITLE
Provide a transpiled version of lib folder for npm

### ISSUE THREAD

**Issue by atd-schubert** [Turfjs/turf#1358]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

---

I have issues on several turf modules, that they do not provide the transpiled version of the files within the `./lib/` folder. Do I made something wrong, or is there an error in your build and publish process?

I had these problems with `bbox-clip`, `bezier-spline` and `concave`. But there are maybe some more... I don't have problems on all!

**Comment by DenisCarriere** [comment]
@atd-schubert Good catch, that's strange that the `*.js` didn't get populated in the `lib` folder 🤔 

Let me re-publish the ones you mentioned.
