### ISSUE TITLE
lineOffset returns NaN for some LineStrings

### ISSUE THREAD

**Issue by mllava** [Turfjs/turf#1361]
Hi,

I'm having an issue with **lineOffset**. Please see the example here: https://jsfiddle.net/y4xfzxmx/3/

For the given LineString, lineOffset returns NaN from coordinate 7 onwards, until one before last; even happens with distance = 0. It only happens with a few lineStrings that I'm working with.

Any clue why this could be happening?

Many thanks in advance!
Martin

**Comment by vamshi29292** [comment]
The coordinates of the points at 8th and 9th index are identical. What is the expected behaviour in this case? Should the duplicates be removed before processing? (That would make the number of points on the output feature and input feature not equal)

**Comment by rowanwins** [comment]
Ah that probably explains it, Thanks for chiming in @vamshi29292 . `@turf/clean-coords` can be used in this task.
