### ISSUE TITLE
Feature Request: Move all polygon points based on new center

### ISSUE THREAD

**Issue by jfuehner** [Turfjs/turf#1365]
I’m not seeing a way to do this based on the docs so I believe it would be a new feature.

With that said, I’m looking for a way to move all polygon, line, extent, circle, etc points from one location to another based on a new center point.

For example, let’s say I draw a geometry in one location and calculated the center for that geometry. 

Providing my end-users with the ability to change the center lat/lon they would like to move it somewhere else.

Based on the newly provided center lat/lon I need to move all associated shape points to their respective new location based on the new center.

The transformTranslate plugin seems close to what I’m trying to accomplish?

As always any help would be great!

**Comment by stebogit** [comment]
Hey @jfuehner is maybe `@turf/transform-translate` what you need?

**Comment by rowanwins** [comment]
Hi @jfuehner 

Sorry for the slow reply but here is a fleshed out example. 
https://runkit.com/rowanwins/transform-translate

Basically you need to find the centroid of your input shape and then calculate the bearing and the distance between the existing centroid and the new centroid and then use the results to feed into `@turf/transform-translate`

Hope that helps
