### ISSUE TITLE
Leaflet CRS.Simple

### ISSUE THREAD

**Issue by mikila85** [Turfjs/turf#1370]
I am using CRS.Simple as in XY none geographical map.

http://leafletjs.com/examples/crs-simple/crs-simple.html

is there a way to make the [turf.intersect](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect) to work with that ?

**Comment by rowanwins** [comment]
What do you mean? It should work with it fine.

**Comment by mikila85** [comment]
you were right i wasnt working with it correctly thank you!!!!
