### ISSUE TITLE
Different results when using length and distance

### ISSUE THREAD

**Issue by ysic** [Turfjs/turf#1371]
Hi there. I do not have the same result when using length and distance for a line. Why is that? I need to have the same number at the end of my processing to calculate some pourcentage, but because they are not the same, I am finishing with more than 100% total. Here a simple example, the results are:

lengthResult in meters:  880.5993558326397 distanceResult in meters:  880.8745790339221

```
const helpers = require('@turf/helpers');
const length = require('@turf/length');
const turf = require('@turf/turf');
const { forEach } = require('lodash');

const testCoords = [
  [0.462, 51.7214],
  [0.461, 51.7218],
  [0.4609, 51.7218],
  [0.4563, 51.7219],
  [0.4545, 51.7217],
  [0.4532, 51.7209],
  [0.4523, 51.7193],
  [0.4524, 51.719]
];

const lengthResult = length(helpers.lineString(testCoords));
let distanceResult = 0;
forEach(testCoords, (coord, i) => {
  if (i < (testCoords.length - 1)) {
    distanceResult = distanceResult + turf.distance(helpers.point(coord), helpers.point(testCoords[i + 1]));
  }
});
console.log("lengthResult in meters: ", lengthResult * 1000, "distanceResult in meters: ", distanceResult * 1000);
```

**Comment by rowanwins** [comment]
Hi @ysic

`@turf/distance` uses the haversine formula to account for the curvature of the earth, ´@turf/length´ does not. So it'll depend a bit on your use case as to what is most appropriate.

Hope that helps
