### ISSUE TITLE
Geospatial indices for spatial predicate functions

### ISSUE THREAD

**Issue by charlesfrisbee** [Turfjs/turf#1375]
This is more of a general question. I haven't been able to find any information on geospatial indices for spatial predicate functions for example "point in polygon test" in the documentation. Does this mean that these functions run linear scans over the entire polygon rather than using a tree structure to reduce the search space?

Thanks

**Comment by rowanwins** [comment]
Hi @charlesfrisbee

Turf works on geojson which is a very simple geometry spec, it doesn't include any indices. 

For some turf functions we quickly create a spatial index, but only in functions that do lots of iterating and where the cost doesn't outweigh the benefit.

Does that answer your question?

Cheers
Rowan

**Comment by charlesfrisbee** [comment]
@rowanwins,

Great, hat is exactly what I was after.

Thanks,
Charles
