### ISSUE TITLE
Why so many intersection functions?

### ISSUE THREAD

**Issue by IMMSPgisgroup** [Turfjs/turf#1377]
In PostGIS, for example, for 2d geometries only one intersection function ST_Intersection() (this method implements the OpenGIS Simple Features Implementation Specification for SQL 1.1. s2.1.1.3). Why turf.intersect() and turf.lineOverlap() simultaneously? Why make need in additional operations for getting common border of polygons? 
____________________________________________________________________________________________________________
With respect, IMMSPgisgroup

**Comment by rowanwins** [comment]
Because writing geometry libraries is tricky :) 

If we can find a way to streamline things we will but at the moment it's the best we've got.

Hope that helps
Rowan
