### ISSUE TITLE
helpers.isNumber() will fail on empty string

### ISSUE THREAD

**Issue by iursevla** [Turfjs/turf#1380]
The helpers isNumber method will return true if the given input is an empty string. 

Simple example can be tested in this [jsfiddle - turfjs isNumber Test](https://jsfiddle.net/rr_alves/41c6L8jv/)

**Comment by stebogit** [comment]
Good catch @iursevla! We missed that test case [here](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/test.js#L391-L421)
