### ISSUE TITLE
Error while upgrading to Angular 6

### ISSUE THREAD

**Issue by ciukstar** [Turfjs/turf#1384]
ERROR in ./node_modules/'@turf'/meta/index.mjs
1002:15-25 Can't import the named export 'lineString' from non EcmaScript module (only default export is available)

**Comment by rowanwins** [comment]
Hi @ciukstar 

This is a duplicate of #1383 but doesn't contain as much information so I'm going to close this issue, if you could follow the other issue that would be great.

Thanks,
Rowan
