### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by Turbo87** [Turfjs/turf#1395]
It seems that v6 was released lately, but the `CHANGELOG.md` still only mentions v5. What were the major changes in v6?

**Comment by rowanwins** [comment]
Hi @Turbo87 

v6 is kind of in alpha and isn't a full formal release yet. Modules are slowly being converted to Typescript and published but they all aren't done yet. Once they are all done there will be a full release.

Cheers

**Comment by Turbo87** [comment]
But why are they released as stable already then? Shouldn't they have a beta tag in the version then?

**Comment by rowanwins** [comment]
Yeah I agree with you @Turbo87 , unfortunately that's outside of my control.
