### ISSUE TITLE
Webpack 4 problems with @turf/invariant

### ISSUE THREAD

**Issue by adityajain15** [Turfjs/turf#1396]
Hello! I'm having trouble working with @turf/boolean-point-in-polygon. I get the following error:

`./node_modules/@turf/invariant/index.mjs
59:34-42 Can't import the named export 'isNumber' from non EcmaScript module (only default export is available)`

I suppose this problem is related to #1383, any ideas for a temporary fix? I've deleted the .mjs file but then I get 

`./node_modules/@turf/invariant/index.mjs
Module build failed: Error: ENOENT: no such file or directory, open '/Users/adityajain/Desktop/Work/ncrb/node_modules/@turf/invariant/index.mjs'`

**Comment by rowanwins** [comment]
Hi @adityajain15 

I've just republished `@turf/invariant` as v 6.1.2 so if you could try that out that would be great.

Cheers
