### ISSUE TITLE
Using nearestNeighborAnalysis package

### ISSUE THREAD

**Issue by codygordon** [Turfjs/turf#1398]
I'd really like to use the `nearestNeighborAnalysis` package, however it's not available upon installation of v5.1.6, and `npm install @turf/nearest-neighbor-analysis` (as illustrated in the [documentation for the package](https://github.com/Turfjs/turf/tree/master/packages/turf-nearest-neighbor-analysis)) returns a 404. 

Assuming it's just brand new and possibly pre-release? Let me know if I'm missing something – and thanks so much for everything!

**Comment by rowanwins** [comment]
Hmm that's weird - thanks for the report @codygordon , it seems like for some reason it's never been published to npm. We'll take a look and let you know when it's been published. cc @DenisCarriere

**Comment by rowanwins** [comment]
Hi @codygordon 

I've just published this to npm - should be available as v 6.0.1 , let me know if you experience and problems.

Cheers
Rowan

**Comment by andrearizzello** [comment]
Hello! Same problem here, i can't use that function anymore @rowanwins 
`"@turf/turf": "^6.5.0"`
