### ISSUE TITLE
Turf Builder UI is missing "booleanPointInPolygon"

### ISSUE THREAD

**Issue by Trommelbohne** [Turfjs/turf#1399]
Loving the turf builder UI, however I noticed that 
Point in Polygon (http://turfjs.org/docs#booleanPointInPolygon)
can not be selected there.

If this needs to be adressed somewhere else, please point me to the right place.

**Comment by rowanwins** [comment]
Hi @Trommelbohne 

Turf builder is maintained [over here](https://github.com/rowanwins/turf-builder), although I use the word 'maintained' very loosely as I haven't touched it in yonks. I'll attempt to show it some love over the weekend as it has been on my to-do list for a while. Good to know that someone is still using it :)

Cheers
Rowan
