### ISSUE TITLE
Support rectangleGrid

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1403]
I'd like to add a new module, rectangleGrid, which is essentially squareGrid without the constraint that height=width. One use case is drone imagery planning, where the rectangular aspect ratio of the camera defines the region to be captured.

Proposed usage:

```
var rectangleGrid = turf.rectangleGrid(bbox, cellWidth, cellHeight, options);
```

Sound good?

(The development time is sponsored by Prairie Apps.)

**Comment by rowanwins** [comment]
Hey @stevage 

@adam3039 previously raised the same issue[here](https://github.com/Turfjs/turf/issues/1251), there was some work done [here](https://github.com/adam3039/rectangle-grid) and [here](https://github.com/adam3039/turf) so might be worth asking how he's going.

Unfortunately things are a bit undocumented at the moment in terms of the typescript transition although hopefully you can follow one of the existing packages (eg [here](https://github.com/Turfjs/turf/tree/master/packages/turf-along)), if not just go with traditional js and one of the contributors can convert it for you.

Thanks to Prairie Apps (whoever you are!)

**Comment by stevage** [comment]
Hmm, one issue I've just encountered (which affects `squareGrid` as well) is where to apply the `units` option. `squareGrid` applies it along the western and southern border. That means that if you ask for rectangles that are, say, 500 miles wide by 100 miles high, for an area that spans from 80 degrees north to 80 degrees south, you'll get rectangles that are much wider than that at the equator.

Obviously, there's something a bit nonsensical about that request, but I feel that converting the units at the centre of the bounding box is more intuitive than at the west and south edges. But then it wouldn't be consistent with squareGrid anymore.

At the very least, this should be documented I think.

Thoughts?

**Comment by adam3039** [comment]
@rowanwins  I'm the owner of Prairie Applications. I couldn't get through the contribution side of things so I reached out to @stevage for a hand. We're in need of this module, so I'm happy to contribute it to turf, it's a fantastic framework that I'd like to support. Thanks for all your work.

Cheers
