### ISSUE TITLE
Old turf is still published at NPM

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1404]
I assume this is old news, but I just ran into a very confusing situation caused by installing the NPM package "turf" instead of "`@turf/turf`".

There is no warning at https://www.npmjs.com/package/turf that the package is very out of date, and that users should use `@turf/turf` instead.

**Comment by rowanwins** [comment]
Hi @stevage 

Yeah it's been an issue for a while. Unfortunately I don't have npm rights for any of those (or `@turf` workspace for that matter).

@tmcw or @morganherlocker is this something you can assign to me?

**Comment by tmcw** [comment]
I've deprecated `turf` with a message to use the `@turf` namespaced module instead. https://www.npmjs.com/package/turf

**Comment by stevage** [comment]
Thanks @tmcw!
