### ISSUE TITLE
Degree-Radian conversion scale factor error.

### ISSUE THREAD

**Issue by barryrowlingson** [Turfjs/turf#1406]
Converting radians to degrees results in what look like mathematical errors. PI radians should be exactly 180 degrees:
```
t.convertLength(Math.PI,"radians","degrees")
179.78993435469053
```

the conversion is done by one of the `factors` in turf-helpers (extract):

```
export let earthRadius = 6371008.8;
...
degrees: earthRadius / 111325,
```

this results in a degree-radian conversion factor of 57.22891, where as 180/pi is 57.29578

Either there's some odd reason why this is set this way, or possibly the `earthRadius` was changed and the corresponding denominator in the degrees calculation wasn't changed. If the intention is to have the mathematical definition of degrees to radians, then the parameter in the factors table should be 180.0/Math.PI and then not depend on the earth radius.

If the current behaviour *is* intentional, then the magic number (111325) should be documented so the next person who sees this doesn't submit an issue (there's quite a few magic numbers in that table...).

**Comment by stevage** [comment]
For context, I raised this question [here](https://gis.stackexchange.com/questions/285623/why-is-the-length-of-one-degree-in-turf-0-9988/285628#285628) when I was trying to understand why a square grid covering 10 degrees with 1x1 degree grid cells only contained 81 cells...

**Comment by rowanwins** [comment]
Looks like this was the [commit](https://github.com/Turfjs/turf/commit/531e856f2aec498b2a469a88eba6184bb0af1984#diff-15d170aa99f58a23f196b174633cd092) when this was introduced. From vague recollection this all came about due to something around buffer sizes at various latitudes...

Anyway if you'd like to propose a sensible way to check it @barryrowlingson go for it, is the best approach just to go back to a static value?

**Comment by stebogit** [comment]
shouldn't it be then
```js
// factors in turf-helpers
degrees: earthRadius / 180 / Math.PI,
...
```
Or did I get it wrong?

**Comment by mfedderly** [comment]
This wound up being: `degrees: 360 / (2 * Math.PI),` because this is a map of unit name to number of those units in a radian.
