### ISSUE TITLE
Calculation for planar 2D objects

### ISSUE THREAD

**Issue by kuchaguangjie** [Turfjs/turf#1410]
Hi, I am trying to do some calculation on planar 2D objects.
It seems objects & math calculations of Turfjs are based on 3D GIS with latitude and longitude.
So I am wondering is Turfjs also suitable for represent objects on planar 2D plans.

I have asked a question with code examples on SO, please check:

https://stackoverflow.com/questions/50716161/calculate-distance-from-point-to-line

Thanks.

**Comment by stebogit** [comment]
Hey @kuchaguangjie see [here](https://stackoverflow.com/a/50764495/4530144)

**Comment by kuchaguangjie** [comment]
@stebogit Very clear, thanks.
