### ISSUE TITLE
Typescript conversion status

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#1412]
Dropping a note here about which modules still need to be converted to Typescript. Have created a little script to check in `scripts/checkTsProgress.js`

Short answer is alot still :)

- [ ] 1. C:/code/turf/packages/turf-boolean-valid-geometry
- [ ] 2. C:/code/turf/packages/turf-buffer
- [ ] 3. C:/code/turf/packages/turf-difference
- [ ] 4. C:/code/turf/packages/turf-dissolve
- [ ] 5. C:/code/turf/packages/turf-ellipse
- [ ] 6. C:/code/turf/packages/turf-envelope
- [ ] 7. C:/code/turf/packages/turf-explode
- [ ] 8. C:/code/turf/packages/turf-flatten
- [ ] 9. C:/code/turf/packages/turf-flip
- [ ] 10. C:/code/turf/packages/turf-great-circle
- [ ] 11. C:/code/turf/packages/turf-interpolate
- [ ] 12. C:/code/turf/packages/turf-isobands
- [ ] 13. C:/code/turf/packages/turf-isolines
- [ ] 14. C:/code/turf/packages/turf-kinks
- [ ] 15. C:/code/turf/packages/turf-line-chunk
- [ ] 16. C:/code/turf/packages/turf-line-offset
- [ ] 17. C:/code/turf/packages/turf-line-slice
- [ ] 18. C:/code/turf/packages/turf-line-slice-along
- [ ] 19. C:/code/turf/packages/turf-line-split
- [ ] 20. C:/code/turf/packages/turf-mask
- [ ] 21. C:/code/turf/packages/turf-meta
- [ ] 22. C:/code/turf/packages/turf-midpoint
- [ ] 23. C:/code/turf/packages/turf-planepoint
- [ ] 24. C:/code/turf/packages/turf-point-on-feature
- [ ] 25. C:/code/turf/packages/turf-points-within-polygon
- [ ] 26. C:/code/turf/packages/turf-polygon-smooth
- [ ] 27. C:/code/turf/packages/turf-polygon-tangents
- [ ] 28. C:/code/turf/packages/turf-polygonize
- [ ] 29. C:/code/turf/packages/turf-rectangle-grid
- [ ] 30. C:/code/turf/packages/turf-rewind
- [ ] 31. C:/code/turf/packages/turf-sample
- [ ] 32. C:/code/turf/packages/turf-sector
- [ ] 33. C:/code/turf/packages/turf-shortest-path
- [ ] 34. C:/code/turf/packages/turf-simplify
- [ ] 35. C:/code/turf/packages/turf-square
- [ ] 36. C:/code/turf/packages/turf-standard-deviational-ellipse
- [ ] 37. C:/code/turf/packages/turf-tag
- [ ] 38. C:/code/turf/packages/turf-tesselate
- [ ] 39. C:/code/turf/packages/turf-transform-rotate
- [ ] 40. C:/code/turf/packages/turf-transform-scale
- [ ] 41. C:/code/turf/packages/turf-transform-translate
- [ ] 42. C:/code/turf/packages/turf-unkink-polygon
- [ ] 43. C:/code/turf/packages/turf-voronoi

**Comment by stevage** [comment]
What is required to "convert" a module to Typescript exactly?

**Comment by rowanwins** [comment]
There are a few instructions in [this comment](https://github.com/Turfjs/turf/pull/1240#issue-166041887) although I think they are outdated. 

I'll try and write up what I think is required based on what I see in the already done modules such as [`@turf/along`](https://github.com/Turfjs/turf/tree/master/packages/turf-along)... it's kinda similar but with some tweaks

**Comment by rowanwins** [comment]
So this is how I understand it currently

- [ ]  Rename `index.js` => `index.ts`

After that it sounds like there are a few avenues

**Option 1**
- [ ]   Add any Typescript types to the input & outputs in the `index.ts` (possibly can steal from the `index.d.ts`)
- [ ]   Delete `index.d.ts` since `index.ts` will now be used as the main Typescript file
- [ ]   Drop `types.ts` files since the Typescript testing will now be achieved via the `index.ts`

**Option 2**
- [ ]  Retain the `index.d.ts` and `types.ts` files and somehow have less typescript-y stuff in the `index.ts`

**Other changes**
- [ ]   Convert `test.js` & `bench.js` to use CommonJS (replace `import` with `require()`). 
- [ ]  Update package.json to reflect the following:
```` 
  "main": "index",
  "types": "index.d.ts",
  "files": [
    "index.js",
    "index.d.ts"
  ],
````
- [ ] Update scripts in the package.json to reflect the following:
```` 
 "scripts": {
    "prepare": "tsc",
    "pretest": "tsc",
    "test": "node test.js",
    "bench": "node bench.js",
    "docs": "node ../../scripts/generate-readmes"
  },
````
- [ ]   Drop `@std/esm` from `devDependencie`s & extra `@std/esm` configs from package.json

I'll try to keep this list updated as I go because I still have lots to try and understand in regards to this whole typescript thing.

**Comment by stevage** [comment]
Is index.d.ts a [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html) (apparently also called a definition file)?

**Comment by rowanwins** [comment]
Superceded by #1428
