### ISSUE TITLE
Turf intersect didn't work in some cases on 5.1.6

### ISSUE THREAD

**Issue by Sparksx** [Turfjs/turf#1418]
Hi,
Turf intersect didn't work well with these polygons:
[Polygon 1](https://gist.github.com/Sparksx/d2a4fcfe5930a9fcb6bd7315af2c4d7c)
[Polygon 2](https://gist.github.com/Sparksx/4a92bcbbbbca02d5314b109919e1c9c4)
[Polygon 3](https://gist.github.com/Sparksx/b47f2af759f7c515d3bb2243ddb822d6)
[Global view of polygons](https://gist.github.com/Sparksx/b96acdfb087ea744b1cc791c3aeec697)

Small explain: Polygon 2 and 3 are inside polygon 1
`turf.intersect(polygon1, polygon2)` => null
`turf.intersect(polygon1, polygon3)` => null

I test it with the **lastest turf version** (currently 5.1.6)
You can try it here: [http://jsfiddle.net/1k9hcsuw/1/](http://jsfiddle.net/1k9hcsuw/1/)

thanks

**Comment by rowanwins** [comment]
Hi @Sparksx 

This is resolved with v6 of `@turf/intersect`, see this [example](https://runkit.com/rowanwins/5b24fbd82865d000121918f9). 

v6 see's us shift from using jsts to martinez for intersect. v6 isn't quite fully released but so far it looks like [martinez](https://github.com/w8r/martinez) will resolve a lot of issues.
