### ISSUE TITLE
turf.isolines() and size of input grid

### ISSUE THREAD

**Issue by IMMSPgisgroup** [Turfjs/turf#1420]
Why user cannot set grid size by row and column in TurfJS 5.1.6 turf.isolines() ?
I see that grid are divided on row by comparing latitude. That may be safely, but slowly.
Why do not have any alternative methods?

**Comment by stebogit** [comment]
Hey @IMMSPgisgroup I'm not sure I understand what you're asking and/or suggesting.
`@ turf/isolines` expects a `pointGrid` input, which itself defines the dimensions and grid size of the output. It uses the [Marching Square](https://en.wikipedia.org/wiki/Marching_squares) algorithm to calculate the lines, which requires a gridded data set as input.

Would you mind elaborating a bit on your suggestion?

**Comment by IMMSPgisgroup** [comment]
I say about [https://github.com/Turfjs/turf/blob/master/packages/turf-isolines/lib/grid-to-matrix.js](url) function sortPointsByLatLng(points, flip). May be I mistaked.
```JavaScript
 // divide points by rows with the same latitude
    featureEach(points, function (point) {
        var lat = getCoords(point)[1];
        if (!pointsByLatitude[lat]) pointsByLatitude[lat] = [];
        pointsByLatitude[lat].push(point);
});
```

**Comment by stebogit** [comment]
@IMMSPgisgroup that is the only way I could came up with to make sure the `zProperty` values of each point in the `pointGrid` have the same position of the correspondent element on the `matrix` input. There is no rule that defines how the `pointGrid.features` are or should be ordered.
You can consider it a slowing down step, but I believe it does still make sense to make sure we have a reliable output with _any_ `pointGrid` input.

However I'd love to see an alternative faster implementation, fell free to send a PR if you have any suggestion.
