### ISSUE TITLE
Isolines by curvilinear grid.

### ISSUE THREAD

**Issue by IMMSPgisgroup** [Turfjs/turf#1421]
Why do not have any tool for building isolines by curvilinear grid?

**Comment by rowanwins** [comment]
Hi @IMMSPgisgroup 

Short answer is because no-one has requested it or built it yet. 

If you would like someone to look at it you'll probably need to provide a few more details as to how it would function (eg what is the input dataset and what are the options)

Thanks,
Rowan

**Comment by stebogit** [comment]
What's a curvilinear grid and what would be an example of application?

**Comment by stebogit** [comment]
I personally don't think this type of warped computational (3D?) space is what Turf is meant to handle.

Might not be aware of something though.
@rowanwins @DenisCarriere?

**Comment by rowanwins** [comment]
Yeah I'm struggling to see the real-world map-based application at the moment...

**Comment by IMMSPgisgroup** [comment]
That is 2d. That "On the other hand, many practically important problems of computational
fluid dynamics are now solved numerically on curvilinear grids [2,3,6,7]." from Computer Algebra in Scientific Computing CASC 2000-Springer Berlin Heidelberg (2000) Alkiviadis G. Akritas, Gennadi I. Malaschonok (auth.), Victor G. Ganzha, Ernst W. Mayr, Evgenii V. Vorozhtsov (eds.) and more another (as example Handbook of grid generation-CRC Press (1999) Joe F. Thompson, Bharat K. Soni, Nigel P. Weatherill).
I see that for building isolines by irregular grid may use TIN or may be Meandering Triangles, but for strustured grid (I thhink) algorithms more simple then in Efficient Methods for Isoline Extraction from a Digital Elevation Model Based on Triangulated Irregular Networks Marc Van Kreveld.

**Comment by stebogit** [comment]
Yeah... still, I don't see that stuff for Turf.
