### ISSUE TITLE
@turf/voronoi not typed correctly 

### ISSUE THREAD

**Issue by nicholasgcoles** [Turfjs/turf#1422]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [X] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Hello, I am trying to generate the Voronoi for a feature collection:
The documentation states that the voronoi is to be generated in the following way:
```
var options = {
  bbox: [-70, 40, -60, 60]
};
var points = turf.randomPoint(100, options);
var voronoiPolygons = turf.voronoi(points, options);
```

However the `turf.voronoi` function only looks for a bounding box (bbox) - this throws an error when trying to build my application in production (due to my typescript linter)

```
export default function voronoi(
    points: FeatureCollection<Point>,
    bbox: BBox
): FeatureCollection<Polygon>;
```

It is a relatively easy fix. Something along the lines of:
```
export default function voronoi(
    points: FeatureCollection<Point>,
    options: {bbox: BBox}
): FeatureCollection<Polygon>;
```

Unless is there something I am doing wrong my side?

Thanks in advance!

**Comment by stevage** [comment]
Looks like you're right - thanks for reporting.

**Comment by chansen-va** [comment]
Hey, I'm also hitting issues around this issue. Any chance someone could merge and create an NPM release with #1424?

**Comment by Naitik333** [comment]
Can some one please merge the Pull request and release it. We are not able to use voronoi in Typescript.

**Comment by amr-y-shalaby** [comment]
I confirm the same error ... even API Documentation Example provided does not work  [https://turfpy.readthedocs.io/en/latest/transformations/voronoi.html ](url)
