### ISSUE TITLE
How to check if GeoJSON feature is in rectangular shape and find corner points?

### ISSUE THREAD

**Issue by Xyroid** [Turfjs/turf#1423]
I have a collection of GeoJSON features as Polygon & MultiPolygon which are saved in MongoDB. Many among them are in rectangular or square shape, while others are odd shaped. How can I find all the four corner (top left, top right, bottom left and bottom right) points if that feature is in rectangular or square shape?

I first tried to filter those features which has only five co-ordinates, so that those points will be corner co-ordinates essentially. But some of them are having more than five co-ordinates but as shape they are rectangle or square. Check below given feature examples. First is odd shaped feature, second is rectangle with redundant points and third is rectangle with 4+1 points.

I checked TurfJS, but didn't find any helpful method. BBox gives me non-rotated rectangle, which is not useful because it can also give bbox for non-rectangular shape also.

https://bl.ocks.org/Xyroid/800dafa55111ce139b8158c62f858c98/

**Comment by stebogit** [comment]
@Xyroid if I understand correctly what you need, I guess (not tested) if you create a [bbox-polygon](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox-polygon) around each polygon (or polygon inside a multipolygon) you should find all the rectangles/squares having exactly 4 points touching the perimeter of the bbox-polygon (you probably want to ignore the duplicated "closing" point in all your polygons).
You could create a `LineString`/`LinearRing` from the bbox-polygon, i.e. the perimeter, and use [`@turf/boolean-point-on-line`](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-point-on-line) on each polygon's point for checking.

You might find a faster way, but this at least to give you an idea I believe should work.

**Comment by Xyroid** [comment]
@stebogit Thanks for responding. You idea works for rectangle shape but some odd shapes will also give me four corner co-ordinates, so how to deal with that? If I can know that shape is rectangle then it's working to find the corner co-ordinates. Check below given code with output.

```
var turf = require("@turf/turf")
var arrMultiPolygon = [
    [
        [
            [-102.61383274599996, 32.37585257400008],
            [-102.61764297999997, 32.375000929000066],
            [-102.62239479299996, 32.388750307000066],
            [-102.60775890199994, 32.392205895000075],
            [-102.60566771099997, 32.392699906000075],
            [-102.60510962499995, 32.39093294600008],
            [-102.61772064899998, 32.387951290000046],
            [-102.61383274599996, 32.37585257400008]
        ]
    ]
];
var multiPolygon = turf.multiPolygon(arrMultiPolygon);
var bbox = turf.bbox(multiPolygon);
var bboxPolygon = turf.bboxPolygon(bbox);
var lineString = turf.lineString(bboxPolygon.geometry.coordinates[0]);

var intersectingPts = [];
arrMultiPolygon[0][0].forEach((x) => {
	var isPointOnLine = turf.booleanPointOnLine(turf.point(x), lineString);
	if (isPointOnLine) {
		intersectingPts.push(x);
	}
});

console.log(intersectingPts);
```

https://bl.ocks.org/Xyroid/4175d963a8b4efc32e51b2cdc46b3f1d

**Comment by rowanwins** [comment]
`@turf/clean-coords` removes redundant coords so that might help for those squares or rectangles with 6+ coords...

**Comment by stebogit** [comment]
Ah! Now I get the actual issue. Sure, use `@turf/clean-coords` to remove redundant coords, then just filter by number of points.

**Comment by Xyroid** [comment]
My major challenge is to determine first that if feature is rectangle or not, then cleaning co-ords and later steps can be used to find the corner points.

**Comment by stebogit** [comment]
Sure, `@turf/clean-coords` does not modify the input by default (see options), so you can use it for your validation.
