### ISSUE TITLE
"Turf" top level package readme confusion

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1427]
The README for the top level turf package (ie, what you see at https://www.npmjs.com/package/@turf/turf) is a bit confusing:

>Install this module individually:

>`$ npm install @turf/turf`

>Or install the Turf module that includes it as a function:

>`$ npm install @turf/turf`

IMHO it should be a bit different from the others. Something like:

> Install this module to include all Turf modules:

>`$ npm install @turf/turf`

>Or you can install each module individually:

>`$ npm install @turf/turf-random`

**Comment by rowanwins** [comment]
I suspect this is because those readme's are auto-generated. We might have to have a manual process for generating that one - although it might get superseded by #1428

**Comment by stevage** [comment]
Yeah, it is auto-generated. Probably can just change the process so that one isn't.

**Comment by rowanwins** [comment]
Superseded by #1428
