### ISSUE TITLE
[@turf/polygon-smooth] Unexpected internal type error. 

### ISSUE THREAD

**Issue by cglacet** [Turfjs/turf#1435]
The following code  with [feature `f`](https://gist.github.com/cglacet/52b12d165c420e942bdd6e73d88e0988) produces a type error:
```es6
import polygonSmooth from '@turf/polygon-smooth';
const f = {
   type:"Feature",
   properties:{},
   geometry:{
      type:"Polygon",
      coordinates: [[[-1.6197482232439597,47.189491323684166],[-1.6365061724532097,47.23037560406607],[-1.517833546488987,47.26205505221413],[-1.538169723552869,47.219700393874255],[-1.541692443366287,47.21535938925448],[-1.5626449835490348,47.20335923635037],[-1.5833073104165578,47.19169146558532],[-1.6197482232439597,47.189491323684166]]]
   }
};
const test = polygonSmooth(f, {iterations: 3});
```
Outputs an error `TypeError: Cannot read property '1' of undefined`.

Detailed error: 
```
node_modules/@turf/polygon-smooth/main.js:80
        var p1 = poly.coordinates[geometryIndex][realCoordIndex + 1];
                                                ^

TypeError: Cannot read property '1' of undefined
    at node_modules/@turf/polygon-smooth/main.js:80:49
    at Object.coordEach (node_modules/@turf/meta/index.es5.js:146:25)
    at processPolygon (node_modules/@turf/polygon-smooth/main.js:73:10)
    at node_modules/@turf/polygon-smooth/main.js:41:17
    at Object.geomEach (node_modules/@turf/meta/index.es5.js:513:17)
    at polygonSmooth (node_modules/@turf/polygon-smooth/main.js:29:10)
    at Object.<anonymous> (test_turf.js:15:13)
    at Module._compile (module.js:643:30)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
```

Obviously the result is the same if I use `const f = turf.polygon(...)` to generate my feature or if I encapsulate it in a feature collection. Changing the number of iterations doesn't change the result either.

**Comment by cglacet** [comment]
I'm still searching for the problem, but it seems like it comes from the [`coordEach callback`](https://github.com/Turfjs/turf/tree/64f90d0cacba07f29c1053d617413bf55214c715/packages/turf-meta#coordeachcallback) which passes an __undefined__ `geometryIndex`.

My @turf/meta version is: 
```bash
├─┬ @turf/polygon-smooth@5.0.1
│ └── @turf/meta@4.7.4
```

**Comment by rowanwins** [comment]
Hi @cglacet 

Yeah unfortunantly a whole lot of packages got out of sync with each-other during work on v6 and a full version of v6 was never released. As I mentioned elsewhere I'm working to bring everything back to parity which should prevent this sort of thing from happening again.

Cheers
