### ISSUE TITLE
Turf interpolate works fine on browser but fails while screencapture with phantomJS

### ISSUE THREAD

**Issue by neavilag** [Turfjs/turf#1437]
I have the following file working with turf interpolating from a geoJson
http://51.15.61.14/idw.html?region=CGT&variable=wind

it reproduces a map like this
https://www.evernote.com/l/ACEusQec9IhDi7ZugHJ_jqnptP_YST1yVG4

but I want to generate a static map of this automatically ever XX hours to store it in my server this I have achieved with other maps not using turfjs with phantomjs CLI escreen capture, but with this url gives me this error

```
bin/phantomjs capture.js "http://51.15.61.14/idw.html?region=CGT&variable=wind" ~/Downloads/mapa_viento.jpg "640px*480px"
TypeError: Attempting to configurable attribute of unconfigurable property.

  https://npmcdn.com/@turf/turf@5.1.6/turf.min.js:1 in defineProperties
  https://npmcdn.com/@turf/turf@5.1.6/turf.min.js:1
  https://npmcdn.com/@turf/turf@5.1.6/turf.min.js:1
  https://npmcdn.com/@turf/turf@5.1.6/turf.min.js:1
TypeError: undefined is not a constructor (evaluating 'turf.polygon')

  http://51.15.61.14/idw.html?region=CGT&variable=wind:301 in populateMap
  http://51.15.61.14/idw.html?region=CGT&variable=wind:239 in onload
```

I have tried different versions, and loading locally or from CDN but the same issue appears, map works in all browsers

thanks for your help

**Comment by rowanwins** [comment]
Hi @neavilag 

Thanks for the report. Don't know too much about phantomJS sorry although looks like a web search brings up lots of similar issues for `TypeError: Attempting to configurable attribute of unconfigurable property.` and phantomjs. 
I also know that PhantomJS is somewhat unsupported so it looks like alterantives being built (eg casperjs), so whether there is a way to swap out that dependency I'm not sure...

Anyway I don't think we can help much more on our end sorry, good luck finding a fix
