### ISSUE TITLE
How to calculate positions of circles (with a known radius) to cover an arbitrary polygon area?

### ISSUE THREAD

**Issue by gajus** [Turfjs/turf#1441]
I am using an API that is limited to 10km geographic radius lookups. I need to capture data for an entire country. I know the shape of the country.

How to calculate positions of circles (with a known radius) to cover an arbitrary polygon area?

**Comment by gajus** [comment]
Here is a quick solution https://gist.github.com/gajus/20e95bd2b06e41a1bace87d62a7de1d6

**Comment by rowanwins** [comment]
Hi @gajus 

Another option might [`@turf/point-grid`](http://turfjs.org/docs#pointGrid). It'll take a polygon as a mask and then work out a grid inside that
````
var myCountry = whateverPolygon
var extent = turf.bbox(myCountry);
var options = {units: 'kilometers'};
var grid = turf.pointGrid(extent, 5, options);
````
Anyway sounds like you've got it sorted :)
