### ISSUE TITLE
Error importing TurtJs in Eclipse Vert.x 

### ISSUE THREAD

**Issue by BOUHAFSADMI** [Turfjs/turf#1447]
when I import `TurfJs` in `Vert.x` like this:

```
var Router = require("vertx-web-js/router");
var turf = require("@turf/turf");


var server = vertx.createHttpServer();

var router = Router.router(vertx);

router.get("/").handler(function (ctx) {
  var response = ctx.response();

  response.putHeader("content-type", "application/json; charset=utf-8");

  response.end("[\"foo\",\"bar\"]");
});

server.requestHandler(router.accept).listen(8080);

```
when I run the script, I get this error:

```
Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2762 ms, time limit is 2000
javax.script.ScriptException: TypeError: Cannot redefine property "name" of function IndexOutOfBoundsException (message) {
    Error.call(this);
    this.message = message || '';
  } in node_modules/@turf/turf/turf.js at line number 26251
```

**Comment by rowanwins** [comment]
Hi @BOUHAFSADMI 

It's a bit hard to know what's going on as I know nothing about `vertx`. It doesn't look like your code even calls `turf` currently which suggests the error isn't actually anything to do with `turf`....

**Comment by BOUHAFSADMI** [comment]
I tried it with the old version of turf and it works fine (https://www.npmjs.com/package/turf)!  
as you see just importing ```turf````  means ```vertx``` start analysis the code, and the import causes the problem.
