### ISSUE TITLE
circle with center coordinates x or y greater than 360

### ISSUE THREAD

**Issue by simodelle** [Turfjs/turf#1448]
Hi,
i have a problem with turf.circle() function because when i pass to the function for example [361,100] as center coordinates, the polygon that it returns is a circle with coordinates:
0: [1, 79.9100679636275]
1: [1.050317153478616, 79.91049719950237]
2: [1.1001623750305176, 79.91178088118679]
3: [1.1490678056032249, 79.91390696562333]
4: [1.1965737096381477, 79.91685549673517]
....
62: [0.8998376249694822, 79.91178088118679]
63: [0.949682846521384, 79.91049719950237]
64: [1, 79.9100679636275]

so with x ranging from 0 to 1 and not from 360 and 361. I need to mantain the original coordinates and not that when I exceed 360 It restart from 0. Is it possibile in any way? 
I hope I was clear

Thank you

**Comment by stebogit** [comment]
@simodelle it looks like the issue could actually be in @turf/destination ([here](https://github.com/Turfjs/turf/blob/master/packages/turf-destination/index.ts#L46)), where basically it removes any offset moving everything between longitude 0-360.
We probably should add an offset to that function to return the correct point.

You could do something like this (not tested) for the time being:
```js
var p = [361, 55];
var c=turf.circle(p, 40);
var offset = p[0] - 360 > 0 ? Math.round(p[0] / 360) * 360 : 0;
c.geometry.coordinates[0] = c.geometry.coordinates[0].map(function(coord) {
  coord[0] += offset;
  return coord;
});
```

**Comment by smallsaucepan** [comment]
User was passing a longitude way outside the bounds of what's expected. Closing.
