### ISSUE TITLE
Typescript definition is missing with `boolean-within`

### ISSUE THREAD

**Issue by nkint** [Turfjs/turf#1465]
Hi,
I'm using node v10.6.0 and npm 6.4.0.

I'm adding `boolean-within` with `$ npm i --save @turf/boolean-within`
and the definition file `index.d.ts` is not downloaded, while in other module it is.

Step to reproduce:

```
$ mkdir /tmp/test
$ cd /tmp/test
$ npm i @turf/boolean-within
$ ls node_modules/@turf/boolean-within
# see that index.d.ts is missing, try another package installed as dep
$ ls node_modules/@turf/boolean-point-in-polygon
# see index.d.ts correctly
```

**Comment by yokots** [comment]
also with @turf/distance @turf/area

**Comment by nkint** [comment]
Yeah seems to be a common problem in how ts definitions are exported

**Comment by guyisra** [comment]
any updates on this?

**Comment by sroettering** [comment]
same issue with @turf/boolean-equal
