### ISSUE TITLE
Keep GeoJson Feature Collection properties with Centroid function

### ISSUE THREAD

**Issue by sylvain-m** [Turfjs/turf#1466]
_(sorry, but i am totally beginner in Javascript)_

Hello,
I try to convert a Multipolygon GeoJson Feature Collection to centroid point layer.
I succeed for geometries, but without keeping properties. However, I see in documentation it might be possible.

He is the function I wrote : 
 
```
function ToCentroid(polyList) {
	var centroidgroup = L.layerGroup();
  for (var i = 0; i < polyList.length; ++i) {
  var centroidtemp = turf.centroid(polyList[i].toGeoJSON());
  centroidgroup.addLayer(L.geoJson(centroidtemp, {
					onEachFeature : onEachFeature,
          }));
    }
  return centroidgroup;
  }
```

I call this function like this : 
`var PointLayer = ToCentroid(PolygonLayer.getLayers()).addTo(map);`

But I don't know how to write the properties option for the `turf.centroid()` function.

I tried with `polyList[i].feature.properties` but it did not work...

Can someone help me ?

Here is a JSFiddle test : 
http://jsfiddle.net/08xaeLdq/

**Comment by sylvain-m** [comment]
I tried `turf.centroid(polyList[i].toGeoJSON(), {properties : polyList[i].feature.properties})` but still don't work...
I should not be far from the solution, but I think I need some help...  :stuck_out_tongue_winking_eye:

**Comment by sylvain-m** [comment]
Sorry for the inconvenience
The problem was that I did not call the latest version of Turf.
With the latest version, it works well with this code:

```
function onEachFeature(feature, layer){
    popupContent = "<b>Nombre d'observation(s): </b>"+ feature.properties.nb_observations+ " <br>" +
    "<b>Année : </b>" + feature.properties.annee + " <br>";
    layer.bindPopup(popupContent);
}
```

However, if you have any improvement on this code, I'm interested in your advice!

**Comment by rowanwins** [comment]
Gday @sylvain-m 

Glad you got it sorted, your code looks good to me!
