### ISSUE TITLE
Using turf.js in Cordova project doesn't work

### ISSUE THREAD

**Issue by vishakhavaidywan** [Turfjs/turf#1471]
I am trying to create a dot density map visualization in my cordova ionic mobile application and I am failing to load turf.min.js.

I included it in the index.html file as:

`<script src="js/libs/turf.min.js" charset="utf-8"></script>`

As soon as the app loads, I can see this error in the console:

**Uncaught TypeError: Cannot redefine property: name**

The turf object comes out to be undefined where I am using it in code.

I am stuck badly at this, please help!!

**Comment by rowanwins** [comment]
Where has your `turf.min.js` come from - is it a file you've downloaded from somewhere?

**Comment by vishakhavaidywan** [comment]
Yes, its a library for advanced geospacial analysis. Here is the link to its official website.
http://turfjs.org/

**Comment by vishakhavaidywan** [comment]
I downloaded the file from the github link for the project -
https://github.com/Turfjs/turf
I tried using the non-minified `turf.js`, it is working fine for me. But the error with the minified file is still there!

**Comment by rowanwins** [comment]
Hmmm that is strange. Perhaps try a slightly older version of the minified like [5.1.0](https://npmcdn.com/@turf/turf@5.1.0/turf.min.js) or [4.7.3](https://npmcdn.com/@turf/turf@4.7.3/turf.min.js) and see if either of those work for you...

**Comment by morganherlocker** [comment]
Stale.
