### ISSUE TITLE
Just published a bridge library to use google.maps along with Turf

### ISSUE THREAD

**Issue by amenadiel** [Turfjs/turf#1474]
I just published my library [turf-google-maps](https://www.npmjs.com/package/turf-google-maps) to NPM.

It allows to use a subset of turf methods on google maps objects (such as Polygons and Polylines) to simplify, create buffers, find kinks, unkink them, perform union of polygons and more.

I thought you guys might be glad to know, since it might help broaden the audience of this awesome library (or collection of libraries).

Caveat: I'm using v5.x modules. I haven't been able to build version 6 modules using Rollup yet.

**Comment by stebogit** [comment]
Nice @amenadiel! 👍

**Comment by rowanwins** [comment]
Nice on @amenadiel - one day I'd like a page in the docs to share some of the things that have been built around the turf ecosystem, one day one day :)
