### ISSUE TITLE
turf import doesn't work for webpack project (Typescript)

### ISSUE THREAD

**Issue by AntonPilyak** [Turfjs/turf#1476]
Steps to reproduce:

1. npm -i @turf/turf  (got "@turf/turf": "^5.1.6")
2. import * as Turf from '@turf/turf';

Error TS2306: {my_path}/node_modules/@turf/turf/turf.min.js is not a module.

Am I doing something wrong or is it an issue? Is there a workaround?

**Comment by rowanwins** [comment]
Hi @AntonPilyak 

A lot depends on the setup of your project. Turf isn't bundled as a ES6 module and so you would need to be applying some sort of build process that enabled that to work, so it'll depend on what your webpack or babel setup might include.

**Comment by stebogit** [comment]
Hey @AntonPilyak does this maybe help? https://github.com/Turfjs/turf/issues/1478#issuecomment-419127691

**Comment by eranimo** [comment]
Having the exact same issue. It's still a problem

**Comment by mfedderly** [comment]
Please try using 6.2.0 or higher, this should be fixed.
