### ISSUE TITLE
Marching Squares on curvilinear grid

### ISSUE THREAD

**Issue by IMMSPgisgroup** [Turfjs/turf#1477]
Hi,
We see in "Isosurfaces geometry, topology, and algorithms" Rephael Wenger page 45 that 

> Sections 2.2 and 2.3 describe the Marching Squares and Marching Cubes
algorithms for regular grids where each grid element is a geometric square or
cube. These algorithms work equally well for curvilinear grids that have the
same combinatorial structure as regular grids but whose elements are convex
quadrilaterals or hexahedra.
> 
That is Marching Squares may be used for curviliniar grid. Realization https://github.com/RaumZeit/MarchingSquares.js that included in TurfJS, in principle allow using curvilinear grid. But in TurfJS this feature not used. In https://github.com/Turfjs/turf/blob/master/packages/turf-isolines/index.js function rescaleIsolines(createdIsoLines, matrix, points) aceptable only for regular grid.

**Comment by rowanwins** [comment]
Hi @IMMSPgisgroup 

We're open to pull requests if you'd like to add some functionality. That said yours is a very particular use case so maybe you are better off using the `MarchingSquares.js` repo directly rather than via TurfJS

**Comment by IMMSPgisgroup** [comment]
Hi rowanwins
We use MarchingSquares.js directly (but in latest version something strange :( - [https://github.com/RaumZeit/MarchingSquares.js/issues/19](url),  [https://github.com/RaumZeit/MarchingSquares.js/issues/18](url) ). We made tool for transormation result MarchingSquares.js (MarchingSquares.js works for curvilinear grid, but coordinates not real) for curvilinear grid. We rely for most Turf-familiar tool, becose isoline for curvilinear grid need not only for us.

**Comment by morganherlocker** [comment]
I don't think there is an actionable request or issue here, but please reopen if more detail is provided.
