### ISSUE TITLE
Missing index.d.ts file in distance package

### ISSUE THREAD

**Issue by pcernek-spare** [Turfjs/turf#1493]
The [@turf/distance](https://github.com/Turfjs/turf/tree/master/packages/turf-distance) package has an `index.ts` file, but not an `index.d.ts`. Therefore, when I use it in my Typescript project and try to compile, I get:

```
Could not find a declaration file for module '@turf/distance'.
```

...because I have `"noImplicitAny": true` set in my project's package.json.

It looks like other packages (such as [@turf/bbox](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox)) **do** have `index.d.ts` files, and I would rather not have to loosen my project configuration to be able to use this package.

**Additional context**
- Some guidelines on publishing types for turf packages: https://github.com/Turfjs/turf/issues/1412#issuecomment-396915653
- The `index.d.ts` file can easily be generated by running the following command:
```
lerna run prepare --scope @turf/distance -- --declaration
```

**Comment by HarelM** [comment]
Any updates on this?
