### ISSUE TITLE
booleanCrosses, booleanContains : two polygon, return error: feature2 Polygon geometry not supported

### ISSUE THREAD

**Issue by szoyaung** [Turfjs/turf#1494]
use booleanCrosses,  params are two polygon, then return error: feature2 Polygon geometry not supported.
and booleanContains return the same error.

**Comment by szoyaung** [comment]
Hi @rowanwins 
thanks for your answer！
Your guess is possible. the polygons may do not have any relationships，but just like that，should the interface（booleanCrosses/booleanContains） return to false like the 'intersect' return null?

**Comment by morganherlocker** [comment]
> TBH I'm not sure why this is and I'd be open to changing it - it does seem curious to me that the relationships don't exist for polygon to polygon but perhaps there is a good reason...

We follow simple feature specification in so far as it defines valid, unambiguous geometries. This is necessary for ensuring repeatable results. For example, a self intersecting polygon could be interpreted as "inside out", covering most of the the earth, but most people would not prefer this strict interpretation. Instead. we ask for clean geometries up front.

**Comment by mfedderly** [comment]
We should probably document that this limitation exists and leave it at that.

**Comment by mfedderly** [comment]
Looks like @turf/boolean-contains does support polygon/polygon for its two args, so just a quick docs fix for @turf/boolean-crosses.
