### ISSUE TITLE
How to create square grid inside polygon?

### ISSUE THREAD

**Issue by ShahriatHossain** [Turfjs/turf#1495]
I am trying to create square grid inside polygon I have drawn on openlayers with turf library.

For example:
```
    var extent = polygon.getSource().getExtent(); // this is openlayer polygon I have drawn

    //this is the output of extent variable:
   //0: 12972892.440560114
   //1: -3785467.388795069
   //2: 13060947.897144636
   //3: -3677844.0529695405

     var vectorSourcePolygons = new ol.source.Vector();

      var poly = turf.squareGrid(extent, 10, 'miles');

      vectorSourcePolygons.addFeatures((new ol.format.GeoJSON()).readFeatures(poly, {
        dataProjection: "EPSG:4326",
        featureProjection: "EPSG:3857"
      }));

      var vectorLayerPolygons = new ol.layer.Vector({
        source: vectorSourcePolygons,
        style: [
          new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: [0, 121, 88, 1],
              width: 1
            })
          })
        ]
      });

      olMap.addLayer(vectorLayerPolygons);
```

The above scenario doesn't produce any result in my openlayer map.
Any help will be appreciated. Thanks.

**Comment by stebogit** [comment]
@ShahriatHossain Turf [uses the WGS84](https://github.com/Turfjs/turf/blob/master/README.md#data-in-turf) coordinate system, so you need to convert the `extent` values.

**Comment by ShahriatHossain** [comment]
@stebogit I am also facing a problem like I have drawn a polygon and created square grid inside the polygon which works fine, but when I draw another polygon and trying to square grid inside this  polygon then the previous one breaking down. Not sure what could be the reason. Can you help me what is the way to create square grid for multiple polygon?

**Comment by rowanwins** [comment]
Hi @ShahriatHossain 

What version of TurfJS are you using?

The current syntax is 
````
var squareGrid = turf.squareGrid(bbox, 10, {
   units: 'miles'
});
````

Also worth noting that square-grid only works on a single polygon, or a multi-polygon, it won't work on a FeatureCollection of polygons.

Hope that helps

**Comment by morganherlocker** [comment]
Resolved (I think). Feel free to reopen with requested details.
