### ISSUE TITLE
How to add pushpin inside of each cell of turf square grid?

### ISSUE THREAD

**Issue by ShahriatHossain** [Turfjs/turf#1496]
I am using turf and openlayers together. I am creating square grid of turf on openlayers map which works fine. But I want to add push pin for each cell of square grid. Is it possible? Need experts help. Thanks.

Here is the code sample of turf's square grid:

```
var bbox = [-95, 30 ,-85, 40];
var cellSide = 50;
var options = {units: 'miles'};

var squareGrid = turf.squareGrid(bbox, cellSide, options);

//addToMap
var addToMap = [squareGrid]
```

**Comment by stebogit** [comment]
@ShahriatHossain I'm not familiar with OpenLayers and I'm not sure what a pushpin is, but this should give you one possible solution to define a point in the middle of each cell of the grid:
```js
var bbox = [-95, 30 ,-85, 40];
var cellSide = 50;
var options = {units: 'miles'};

var grid = turf.squareGrid(bbox, cellSide, options);

var pins = [];
turf.featureEach(grid, function (cell, idx) {
	console.log(cell);
	var pin = turf.centroid(cell, {"marker-color": "#00F"});
  pins.push(pin);
});
```
If you need more OpenLayers specific information I suggest you to post on StackOverflow or other map specific websites.
