### ISSUE TITLE
squareGrid, hexGrid do not line when using multiple grids as tiles on a map overlay

### ISSUE THREAD

**Issue by keithfraley** [Turfjs/turf#1500]
I have a series of turf grids that are created on the fly based on the end users zoom extent.  That zoom extent is actually 8 separate requests with bounding boxes that line up perfectly with each other.  When I create a grid for each of the requests in theory they should line up perfectly but I am getting a gap between the tiles.  I have hightlighted in green the gap, I have triple checked the bounding boxes and they line up, but the grids create from the bounding boxes do not

![onpaste 20181002-220651](https://user-images.githubusercontent.com/3977556/46388035-8fcd0080-c68f-11e8-8c0f-f7d542e0b269.png)

**Comment by keithfraley** [comment]
![onpaste 20181002-220948](https://user-images.githubusercontent.com/3977556/46388092-ea665c80-c68f-11e8-84aa-edc6dbcf7782.png)

**Comment by keithfraley** [comment]
if (esQuery.body.query.bool.filter !== undefined) {
                            topleftx = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].top_left[0];
                            toplefty = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].top_left[1];
                            bottomrightx = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].bottom_right[0];
                            bottomrighty = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].bottom_right[1];
                        }
                        var bbox = [topleftx, bottomrighty, bottomrightx, toplefty];
                        
                        if (bottomrighty > 0)
                        {
                            var from = turf.point([topleftx, bottomrighty]);
                            var to = turf.point([bottomrightx, bottomrighty]);

                        }
                        else
                        {
                            var from = turf.point([topleftx, toplefty]);
                            var to = turf.point([bottomrightx, toplefty]);
                        }
                        var options = { units: 'kilometers' };
                        var distance = turf.distance(from, to, options);
                        var cellSide = distance / 15;
                        var hexgrid = turf.squareGrid(bbox, cellSide, options);

**Comment by keithfraley** [comment]
` if (esQuery.body.query.bool.filter !== undefined) {
                            topleftx = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].top_left[0];
                            toplefty = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].top_left[1];
                            bottomrightx = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].bottom_right[0];
                            bottomrighty = esQuery.body.query.bool.filter.geo_bounding_box[indexConfig.geometryField].bottom_right[1];
                        }
                        var bbox = [topleftx, bottomrighty, bottomrightx, toplefty];
                        
                        if (bottomrighty > 0)
                        {
                            var from = turf.point([topleftx, bottomrighty]);
                            var to = turf.point([bottomrightx, bottomrighty]);

                        }
                        else
                        {
                            var from = turf.point([topleftx, toplefty]);
                            var to = turf.point([bottomrightx, toplefty]);
                        }
                        var options = { units: 'kilometers' };
                        var distance = turf.distance(from, to, options);
                        var cellSide = distance / 15;
                        var hexgrid = turf.squareGrid(bbox, cellSide, options);`

**Comment by stebogit** [comment]
I have the suspect, just a thought, the issue might be related to the fact that Turf `distance` is calculated on the actual earth's curved/spherical surface, so the projection of that on the plane surface of the web map result shorter. You might want to try using a Mercator or euclidean distance instead to fin your `cellSide`.

**Comment by keithfraley** [comment]
I am certain it is the cell size, not really sure how to fix it.  If I change the units the gap will get marginally smaller or sometimes flip vertically.  

Is there a turf function for calculating mercator distance?

**Comment by stebogit** [comment]
@keithfraley there is not a Mercator/Euclidean distance method, yet, but you can find the actual code [here](https://github.com/Turfjs/turf/issues/1017). Feel free to submit a PR to add the function to Turf if you like 😃

**Comment by morganherlocker** [comment]
I believe the issue here is that the cell size is determined by measuring the geodesic distance a single time at the bottom left corner of a grid, so calculating multiple will shift the cell size unless the bbox stays exactly the same. This behavior is intended, since the grid modules were designed for localized analysis. I would recommend instead using a module that provides systematically consistent alignment such as [@mapbox/tile-cover](https://github.com/mapbox/tile-cover), which is able to bin features into quadtree cells. For hex grids, I would recommend exploring [h3-js](https://github.com/uber/h3-js), which has a similar design to tile-cover, although I have not used it myself yet.
