### ISSUE TITLE
Grid Skew on large bbox

### ISSUE THREAD

**Issue by cmtoomey** [Turfjs/turf#1505]
Similar to #758 - we are getting strange skew for grids that utilize a large bbox (world scale)

[Hex](https://runkit.com/embed/ff9fria9sgqf)
[Square](https://runkit.com/embed/cr0ng5238bqy)

We are seeing similar results in our production application, regardless of grid size. 

Square
![image](https://user-images.githubusercontent.com/12201602/46495460-5351ef80-c7ca-11e8-9e2b-20eb2e231204.png)

Hex 
![image](https://user-images.githubusercontent.com/12201602/46495495-65339280-c7ca-11e8-9189-012f5561e914.png)

It looks like the fix in #758 didn't resolve this for @turf/square-grid or @turf/hex-grid

@DenisCarriere - is it possible to get this resolved?

cc @mtirwin

**Comment by mtirwin** [comment]
@DenisCarriere asking because we know you're super close to the issue and the codebase. Even if you don't have time to submit a PR, getting any guidance you can offer on approach would be 👌.

**Comment by cmtoomey** [comment]
Additional context - this issue doesn't appear for smaller bounding boxes.

cc @morganherlocker @mourner for potential thoughts on an approach to fix.

**Comment by stebogit** [comment]
@cmtoomey have you read #1059?

I believe it all depends on the projection distortion. You might wanna try playing with [`@turf/projection`](https://github.com/Turfjs/turf/tree/master/packages/turf-projection) and see if that helps when the bbox is large enough to generate the issue.

**Comment by rowanwins** [comment]
Hi @cmtoomey & @mtirwin 

Thanks for reporting the issue, looks like something funky going on, today said there is no need to cc in ppl within 2 hours, particularly when they aren't actively involved in the maintenance of the library.

I've just [released](https://github.com/Turfjs/turf/issues/1499) an alpha of v7 which is a fairly big overhaul of the structure of the lib.

I'll take a look at it when i get a chance but if you've got time to look into the issue feel free.We're open to pull requests against the v7 branch.

Cheers
Rowan

**Comment by cmtoomey** [comment]
@rowanwins 
Thanks for the note about alpha - our team will look at that and #1059 per @stebogit and see if that can get us a quick fix. The CCs were more to get some internal visibility on the issue - not to cause a small 🔥 

We think we have a workaround for now, but if someone could take a look at some point in the future, it would be much appreciated. I'll close for now.
