### ISSUE TITLE
Why intersect return null ？

### ISSUE THREAD

**Issue by cooljser** [Turfjs/turf#1513]
When i use turf.intersect to judge the relation between tow polygons like below, it return null, could someone tell me what happened?
[http://jsfiddle.net/cooljser/o1w2ezaj/](http://jsfiddle.net/cooljser/o1w2ezaj/)

**Comment by rowanwins** [comment]
Hi @cooljser 

I don't seem to be able to access that fiddle...

**Comment by cooljser** [comment]
Thanks for reply, i'm so sorry that i pasted a wrong link. Now i already solved this problem, because i used the wrong intersect version.
