### ISSUE TITLE
Type checking included turf library in typescript fails for nearest-point-to-line and point-to-line-distance

### ISSUE THREAD

**Issue by tel** [Turfjs/turf#1518]
When type checking a project including turf two `d.ts` files seem to not get registered properly. This can be trivially fixed by adding local declarations (copied from the relevant ones in the repo), but it's not obvious and leads to a rougher onboarding experience.

## To replicate

Install turf as part of a package and try to check using typescript

`tsconfig.json`
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react",
    "module": "commonjs",
    "noEmit": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "outDir": "./dist/",
    "sourceMap": true,
    "strict": true,
    "target": "es5"
  },
  "include": ["./src/**/*.ts", "./src/**/*.tsx"],
  "exclude": ["./dist/", "./node_modules"]
}
```

```
$ tsc
node_modules/@turf/turf/index.d.ts:34:45 - error TS7016: Could not find a declaration file for module '@turf/nearest-point-to-line'. '/Users/jabrahamson/Development/cibo/ursa-web/node_modules/@turf/nearest-point-to-line/index.js' implicitly has an 'any' type.
  Try `npm install @types/turf__nearest-point-to-line` if it exists or add a new declaration (.d.ts) file containing `declare module '@turf/nearest-point-to-line';`

34 export {default as nearestPointToLine} from '@turf/nearest-point-to-line';
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@turf/turf/index.d.ts:84:46 - error TS7016: Could not find a declaration file for module '@turf/point-to-line-distance'. '/Users/jabrahamson/Development/cibo/ursa-web/node_modules/@turf/point-to-line-distance/index.js' implicitly has an 'any' type.
  Try `npm install @types/turf__point-to-line-distance` if it exists or add a new declaration (.d.ts) file containing `declare module '@turf/point-to-line-distance';`

84 export {default as pointToLineDistance} from '@turf/point-to-line-distance';
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
```

**Comment by pietrovismara** [comment]
Same here

**Comment by HarelM** [comment]
Same here, any workaround for this?

**Comment by jfavrod** [comment]
Installing the referenced packages resolved the issues for me:
```
npm i @turf/nearest-point-to-line
npm i @turf/point-to-line-distance
```

**Comment by pleerock** [comment]
This problem [is fixed in repository itself](https://github.com/Turfjs/turf/tree/master/packages/turf-nearest-point-to-line), but in there version is 6.0.0 while `turf` itself uses `5.1.6`. On turf dependency must be updated to 6.0.0. This will fix this issue.

**Comment by fabianmoronzirfas** [comment]
I'm also running into this issue

> On turf dependency must be updated to 6.0.0.

What do you mean by ☝️ ?

**Comment by Naitik333** [comment]
Can some admin please release 6.0.0 version of @turf/turf module, so that this issue gets fixed and also we get the latest version of all the modules.

**Comment by jeisonng** [comment]
> Installing the referenced packages resolved the issues for me:
> 
> ```
> npm i @turf/nearest-point-to-line
> npm i @turf/point-to-line-distance
> ```
> 
> This will install the latest version of these packages (currently `6.0.0`)

Working for me

**Comment by pmeller** [comment]
Possible temporary fix for Yarn users is to define [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) in `package.json`:

```json
{
  ...
  "resolutions": {
    "@turf/nearest-point-to-line": "6.0.0",
    "@turf/point-to-line-distance": "6.0.0"
  }
```
