### ISSUE TITLE
Bug calculating distance

### ISSUE THREAD

**Issue by jsnoble** [Turfjs/turf#1520]
There is a bug on how the distance function works. I was originally trying to create a circle from a center point but noticed that the results were drastically off. I set a coordinate point randomly in Mesa Arizona with a distance of 5km and it gave me coordinates to Bermuda.

Code snippet:
```
const results = turf.destination([ 33.435518, -111.873616 ], 5, 0);
console.log(results.geometry.coordinates)  
//  it logs [33.435518, -68.17135001818623]
```

**Comment by stebogit** [comment]
so @jsnoble, no bug? 😄

**Comment by jsnoble** [comment]
Its the age old issue of lat/long vs long/lat. All the systems I work with are lat/long, and I didn't see anything anything at a glance that this was a long/lat code base at first. It works if I reverse the coordinates. Ugg.... why can't there be a real non arbitrary standard, its frustrating.

**Comment by stebogit** [comment]
Yeah that happens sometimes.
In addition to [this note on the readme](https://github.com/Turfjs/turf#data-in-turf), would you suggest anything else to make it more obvious?

**Comment by jsnoble** [comment]
Maybe it would be helpful to put it in http://turfjs.org/ ?  I realize this
is totally my fault for not reading the entire readme. As I was browsing
different geo libs to build out the feature I was working on I briefly went
over the readme since it did not have the api so I only read the part to
install and then I went to http://turfjs.org/ for everything after that.
