### ISSUE TITLE
Why intersect return null in the below case ?

### ISSUE THREAD

**Issue by cooljser** [Turfjs/turf#1521]
[http://jsfiddle.net/cooljser/vh4upbo1/](http://jsfiddle.net/cooljser/vh4upbo1/)

**Comment by vamshi29292** [comment]
The `martinez-polygon-clipping` package used to find intersection of polygons is returning an empty array.
http://jsfiddle.net/1e8pohry/

**Comment by cooljser** [comment]
I don't understand. In my example the two graphics should be intersecting.

**Comment by rowanwins** [comment]
This works in v7
http://jsfiddle.net/1e8pohry/2/

**Comment by cooljser** [comment]
Thanks.
