### ISSUE TITLE
Missing Types for TypeScript When Using turf/circle Directly

### ISSUE THREAD

**Issue by ksylvest** [Turfjs/turf#1523]
Using:

```typescript
import * as circle from '@turf/circle';
```

> Could not find declaration file for module '@turf/circle'. node_modules/@turf/circle/index.js implicitly has 'any' type.

Using:

```typescript
import { circle } from '@turf/turf'; // OK
```

It looks like no index.d.ts file is setup here: https://github.com/Turfjs/turf/tree/master/packages/turf-circle Is that needed?

**Comment by brendanmc6** [comment]
I found the problem: the `index.ts` file should actually be named `index.d.ts`

Submitting a PR now.
