### ISSUE TITLE
Crosstrack

### ISSUE THREAD

**Issue by jczaplew** [Turfjs/turf#153]
I wrote a turf-flavored module for calculating the distance between a point and a line segment - https://github.com/jczaplew/turf-crosstrack

If you would like to add it to Turf, I will happily transfer ownership to the organization.

**Comment by DenisCarriere** [comment]
Seems like this type of module would easily be solved with [`@turf/point-on-line`](https://github.com/Turfjs/turf/tree/master/packages/turf-point-on-line) & [`@turf/distance`](https://github.com/Turfjs/turf/tree/master/packages/turf-distance). I also agree with Morgan tha this type of module sounds like it would be a "one off use case".

Closing for now.
