### ISSUE TITLE
import circle undefined

### ISSUE THREAD

**Issue by HuangHuaYe** [Turfjs/turf#1532]
import { circle } from 'turf';

variable circle undefined.

**Comment by stebogit** [comment]
@HuangHuaYe
I believe the correct syntax would be
```js
import { circle } from '@turf/turf';
```

However, since the project is module based, you should probably just import the module you are interested into:
```js
import circle from '@turf/turf-circle';
```

**Comment by HuangHuaYe** [comment]
OK, thanks.
