### ISSUE TITLE
distance, nearest return  wrong values with wrong unit

### ISSUE THREAD

**Issue by citymeterio** [Turfjs/turf#1534]
I'm using "@turf/turf": "^5.1.6.

Steps: 
1) using google maps  I'm picking two points which by walk are almost 1 kilometer and I'm sure it is ~1km
2) putting those point to turf.distance or nearest without options gaves me ~1.6km ( so it is one mile)
3) when I provide unit as "miles" it gives me ~1km

what is wrong or maybe what I'm doing wrong?

**Comment by stebogit** [comment]
@citymeterio on [geojson.io](http://geojson.io) those two points looks like are ~1 mile apart, not ~1km

![screen shot 2018-11-25 at 10 28 52 am](https://user-images.githubusercontent.com/12717225/48982887-050bef00-f09d-11e8-8ddd-716f206e3cd4.png)

**Comment by rowanwins** [comment]
QGIS also provides similar results, it looks like your points are approx 1.6km apart.

**Comment by citymeterio** [comment]
I just had to use flip metod to swap the coordinates
