### ISSUE TITLE
Download version 6

### ISSUE THREAD

**Issue by wafisher** [Turfjs/turf#1535]
How do I download version 6.0.0?

I see that dcfaa10fb946f5adf947bd8e8add430ef354a415 bumped the version, which in theory would allow me to use

    "@turf/turf": "^6.0.0"

But npm doesn't have the latest version (https://www.npmjs.com/package/@turf/turf).

Thoughts?

**Comment by rowanwins** [comment]
Hi @wafisher 

Version 6 was never published as a full release and most of the individual modules that were published should be thought of as alpha releases, unfortunately they weren't tagged that way.

Hopefully that helps
