### ISSUE TITLE
@turf/mask endlessly loops if mask contains enough features

### ISSUE THREAD

**Issue by vallendm** [Turfjs/turf#1537]
I'm trying to use @turf/mask to create a mask with multiple features. 

See https://jsfiddle.net/s4p3rvg1/11/

When NUM_BOXES < 9 is the above fiddle works fine. When I increase the value it never returns. 

I've traced through - and I believe the error is in unionPolygons - which creates an rtree ( rbush ) - and then starts removing items from the tree and merging them. But none of the tree removals work - unless the topNode is also a leafNode.

I replaced the calls to remove with this 
```        
        // get the bbox of the item we want to remove
        var currentBBox = turfBBox( currentFeature.geometry );
        // pass the bbox into the remove call. 
        tree.remove({index: currentIndex,
            minX: currentBBox[0],
            minY: currentBBox[1],
            maxX: currentBBox[2],
            maxY: currentBBox[3]
        }, filterByIndex);
```
ie passing in the bbox of the feature to remove - and that works - but I'm not sure if there's a better way to remove the item from the rtree.

**Comment by rowanwins** [comment]
Hi @vallendm 

I've re-written the mask module in the v7 branch and we're pulling in a different union module - from my testing so far it looks like it'll be a bit more robust.

I can be checked on [npm alpha version here](https://www.npmjs.com/package/turf/v/7.0.0-alpha.1)

Would be interested to see how you go

**Comment by vallendm** [comment]
@rowanwins - I just tried the v7alpha branch and there appears to be no problems there.

**Comment by rowanwins** [comment]
awesome - thanks for checking @vallendm !

**Comment by Stophface** [comment]
Unfortunatly, this is still a problem 
https://github.com/Turfjs/turf/issues/2054
