### ISSUE TITLE
turf-skeleton

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#154]
straight skeleton algorithm, which forms the basis for most polygon offset curve algorithms

https://www.cgal.org/UserWorkshop/2004/straight_skeleton.pdf

The general idea is this:

![](https://dl.dropbox.com/s/8d8yp1aprfla4u1/Screenshot%202014-12-04%2014.27.26.png?dl=0)

[CGAL implementation](http://doc.cgal.org/latest/Straight_skeleton_2/index.html#Chapter_2D_Straight_Skeleton_and_Polygon_Offsetting)

**Comment by gmaclennan** [comment]
There's also https://github.com/migurski/Skeletron

**Comment by morganherlocker** [comment]
@gmaclennan Skeletron no longer uses a straight skeleton, but I was able to dig through the repo and find a commit where it still had the code around. No idea how robust the implementation is, but it might be a good reference. https://github.com/migurski/Skeletron/blob/74103e06c726f953db50b9dad98718d4bff05cdf/Skeletron/__init__.py

**Comment by vlasvlasvlas** [comment]
nice, love the different approaches.

**Comment by tremby** [comment]
> Interestingly, this algorithm can be used for computing road centerlines.

This is what I'm looking for. In particular right now I have some polygonal data for the position a new pipeline will be in, and the things I need to do with this data would be far easier if it were a line rather than a polygon.
