### ISSUE TITLE
@turf/great-circle@5.1.5 not installing

### ISSUE THREAD

**Issue by gusoskar** [Turfjs/turf#1541]
Deleted my node_modules, and cannot reinstall turf. npm install always freezes on @turf/great-circle@5.1.5

**Comment by rowanwins** [comment]
Hi @gusoskar 

Can you let me know what command you are running to install turf?

I've just tried running both `npm install @turf/turf` and `npm install @turf/great-circle` and they both work fine for me

Thanks,
Rowan

**Comment by gusoskar** [comment]
I managed to install it in the end. For some reason it took over 10 minutes, so I thought it wasn't working at all. Thank you @rowanwins.
