### ISSUE TITLE
centerOfMass retains properties for points, not polygons

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1542]
centerOfMass doesn't seem to keep `properties` for a polygon, but it does for a point?

https://runkit.com/stevebennett/centerofmass-inconsistent-retention-of-properties

This was confusing when I was generating labels for a bunch of heterogeneous data.

**Comment by rowanwins** [comment]
Good pickup thanks @stevage - have fixed this in the v7 branch.

**Comment by mfedderly** [comment]
I think this has been fixed, from looking at the code in the PR and the tests that exist today.
