### ISSUE TITLE
Turf Intersect only returning fraction of true intersect

### ISSUE THREAD

**Issue by Harrisandwich** [Turfjs/turf#1544]
I'm using turf in combination with mapbox draw gl to get the intersects of a drawn area. For the most part it seems to work, but sometimes the intersects are incorrect. Only partial geometry is being returned.

**Screenshot**
![screen shot 2018-12-04 at 5 45 40 pm](https://user-images.githubusercontent.com/5429518/49458385-ff28b300-f7ec-11e8-90bd-abb3161cb06a.png)

**Where I'm using intersect to find intersecting features:**
```javascript
const featuresToTest = map.queryRenderedFeatures({ layers: polyLayerIDs })
// getting a polygon feature with turf.polygon helper
// geometry is the geometry of the drawn polygon
const queryFeature = polygon(geometry)
featuresToTest.forEach((feature) => {
    const featureIntersect = intersect(feature, queryFeature)
    if (featureIntersect) {
      const overlappedFeatureArea = area(feature)
      const featureIntersect = intersect(feature, queryFeature)
      const featureIntersectArea = area(featureIntersect)
      const intersectPercentage = featureIntersectArea / overlappedFeatureArea
   }
}
```

**Comment by rowanwins** [comment]
Hi @Harrisandwich 

Are you able to provide the input and output geometries? 

In the v7 branch I've replaced the intersect algorithm and it seems a fair bit more stable. I can test your geometries against that and see how it performs. It's available [here on npm](https://www.npmjs.com/package/turf/v/7.0.0-alpha.1)

Cheers
Rowan

**Comment by Harrisandwich** [comment]
[Here is the GeoJson](https://gist.github.com/Harrisandwich/5b65df51fb40fe9efb177b874a131af2) for a drawn feature used to test for intersects

[And here is an array of features ](https://gist.github.com/Harrisandwich/68fbaeb65c79caf45768fe2261f84c49)that are being tested for intersections

I also installed the new version of turf that you recommended and received this error:
![screen shot 2018-12-05 at 10 29 39 am](https://user-images.githubusercontent.com/5429518/49504071-4492c200-f879-11e8-9aa5-25e0a661fa44.png)

I'm importing 'intersect' and 'area' like so: `import { intersect, area } from '@turf/turf'`

**Comment by Harrisandwich** [comment]
Sorry, I think I was installing the incorrect version of the package. How do I get v7? I tried installing it with npm, but I think I'm missing a crucial step/not understanding something.

**Comment by Harrisandwich** [comment]
I managed to install the v7 branch with `npm install git://github.com/turfjs/turf.git#v7 --save`. I'm testing it now and I'm still seeing missing intersects.

**Comment by Harrisandwich** [comment]
I've testing a few things out and I noticed something that might help...

It seems as though there are a few specific problem features that are an issue every time consistently. This one for example:
![screen shot 2018-12-05 at 3 10 03 pm](https://user-images.githubusercontent.com/5429518/49519066-6fdcd780-f8a0-11e8-8f38-8993a76eb4c0.png)


When drawing a polygon that completely envelopes it, the intersect is incorrect like so:
![screen shot 2018-12-05 at 3 10 26 pm](https://user-images.githubusercontent.com/5429518/49519103-85520180-f8a0-11e8-864e-7423e9496fd4.png)

BUT, when you exclude the right most section of the feature, the intersect looks correct:
![screen shot 2018-12-05 at 3 10 39 pm](https://user-images.githubusercontent.com/5429518/49519144-9c90ef00-f8a0-11e8-80fc-84c73add1c8f.png)

and when you get JUST the right half it's incorrect:
![screen shot 2018-12-05 at 3 11 21 pm](https://user-images.githubusercontent.com/5429518/49519176-b03c5580-f8a0-11e8-92e6-401ce01f0f48.png)

[Here's a gist of the problem feature. Perhaps it will help](https://gist.github.com/Harrisandwich/e2b355ca565b3964685a51cc544fbba3)

**Comment by rowanwins** [comment]
I've just tested with v7 and it looks like it's resolved, take a look at [this jsfiddle](https://jsfiddle.net/mrux30s6/1/)

**Comment by Harrisandwich** [comment]
How do I install v7? I think I have it installed ( my package.json has the following: `"turf": "^7.0.0-alpha.1"`) but I'm still getting the issue.

**Comment by arunasank** [comment]
Question related to ^: I am checking out the v7 branch locally, and linking it as a local dependency to my code. When I do this, a lot of packages, like `lineSplit` and `booleanContains` don't exist. Why is this?

**Comment by Harrisandwich** [comment]
And now I'm getting self intersection errors. I think something is wrong with mapbox's vector tile layer, and not necessarily turf

**Comment by Harrisandwich** [comment]
Okay, now I'm really suspecting this is a vector tile issue somehow. Look at the screenshot below. With a big enough intersection polygon, you can see the tile borders slicing through the intersects:
![screen shot 2018-12-06 at 2 12 56 pm](https://user-images.githubusercontent.com/5429518/49586330-26a08c80-f961-11e8-905c-6a71eceb029e.png)

**Comment by Harrisandwich** [comment]
Ok, I'm sorry about the message spam, but I've figured it out and Turfjs isn't to blame...

Because of the tiled nature of the vector tile mapbox layer, it splits polygons into 2 separate features, but seems to treat them like one feature in all of the major ways (coloring, borders, mouse hover). When creating my list of intersects the second half of the border polygon is being overwritten, leaving me with only the half of the polygon on one side of the tile border. 

Sorry for wasting your time. Perhaps this issue will come in handy to someone googling this issue in the future (though it's an absurd edge case)

**Comment by rowanwins** [comment]
Hi @arunasank 

Best to create a new issue rather than get your issue lost within this one. But basically it's because I'm still fixing some of the treeshaking issues related to certain modules, you can see those modules which are fixed in the [`src/index.js`](https://github.com/Turfjs/turf/blob/v7/src/index.js), the ones commented out need some work still.

**Comment by rowanwins** [comment]
Hi @Harrisandwich 

Yeah vector tiles do present some complexities. This [blog post](https://medium.com/nycplanninglabs/stitching-together-map-tile-fragments-a6698ae1cbf4) & associated repo might provide some help.

Cheers

**Comment by arunasank** [comment]
@rowanwins ah, sorry about that, and thank you for the quick response! ♥️
