### ISSUE TITLE
turf-sector

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#155]
Need to make these for rounded miter joins

![](http://kineme.net/files/composition/gtoledo3/Pacman%20CoreImage.png)

``` js
sector(centerPoint, bearing1, bearing2, radius, units)
```

**Comment by rowanwins** [comment]
Now available in [@turf/sector](http://turfjs.org/docs/#sector)

**Comment by DenisCarriere** [comment]
Nom nom! Pacman 👍 This module put a huge smile on my face when we implemented this!

![image](https://cloud.githubusercontent.com/assets/550895/25118668/40433938-23e5-11e7-80af-f644e917afee.png)

Cheers to @morganherlocker @rowanwins @stebogit !
