### ISSUE TITLE
Browserify build not working as described in the guide

### ISSUE THREAD

**Issue by marcodelpercio** [Turfjs/turf#1550]
Hi,

I just needed to combine @turf/bbox-clip and @turf/line-offset into a browser build using browserify.
I followed the steps described at [http://turfjs.org/getting-started/](http://turfjs.org/getting-started/).
My main.js is as follows:
`
module.exports = {
    bboxClip: require('@turf/bbox-clip'),
    lineOffset: require('@turf/line-offset')
};
`
 and yet when I include my custom turf.js if I look at the **turf** object in console I see
![image](https://user-images.githubusercontent.com/7857757/49993333-501f7080-ff7e-11e8-9d18-a4be626572e4.png)

I can invoke turf.lineOffset as expected however turf.bboxClip appears to be wrapped into something else and the actual function is inside a "default" field.

Any idea why 2 different behaviours? I was expecting turf.bboxClip to be available the same as turf.lineOffset.

Many thanks

**Comment by mfedderly** [comment]
This is likely caused by using `export default function...` in the Typescript modules instead of `export = function...`.
