### ISSUE TITLE
Broken Doc Links

### ISSUE THREAD

**Issue by OmarShehata** [Turfjs/turf#1554]
Go to: http://turfjs.org/docs/

Click on any of the links in the sidebar, it'll try to go to http://turfjs.org/docs/docs#centerOfMass which does not exist.

This is not an issue if you start on http://turfjs.org/.

**Comment by rowanwins** [comment]
Hey @OmarShehata 

Good pickup, thanks. And yep thanks @andrewharvey , I'll take a look into redirecting that page.

**Comment by rowanwins** [comment]
Resolved
