### ISSUE TITLE
Suggesting curators and CDN of most used Turf methods

### ISSUE THREAD

**Issue by ppKrauss** [Turfjs/turf#1560]
Hi, can I suggest here an issue for CDN users? Something as  *"Popular Turf modules CDN"*, a Turf subset of most frequently used Turf modules. 

The [standard CDN for `turf.min.js`](https://cdn.jsdelivr.net/npm/@turf/turf@5/turf.min.js) is a ~600kb file, so big for some applications...  But ~300kb **or less** file is not so big...  There are many Github, GitLab, etc.  projects that use only a little subset of Turf... And supposed that is possible to build a commom  subset that will be a suitable CDN for 50% of more of them.

Curatory statistcs: the curators need only to list a set of *use cases* ([example](https://github.com/tcoupin/leaflet-paintpolygon/blob/master/src/myTurf.js)), with lines of `import _module_ from '@turf/_module_'` ...

PS: another good starting point will be a  [statistics of a *turf-builder*](https://github.com/rowanwins/turf-builder/issues/19).

**Comment by rowanwins** [comment]
Hi @ppKrauss 

Thanks for the suggestion. I'm currently working on the `v7` branch which will be considerably smaller (eg in the vicinity of 200kb) as it'll drop the jsts dependency which is by far our heaviest, hopefully that offers a sufficient resolution.

Cheers

**Comment by ppKrauss** [comment]
Hi  @rowanwins , the answer and the big work that you are doing  with Turf (!).  `v7` seems great!
The parameter "200kb" is personal, perhaps there are other users looking for 50kb ;-)

The main suggestion is to invite people to help seleting a good "popular Turf subset" to a secondary distribution, perhaps a sister-project git, and very easy to maintain (I  can help to build and maintain)... Will be no impact here, we need only your agreement... If success will be generate a broader  user-community for Turf.

**Comment by stebogit** [comment]
It look like on jsDelivr you can [link any specific file inside a GitHub project](https://github.com/jsdelivr/jsdelivr/blob/master/README.md#github).

I wouldn't create a separate project, but I do like the idea of a "Truf-light" or "Turf-essentials". We could simply build a production file for a subset of modules and define (i.e. officialize) new CDN links.
We could even define other specific subset packages like, for instance, "Turf-transform" with the transform modules (and maybe some useful related ones, if that makes sense) for polygon transformation.

**Comment by rowanwins** [comment]
Hey @ppKrauss 

Yeah I see where you're coming from, that's a large part of the reason why turf is available as modules so you can only pull in the bits you need (eg just doing `npm install @turf/area` or whatever). Having a precompiled set of packages available via cdn attempts to fill a similar need although it's even simpler for users as they just pull in the relevant script file. 

In terms of maintenance how do you imagine it work? Say I push an update to the `area` module, how would that flow through to all those pre-compiled bundles that might rely on `area`?

Cheers

**Comment by ppKrauss** [comment]
Hi @rowanwins and @stebogit , there are  [no statistics reference](https://github.com/rowanwins/turf-builder/issues/19#event-2070450784), so a **Turf-essentials** roadmap suggestion:

1. define a recipe to generate the CDA from `npm install @turf/area`, etc. (that is not trivial for mortals, we need a complete recipe to help). Need to define  webpack/browserify/nodular/? and the reference system for recipes (ex. UBUNTU 18).

2. define a group that will be the curators to vote  decisions before to change the  Turf-essentials-modules.  And define one of the  group to be responsible for the updates in general (pull requests for natural updates).

3. Discuss (in the group of item 2) the resurrect the (seems dead) [turf-builder](https://github.com/rowanwins/turf-builder), and the possibility to add statistics there... And perhaps use it is "automatic CDA generator" of the item 1.

**Comment by ppKrauss** [comment]
Hi @stebogit, sorry the confusion with example of `npm install @turf/area`, was another subject, commented by @rowanwins [here](#issuecomment-450768973)  about skills for "create the  precompiled set of packages", I am **not** say that "Turf-essentials" is @turf/area.  The terms "Turf-essentials" and "Turf-transform" are [used by you here](#issuecomment-450745764) and I am using with the **same semantic**.

-----

PS: I will edit and delete the citation of the example  `npm install @turf/area` from my post to avoid more confusion.

**Comment by stebogit** [comment]
@ppKrauss I understand `@turf/area` is just an example of one of the possible essential modules.
I was suggesting to get the statistics of usage/installation for each module via npm API to decide which are the most used and select the "essentials".

Also, I am not clear what you mean by 
> define a group that will be the curators to vote decisions before to change the Turf-essentials-modules.

Again, wouldn't the maintainers be that group?

Finally, why do you need to create a separate project? We could simply create a set of `.min` files like `turf.essentials.min.js` and publish them via CDN the same way we publish `turf.min.js`. Couldn't we?

**Comment by stebogit** [comment]
BTW looks like [turf-builder](https://turfjs-builder.herokuapp.com/) is up and running (_Currently using Turf 5.1.6_)

**Comment by ppKrauss** [comment]
Hi @stebogit ,  

> @ppKrauss I understand `@turf/area` is just an example of one of the possible essential modules.

ok

> I was suggesting to get the statistics of usage/installation for each module via npm API to decide which are the most used and select the "essentials".

Yes, perfect, I agree, if the statistics make sense (some big bias?).

> 
> Also, I am not clear what you mean by
> 
> > define a group that will be the curators to vote decisions before to change the Turf-essentials-modules.
> 

To vote (votes by people from a group of interest) is a **complement** or alternative to the statistics, to define "most important modules" (by personal estimates or opinion) and select the "essentials".


> Again, wouldn't the maintainers be that group?

It is about the person that will do the final pull-requests to create the `turf-essentials.min.js`.

> 
> Finally, why do you need to create a separate project? We could simply create a set of `.min` files like `turf.essentials.min.js` and publish them via CDN the same way we publish `turf.min.js`. Couldn't we?

Because I am dummy, not understand technically how to (it is a complex procedure??)  to create and maintain the `turf-essentials-min.js` .... see  the real fact:

file |  size | comments
----|------|------
[turf.min.js](https://cdn.jsdelivr.net/npm/@turf/turf@5/turf.min.js) | 557K | some "optimized compression?" less modules?
modulesAll.min.js |700K | builder, all modules, why ~150K more?
area-bboxAll-booleanAll-center.min.js | 67K | builder, very basics for spatial analysis
transform-all.min.js | 28K | build, very specific

 so, not make sense (why size of modulesAll is not equal to turf.min?), is not a big gain... Perhaps is impossible to create "essentials" with half of the size, only a very very specialized CDN files. The first step is the fact-checking.

**Comment by rowanwins** [comment]
Hi @ppKrauss 

The `turf-builder` was a project i created many years ago for this sort of use case, it's largely been left untouched but I've added a new maintainer so it now might get a bit more love.

In terms of the size difference between `turf.min.js` and your `modulesAll.min.js` I'm not 100% why they'd be generating different outputs, but probably most likely it's due to different build tools being used. Turf-builder uses [browserify](http://browserify.org/) which used to be popular a few years back. Turf however now uses [rollup](https://rollupjs.org/guide/en) which does a similar thing but is probably more effective at removing redundant code.

With Turf v7 which is in the pipeline it should be possible to create a new and improved version of `turf-builder` which generates more consistent results.

**Comment by stebogit** [comment]
@ppKrauss well I don't know either how exactly the `.min` files are created 😅 

@rowanwins do you have any idea? I searched the code a bit but I didn't found anything clear to me... 😞

**Comment by morganherlocker** [comment]
@ppKrauss This is a good suggestion, but not something we have bandwidth to support. Custom builds are possible to generate with well maintained tools outside Turf, which is the standard level of distribution support provided by most modules. This allows you to mix and match Turf modules however works best for you, providing maximum flexibility.

> @ppKrauss well I don't know either how exactly the `.min` files are created 😅

We have traditionally used the [uglify module](https://www.npmjs.com/package/uglify-js) for generating minified distributions. Combined with browserify, you can create any type of distribution you need by following the docs on those tools.
