### ISSUE TITLE
clean-coords 6.0.1 fails on short, closed linestring

### ISSUE THREAD

**Issue by PizzaBrandon** [Turfjs/turf#1563]
A short (3 point) closed linestring (rare, but does happen) throws an exception in clean-coords due to the code assuming it's a polygon. 

Problem occurs due to https://github.com/Turfjs/turf/blob/master/packages/turf-clean-coords/index.ts#L118 assuming the first and last points matching means it's a polygon.

This can also happen with a linestring that is cleaned to < 4 points. Discovered this when testing clean-coords as a way to help detect certain bad geometries, but a 3-point closed linestring isn't "bad".

Live example:
https://runkit.com/pizzabrandon/5c2d226af5d4340012e87767

**Comment by rowanwins** [comment]
Hey @PizzaBrandon 

Thanks for the excellent bug report, should be relatively easy fix by only applying that check if the geometry type is `Polygon` or `MultiPolygon`.

**Comment by ka7eh** [comment]
Hi @rowanwins and @PizzaBrandon, I created a PR (https://github.com/Turfjs/turf/pull/1764) that fixes this.
