### ISSUE TITLE
Typings for @turf/distance

### ISSUE THREAD

**Issue by goodwin64** [Turfjs/turf#1568]
Hi! It seems that typings for `distance` do not work out-of-the-box.

STR:
1. `npm install --save @turf`
2. `import distance from '@turf/distance';`

Compiler says:
```
Type error: Could not find a declaration file for module '@turf/distance'. 'src/node_modules/@turf/distance/index.js' implicitly has an 'any' type.
  Try `npm install @types/turf__distance` if it exists or add a new declaration (.d.ts) file containing `declare module '@turf/distance';`  TS7016
```
Though if I suppress it, no errors occur while runtime.

When I look into `/distance` module, there is no .ts files there:

![screenshot from 2019-01-13 21-19-13](https://user-images.githubusercontent.com/10671879/51089615-f1196b00-1778-11e9-82a7-069580c4fba2.png)

Tried the following steps to fix:
1. `npm install @types/turf__distance` - 404 Not Found (as turf contains types on its own, not in `types` repo
2. `npm install @types/turf` - old version of typings
3. `npm install @turf/turf` - better, I can use typings as well as `distance` itself, but only in way when I import the entire `turf` lib. So that bundle size increased by 300kb, doesn't fit.
4. `dts-gen @turf/distance` - no `.ts` files there to create the `.d.ts` file

**The question is**: how can I use the single `@turf/distance` module along with TypeScript typings?

**Comment by rowanwins** [comment]
Hi @goodwin64 

Typings aren't my strength and Denis isn't involved in the project at the moment. 

Can you perhaps try one of the version 5 packages available on npm? Some of the version 6 stuff was a bit experimental and wasn't tagged as an alpha unfortunantly, but the v5 stuff should be fairly stable.

Cheers
Rowan

**Comment by asennikov** [comment]
I think the issue is just an incorrectly released version - other @turf/* packages written in ts have `index.d.ts` along with `index.js`, but `@turf/distance` does not.

Maybe somebody from the @turf team could re-release this package only?

**Comment by genintho** [comment]
It is not a packaging issue, the files was removed with this commit 
https://github.com/Turfjs/turf/commit/5fab0fe342b264d8b20a515dc55539191b4fdabe#diff-6d071eff6c43993c40d93a8b2b275048

It is unclear why.

**Comment by asennikov** [comment]
![image](https://user-images.githubusercontent.com/1835550/52164950-d482aa00-270a-11e9-9b2e-463df567f7f5.png)


The `index.d.ts` was removed because the code itself is written in typescript now (`index.ts`), which should be translated into `index.js` + `index.d.ts` during packaging process.

**Comment by mfedderly** [comment]
Also happening for at least these packages:

@turf/centroid@6.0.2
@turf/boolean-within@6.0.1
@turf/nearest-point-on-line@6.0.2

**Comment by goodwin64** [comment]
@rowanwins I'm sorry to disturb but are there any updates on this topic? Whom of the contributors could you suggest to clarify?

**Comment by rowanwins** [comment]
Hi @goodwin64 

Have you tried one of the v5 releases? Packaging a new release for the v6 series is very complicated and unlikely to happen and there shouldn't be any performance difference rolling back to v5.

None of the current contributors have much experience with typescript sorry

**Comment by sebastiangug** [comment]
Any luck with these? Ended up importing the whole package myself even though I only need the distance.

**Comment by yolibernal** [comment]
Using the latest v5 release worked for me 👍

**Comment by AntonPilyak** [comment]
any updates for ^6.0.0?

**Comment by Nkzn** [comment]
my workaround with `@turf/distance@6.0.1`. (require `npm install @types/geojson`)

```ts
// turf-distance.d.ts
declare module "@turf/distance" {
  import { Point, Feature } from "geojson";
  import { Units } from "@turf/helpers";
  function distance(from: Point | Feature<Point> | number[], to: Point | Feature<Point> | number[], options: { units?: Units }): number;
  export default distance;
}
```

**Comment by leonardobazzobonato** [comment]
Try install @types/turf :)

**Comment by charlieforward9** [comment]
This issue is persisting for me when I try to import ANY turf module into my project. 

In my case: `import { point, inside } from "@turf/turf";` shows the error: 

```
Could not find a declaration file for module '...'. '.../node_modules/@turf/.../dist/es/index.js' implicitly has an 'any' type. There are types at '.../node_modules/@turf/.../dist/js/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/...' library may need to update its package.json or typings.
```

Installing `@types/turf` fixes the problem for me, but I get: `npm WARN deprecated @types/turf@3.5.32: 'turf' has been deprecated in favor of '@turf/turf', which provides its own types.`

It'd be nice to not depend on deprecated packages.

**Comment by twelch** [comment]
@charlieforward9 what version of turf are you using? Have you tried the latest v7 alpha on npm? A number of fixes have been made but not yet released under stable

**Comment by charlieforward9** [comment]
@twelch I depend on these versions
``` json
"@turf/turf": "^6.5.0",
"@types/turf": "^3.5.32",
```

**Comment by hydrandt** [comment]
I started to use the prerelease versions of turf packages and the types seem to be defined correctly; all import-related errors were resolved:

```
"@turf/bbox": "^7.0.0-alpha.113",
"@turf/distance": "^7.0.0-alpha.113",
```
