### ISSUE TITLE
Sort a list of points to form a non-self-intersecting polygon

### ISSUE THREAD

**Issue by topclaudy** [Turfjs/turf#1572]
Does the library offer an helper/function for this:

https://cs.stackexchange.com/questions/52606/sort-a-list-of-points-to-form-a-non-self-intersecting-polygon/52627 ?

Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by topclaudy** [comment]
Answer: http://turfjs.org/docs/#unkinkPolygon

**Comment by rowanwins** [comment]
Hi @topclaudy 

Perhaps you're looking for something like our [`concave`](http://turfjs.org/docs/#concave) module?

Cheers
Rowan
