### ISSUE TITLE
Support MultiLineString for lineSliceAlong

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1576]
lineSliceAlong currently doesn't support multiLineString. I think a simple implementation would simply consider the individual LineString's to be connected one to the next, with no consideration of what gap exists between them.

**Comment by morganherlocker** [comment]
> I think a simple implementation would simply consider the individual LineString's to be connected one to the next, with no consideration of what gap exists between them.

This should be implemented by the user, since I can imagine multiple equally valid ways this could function. Closing, but willing to reopen if there is a common usecase for this I am overlooking, where exactly this behavior is expected (could even be a separate module).
