### ISSUE TITLE
TopologyException: side location conflict

### ISSUE THREAD

**Issue by mnvx** [Turfjs/turf#1578]
Cant build intersection of two polygons:

![image](https://user-images.githubusercontent.com/829880/52197740-a23f8c80-2871-11e9-9665-23219ddd6a0c.png)

http://geojson.io/#id=gist:mnvx/241e3eb3cf2ed7d3485c44e4a0c6640b&map=17/45.33278/41.71651

https://jsfiddle.net/mnvx/0av2pf1c/

Error occurs for point
```
x: 41.71643433537568
y: 45.33405320836525
```

I think this issue is linked with #1575 but in this case I have not any ideas how to avoid problem.

**Comment by morganherlocker** [comment]
I inspected your geometry and found two non simple feature compliant edges. The issue in both cases is self overlapping edges, which must be eliminated to be valid turf inputs. 

![52197740-a23f8c80-2871-11e9-9665-23219ddd6a0c](https://user-images.githubusercontent.com/814300/52226339-83d19500-2861-11e9-9a11-b55ed33c875b.png)

**Comment by mnvx** [comment]
> The issue in both cases is self overlapping edges

These edges cant be overlapped because first figure (T) was built as union of many simple rectangles.
Second figure (F) is simple rectangle. I try to intersect them to find area of intersection:

![image](https://user-images.githubusercontent.com/829880/52232672-2b84ac80-28ce-11e9-9dc5-457e8bc94b6c.png)

And as I understand points A and B are translated to one vertex A' by reason of not very high precision of calculations. And two lines BC and CA becomes A'C and CA'. It is reason of exception as I suppose. 
But I have not any ideas about how to reliably avoid this outside of Turf.

**Comment by mnvx** [comment]
As I understand problem in dependency martinez.intersection: https://github.com/Turfjs/turf/blob/3620b83017d015d6b48fa562faa0f15832932ba1/packages/turf-intersect/index.ts#L52

**Comment by fahmad2** [comment]
@mnvx Were you able to resolve this issue? Been having the exact same problem

**Comment by mnvx** [comment]
@fahmad2 I has tried different ways. In result I has resolve issue, but I has ported necessary for me functions of Turfjs to server side for this (Python in my case). https://github.com/zubroide/turfik
