### ISSUE TITLE
Example links are broken

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1582]
Of the four links in the "Examples" section in the top right of the turfjs.org webpage:

- two point to mapbox.com/guides/... and 404
- one points to https://github.com/Turfjs/turf-server-example and is "deprecated".

The fact these haven't been reported suggests also that they weren't very visible to begin with.

**Comment by stevage** [comment]
Oh, actually the "deprecation" was done by @morganherlocker only 11 days ago, and possibly the mapbox.com links only broke in the recently site reorg, so maybe my last comment isn't right.

**Comment by rowanwins** [comment]
Resolved
