### ISSUE TITLE
turf intersect: Each LinearRing of a Polygon must have 4 or more Positions

### ISSUE THREAD

**Issue by francoisromain** [Turfjs/turf#1583]
Please provide the following when reporting an issue:

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Hello, 

I have an error with turf/intersect. Is that something I am doing wrong or a bug?

Thank you

```
const intersect = require("@turf/intersect").default;

const geoJson1 = {
  type: "Feature",
  properties: {
    code: "65242"
  },
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [0.141179, 43.36818], [0.148728, 43.367642], [0.153978, 43.367941], [0.15406, 43.368879], [0.163409, 43.371427], [0.162531, 43.370615], [0.165807, 43.367931], [0.166334, 43.362561], [0.168195, 43.361501], [0.168578, 43.357791], [0.170263, 43.356262], [0.173148, 43.3492], [0.165161, 43.34775], [0.157626, 43.342611], [0.152694, 43.342085], [0.149333, 43.342992], [0.145901, 43.341962], [0.140744, 43.342316], [0.140504, 43.344645], [0.134485, 43.344652], [0.13974, 43.358065], [0.142917, 43.357494], [0.14257, 43.359911], [0.140389, 43.363775], [0.141179, 43.36818]
      ]
    ]
  }
};

const geoJson2 = {
  type: "Feature",
  properties: {},
  geometry: {
    type: "MultiPolygon",
    coordinates: [
      [
        [
          [-0.003511817426206, 43.4699897941247], [-0.003510675548367, 43.379992017286], [0.086492457141402, 43.3799922060496], [0.086492395200926, 43.2899938575523], [0.266499564242721, 43.2899958347523], [0.266498422976084, 43.3799936438263], [0.176495463022904, 43.3799924051132], [0.176494466412028, 43.4699904648683], [-0.003511817426206, 43.4699897941247]
        ],
        [
          [0.221496676867966, 43.3259988784034], [0.221497305021322, 43.3439979092252], [0.248497229697336, 43.3439977847358], [0.248498037469127, 43.3259979174387], [0.221496676867966, 43.3259988784034]
        ],
        [
          [0.149494714775711, 43.3169980868321], [0.149495737551508, 43.3259972246487], [0.140494074719633, 43.3259972052475], [0.140494667441234, 43.3439967446387], [0.131494370741759, 43.3439970882588], [0.131493979866131, 43.3529964603265], [0.122493641497581, 43.3529971097641], [0.122494266127063, 43.370996144705], [0.158495319359878, 43.3709970371161], [0.158494333168507, 43.3619965574681], [0.194496359336044, 43.361996882516], [0.194496951739768, 43.3169982443264], [0.149494714775711, 43.3169980868321]
        ]
      ]
    ]
  }
};

intersect(geoJson1, geoJson2);
```

Throws an error: 
```
Error: Each LinearRing of a Polygon must have 4 or more Positions.
    at Object.polygon (/test-turf/node_modules/@turf/helpers/index.js:213:19)
    at intersect (/test-turf/node_modules/@turf/intersect/index.js:62:34)
    at intersect (/test-turf/node_modules/@turf/intersect/index.js:74:35)
    at intersect (/test-turf/node_modules/@turf/intersect/index.js:102:16)
    at Object.<anonymous> (/test-turf/index.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

**Comment by francoisromain** [comment]
maybe related to this: https://github.com/Turfjs/turf/issues/1497

**Comment by morganherlocker** [comment]
At the very least, all the rings have >4 positions, so the error message is incorrect.

**Comment by GopherJ** [comment]
got the same error:

```
const turf = require('@turf/turf');

const poly = [
    [
        113.934016773462,
        22.3024968145298
    ],
    [
        113.93406067194,
        22.3025093244585
    ],
    [
        113.934064538645,
        22.3024954498103
    ],
    [
        113.934020867621,
        22.3024833947881
    ],
    [
        113.934016773462,
        22.3024968145298
    ]
];

const point = [113.934095926182, 22.3025208344616];

console.log(turf.booleanPointInPolygon(turf.point(point), turf.polygon(poly)))
```

with `@turf/turf: 5.1.6`

**Comment by stebogit** [comment]
Apparently on v5.1.6 and v7.0.0-alpha.1 the error doesn't show up

**Comment by krnbatta** [comment]
Can I draw triangle with turf.polygon?

**Comment by frastlin** [comment]
I am getting this same error using booleanPointInPolygon in v6.5.0. Same problem of my polygon has more than 4 points, but throws this error.

**Comment by rowanwins** [comment]
Resolved since v6.3.0

**Comment by rowanwins** [comment]
@frastlin can you please open a new issue with a full geojson sample, thanks :)

**Comment by blstdmi** [comment]
6.5.0 and 6.3.0 error 

>  geometry: '{"type":"Polygon","coordinates":[[[-176.760127570212,71.404110118003],[-176.729480888485,71.4039808516625],[-176.717698205595,71.4046823978819],[-176.713062032363,71.4049582113492],[-176.698566424868,71.4067220227354],[-176.667895687226,71.4132731398289],[-176.610974127022,71.4232822875088],[-176.590507215765,71.4256232714322],[-176.574512409404,71.4261445354607],[-176.562397893954,71.4248302868158],[-176.550505966222,71.4210810996798],[-176.539034017264,71.4149492951639],[-176.530348046647,71.4076084704096],[-176.526274939604,71.3976868544094],[-176.528873244141,71.3937987444177],[-176.534843962642,71.3895839954709],[-176.548308387278,71.3832287057385],[-176.578588809302,71.3715123595721],[-176.615059030875,71.3608499690022],[-176.626889461509,71.3564266158932],[-176.634770859474,71.3502293980999],[-176.637547329151,71.3356866052879],[-176.642034430269,71.330280395434],[-176.66047301,71.3230501594819],[-176.688121968905,71.3167254091917],[-176.703835124013,71.3144379963086],[-176.718565105755,71.3131938333588],[-176.731514800967,71.3130574930579],[-176.742347252324,71.3140303491327],[-176.755028447724,71.3166103909256],[-176.791275754056,71.3262176842002],[-176.835551357001,71.3354768198006],[-176.874807410875,71.3365282670244],[-176.927840860327,71.3368002900314],[-176.956671080224,71.338494741844],[-176.968532989295,71.3404944864846],[-176.976986176192,71.3432813406615],[-176.991086624871,71.3554514719258],[-176.99943644926,71.3592961208683],[-177.014765839216,71.3622756072223],[-177.056448642552,71.3673608321383],[-177.06868384809,71.3708011582393],[-177.069420839143,71.3746550326303],[-177.057322466386,71.3849126549518],[-177.059419002031,71.3908704084613],[-177.066285959826,71.3959339544042],[-177.09200211464,71.4104347276389],[-177.123608530729,71.4258090792832],[-177.129245281832,71.4301837365324],[-177.130625179733,71.4339973976174],[-177.128049250237,71.4370837857458],[-177.121420282943,71.4403118078708],[-177.119293559238,71.4409334743146],[-177.077776625928,71.4530560672556],[-177.06464683179,71.4592735127098],[-177.062403522284,71.466575616313],[-177.072547504046,71.4831186304429],[-177.072989238718,71.4900350822606],[-177.066118717907,71.4990490961029],[-177.057238776272,71.5070172458593],[-177.048385676582,71.5121160175495],[-177.039745585732,71.5143585118149],[-177.034441745649,71.5142998929957],[-177.028003286494,71.5131552618624],[-177.011191317754,71.5074968815427],[-176.981585714544,71.4943008084667],[-176.963033425223,71.4833181809506],[-176.949732368661,71.470744521203],[-176.944734145236,71.4478517233844],[-176.933658530488,71.439154783248],[-176.920808342953,71.4330326519169],[-176.904467957083,71.4270445421293],[-176.885269559732,71.4214231072192],[-176.864287730394,71.4164843578977],[-176.831211811796,71.4107406067318],[-176.794484320248,71.4063794081507],[-176.760127570212,71.404110118003]]]}',

**Comment by frastlin** [comment]
Hello,
I found the problem:

`polygon([[1,1],[1,2], [2,1], [1,1]])`

throws an error, but:

`polygon([[[1,1],[1,2], [2,1], [1,1]]])`

Does not throw an error and works just fine.

**Comment by stebogit** [comment]
@frastlin that is expected, as a [`Polygon`](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6) is composed of one or more `LinearRings`, which are composed of coordinates. So the coordinates attribute of a polygon must be an array of arrays (lines) of arrays (points). For instance, a polygon with a hole (i.e. doughnut shape) has two lines, one "inside the other".

```js
{
  "type":"Feature",
  "properties":{},
  "geometry":{
    "type":"Polygon",
    "coordinates":[
      [ // external linearRing
        [-121.6021728515625,47.05141149430736],[-121.33300781249999,46.83389173208538],[-120.67932128906249,46.976504510552],[-120.684814453125,47.4057852900587],[-121.25610351562499,47.41322033016902],[-121.640625,47.327653995607115],[-121.6021728515625,47.05141149430736]
      ],[ // internal linearRing
        [-121.343994140625,47.156104775044035],[-121.2615966796875,47.010225655683485],[-120.91003417968749,47.148633511301426],[-121.09130859375,47.27922900257082],[-121.343994140625,47.156104775044035]
      ]
    ]
  }
}
```

![Screen Shot 2022-03-24 at 3 20 34 PM](https://user-images.githubusercontent.com/12717225/160019706-a88fc48d-c7e7-4883-8599-6fbe1279bb25.png)

**Comment by frastlin** [comment]
The error that is thrown when you don't have any internal rings is "Each LinearRing of a Polygon must have 4 or more Positions". There should be another check to throw an error if there are no rings that says something like: "Each polygon must have at least one internal ring of 4 or more positions."

**Comment by stebogit** [comment]
@frastlin a full validation of GeoJSON object is expected to be done by the user before using any Turf modules. The [`@turf/boolean-valid`](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-valid) module (which [might not be perfect](https://github.com/Turfjs/turf/issues?q=is%3Aissue+is%3Aopen+boolean-valid+)) was added to do that.

In other words, Turf modules generally expect valid inputs. Checking if the Polygon's coordinates array contains an array of (valid) LinearRings or (valid) coordinates is not trivial, so it is best keeping that outside the scope of the `intersect` module, in this case.

**Comment by blstdmi** [comment]
Sorry, I may have made a mistake with incorrect data. I'm checking it out
there is no error in the online script, perhaps I will try to reproduce node.js
example of code testing .. some in the project.  

https://codepen.io/bumchigabum/pen/KKZaLLy?editors=1111

**Comment by blstdmi** [comment]
![изображение](https://user-images.githubusercontent.com/16188904/160379343-7e56085d-cbbe-471c-b4f0-008a9110b337.png)

**Comment by ralyodio** [comment]
i'm also getting this error. I tried to filter out with mapshaper but that was unfruitful:

```
$ npx mapshaper -i ne_110m_admin_0_countries.shp -filter 'this.properties.NAME_EN && this.geometry && ((this.geometry.type === "Polygon" && this.geometry.coordinates.every(ring => ring.length >= 4)) || (this.geometry.type === "MultiPolygon" && this.geometry.coordinates.every(polygon => polygon.every(ring => ring.length >= 4))))' -o format=geojson countries.geojson

Error: [filter] Expression must return true or false
Run mapshaper -h to view help
➜  ne_110m_admin_0_countries 

```

**Comment by ralyodio** [comment]
does anyone know how to fix??

**Comment by mariogiampieri** [comment]
I had been dealing with a similar issue, but properly nesting each LinearRing as proposed by @frastlin above and reducing the coordinate precision as described in https://github.com/Turfjs/turf/issues/2310 solved my issue.

**Comment by iyu98** [comment]
I solved this problem. just converted to the depth of the array.
Because some API only supports the two -dimensional array, I wrote one method to solve this problem.

this my code:
```javascript
function getDepth(arr) {
  const depths = []
  arr.forEach(x => {
    let depth = 0
    if (Array.isArray(x)) {
      depth = getDepth(x)
    }
    depths.push(depth)
  })
  return 1 + max(depths)
}

function margeArr(arr) {
  return arr.reduce((a, b) => {
    if (getDepth(b) > 2) {
      a.push(...b)
    } else {
      a.push(b)
    }
    return a
  }, [])
}

const getMulitPolygons = (polygons) => {
  let tempPolygons = [...polygons]
  let dep = getDepth(tempPolygons)
  if (dep < 2) {
    // min depth Two-dimensional array
    return
  }

  if (dep === 2) {
    tempPolygons = [tempPolygons]
  } else {
    while (dep > 3) {
      tempPolygon = margeArr(tempPolygons)
      dep = getDepth(tempPolygons)
    }
  }
  
  return tempPolygons
}


// Usage
const polygon = getMulitPolygons(coordinatesArr)
```

**Comment by welldyrosman** [comment]
> I solved this problem. just converted to the depth of the array. Because some API only supports the two -dimensional array, I wrote one method to solve this problem.
> 
> this my code:
> 
> ```js
> function getDepth(arr) {
>   const depths = []
>   arr.forEach(x => {
>     let depth = 0
>     if (Array.isArray(x)) {
>       depth = getDepth(x)
>     }
>     depths.push(depth)
>   })
>   return 1 + max(depths)
> }
> 
> function margeArr(arr) {
>   return arr.reduce((a, b) => {
>     if (getDepth(b) > 2) {
>       a.push(...b)
>     } else {
>       a.push(b)
>     }
>     return a
>   }, [])
> }
> 
> const getMulitPolygons = (polygons) => {
>   let tempPolygons = [...polygons]
>   let dep = getDepth(tempPolygons)
>   if (dep < 2) {
>     // min depth Two-dimensional array
>     return
>   }
> 
>   if (dep === 2) {
>     tempPolygons = [tempPolygons]
>   } else {
>     while (dep > 3) {
>       tempPolygon = margeArr(tempPolygons)
>       dep = getDepth(tempPolygons)
>     }
>   }
>   
>   return tempPolygons
> }
> 
> 
> // Usage
> const polygon = getMulitPolygons(coordinatesArr)
> ```

what is on max function?

**Comment by iyu98** [comment]
> > I solved this problem. just converted to the depth of the array. Because some API only supports the two -dimensional array, I wrote one method to solve this problem.
> > this my code:
> > ```js
> > function getDepth(arr) {
> >   const depths = []
> >   arr.forEach(x => {
> >     let depth = 0
> >     if (Array.isArray(x)) {
> >       depth = getDepth(x)
> >     }
> >     depths.push(depth)
> >   })
> >   return 1 + max(depths)
> > }
> > 
> > function margeArr(arr) {
> >   return arr.reduce((a, b) => {
> >     if (getDepth(b) > 2) {
> >       a.push(...b)
> >     } else {
> >       a.push(b)
> >     }
> >     return a
> >   }, [])
> > }
> > 
> > const getMulitPolygons = (polygons) => {
> >   let tempPolygons = [...polygons]
> >   let dep = getDepth(tempPolygons)
> >   if (dep < 2) {
> >     // min depth Two-dimensional array
> >     return
> >   }
> > 
> >   if (dep === 2) {
> >     tempPolygons = [tempPolygons]
> >   } else {
> >     while (dep > 3) {
> >       tempPolygon = margeArr(tempPolygons)
> >       dep = getDepth(tempPolygons)
> >     }
> >   }
> >   
> >   return tempPolygons
> > }
> > 
> > 
> > // Usage
> > const polygon = getMulitPolygons(coordinatesArr)
> > ```
> 
> what is on max function?

Sorry, I missed it. Code has been updated.
```javascript
const max = (arr) => {
  return arr.reduce((accu, curr) => {
    if (curr > accu) return curr
    return accu
  })
}
```
