### ISSUE TITLE
Turf-isoline not working with custom point grid 

### ISSUE THREAD

**Issue by ChatzisE** [Turfjs/turf#1585]
Hello. I am trying to implement `turf-isolines` to draw isolines of mean sea level pressure (mslp).
In that regard, I have a array of lon, lat and mslp which I use to create a custom pointGrid.
Then I use this pointGrid with turf.isolines but when it returns, the multilines come without coordinates.
Please see my code below:
```js
drawIsolines(weatherData) {
    let pointGrid = {
        "type": "FeatureCollection",
        "features": []
    };
    for (var i = 0; i < weatherData.length; i++) {
        const feature = {
            "type": "Feature",
            "properties": {
                "mslp": weatherData[i].mslp
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    weatherData[i].lon,
                    weatherData[i].lat
                ]
            }
        };
        pointGrid.features.push(feature);
    };
    var breaks = [950, 960, 970, 980, 990, 1000, 1010, 1020, 1030, 1040, 1050];
    var lines = turf.isolines(pointGrid, breaks, {zProperty: 'mslp'});
    var myStyle = {
        "color": "#575A5D",
        "weight": 2,
        "opacity": 0.65
    };
    L.geoJSON(lines, {
        style: myStyle
    }).addTo(map);
}
```

And see attached the pointGrid that I am feeding to turf.isolines (I uploaded it in txt, since json is not allowed): [mslp.txt](https://github.com/Turfjs/turf/files/2859846/mslp.txt)

Any ideas?

**Comment by stebogit** [comment]
@ChatzisE I don't see any error running it [here](https://jsfiddle.net/jStefano/wmqfu9ho/), which uses turf@5.1.6 BTW.
Looks like you could adjust your `breaks` to produce more isolines with that dataset.

`pointGrid`:
![screen shot 2019-02-13 at 11 45 39 am](https://user-images.githubusercontent.com/12717225/52739047-ea9f2e80-2f84-11e9-8266-573a11cf317f.png)

`lines`:
![screen shot 2019-02-13 at 11 44 45 am](https://user-images.githubusercontent.com/12717225/52739007-d3f8d780-2f84-11e9-8917-ab8816eced16.png)

**Comment by ChatzisE** [comment]
Thank you very much. I have one more question can I change fill-opacity: 0.2; from isobands layer ?

**Comment by stebogit** [comment]
@ChatzisE with both [`@turf/isobands`](https://github.com/Turfjs/turf/tree/master/packages/turf-isobands#isobands) and [`@turf/isolines`](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines#turfisolines) you can pass an `options` object with both a `commonProperties` object, passed to each iso-results, and a `breaksProperties` array (of objects), passed to the correspondent iso-result.

Remember that `@turf/isolines` returns lines, which do no have a `fill-opacity` attribute.

**Comment by Modestgentleman** [comment]
为什么我这个点数据就不能用？mei没有返回结果
[11.txt](https://github.com/Turfjs/turf/files/3497487/11.txt)
![image](https://user-images.githubusercontent.com/17976782/62951348-69820080-be1c-11e9-84b0-7d5b784b8255.png)
