### ISSUE TITLE
The last point of the coordinates returned by lineArc() is not match ‘bearing2‘.

### ISSUE THREAD

**Issue by huanglii** [Turfjs/turf#1587]
I used the **`lineArc()`** to draw arcs, But the last point of the coordinates returned by **`lineArc()`** is not match **`bearing2`**. If increase the param which named **`steps`**, it will be better. 

With my expectation, the first point and the last point should match the **`bearing1`** and the **`bearing2`**.

[The Sample Code by JSFiddle](https://jsfiddle.net/95j1o2dq/)
![image](https://user-images.githubusercontent.com/20068340/52792774-292d0a00-30a7-11e9-9ad4-ebe6df2e4cbe.png)

**Comment by huanglii** [comment]
the line 52, `360` should be changed to `Math.abs(angle2 - angle1)`
`alfa = arcStartDegree + i * 360 / steps;`

**Comment by huanglii** [comment]
the line 52, `360` should be changed to `(Math.abs(arcEndDegree - arcStartDegree))`
`alfa = arcStartDegree + i * 360 / steps;`

**Comment by huanglii** [comment]
This issue is fired when '(bearing2 - bearing1) % (360 / steps) == 0'. At this time, alfa will eaual to arcEndDegree, so the last point is lost.
from [pull request 1590](https://github.com/Turfjs/turf/pull/1590)

**Comment by vwong** [comment]
I'm just stumbling across this bug now, and independently (before I saw this issue), deduced the same fix. What's stopping this from being merged?

**Comment by huanglii** [comment]
Sorry, Did not reply for a long time, thought the submission was wrong.
A new pr([line-arc fix. Resolves #1587](https://github.com/Turfjs/turf/pull/1778)) was opened.
