### ISSUE TITLE
Centroid is acting funny

### ISSUE THREAD

**Issue by wishinghand** [Turfjs/turf#1595]
I've imported Turf as ES6 imports like so (object destructuring didn't seem to work):

```
import * as turf from "@turf/turf"
import * as turfHelper from "@turf/helpers"
```

I then use `centroid` and `multiPolygon`,  in this function:
```
polygonCenter(outline) {
  // almost exactly as the docs have it
  let polygon = turfHelper.multiPolygon(outline)
  let centroid = turf.centroid(polygon)
  return centroid
}
```

the `outline` argument is this array of coordinates:
```
[
  [37.33308330509613, -121.88278019428256],
  [37.33296387451428, -121.88303768634798],
  [37.332759135932186, -121.88287675380708],
  [37.33284444374253, -121.8826085329056],
]
```

I get the error `Error: coordinates must contain numbers"`. Not sure why this would happen as I'm very close to the docs. I use `multiPolygon` instead of `polygon` because `polygon` insists on the equality of the first and last points, which we don't have.

**Comment by stebogit** [comment]
@wishinghand from the [specs](https://tools.ietf.org/html/rfc7946#section-3.1.7): 
> the "coordinates" member is an array of Polygon coordinate arrays

so try using 
```js
const outline = [
  [
    [37.33308330509613, -121.88278019428256],
    [37.33296387451428, -121.88303768634798],
    [37.332759135932186, -121.88287675380708],
    [37.33284444374253, -121.8826085329056],
  ],
];
```

**Comment by wishinghand** [comment]
If I amend my function to this:

```
polygonCenter(outline) {
  let polygon = turfHelpers.multiPolygon([[outline]])
  let centroid = turf.centroid(polygon)
  return centroid.geometry.coordinates
}
```

I don't get any erros, but I'm not sure it's working correctly. I might be misunderstanding exactly what a centroid is. I have a couple of screenshots:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/4001750/53276828-c5619d00-36b5-11e9-9754-32b50b2245bd.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/4001750/53276832-c8f52400-36b5-11e9-9f80-7355be5a81e1.png">

**Comment by morganherlocker** [comment]
Note that there is no single definition for a centroid. There are numerous valid ways to calculate the centroid of a feature. The implementation used here is the geometric centroid, which is defined as the average X and average Y of all coordinates considered. This will sometimes lead to centroids that are outside a polygon hull, in the case of heavily concave polygons.

![](https://user-images.githubusercontent.com/4001750/53276832-c8f52400-36b5-11e9-9f80-7355be5a81e1.png)

Turf also currently implements 3 distinct algorithms for centroids:

- turf.centroid
- turf.center
- turf.centerOfMass

I recommend reading the docs for each and giving them a try to see if another strategy better fits your use case. This is a deep topic, and many cases require a custom strategy, such as label placement or population-weighted centroids.
