### ISSUE TITLE
pointsWithinPolygon is wrong in some cases

### ISSUE THREAD

**Issue by davidgilbertson** [Turfjs/turf#1597]
This snippet doesn't return the point that is on the edge of the polygon:

```js
const polygon = {
  type: "Feature",
  properties: {},
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [-115.1752628, 36.0873974],
        [-115.1752969, 36.0873974],
        [-115.1752969, 36.0874526],
        [-115.1752628, 36.0874526],
        [-115.1752628, 36.0873974]
      ]
    ]
  }
};

const point = {
  type: "Feature",
  properties: {},
  geometry: {
    type: "Point",
    coordinates: [-115.1752799, 36.0874526]
  }
};

const pointsWithinPolygon = turf.pointsWithinPolygon(point, polygon); // no features!
```

If you put the point on the other side of the polygon, it works just fine:
```js
const point = {
  type: "Feature",
  properties: {},
  geometry: {
    type: "Point",
    coordinates: [-115.1752799, 36.0873974]
  }
};
```

I have a map with 700 polygons and a few thousand points, and `pointsWithinPolygon` is failing to detect that a point is on a polygon for about 5 of them. So I'm guessing some rounding issue.

My workaround is to use `turf.buffer(polygon, 0.000001)`, although this is not ideal.

**Comment by rowanwins** [comment]
Thanks for the interesting test case @davidgilbertson . One thing that comes to mind is whether we've got something funky because of the repeated first/last coordinate in geojson... or perhaps as you suggest it's a floating point precision thing...

I'll do some digging and report back

**Comment by davidgilbertson** [comment]
Ah, I just thought of an interesting test case. If you change all the instances of `36.0874526` to `36.0874528` (that is, moving both the line and the point up a bit) then the bug goes away.

That seems to point to floating point.

PS, I'm no expert, but I believe the [first and last values MUST contain identical values](https://tools.ietf.org/html/rfc7946#section-3.1.6) - is that what you meant?

**Comment by rowanwins** [comment]
yeah so according to the geojson spec the first and last point must be the same, however I was wondering if there was anything in our implementation under the hood where we do our maths that might've been contributing to the error, but it sounds like that's not the case.... floating point strikes again (urgh)

**Comment by morganherlocker** [comment]
Thank you for the detailed bug report @davidchouse. I'm classifying this one as `wontfix`, since Turf does not aim to achieve float safe precision (unlike some other geometry libs such as CGAL, which do) for these really tiny measurements. Non-geodesic topology operations also complicate this issue further, so its a very challenging problem with a number of confounding factors at these scales. That said, your report is appreciated, we just won't be able to provide a fix.
