### ISSUE TITLE
turn off greenkeeper

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#1611]
This issue is posted to investigate what's going on with greenkeeper usage and track progress on disabling or repurposing the service. **greenkeeper is generating a lot of issue noise in this repo.** 
<img width="1008" alt="screenshot 2019-03-07 22 46 21" src="https://user-images.githubusercontent.com/814300/54012418-d9cc7d80-412a-11e9-9217-67638c3708d7.png">
I want to disable it, but do not see a straightforward way to do so in the greenkeeper interface -- as a repo admin, but not the originator of greenkeeper integration.  Does anyone care if we disable this? Is `npm audit` a better signal for deps that really need a critical update? We do not have enough contributors to accommodate the update frequency suggested by this service.

**Comment by rowanwins** [comment]
Hi @morganherlocker 

I suspect @DenisCarriere is your man re disabling. I'd be supportive of ditching it for the timebeing :)

**Comment by rowanwins** [comment]
Done
