### ISSUE TITLE
document too new

### ISSUE THREAD

**Issue by magicdawn** [Turfjs/turf#1612]
The document is too new.

http://turfjs.org/docs/#bboxPolygon
I'm using `turf.bboxPolygon(bbox, { properties: { prop: 'value' } })`

but the return feature does not contains `properties`, so I tried `npm i @turf/turf@latest -S` many times 😂, it does not work

So I have to check the source code. the latest version is 5.1.6
and the v5.1.6 code does not contain the `options` argument
https://github.com/Turfjs/turf/blob/v5.1.6/packages/turf-bbox-polygon/index.js#L17-L40

Seems like the  `options` argument will be added in the next version 😢 
https://github.com/Turfjs/turf/blob/ebbdf83962b5f88b15f46b8cd4a0379e4d2a1a81/packages/turf-bbox-polygon/index.ts#L23-L48

**Comment by rowanwins** [comment]
This is now resolved with the release of 6.2.0
