### ISSUE TITLE
How to extract the largest Polygon from a MultiPolygon?

### ISSUE THREAD

**Issue by wzup** [Turfjs/turf#1614]
Is it possible to extract the largest Polygon from a MultiPolygon?

**Comment by stebogit** [comment]
@wzup how about simply looping throw them all and selecting the one with the greater area (using `@turf/area`)?

**Comment by morganherlocker** [comment]
@stebogit's answer is the standard solution here. @wzup please reopen if this does not work for your use case for any reason.

**Comment by wzup** [comment]
@stebogit 

Yep, this is what I'm trying to do now. I decided to ask if there was some best practice or default method to do this.
