### ISSUE TITLE
turf.centroid: What's `lat` and what is `long` in `turf.centroid` result?

### ISSUE THREAD

**Issue by wzup** [Turfjs/turf#1619]
What is `lat` and what is `long` in `turf.centroid` result?

`turf.centroid` returns following result. Where is `lat`? Where is `long`?

```
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [
      0.30126008511782404, // <==Is it Lat? or Long?
      49.719229409425175 // <==Is it Lat? or Long?
    ]
  }
}
```

**Comment by rowanwins** [comment]
Hi @wzup 

Turf uses the geojson format for everything which specifies the coordinates array as [lon, lat].

Hope that helps, if so please close the issue :)
