### ISSUE TITLE
[@turf/clone] - object with key "length" is interpreted as array due to value.length in js code

### ISSUE THREAD

**Issue by udos** [Turfjs/turf#1621]
I have a GeoJSON feature with a key "length":
```js
myGeoJSON = {
    geometry: [...],
    bbox: [...],
    properties: {
        processed: {
            length: {
                orig: 123.456,
                opti: 100.00,
            },
        }
    }
};
```
at some point, `clone` is called, which interprets the processed object as an array due to line
```js
} else if (value.length) {
```
in
```js
/**
 * Clone Properties
 *
 * @private
 * @param {Object} properties GeoJSON Properties
 * @returns {Object} cloned Properties
 */
function cloneProperties(properties) {
    var cloned = {};
    if (!properties) return cloned;
    Object.keys(properties).forEach(function (key) {
        var value = properties[key];
        if (typeof value === 'object') {
            if (value === null) {
                // handle null
                cloned[key] = null;
            } else if (value.length) {
                // handle Array
                cloned[key] = value.map(function (item) {
                    return item;
                });
            } else {
                // handle generic Object
                cloned[key] = cloneProperties(value);
            }
        } else cloned[key] = value;
    });
    return cloned;
}
```
and throws an error...

looking at the TypeScript code, it looks as this is handled properly (source: https://github.com/Turfjs/turf/blob/master/packages/turf-clone/index.ts#L78):

```ts
} else if (Array.isArray(value)) {
```

there might be a reason for this, but it would be nice if JS array identification would be done in a more robust way.

p.s.: meanwhile I change my key :|

**Comment by rowanwins** [comment]
Thanks for the report @udos

**Comment by rowanwins** [comment]
I've just done a quick check and I'm having trouble replicating your error
https://runkit.com/rowanwins/clone-issue

Another option to check out is the v5 series of modules was published using regular js so there shouldn't be any ts to js transformation issues there.

Hope that helps

**Comment by udos** [comment]
@rowanwins, I tried to reproduce on runkit but I'm struggling to understand how to use it properly :|

is it possible that nodejs is using the ts files where the Array identification is properly identified?

note: I'm using the latest versions via npm.  actually I'm using _@turf/simplify_ which at some point calls _@turf/clone_ when the error is thrown.

from your runkit I noticed that _@turf/clone_ is at version 6.0.2. _@turf/simplify_ is at version 5.1.5. _@turf/clone_ is a dependency of _@turf/simplify_ (_package-lock.json_):
```
"@turf/simplify": {
      "version": "5.1.5",
      "resolved": "https://registry.npmjs.org/@turf/simplify/-/simplify-5.1.5.tgz",
      "integrity": "sha1-Csjyei60IYGD7dmZjDJ1q+QIuSY=",
      "requires": {
        "@turf/clean-coords": "^5.1.5",
        "@turf/clone": "^5.1.5",
        "@turf/helpers": "^5.1.5",
        "@turf/meta": "^5.1.5"
```
so _@turf/clone_ is "locked" at version 5.5. I will try to re-install _@turf/simplify_ to see if this changes.
`npm outdated` did not indicate me outdated turf components...

**Comment by rowanwins** [comment]
As yes ok with v@5.1.5 of clone I'm seeing the issue, looks like the offending code is [here](https://github.com/Turfjs/turf/blob/862515c0fab6ab4ed135d5f40263452fe49e882a/packages/turf-clone/index.js#L72-L84) . It looks like it was resolved last year in the v6 series [here](https://github.com/Turfjs/turf/commit/bdbeaf4f423998338c7ddc07d92ae18d3b0bb7c9).

The challenge you'll have is that `@turf/simplify` hasn't been re-released at a v6 module which means the changes to clone haven't been incorporated :(

**Comment by udos** [comment]
thanks. no worries!

the workaround until `@turf/simplify` is re-released as a v6 module could be that I uninstall `@turf/simplify`, install `@turf/clone` 6.0.2 (so it is available as a package and not as a dependency) and then re-install `@turf/simplify`. `@turf/simplify` might then use `@turf/clone` 6.0.2...

I will give that a try later today

**Comment by smallsaucepan** [comment]
Fairly sure this would have been resolved when Turf updated its JS target from es5 (as of v5.1.5) to es20xx. Have confirmed the currently generated code for CJS and ESM builds uses the `Array.isArray` call rather than the `value.length` check.

Have submitted PR #2749 to add a regression test making sure a property with a name `length` makes it through cloning unscathed.
