### ISSUE TITLE
pointGrid Margin problems

### ISSUE THREAD

**Issue by mertselimb** [Turfjs/turf#1626]
While i was using this function i had some margin problems. I had several pointGrids with differently spaced points and i wanted them to align. There should be a margin parameter on this function.

**Comment by stebogit** [comment]
@mertselimb would you please add an example of the issue you mentioned?

**Comment by mertselimb** [comment]
![2dc3046f-f97e-449f-bf78-61cff95b05c5](https://user-images.githubusercontent.com/18145782/54902389-519bf580-4eea-11e9-94a6-415a9a2587f6.jpg)

You can see aligning problem at them middle.

**Comment by mertselimb** [comment]
The issue is because the square sides are not a multitude of the point distance so function creates a small margin for the compensation. Because of this i understood there is actually no margin.

**Comment by stebogit** [comment]
See a snippet of the actual code it's necessary, otherwise we can't see what's going on...

**Comment by morganherlocker** [comment]
The grid functions in turf are not intended to be used in this way. I would recommend using a library that has global, distributed alignment as a design goal, such as [tile-cover](https://github.com/mapbox/tile-cover).

**Comment by mertselimb** [comment]
@stebogit  here is the code

```
  /**
   * Fills map with points
   * @param {turfFeatureCollection} mapGrid
   * @param {Array} IoU
   * @return {turfFeatureCollection} featureCollection
   */
  fillMap(mapGrid, IoU) {
    let coordArray = [];
    turfFeatureEach(this.geoJson, currentFeature => {
      coordArray = coordArray.concat(turfGetCoords(currentFeature));
    });

    let options = {
      mask: turfMultiPolygon(coordArray)
    };
    let featureArray = [];
    turfFeatureEach(mapGrid, (currentSquare, squareIndex) => {
      let pointDistance = this.calcPointDensity(IoU[squareIndex]);
      if (pointDistance !== null) {
        let bBox = this.calcbBox(currentSquare);
        options.properties = {
          squarebBox: bBox,
          pointDistance: pointDistance
        };
        let pointGrid = this.pointGrid(bBox, pointDistance, options);
        featureArray = featureArray.concat(pointGrid.features);
      }
    });
    return featureArray;
  }
```

**Comment by mertselimb** [comment]
Solved by changing this

```
var columns = Math.floor(bboxWidth / cellWidth);
    var rows = Math.floor(bboxHeight / cellHeight);
```
To this
```
var columns = Math.floor(bboxWidth / cellWidth)+1;
    var rows = Math.floor(bboxHeight / cellHeight);
```
