### ISSUE TITLE
turf/distance "obj is required"

### ISSUE THREAD

**Issue by timinho111** [Turfjs/turf#1627]
Hello,

I really enjoy working with Turf.js. I use it in a combination with Mapbox GL JS. 
The use of Turf.js in the Mapbox-project is the calculation of distances. I thought it was working perfectly until my co-worker brought the attention to a bug in the programm:

Some locations are receiving an error and others (the vast majority) are not.

The programm is written in Django with a JS-Frontend. I fill the location-array via a for-loop and made sure every location is saved in the array.

If you have a look at the following console output you can see that the first location is found, its number in the array and the GeoJSON object. 
The second location is also found, the number in the array shows up and the GeoJSON object is in the same format as the first object.
![akquisetool_bug](https://user-images.githubusercontent.com/28393814/54761585-a7bf1f00-4bf2-11e9-8fae-48d04ffe7a98.png)

This is the code snippet where the error gets produced:
![akquisetool_code](https://user-images.githubusercontent.com/28393814/54761970-75fa8800-4bf3-11e9-8df3-6d902fb38196.png)

Do you have any clue what the problem might be? I would really appreciate some input or maybe even the solution :)

Thanks in advance,
Tim

**Comment by stebogit** [comment]
Hey @timinho111 what's the value of `to.kundennummer` and what's `var_points[{{to.kundennummer}}]`?
Also, you are not actually logging `var_points[from]`...
Why don't you try that. I have no other ideas here... 🤷🏻‍♂️

**Comment by rowanwins** [comment]
Can you provide the file that's causing the issues @timinho111 , it sounds like it's more an error with the data that is being passed into `distance`?

**Comment by timinho111** [comment]
Yes you are right @rowanwins....It is a problem with the data passed into distance. 
There are leading zeros in the data which cause problems. So this is not a Turf, but my coding issue.

Thanks for your help guys and have a nice day!
