### ISSUE TITLE
Is it possible to compute a certain number of coordinate points equidistant from two coordinate points

### ISSUE THREAD

**Issue by xianxuLi** [Turfjs/turf#1638]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by stebogit** [comment]
I believe the set of all such points would be represented by the line perpendicular to the line passing through the two points. Does that help @xianxuLi?

**Comment by xianxuLi** [comment]
I'm sorry, I misstated it, but what I'm saying is that I want to find some coordinate points that are equally spaced within a line segment

**Comment by stebogit** [comment]
I guess you need to make a more specific example...

Maybe you can try playing with `@turf/length` and `@turf/line-chunk`

**Comment by xianxuLi** [comment]
I want to return a fixed number of coordinate points on a line that are equally distant, just like the midpoint, on the same line.
