### ISSUE TITLE
turf-dissolve

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#165]
merge polygons based on a common value

**Comment by rowanwins** [comment]
well I've had a first crack at this @morganherlocker and @tcql and created a [turf-dissolve module](https://github.com/rowanwins/turf-dissolve)

Basically input a featurecollection of polys and give it an attribute name to check against
````
var dissolvedPolys = dissolve(featureCollection, "STATENAME");
````

Its working well on small input datasets (eg half a dozen polys) but on larger ones (500+ polys) its really quite slow, I suspect my lopping mechanism is the issue although Im not sure of the best way to refactor things....

I need to run a few more tests and write up some doco but its a bit of a start.

**Comment by rowanwins** [comment]
FYI am now working on an rbush implementation which should speed things up a bit, will keep you posted

**Comment by DenisCarriere** [comment]
@rowanwins Any updates an rbush implementation of `turf-dissolve`? This would be a handy feature to have in TurfJS

**Comment by rowanwins** [comment]
Hi @DenisCarriere 

Yep the dissolve module now uses rbush and is reasonably fast. Keep in mind that the module I prepared was for v2 of turf so it probably needs a bit of updating to be suitable for v3. I haven't looked at it in a while sorry.

Cheers
Rowan

**Comment by DenisCarriere** [comment]
@rowanwins 
Well throw up it as a Gist or create a branch, I'll test it out and I can try to help out if I see any issues.

Can't wait to see it 👍

**Comment by DenisCarriere** [comment]
Was it this one you were working on? Or another project?
https://github.com/rowanwins/turf-dissolve

**Comment by rowanwins** [comment]
Hi @DenisCarriere yep that's the repo (if you didn't work that by now :) )

**Comment by rowanwins** [comment]
Now available as [turf-dissolve](http://turfjs.org/docs/#dissolve)

**Comment by DenisCarriere** [comment]
+1
