### ISSUE TITLE
Buffer function won't run

### ISSUE THREAD

**Issue by EngineerEmily** [Turfjs/turf#1660]
Hi! I don't know if I'm just doing this all wrong, but I'm getting an error when I try to use the buffer function and a multipolygon geojson file. 

This is the error I get:
````
Uncaught Error: Invalid unit
    at Object.e.exports.distanceToDegrees (turf.min.js:16)
    at Object.e.exports [as buffer] (turf.min.js:1)
    at (index):30
````
The code snippet calling the function:
````
var multiPolygon = turf.multiPolygon('https://mvaccess.github.io/cannabismap/test.geojson');
var buffered = turf.buffer(multiPolygon, 650, {units: 'feet'}); 
````
I'm using the library from mapbox
https://api.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js

It was shown in this tutorial 
https://docs.mapbox.com/help/tutorials/analysis-with-turf/

But I have also loaded the minifile from the "getting started" section (not at the same time)
https://npmcdn.com/@turf/turf/turf.min.js

I'm trying to run from the browser.

This is the geojson file that I'm using
https://mvaccess.github.io/cannabismap/test.geojson

I tried different files, but I still get an error. 

The repo for my project is here:
https://github.com/mvaccess/cannabismap

I don't really need someone to go through my code and tell me what the problem is (although, that would be awesome if someone is willing to do that). I'm hoping someone can send me an example project that uses a multipolygon geojson and runs the library in the browser.

Thanks!

**Comment by rowanwins** [comment]
Hi Emily

There are a couple of things

Turf can't work with remote data (eg the stuff you're trying to access via a url). So you'll need to perform an [XHR request](https://www.w3schools.com/xml/xml_http.asp) to get the data into your app. There are thousand libraries that can help make this a bit easier, one of the more popular ones these days is called [axios](https://github.com/axios/axios). That said the url you are pointing to doesn't show any data so there is something you need to fix there too... (hint: here is a url that works - https://raw.githubusercontent.com/mvaccess/cannabismap/master/city.geojson)

Once you've got your data you should be able to do something like, there is no need to call `turf.multipolygon` first if your data is already a multipolygon.
````
var buffered = turf.buffer(multiPolygon, 650, {units: 'feet'}); 
````

You will also need to use an update version of the library, I'd suggest `https://npmcdn.com/@turf/turf/turf.min.js`. Turf v3.0.11 is very old and has a slightly different API which wouldn't have helped.

Hopefully that helps get you on your way :) Sing out if you get stuck

Cheers
Rowan
