### ISSUE TITLE
@turf/difference unexpectedly returns null

### ISSUE THREAD

**Issue by kuige** [Turfjs/turf#1661]
feature1 GeoJSON here: https://gist.github.com/kuige/c787f9570756a9711e3ab8a938f4db27
feature2 GeoJSON here: https://gist.github.com/kuige/37327abb6a9496e2a3585da97781f577

`difference(feature1, feature2)` should not be null, but the result is null.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/8212800/56722542-e14af300-6779-11e9-83ea-b2aaf722144b.png">

Here is a codepen demo: https://codepen.io/sange/pen/OGaEqq

**Comment by stebogit** [comment]
@kuige you are feeding Turf GeoJSON object with the wrong coordinates (see [docs](https://github.com/Turfjs/turf#data-in-turf)). Try converting them to WGS84 first, is the result the same?

**Comment by jcready** [comment]
Yeah, this works: https://codepen.io/anon/pen/mgveGo
```js
const featureDiffGeoJSON = turf.toMercator(
    turf.difference(
        turf.toWgs84(featureGeoJSON),
        turf.toWgs84(polygonGeoJSON)
    )
);
console.log(featureDiffGeoJSON);
```

**Comment by stebogit** [comment]
👍

**Comment by kuige** [comment]
Sorry, I'm late. I use Openlayers to transform the GeoJSON from 'EPSG:3857' to 'EPSG:4326', and it works !

**Comment by kuige** [comment]
@stebogit @jcready When working with funnel shape, turf.difference always returns null, this time I'm using the right coordinates(WGS84), here is the demo:https://codepen.io/sange/pen/xeBRbe
<img width="677" alt="image" src="https://user-images.githubusercontent.com/8212800/56861453-5fee9d00-69d3-11e9-80c0-a170aa9644ba.png">

**Comment by stebogit** [comment]
@kuige [technically](https://tools.ietf.org/html/rfc7946#section-3.1.6) the funnel feature is actually a multipolygon.
Would you please try that? I'm not sure though if difference accepts that type as input; if not you could simply loop through its coordinates array.

**Comment by kuige** [comment]
@stebogit I checked the funnel feature GeoJSON, it's not a multipolygon.

I have tried the turf5.16 npm package, when turf/difference accepts the funnel feature GeoJSON as input, it throws a TopologyException with the error message: "found non-noded intersection between LINESTRING".

It seems that turf/difference doesn't support this kind of feature. I can't figure out why this kind of feature is not being supported, could you please explain it a bit ?

I will try the `@turf/unkink-polygon`.

**Comment by stebogit** [comment]
@kuige what I meant is that I think the funnel is not a valid polygon. In particular I refer to the last point of the polygon specs. In addition, although not specified, I'm not sure overlapping sides of the polygon are not valid.
I think the feature should be converted into a multipolygon, unkink-polygon should be able to do that.

**Comment by kuige** [comment]
@stebogit I tried the `unkink-polygon` operation, it works for the simple funnel feature, but for the "complicated funnel feature", it throws one error.

- `unkink` works fine for the orange feature
- the brown feature, `unkink` throws one error: "The input polygon may not have duplicate vertices (except for the first and last vertex of each ring)"
<img width="667" alt="image" src="https://user-images.githubusercontent.com/8212800/56879118-e2d22f00-6a89-11e9-826a-c8df08e512a7.png">

Here is the demo: https://codepen.io/sange/pen/XQGGVd

**Comment by stebogit** [comment]
@kuige try using `@turf/clean-coords` on that feature before unkinking it

**Comment by kuige** [comment]
@stebogit `@turf/clean-coords` works ! 👍
