### ISSUE TITLE
turf line intersection wrong calculation

### ISSUE THREAD

**Issue by onderaltintas** [Turfjs/turf#1664]
Intersection of 2 lines is at the wrong point. I couldn't find the reason. Is it about calculations are being done non-geodetic? If yes, will segmentation of lines solve the problem? 

fiddle link:
http://jsfiddle.net/gykunLjq/

in case of fiddle doesn't work, here is the code with leaflet:
```js
var map = L.map("map").setView([35, 45], 5);
L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
var line1 = turf.lineString([[39.93902183683848, 30.31516788588837], [48.146738758859335, 35.53001565402316]]);
var line2 = turf.lineString([[41.66218892543953, 35.75674816568121], [46.633919275463526, 29.30961941071382]]);
var intersects = turf.lineIntersect(line1, line2);
L.geoJson(line1).addTo(map);
L.geoJson(line2).addTo(map);

L.geoJson(intersects).addTo(map);
//added intersection point is below the real intersection.
```

**Comment by morganherlocker** [comment]
> Intersection of 2 lines is at the wrong point. I couldn't find the reason. Is it about calculations are being done non-geodetic? If yes, will segmentation of lines solve the problem?

Yes, I believe you are correct. I would expect more segments to improve precision.

**Comment by dpmcmlxxvi** [comment]
You can use `turf.lineChunk` to segment the lines further and you can control the accuracy you want with the `segmentLength` option. See example below.

http://jsfiddle.net/dpmcmlxxvi/u9ef7rnt/

**Comment by onderaltintas** [comment]
I don't know how to quote here, dpmcmlxxvi, your example seems to solve the problem. Thank you :)
