### ISSUE TITLE
Attempting to a configurable attribute of a configurable property Issue

### ISSUE THREAD

**Issue by anastely** [Turfjs/turf#1667]
Hi!
I have an issue with @turf/turf the last version, in my react native app

    "react-native": "0.58.0",
    "@turf/turf": "^5.1.6"

I just followed the same example in the **README.md**  but it's not working with me 
The issue is when I import turf like this
`import * as turf from '@turf/turf';
`
and write the function here is
```
handleNearby = () => {
        const { region, providers } = this.state;
        let currentPoint = [region.longitude, region.latitude]
        let points = _.map(providers, p => {
            console.log('@p', p);
            const to = [p.coordinates.longitude, p.coordinates.latitude];
            const distance = turf.distance(currentPoint, to, { units: 'kilometers' });
            return { coords: p.coordinates, name: p.username, id: p.id, distance }
        });
        const sortPoints = _.sortBy(points, ['distance']);
        this.setState({ sortedMarkers: sortPoints });
        console.log('@#points', sortPoints);
        return;

    }
```
and run the app i have this error

      attempting to a configurable attribute of a configurable property

[https://imgur.com/Pvf46B7](url)

**But** when I run the debugger on the browser the app is work very well I don't know why!
any help?

**Comment by rowanwins** [comment]
Hi @anastely 

I don't think this is related to turf.js , if I was going to hazard a guess I'd say this line is what
is causing the trouble 
````
this.setState({ distance }, () => console.log(this.state.distance.properties.distanceToPoint))
````
If i were you I'd try commenting out the bulk of the `handleNearby` function and slowly uncommenting lines and see where things break.

**Comment by anastely** [comment]
No that's just for test at first time I added, but in the debugger mode it's work and I see the output in the console

**Comment by anastely** [comment]
@rowanwins  any update!! I really need to solve this issue.

**Comment by morganherlocker** [comment]
Hey @anastely, please note that we are all volunteers here. We'll try to help, and will communicate as possible over issues, but please refrain from repeating questions or asking for updates when no commitment was made. As noted by @rowanwins, this appears to be an issue specific to the combination of tools you are using that neither of us are capable of reproducing with the details provided. Post more details and we'll try to address specific questions. Thank you.

**Comment by anastely** [comment]
@morganherlocker I will but my issue is simple. 
when I use @turf js just I see an error with there **example** in README.md, and just when I run the **debugger** mode the error is disappeared and app **work** very well, that's it
