### ISSUE TITLE
multiple lineIntersection Hangs the UI on frontend.

### ISSUE THREAD

**Issue by shobishani** [Turfjs/turf#1668]
I have 143 Polylines so in linear approach I have to compare every polyline coords to every other polyline coords and check if these two lines intersect with `lineIntersect` method. this solution works for smaller Polylines like if I have 50 - 100 Polylines it works perfectly but when I have more polylines like in one case 143 then browser't tab completely hangs.
Here is the code gist for linear approach.
[https://gist.github.com/shobishani/56ecea6f053c3ab3c859a94a6e87a259](url)
this is my linear approach that I am using to find out the intersection points. Please tell me how can I do it better or is there any method that can get all intersections from all polylines without going through the loop.

For Instance: I used bentley-ottman sweepline algorithm and it works fine maybe because in that I am using AVL and EventQueue but those intersection points are not perfect.

**Comment by shobishani** [comment]
I have 143 Polylines so in linear approach I have to compare every polyline coords to every other polyline coords and check if these two lines intersect with `lineIntersect` method. this solution works for smaller Polylines like if I have 50 - 100 Polylines it works perfectly but when I have more polylines like in one case 143 then browser't tab completely hangs.
`  private checkIntersection() {
    const alreadyChecked: number[][] = [];
    for (let i = 0; i < this._polyLines.length; i = 1) {
      for (let j = 0; j < this._polyLines.length; j = 1) {
        if (i === j) continue;
        const isAlreadyCompared: number[] | undefined = alreadyChecked.find((item: number[]) => {
          return isEqual(sortBy(item, Number), sortBy([j, i], Number));
        });
        if (isAlreadyCompared && isAlreadyCompared.length) continue;
        alreadyChecked.push([i, j]);
        const cords1: any[] = convertToCords(this._polyLines[i].getPath());
        const cords2: any[] = convertToCords(this._polyLines[j].getPath());
        const line1 = lineString(cords1);
        const line2 = lineString(cords2);
        const intersects = lineIntersect(line1, line2);
        if (intersects && intersects.features && intersects.features.length) {
          const item: any = intersects.features[0];
          const { coordinates } = item.geometry;
          if (coordinates && coordinates.length > 0) {
            this._intersectionPoints.push({
              lat: coordinates[0],
              lng: coordinates[1],
              volume: this._polyLines[i].getVolume(),
            });
          }
        }
      }
    }
  }`

this is my linear approach that I am using to find out the intersection points. Please tell me how can I do it better or is there any method that can get all intersections from all polylines without going through the loop.

For Instance: I used bentley-ottman sweepline algorithm and it works fine maybe because in that I am using AVL and EventQueue but those intersection points are not perfect.

**Comment by rowanwins** [comment]
Hi @shobishani 

You might want to take a look at the [shamos-hoey package](https://github.com/rowanwins/shamos-hoey), it should be more optimised for this work. I'd suggest putting all your lines into a `MultiLinestring` geometry. I wrote the lib for this sort of use case and intend on merging it across into turf at some stage.

Hope that helps

**Comment by shobishani** [comment]
Sure I'll give that try. But I think Shamos-Hoey algorithm terminates when it find first intersection but I need all the points where lines are intersecting.
In this doc.
[http://geomalgorithms.com/a09-_intersect-3.html#Shamos-Hoey-Algorithm](url)
I'll try it and get back if still not solved 
Thanks @rowanwins .

**Comment by rowanwins** [comment]
I modified my package to provide either option, either a boolean response, or all the intersection points.

**Comment by shobishani** [comment]
Thanks @rowanwins  it solved my problem.  great work.
