### ISSUE TITLE
discrepancy between code and documentation for union

### ISSUE THREAD

**Issue by andrewharvey** [Turfjs/turf#1669]
The JSDoc for turn.union at https://github.com/Turfjs/turf/blob/master/packages/turf-union/index.ts says:

> * Takes two {@link (Multi)Polygon(s)} and returns a combined polygon. If the input polygons are not contiguous, this function returns a {@link MultiPolygon} feature.

However the online documentation at http://turfjs.org/docs/#union says:

> Takes two or more polygons

which is wrong, as union only takes two polygons, as two arguments, not any number of polygons as the live documentation suggests.

I'm not sure where I need to place the PR to fix this, given it's already fixed in master.

**Comment by lostpebble** [comment]
I've been making use of union recently and passing in multiple polygons like so:

```typescript
const newGeometryFeature = union(...geometryFeatures);
```

It seems to be combining more than two polygon features together. But looking at the code in master, it seems like it only takes two? Kinda weird... Does the master code and released version not align?

I'm using ` "@turf/turf": "5.1.6"`.

**Comment by andrewharvey** [comment]
> It seems to be combining more than two polygon features together. But looking at the code in master, it seems like it only takes two? Kinda weird... Does the master code and released version not align?

Yeah that's what I'm very confused about too!

**Comment by rowanwins** [comment]
Hi @andrewharvey & @lostpebble 

Sorry for the confusion. Some of those docs are probably reflectively of the change from `JSTS` which was used in v5 and earlier which took any number of arguments. In v6 `martinez` was used which only takes 2 arguments. 

In v7 I've implemented [`polygon-clipping`](https://github.com/mfogel/polygon-clipping) which goes back to taking any number of arguments. The latest hasn't been published yet as a turf module yet but the 0.14.0 release of `polygon-clipping` looks really good and passes all the turf tests.

**Comment by brylie** [comment]
This almost seems like a regression. Is there a way to get a union of a MultiPolygon with Turf.js?

**Comment by rowanwins** [comment]
Docs and code are now in sync. It's still on my radar to relook at adding support for more than 2 polys.
