### ISSUE TITLE
Is there a method to rotate the squareGrid?

### ISSUE THREAD

**Issue by chan-dev** [Turfjs/turf#1678]
Is there a way to rotate the `squareGrid`?

Here's what i have right now.

[Link to source](https://codepen.io/chan-dev/pen/wbBXjY?editors=0010)

What i want is for the grid to rotate to align with the angle of a polygon shape in google maps.

![gridcells](https://user-images.githubusercontent.com/46891115/57444054-e7fd5e00-7281-11e9-991f-12b265804236.PNG)

```
var map = new google.maps.Map(document.getElementById("map"), {
  zoom: 3,
  maxZoom: 8,
  minZoom: 2,
  center: {
    lat: 0,
    lng: -180
  },
  streetViewControl: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP
});

var triangleCoords = [
  { lat: 25.774, lng: -80.19 },
  { lat: 18.466, lng: -66.118 },
  { lat: 32.321, lng: -64.757 },
  { lat: 25.774, lng: -80.19 }
];

// Construct the polygon.
var bermudaTriangle = new google.maps.Polygon({
  paths: triangleCoords,
  strokeColor: "#FF0000",
  strokeOpacity: 0.8,
  strokeWeight: 2,
  fillColor: "#FF0000",
  fillOpacity: 0.35
});
bermudaTriangle.setMap(map);

const polygonMap = bermudaTriangle.getMap();
const projection = polygonMap.getProjection();

google.maps.Polygon.prototype.my_getBounds=function(){
    var bounds = new google.maps.LatLngBounds()
    this.getPath().forEach(function(element,index){bounds.extend(element)})
    return bounds
}

let coordinates = [];

// convert to bermudaTriangle path to geojson
for (let point of bermudaTriangle.getPath().getArray()) {
  coordinates.push([point.lng(), point.lat()]);
}

const bounds = bermudaTriangle.my_getBounds();
const center = bounds.getCenter().toJSON();

const geojson = turf.polygon([coordinates]);

const pivot = [center.lng, center.lat];
const options = {pivot: pivot};
const rotatedPoly = turf.transformRotate(geojson, 0, options);
const bbox = turf.bbox(rotatedPoly);

const grid = turf.squareGrid(bbox, 50, {
  units: "miles",
  // mask: geojson
});

map.data.addGeoJson(grid);

```

**Comment by stebogit** [comment]
@chan-dev this is a tough one.
I believe you could try using `@turf/transform-rotate` on each square of the grid, using as origin of rotation the center of rotation for the big square "containing" the square grid.
Does that help?

**Comment by chan-dev** [comment]
@stebogit right now i have no idea how to achieve that. Isn't the grid generated a single unit? How do i deal with each grid cell?

**Comment by dpmcmlxxvi** [comment]
@chan-dev The grid is a just feature collection. Just iterate over the collection with, for example, `@turf/meta.featureEach` and apply `@turf/transform-rotate` to each feature (i.e., cell).

**Comment by chan-dev** [comment]
@dpmcmlxxvi thanks, i didn't know about that. I'll give it a try

**Comment by dpmcmlxxvi** [comment]
@chan-dev  It's only as expensive as the number of grid cells you have. I don't see how to rotate them without rotating each cell. The other alternative would be to rotate the polygon first then create the grid, but turf doesn't support that. 

Also, remember to use @stebogit's suggestion to use a fixed origin otherwise they will each get a different origin which is probably not what you want.

**Comment by chan-dev** [comment]
@dpmcmlxxvi would u mind if you can provide a snippet with rotating from a fixed origin?

**Comment by dpmcmlxxvi** [comment]
@chan-dev The documentation provides a snippet on using it.

https://turfjs.org/docs/#transformRotate

**Comment by chan-dev** [comment]
@dpmcmlxxvi

```
const center = bounds.getCenter().toJSON();

const geojson = turf.polygon([coordinates]);

const pivot = [center.lng, center.lat];
const bbox = turf.bbox(geojson);

const grid = turf.squareGrid(bbox, 50, {
  units: "miles",
  mask: geojson
});

turf.featureEach(grid, (feature, i) => {
  const options = {pivot: pivot};
  console.log(feature.geometry.coordinates);
  const rotatedPoly = turf.transformRotate([feature.geometry.coordinates], 20, options);
})
```

But i got this error:

`Uncaught Error: unknown GeoJSON type`

**Comment by chan-dev** [comment]
@dpmcmlxxvi @stebogit 

I was able to rotate the grid now

Here's a snippet

```
const rotatedGrid = turf.featureCollection([]);

turf.featureEach(grid, (feature, i) => {
  const options = {pivot: pivot};
  const rotatedPoly = turf.transformRotate(feature, 10, options);
  rotatedGrid.features.push(rotatedPoly);
})
```

I have to create a `featureCollection` and then append each rotated cell. Can you guys suggest any solution that's more efficient than this?

**Comment by stebogit** [comment]
@chan-dev I don't think there is really a more efficient way.
I can only suggest a shorter/prettier, though not tested, version (no optimization, just a more compact form thanks to ES6 syntax):
```js
const rotatedGrid = turf.featureCollection(
  grid.features.map((feature) => turf.transformRotate(feature, 10, {pivot}))
);
```

**Comment by dpmcmlxxvi** [comment]
I think @stebogit is correct. You have to transform each and store it somewhere. Except for saving a little memory by saving in place in the original collection, that's as good as it's going to get. Besides, unless you have a specific efficiency bottleneck, I wouldn't worry about preemptively optimizing code.

**Comment by chan-dev** [comment]
@stebogit @dpmcmlxxvi . 

Oh i see, this is the only solution available. 
I was searching for the solution for days regarding this and finally found one with your help.  Thanks a lot guys for your help.
