### ISSUE TITLE
@turf/cleanCoords not removing duplicates

### ISSUE THREAD

**Issue by kochis** [Turfjs/turf#1679]
turf.js version 5.1.5

Test File: https://gist.github.com/kochis/532dd84213728dd7f459b24c01f3ef83

Maybe I'm misunderstanding something about how `cleanCoords` works, but it seems like it's not removing duplicate coordinates in some cases. In this case, I'm trying to unkink any overlapping polygons.

For instance, with the sample file posted above:

*Note: need to bump the node stack size to process file*
```bash
$ node --stack_size=1000000
> var multipolygon = require('./multipolygon.json')
> var turf = require('@turf/turf')
> turf.unkinkPolygon(turf.cleanCoords(multipolygon))
Error: The input polygon may not have duplicate vertices (except for the first and last vertex of each ring)
    at simplepolygon (/Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:11509:36)
    at /Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:11875:21
    at /Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1411:13
    at Array.forEach (<anonymous>)
    at /Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1406:33
    at geomEach (/Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1275:17)
    at flattenEach (/Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1379:5)
    at Object.unkinkPolygon (/Users/redacted/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:11873:5)
```

**Comment by stebogit** [comment]
@kochis 
Would you please post the result of `cleanCoords`?
BTW what happens if you run it twice?
```js
var m =  turf.cleanCoords(turf.cleanCoords(multipolygon))
```

**Comment by kochis** [comment]
@stebogit 

Here's the cleaned output: https://gist.github.com/kochis/5a82492270253e1ca8590ef80847ae53

Running it through `cleanCoords` didn't seem to have any affect.
```
> turf.unkinkPolygon(turf.cleanCoords(turf.cleanCoords(multipolygon)))
Error: The input polygon may not have duplicate vertices (except for the first and last vertex of each ring)
    at simplepolygon (/Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:11509:36)
    at /Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:11875:21
    at /Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1411:13
    at Array.forEach (<anonymous>)
    at /Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1406:33
    at geomEach (/Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1275:17)
    at flattenEach (/Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:1379:5)
    at Object.unkinkPolygon (/Users/craigkochis/Projects/shapefile-to-geojson/node_modules/@turf/turf/turf.js:11873:5)
```

FYI, I ran it through cleanCoords about 100 times, and still got the failure.

**Comment by rowanwins** [comment]
Hi @kochis 

Any chance you could provide a simplified test? it's a little hard to scan something with so many coords and know which ones are supposed to be removed, and which ones aren't being moved.

**Comment by kochis** [comment]
Here is one of the polygons from the original file (has ~500pts): https://gist.github.com/kochis/bd15e77effd64f4c162f3fe9f6176179

Looks like the point `[4.939971, 51.436119]` occurs three times.

**Comment by rowanwins** [comment]
Hi @kochis 

So the geojson spec forces the first and last coord to be the same. And cleancoords only strips out identical coords that are sequential, the other occurance of that point was surrounded by other unique vertices. 

Perhaps you should be using `@turf/unkinkPolygon`?

**Comment by kochis** [comment]
@rowanwins, using `unkinkPolygon` is my intended goal, which is how I came across the original error when running it
```
> turf.unkinkPolygon(polygon)
Error: The input polygon may not have duplicate vertices (except for the first and last vertex of each ring)
```
I was trying to run the polygon through `cleanCoords` in an attempt to remove the duplicates that it was complaining about. Though I didn't realize it only takes into account _sequential_ coordinates, so it does seem that is working as expected.

I guess the real issue then, is why does `unkinkPolygon` not work on this one? Does unkinkPolygon has a different concept of _duplicate vertices_ (i.e. not sequential)

**Comment by kochis** [comment]
By removing the point `[4.939971, 51.436119] `,  `unkinkPolygon` was able to run without the error, so that point seems to be the issue. 

One thing to note, that point in this case is both an intersection _and_ the start & end of the polygon (which is why it occurs three times). So it's not technically a duplicate in the `cleanCoords` sense, but it does fail the `isUnique` check that happens in unkinkPolygon: https://github.com/Turfjs/turf/blob/17002ccd57e04e84ddb38d7e3ac8ede35b019c58/packages/turf-unkink-polygon/lib/simplepolygon.js#L391

I'm wondering if this is the the expected behavior of `isUnique`, or if this case is an exception.

[visual of point]
![image](https://user-images.githubusercontent.com/814934/57631282-343feb00-756d-11e9-85dd-eadb1b7c85fb.png)

**Comment by stebogit** [comment]
I isolated the problem with a simplified kinked polygon and I believe `unkink-polygon` should be able to work in this very specific situation, as I don't see anything wrong with the polygon:
```js
const kinked = turf.polygon([
  [4.835014343261719,52.390058694222034], // first
  [4.7714996337890625,52.3527476801277],
  [4.769096374511719,52.43215291193842],
  [4.835014343261719,52.390058694222034], // middle
  [4.89715576171875,52.34939233715191],
  [4.905738830566406,52.43340883827937],
  [4.835014343261719,52.390058694222034] // last
]);

const result = turf.unkinkPolygon(kinked);
// Uncaught Error: The input polygon may not have duplicate vertices (except for
// the first and last vertex of each ring)
```
Maybe this could become a test case for whoever would like to try fixing this issue (bug?).

![Screen Shot 2019-05-13 at 8 36 47 AM](https://user-images.githubusercontent.com/12717225/57634491-42384080-755a-11e9-835e-2027630d477c.png)

**Comment by kochis** [comment]
Would the solution in this case be to omit the first/last vertices from the `isUnique` test?

**Comment by stebogit** [comment]
I don't think so @kochis, as the output would need 8 total points.
Although not straightforward, you'd actually want to replicate that middle point to be the first/last point of one of the two resulting unkinked polygons... 🤔

**Comment by dpmcmlxxvi** [comment]
@kochis @stebogit  It looks like the real issue is that [simplepolygon](https://github.com/mclaeysb/simplepolygon) does not allow cases where a polygon self-intersects at an existing vertex. It is mentioned in the [dissertation](http://www.cis.southalabama.edu/~hain/general/Theses/Subramaniam_thesis.pdf) that the code comes from and is discussed in [issue #12](https://github.com/mclaeysb/simplepolygon/issues/12#issuecomment-319580771).

So, cleaning the coordinates will only help if you get lucky and the self-intersection happens to fall on the line defined by it's adjacent vertices.

I looked at the simplepolygon code to see if there is a simple solution and found the code a bit impenetrable. It would take a deep dive of the dissertation and code to understand what's going on. It might help to ask the original developer for some guidance on whether there is a simple fix, but they have indicated on their issue tracker that they don't plan to develop the code anymore.

**Comment by kochis** [comment]
@dpmcmlxxvi Thanks for those reference links, good to know this is a known issue. I kind of came to the same conclusion after digging into the `unkinkPolygon` and `simplepolygon` code. My work around for the moment is to just manually detect the duplicate points, and fuzz them by a few centimeters to the point where it no longer detects them as duplicates.

Since this is a simplepolygon issue, and they are tracking it I'm going to close this one out.

**Comment by dpmcmlxxvi** [comment]
@kochis No problem. I don't think this is really being tracked by simplepolygon since the developer is no longer maintaining the code. Turf developers will probably have to address it at some point.

**Comment by smdjeff** [comment]
seems like clean should clean the whole poly not just sequentials
