### ISSUE TITLE
union documentation on input parameters

### ISSUE THREAD

**Issue by YvainLeyral** [Turfjs/turf#1695]
There is differences between online documentation and js documentation on input type allowed for union function.

online documentation says that only polygon are allowed as input parameters 
https://turfjs.org/docs/#union

but readme says that multipolygon or polygon are allowed 
https://github.com/Turfjs/turf/tree/master/packages/turf-union

```
Parameters

    polygon1 Feature<(Polygon | MultiPolygon)> input Polygon feature
    polygon2 Feature<(Polygon | MultiPolygon)> Polygon feature to difference from polygon1

```

We are using typescript on the project and the  index.d.ts file indicate the following signature for the union function:

`export default function (
    ...features: Feature<Polygon>[]
): Feature<Polygon | MultiPolygon>;
`
so we get the following error :
```
Argument of type 'Feature<MultiPolygon, { [name: string]: any; }>' is not assignable to parameter of type 'Feature<Polygon, { [name: string]: any; }>'.   Type 'MultiPolygon' is not assignable to type 'Polygon'. 
    Types of property 'type' are incompatible. 
      Type '"MultiPolygon"' is not assignable to type '"Polygon"'
```

We have changed the typscript type signature of  index.d.ts and manage to realise a fusion of two Multipolygon.

Is union of multipolygon allowed?

**Comment by andrewharvey** [comment]
Is this the same as #1669 ?

**Comment by mfedderly** [comment]
Yeah I think this is fixed now. Please reopen if I'm wrong.
