### ISSUE TITLE
along doesn't work over longer distances

### ISSUE THREAD

**Issue by hyperknot** [Turfjs/turf#1696]
It's simpler in code:
```
var line = turf.lineString([[0, 0], [80, 80]]);

var length = turf.length(line);
console.log(length); // 9815 km

var center = turf.along(line, length / 2).geometry.coordinates;
console.log(center); // [9.4, 43.3]
```

https://jsbin.com/qonuyak/edit?html,console

I don't understand what is happening, along should be a very simple linear interpolator along points, and even if the great line distance calculation wouldn't be correct, it should always stay on the lat=lon line in this example. Instead, it returns a very weird point.

**Comment by stebogit** [comment]
@hyperknot `along` looks like operates on a `great-circle` line, I guess for precision reason:
```js
const greatCircle = turf.greatCircle(
  turf.point([0, 0]),
  turf.point([80, 80])
);  

const center = turf.along(
  greatCircle,
  turf.length(greatCircle) / 2
);
```
![Screen Shot 2019-05-18 at 10 34 44 PM](https://user-images.githubusercontent.com/12717225/57978316-c3ab2b00-79bf-11e9-9f5f-b12faf51a98a.png)

**Comment by hyperknot** [comment]
It must indeed be the case! Do you know any way to make an along work in WebMercator projection system? I'd like to put a popup to the middle of a line, as visible in a JS viewer (Mapbox GL).

**Comment by stebogit** [comment]
@hyperknot this should work, however at high latitudes the projection distortion becomes an issue, and I don't really know how to correct it so the point still appears half way.
```js
var start = turf.point([0,0]);
var end = turf.point([50, 50]);

var line = turf.lineString([start.geometry.coordinates, end.geometry.coordinates]);
  
var bearing = turf.rhumbBearing(start, end);
var distance = turf.rhumbDistance(start, end);
var center = turf.rhumbDestination(start, distance / 2, bearing);
// [22.30547292169922, 25.000000000000014]
```
![Screen Shot 2019-05-23 at 10 37 35 PM](https://user-images.githubusercontent.com/12717225/58305215-1e6fc880-7dac-11e9-8b24-8b8b059acfb7.png)
![Screen Shot 2019-05-23 at 10 40 55 PM](https://user-images.githubusercontent.com/12717225/58305216-1e6fc880-7dac-11e9-9e0f-744cbebd03c2.png)
