### ISSUE TITLE
greatCircle appears wrong

### ISSUE THREAD

**Issue by csimpi** [Turfjs/turf#1700]
Please provide the following when reporting an issue:

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

When I want to draw an arc between DBX and SFO airports I'm getting this strange circle:
![image](https://user-images.githubusercontent.com/6192067/58087073-af5c5f00-7b74-11e9-870e-37eef11222b6.png)

Check my example fiddle here:
https://jsfiddle.net/b5v6j1wg/2/

**Comment by stebogit** [comment]
@csimpi what output would you expect instead?

**Comment by csimpi** [comment]
@stebogit 
Is this supposed to be a rhetorical question? You can see that on the screenshot, the arc is wrong, it brokes on the top, tops somewhere in the heaven and this is not even the shortest path between the two points.

Google maps in the same situation:

![image](https://user-images.githubusercontent.com/6192067/58125013-6fbd6380-7bc4-11e9-9e1e-d8af50228a1c.png)

https://goo.gl/maps/t8AihHrRQz9qmg45A

**Comment by stebogit** [comment]
@csimpi no mine was not a rhetorical question. Assuming the `great-circle` calculations are correct, I don't see anything wrong with the returned result, which surely does seem weird on a web-mercator (web map) projection:

![Screen Shot 2019-05-21 at 12 57 45 PM](https://user-images.githubusercontent.com/12717225/58126690-5dddbf80-7bc8-11e9-9f4a-7215dc9ffbe0.png)

The representation of the google flight is definitely more intuitive, but I'm sure it's not the actual (shortest) route between the two cities

**Comment by csimpi** [comment]
@stebogit 

1. the arc goes through Greenland on your screenshot, the arc on my example doesn't, it's very far from that
2. the top (broken) part of the arc on my screenshot should continue and appear somewhere else on the map not be broken on the top this way. It seems the route is in nowhere which is not possible. There should be a route that's on the Earth, I'm sure the travelers between DXB and SFO use aircraft, not a spaceship also :))

**Comment by stebogit** [comment]
@csimpi I just manually draw the line on the globe picture, mine was just an approximation.

The "broken" part you're referring to it's basically the [projection](https://en.wikipedia.org/wiki/Map_projection#Cylindrical) of a single point, the north pole, of the globe sphere on a flat plain. An azimuthal projection might be more suitable to represent the great-circle line in your case, although I have no idea if nor how you could create that map for the web.

In general it's always tricky to correctly represent features at high latitudes on a web map due to the highest [distortion](https://en.wikipedia.org/wiki/Mercator_projection#Distortion) introduced by the projection.

**Comment by stebogit** [comment]
[This link](https://en.wikipedia.org/wiki/Great-circle_distance) might also help to give you a better understanding of the great circle line

**Comment by csimpi** [comment]
@stebogit 
Thank you for the explanation. Yes, I know about the distortion problem, but I also know there should be a real route somewhere (instead of nowhere) since I'm on the Earth even If I'm traveling between DXB and SFO.  That's true, it wouldn't appear as an arc, but as you can see on my screenshot, that's not a perfect arc either, it's distorted but on the wrong/unreal way instead of being distorted on the real way. 

In antimeridian cases, turf cuts the arc two pieces (MultiLineString) instead of distorting/hiding the other parts, it continues at the opposite side of the map.

**Comment by stebogit** [comment]
> In antimeridian cases, turf cuts the arc two pieces (MultiLineString) instead of distorting/hiding the other parts, it continues at the opposite side of the map.

Would you mind posting a code snippet and a picture of that?

Anyway, personally I still don't see the case you reported as buggy or wrong, but I might be mistaken.

**Comment by csimpi** [comment]
@stebogit 

Here is the example for antimeridian + turf handling, this is the right way to handle the distortion problems of the maps:

https://jsfiddle.net/Lx2gtyzp/1/

Discussion:
https://github.com/Turfjs/turf/issues/1671

If you say that generating a real route geometry which is going outside of the world to nowhere is not a bug, then it's not a bug, I still think it could be handled better and the additional parts of the arc should appear on the right/real point of the map as happens with antimeridian. 

Another aspect of the issue is that turf generates coordinates upper than 85 longitude, but it seems the maps are not able to show the world above 85 lng (due to the distortion that you're talking about). That's why we're getting the flat top instead of a real arc.

The additional part (the top that's flat due to the longitude is higher than 85) shouldn't appear (in this case two lines should be added to the map similar to antimeridian cases) or should appear on the right place.

**Comment by stebogit** [comment]
@csimpi sorry, for some reason I confused antemeridian with the south pole... 😅 

BTW it happens also in the southern hemisphere:
```js
const start = turf.point([-68.203125, -62.26792262941758]);
const end = turf.point([108.03125, -63.54855223203643]);
          
const greatCircle = turf.greatCircle(start, end);
```
![Screen Shot 2019-05-23 at 8 20 10 AM](https://user-images.githubusercontent.com/12717225/58264939-9a79fa00-7d33-11e9-9063-6741fe0c29a0.png)


Look at this example, with two points perfectly on opposite sides on the north pole, i.e. along the same meridian line:
```js          
var greatCircle = turf.greatCircle(turf.point([-68, 50]), turf.point([112, 50]));
```
![Screen Shot 2019-05-23 at 8 22 37 AM](https://user-images.githubusercontent.com/12717225/58265356-5509fc80-7d34-11e9-8951-3a66bae73bcb.png)
The top most section of the line (actually the entire top line of the map!) represents just the projection over the flat map of the north pole. In fact if you think about that every meridian intersect at north and south to that single point, which becomes a line on the projected plain.

It is indeed an extreme case and you are never gonna show that on a map, however there is nothing wrong with the [calculations](https://github.com/Turfjs/turf/blob/master/packages/turf-great-circle/lib/arc.js#L77) of `@turf/great-circle`

**Comment by dpmcmlxxvi** [comment]
@stebogit so if this is just a projection/visualization problem, can this be closed?

@csimpi you could check the actual values coming out of 'great-circle' to verify they are correct and remove the visualization middleman to ensure that is not introducing the problem.

**Comment by stebogit** [comment]
Yes I believe we can close this
