### ISSUE TITLE
DIfference between union imported via @turf/turf and as @turf/union

### ISSUE THREAD

**Issue by gorbypark** [Turfjs/turf#1706]
I'm having an odd issue where union is crashing the entire browser tab.  I'm using union to join a few line fragments in mapbox gl, something along the lines of this:
```
        if (sourceFeatures.length > 1) {
          feature = sourceFeatures[0];
          sourceFeatures.map(x => {
            // Combine all source geometry fragments into one single feature
            feature = turf.union(feature, x);
          });
        }
```

If turf is imported using `import { turf } from "@turf/turf";` everything works fine, but importing just the module as `import union from "@turf/union";` and union crashes after about 30 seconds.  I'm not an expert using Chrome's debugger, but it appears to be pointing me to this while loop that's crashing (in martinez.umd.js)
```
      while (pos >= i) {
        event = resultEvents[pos];
        processed[pos] = true;

        if (event.left) {
          event.resultInOut = false;
          event.contourId   = ringId;
        } else {
          event.otherEvent.resultInOut = true;
          event.otherEvent.contourId   = ringId;
        }

        pos = event.pos;
        processed[pos] = true;
        contour[0].push(resultEvents[pos].point);
        pos = nextPos(pos, resultEvents, processed, i);
      }
```

**Comment by dpmcmlxxvi** [comment]
@gorbypark Importing `@turf/turf` uses v5 which was the last stable release. Importing the individuals modules like `@turf/union` uses v6 which was not stable and had experimental features. I'd suggest using v5 until v7 is released. A number of other users have reported similar issues #1519, #1568. Alternatively, you can try using the [v7-alpha release](https://www.npmjs.com/package/turf/v/7.0.0-alpha.1)

**Comment by rowanwins** [comment]
Hi @gorbypark 

@dpmcmlxxvi is correct.

If you're just wanting a union operation I'd suggest using the [`polygon-clipping`](https://github.com/mfogel/polygon-clipping) library directly which is what we'll be using in v7.

Cheers

**Comment by destus90** [comment]
I've had the same issue and I had to downgrade `@turf/union` to version 5, because `polygon-clipping` doesn't work when the input data is array of points
