### ISSUE TITLE
How to install turf from local repository?

### ISSUE THREAD

**Issue by kochizufan** [Turfjs/turf#1709]
I made some modification to turf.js in my local repository, and want to install it to my some project.

I tried
```
npm install ./local_turf
```
But it shows errors saying "Missing package name":
```
npm ERR! Can't install /Users/kokogiko/github/turf-builder/local_turf: Missing package name

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kokogiko/.npm/_logs/2019-06-08T03_19_17_735Z-debug.log
```

How to install turf from local repository?

**Comment by rowanwins** [comment]
Hi @kochizufan 

Perhaps try `npm link`, there is a [good tutorial here](https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557)

**Comment by morganherlocker** [comment]
This is the "official" option supported by npm. Please reopen if you hit snags.
