### ISSUE TITLE
Is there anyway to check if one shape goes inside another shape? 

### ISSUE THREAD

**Issue by dhivehi** [Turfjs/turf#1712]
![image](https://user-images.githubusercontent.com/18715293/59328644-5791bd80-8d06-11e9-9088-c120839029a9.png)

if such a function doesnt exist already, maybe `turf.booleanGoesInside(shape1,shape2)` ?

**Comment by stebogit** [comment]
@dhivehi among the turf boolean packages you should find what you are looking for. For example `@turf/boolean-contains` or `@turf/boolean-crosses`.
[This link](http://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/shapes/spatial_relations/predicates.htm#Disjoint) explains the definitions (ref. #919)

**Comment by dhivehi** [comment]
boolean-crosses returns true whether or not line touches boundary or goes inside. I want a return false for boundary touching and true when line goes inside polygon. I have tested all possible functions in turf. non of it works for the above case.

**Comment by dhivehi** [comment]
I have also tested de9im functions. nothing works for above case.

**Comment by stebogit** [comment]
What about combining `cross` and (not)`within`/`containing`?

**Comment by stebogit** [comment]
I believe @dhivehi  you are looking for the `Touch` function described in the [ARCGIS spatial relationships](http://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/shapes/spatial_relations/predicates.htm#Disjoint), which might be a possible new package, although I believe combining the two boolean modules returns the same result.
A distinct module should be faster though.

**Comment by dhivehi** [comment]
combining cross and (not)within/containing doesnt work. Because i want is to check whether a PART of line goes inside a polygon or not. In other words, i want the `intersect` function to return false even if two shapes intersects on boundary as long as one doesnt go inside another.

**Comment by dhivehi** [comment]
To give some context, this function i needed is for improving visibility graph in shortest path calculation.

**Comment by stebogit** [comment]
@dhivehi would you please post some code example of your issue?

**Comment by smallsaucepan** [comment]
This has been inactive for a few years now, so closing. Please reopen if there is some example code that can be made available.
