### ISSUE TITLE
isObject is too strict of a check for fameworks that provide access to turf eg nodered. causes many modules to reject a legitimate options object

### ISSUE THREAD

**Issue by spydmobile** [Turfjs/turf#1720]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by stebogit** [comment]
@spydmobile would you please provide some examples of the actual issue? That will help us to better understanding the extent of the problem.

**Comment by spydmobile** [comment]
This issues seems to prove itself mostly when using turf via a 3rd party, for example, I use turf inside nodered, and regardless of if I use the nodered module or the npm module or even implement it myself, the way the framework provides the options object seems to be constructor less therefore the options object is rejected as invalid even using the code provided. this issue does not happen if i use turf directly in nodejs as the objects are fully accepted, but this is happening in many modules such as concave and simplify, using the isObject directly inside the framework returns false when running code like this inside nodered:
`turf. isObject({units: 'kilometers', maxEdge: 1}) `

**Comment by spydmobile** [comment]
this code in nodejs works as expected (From example): 
```
const turf = require("@turf/turf");
var points = turf.featureCollection([
  turf.point([-63.601226, 44.642643]),
  turf.point([-63.591442, 44.651436]),
  turf.point([-63.580799, 44.648749]),
  turf.point([-63.573589, 44.641788]),
  turf.point([-63.587665, 44.64533]),
  turf.point([-63.595218, 44.64765])
]);
var options = { units: "miles", maxEdge: 1 };

var hull = turf.concave(points, options);
console.log(hull);
```

but when this code is used in a node in nodered, this will fail. 
This example exposes turf as per node red docs, this is added to settings.js
`  functionGlobalContext: {
    // os:require('os'),
    // jfive:require("johnny-five"),
    // j5board:require("johnny-five").Board({repl:false})
    turfLib: require("@turf/turf"),
    momentLib: require("moment")
  },`

then this code in the now turf aware node red in a stock function node:
`turf = global.get('turfLib')
var points = turf.featureCollection([
  turf.point([-63.601226, 44.642643]),
  turf.point([-63.591442, 44.651436]),
  turf.point([-63.580799, 44.648749]),
  turf.point([-63.573589, 44.641788]),
  turf.point([-63.587665, 44.64533]),
  turf.point([-63.595218, 44.64765])
]);
var options = { units: "miles", maxEdge: 1 };

var hull = turf.concave(points, options);
node.warn(hull);
msg.payload = hull

return msg;`

when executed will produce the error:
`Error: options is invalid`

an entire working flow to reproduce in node-red:
`[
    {
        "id": "b29eae1b.16b72",
        "type": "tab",
        "label": "Turf Error Demo Flow",
        "disabled": false,
        "info": ""
    },
    {
        "id": "8288b9a4.0f2548",
        "type": "inject",
        "z": "b29eae1b.16b72",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 160,
        "y": 140,
        "wires": [
            [
                "d261acdd.567d7"
            ]
        ]
    },
    {
        "id": "adc3504e.3bcac",
        "type": "debug",
        "z": "b29eae1b.16b72",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 610,
        "y": 140,
        "wires": []
    },
    {
        "id": "83c9008c.07838",
        "type": "catch",
        "z": "b29eae1b.16b72",
        "name": "",
        "scope": null,
        "uncaught": false,
        "x": 360,
        "y": 200,
        "wires": [
            [
                "adc3504e.3bcac"
            ]
        ]
    },
    {
        "id": "d261acdd.567d7",
        "type": "function",
        "z": "b29eae1b.16b72",
        "name": "",
        "func": "turf = global.get('turfLib')\nvar points = turf.featureCollection([\n  turf.point([-63.601226, 44.642643]),\n  turf.point([-63.591442, 44.651436]),\n  turf.point([-63.580799, 44.648749]),\n  turf.point([-63.573589, 44.641788]),\n  turf.point([-63.587665, 44.64533]),\n  turf.point([-63.595218, 44.64765])\n]);\nvar options = { units: \"miles\", maxEdge: 1 };\n\nvar hull = turf.concave(points, options);\nnode.warn(hull);\nmsg.payload = hull\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 350,
        "y": 140,
        "wires": [
            [
                "adc3504e.3bcac"
            ]
        ]
    }
]`

**Comment by spydmobile** [comment]
Note: to reproduce the error in Nodered (any version, it should not matter) you will need to implement turf as per my first snippet, in the global Context. However, for folks that use the 	function-npm node to integrate NPM modules, instead of adding them to global context, the results are the same, the errors are the same.

**Comment by spydmobile** [comment]
Also I was reading that the weakness in the approach used in isObject is that it will reject a custom object, so others dont use that technique without additional code logic, however I dont know if this is related or a red herring... hope this helps, please let me know if there is anything else I can provide to facilitate.....
Thank you to the moon and back for Turf, my life would suck without it!!!!

**Comment by willvincent** [comment]
This is a major issue, yes.

node v12.16.1, turf 5.1.6:

```
> turf.helpers.isObject({})
false
> turf.helpers.isObject(new Object())
false
```

Both of those, _absolutely_ should resolve to true, but do not... as a result, it's impossible to use the options param on basically any turf method.
