### ISSUE TITLE
Property 'booleanPointInPolygon' does not exist on type 'typeof 

### ISSUE THREAD

**Issue by RZR666** [Turfjs/turf#1723]
import * as turf from "@turf/boolean-point-in-polygon";

var inBounds = turf.booleanPointInPolygon(pt, polygon);

Property 'booleanPointInPolygon' does not exist on type 'typeof 

Is this a typescript issue, any way to get around it without installing all of turf?

Thanks

**Comment by mfedderly** [comment]
You probably mean to do `import booleanPointInPolygon from "@turf/boolean-point-in-polygon"` as this is a default export from that module.
