### ISSUE TITLE
No typings for the standalone @turf/distance package

### ISSUE THREAD

**Issue by wcauchois** [Turfjs/turf#1725]
Hi,

I installed @turf/distance@6.0.1 and it doesn't appear to have TypeScript typings. The package.json says there should be an index.d.ts, but that file isn't present in the package under the node_modules folder.

I think maybe this commit might have broken it https://github.com/Turfjs/turf/commit/364dc81a97d13744b770e1d62802f7b8979d61d6#diff-6d071eff6c43993c40d93a8b2b275048 but I don't really have much context on all this.

To mitigate this for myself I downgraded to 6.0.0 which includes the .ts file and so works fine.

Would appreciate a fix.

**Comment by sgarwood** [comment]
Try removing `@types/turf` if you have it in your `package.json` file if you have it

**Comment by danvk** [comment]
I also ran into this today. You can see on [yarnpkg][1] that `index.d.ts` didn't get published:

![image](https://user-images.githubusercontent.com/98301/64891373-cb15d480-d63f-11e9-969f-65f647df7230.png)


[1]: https://yarnpkg.com/en/package/@turf/distance?files
