### ISSUE TITLE
Arc.js missing license / attribution

### ISSUE THREAD

**Issue by mourner** [Turfjs/turf#1729]
Accidentally noticed that https://github.com/Turfjs/turf/commit/c7e69d111e0a2d1f8c9371e6c6eedba774570f15 added vendored [Arc.js](https://github.com/springmeyer/arc.js/) without properly attributing the author (@springmeyer) or including its license (which is BSD and explicitly requires attribution / license when redistributing) — surely this wasn't intentional, but would be nice to fix. cc @DenisCarriere 

Alternatively, @springmeyer would you accept a PR to expose it as a ES module (with Rollup for CommonJS/UMD) and release a new major version? That way we could remove the vendored version and get it back to dependencies.

**Comment by springmeyer** [comment]
@mourner - thanks for flagging. Yes, arc.js should support being exposed as an ES module. I would be happy to accept a PR that does that or be instructed on how to do it. I've not been following arc.js repo for some time, but I just did again so I should see notifications.

**Comment by mfedderly** [comment]
I'm going to go ahead and at least add the license header to our vendor copy. I tried to go back to just including the arc module but I don't think it will work for ES imports without some modifications to the arc package itself.

**Comment by mfedderly** [comment]
Fixed by https://github.com/Turfjs/turf/pull/2175
