### ISSUE TITLE
destination and rhumbDestination resulting in wrong distnace the closer to the North/South deviation  angle applied

### ISSUE THREAD

**Issue by jcimoch** [Turfjs/turf#1732]
When you look at example below you can see 3 points. 
Two of them are in about 100 miles distance on the same latitude. 
One of them is supposed to be 100miles away to the North direction (90 degrees), but clearly it's not 100miles, more like 10000miles. 

Why is this happening? Is it a bug or I don't understand something? 
I know that in Mercator projection we have the same distance but not angles, however I don't see corelation in calculations here to the projection issue (nevertheles this issue https://github.com/Turfjs/turf/issues/684 seems to touch similar problem)
![Screenshot 2019-07-16 at 16 59 47](https://user-images.githubusercontent.com/5717461/61305475-2e73b980-a7eb-11e9-9821-84c6c8b34a6f.png)

 
**Code example reproducing the problem** [HERE](http://jsfiddle.net/ftLmjur0/1/)

**Comment by dpmcmlxxvi** [comment]
Doesn't look like a bug. Leaflet expects coordinates in order (latitude, longitude) but Turf expects them in the order (longitude, latitude). Just reverse them before using in Turf and then reverse them back when using the result in Leaflet.

**Comment by stebogit** [comment]
@jcimoch I believe this is due to the [distortion](https://en.wikipedia.org/wiki/Mercator_projection#Distortion) of the Mercator projection. Rhumb functions move along straight lines, so the issue is emphasised.

**Comment by jcimoch** [comment]
@dpmcmlxxvi good catch! indeed it's argument (lat/lon) order. I was reversing it however forgot to also revers the output back ... thanks a lot!!

here is solution 
http://jsfiddle.net/3x7548Lm/

I'm closing the topic.
