### ISSUE TITLE
TypeScript type definitions not included in npm-installed @turf/clusters-dbscan

### ISSUE THREAD

**Issue by ssalka** [Turfjs/turf#1733]
Example:
```ts
import clustersDbscan from '@turf/clusters-dbscan';

const myFeatureCollection = featureCollection(...);

// return value inferred as `any`
const result = clustersDbscan(myFeatureCollection, 10);

// this should cause a TS compiler error, but doesn't because `result` type is `any`
console.log(result.doesntExist);
```

Expected: the above code should not compile, since `doesntExist` isn't a real field of the return object, which the compiler would know if type definitions for this module were included.

I suspect this is likely also an issue w/ some other turf packages, but haven't checked myself.

Would suggest enabling the [`declaration` option in tsconfig.json](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options), or otherwise explicitly making sure that a `.d.ts` file is included in the packaged module

**Comment by thisjeremiah** [comment]
I am also experiencing this issue with `@turf/distance`.

**Comment by sgarwood** [comment]
Try removing `@types/turf` if you have it in your `package.json` file if you have it

**Comment by mad-it** [comment]
Have the same issue with `@turf/circle`.

**Comment by chrisparton1991** [comment]
The repo seems to be missing `.d.ts` files for some of the features (e.g. no `@turf/distance/index.d.ts`).

If this is a simple case of a missing type definition, I'm happy to raise a PR to add typings for `@turf/distance`.
