### ISSUE TITLE
Is Envelope redundant?

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1734]
I'm confused what purpose `envelope` serves.

>Takes any number of features and returns a rectangular Polygon that encompasses all vertices.

Meanwhile, `bbox`:

>Takes a set of features, calculates the bbox of all input features, and returns a bounding box.

and `bboxPolygon`:

>Takes a bbox and returns an equivalent polygon.

So... `turf.envelope(x)` is equivalent to `turf.bboxPolygon(turf.bbox(x))`?

It seems to be so in my primitive testing.

**Comment by dpmcmlxxvi** [comment]
Looks like it. If you check out the code:

https://github.com/Turfjs/turf/blob/b6cb691e0d23293ca0c881fe561f0e8a4536ad6a/packages/turf-envelope/index.js#L23

it looks like the implementation is just what you wrote. I guess it could be classified as a convenience function.

**Comment by rowanwins** [comment]
Yeah it's just a convenience method that has been [discussed in the past](https://github.com/Turfjs/turf/issues/306#issuecomment-185336634) , to date it's held on
