### ISSUE TITLE
@turf/boolean-valid unreleased to npm

### ISSUE THREAD

**Issue by ntatko** [Turfjs/turf#1737]
Hello.

I'm interested in using the fairly new `@turf/boolean-valid` package from NPM, however, it appears as though it has yet to be published as a free-standing module or as a part of Turf. #1302 was merged quite a while ago, I'm just wondering if there's anything I can do to get it out the door. 

Thanks so much!

**Comment by rowanwins** [comment]
Hi @ntatko  

It should be available via the alpha release,
`npm install turf@7.0.0-alpha.1`

Cheers
Rowan

**Comment by ntatko** [comment]
Thanks!
