### ISSUE TITLE
chunk line computed by oldLine is a little offset from oldLine

### ISSUE THREAD

**Issue by wanyicss** [Turfjs/turf#1738]
line data：
```js
const oldLine = {
  "type": "Feature",
  "geometry": {
    "type": "LineString",
    "coordinates": [[120, 30], [121, 31]]
  }
}
```
new line computed by source code:
```js
let newLine = {
    "type": "FeatureCollection",
    "features": []
}
const chunk = turf.lineChunk(oldLine, 0.2)
chunk.features.map((cf, index)=>{
  newLine.features.push({
    "type": "Feature",
    "geometry": {
       "type":"Point",
       "coordinates":cf.geometry.coordinates[1]
    }
  })
})
```
turf version: 4.7.3

expect: newLine and oldLine on the same line
result:
<img width="526" alt="屏幕快照 2019-08-07 下午4 21 37" src="https://user-images.githubusercontent.com/10771694/62607223-4c3ac700-b930-11e9-9463-d0c9e46c0e16.png">

**Comment by firefueled** [comment]
[Sandbox showing misalignment](https://codesandbox.io/s/points-out-of-line-11ri4?file=/src/App.js)

**Comment by firefueled** [comment]
I updated the example to show that the points created for the line fail a `booleanPointOnLine` check

**Comment by mfedderly** [comment]
I think this is fixed in the 6.x series. Please reopen if this is incorrect.
