### ISSUE TITLE
Turf feature creation does not convert nested object properly

### ISSUE THREAD

**Issue by Stophface** [Turfjs/turf#1739]
I am using the [helper function][1] `turf.point()`

    const feature = turfHelpers.point(coords, properties, { id: properties.id });

`properties` looks like this

    properties = {
      id: 1,
      thisWorks: 'no problem'
      foo: {
        thisDoesntWork: 'this is a problem'
        }
      }

When I create `feature` with `turfHelpers.point()`, it messes with the object. The nested object is not an `object` anymore, but gets stringyfied...

So, `features.properties` is
    
    {
      id: 1,
      thisWorks: 'no problem'
      foo: "{
        thisDoesntWork: 'this is a problem'
      }"
    }

Now, I cannot access. `feature.properties.foo.thisDoesntWork` anymore, because its a string...
Why is `turf.js` doing that?

  [1]: https://turfjs.org/docs/#point

**Comment by morganherlocker** [comment]
Ran into this today. I am not sure why this change was made, but I believe we should switch back to passing the object without modification. I'll do some digging to see if there was a reason for the change, but my guess is interoperability with columnar formats.

**Comment by morganherlocker** [comment]
Can you confirm that this is happening strictly with a turf call? In my case, I realized that mapbox-gl was the culprit, not Turf.

**Comment by Stophface** [comment]
@morganherlocker  My bad. You are right!
