### ISSUE TITLE
Proposal for using Kotlin as developing language

### ISSUE THREAD

**Issue by kochizufan** [Turfjs/turf#1740]
Hi turf members,

This is just an idea but why don't we implement turfjs by using Kotlin as developing language?

Kotlin can be compiled into JavaScript, and with Kotlin/Native, it also can be compiled into Android library and iOS framework.
This helps to increase the number of users of turfjs!

**Comment by morganherlocker** [comment]
Hi @kochizufan, thanks for the suggestion, but not interested in changing the language at this point. Turf is a mature project and changing the language would not be a productive use of time this far in.
