### ISSUE TITLE
Typescript type definitions not included in @turf/centroid

### ISSUE THREAD

**Issue by gertgeringer** [Turfjs/turf#1742]
The index.d.ts file for the @turf/centroid package is missing.

**Comment by EvertEt** [comment]
Same problem for all 6.0.x versions of @turf/union

**Comment by OlivierKamers** [comment]
@mfedderly I believe this is still a problem for the @turf/centroid package, using the latest available version 6.0.2:
![image](https://user-images.githubusercontent.com/5834741/84478800-2f7ac880-ac92-11ea-9e6d-971373ab0732.png)

**Comment by mfedderly** [comment]
Yes they haven't made it to a stable release yet. If you want to check it out, you can try @turf/centroid@6.2.0-alpha.1 but we need to fix #1866 before we can release 6.2.0.
