### ISSUE TITLE
cannot import @turf/difference from typescript

### ISSUE THREAD

**Issue by noerw** [Turfjs/turf#1745]
Importing `@turf/intersect` works fine, however doing the following gives `TypeError: difference_1.default is not a function` after compiling to javascript.

```ts
import difference from '@turf/difference'
difference()
```

Reason seems to be, that the function is exported as `module.exports = difference`, whereas the working @turf/intersect has `exports.default = intersect`

**Comment by rlueder** [comment]
related to https://github.com/Turfjs/turf/issues/1478

**Comment by mfedderly** [comment]
I think this should be fixed now. Please reopen if I'm wrong.
