### ISSUE TITLE
Distance mis-reported

### ISSUE THREAD

**Issue by stockholmux** [Turfjs/turf#175]
I'm running the following code:

```
var
  turf = require('turf'),
  distance = turf.distance,
  point = turf.point,
  unit = 'miles';


console.log(distance(point(42.954553, -81.347474),point(46.471034, -80.980912),unit));
```

The result I'm getting is:
```
45.105636619364745
```

Now, those two coordinates are London, Ontario and Sudbury, Ontario which are over 240 miles apart, checked against [this](http://tjpeiffer.com/crowflies.html). Other coordinates seem to be reporting rational distances. Am I doing something wrong or is this a bug?

**Comment by morganherlocker** [comment]
Hey @stockholmux, the issue is that you are using lat,lon. Turf assumes data will be x,y. I tried flipping your coordinates and got `243.70683798086725`. 

```
var dist = require('turf-distance')
var p1 = {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.347474,
          42.954553
        ]
      }
    }
var p2 = {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -80.980912, 46.471034
        ]
      }
    }
console.log(dist(p1,p2,'miles'))
```

Thanks for reporting the issue. I will document this a bit better to avoid the confusion in the future. For reference, Turf follows the [GeoJSON](http://geojson.org/geojson-spec.html) spec for all data, which specifies x,y,z encoding.

> A position is represented by an array of numbers. There must be at least two elements, and may be more. The order of elements must follow x, y, z order (easting, northing, altitude for coordinates in a projected coordinate reference system, or longitude, latitude, altitude for coordinates in a geographic coordinate reference system). Any number of additional elements are allowed -- interpretation and meaning of additional elements is beyond the scope of this specification.

**Comment by stockholmux** [comment]
Yep! That'll do it. Thanks for your quick response.
