### ISSUE TITLE
How to use turf in angular library 

### ISSUE THREAD

**Issue by SSaeedHoseini** [Turfjs/turf#1754]
I used turf library in an angular library which installed the following:

`npm install @turf/turf`

And I've used it that way. 

```
import { Component, OnInit } from '@angular/core';
import * as turf from '@turf/turf';

@Component({
  selector: 'lib-mylibrary',
  template: `
    <p>
      mylibrary works!
    </p>
    <button (click)="lo()">Click</button>
  `,
  styles: []
})
export class MylibraryComponent {
  constructor() { }
  lo() {
    console.log(turf.point([12, 12]));
  }
}
```

when the library is building, everything is Ok
`ng b myLibrary`

but when I use my library in an angular app this error raised :

```
ERROR in ./dist/MyLibrary/fesm5/MyLibrary.js
Module not found: Error: Can't resolve '@turf/turf' in 'XXX\dist\MyLibrary\fesm5'

```

**Comment by stebogit** [comment]
@SSaeedHoseini what version are you using?
v6 has few issues with imports. Maybe you could try the latest v5.

**Comment by SSaeedHoseini** [comment]
@stebogit      The version I use "@turf/turf": "^5.1.6"
