### ISSUE TITLE
cleanCoords fails with line of 3 coordinates of which the first two are equal

### ISSUE THREAD

**Issue by kaligrafy** [Turfjs/turf#1758]
Using this data:
```[[0,0], [0,0], [0,2]]```,
At line 116, isPointOnLineSegment fails because the new length is less than 3:
```if (isPointOnLineSegment(newPoints[newPointsLength - 3], newPoints[newPointsLength - 1], newPoints[newPointsLength - 2])) newPoints.splice(newPoints.length - 2, 1);```

Before using isPointOnLineSegment, we should verify that lentgh of newPoints is > 3, otherwise just return the newPoints.

**Comment by pmeller-siili** [comment]
I've encountered problem with `simplify` for 2 equal coordinates (e.g. `[[0,0], [0,0]]`) which originates with from the bug described above.

`cleanCoords` used internally in `simplify` results with array that includes `undefined` (`[[0,0], undefined]`).

**Comment by pmeller** [comment]
I've encountered problem with `simplify` for 2 equal coordinates (e.g. `[[0,0], [0,0]]`) which originates with from the bug described above.

`cleanCoords` used internally in `simplify` results with array that includes `undefined` (`[[0,0], undefined]`).

**Comment by misaugstad** [comment]
Having a very similar issue. Inputting a two-point linestring with the same start and end point sets the 2nd endpoint to `undefined`. We really shouldn't be trying to input something invalid like that, but that's the output I got from `lineSlice()`. And I'd love for one of those two to give an error that isn't an `undefined` embedded in the coordinates.

**Comment by Jamie5** [comment]
Running into this too. Since the code has shifted around a bit, I think it's the second call to `isPointOnLineSegment` which needs a guard of `if (newPointsLength > 2) {`, since the first call to it already has such a guard.
