### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: coordinates must only contain numbers

### ISSUE THREAD

**Issue by PhilippeCorreges** [Turfjs/turf#1759]
Please provide the following when reporting an issue:

Hello,
I am not sure to use gitHub for support but I guess I have encoutered an issue.
I am building an Array of Arrays of coordinates 

> this.polygons.push(element.geoDefinition.features['0'].geometry.coordinates);

to be able to run:

      const searchWithin = turf.multiPolygon(this.polygons);
      const ptsWithin = turf.pointsWithinPolygon(points, searchWithin);

with:
```
var points = turf.points([
        [43.247056, 5.403461999999999]
    ]);
```

The built Array is
```
[    
 0: Array(1)
    0: Array(6)
        0:  [5.379856, 43.252967]
        1:  [5.422988, 43.249466]
        2:  [5.425048, 43.245153]
        3:  [5.383804, 43.239838]
        4:  [5.399856, 43.212967]
        5:  [5.379856, 43.252967]
1: Array(1)
    0: Array(6)
        0:  [5.39014, 43.279295]
        1:  [5.393069, 43.279249]
        2:  [5.391814, 43.278421]
        3:  [5.390709, 43.278749]
        4:  [5.3909, 43.2785]
        5:  [5.39014, 43.279295]
 ]
```
on turf.pointsWithinPolygon(points, searchWithin) I am getting the error.

Coordinates are numbers.

**Comment by dpmcmlxxvi** [comment]
@PhilippeCorreges 1) We can't see what the value of `this.polygons` is that you are using, but the error message suggests that it is not an array of polygons but instead a single polygon, so your coordinates array is not nested deep enough. Try wrapping it in `[]`. 2) Also, your `points` coordinates are in the wrong order. That won't cause an error but may cause you to return no points found.

**Comment by PhilippeCorreges** [comment]
Hi @dpmcmlxxvi 
As requested here is the this.polygons array. It is an Array of Arrays of Coordinates Arrays. Here it is an Array of 3 Arrays of 6 coordinates Array each.

![Capture d’écran 2019-09-23 à 13 20 43](https://user-images.githubusercontent.com/11230777/65421816-03b66a80-de05-11e9-9c3b-36c5789cf218.png)

**Comment by PhilippeCorreges** [comment]
Hello @dpmcmlxxvi 
I tried to hard code things like below:
```
          var points = turf.points([
            [ 5.403467699999999,43.247045299999996]
        ]);

      const searchWithin = turf.polygon([
        [
          [5.39014, 43.279295],
          [5.393069, 43.279249],
          [5.391814, 43.278421],
          [5.390709, 43.278749],
          [5.3909, 43.2785],
          [5.39014, 43.279295]
        ],
            [
              [5.379856, 43.252967],
              [5.422988, 43.249466],
              [5.425048, 43.245153],
             [5.383804, 43.239838],
             [5.399856, 43.212967],
             [5.379856, 43.252967]
            ],
            [
              [-0.607051, 44.840753],
              [-0.543708, 44.832962],
              [-0.52225, 44.820544],
              [-0.566367, 44.808853],
              [-0.586367, 44.788853],
              [-0.607051, 44.840753]
            ]
          ]);
 //         console.log(points);
      const ptsWithin = turf.pointsWithinPolygon(points, searchWithin);
      console.log('pointWithIn' + JSON.stringify(ptsWithin));
```

My point is withing the first polygon. So, everything is ok. If I change the structure i.e. my 1st polygon is 2nd, turf.pointsWithinPolygon does not return anything.

Later on I will manipulate data from the database but I want to be sure of everything before.

Thanks for any help.

Philippe

**Comment by PhilippeCorreges** [comment]
ok. I used MultiPolygon.
Nevertheless, I still have issues and still getting this message ...
From the database, I receive (geoDefinition.features['0'].geometry.coordinates) which is an array of arrays of arrays (3 dimensions). I declared a variable like polygons: number[][][][] and push in it what I receive from the database. I will have a 4 dimensions array that is needed, correct ?

**Comment by dpmcmlxxvi** [comment]
I think the problem is how you are defining multipolygons. This works for me:

```
var points = turf.points([
    [ 5.403467699999999,43.247045299999996]
]);

const searchWithin = turf.multiPolygon([
  [
    [
      [5.39014, 43.279295],
      [5.393069, 43.279249],
      [5.391814, 43.278421],
      [5.390709, 43.278749],
      [5.3909, 43.2785],
      [5.39014, 43.279295]
    ]
  ],
  [
    [
      [5.379856, 43.252967],
      [5.422988, 43.249466],
      [5.425048, 43.245153],
      [5.383804, 43.239838],
      [5.399856, 43.212967],
      [5.379856, 43.252967]
    ]
  ],
  [
    [
      [-0.607051, 44.840753],
      [-0.543708, 44.832962],
      [-0.52225, 44.820544],
      [-0.566367, 44.808853],
      [-0.586367, 44.788853],
      [-0.607051, 44.840753]
    ]
  ]
]);
const ptsWithin = turf.pointsWithinPolygon(points, searchWithin);
console.log('pointWithIn' + JSON.stringify(ptsWithin));
// = pointWithIn{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[5.403467699999999,43.247045299999996]}}]}
```

**Comment by PhilippeCorreges** [comment]
hi @dpmcmlxxvi 
I finally succeeded having it working. It was effectively related to the number of [].
Thanks for your support and thanks to have maintained this issue open.
You can close it now.
