### ISSUE TITLE
One suspect is the line problem caused by lineOffset/bezierSpline/...

### ISSUE THREAD

**Issue by ifzm** [Turfjs/turf#1766]
This is a problem that still exists for version turf@5.1.6
Test: https://jsfiddle.net/devfzm/12zbspqk/2/

![image](https://user-images.githubusercontent.com/12740295/66448832-6f473b80-ea85-11e9-9455-cd3c70b12ac5.png)

_Originally posted by @ifzm in https://github.com/Turfjs/turf/issues/1024#issuecomment-539804817_

**Comment by mfedderly** [comment]
Closing in favor of https://github.com/Turfjs/turf/issues/1024
