### ISSUE TITLE
turf/length is buggy: this is a working version

### ISSUE THREAD

**Issue by alexroat** [Turfjs/turf#1773]
turf.length is buggy. It computes a linestring length different than the sum of harvesine formula applied to each segment. Here below the verification. Please, consider to replace with lsLength implementation.

```
> var line = turf.lineString([[-83, 30], [-84, 36], [-78, 41]]);
> function lsLength(ls)
... {
...     var l=0;
...     var cc=ls.geometry.coordinates.map(function(x){return turf.point(x);});
...     for (var i in cc)
...     {
.....         if (i<=0)
.....             continue;
.....         l+=turf.distance(cc[i-1],cc[i]);
.....     }
...     return l;
... }
undefined
> lsLength(line)
**1436.4129262509587**
> turf.line
turf.lineDistance  turf.lineSlice     turf.lineString    

> turf.line
turf.lineDistance  turf.lineSlice     turf.lineString    

> turf.length = require("@turf/length").default;
[Function: length]
> turf.length(line)
**1435.9641289155197**

```

Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by smallsaucepan** [comment]
Just checked this in v7.1.0 and got the result 1435.9641289155197 🎉 This was probably fixed in an earlier PR.

Thanks for reporting @alexroat.
