### ISSUE TITLE
Unable to generate representative isolines at close proximity

### ISSUE THREAD

**Issue by SidneyNiccolson** [Turfjs/turf#1774]
Geojson can be found here: [geojson-sample](https://gist.github.com/SidneyNiccolson/d51580196ebf820f5c03916537b3d6b5)

I followed the documentation and also looked in past issues (namely: #829 ), but I seem to be unable to generate nice isolines based on my data. Steps performed:

- Creation of my base map (which is working fine):
![image](https://user-images.githubusercontent.com/8831506/67298251-485c2100-f4eb-11e9-8972-92fe1b8ef9b0.png)

- Use turf.interpolate to generate a pointGrid instead of random points:

![image](https://user-images.githubusercontent.com/8831506/67298054-0501b280-f4eb-11e9-9941-11c1216b5616.png)
 `var options = {gridType: 'points', property:'mslp', units:'kilometers'} `
 `var grid = interpolate(pointGrid, 0.002, options)`

- use turf.isolines: 
![image](https://user-images.githubusercontent.com/8831506/67300123-c9b4b300-f4ed-11e9-8ecd-335d4d0a6a12.png)

`var newBreaks = [breaks.min, breaks.q25, breaks.q50, breaks.q75, breaks.max] `
 `var lines = isolines(grid, newBreaks, {zProperty: 'mslp'})`

[result object](https://gist.github.com/SidneyNiccolson/be26060306f4e8fcf83039f53ae11196)

**Problem**
From reading the documentation I figured that I cannot use directly the geojson without firstly creating a pointGrid. Personally as a newbie with Turf my assumption is that the issue starts with the fact that the datapoints are at a close proximity. Next to that I tried altering the cellSize which either leads to nothing (empty coordinates overall) or heavy memory use (logically). I also tried to increase the values times 10 and times 100, but to no avail.

Can someone assist me if this is the right way to go? 
The endresult should be something like [this](https://observablehq.com/@mbostock/turf-isolines), but with real spatial data off course.
Any help would be greatly appreciated.

**Comment by SidneyNiccolson** [comment]
Closing the issue. I got it working with adding more breaks coupled with isobands() instead of isolines(). A bit of tinkering on the options for the interpolate() also improved the end result.

**Comment by morganherlocker** [comment]
Thanks for sharing @SidneyNiccolson. I wrote these algorithms in the very early days ~8 years ago, and I know they can be finicky without some manual nudging. I appreciate you working through the issue.

**Comment by SidneyNiccolson** [comment]
@morganherlocker Thanks for your response. I also worked a bit more on the dataset with ArcGis and found out that Kriging suits my case better. I checked the issue list, are there any updates on  #41? Aside I'm also considering the workaround on #1034
