### ISSUE TITLE
ring of polygons -> @turf/union -> multipolygon with overlapping interior ring ?

### ISSUE THREAD

**Issue by cmonacaps** [Turfjs/turf#1775]
Hi, I have a ring of polygons, whose sides touch, but do not overlap, with an empty region inside, that is completely encircled by the polygons.  It looks like a donut.  A donut of separate bits of dough that have been smushed together but not become one piece of dough yet.

I want to make the donut into a donut of a single piece of dough.

I do a `@turf/union` on it, using `geomReduce` and merge each geom with the accumulating merge doughball.

Instead of a donut I get a multipolygon where the donut hole, whose size and shape looks correct, is an interior, completely overlapping polygon.  More of a jelly donut.

I think it is because the winding of the donut hole should be clockwise, but it isn't.  I think I could like, rewind the interior and get my shape.  But this is an edge case in some code that should take a set of polygons, mostly non overlapping but frequently touching, and return a minimal multipolygon representing the same covered area.

Perhaps `@turf/dissolve` is right way instead.  Perhaps there is an option to pass to union or another turf function to correctly make the donut.

Hopefully, someone who reads this recognizes the problem and give a quick answer, but if not I will follow up with an example GeoJSON and snippet.

edit - using `@turf/union`, mistakenly called "merge"

Please provide the following when reporting an issue:

- [TO DO] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [TO DO] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by rowanwins** [comment]
This is likely resolved by v6.3.0 although there isn't enough info to reproduce so I'm going to close
