### ISSUE TITLE
@turf/difference result is invalid MultiPolygon

### ISSUE THREAD

**Issue by cmonacaps** [Turfjs/turf#1776]
Two features pass geojsonhint linter, but the result from `difference` is pretty odd.

I put the 2 geojson files and one complete js file having both geojsons inline and some code:

https://gist.github.com/cmonacaps/4e8a427dfe7c32ac3a2a0c401d6c59c1

The result from `difference` is type `MultiPolygon` but it has some "Linear Rings" with less than 4 coordinates, and some where the start and end coordinate are not equal.

If I try to repeat the operation, doing a difference again where the first parameter ("complete") is the result of the prior diff, `difference` throws an error because of these same invariants.

I tried to do jsfiddle but couldn't figure out how to get the right turf lib and also load the geojson files.

My `packages.json` says:
`    "@turf/difference": "6.0.1",`

Please provide the following when reporting an issue:

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [not really] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by rowanwins** [comment]
This is resolved in v6.3.0
