### ISSUE TITLE
@turf/intersect throws "Each LinearRing of a Polygon must have 4 or more Positions."

### ISSUE THREAD

**Issue by stuarta0** [Turfjs/turf#1777]
Turf fails to intepret the return type from martinez during intersection if a particular case is encountered internally in martinez. Turf's logic then tries to create a polygon with an incorrect coordinate array, which throws the linear ring error.

Here's a test case for @turf/intersect which fails in the current 6.1.3 version (I'd create a smaller test case, but this was real world data causing the issue, and I'd need to understand martinez-polygon-clipping to produce the correct test):
https://gist.github.com/stuarta0/15101e670873471b20bc953b90971ce3

The failing case occurs when this line in martinez-polygon-clipping is encountered:
https://github.com/w8r/martinez/blob/827e8433f39054570e6e668dc4c0c0b0f93b8cd6/src/connect_edges.js#L111

Which causes a deeply nested array to be returned to turf:
https://github.com/Turfjs/turf/blob/b6cb691e0d23293ca0c881fe561f0e8a4536ad6a/packages/turf-intersect/index.ts#L52
```
[                  // ??
  [                // collection?
    [              // multipolygon
      [            // polygon
        [          // ring
          [x, y],  // coord
          ...
```

I've got a workaround but I'm unsure whether this is the correct fix. Maybe there's an issue in martinez-polygon-clipping? Maybe it's just a case missed in turf? In any case, the existing tests still pass, and the new test passes too:
https://github.com/stuarta0/turf/tree/intersect-martinez-fix

More specifically, the change can be found here:
https://github.com/stuarta0/turf/commit/61386b19c909172e51cf03fb74696276b1c7e491

**Comment by rowanwins** [comment]
This is resolved in v6.3.0
