### ISSUE TITLE
global leaks

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#178]
there are some

![2015-01-07 at 5 53 pm](https://cloud.githubusercontent.com/assets/32314/5654919/19bcf1de-9696-11e4-8939-e5caae489918.png)

* fixed 'inside' leak in turf-tag
* fixed 'distance' leak in turf-nearest

**Comment by tchannel** [comment]
Closing - these are gone now, aside from third party leaks in jsts and javascript (from javascript.util)
