### ISSUE TITLE
Is there is a way to check if polygon is touch each other?

### ISSUE THREAD

**Issue by Jenusdy** [Turfjs/turf#1781]
![image](https://user-images.githubusercontent.com/23545319/67734635-22c3a000-fa34-11e9-84b4-4171814ed8c3.png)

I want to check if polygon is touch by another polygon. There is a way to check it?

**Comment by morganherlocker** [comment]
If the result of turf.difference is non-null, the polygons have overlap.

https://turfjs.org/docs/#difference
