### ISSUE TITLE
Use npm package instead of embedding geojson typescript definitions.

### ISSUE THREAD

**Issue by Peter-Optiway** [Turfjs/turf#1782]
Currently you have embedded your own version of geojson.d.ts instead of using the already existing package [@types/geojson](https://www.npmjs.com/package/@types/geojson).

This causes problems when you have multiple libraries that use geojson as the types aren't the same and requires additional casting.

Is there any chance you could remove your embedded geojson.d.ts and instead put a dependency on @types/geojson?

**Comment by rowanwins** [comment]
Yes this is certainly annoying @Peter-Optiway - I believe many years ago there were some issues with the defintions hence why we had embedded definitions but that may have changed.

**Comment by comatory** [comment]
Any progress on this? Anyway I wanted to ask @Peter-Optiway how do you deal with incompatibility between libs as far as TS definitions go? Do you just use `as ...` expression to cast Turf's objects into something else?

**Comment by rdmurphy** [comment]
@comatory I don't always stress about it, but there have been a few times where I've copy-pasted in the Turf code I needed and altered the types to use `@types/geojson` instead.

**Comment by twelch** [comment]
closing in favor of tracking in #1658
