### ISSUE TITLE
@turf/intersect sometimes returns improperly formatted coordinate tuples

### ISSUE THREAD

**Issue by yogurtandjam** [Turfjs/turf#1785]
Please provide the following when reporting an issue:

strangely, turf/intersect of [these two features](https://gist.github.com/yogurtandjam/a8cc42afcf67ff546c72fa250dd4ec22) returns the following feature
```
{
  type: 'Feature',
  properties: {
    entity_type: 'geofence',
    area_sqm: 149855.00957942175,
    lat: 45.49998747388729,
    lng: -73.56712921691815,
  },
  bbox: [-73.5708342, 45.4969652, -73.563561, 45.5027965],
  geometry: {
    type: 'Polygon',
    coordinates: [
      [
        [-73.5708342, 45.5009505],
        [-73.5691143, 45.5001265],
        [-73.5689451, 45.5000483],
        [-73.5669334, 45.4990216],
        [-73.5667341, 45.4989815],
        [-73.5674464, 45.4981792],
        [-73.5676978, 45.4980896],
        [-73.5683919, 45.4978923],
        [-73.56852131313369, 45.49781208771207],
        [-73.5678807, 45.4975052],
        [-73.5677529, 45.4974241],
        [-73.5673383, 45.4972178],
        [-73.5671979, 45.4971466],
        [-73.5670654, 45.4970914],
        [-73.5667672, 45.4969652],
        [-73.5660148, 45.4975449],
        [-73.5651425, 45.4982534],
        [-73.5647914, 45.498536],
        [-73.563561, 45.4995901],
        [-73.5638802, 45.4998137],
        [-73.5645449, 45.500288],
        [-73.5653412, 45.5007244],
        [-73.5662153, 45.5011559],
        [-73.5670617, 45.5016145],
        [-73.5673209, 45.5017831],
        [-73.5675031, 45.5019055],
        [-73.5679737, 45.5021498],
        [-73.5685661, 45.5024473],
        [-73.5688982, 45.5026183],
        [-73.5690299, 45.5027965],
        [-73.5708342, 45.5009505],
      ],
    ],
  },
}
```
which as you can see has a non-truncated coordinate tuple. When this feature is used as an input in another intersect call, the application freezes silently.

Expected behavior should include any or all of the following:
 - Ability to truncate coordinates upon intake
 - Ability to truncate coordinates on output
 - Ability to process coordinates without truncation
 - Ability to expose errors due to issues with truncation etc.

**Comment by rowanwins** [comment]
Hi @yogurtandjam 

I think this result is expected. If you need to truncate coordinates for subsequent operations you can use the `truncate` module. 
http://turfjs.org/docs/#truncate

Under the hood the new package which gets used for `intersect` is a bit more robust when handling very precise coordinates.
