### ISSUE TITLE
Creating intersection between polygons and buffer

### ISSUE THREAD

**Issue by MaxDragonheart** [Turfjs/turf#1787]
I am trying to create an intersection between some polygons(buildings) and a buffer from line vector. I'm using Turf with Mapbox.

I am able to create a buffer following the indication from the [official example][1] and I can render my buildings. Now with that I need to create an intersection:

      map.on('load', function() {
        .
        .
        .

    var xhttp = new XMLHttpRequest();
    xhttp.open("GET", "{% url 'linebuffer_api' %}", false);
    xhttp.send();
    var response = xhttp.responseText;
    var lines_source = JSON.parse(response) // responseJSON

    map.addSource('line_source', {
      type: 'geojson',
      data: lines_source,
    });

    map.addLayer({
        'id': 'power_line',
        'type': 'line',
        'source': 'line_source',
        'layout': {
          'line-join': 'round',
          'line-cap': 'round'
        },
        'paint': {
          'line-color': '#487bb6',
          'line-width': 4
        }
    });

        var xhttp = new XMLHttpRequest();
        xhttp.open("GET", "{% url 'buildings_api' %}", false);
        xhttp.send();
        var response = xhttp.responseText;
        var polygons_source = JSON.parse(response) // responseJSON
    
        map.addSource('polygon_source', {
          type: 'geojson',
          data: polygons_source,
        });

    map.addLayer({
        'id': 'building',
        'type': 'fill',
        'source': 'polygon_source',
        'paint': {
          'fill-color': '#487bb6',
          'fill-opacity': 1.0,
          'fill-outline-color': '#000'
        }
    });
    
        var mybuffer = turf.buffer(
            lines_source, 
            200, 
            {units: 'meters'}
            );
    
        var myintersection = turf.intersect(polygons_source, mybuffer);
    
        map.addLayer({
              'id': 'intersection',
              'type': 'fill',
              'source': {
                  'type': 'geojson',
                  'data': myintersection
              },
              'paint': {
                  'fill-color': '#fff',
                  'fill-opacity': 0.50,
                  'fill-outline-color': '#f30'
              }
          });
    
      });

Unfortunately, I see this error:

> Uncaught Error: geojson must be a valid Feature or Geometry Object

If I delete a code from `var myintersection` and the relative style I can see my buildings without problems.

What do I have wrong?

I am new to JavaScript.

  [1]: https://turfjs.org/docs/#buffer

**Comment by stebogit** [comment]
What's the content of your geojson objects?
There's probably something wrong in there

**Comment by MaxDragonheart** [comment]
This is the line for my buffer: https://gist.github.com/MaxDragonheart/cf03feda3af8402869d04f5b53f9e860

And this is my buildings for the intersect: https://gist.github.com/MaxDragonheart/d6c0d50b5b8175c0b8574d21dd2a383d

I use Django Rest Framework and with its output I try to have my intersection.

**Comment by stebogit** [comment]
I guess you'll need to debug the code more in depth and see what's exactly the object that goes to the Map or whatever is actually breaking

**Comment by MaxDragonheart** [comment]
I know that in debug I can't go after `mybuffer` because with `myintersection` I see the previous error.

I don't know wich type of object is generated with the buffer. I was hoping that with the buffer I had a GeoJSON but I’m not sure anymore

**Comment by stebogit** [comment]
What's the output turf.buffer? And what's `lines_source`?
There's must be some issue in there

**Comment by MaxDragonheart** [comment]
I've updated my first post with `line_source`. 
Is the output of buffer `mybuffer`? Maybe the problem is here...

Here a screenshot from my map. As you can see it is possible to see `line_source`, `polygons_source` and `mybuffer` but not `myintersection`

![Screenshot from 2019-11-11 19-12-17](https://user-images.githubusercontent.com/18444902/68610110-503e2e00-04b7-11ea-96de-11d4c3edd1ab.png)

**Comment by stebogit** [comment]
No, you did not show the actual content of `lines_source` but mainly Map code/screenshot, which is not relevant here.

**Comment by MaxDragonheart** [comment]
What do you mean?

**Comment by MaxDragonheart** [comment]
I think that my problem is that I have a FeatureCollection and intersect would like a [Faeture](https://turfjs.org/docs/#intersect).
I need to transform FeatureCollection to Feature maybe..?

**Comment by MaxDragonheart** [comment]
I think this is the [same situation](https://gis.stackexchange.com/questions/129750/intersecting-featurecollections-in-turf-js) of mine. FeatureCollection aren't supported since 2014.

**Comment by stebogit** [comment]
Yes, `@turf/intersect` expects two `(Multi)Polygon`s

You can use [`featureEach`](https://github.com/Turfjs/turf/tree/master/packages/turf-meta#featureeach) (`@turf/meta`) to loop through each feature of a `FeatureCollection`.

**Comment by MaxDragonheart** [comment]
Then if I put `polygons_source` inside `featureEach`I can use the response for the intersect?

I need to do a thing like this:
```
var polygons_source_to_feature =  turf.featureEach(polygons_source , function (currentFeature, featureIndex) {
  //=currentFeature
  //=featureIndex
});
```
?

**Comment by stebogit** [comment]
Yes, you should be able to

**Comment by MaxDragonheart** [comment]
Ok, as soon as possible I try

**Comment by MaxDragonheart** [comment]
Using featureEach with polygons_source 
```
var polygons_source_to_feature =  turf.featureEach(polygons_source , function (currentFeature, featureIndex) {
  //=currentFeature
  //=featureIndex
});
```

I see this error:

> Uncaught Error: geojson is required

[Here](https://gis.stackexchange.com/questions/264856/turf-js-intersect-problem) there is a similar problem but with Leaflet instead of MapBox.

I need to create `polygons_source_to_feature` and `buffer_to_feature`, after this I can use intersect?

> var myintersection = turf.intersect(polygons_source_to_feature, buffer_to_feature)

I've some difficult on this, I thought it was simple because with SQL is easiest but I need to do this with JavaScript

**Comment by stebogit** [comment]
```js
var line = lines_source.features[0]; // assuming you'll always have a single LineString here
var buffer = turf.buffer(line, 200, {units: 'meters'});

var intersected = turf.featureEach(polygons_source , function (polygon, index) {
  return turf.intersect(polygon, buffer);
});
```
or maybe better
```js
var intersected = turf.featureReduce(polygons_source, function (result, polygon, index) {
  var intersection = turf.intersect(polygon, buffer);
  if (intersection) result.push(intersection);
  return result;
}, []);
```
so you don't end up with a bunch of `null`s in your `intersected` result.

**Comment by MaxDragonheart** [comment]
I've used both examples and I see this error now:

> Uncaught`` Error: geojson must be a valid Feature or Geometry Object

Then I've applied another solution using this code:

```
    var mydissolve = turf.dissolve(mybuffer, {propertyName: 'combine'});    
    var comparison = polygons_source.features; 
    intersection = [];
    real_intersection = [];
    for (var i = 0; i < comparison.length; i++ ){
                var compare = comparison[i];
                var vector1 = turf.polygon(compare.geometry.coordinates);
                var vector2 = turf.polygon(mydissolve.features[0].geometry.coordinates);  

        var intersected = turf.intersect(vector1, vector2);
        
        if (intersected != null){
            intersection.push(intersected);
            real_intersection.push(compare);
        }

    }
    var collection = turf.featureCollection(real_intersection);
```
Now I'm be able to iterate the intersection between my datas but I see that the intersection is not correct:
![Screenshot from 2019-11-20 16-50-33](https://user-images.githubusercontent.com/18444902/69254090-f5db5680-0bb5-11ea-87fd-a560344b1c32.png)

Are you sure that turf.intersect haven't any bug?

Using PostGIS I see this:
![intersect_postgis](https://user-images.githubusercontent.com/18444902/69254265-494da480-0bb6-11ea-924e-ab427128db76.png)

As you can see some polygons that are inside the buffer aren't rendered with the intersection. I expect the same result of PostGIS on the browser, but is not so.

**Comment by stebogit** [comment]
@MaxDragonheart the code you shared is not easy to analyze particularly because it does not highlight/show a specific issue of a Turf module.
Although I'm not at all excluding a possible issue within some Turf's module, I suspect there might be some problem in your code or the actual GeoJSON data you pass to the Turf module(s).

Since we can't debug your code, I suggest you to find out a specific unexpected behaviour of one module and post a reproducible (possibly a [jsfiddle](https://jsfiddle.net) or similar) example, so we can take a close look at it and help you in a more effective way.

**Comment by MaxDragonheart** [comment]
@stebogit here there is my code:
https://jsfiddle.net/maxdragonheart/q1d2zpso/13/

As I said the my vectors cames from Django Rest Framework. I can't reproduce this but you can put this 
[lines_source.zip](https://github.com/Turfjs/turf/files/3873464/lines_source.zip) instead of `{% url 'linebuffer_api' %}` and this 
[polygons_source.zip](https://github.com/Turfjs/turf/files/3873474/polygons_source.zip) instead of `{% url 'buildings_api' %}`

I exclude that the problem comes from my vectors because via PostGIS I see a perfect intersection without topological errors.

**Comment by stebogit** [comment]
@MaxDragonheart sorry but I won't debug your entire code, and this is not really the place where to seek for help on that.
As I mentioned you can narrow down your code to present a specific simple case (say a single polygon not returning the right/expected output when intersected with your buffer using `@turf/intersect`) and I or other developers can check if there is in fact an issue with the library.

BTW, FYI you can create a [public gist](https://gist.github.com/) to serve static files, e.g. json data.

**Comment by MaxDragonheart** [comment]
@stebogit following your suggestions I've simplyfied the code on the [new example](https://jsfiddle.net/maxdragonheart/q1d2zpso/29/).
Now I use only two polygons: one from the buffer, the second it is a building. As you can see the intersection doesn't clip the building with the buffer.

![Screenshot from 2019-11-22 08-59-52](https://user-images.githubusercontent.com/18444902/69412063-7e6d0a80-0d0e-11ea-9c4d-cd802a8fefac.png)

It seem a "within" function and not an "intersect" function like on PostGIS

**Comment by stebogit** [comment]
@MaxDragonheart there is definitely something wrong in your code, as I suspected.
Run this and you'll see `@turf/intersect` works as expected:

```js
var map = new mapboxgl.Map({
    container: 'map',
    accessToken: 'pk.eyJ1IjoibWF4cGVudGEiLCJhIjoiY2szNzJ5M3RtMDdsZzNtbzluMzRqczB2cyJ9.oBCPa5oV2driLsx-tEiugg',
    style: 'mapbox://styles/maxpenta/ck3733qvp0tn81cmxe0m4whkf',
    center: [14.36149, 40.835692],
    zoom: 14,
});

map.on('load', function () {

    var line = {"id":8,"type":"Feature","geometry":{"type":"LineString","coordinates":[[14.3589111,40.8391469],[14.3586336,40.8392848],[14.360673,40.837083],[14.3639037,40.8354795],[14.3653988,40.8332378],[14.3669238,40.8312481],[14.3682214,40.8296107],[14.3705268,40.8273662],[14.3726347,40.8253014],[14.3740272,40.82394],[14.3767689,40.8212471],[14.3767643,40.8215147]]},"properties":{}};

    var polygon = {"id":3130,"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[14.3613346,40.8358225],[14.361336,40.8358242],[14.3614867,40.8358077],[14.3614763,40.835753],[14.3616483,40.8357341],[14.3616274,40.8356242],[14.3614797,40.8356404],[14.3614895,40.8356921],[14.3614592,40.8356954],[14.3613693,40.8352221],[14.3613955,40.8352192],[14.3614059,40.8352739],[14.3615526,40.8352578],[14.361532,40.835149],[14.3613613,40.8351678],[14.3613341,40.8350242],[14.3614995,40.835006],[14.3614784,40.8348948],[14.361339,40.8349101],[14.3613488,40.8349615],[14.3613216,40.8349645],[14.3612322,40.8344932],[14.3612758,40.8344884],[14.3612879,40.8345519],[14.3614223,40.8345371],[14.361399,40.8344141],[14.3612206,40.8344338],[14.3612033,40.8343427],[14.3610523,40.8343593],[14.3611184,40.8347079],[14.360952,40.8347261],[14.3609611,40.8347743],[14.3609299,40.834777],[14.3609063,40.8347369],[14.36077,40.8347804],[14.3608011,40.8348329],[14.3607809,40.8348425],[14.3606677,40.8346551],[14.3608291,40.8345989],[14.3607695,40.8345003],[14.3606291,40.8345416],[14.3606617,40.8345956],[14.3606375,40.8346041],[14.3605287,40.8344238],[14.3606956,40.8343656],[14.3606311,40.8342588],[14.360496,40.8343086],[14.3605282,40.8343619],[14.3605002,40.8343686],[14.3604444,40.8342762],[14.3604134,40.8342855],[14.3604096,40.8342678],[14.3604411,40.8342679],[14.3604129,40.8341273],[14.3604388,40.8341243],[14.3604495,40.8341779],[14.3605995,40.8341605],[14.3605776,40.8340513],[14.3604048,40.8340646],[14.3603361,40.8337214],[14.3601942,40.8337351],[14.3602176,40.8338498],[14.3601896,40.8338531],[14.3601777,40.8337948],[14.3600762,40.8338068],[14.3600984,40.833916],[14.3602273,40.8339007],[14.360306,40.834286],[14.3603713,40.8342783],[14.3603783,40.8342922],[14.3603044,40.8343148],[14.3604603,40.8345454],[14.3607303,40.8350181],[14.3608574,40.8349762],[14.3608081,40.8348898],[14.3609663,40.8348376],[14.3611191,40.8348238],[14.3611078,40.8347637],[14.361135,40.8347623],[14.3612667,40.8354565],[14.3612423,40.8354591],[14.3612318,40.8354039],[14.3610874,40.8354197],[14.3611084,40.8355304],[14.3612757,40.8355121],[14.3613346,40.8358225]]]},"properties":{}};

    var mybuffer = turf.buffer(line, 200, {units: 'meters'});

    var intersected = turf.intersect(polygon, mybuffer);

    // console.log(JSON.stringify(intersected))

    map.addLayer({
      'id': 'buffer', 'type': 'fill',
      'source': {'type': 'geojson', 'data': mybuffer},
      'paint': {'fill-color': '#fff', 'fill-opacity': 0.50, 'fill-outline-color': '#f30'}
    });
    
    map.addLayer({
      'id': 'poly', 'type': 'fill',
      'source': {'type': 'geojson', 'data': polygon},
      'paint': {'fill-color': '#f30', 'fill-opacity': 1.0, 'fill-outline-color': '#f30'}
    });
    
    map.addLayer({
      'id': 'intersection', 'type': 'fill',
      'source': {'type': 'geojson', 'data': intersected},
      'paint': {'fill-color': '#000', 'fill-opacity': 1.0, 'fill-outline-color': '#000'}
    });

});  
```

<img width="667" alt="Screen Shot 2019-11-22 at 7 47 56 AM" src="https://user-images.githubusercontent.com/12717225/69439743-6c826c00-0cfc-11ea-9fb8-8de5b8d1ef0b.png">

**Comment by MaxDragonheart** [comment]
But your is the simpliest and uncommon situation because normally a GeoJSON is a FeatureCollection and not a Feature. For example the function [ST_AsGeoJSON ](https://postgis.net/docs/ST_AsGeoJSON.html) from PostGIS make a FeatureCollection and if you export a vector from QGIS as GeoJSON it will be a FeatureCollection.

After over 10 days I can say that Turf.js is too young for make real spatial analysis. I hope that in the next future it will be ready for do that promise.
