### ISSUE TITLE
@turf/bbox doesn't support FeatureCollections with MultiPolygon features

### ISSUE THREAD

**Issue by foundryspatial-duncan** [Turfjs/turf#1795]
I want to fit the bounds of a map to the extend of all of its visible features. In this case, I have a 2 MultiPolygon features and 2 point features.

The `@turf/bbox` docs say "Takes **a set of features**, calculates the bbox of **all input features**, and returns a bounding box." but it only accepts one GeoJson object, so I create a FeatureCollection:

```js
const allFeatures = featureCollection([
    multiPolygon1,
    multiPolygon2,
    point1,
    point2,
]);

const turfBounds = bbox(allFeatures);
```

The code above causes this error:

```
TypeError: Cannot read property 'coordinates' of undefined
    at Object.coordEach (index.js?716c:79)
    at bbox (index.js?409f:20)
    [...]
```

If I pass in *just the MultiPolygon*, it works as expected:

```js
const turfBounds = bbox(multiPolygon1); // works!
```

If I pass in a FeatureCollection with just the 2 points in it, it also works. 
If I pass in a FeatureCollection with just a MultiPolygon, it fails with the error above.

You can [see one of the MultiPolygons in a gist here](https://gist.github.com/foundryspatial-duncan/76ac812623212a53e27b4374bd0313c4). Incidentally these MultiPolygons only really contain one polygon :P

**Comment by foundryspatial-duncan** [comment]
The plot thickens, it also fails with a `FeatureCollection` containing regular `Polygon`s. Am I not doing this right? How do you get the bounding box of multiple features?

**Comment by stebogit** [comment]
@foundryspatial-duncan I believe you are doing right using a `FeatureCollection`.
It looks like though [`bbox` should work](https://github.com/Turfjs/turf/blob/master/packages/turf-bbox/test.js#L27-L49) with all feature types or collection of any features.

Maybe a collection with more than one `MultiPolygon`, not tested at this time, is what breaks it... 🤔 
Would you please try creating a simple test case for that and see if it does fail?

**Comment by foundryspatial-duncan** [comment]
I think the problem may (technically) be on my end. My GeoJSON is coming out of PostIGIS (v2.5) and [multi]polygon features have got a noticeably different structure to those created by Turf. I wonder if PostGIS is using some older version of the GeoJSON spec? The structures of the objects that have the coordinates are different, so it's no surprise Turf is having trouble finding the points.

Is that something you've heard of before?

**Comment by stebogit** [comment]
Good to hear everything is working as  expected
