### ISSUE TITLE
Inconsistent behaviour between modules

### ISSUE THREAD

**Issue by edap** [Turfjs/turf#1796]
Importing and using `@turf/boolean-point-in-polygon` works like this

```js
import booleanPointInPolygon from '@turf/boolean-point-in-polygon';
booleanPointInPolygon(myPoint, myOutline); // works
```

Importing turf/area does not work.

```js
import area from '@turf/area';
area(myPolygon); // error
```

returns `area is not a function`

**Comment by rowanwins** [comment]
I'm not sure too much about your setup but it works for me using v`6.0.1`

````
import area from '@turf/area';
import {polygon} from '@turf/helpers';

var p = polygon([[[125, -15], [113, -22], [154, -27], [144, -15], [125, -15]]]);
console.log(area(p));
````

I know in the past there has been an annoying requirement occasionally to use `.default`, so depending on what version you are using that might be a factor

**Comment by mfedderly** [comment]
I would like to at least consider this for 7.0.0, even if we don't wind up fixing it.

**Comment by mfedderly** [comment]
I think this is already fixed with some of the 6.x stuff we've already done. If it is still broken please reopen @edap. Thanks!
