### ISSUE TITLE
isobands fails on flat data

### ISSUE THREAD

**Issue by Eh2406** [Turfjs/turf#1797]
We are hitting this in a map @superchad and I are developing. When all the points in the grid fall in the same band then `isobands` returns no geometry instead of the bbox of the grid. If one point on the edge has a different band than the hole area is filled in correctly. Instead of a geojson I have a failing test https://github.com/Turfjs/turf/compare/v7...Eh2406:v7

**Comment by stebogit** [comment]
Hey @Eh2406 looking at your test I believe the issue is on the passed data. In fact you are setting the `elevation` value  to `1` for all points in your grid and looking for intersections of the resulting "virtual" 3D surface (in this case flat) with planes parallel to the map (at `0` and `2` elevation in your case), which is none.

If you try this it will work:
```js
const points = turf.pointGrid([-70.823364, -33.553984, -70.473175, -33.302986], 5);
points.features.forEach((point) => point.properties={elevation: Math.random()});
const lines = turf.isobands(points, [0, 0.5, 1]);
```

![Screen Shot 2019-11-30 at 10 50 44 AM](https://user-images.githubusercontent.com/12717225/69904757-4776a480-135f-11ea-9cfc-658e1ad3486b.png)

**Comment by Eh2406** [comment]
Do you have advice for how you would like to see this fixed? Are you open to merging PRs? (I assume to the v7 branch, but if that is not where you want them say so)

I have spent the past week trying to dig in. It looks like the boundary edges are added in the loop in [BandGrid2AreaPaths](https://github.com/Turfjs/turf/blob/3bbeedaeb9abec5bfdf0a27ba70cf9bf19d81d13/src/isobands/lib/marchingsquares-isobands.js#L2100), but that is only triggered when an internal edge hits the boundary. I think we can separate the core of that loop into a function, and then call the function on (0, 0) if it should be in the band. But I am very open to advice.

**Comment by stebogit** [comment]
@Eh2406 I originally used [MarchingSquares.js](https://github.com/RaumZeit/MarchingSquares.js) importing the library via mpn, then on an [unsuccessful attempt](https://github.com/Turfjs/turf/issues/1428) to convert Turf to TypeScript, the library was included as local dependency.
For any issue/question on the library you should try to contact [Ronny Lorenz](https://github.com/RaumZeit), he has been very helpful in the past when I developed the Turf module.
I know he worked on its MS algorithm after I implemented `@turf/isobands`, but I'm not sure we ever included those changes back in. You might want to try if the latest version does fix your issue.

**Comment by Eh2406** [comment]
You are reading our minds! I was just going to comment that it looked like you had copied the code from there and that the npm version does not have this bug. Given that the v7 branch is giving up on TypeScript, do you want a PR moving back to using the npm version?

**Comment by stebogit** [comment]
> Given that the v7 branch is giving up on TypeScript, do you want a PR moving back to using the npm version?

👍
