### ISSUE TITLE
Installing modules from NPM

### ISSUE THREAD

**Issue by flightltd** [Turfjs/turf#1798]
Issuing the following command in Windows 10:

`C:\--\--\turf>npm install @turf/collect @turf/getCoords`

Gets the following response:

```
npm ERR! code E404
npm ERR! 404 Not Found: @turf/getCoords@latest
```

Commands to install most other modules seemd to have reported back ok.

**Comment by rowanwins** [comment]
`getCoords` is part of the `invariant` module. 

````
npm install @turf/invariant
````

On the docs page you should see some notes that specify how to install
https://turfjs.org/docs/#getCoords
