### ISSUE TITLE
Multiple results for turf-nearest

### ISSUE THREAD

**Issue by peterqliu** [Turfjs/turf#180]
For when I want the n nearest points, returned in order of proximity. method could look something like `turf.nearest(point, featurecollection, n)`

**Comment by lyzidiamond** [comment]
Oh, this would be super useful for so many things. In particular, "Where is my nearest taco?" That's my most common question.

**Comment by tmcw** [comment]
see https://github.com/mapbox/leaflet-knn https://github.com/darkskyapp/sphere-knn

**Comment by tmcw** [comment]
Closing; good options here are:

* knn if you're doing the calculation repeatedly
* sortBy with distance if you're doing it once.
