### ISSUE TITLE
turf 7's difference throws "Unable to complete output ring"

### ISSUE THREAD

**Issue by meelkor** [Turfjs/turf#1800]
Running following call:
```javascript
turf.difference(geojson_a, geojson_b)
```

with following data:

https://gist.github.com/meelkor/8d7b3b4f353d769bfe740da1c1511962?short_path=914da70
https://gist.github.com/meelkor/27b42eee6ab53c3d0300929993a03f17?short_path=25612ce

results in `difference` throwing:
```
Error: Unable to complete output ring starting at [-103.9659, 29.7383]. Last matching segment found ends at  [-102.88510638171053, 29.72515559889628].
    at Function.factory (.../node_modules/turf/dist/turf.js:6338:23)
    at doIt (.../node_modules/turf/dist/turf.js:7465:31)
    at difference (.../node_modules/turf/dist/turf.js:7479:14)
    at Object.difference$1 [as difference] (.../node_modules/turf/dist/turf.js:26235:27)
```

Using version **7.0.0-alpha.1** that is published in the original deprecated [turf package](https://www.npmjs.com/package/turf) as opposed to the [@turf/difference](https://www.npmjs.com/package/@turf/difference) package which doesn't have the alpha release and the previous version often produces weird / broken geometries.

I haven't tested it with current master, so it's possible it's fixed already but not published anywhere...

**Comment by rowanwins** [comment]
Turf 7.0.0-alpha.1 is no longer in development. This is now resolved in v6.3.0
