### ISSUE TITLE
Turf area return wrong result for l-shape

### ISSUE THREAD

**Issue by edap** [Turfjs/turf#1803]
I have weird values when making the area calculation of an L-Shape

```
LShape =[
  [
    -96.42846501760152,
    -47.874074822480466
  ],
  [
    37.165121096735334,
    -36.1861505177017
  ],
  [
    36.29356366925875,
    -26.22420353678424
  ],
  [
    -87.33807546416065,
    -37.04057041408643
  ],
  [
    -91.99343795333672,
    16.17046632550918
  ],
  [
    -101.95538493425417,
    15.2989088980326
  ],
  [
    -96.42846501760152,
    -47.874074822480466
  ]
]

 const poly = turf.polygon([LShape]);
const area = turf.area(poly);

console.log(area); //  19344160251160.047
```

The result of the area is incorrect.

In blu, the shape of the polygon.

<img width="539" alt="Screen Shot 2019-12-10 at 11 41 21" src="https://user-images.githubusercontent.com/161152/70522770-1017ad00-1b42-11ea-8c78-f623488c8135.png">

**Comment by stebogit** [comment]
@edap how did you validate the result, i.e. how do you know it's wrong?
What would be the correct result and how did you calculate that?

**Comment by edap** [comment]
Hello @stebogit, well, my test is quite easy. The l-shape is inside a rectangle. If, for example, the width of the rectangle is 40 and the height it is 30, turf.area returns correctly 1200. But if I design an l-Shape inside that rectangle of 40x30, the returning area is bigger than the rectangle's area, (it is actually returning 6644328442107.6 squares meter).

**Comment by edap** [comment]
Is there something else that I can do to help you debugging this issue?

**Comment by smallsaucepan** [comment]
Hi @edap. Probably far too late an answer for you on this. However, I'm not sure the logic of your check is valid:

> If, for example, the width of the rectangle is 40 and the height it is 30, turf.area returns correctly 1200 ... if I design an l-Shape inside that rectangle of 40x30

The coordinates you provided are not contained within a box of 1200m2 though. A rectangle around those points (roughly drawn below) would be closer to 130026988369977m2.

![Screenshot 2024-09-21 at 10 05 40 PM](https://github.com/user-attachments/assets/9ffd9cc4-0f44-4edd-9812-b9d0115ab62c)

Perhaps there was some scaling issue in the design program you were using?

Closing this issue. If I've misunderstood though, please reopen and provide some further information.
