### ISSUE TITLE
lineToPolygon(line) mutates the underlying LineString

### ISSUE THREAD

**Issue by franklinharvey** [Turfjs/turf#1812]
[Here's a JSFiddle](https://jsfiddle.net/hesfyndk/) and [a sample geojson](http://geojson.io/#map=8/49.440/11.448).

Basically, if I have a LineString of length `k`, calling `lineToPolygon(line)` (which returns a "new" polygon) also mutates `line` to have `k + 1` points. Of course, you can set the property `autoComplete`, but I would never expect `lineToPolygon(line)` to both return a `Polygon` and also mutate the input. In this case, I *want* the resulting Polygon to autoComplete, but I don't want to change the input string in place

My current workaround is `lineToPolygon(clone(line))`

```
var linestring1 = turf.lineString([[10, 50], [10.3, 50.3], [11.1, 49.5]]);
var line1Len = turf.getCoords(linestring1).length

var poly1 = turf.transformTranslate(turf.lineToPolygon(linestring1), 20, 35); 
var poly1Len = turf.getCoords(linestring1).length

console.log(line1Len, poly1Len, turf.getCoords(linestring1).length); // 3, 4, 4
console.log(line1Len === turf.getCoords(linestring1).length); // false
```

Please provide the following when reporting an issue:

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by rowanwins** [comment]
Yeah mutating inputs isn't great @franklinharvey - we often try to have a test to make sure that doesn't happen. Sounds like we should add an option called `mutate` which defaults to false perhaps, it would pretty much do that same clone operation as your workaround.
