### ISSUE TITLE
@turf/clamp?

### ISSUE THREAD

**Issue by mayteio** [Turfjs/turf#1814]
I can't seem to find `clamp point inside bounds` functionality in turf - is this outside the scope? 

The use-case I have is preventing a map from being scrollable outside certain bounds. I currently have a function I copy + paste myself when needed. Would you guys accept a PR? I would like to start contributing to OSS projects so it'd be my honour.

A more advanced version could clamp inside any given polygon - potentially using `line` & `intersect`. Would need to look into it further.

**Comment by rowanwins** [comment]
Hi @mayteio 

Thanks for the suggestion. The closest thing we have at the moment is [`nearestPointOnLine`](https://turfjs.org/docs/#nearestPointOnLine) which you might be able to adapt perhaps to also suit polygons? 

Sometimes this sort of operation might also be referred to as 'snapping' although it perhaps infers a tolerance.

At the moment we have a lot of outstanding PR's so if you wanted to start looking at code you could perhaps write it as a standalone module and then when things get a bit more under control with Turf we can write a wrapper around your module.

Cheers
Rowan

**Comment by smallsaucepan** [comment]
It sounds like this might be functionality best handled by the map presentation / interaction layer? Closing this issue, though please reopen if it is definitely something required at Turf's level.
