### ISSUE TITLE
turf.polygon -- Error: Each LinearRing of a Polygon must have 4 or more Positions

### ISSUE THREAD

**Issue by franklinharvey** [Turfjs/turf#1819]
[GeoJSON Gist](https://gist.github.com/franklinharvey/557858ad4603d7c7fc716675ebf9d950) and [JSFiddle](https://jsfiddle.net/Lwjs2cg6/)

When using `turf.polygon()` I get an error even if I have 4 points. I'm using `turf.polygon()` instead of `turf.lineToPolygon()` because of a previous issue ( #1812 ) which caused mutation of the underlying linestring. I have also seen `lineToPolygon` fail with the same error, but I can't seem to replicate it in JSFiddle.

```
var line = lineString([[-105.126128671085,40.14645772714157],[-105.1259925489775,40.14645798342624],[-105.1259902020446,40.1465394819091],[-105.12612833580887,40.14653845677154]])

var poly = turf.polygon(turf.getCoords(line) // error
var poly2 = turf.lineToPolygon(line) // works, sometimes
```

Please provide the following when reporting an issue:

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by smallsaucepan** [comment]
Probably far too late to be of help @franklinharvey, however will describe below what was happening in case someone else has the same issue.

There were two things tripping you up.

The first is that the start and end coordinates aren't the same. Any polygon in geojson has to be closed. So if you were to work with this data instead:

```
var line = turf.lineString([
  [-105.126128671085,40.14645772714157], 
  [-105.1259925489775,40.14645798342624], 
  [-105.1259902020446,40.1465394819091],
  [-105.12612833580887,40.14653845677154],
  [-105.126128671085,40.14645772714157] // <-- duplicate of start point
])
```

The second is that for a line input turf.getCoords returns a Position[]. However turf.polygon expects a Position[][]. If you were to change this line to:

```
// Note the result of getCoords is wrapped in an extra array.
var poly = turf.polygon([turf.getCoords(line)])
```

You'd end up with:

```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-105.126128671085, 40.14645772714157],
            [-105.1259925489775, 40.14645798342624],
            [-105.1259902020446, 40.1465394819091],
            [-105.12612833580887,40.14653845677154],
            [-105.126128671085, 40.14645772714157]
          ]
        ]
      }
    }
  ]
}
```

Hope this is of some help to someone.
