### ISSUE TITLE
[@turf/helpers] Polygon: First and last position check is not according to the spec

### ISSUE THREAD

**Issue by daniel-hauser** [Turfjs/turf#1820]
According to [section 3.1.6](https://tools.ietf.org/html/rfc7946#section-3.1.6):
>  The first and last positions are equivalent, and they MUST contain identical values; their representation SHOULD also be identical.

In the example below, both are invalid, but we throw an error only for the second one

```javascript
const { polygon } = require('@turf/helpers');
console.log('valid', polygon([[
    [ 1,2,3],
    [ 4,5 ],
    [ 6,7 ],
    [ 1,2 ]
]]).geometry)

console.log('invalid', polygon([[
    [ 1,2 ],
    [ 4,5 ],
    [ 6,7 ],
    [ 1,2,3 ]
]]).geometry)
```

- [X] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by rowanwins** [comment]
Hi @daniel-hauser 

Thanks for the bug report. We've not done much at all with the optimising Turf for use with z coords.

**Comment by daniel-hauser** [comment]
@rowanwins 
See #1822 - the fix is very small.
