### ISSUE TITLE
Error building buffer with Rollup ('GeoJSONReader' is not exported by node_modules/turf-jsts/jsts.min.js)

### ISSUE THREAD

**Issue by Crisfole** [Turfjs/turf#1823]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Here's a demo of the bug. Instructions for reproducing in README.md

https://github.com/Crisfole/turf-buffer-bug

I'm experiencing this with node v12.10.0

**Comment by endafarrell** [comment]
I too have the same issue.

```
[!] Error: 'GeoJSONReader' is not exported by node_modules/turf-jsts/jsts.min.js, imported by node_modules/@turf/buffer/dist/es/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@turf/buffer/dist/es/index.js (2:19)
```

My dependencies are "latest" as of 2021-05-10:

    "@turf/buffer": "^6.3.0",

    "rollup": "^2.47.0",
    "rollup-plugin-commonjs": "^10.1.0"

**Comment by endafarrell** [comment]
Ah - `    "@rollup/plugin-commonjs": "^19.0.0",` rather than the no-longer-supported `"rollup-plugin-commonjs"` resolves this for me.

**Comment by mfedderly** [comment]
Thanks!
