### ISSUE TITLE
Big size of js file not loading 

### ISSUE THREAD

**Issue by HtunLinAung** [Turfjs/turf#1825]
I use a big size javascript plugin (355KB ) on webpage and converting to pdf but the js file can't be loaded.
I also use jQuery plugin and it is working.

wkhtmltopdf.exe --no-stop-slow-scripts --enable-javascript --javascript-delay 28000 --debug-javascript report\Report_R001998H_SEFU21.html report\LandedPropertyReport_101.pdf

If you any suggestion, pls share me.

Thanks.

**Comment by rowanwins** [comment]
This sounds like it doesn't have anything to do with TurfJS

**Comment by HtunLinAung** [comment]
Yes. But the size of TurfJS is too big and can't load when converting to PDF.

**Comment by rowanwins** [comment]
Are you using all of turf or can you install single modules?

**Comment by HtunLinAung** [comment]
I use only Helper, Area and Difference modules but the size of Difference is over 345KB.
That's why can't be loaded.

**Comment by rowanwins** [comment]
Which series of modules are you using, v5 or v6 ? I expect v5 is very large but v6 should be smaller.

**Comment by HtunLinAung** [comment]
I'm currently using Turf 5.1.6.
