### ISSUE TITLE
Webpack error when using NPM package @turf/boolean-equal

### ISSUE THREAD

**Issue by javier-lopez-1s** [Turfjs/turf#1827]
I have an **Angular 8** application including some Turfjs NPM packages and everything had worked beautifully so far. However, after adding the NPM package **@turf/boolean-equal**, I started getting the following error:

> ERROR in ./node_modules/@turf/clean-coords/index.ts
> Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
> Error: C:\Projects\PRAI\Code\prai_dmaps\DMapS\ClientSide\dmaps-client\node_modules\@turf\clean-coords\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (C:\Projects\PRAI\Code\prai_dmaps\DMapS\ClientSide\dmaps-client\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:913:23)
>     at plugin.done.then (C:\Projects\PRAI\Code\prai_dmaps\DMapS\ClientSide\dmaps-client\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> 

_@turf/clean-coords_ is a dependency of _@turf/boolean-equal_. I checked and confirmed that the file _./node_modules/@turf/clean-coords/index.ts_ exists, so I guess this file is not being properly referenced.

As suggested in the error, I tried adding _@turf/clean-coords/index.ts_ to the "files" property of my _tsconfig.json_, and the error disappeared but I got two new identical errors, this time for the files _./src/main.ts_ and _./src/polyfills.ts_. These files are fundamental in any Angular application and never had this problem before, so I guess something is still not right. If I add all 3 files to the tsconfig.json then all the errors disappear, but importing these files (main.ts and polyfills.ts) is not something that one should have to do in order to use @turf/boolean-equal.
```
  "files": [
    "node_modules/@turf/clean-coords/index.ts",
    "src/main.ts",
    "src/polyfills.ts"
  ]
```
Just in case it helps, I noticed that _@turf/boolean-equal_ **is missing the file index.d.ts**.

**Comment by Andi-Lo** [comment]
Can confirm this. Having the same problem in my angular app (v8.3)
