### ISSUE TITLE
Create line from point using distance and direction

### ISSUE THREAD

**Issue by johnbester** [Turfjs/turf#1832]
There is one simple feature which does not seem to be implemented (at least not in the documentation). Currently the only function turf supplies that allows you to get an endpoint (or line) by using a starting point, distance and direction is to use turf.lineArc as follows:
    let arc = turf.lineArc(start, distance/1000.0, direction, direction+5)
    led endPoint = arc.geometry.coordinates[0]
If you use the same direction, a complete circle is created and if the difference in direction is too small, I got an error. Please give us a function that simply creates a line (or just give back the endpoint). (e.g. turf.lineFrom(start, distance, direction, options))
If I missed something, please point me in the right direction.

**Comment by stebogit** [comment]
@johnbester you can use [`@turf/destination`](http://turfjs.org/docs/#destination) to get a point at a certain (Euclidean) distance and direction from an origin or [`@turf/rhumb-destination`](http://turfjs.org/docs/#rhumbDestination) if you want to follow a [Rhumb line](https://en.wikipedia.org/wiki/Rhumb_line).
[`@turf/great-circle`](http://turfjs.org/docs/#greatCircle), gives you instead the shortest path (a line) between two points.
