### ISSUE TITLE
booleanPointInPolygon() / inside() wont work while coord values are decimal

### ISSUE THREAD

**Issue by klimtron** [Turfjs/turf#1840]
Hello, I've got a problem while I'm trying to check if clicked point is laying on two or more layer polygons. Do I really need to convert this values to integer?

```
        var pt2 = turf.point([22.65380859375, 49.710272582105695]);
        var multiPoly = turf.multiPolygon([[[
            [22.828611111111112, 49.68472222222222],
            [23.065833333333334, 49.9],
            [23.20861111111111, 49.843333333333334],
            [22.98611111111111, 49.650555555555556],
            [22.828611111111112, 49.68472222222222],
            [22.828611111111112, 49.68472222222222],
            [22.828611111111112, 49.68472222222222]
        ]]]);
        console.log("test-turf",turf.booleanPointInPolygon(pt2, multiPoly));
```
It returns false

**Comment by stebogit** [comment]
@klimtron I'm not sure I get what's wrong with your example; it looks like your `pt2` is actually outside `multiPoly`. What would you expect instead?

<img width="639" alt="Screen Shot 2020-03-02 at 8 36 18 AM" src="https://user-images.githubusercontent.com/12717225/75696733-e82b7780-5c60-11ea-87b0-36ed164fe419.png">

**Comment by klimtron** [comment]
@stebogit  Thank you for paying attention. I forgot to check this obvious detail, Everything is works how it should.
