### ISSUE TITLE
Issue with number of steps in options vs the length of the coordinates array that is produced

### ISSUE THREAD

**Issue by cdwhitt** [Turfjs/turf#1848]
Here is the gist file:[trackcircle.geojson](https://gist.githubusercontent.com/cdwhitt/895cf667936493ecf53e7b0698f64ef9/raw/02cc948c875d30c434e12ab34a202ee12e8a859f/trackcircle.geojson)

```
const maskLatLng = property => {
  if (property.latitude && property.longitude) {
    const randomIndex = Math.round(Math.random() * 100) //originally was at 101, but that would break my app
    const ownerLocation = [property.longitude, property.latitude]
    const trackCircleRadius = Math.round(Math.random() * 3) + 1

    //Passing 100 steps returns an array with a length of 101,
    //BUT we only want a randomIndex up to 100 because 101 will always be undefined for some reason
    const options = {
      steps: 100,
      units: 'miles'
    }

    const trackCircle = circle.default(
      ownerLocation,
      trackCircleRadius,
      options
    )

    const newCenter = trackCircle.geometry.coordinates[0][randomIndex]
    property.longitude = newCenter[0]
    property.latitude = newCenter[1]
  }

  return property
}
```

Using the function above, I've created a circle layer on a map that is slightly obfuscated so as not to give away a homeowner's location. The ```trackCircle``` is based around the actual location of a homeowner, and my circle layer 'travels' the ```trackCircle``` to obfuscate the homeowner's actual location on a map (may not be the best way, but I was trying to be creative). Essentially, each time a refresh happens on a page where I'm rendering a map with this circle layer, the circle appears in a slightly different location so that nobody can ever figure out where a homeowner is actually located. 

The ```randomIndex``` is based on the ```trackCircle```, which allows me to generate a new center point for the circle layer each time the page renders. The issue that I've found is that passing 100 steps to the ```options``` object produces an array with a length of 101, not 100. This is misleading for my ```randomIndex``` because if ```Math.random()``` ever returns 101, my app would break because the 101st index of the coordinates array is undefined for whatever reason. I have fixed the issue, but I wanted to bring this to the attention of anyone who attempts something similar. I think having ```circle.default``` return a coordinates array with a length of 100 makes a lot more sense and would alleviate any confusion. I would expect passing 100 to ```steps``` would produce an array of coordinates with the same length, and initially, I had my app set up to handle that number. Just something to consider!

**Comment by rowanwins** [comment]
The first and last coordinates are duplicated in the geojson spec so there are 100 unique values, and 101 values in the array. Perhaps a little confusing but does that make sense @cdwhitt ?

**Comment by cdwhitt** [comment]
> The first and last coordinates are duplicated in the geojson spec so there are 100 unique values, and 101 values in the array. Perhaps a little confusing but does that make sense @cdwhitt ?

It's been a long time since I looked at this... Sorry! What is the reasoning behind duplicating those values?

**Comment by stebogit** [comment]
@cdwhitt see the [GeoJSON specs](https://tools.ietf.org/html/rfc7946#section-3.1.6)
