### ISSUE TITLE
turf-displace

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#185]
moves features - would be useful for docs and things in general.

**Comment by klokoy** [comment]
I have a repo turf-translate that translate all kind of features using a given translate function. I would love to transfer the repo to turf.

Take a look at https://www.npmjs.com/package/turf-translate

**Comment by klokoy** [comment]
Currently turf-translate does not take into account for global curvature. Would it be more interesting if turf-translate works like turf-distance?

**Comment by tmcw** [comment]
👍 turf-translate is great for this.
