### ISSUE TITLE
Can not draw perpendicular lines using destination and bearing

### ISSUE THREAD

**Issue by malik-aliyev-94** [Turfjs/turf#1852]
I am trying to draw perpendicular lines and I am using destination and rhumbDestination methods.

```javascript
    let home = turf.point([43.12831626497193, 1.259286403656006]);
    L.circle(home.geometry.coordinates, {
        color: 'purple',
        fillColor: 'purple',
        fillOpacity: 0.5,
        radius: 20
    }).addTo(map);

    let destination;

    destination = turf.rhumbDestination(home.geometry.coordinates, 400, 45, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'green', weight: 5}).addTo(map);
    destination = turf.rhumbDestination(home.geometry.coordinates, 400, -135, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'green', weight: 5}).addTo(map);


    destination = turf.rhumbDestination(home.geometry.coordinates, 400, 135, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'red', weight: 5}).addTo(map);
    destination = turf.rhumbDestination(home.geometry.coordinates, 400, -45, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'red', weight: 5}).addTo(map);
```

But resulting lines are not perpendicular 

<img width="593" alt="Screen Shot 2020-03-14 at 22 32 50" src="https://user-images.githubusercontent.com/10786526/76688247-901f4880-6644-11ea-9ff4-6e04e598b63f.png">

I am using leaflet for visualization. 
I have also tested with destination method, the same result. 

While bearing is multiple of 90 the result is right.
```javascript
   destination = turf.rhumbDestination(home.geometry.coordinates, 400, 0, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'green', weight: 5}).addTo(map);
    destination = turf.rhumbDestination(home.geometry.coordinates, 400, -180, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'green', weight: 5}).addTo(map);


    destination = turf.rhumbDestination(home.geometry.coordinates, 400, 90, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'red', weight: 5}).addTo(map);
    destination = turf.rhumbDestination(home.geometry.coordinates, 400, -90, {units: 'meters'});
    L.polyline([destination.geometry.coordinates, home.geometry.coordinates]).setStyle({color: 'red', weight: 5}).addTo(map);
``` 

<img width="419" alt="Screen Shot 2020-03-14 at 22 43 49" src="https://user-images.githubusercontent.com/10786526/76688352-5d298480-6645-11ea-89b4-e11164d6a357.png">

**Comment by stebogit** [comment]
@malik-aliyev-94 as stated [here](https://github.com/Turfjs/turf#data-in-turf), it is a matter of coordinates order: Leaflet (like Google Maps) uses the [latitude, longitude] schema, while Turf follows the GeoJSON definition of  [longitude, latitude], i.e. the equivalent of [x, y] on a geometrical plane.

Here is the [working example](url);
![Screen Shot 2020-03-14 at 5 11 17 PM](https://user-images.githubusercontent.com/12717225/76692668-d52c8600-6616-11ea-8907-662e1872948d.png)

**Comment by malik-aliyev-94** [comment]
> @malik-aliyev-94 as stated [here](https://github.com/Turfjs/turf#data-in-turf), it is a matter of coordinates order: Leaflet (like Google Maps) uses the [latitude, longitude] schema, while Turf follows the GeoJSON definition of [longitude, latitude], i.e. the equivalent of [x, y] on a geometrical plane.
> 
> Here is the [working example](url);
> ![Screen Shot 2020-03-14 at 5 11 17 PM](https://user-images.githubusercontent.com/12717225/76692668-d52c8600-6616-11ea-8907-662e1872948d.png)

Thank you for answer, but working example is not available

**Comment by stebogit** [comment]
sorry @malik-aliyev-94 I fixed the link ☝️, thanks for the heads-up

**Comment by malik-aliyev-94** [comment]
Great thanks !
