### ISSUE TITLE
turf.length is not a function

### ISSUE THREAD

**Issue by SakamotoLfe** [Turfjs/turf#1858]
I need to center my map based on a route loaded by map.addGeoJson(), that returns a FeatureCollector. The first thing is good but, when I need to use the "turf.length" he just says that this isn't a function! Am I doing something wrong?
`let length = turf.length(turf.lineString(r.geom.coordinates), {units: 'kilometers'});`
PS: I'm using AngularJS with Bower and NPM. I imported "along" and "length".
PS2: I'm just posting this as an issue because I didn't found anything about this error on the internet and I need some support. If this is inappropriate, please tell me!

The log that show the error. ("rotas" is routes on english).
![Annotation 2020-03-16 175714](https://user-images.githubusercontent.com/42591907/76799068-9a118a80-67af-11ea-9bdf-4bcc348a85a7.png)

There's a image that show that @turf is imported.
![Untitled](https://user-images.githubusercontent.com/42591907/76798952-5f0f5700-67af-11ea-89f9-05e3822fdd8b.png)

**Comment by rowanwins** [comment]
I suspect you need to do something like
````
const length = require('@turf/length')
````
Check out the [getting started page](https://turfjs.org/getting-started) and in particular the "Using in Node or with a build tool" heading.

**Comment by SakamotoLfe** [comment]
I'm using AngularJS and, on this project, we can't import things like this (I don't remember why, I'll ask to my co-worker tomorrow). There's another way?

**Comment by rowanwins** [comment]
Another option might be
```` 
import length from '@turf/length'
````

**Comment by SakamotoLfe** [comment]
I talked with my co-worker and this is impossible with the actual project, we use bower and, to install a NPM dependency, it`s a impossible work! And I didn`t found this API on Bower dependencies. He says that to make NPM dependencies work we need to copy the .js of the dependency and put it as a internal file of the project. I'll try copying the file that I need to see what happens

**Comment by rowanwins** [comment]
In that case you should be able to download the file from 
https://npmcdn.com/@turf/turf/turf.min.js

Good luck :)

**Comment by SakamotoLfe** [comment]
Thanks!!
