### ISSUE TITLE
Version with turf.angle in @turf/turf has not been published

### ISSUE THREAD

**Issue by joltmode** [Turfjs/turf#1861]
I wanted to use the `turf.angle` function, but apparently in the latest version of `@turf/turf` published on NPM, it isn't there.

Judging by GitHub releases, the latest was released on 10 Dec 2017, but `turf.angle` was implemented on 19 Dec 2017. 

I wonder, what else hasn't been published?

**Comment by rowanwins** [comment]
Hi @joltmode 

It's available as a standalone package
https://www.npmjs.com/package/@turf/angle
but not part of the core package which remains stuck on v5.x

We're in the process of working towards a new release so stay tuned

**Comment by joltmode** [comment]
Yeah, am already using it as a standalone.

Thought it was a blunder that it's not in main package.

Good to know that a release is WIP!
