### ISSUE TITLE
Question: Vertices within viewport?

### ISSUE THREAD

**Issue by jfuehner** [Turfjs/turf#1867]
Hi all! Does turf provide a way to find vertices given a users viewport/bbox?

Essentially, I just want to filter/render what the user has within their viewport as they move around a mapping interface.

My positional data(lat/lon/alt) is large and stored within TypedArrays so I would most likely do the filtering within a web worker for better performance...

Thanks!

**Comment by rowanwins** [comment]
Hi @jfuehner 

There is nothing built in but you could probably use a combination of `booleanPointInPolygon` and `coordEach`. The `booleanPointInPolygon` perhaps isn't the most optimised method given it's designed for polygons, so another option might be to use the `insideBBox` method in the [cheap-ruler](https://github.com/mapbox/cheap-ruler) library.

Hope that helps.
Rowan

**Comment by jfuehner** [comment]
Thanks for the direction; I’ve actually never heard of the cheap-ruler library so I’ll check it out...

Curious how these options will perform with 100-200k vertices...

**Comment by mfedderly** [comment]
@jfuehner you might also look into using @turf/bbox-clip, which would be faster than booleanPointInPolygon.
