### ISSUE TITLE
turf-collect returning empty arrays (sometimes)

### ISSUE THREAD

**Issue by markusand** [Turfjs/turf#1880]
Collect is returning empty arrays when using it with hexgrid FeatureCollection.
```js
import border from './assets/border.geojson';
import people from './assets/people_positions.geojson';

const bbox = [1.327285, 42.680921, 1.893768, 42.40115];
const hexgrid = turf.hexGrid(bbox, 1, { units: 'kilometers', mask: border });

const collected = turf.collect(hexgrid, people, 'birthday', 'bday');
```

All `bday` properties inside collected are empty.

If using another featureCollection, for exemple creating a new one from border polygon I'm using for mask, bday property is filled expected.
```js
const borderFC = turf.featureCollection([border]);
const collected = turf.collect(borderFC, people, 'birthday', 'bday');
```
Using `squareGrid` instead of hexGrid also gives expected results.

**Comment by rowanwins** [comment]
Thanks for the report @markusand . Are you able to share your geojson files?

**Comment by markusand** [comment]
I've been testing with mock geojson created in [geojson.io](http://www.geojson.io) like
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": { "views": 23, "likes": 15 },
      "geometry": { "type": "Point",  "coordinates": [1.522293,  42.535627]  }
    },
    {
      "type": "Feature",
      "properties": {  "views": 10, "likes": 2 },
      "geometry": {  "type": "Point",  "coordinates": [1.586837, 42.549539]  }
    },
    (...)
  ]
}
```

A simplified version that autogenerates the mask is the following :
```js
const bounds = bbox(json);
const mask = concave(json);
const grid = hexGrid(bounds, 1, { mask });
const collected = collect(grid, json, 'views', 'aggr_views');
```
I need to polish it a little bit, as concave hull vertices are not included into the mask, but you get the point.

This setup is working with squareGrid and triangleGrid, but fails with hexGrid.

**Comment by ssontag55** [comment]
I agree with @markusand, working with square, not with hexGrid.

**Comment by markusand** [comment]
I updated to 6.3.0 and the issue seems to have been fixed.
