### ISSUE TITLE
Question about additional functionality related to lineToPolygon function

### ISSUE THREAD

**Issue by alexeyvax** [Turfjs/turf#1881]
Hi guys,
Thank you for this awesome library!

I would like to ask you one question regarding converting line to polygon. I'm using `lineToPolygon` function and it works like a charm. But I need more functionality.

For example, I have one complex line, something like this, which was converted to polygon via `lineToPolygon` function:

![photo_2020-04-05_11-01-21](https://user-images.githubusercontent.com/22244018/78469797-f0c61080-772c-11ea-8d51-749e5523a48c.jpg)

There is a lot of lines and shapes within polygon, which are part of this polygon. And I need to reduce it to avoid drawing unnecessary lines and make a correct searching inside it.

**So the question is:**
Does Turf have functionality to detect crossed lines within polygon, remove these lines and make polygon like on the next screenshot?

![photo_2020-04-05_11-01-28](https://user-images.githubusercontent.com/22244018/78469807-fb80a580-772c-11ea-9c16-96292633916f.jpg)

Thanks

**Comment by rowanwins** [comment]
Hi @alexeyvax 

Turf doesn't support anything like that currently and we'd probably need a new module to do so.
The algorithm would need to identify intersection points and then how to reconstruct a contour made of the outer segments.

Cheers

**Comment by stebogit** [comment]
@alexeyvax if I understand correctly what you want to do, I think you could do something like [this](http://jsfiddle.net/jStefano/u76teyod/), where I destructured the line into points and generated a concave polygon out of them:

```js
function toPoints (features) {
  const points = [];
  turf.coordEach(features, function (currentCoord) {
    points.push(turf.point(turf.getCoords(currentCoord)));
  }, {excludeWrapCoord: true});
  return turf.featureCollection(points);
}

const hull = turf.concave(toPoints(data));
```

<img width="563" alt="Screen Shot 2020-04-05 at 9 49 05 AM" src="https://user-images.githubusercontent.com/12717225/78504573-fd456b80-7722-11ea-85ed-793cf5813f5c.png">

<img width="561" alt="Screen Shot 2020-04-05 at 9 48 45 AM" src="https://user-images.githubusercontent.com/12717225/78504574-fe769880-7722-11ea-8361-fd088580b952.png">

**Comment by rowanwins** [comment]
Brilliant solution @stebogit , so elegant!

**Comment by alexeyvax** [comment]
Many tanks guys @rowanwins and @stebogit for your replies.

Yep, that's definitely what I'm looking for!
Many thanks for you solution @stebogit, it works like a charm.

And can I ask you one more question?

Your function `toPoints` works great but call each time when polygon was drawn. 
For example, if user drawn valid polygon(without crossed lines inside polygon), like this one:

![photo_2020-04-11_08-51-57](https://user-images.githubusercontent.com/22244018/79036547-c6af9b00-7bd1-11ea-9d5e-1761f1f24d0c.jpg)

it becomes to:

![photo_2020-04-11_08-52-00](https://user-images.githubusercontent.com/22244018/79036548-c911f500-7bd1-11ea-854b-c0e7315bdc7e.jpg)

Is there some function which can check that the polygon has crossed lines inside? If yes - should call `toPoints`, if no - should not cal it.

I have some guesses about it:
  - First one, separate exist polygon to multiple polygons via `multiPolygon` or `polygonize`. if these functions will return few polygons, it's obvious that polygon have crossed lines inside.
  - Second one, use `booleanContains`, to check that polygon contain something.

But I'm not sure that all are work fine here.

Maybe you have solution for this? Please share with me.

Thanks in advance.

**Comment by stebogit** [comment]
I can't think of anything generic enough to apply to any possible case.
However I'd suggest you to play a bit with the [`maxEdge`](https://github.com/Turfjs/turf/tree/master/packages/turf-concave#concave) option of `@turf/concave` to see if you can find a good value to allow the algorithm to automatically define the U shape polygon in your example.

Alternatively you can try [`concaveman`](https://github.com/mapbox/concaveman) (which I thought was what is running under the hood of the turf module, but [it isn't](https://github.com/Turfjs/turf/pull/907)).

**Comment by rowanwins** [comment]
You could use [shamos-hoey](https://github.com/rowanwins/shamos-hoey) to check for self-intersections first before applying the concave function

**Comment by alexeyvax** [comment]
Thank you guys @stebogit and @rowanwins . shamos-hoey is what I'm looking for!
You are both stars! :)

Cheers!
