### ISSUE TITLE
@turf/difference adds center point calculating difference between two sectors

### ISSUE THREAD

**Issue by carlostxm** [Turfjs/turf#1889]
Hi,

I am calculating the difference between two sector polygons but the resulting polygon has an unneeded point which correspond with the center of the sector.

![image](https://user-images.githubusercontent.com/11058795/80727748-60e66d00-8b06-11ea-8e7f-178632ee353f.png)

You can see the issue on this codepen.

https://codepen.io/carlostxm/pen/LYpjapX

Thanks!

**Comment by rowanwins** [comment]
Thanks for reporting @carlostxm

**Comment by rowanwins** [comment]
There will hopefully be some positive changes to difference as a result of #1916 so stay tuned

**Comment by mfedderly** [comment]
#1916 has been merged and released, if this is still broken please reopen the ticket.
