### ISSUE TITLE
is there a package or support of turf in flutter? 

### ISSUE THREAD

**Issue by abdelmoughit555** [Turfjs/turf#1892]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by rowanwins** [comment]
Can you provide more details - what is flutter?

**Comment by mrkking** [comment]
https://flutter.dev/
Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.

https://dart.dev/
Dart is a client-optimized language for fast apps on any platform
