### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#190]
We handle errors multiple ways in Turf:

* returning `null`
* returning an `Error` object https://github.com/Turfjs/turf-flip/blob/master/index.js#L65 https://github.com/Turfjs/turf-polygon/blob/master/index.js#L23
* throwing an `Error`

I vote for throwing errors on the basis of:

* It fails faster
* It gives useful line numbers for where the error happened and which function it happened in, unlike returning errors, which defer the failure to the next function

/cc @morganherlocker @lyzidiamond

**Comment by morganherlocker** [comment]
:+1: this seems like the way to go

**Comment by tmcw** [comment]
:+1: I'm going to tag functions that can throw with [@throws](http://usejsdoc.org/tags-throws.html)

**Comment by tmcw** [comment]
:+1: Switched all return error instances to throw.

ag is useful for spotting tasks like this - assuming you've used `turf-runner` to clone all modules, run

```
$ ag Error
```

Within the `turf_modules` dir to find all instances.

**Comment by lyzidiamond** [comment]
Did you update all the tests, or do those need updates too?

**Comment by tmcw** [comment]
Updated all tests as well.
