### ISSUE TITLE
turf Content Security Policy error

### ISSUE THREAD

**Issue by coros-sanborn** [Turfjs/turf#1903]
I'm getting the following error when loading turf from the CDN:
"https://cdn.jsdelivr.net/npm/@turf/turf@5/turf.min.js"

```
turf.min.js:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https:".

    at new Function (<anonymous>)
    at o (turf.min.js:1)
    at turf.min.js:1
    at mt (turf.min.js:1)
    at turf.min.js:1
    at turf.min.js:1
    at turf.min.js:1
```

Is there a way to get around this issue without having to add 'unsafe-eval' to the Content Security Policy. Everything I've read indicates adding "unsafe-eval" exposed the application to security risks.

**Comment by toolchild** [comment]
Hi,
Your problem is very likely related to this one: https://github.com/Turfjs/turf/issues/261

**Comment by rowanwins** [comment]
If it's related to robust-orientation then we might be able to swap it out for the [robust-predicates](https://github.com/mourner/robust-predicates) library.

**Comment by donmccurdy** [comment]
@coros-sanborn if you're still seeing this issue, could you share the result of `npm ls concaveman`?

**Comment by rowanwins** [comment]
I believe this is now resolved.

**Comment by el-Rey-magico** [comment]
me too

**Comment by el-Rey-magico** [comment]
I encounter the same problem as @badams.
