### ISSUE TITLE
1 instead of i 

### ISSUE THREAD

**Issue by saadan** [Turfjs/turf#1904]
https://github.com/Turfjs/turf/blob/3fa082cbe073a536bf01022e85fbf8b5e496ffdf/packages/turf-boolean-within/index.ts#L123

I dont think it sould be multiPoint.coordinates[1]  but multiPoint.coordinates[i] I changed it in my project and now it works.

its multiple places like its was copied

**Comment by saadan** [comment]
When i run boolean-within with following multipoint with only one item in multipoint 
![image](https://user-images.githubusercontent.com/1712539/81824454-c8081680-9535-11ea-98b3-b739048bd902.png)


so it try to run on multiPoint.coordinates[1] and there is no point at 1 so it will fail.

**Comment by rowanwins** [comment]
This is now resolved, not quite sure when though...
