### ISSUE TITLE
`Position` type has correct definition commented out

### ISSUE THREAD

**Issue by thw0rted** [Turfjs/turf#1906]
The [definition of the Position type](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/lib/geojson.ts#L68) in the `helpers` package reads

````ts
export type Position = number[]; // [number, number] | [number, number, number];
````

The commented-out tuples are correct, since an array of anything but 2 or 3 numbers (4 if you're working with a version that supports M-values) is an error.  It matters because passing a Position as an argument to a correctly-typed function breaks the build:

````ts
function foo(p: [number, number, number?]) { ... }
const pos: Position = [1,2];
foo(p); // "Type 'number[]' is missing the following properties from type '[number, number, (number | undefined)?]': 0, 1"
````

Since optional tuple members have been supported for some time now, I would suggest going with `[number, number, number?]` as above.

**Comment by mfedderly** [comment]
Closing in favor of https://github.com/Turfjs/turf/issues/1658
