### ISSUE TITLE
Boolean Modules Typescript Declaration File Missing

### ISSUE THREAD

**Issue by wajeehmisbahkhan** [Turfjs/turf#1911]
I have seen PR #1849 and the 'missing type declarations' issue continues to persist for some boolean functions when importing in Typescript.

It is found in:
@turf/boolean-crosses
@turf/boolean-equal
@turf/boolean-overlap
@turf/boolean-parallel
@turf/boolean-within

These packages don't seem to contain any index.d.ts files like the other modules. Reproduced here using StackBlitz TypeScript starter project:
https://stackblitz.com/edit/typescript-8evw9u?embed=1&file=index.ts

Better error description:
Could not find a declaration file for module '@turf/boolean-within'. './node_modules/@turf/boolean-within/index.js' implicitly has an 'any' type.
  Try `npm install @types/turf__boolean-within` if it exists or add a new declaration (.d.ts) file containing `declare module '@turf/boolean-within';`

**Comment by rowanwins** [comment]
I think updating the dependencies to use version `6.2.0-alpha.1` resolves the issue? I think because it's an alpha version you can't use caret operators in the package json to get them.

**Comment by mikesimps** [comment]
Same problem with @turf/distance 6.0.1. Using 6.2.0-alpha.1 worked for me.

**Comment by mfedderly** [comment]
I think this has been fixed at this point.
