### ISSUE TITLE
@types/geojson vs ./lib/geojson.d.ts types mismatch - Typescript

### ISSUE THREAD

**Issue by goszczynskip** [Turfjs/turf#1913]
Turfjs provides it's own copy of geojson types. When users are using @types/geojson in their projects type conflicts arise. Eg. featureCollection method returns FeatureCollection type with property `type: string`. Current version of @types/geojson has FeatureCollection typed with property `type: "FeatureCollection"`. Different typings forces users to unnecessarily cast returned value with `as FeatureCollection<...>` to make types work.

Potential fixes:
* Move @types/geojson to peerDependencies
* Add @types/geojson to dependencies
* Update local version to newest @types/geojson

EDIT:
`./lib/geojson.d.ts` relates to `@turf/helpers` project

**Comment by rowanwins** [comment]
Hi @goszczynskip 

This is a known issue that we're working towards resolving. Closing in favour of https://github.com/Turfjs/turf/issues/1658
