### ISSUE TITLE
Turf.hexgrid creates hexagons as shallow copies. This creates problems with turf.collect

### ISSUE THREAD

**Issue by coquelicotstudio** [Turfjs/turf#1914]
The feature collection returned by `turf.hexgrid` is an array of features which all reference the same object. As a result, when using the hexagonal grid provided by turf.hexgrid to do a binning (with turf.collect, for example) all the hexagons get the result of the last hexagon of the loop.

```
var hexbins = turf.hexGrid(bbox, 0.5)
var collected = turf.collect(hexbins, points, "unitprice", "unit_prices");

//every hexagon shares the same properties
```
I discovered this when I rewrote a collect function since turf.collect wasn't working for me, then it it me. 
A simple workaround is to JSON.parse and JSON.stringify the hexes
```
var hexbins = turf.hexGrid(bbox, 0.5)
hexbins = JSON.parse(JSON.stringify(hexbins))
var collected = turf.collect(hexbins, points, "unitprice", "unit_prices");

//hexagons as independent objects
```

**Comment by rowanwins** [comment]
Thanks for the debugging @coquelicotstudio - good find!

**Comment by rowanwins** [comment]
Hmm looking at this in detail @coquelicotstudio I'm not sure, at least in the current `master` branch

We have a test that ensure this doesn't happen
https://github.com/Turfjs/turf/blob/master/packages/turf-hex-grid/test.js#L61-L71

And the [handling in the code](https://github.com/Turfjs/turf/blob/master/packages/turf-hex-grid/index.ts#L122) looks like JSON.parse is called on every features properties. 

So perhaps this is a version issue. Can you try and use v 6.2.0-alpha.1 ?

**Comment by coquelicotstudio** [comment]
Yes, I'll try and get back to you. Actually I compiled a custom version from [here](https://turfjs-builder.herokuapp.com/), so maybe it's that. Sorry if this caused confusion!

**Comment by rowanwins** [comment]
No longer an issue
