### ISSUE TITLE
@turf/transform-rotate on Polygon, 'coordinates must contain numbers'

### ISSUE THREAD

**Issue by MattIPv4** [Turfjs/turf#1920]
I have a Polygon (`polygon` from `@turf/helpers`) and need to rotate it 180 degrees, so I am using `transformRotate` from `@turf/transform-rotate`.

However, whenever I call `transformRotate(poly, 180)`, I get back an error with `coordinates must contain numbers`, which makes no sense to me?

Basic reproduction can be seen here: https://repl.it/repls/DeafeningWelloffNumericalanalysis#index.js

**Comment by stebogit** [comment]
@MattIPv4 Turf coords must follow the [WGS84 standards](https://github.com/Turfjs/turf#data-in-turf), therefore in `[longitude, latitude]` order, where `latitude` has values between `-90` and `90`.
Many values in your `coords` array are outside the map:

![Screen Shot 2020-06-30 at 5 32 32 PM](https://user-images.githubusercontent.com/12717225/86189918-c4d1e580-baf7-11ea-923a-ac1691196f16.png)

**Comment by MattIPv4** [comment]
Ah, didn't realise that, makes sense. Will look for another solution to rotating the poly -- I'm only using turf for working with polys are no other library seems to be able to take arbitrary coordinates and create polys, then merge them cleanly.
