### ISSUE TITLE
turf.difference and @turf/difference show different results

### ISSUE THREAD

**Issue by Falke-Design** [Turfjs/turf#1922]
The latest turf npm package returns a different result of `difference` then @turf/difference.
It looks like @turf/difference was not updated when the turf package was updated. 

[Sandbox](https://codesandbox.io/s/falke-design-7e88b?fontsize=14&hidenavigation=1&theme=dark)

```
import turf from "turf";
import difference from "@turf/difference";

var polygon1 = turf.polygon([[
  [128, -26],
  [141, -26],
  [141, -21],
  [128, -21],
  [128, -26]
]]);
var polygon2 = turf.polygon([[
  [126, -28],
  [140, -28],
  [140, -20],
  [126, -20],
  [126, -28]
]]);

var diff = turf.difference(polygon1, polygon2)
console.log(JSON.stringify(diff))

var diff2 = difference(polygon1, polygon2)
console.log(JSON.stringify(diff2))
```

**Comment by rowanwins** [comment]
Hi @Falke-Design 

The "turf" package was deprecated many years ago. There is a big notice on npm which says that 
https://www.npmjs.com/package/turf

The underlying library used for the difference operation has changed since then.

Cheers
