### ISSUE TITLE
Mask hangs browser with certain input

### ISSUE THREAD

**Issue by ptallett** [Turfjs/turf#1923]
This crashes (hangs) the browser - some sort of infinite loop?

let p = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[139.77818653048803,35.714261739048666],[139.76494456104314,35.70102500726759],[139.76676400427846,35.6992641470014],[139.78511707505072,35.70755525179209],[139.77818653048803,35.714261739048666]]]}};

let h = {"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":
[[[[139.777001,35.712308],[139.766135,35.701446],[139.767628,35.700001],[139.782689,35.706804],[139.777001,35.712308]]],[[[139.777601,35.713297],[139.765533,35.701233],[139.767191,35.699628],[139.783918,35.707184],[139.777601,35.713297]]],[[[139.778187,35.714262],[139.764945,35.701025],[139.766764,35.699264],[139.785117,35.707555],[139.778187,35.714262]]],[[[139.777601,35.713297],[139.765533,35.701233],[139.767191,35.699628],[139.783918,35.707184],[139.777601,35.713297]]],[[[139.777001,35.712308],[139.766135,35.701446],[139.767628,35.700001],[139.782689,35.706804],[139.777001,35.712308]]],[[[139.776461,35.711417],[139.766678,35.701637],[139.768022,35.700336],[139.781582,35.706462],[139.776461,35.711417]]],[[[139.777001,35.712308],[139.766135,35.701446],[139.767628,35.700001],[139.782689,35.706804],[139.777001,35.712308]]],[[[139.777601,35.713297],[139.765533,35.701233],[139.767191,35.699628],[139.783918,35.707184],[139.777601,35.713297]]],[[[139.778187,35.714262],[139.764945,35.701025],[139.766764,35.699264],[139.785117,35.707555],[139.778187,35.714262]]],[[[139.778187,35.714262],[139.764945,35.701025],[139.766764,35.699264],[139.785117,35.707555],[139.778187,35.714262]]]]}};

turf.mask(h, p);

**Comment by rowanwins** [comment]
Resolved with v6.5.0
