### ISSUE TITLE
Yards units are wrong

### ISSUE THREAD

**Issue by jwoodwardtfx** [Turfjs/turf#1924]
In the turf-helpers the "yard" units are wrong.

For example, "unitsFactors" lists:
 => 1 meter as 100 centimetres (correct)
 => 1 meters as 3.28084 feet (correct)
 => 1 meters as 39.370 inches (correct)
 => 1 meters as 1 / 1.0936 yards (i.e. 0.9144 yards) (wrong!)

A meter is bigger than a yard, so the value should be 1.0936 (i.e. no need for the 1 divided by).

**Comment by lisabaut** [comment]
This PR contains the fix:
https://github.com/Turfjs/turf/pull/2046

**Comment by rowanwins** [comment]
Released in v6.4.0
