### ISSUE TITLE
Missing index.d.ts for @turf/center@6.0.1 standalone module

### ISSUE THREAD

**Issue by papb** [Turfjs/turf#1926]
Something is wrong with the release of `@turf/center` version 6.0.1. It does not have the `index.d.ts` file. To reproduce, simply run `npm i @turf/center` and look into `node_modules`. This problem does not happen with other modules I tested (such as `@turf/helpers` v6.1.4), nor with the previous version of `@turf/center` (5.1.5).

**Comment by F0rt1s** [comment]
center-of-mass has the same problem. I see the .ts files in the repo, but not via npm.

**Comment by mfedderly** [comment]
Can you move to 6.2.0-alpha.2? It should have proper typings. I'm working on releasing 6.2.0 official soon. Reopen this ticket if that branch is still broken.

**Comment by sfadiga** [comment]
Just to confirm that moving to a newer version solves the issue. (6.3.0). 

> Can you move to 6.2.0-alpha.2? It should have proper typings. I'm working on releasing 6.2.0 official soon. Reopen this ticket if that branch is still broken.
