### ISSUE TITLE
inconsistent cleanCoords: mutates points, but rebuilds linestring objects

### ISSUE THREAD

**Issue by ggerber** [Turfjs/turf#1930]
It seems that the clean-coords function (without options provided) mutates points, but builds a new object for linestrings.

If one has a point feature with a parent prop e.g. systemId, this prop will be kept after cleaning (see example below).
```
const dirtypoint = {
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 27.18503064, -31.98847776 ] },
  properties: {
    name: 'TAP 347'
  },
  systemId: 'q2FKy87Aj9Ycuhtxx'
}
const cleanpoint = turf.cleanCoords(dirtypoint);

cleanpoint result keeps the systemId prop:
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 27.18503064, -31.98847776 ] },
  properties: {
    name: 'TAP 347'
  },
  systemId: 'q2FKy87Aj9Ycuhtxx'
}
```
If one has a linestring feature with a parent prop e.g. systemId, this prop will NOT be kept after cleaning.
```
const dirtyline = {
  type: 'Feature',
  geometry: { type: 'LineString', coordinates: [ [Array], [Array] ] },
  properties: {
    name: '6DRR'
  },
  systemId: 'q2FKy87Aj9Ycuhtxx'
}
const cleanline = turf.cleanCoords(dirtyline );

cleanline result returns an object without the systemId prop:
cleanedFeature> {
  type: 'Feature',
  properties: {
    name: '6DRR'
  },
  geometry: { type: 'LineString', coordinates: [ [Array], [Array] ] }
}
```
It appears that cleanCoords mutates points, but builds new objects for linestrings (and maybe other feature types) when no options are specified

**Comment by rowanwins** [comment]
Hi @ggerber 

Sorry for the slow response. 

`cleanCoords` doesn't mutate the point as such, it simply returns itself as there are no coords to be deduplicated :) 
https://github.com/Turfjs/turf/blob/master/packages/turf-clean-coords/index.ts#L57-L58

For other geometry types they go through a feature creation stage where non-geojson spec keys will be dropped.

Hope that helps
