### ISSUE TITLE
Missing index.d.ts files for turf-nearest-point-to-line and turf-point-to-line-distance in version 5.1.6

### ISSUE THREAD

**Issue by jimyang-9** [Turfjs/turf#1933]
To reproduce, install @turf/turf and notice that the files are missing.

**Comment by papb** [comment]
I am also facing the same problem #1926

**Comment by Abourass** [comment]
Same issue on [#1945](https://github.com/Turfjs/turf/issues/1945) in @turf/circle

**Comment by mfedderly** [comment]
Can you move to 6.2.0-alpha.2? It should have proper typings. I'm working on releasing 6.2.0 official soon, hopefully. Reopen this ticket if that branch is still broken.
