### ISSUE TITLE
Dissolve example in documentation is not dissolving

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1934]
The example given for dissolve is not showing any dissolving:

![Screen Shot 2020-08-03 at 11 00 47 am](https://user-images.githubusercontent.com/678344/89136773-b6546f00-d578-11ea-8d02-d20f0a993ce1.png)

I believe the two blocks on the left are not supposed to have a line between them.

I seem to recall having seen this working properly in the past.

http://turfjs.org/docs/#dissolve

**Comment by rowanwins** [comment]
If you use the layer toggle thing on the map you'll be able to see the input and output. Looks like the output is doing what I'd expect.
