### ISSUE TITLE
npmcdn.com/@turf/turf/turf.min.js down

### ISSUE THREAD

**Issue by rmpt** [Turfjs/turf#1935]
seems that turfjs in npmcdn is down. Check it here
https://npmcdn.com/@turf/turf/turf.min.js

**Comment by mvenaas** [comment]
Can confirm. All @turf packages seems to be gone from the registry. Is there anything we can do to help?

**Comment by platon-rov** [comment]
`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@turf/intersect/-/intersect-4.7.3.tgz
`

npm also sends an error.

**Comment by mvenaas** [comment]
It is a problem with the registry itself: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by rmpt** [comment]
seems to be fixed.
