### ISSUE TITLE
intersects error

### ISSUE THREAD

**Issue by EPINRAP** [Turfjs/turf#1936]
Hi
I use `turf.intersect(poly1, poly2)` and I've got the error 

> TopologyException: found non-noded intersection between LINESTRING ( 3.769398 43.56858, 3.769487 43.568614 ) and LINESTRING ( 3.769478 43.568611, 3.769469 43.568605 )

`poly1 = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"measure":"489.38 m^2","type":"Polygon"},"geometry":{"type":"Polygon","coordinates":[[[3.769483032451743,43.568504264325696],[3.7695293005572506,43.56861455199268],[3.7694837030039974,43.56862912744015],[3.769092771040077,43.56852272659239],[3.769122275339241,43.56842458500455],[3.7692188348637767,43.568399320807515],[3.769483032451743,43.568504264325696]]]}}]}`
and
`poly2 = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"parcelles":"34295000AK0033","communes":"Saussan","surface":"255.89 m2","lien":"#z=21/x=419597/y=5398909.85"},"geometry":{"type":"Polygon","coordinates":[[[3.76912122,43.56850399999996],[3.76939757,43.568579510000006],[3.7694867700000003,43.56861442000002],[3.7694783,43.568610610000036],[3.7694685799999994,43.56860510000001],[3.76946106,43.568598140000006],[3.7694571000000003,43.56858890000001],[3.76945683,43.56857846],[3.7694593200000006,43.56857008],[3.7694624299999995,43.56856205],[3.76948242,43.56853941],[3.7692241,43.568415000000016],[3.76912122,43.56850399999996]]]}}]}`

What can I do please ?

**Comment by rowanwins** [comment]
Resolved with the 6.x versions of Turf
