### ISSUE TITLE
Webpack problems with @turf/transformation

### ISSUE THREAD

**Issue by RaymondDashWu** [Turfjs/turf#1937]
More specificially I'm getting this error message:

`_turf_transform_translate__WEBPACK_IMPORTED_MODULE_6__.transformTranslate is not a function`

The code I'm working with. I know that it works because I was previously using @turf/turf. However, I'm trying to refactor and use just the packages I need.

```
import * as turf_transformation from '@turf/transformation';
import * as turf_helper from '@turf/helpers';

const point = turf_helper.point([camera.values[1].longitude, camera.values[1].latitude])
const translatedPoly = turf_transformation.transformTranslate(point, 10000, 270);
```

**Comment by chrisgervang** [comment]
The last version of transform-translate was 5.1.5, released 5 years ago. It seems over the last 5 months they’ve started producing new alpha versions that could potentially work.

Let’s try the version “6.2.0-alpha.2” for both sub-packages.

**Comment by chrisgervang** [comment]
Also I don’t believe “@turf/transformation” is a package on npm, I expect it to be “@turf/transform-translate”

https://www.npmjs.com/package/@turf/transform-translate

**Comment by RaymondDashWu** [comment]
This is the error message I'll get whether I'm using the latest transform-translate package or the alpha:
![image](https://user-images.githubusercontent.com/33266041/91608989-683e4b80-e92b-11ea-9be2-d6780683da66.png)


What I'm trying to transform-translate. Works with the standard @turf/turf package
![image](https://user-images.githubusercontent.com/33266041/91608861-2e6d4500-e92b-11ea-8a54-c228b3ab36c3.png)

**Comment by stebogit** [comment]
@RaymondDashWu I think it should be
```js
import transformTranslate from '@turf/transform-translate';
```

**Comment by RaymondDashWu** [comment]
Yup that was it. I wasn't aware there was a difference in Javascript
