### ISSUE TITLE
point() no longer throws if given invalid args

### ISSUE THREAD

**Issue by diachedelic** [Turfjs/turf#1941]
As of v6.2.0-alpha.2, you can pass `@turf/helper`'s `point` function literally anything and it will not complain. This a breaking change for me - if it's intentional could it be mentioned in the changelog?

```js
import { point } from "@turf/helpers";
point("hello");
// {
//  type: 'Feature',
//  properties: {},
//  geometry: { type: 'Point', coordinates: 'hello' }
// }
```

**Comment by mfedderly** [comment]
Looks like this got dropped when helpers was converted to Typescript. Typescript would catch errors like this at compile time, but obviously not all of our consumers are using Typescript.

**Comment by diachedelic** [comment]
Thanks!
