### ISSUE TITLE
mask freezing and using 100% of CPU

### ISSUE THREAD

**Issue by generalpiston** [Turfjs/turf#1944]
Turf#mask freezes when called using the borders for the city of los angeles. The actual geojson loads fine in geojson.io. It's only when calculating the mask that my CPU hits its limits and the process freezes.

The geojson content is pretty big: above 200kb. It was converted from the tiger census shape files. 

### Steps to reproduce:

1. Save this [gist](https://gist.github.com/generalpiston/a37c167f732eb99c67ebd01c880a1129) to a file called `los-angeles.json`.
2. Run the following code in nodejs.

```javascript
const turf = require('@turf/turf');

const fc = JSON.parse(fs.readFileSync('los-angeles.json').toString());
const poly = turf.polygon(fc.features[0].geometry.coordinates);
const mask = turf.mask(poly);
```

**Comment by generalpiston** [comment]
Apparently it can't compute complex polygons with gaps, holes, etc.

### Work around: 

```
function getBoundariesPolygon(polygon: Polygon): Polygon {
  const [first] = polygon.coordinates
  const coordinates = [first]
  return turf.polygon(coordinates)
}

function getBoundariesMultiPolygon(multipolygon: MultiPolygon): MultiPolygon {
  const coordinates = multipolygon.coordinates.map(([first]) => [first])
  return turf.multiPolygon(coordinates)
}
```

**Comment by Stophface** [comment]
Unfortunatly, this is still a problem 
https://github.com/Turfjs/turf/issues/2054
