### ISSUE TITLE
Does the functional area count correctly?

### ISSUE THREAD

**Issue by na5tyk** [Turfjs/turf#1950]
I am using @turf/area with Leaflet and I created a layer by code:

```
createVectorLayer = config => {
    const { type, latLngs, options = {}, id } = config;
    const layerOptions = options;
    let layer;

    switch (type) {
      case this.names.VECTOR_LAYERS_TYPES.polyline:
        layer = L.polyline(latLngs, layerOptions);
        break;
      case this.names.VECTOR_LAYERS_TYPES.polygon:
        layer = L.polygon(latLngs, layerOptions);
        break;
      default:
        return;
    }

    layer._type = type;

    if (id) {
      layer._leaflet_id = id;
    }

    return layer;
  };

const latlng = this.getPrependicularDestination(currentPoint);
newCoordinates = { lat: latlng[0], lng: latlng[1] };

areaLayer = this.createVectorLayer({
    type: this.names.VECTOR_LAYERS_TYPES.polygon,
    latLngs: [...this.context.coordinates.map(c => [c.lat, c.lng]), latlng]
});
```

And when I calculated a triangle by `area` I get a wrong result.
![obraz](https://user-images.githubusercontent.com/25394240/94234085-42e03580-ff09-11ea-8ae9-1f33bde33280.png)

**Comment by stebogit** [comment]
@na5tyk sorry but I don't see `@turf/area` used anywhere in your code snippet. Is that possible?

**Comment by na5tyk** [comment]
Yes, I am using `@turf/area` in code:

`import area from '@turf/area';
import { parseArea } from '../';

/**
 *
 * @param {Layer} layer
 * @return {Object}
 */
const calculateArea = (layer, unit = 'm') => {
  let value = null;
  if ('geometry' in layer) value = area(layer);
  else value = area(layer.toGeoJSON());

  return {
    value, // unit: square meters
    valueString: parseArea(value, unit)
  };
};

export default calculateArea;
`
