### ISSUE TITLE
打包framework

### ISSUE THREAD

**Issue by fenghedemo1** [Turfjs/turf#1951]
Please provide the following when reporting an issue:

I'm going to report this error using the Turf. Framework as a dependency on my own framework
xcodeproj The linked and embedded framework 'Turf.framework' is missing one or more architectures required by this target: armv7.

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by fenghedemo1** [comment]
It looks like this guy only supports arm64 and I want him to support armv7

**Comment by mfedderly** [comment]
Are you sure you have the right project? This is a javascript library, we don't support any specific CPU architectures.
