### ISSUE TITLE
turf.union will not generate a polygon with a hole

### ISSUE THREAD

**Issue by BradleySpencer** [Turfjs/turf#1955]
I have several polygonal areas that i successfully turn into turf.Polygons. I then want to merge all these polygons together to get a composite polygon. I use the turf.union method and do not have any problems creating a single Polygon/MultiPolygon. However, if the polygons create a hole, turf returns a nothing feature. That is just two points.

If union does not support holes, is it possible that when I do a union I can get a merged result even without the hole rather than nothing?

Two files to test union with...
[map1.geojson.txt](https://github.com/Turfjs/turf/files/5352983/map1.geojson.txt)
[map2.geojson.txt](https://github.com/Turfjs/turf/files/5352984/map2.geojson.txt)

Cheers, Brad...

**Comment by BradleySpencer** [comment]
Can anyone please help me here?

**Comment by BradleySpencer** [comment]
Still need help on this.

**Comment by stebogit** [comment]
@BradleySpencer would you please create a working example (jsfiddle of somthing) of what you did?
That would make it easier to understand your issue

**Comment by BradleySpencer** [comment]
This has resolved. I did provide the Two polygons that were not merging. But since then I have changed how I generate these polygons and voila the merge worked. I will get online again and cancel this issue. Thanks for responding.
Cheers Brad....
