### ISSUE TITLE
Intersection misses

### ISSUE THREAD

**Issue by khrome-cape** [Turfjs/turf#1957]
I am finding that some intersections are "missing", this leads me to not trust the intersect function. It seems to be when the intersected area is very small (possibly a precision error).

1) is it possible to characterize this behavior so I could understand the domain of "misses"?
2) is it possible to control the precision, so I could reduce this potential?

https://jsfiddle.net/khrome/2x1uLq6m/

https://gist.github.com/khrome-cape/6e4c6ccbb20fa440bf55c4501726b7fd

I am currently avoiding these functions and using area calculations to calculate the intersected area, but if I wanted a shape, I would be SOL. How do others accommodate this?

Thanks!

-abbey

**Comment by rowanwins** [comment]
@khrome-cape Sorry for the slow reply, this appears to be resolved with the latest release of TurfJS (v6.3.0)
