### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by liuvigongzuoshi** [Turfjs/turf#1958]
### [code](https://github.com/Turfjs/turf/blob/3fa082cbe0/packages/turf-line-intersect/index.ts#L101-L103)

![image](https://user-images.githubusercontent.com/26923747/95984748-40ad2f00-0e56-11eb-8cc8-42ffdd995d3e.png)

**Comment by stebogit** [comment]
@liuvigongzuoshi what's the issue here? Can you be more explicit please?

**Comment by liuvigongzuoshi** [comment]
@stebogit 
The following code is redundant ?
```js
if (numeA === 0 && numeB === 0) {
	return null;
}
```

**Comment by stebogit** [comment]
👍🏻
