### ISSUE TITLE
Transform Scale Geometry Smaller

### ISSUE THREAD

**Issue by ismetsk** [Turfjs/turf#1959]
Hi,
i am trying to scale  geometry smaller by passing negative value using transform-scale, but it cannot, factor parameter should be greater than zero

but in the  @turf/transform-scale documentation , it says  "_factor number of scaling, positive or **negative** values greater than 0_"

why mentioning negative number when it should be greater than zero  and how to scale geometry to make it smaller than the original.

Thank you.

**Comment by stebogit** [comment]
@ismetsk you should pass a factor less than 1 to reduce the size, like 0.5 to scale it half size.
The docs are clearly wrong and there should indeed be an additional input validation to accept only positive factor values.

**Comment by ismetsk** [comment]
Got it, thank you

**Comment by pm0u** [comment]
This is still an issue
