### ISSUE TITLE
[Workaround provided] boolean-point-in-polygon sometimes fail with points on the edges of the polygons

### ISSUE THREAD

**Issue by matafokka** [Turfjs/turf#1962]
Hello, the issue is basically described in the title. I need to find whether the point is on the edge of the polygon and use `boolean-point-in-polygon` module for it. However, it seems to be failing at complete random, though my points are 100% on the edges.
I'll describe my use-case below if it will help.

I have a grid in which users can select polygons, and script will draw some vertical and horizontal lines in selected polygons. Both grid's edges and drawn lines are straight lines (i.e. lat or lng is always the same).

Algorithm works like this:
1. Use `union` to merge polygons.
1. For each polygon in united multipolygon feature:
   1. Use `bbox` on current polygon to determine where lines should be.
   1. Create the line using the bbox.
   1. Split it by the polygon using `line-split`.
   1. Iterate through each split line and check if both points are in the polygon.

Following screenshot indicates which lines failed throughout my testing:
![Capture](https://user-images.githubusercontent.com/34414488/97080558-eefa6680-1604-11eb-87d2-02d785afd625.PNG)

In my use-case, it seems to fail only on vertical lines, but I'm actually not sure.

P. S. I can't use `boolean-feature-in-polygon` because it ignores the edges and uses `boolean-point-in-polygon` anyway.

**Comment by matafokka** [comment]
I suspect that the problem occurs because of floating point errors, so I decided to write my own script that solves it by leaving the gap in 0.00001 units when comparing floats. It should be enough for the most use-cases.

Please, take a look and change your code accordingly: https://gist.github.com/matafokka/6e071477152aab7f590ac49b569e0dab

Screenshot below shows that my solution works fine:
![Capture](https://user-images.githubusercontent.com/34414488/97086664-65ab5a00-162d-11eb-9783-f61664dc39c4.PNG)

P. S. I'll leave this issue open until you fix the code. My workaround doesn't solve it, it, well, provides a workaround :D

**Comment by rowanwins** [comment]
Hi @matafokka 

Sorry for the slow reply

You might want to take a look at [point-in-polygon-hao](https://github.com/rowanwins/point-in-polygon-hao). This module should accurately report whether a point is on an edge.

I've got a [PR](https://github.com/Turfjs/turf/pull/1893) for Turf which will update it to use that module

Hopefully that helps

**Comment by matafokka** [comment]
Hello, @rowanwins, thank you for the suggestion, but I've already implemented my own algorithm and posted a [gist](https://gist.github.com/matafokka/6e071477152aab7f590ac49b569e0dab) with it here.

If someone's interested, I've also implemented line intersection _(works with all types of intersection including overlapping and perpendicular lines)_ and clipping _(it doesn't account holes since I don't need it in my project)_. Use [this gist](https://gist.github.com/matafokka/d7d51f58a583eea21557ac07fe6a34ef) if you need such functionality.
