### ISSUE TITLE
Test output in @turf/destination does not match manual results

### ISSUE THREAD

**Issue by baparham** [Turfjs/turf#1966]
I am having a hard time understanding one of the tests in `@turf/destination` called `point-far-away` which takes an [input geojson](https://github.com/Turfjs/turf/blob/master/packages/turf-destination/test/in/point-way-far-away.geojson) and using the destination function, the test expects an output point defined in the [out geojson](https://github.com/Turfjs/turf/blob/master/packages/turf-destination/test/out/point-way-far-away.geojson).

When I run the `destination()` function manually with the same `lng: -75, lat: 39` coordinates, bearing of `90` and distance of `5000 miles`, as defined in the input geojson, the result I get is `lng: 1.1237... , lat: 10.990466...` but the test output geojson suggests that the answer should instead be `lng: -22.885356, lat: 26.440011`

```
var destination = require('@turf/destination')
destination([-75,39], 5000, 90, {units: 'miles'});
{
  type: 'Feature',
  properties: {},
  geometry: {
    type: 'Point',
    coordinates: [ 1.123702522680564, 10.990466075751456 ]
  }
}
```

The test says it passes in CI, as well as locally in my clone (based on a recent master SHA 23d5cb9)
```
...
ok 1 point-0
ok 2 point-180
ok 3 point-90
ok 4 point-way-far-away

1..4
# tests 4
# pass  4

# ok
...
```
 
My question is how can this test pass? It appears to expect the wrong result, but be marked as passed in the test suite.

I've attempted to manually generate the destination in this jsfiddle to try and verify the expected results.

See [this jsfiddle](https://jsfiddle.net/wgr5pjz1/) for steps taken to manually generate resulting lat/lng

Thanks for any help you can provide! I'll continue investigating to see if I can find the root cause as well in the meantime.

**Comment by baparham** [comment]
Ah, it seems asking the question leads oneself to the answer. It appears that the call to `destination()` in this test does not pass along any `units` specified in the in.geojson file.

Attempting the manual destination call with the default of kilometers results in the same coordinates as the output.geojson file expects.

I can work up a PR to update the test to pass along the units, and test both km and miles in this case.

**Comment by rowanwins** [comment]
Resolved
