### ISSUE TITLE
Question: Minimum bounding rectangle by width possible to get in Turf?

### ISSUE THREAD

**Issue by matthiasfeist** [Turfjs/turf#1969]
Hi everyone.

I wonder if it's possible with Turf (or a different library) to get the minimum boundary rectangle by width from a arbitrary polygon.
See here for an illustration of what I mean: http://resources.arcgis.com/en/help/main/10.1/0017/GUID-EFBA5DB8-A161-4FE1-B2CB-792B65DC1469-web.png
It's not really a bounding box since a bbox since the rectangle I want can also be rotated.

Thanks for the help!
Matthias

**Comment by stebogit** [comment]
@matthiasfeist there's only `@turf/envelope` which is still not what you're looking for.
I don't know other libraries out there that could help you, but maybe somebody else might have suggestions.

**Comment by matthiasfeist** [comment]
would that be something of interest to implement for turf? Because I'm actually thinking of implementing this myself. Or is this too niece and therefore maybe it's best as a complete separate module?

**Comment by matthiasfeist** [comment]
It was actually not that hard to implement with Turf: https://www.npmjs.com/package/geojson-minimum-bounding-rectangle
