### ISSUE TITLE
@turf/distance does not include index.d.ts

### ISSUE THREAD

**Issue by mjeffryes** [Turfjs/turf#1971]
I noticed that if I import @turf/distance as a separate module, I don't get the type definitions. Since they are present in @turf/turf, this is probably just an issue with how the module is packaged for publishing

I'm using @turf/distance version 6.0.1

**Comment by rowanwins** [comment]
Hi @mjeffryes 

Perhaps try version 6.2.0-alpha.2 . That release should fix a bunch of issues with typings.

**Comment by mjeffryes** [comment]
I can confirm that the typing for this package is correct in 6.2.0-alpha.2.
Thanks!
