### ISSUE TITLE
cleanCoords not working.

### ISSUE THREAD

**Issue by spirityy** [Turfjs/turf#1973]
![image](https://user-images.githubusercontent.com/424997/100598117-43e27880-3339-11eb-8071-4d2c1cfe8b5b.png)
["121.477569", "31.249001"]. 1
["121.480350", "31.246342"] 2
["121.483611", "31.243204"] 3
["121.486640", "31.240326"] 4
["121.488970", "31.237995"] 5
`
console.info(new_line)
                const line = turf.lineString(new_line);
                const nn = turf.cleanCoords(line);
                console.info(nn);`

2,3,4 These three points are all online, but they are not removed.

**Comment by stebogit** [comment]
@spirityy [looks like](https://jsfiddle.net/jStefano/hLdg68rb/) the original points are actually not on the same straight line:

<img width="755" alt="Screen Shot 2020-12-01 at 5 20 57 PM" src="https://user-images.githubusercontent.com/12717225/100815779-9aaf8700-33f9-11eb-926d-e7a979d38cc9.png">

**Note:** GeoJSON specs require the coordinates to be an array of numbers
