### ISSUE TITLE
Typo in function lineString(coordinates, properties, options)

### ISSUE THREAD

**Issue by devleaks** [Turfjs/turf#1977]
@turf/turf 5.1.6
turf.js, line 301

function lineString contains following test:

    if (!isNumber(coordinates[0][1]) || !isNumber(coordinates[0][1])) throw new Error('coordinates must contain numbers');

I guess it should be

    if (!isNumber(coordinates[0][0]) || !isNumber(coordinates[0][1])) throw new Error('coordinates must contain numbers');

Best regards.

**Comment by rowanwins** [comment]
This check has been removed in converting the package to TS
