### ISSUE TITLE
Feature request: Calculate bbox around a lat lon point (eg 10km from point)

### ISSUE THREAD

**Issue by giorgio79** [Turfjs/turf#1990]
Would love to be able to get a bounding box around a point
https://stackoverflow.com/questions/238260/how-to-calculate-the-bounding-box-for-a-given-lat-lng-location

**Comment by stebogit** [comment]
@giorgio79 how about this:

```js
function bboxFromPoint (point, distance, units = 'kilometers') {
    const sw = turf.destination(point, distance, 225, {units});
    const ne = turf.destination(point, distance, 45, {units});
    return turf.bbox(turf.featureCollection([sw, ne]));
}

const p = turf.point([0, 51.5]);
const bbox = bboxFromPoint(p, 10);

console.log(JSON.stringify(bbox));
// [-0.1020103424526593,51.436364157041396,0.10229541253210864,51.56354711265323]
```

**Comment by giorgio79** [comment]
Thanks Stefano! Looks good. I have to admit I went with a radius solution meanwhile for Openstreetmap. I worked with getVisibleRegion for GoogleMaps to get bbox, but wanted to break free from Google.
