### ISSUE TITLE
doxme readmes

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#200]
per @tmcw's suggestion, lets automate readme generation using dox and doxme. We should make the parameters a bit more readable (using tables or whatever). Once ready, let's run it across all submodules in a mega script.

Once this is done, docs will be updated in exactly one place, the jsdoc comments.

**Comment by morganherlocker** [comment]
cc @lyzidiamond

**Comment by lyzidiamond** [comment]
Let's just keep track of how this changes the workflow so we can keep DOCUMENTATION.md and the README up to date. :haircut: :ear: :ice_cream:

**Comment by tmcw** [comment]
Now that I look at this, it kind of makes sense for doxme to generate a complete readme, not just the `##api` section. What do you think?

**Comment by tmcw** [comment]
upstream: https://github.com/tmcw/doxme/issues/2

**Comment by morganherlocker** [comment]
@tmcw agree, this should be 100% generated from the jsdocs.

**Comment by tmcw** [comment]
This is ready to go: [turf-modules-add-dox](https://github.com/Turfjs/turf-extent#turf-extent) makes and runs a `npm run doc` script. [example output](https://github.com/Turfjs/turf-extent#turf-extent).

Going to drop this in as soon as @lyzidiamond and co are happy with the state of the content

**Comment by tmcw** [comment]
Done: run `npm run doc` in any repo to rebuild.
