### ISSUE TITLE
Error with topojson on npm install

### ISSUE THREAD

**Issue by countfak** [Turfjs/turf#2005]
Hi, I have the following error when installing Turf 6.2.0 with npm install:

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /app/node_modules/topojson/node_modules/topojson-server/bin/geo2topo
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/app/node_modules/topojson/node_modules/topojson-server/bin/geo2topo'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

I have no issues when installin with yarn install.
Tried with both node 14 and 15.
I'm on macos, but I get the same error when building my application with docker.

**Comment by rowanwins** [comment]
Hi @marcofacheris 

I just ran `npm install @turf/turf` on mac with node v14 and didn't get any errors. 

It did throw a warning saying 
````
npm WARN deprecated topojson@3.0.2: Use topojson-client, topojson-server or topojson-simplify directly
````
but the install continued successfully. I can also see the file `/topojson/node_modules/topojson-server/bin/geo2top` in my install directory.

🤷‍♂️

**Comment by LucaIaconelli** [comment]
same problem here

**Comment by andy-harney** [comment]
I have the same issue here trying to upgrade to 6.3.0.
Running Node v15.6.0 on Ubuntu 20.04.
```
❯ npm install @turf/turf@latest
npm WARN deprecated topojson@3.0.2: Use topojson-client, topojson-server or topojson-simplify directly.
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /xxx/xxx/xxx/node_modules/topojson/node_modules/topojson-server/bin/geo2topo
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/xxx/xxx/xxx/node_modules/topojson/node_modules/topojson-server/bin/geo2topo'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2021-01-22T15_50_26_409Z-debug.log
```
I also see the file in `node_modules/topojson/node_modules/topojson-server/bin/geo2topo`, but the install won't work.  
I've tried removing all the packages and starting clean, but still no joy.

I can selectively pick out the modules I need individually so not so pressing for me.

Thank you for the great library, my work would not be possible without it.

**Comment by rowanwins** [comment]
The answer is to probably update the module/s which rely on topojson

**Comment by zdm** [comment]
1. This issue is only for npm v7, because npm7 trying to install deps to the top node_modules directory, but topojson has hardcoded path, that points to it;s owe node_modules;
2. topojson was deprecated and should be replaced with topojson-client, topojson-server;

**Comment by danielkbx** [comment]
Same here, npm v7.
