### ISSUE TITLE
calculate latitude/longitude of a point based on distance between another point

### ISSUE THREAD

**Issue by HuyHoang-Ta** [Turfjs/turf#2006]
Hello everyone, is there a method or function to calculate latitude/longitude of second point based on the latitude/longitude of first point and distance in meter between them. Thank you!

**Comment by rowanwins** [comment]
I think you're looking for [`destination`](http://turfjs.org/docs/#destination)

**Comment by HuyHoang-Ta** [comment]
Thank you
