### ISSUE TITLE
Direction of rotation in transformRotate?

### ISSUE THREAD

**Issue by pasieronen** [Turfjs/turf#2015]
The documentation for transformRotate says `angle: of rotation (along the vertical axis), from North in decimal degrees, negative clockwise` and `all rotations follow the right-hand rule` (which here means positive = counterclockwise, right?).

But the example in http://turfjs.org/docs/#transformRotate shows that a positive angle (10 degrees in the example) rotates the triangle **clockwise**.

(And this would be consistent with the "bearing" parameter for some other Turf.js functions, which explicitly say `positive clockwise`).

Which is the intended behavior here? 

(btw, turf/ellipse has the same description for its "angle" parameter, and it uses transformRotate internally).

**Comment by stebogit** [comment]
yeah, that's definitely an error on the docs: the example is correct, **_positive rotation_** is **_clockwise_**
