### ISSUE TITLE
TypeScript errors in turf 6 (TS2304 and TS2312)

### ISSUE THREAD

**Issue by everhardt** [Turfjs/turf#2017]
I've updated @turf/turf from 5.1.6 to 6.3.0 and now TypeScript is complaining about the following when I transpile my project:

```
node_modules/@turf/center-median/dist/js/index.d.ts:59:29 - error TS2304: Cannot find name 'Position'.

59     medianCandidates: Array<Position>;
                               ~~~~~~~~

node_modules/@turf/clusters-dbscan/dist/js/index.d.ts:3:38 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

3 export interface DbscanProps extends Properties {
                                       ~~~~~~~~~~

node_modules/@turf/clusters-kmeans/dist/js/index.d.ts:2:38 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

2 export interface KmeansProps extends Properties {
                                       ~~~~~~~~~~
```

My tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "target": "es2019",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "preserveSymlinks": true,
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*",
      ]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./src/types"
    ]
  },
  "include": [
    "src/**/*",
    "test/**/*"
  ]
}
```

I just tried with 6.2.0 and that gives the same issue. For now, I've reverted back to 5.1.6

**Comment by mfedderly** [comment]
Your typescript settings are likely more strict than Turf's. I'm hoping to enable all the strictness but in the meantime you might want to look into the `skipLibCheck` option.

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by everhardt** [comment]
Thanks for the quick response. I looked into that but I have some custom declaration files in the project as well, that I do like to get checked. I'm not in a hurry, so I'll just hold off on updating for now.

**Comment by antonazaides** [comment]
Hi @mfedderly, I have a similar issue.

I also upgraded to 6.3 from 5.1, and I started to get ts 2322 (type assignment) erros.
Those errors happen for assignment of a feature to another feature. It seems null was added as an option somewhere, and I can't figure out where.

Could you please take a look? Thanks a lot for your time and effort!

An example for those two types :

```
selectedUnion: Feature <Polygon | MultiPolygon>
coveredAreaPolygon: Feature <Geometry>
```

![image](https://user-images.githubusercontent.com/73165655/108621251-476a3500-743a-11eb-90c2-c5edcc15864f.png)

```
Type 'Feature<Polygon | MultiPolygon, Properties>' is not assignable to type 'Feature<Geometry, Properties>'.
  Types of property 'geometry' are incompatible.
    Type 'Polygon | MultiPolygon | null' is not assignable to type 'Geometry'.
      Type 'null' is not assignable to type 'Geometry'.ts(2322)
```


I tried to change the coveredAreaPolygon to Feature<Geometry>, I get the same error but but for Geometry object:


```
Type 'import("c:/Users/AtonZaides/Documents/TaranisRepos/pilot-mission-tool/node_modules/@turf/center/node_modules/@turf/helpers/lib/geojson").Feature<import("c:/Users/AtonZaides/Documents/TaranisRepos/pilot-mission-tool/node_modules/@turf/center/node_modules/@turf/helpers/lib/geojson").Geometry, import("c:/Users/AtonZaid...' is not assignable to type 'import("c:/Users/AtonZaides/Documents/TaranisRepos/pilot-mission-tool/node_modules/@turf/helpers/dist/js/lib/geojson").Feature<import("c:/Users/AtonZaides/Documents/TaranisRepos/pilot-mission-tool/node_modules/@turf/helpers/dist/js/lib/geojson").Geometry, import("c:/Users/AtonZaides/Documents/TaranisRepos/pilot-miss...'.
  Types of property 'geometry' are incompatible.
    Type 'Geometry | null' is not assignable to type 'Geometry'.
      Type 'null' is not assignable to type 'Geometry'.ts(2322)
```

The same thing happens in other places, while trying to assign Feature<Polygon | MultiPolygon> to another Feature<Polygon | MultiPolygon>, and Feature<Point> to Feature<Point>.

```
Types of property 'geometry' are incompatible.
    Type 'Polygon | MultiPolygon | null' is not assignable to type 'Polygon | MultiPolygon'.
      Type 'null' is not assignable to type 'Polygon | MultiPolygon'
```

**Comment by Seairth** [comment]
Submitted PR (#2044).

**Comment by Pesonet1** [comment]
This is not fully resolved, since centerMedian method still misses Position type import (@turf/center-median/dist/js/index.d.ts). Tested with newest 6.3. version. @Seairth PR only partly resolves the problem.

**Comment by Seairth** [comment]
> This is not fully resolved, since centerMedian method still misses Position type import (@turf/center-median/dist/js/index.d.ts). Tested with newest 6.3. version. @Seairth PR only partly resolves the problem.

Have you tested with the Master branch?  The PR was submitted after 6.3.  A version including that PR has not yet been published to npm.

**Comment by Pesonet1** [comment]
My bad. I thought that that was already published (should have investigated further).

**Comment by Naitik333** [comment]
@mfedderly When this fix will be released? Its blocking so many people to upgrade to latest version 6.3.0. 
Please release this fix as soon as possible.

**Comment by karl-axel-linstrom** [comment]
when is this fix getting released? and until that what how far back does one have to go to find a version without this bug?

**Comment by sagewall** [comment]
I'm also anxiously awaiting a new release to NPM due to the typescript errors preventing the build in @angular/cli 12

**Comment by everhardt** [comment]
I just updated to turf 6.4, but I still get one of them:

```
node_modules/@turf/clusters-dbscan/dist/js/index.d.ts:3:38 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

3 export interface DbscanProps extends Properties {
                                       ~~~~~~~~~~
```

**Comment by mfedderly** [comment]
Yep still working on it. There's 5 packages that still need fixes. polygonize, clusters-kmeans, clusters-dbscan, boolean-equal, and boolean-overlap. Waiting on:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53899
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53900
