### ISSUE TITLE
Some packages not exporting their `package.json`

### ISSUE THREAD

**Issue by mindrones** [Turfjs/turf#2018]
Hi, I'm using turf in a [Svelte](https://svelte.dev) component, and I'm getting:

```
[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

- @turf/meta
- @turf/helpers
```

Just a FYI, not sure if relevant for you, feel free to close if not, thanks!

**Comment by mfedderly** [comment]
Did you try 6.3.0?

**Comment by mindrones** [comment]
Hi, nope, this is happening with `6.2.0-alpha.0`, will try this in the coming days (I need to update `turf` in a dependency first) and will report back thanks!

**Comment by mindrones** [comment]
This seems to have been fixed, closing, thanks!
