### ISSUE TITLE
Get coordinates of inner polygon at a offset distance from x m or km 

### ISSUE THREAD

**Issue by DVGY** [Turfjs/turf#2021]
Hello

![image](https://user-images.githubusercontent.com/46158826/105700225-93ef4d00-5f2e-11eb-8917-290c71660ed9.png)

Suppose x1, y1, ...... x4,y4 are some coordinates of a polygon. I want to generate a similar innner polygon at a offset distance of x m or km. 

How can i achieve this using turf js ?

Thanks

**Comment by Neorth** [comment]
You should be able to use the [distance](http://turfjs.org/docs/#distance) function to find the new corners.

**Comment by stebogit** [comment]
Actually `@turf/destination` would find the new points you are looking for, `@turf/distance` would instead measure the distance between two points.

Alternatively you could try `@turf/transform-scale`, I guess using the ratio between the length of the original side and the one of the desired new side, which would automatically keep the new poligon centered on the original one.

**Comment by Neorth** [comment]
Ah, thought of destination but copied distance link. Thanks for correcting me!

**Comment by DVGY** [comment]
> Actually `@turf/destination` would find the new points you are looking for, `@turf/distance` would instead measure the distance between two points.
> 
> Alternatively you could try `@turf/transform-scale`, I guess using the ratio between the length of the original side and the one of the desired new side, which would automatically keep the new poligon centered on the original one.

Okay, will try that. Let's say the offset distance is not different for each side. Then??

**Comment by stebogit** [comment]
Huh? 🤨

**Comment by DVGY** [comment]
> Huh? 🤨

I mean let's say the distance of inner polygon from the outer polygon is different for each side. So in my original question it is 15 m. Let's say it is 10m ,5m, 15m and 8m. Will the transform/scale and distance work ?

**Comment by stebogit** [comment]
No

**Comment by DVGY** [comment]
> No

Then what can really work in this case ?

**Comment by stebogit** [comment]
I can't think of anything else but calculating the position of each new vertexes with `@turf/destination`.
