### ISSUE TITLE
lineArc doesn't goes all the way to the end bearing 

### ISSUE THREAD

**Issue by SBD580** [Turfjs/turf#2022]
turf version: 6.3

Seems line the `lineArc` function is not returning a full arc between the start and end bearing.

Running this code:
```
console.log(JSON.stringify((()=>{
    const center = [40,-40];
    const radius = 0.1;
    const angle = 90;
    return turf.featureCollection([
        turf.point(center),
        turf.destination(center,radius,angle),
        turf.lineArc(center,radius,0,angle)
    ]);
})()));
```

will produce the following output:
```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[40,-40]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[40.001173979358185,-39.999999994077704]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[40,-39.99910067963628],[40.000115068591285,-39.99910501005274],[40.00022902905257,-39.99911795959949],[40.000340783924074,-39.999139403570176],[40.00044925698379,-39.999169135455496],[40.00055340361059,-39.99920686893177],[40.000652220843214,-39.999252240617906],[40.00074475703826,-39.9993048135745],[40.00083012103427,-39.99936408151124],[40.00090749073357,-39.99942947366214],[40.00097612101938,-39.99950036028168],[40.001035350931865,-39.999576058708946],[40.00108461003402,-39.99965583994146],[40.00112342390608,-39.999738935655245],[40.00115141871549,-39.99982454560377],[40.00116832481846,-39.99991184532433]]}}]}
```

which looks like that:
![image](https://user-images.githubusercontent.com/3942469/105998520-6680db80-60b5-11eb-9972-53a8705df572.png)

**Comment by rowanwins** [comment]
Sorry for the slow reply @SBD580 

This has been resolved by #2142 although isn't yet released, stay tuned.

**Comment by SBD580** [comment]
Great, thanks for the update.
Would that going to fix the sector function as well?

**Comment by rowanwins** [comment]
Yep

**Comment by mfedderly** [comment]
I'm going to close this, as the PR has merged and we're looking at doing the 7.0 release very soon.

**Comment by SBD580** [comment]
Any update? It has been two years and version 7.0 wasn't released yet.
Any chance to have a fix for it in 6.x version?

**Comment by drowouw** [comment]
Still having this issue using version 7.0 alpha with arc smaller than 90 degree ([fiddle](https://jsfiddle.net/r4mo2gua/3/)). The fiddle creates an arc between the displayed lines.
Output pasted on [geojson.io](https://geojson.io/) shows gaps at start and end bearing (set A).
Furthermore, running the lineArc command in a different location delivers a different result, with included end bearing (set B).

Does anyone have a workaround for this issue?

**Comment by SBD580** [comment]
@drowouw this is what we are using as a workaround:

```typescript
const iterativeLineArc: typeof lineArc = (
  origin,
  radius,
  startAngle,
  endAngle,
  options
) => {
  const steps = options?.steps ?? 64;
  return lineString(
    new Array(steps + 1).fill(null).map((_, i) => {
      return destination(
        origin,
        radius,
        startAngle + (i * (endAngle - startAngle)) / steps,
        { units: options?.units }
      ).geometry.coordinates;
    })
  );
};
```
