### ISSUE TITLE
Multiple HexGrid doesn't connect between them

### ISSUE THREAD

**Issue by Zheroh** [Turfjs/turf#2025]
Hi,
I'm not sure the title was clear enough.
So I made 2 hexGrid :

`   const bbox =   [3.779293, 43.580393, 3.823239, 43.612219];
    const bbox2 = [3.779293 ,43.548550, 3.823239, 43.580393];
    const cellSide =0.012;
    const options = {};
    const hexGrid = turf.squareGrid(bbox, cellSide, options);
    const hexGrid2 = turf.squareGrid(bbox2, cellSide, options);
`

But the grid are not connected, like in this image that : <a href="https://ibb.co/mFWCZ3d"><img src="https://i.ibb.co/mFWCZ3d/Capture-d-cran-de-2021-02-04-17-35-10.png" alt="Hexgrid" border="0"></a>

Am I missing something?

**Comment by stebogit** [comment]
@Zheroh the square grid is created centered within the passed bbox, therefore if the sum of the cell sides don't match with the bbox dimensions you'll end up with some "padding". You should adjust the `cellSide` value accordingly, e.g.

`cellSide = bboxHeight / expectedNumberOfCells`

https://turf-sandbox.netlify.app/?gist=c4b211b0f40114c1053313f44bcd1efd

![Screen Shot 2021-02-04 at 9 39 02 AM](https://user-images.githubusercontent.com/12717225/106933591-f209f600-66cd-11eb-8b53-d379352e93ba.png)
