### ISSUE TITLE
lineStringsIntersect in geojson-utils a lot faster than turf.lineIntersect

### ISSUE THREAD

**Issue by matthiasfeist** [Turfjs/turf#2029]
I have a usecase where I need to check for a lot of lines where they intersect which a lot of Polygons. I really like turf and I use it a lot in my project but I noticed that turf.lineIntersect is relatively slow.

I then stumbled upon https://github.com/maxogden/geojson-js-utils (which does not seem to be actively maintained anymore) and their lineStringsIntersect method.

This seems to be (in my usecase) significantly faster and I wonder why. In case the algorithm is just way quicker, maybe it would be cool to integrate the faster algorithm into turf?

**Comment by rowanwins** [comment]
Hi @matthiasfeist 

Thanks for the tip. I've got an open PR (see #2033) for a rewrite of this module which makes it much more performant (particularly for non-trivial geometries) by using a sweepline algorithm I wrote, this should be faster than the geojson-js-utils lib which I think uses a fairly brute force algorithm.

**Comment by matthiasfeist** [comment]
nice
