### ISSUE TITLE
boolean relationships

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#203]
See http://toblerity.org/shapely/manual.html#relationships

I want `intersects, crosses, overlaps, touches, equals, contains`: each should take two GeoJSON objects and return true or false.
- equals: https://github.com/Turfjs/turf-equal

---

I think these would be best conceived as a feature to land in 1.5.0 or such, all-at-once and fairly well-polished, so we can have a very predictable logic for how they relate to each other, as Shapely does

**Comment by lyzidiamond** [comment]
:+1: This would be a huge step towards a more complete GIS alternative.

**Comment by morganherlocker** [comment]
most of these are already around in one way or another, but it would be great to make these components more high level.

**Comment by tmcw** [comment]
@morganherlocker - any pointers for where these are implemented? I guess we could emulate crosses & intersects by running an intersection and checking whether the result is nil, but that seems unnecessarily expensive.

**Comment by morganherlocker** [comment]
> intersects by running an intersection and checking whether the result is nil

@tmcw yeah, that's pretty much what I had in mind. Agree that these should be separate implementations with performance front and center. I think most of these can be implemented to run very fast using modified variations of [turf-kinks](https://github.com/Turfjs/turf-kinks/blob/master/index.js). Throw in sweepline, or various other indexing strategies, and it should be quite performant. `contains` will probably be the most expensive.

For reference, this seems to be the exact specification that Shapely (and probably postgis, ogc, etc.) try to follow http://en.wikipedia.org/wiki/DE-9IM

Also, I believe Shapely uses planar geometry, but I think these calculations should be geodesic in Turf.

**Comment by landonreed** [comment]
This would definitely be helpful.  I'm using intersect now and noticing that `undefined` means no intersect, feature Polygon means they overlap, and feature MultiLineString means they share a border.  Do you think the [docs](http://turfjs.org/static/docs/module-turf_intersect.html) should reflect this distinction at the very least?

**Comment by lyzidiamond** [comment]
@landonreed :+1: => https://github.com/Turfjs/turf-intersect/issues/6

**Comment by landonreed** [comment]
:grin:

**Comment by tchannel** [comment]
I'm tinkering on some of these right now:

- [Overlaps](https://github.com/tchannel/turf-overlaps) - This should be relatively workable at this point. I haven't put in all the tests yet, but *I think* it should work for multipolygons / correctly deal with donuts
- [Within for Polygons](https://github.com/tchannel/turf-polygon-within) - This one is very prototypey. Haven't had a chance to test it with a bunch of cases yet, and I need to look at some other GIS tool examples for how they handle special cases. For example, in the case of a polygon inside the "hole" section of a donut... is it considered "within"? The current implementation won't handle that.

**Comment by lyzidiamond** [comment]
@landonreed JFYI, this doc is fixed now: http://turfjs.org/static/docs/module-turf_intersect.html

**Comment by dr-jts** [comment]
@tchannel a polygon A  inside the hole of a "donut" polygon B is NOT "within" B, since it lies in the exterior of B ( = does not intersect any point of B)

**Comment by tmcw** [comment]
Please re-open under a different user if this is still a priority; I'm not tracking this as work that I'll do.

**Comment by DenisCarriere** [comment]
👍 @tmcw re-opening each of these individually sounds like a better plan.
