### ISSUE TITLE
booleanIntersects is not exported from @turf/turf

### ISSUE THREAD

**Issue by kachkaev** [Turfjs/turf#2034]
- [x] **Turf version:** @turf/turf@6.3.0
- [x] **GeoJSON data:** N/A
- [x] **Snippet of source:**

```ts
import * as turf from "@turf/turf";
import { a, b } from "./myGeoFeatures";

const check = turf.booleanIntersects(a, b) // ❌ Property 'booleanIntersects' does not exist on type 'typeof import("/path/to/node_modules/@turf/turf/index")'.ts(2339)
const workaround = !turf.booleanDisjoint(a, b) // ✅ OK
```

Looks like `booleanIntersects` is simply missing from module re-exports.

**Comment by rowanwins** [comment]
Thanks for the report @kachkaev , I've opened a PR

**Comment by infacto** [comment]
@rowanwins Please consider release a new version with this fix. Thanks.
