### ISSUE TITLE
Incompatibility: "metres" not allowed by the Units type in v6

### ISSUE THREAD

**Issue by tuukka** [Turfjs/turf#2038]
Code such as `turfDistance(from, to, {units: "metres"})` works in 5.1.6 but Typescript fails it in 6.3.0:

`Type '"metres"' is not assignable to type '"meters" | "millimeters" | "centimeters" | "kilometers" | "acres" | "miles" | "nauticalmiles" | "inches" | "yards" | "feet" | "radians" | "degrees" | "hectares" | undefined'.`

Should `"metres"` be added in the type definition (keeping compatibility) or should "metres" be deprecated and removed from the documentation (simplifying the API)?

**Comment by stebogit** [comment]
I'm quite sure we used to support "kilometre", in addition to "kilometer", so maybe we sould have both added back?

I've always thought it was a typo, but it appears it's just the common spelling outside the US. I'd suggest we support both alternatives.

**Comment by rowanwins** [comment]
Support for metres should be added to the typings
