### ISSUE TITLE
turf.buffer add capStyle to the options

### ISSUE THREAD

**Issue by abouroubi** [Turfjs/turf#2039]
The underlying jsts library used by turfjs to do the buffer operation accepts an `endCapStyle` argument, it can be round, flat or square, I think it should be added to the options of turf.buffer function.

**Comment by rowanwins** [comment]
Thanks @abouroubi , it's on the radar :) 
Although I'm going to close this ticket in favour of #639 which has a bit more history but a very similar idea.
