### ISSUE TITLE
Not support triangle?

### ISSUE THREAD

**Issue by justb** [Turfjs/turf#2041]
var polygon = turf.polygon([[
    [108.09876, 37.200787],
    [106.398901, 33.648651],
    [114.972103, 33.340483],
  ]]);
![image](https://user-images.githubusercontent.com/22002343/108698932-a1a0ee00-753f-11eb-8cbf-7d07623c80ca.png)

**Comment by stebogit** [comment]
@justb as per [GeoJSON specs](https://tools.ietf.org/html/rfc7946#section-3.1.6) a Polygon should always have identical first and last point of its linear ring, which should have at least 4 points (in the case of a triangle)

**Comment by jfoclpf** [comment]
@stebogit please do kindly then clarify that in the documentation: 

> **a Polygon should always have identical first and last point of its linear ring**

https://www.npmjs.com/package/turf-polygon

it took me a while to get that, just your message here clarified my question
