### ISSUE TITLE
turf-segments

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#205]
line-slice a collection of points against a linestring. Playing with a use case now that I think this would be useful for, but I will circle back with a decision on how useful this actually is for general cases.

Another alternative would be to allow turf-line-slice to accept a featurecollection of points, but that might blunt the usability a bit.

**Comment by tmcw** [comment]
see also https://github.com/mapbox/geojson-segment

**Comment by DenisCarriere** [comment]
👍 this would be a good idea for a Turf module, I've had to create 2 vertex line segments from Polygon/LineString (any valid GeoJSON that aren't points) in many scenarios.

Here's a few modules that would already depend on this module/feature.

- `line-intersect`
- `kinks`
- `unkink-polygon`
- `polygon-slice`

We could call this module `@turf/line-segment`.

**Comment by DenisCarriere** [comment]
PR https://github.com/Turfjs/turf/pull/611 adds this type of module/feature.
