### ISSUE TITLE
transformScale not really centered

### ISSUE THREAD

**Issue by JMFL92** [Turfjs/turf#2056]
Hi
I use for the first time turfjs ... very great thank you all !
my goal is to make large inner boundaries of a polygon, filled with pattern.
To do that, I use "transformScale" with "mask"
the factor I set is 0.9
I've tried with the option origin: center or centroid, but the result is the same : 
the masked final polygone (multi segments) has different border width, depending of the segment of the polygon.
![exemple-screenshot](https://user-images.githubusercontent.com/31623542/111130151-2a2b1100-8577-11eb-8cc1-3a7693f318fc.png)
I'm not expert, so I can't say that this is the result of the centering option which return bad results. Maybe they are good. Just I mean maybe it should be a third centering option, which make that all borders have the same width between  the original polygon, and its mask which is the result of the transformScale of the original polygon ...

Or maybe I'm not using the best functions to do that ...

I'm using the 6.3 version of turf with leaflet for OSM

thank you for your help
JMarc

**Comment by stebogit** [comment]
@JMFL92 I can't say there are no issue in the library, however scaling is different than creating a buffer. Scaling a polygon will shrink or enlarge the feature proportionally to the dimension of its shape, while a buffer creates a new polygon where all points have the same distance from the original feature. I am honestly not sure I understand your specific use case, but maybe [`@turf/buffer`](https://turfjs.org/docs/#buffer) is what you are looking for?

**Comment by JMFL92** [comment]
thank you so much @stebogit  ! Buffer is exactly what I was looking for...
I didn't notice this function ...
I'll be able to continue playing with my map ;)
