### ISSUE TITLE
how to convert wkt to geojson?

### ISSUE THREAD

**Issue by liucaidong** [Turfjs/turf#2057]
the latest version of turf, could we consider this utility to be added to our lib?

**Comment by chrispahm** [comment]
Hey @liucaidong,

in case you're just looking for a library capable of converting WKT to GeoJSON, there are a few options available:
- [wellknown](https://github.com/mapbox/wellknown#parsewkt), released by Mapbox (the company behind the first versions of turf.js)
- [wicket](https://github.com/arthur-e/Wicket)

Here's a small notebook demonstrating how to use the wellknown library:
https://observablehq.com/@chrispahm/parse-well-known-text-wkt-into-geojson

With regards to your request adding this feature to turf: To the best of my knowledge, converting between geometry formats is generally not in the scope of the turf.js library. Therefore I'd propose that you just import any of the above libraries into your project in addition to turf.
Does this answer your question?

**Comment by rowanwins** [comment]
Hi @liucaidong

As @chrispahm says there are plenty of other libs out there for doing this. Turf is not a library for conversion of data formats so we're not looking at adding functionality along those lines.

Thanks

**Comment by liucaidong** [comment]
@chrispahm @rowanwins Thanks a lot, you guys really did me a big favor!
