### ISSUE TITLE
Function not found: jslibs.turf.ST_BUFFER

### ISSUE THREAD

**Issue by cvargas-geo** [Turfjs/turf#2058]
Hello can someone help me with this?
I am executing a query in BigQuery, but this is not working, I get the following error:

Function not found: jslibs.turf.ST_BUFFER at [2: 3]

But this line works perfectly:
SELECT jslibs.turf.ST_BUFFER (ST_GEOGPOINT (-33.2187979, -70.6843369), 1000, 'meters', 10) AS geo;
 

 [`carto-spatial-extension/issues/46`](https://github.com/CartoDB/carto-spatial-extension/issues/46)

**Comment by JamesLMilner** [comment]
Unfortunately this issue needs a little bit more information such as which version you're using, which actual Turf methods are being called and what the Turf error stack trace looks like. Realistically this might be a bit out of our scope to resolve as it seems to be being called in a SQL Query. `ST_BUFFER` isn't currently a method on turf so I'm a bit confused about what is happening there? I will close this issue, but if there is a more detailed report over what is broken in turf that needs fixing then feel free to reopen a new issue addressing the concern.
