### ISSUE TITLE
Ability to split/slice a geometry by another geometry

### ISSUE THREAD

**Issue by jumpinjackie** [Turfjs/turf#206]
It would be nice to have an API in turf.js that allows you to split a given geometry by another geometry.

Basically, a turf.js implementation of ST_Split in PostGIS: http://postgis.net/docs/ST_Split.html

**Comment by morganherlocker** [comment]
Awesome idea @jumpinjackie! We just added [line-slice](https://github.com/Turfjs/turf-line-slice), which allows you to slice a linestring by 2 points along the line. 

The concept of slicing a polygon by a linestring sounds really cool too. Do you have a use case in mind? The PostGIS docs are unclear on how this would be used in real world applications, but we like to provide a few examples in the documentation of Turf modules. Ideas?

**Comment by jumpinjackie** [comment]
In our case, we have a set of boundary polygons overlaid on a map. We'd like the user to be able to select a polygon, trace a "blade" line string over it to slice that polygon up along the traced line. 

This would be an easy intuitive way of dividing up any polygon-based spatial data (eg. Parcel/Electoral boundaries)

Current workaround would be AJAX request to some web service with the polygon and traced line string and let PostGIS do its ST_Split magic there and return the split geometries back to the client. It would be much better if we can do that all client-side.

**Comment by jczaplew** [comment]
I have a very similar use case to @jumpinjackie, and would also love this functionality. 

Another example use case might be for altering building footprints in OSM. Often times buildings that touch (or almost touch) are initially drawn as one large polygon. It'd be useful to draw a line through these footprints to separate the single polygon into many, which, in the case of touching buildings, would ensure that there is not a gap or overlap between them (i.e. topology is maintained).

**Comment by franckl** [comment]
I have a collection of geojson multi-polygons crossing the antemeridian (satellite network coverage, continent sized polygons), their coordinates go above +180 or -180 to represent them on the map via mapbox.js. I would need to cut them in half at the dateline and convert them to epsg:4326 in order to perform intersect operations on postgis/mongodb database.

It would be great if the turf version of ST_split could accept coordinates outside the -180,180 range

**Comment by tchannel** [comment]
> In our case, we have a set of boundary polygons overlaid on a map. We'd like the user to be able to select a polygon, trace a "blade" line string over it to slice that polygon up along the traced line.

@jumpinjackie this is done in Turfjs/turf-cut, although this doesn't let you cut by arbitrary geometry

**Comment by alperdincer** [comment]
How can we add turf-cut module to current minified JS file. Is there any documentation to compile a new minified JS file?

**Comment by morganherlocker** [comment]
In its current form, turf-cut is not robust enough to be an officially supported turf module. It has not been published to npm and has zero releases. To get it off the ground, it needs:

1. a proper cut algorithm implementation (it's [a hack](https://github.com/Turfjs/turf-cut/blob/master/index.js#L24) at the moment)
2. tests
3. performance benchmarks
4. [style](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#code-style) clean up

@alperdincer if you are looking for a one-off temporary fix, you can clone the repo and run [browserify](http://browserify.org/) with the standalone flag to create a clientside js file.

**Comment by alperdincer** [comment]
Thanks @morganherlocker I created the client side js file with turf-cut support to test it in my apps.

**Comment by osro** [comment]
Any idea what that proper cut algorithm would be?
I'm in a need to cut polygons with a polyline and the turf-cut's buffered "hack" isn't an option as it breaks the source topology.

**Comment by rowanwins** [comment]
Gday @morganherlocker & @DenisCarriere 

I came across the PolyK the other day that has [polygon slicing](http://polyk.ivank.net/?p=demos&d=slice).

I've had a quick look and got it working with geojson. Bundled turf cut with polyK would result in roughly ~30kb. 

The only downside I can see is that the line has to be a single straightline, eg can't have more than two coord pairs. Not ideal but at least it's something.

Are you interested in seeing it in a pull request?

Cheers
R

**Comment by DenisCarriere** [comment]
Polygon slicing would be a handy module.

`@turf/slice`

PolyK's license is MIT and written in ES5, don't see any issues having that as a dependency.

https://github.com/MartyWallace/PolyK

**Comment by osro** [comment]
I actually managed to make this cut with any kind of polyline and it preserves the topology of the source. It uses JSTS (which is already part of the turfjs?)

https://github.com/focusnet/fi.simosol.focus.map/blob/master/EditToolbar.Split.js#L243

**Comment by rowanwins** [comment]
Hi @osro thanks for the information, we're actually trying to remove the jsts dependency as it as a lot of overhead to the codebase so I don't think we're keen to introduce it for new modules of we can avoid it.

Cheers

**Comment by rowanwins** [comment]
Closing on favour of #580 thanks to some great work by @DenisCarriere
