### ISSUE TITLE
[@turf/clean-coords] Polygons being mutated by cleanCoords

### ISSUE THREAD

**Issue by hally9k** [Turfjs/turf#2062]
I am experiencing some mutation when processing polygons with `@turf/clean-coords`.

Pre cleaning: https://gist.github.com/hally9k/468f7c8933ffdc7485959a7384bac0fd
Post cleaning: https://gist.github.com/hally9k/efde55bce74b3e62eb44c28324779236

Notice the split down the middle, more visible in this screen shot:

<img width="3000" alt="Screen Shot 2021-04-01 at 4 08 04 PM" src="https://user-images.githubusercontent.com/3803536/113238532-757a4900-9305-11eb-81e0-fb5d65e134a9.png">

I reproduced with a simple node script to make sure nothing else was at play:

```
const fs = require('fs')
const cleanCoords = require('@turf/clean-coords')
const { featureCollection } = require('@turf/helpers')

const preClreanedString = fs.readFileSync('./pre-clean.json')

const preCleaned = JSON.parse(preClreanedString)

const cleanedFeatures = preCleaned.features.map(cleanCoords)

const cleanedFeatureCollection = featureCollection(cleanedFeatures)

fs.writeFileSync(
  './post-clean.json',
  JSON.stringify(cleanedFeatureCollection, null, 2)
)
```

I'm using `@turf/turf@5.1.6` (Due to some friction with the typescript types in the latest version)

Is this some projection handling I've messed up or something? Any and all help super welcome.

**Comment by rowanwins** [comment]
Hi @hally9k ,

Apologies for the slow reply. I couldn't replicate with v6.4.0

````
import * as turf from '@turf/turf';
import test from 'tape';

test('timing test', function (t) {
  var line = turf.lineString([[0, 0], [0, 2], [0, 5], [0, 8], [0, 8], [0, 10]]);
  const preCleaned = JSON.parse(JSON.stringify(line))
  const cleanedFeatures = turf.cleanCoords(line)
  t.deepEqual(preCleaned, line)
  t.end()
});
````

Do also note that there is a `mutate` option that defaults to false.

Hope that helps
Rowan

**Comment by JamesLMilner** [comment]
I will close this as there has been no follow up in a month. Feel free to open up if this can be replicated with `6.4.0`. Thanks!

**Comment by hally9k** [comment]
Cool, will get back to this relatively soon and reopen with a reproduction
if it’s not fixed.
