### ISSUE TITLE
ERROR: node_modules/@turf/center-median/dist/js/index.d.ts:59:29 - error TS2304: Cannot find name 'Position'.

### ISSUE THREAD

**Issue by Michel00291182** [Turfjs/turf#2064]
Hello,

I currently have upgraded my project to Angular 11 (11.2.7) that is using typescript 4.1.5, i found out that there is a bug in one of your typescript definition files.
i now use latest release of TurfJs 6.3.0

if i try to compile my project i am getting a compile error like this;

![image](https://user-images.githubusercontent.com/5758829/113429873-80061280-93d9-11eb-93c6-4b5abd1bf8ab.png)

![image](https://user-images.githubusercontent.com/5758829/113430081-d83d1480-93d9-11eb-828f-2d955ffde7f0.png)

For nou a can patch it with patch-package, but i will be very pleased if this can be resolved, i want to continue
to use your library i think this is a really awesome project!

**Comment by viestat** [comment]
Relates to https://github.com/Turfjs/turf/issues/2017

**Comment by JamesLMilner** [comment]
So to my understanding this is actually fixed, just hasn't been released yet? https://github.com/Turfjs/turf/pull/2044

**Comment by ldllidonglin** [comment]
> So to my understanding this is actually fixed, just hasn't been released yet? #2044

@Seairth hi, when will release a new version to fixed this issue

**Comment by Seairth** [comment]
> > So to my understanding this is actually fixed, just hasn't been released yet? #2044
> 
> @Seairth hi, when will release a new version to fixed this issue

I don't know. :smile:  I only submitted the fix. Maybe @mfedderly can answer that one.

**Comment by rowanwins** [comment]
This should've been resolved with the release of v6.4.0

**Comment by Michel00291182** [comment]
Yes thanks for resolving the issue! :) 👍
