### ISSUE TITLE
Consider removing "releases" section with ancient release

### ISSUE THREAD

**Issue by matkoniecz** [Turfjs/turf#2066]
Your github page ( https://github.com/Turfjs/turf ) has "releases" section with incredibly old release 

> released this on Jun 17, 2016 · 2536 commits to master since this release 

Note that you can hide this section in repository settings, also empty packages section may be worth removing

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)

I am not making a PR as it is defined in proprietary github settings, not in a git repository - and I have no rights to modify repo settings.

**Comment by matkoniecz** [comment]
wait, https://github.com/Turfjs/turf/tree/master/releases also has no recent releases

what is going on? No releases in last 3 years?

**Comment by rowanwins** [comment]
Hmm i'm not sure how Github is populating that little section on the main repo page
As you can see there have be many more releases
https://github.com/Turfjs/turf/releases
 
@mfedderly or @JamesLMilner do you have any thoughts on whether we should continuing populating the `/releases` folder or just focus on the `CHANGELOG.md` ?

**Comment by matkoniecz** [comment]
> Hmm i'm not sure how Github is populating that little section on the main repo page

it appears me that it lists things tagged in git ( https://git-scm.com/book/en/v2/Git-Basics-Tagging ) though not sure is it including all tags or only what was detected as a release (`v` prefix?)

**Comment by mfedderly** [comment]
I don't really have any opinion on what we use to track the changes, just that we do so. I don't have full admin access to this repo so I can't really mess with these settings.

**Comment by rowanwins** [comment]
I've readded this. Basically I added some notes to the tagged release and it seemed to correctly appear.
