### ISSUE TITLE
Obtaining not minified version

### ISSUE THREAD

**Issue by matkoniecz** [Turfjs/turf#2067]
What is the best way to obtain not minified version? For some reason some geometries trigger crash in turf and debugging that with minified code is quite annoying

Minified version is easy to obtain ( https://github.com/Turfjs/turf#in-browser ) so thanks for that!

**Comment by rowanwins** [comment]
The full range of files available via jsdelivr can be found at 
https://www.jsdelivr.com/package/npm/@turf/turf

In this case you're probably looking for
https://cdn.jsdelivr.net/npm/@turf/turf@6/dist/js/index.js

**Comment by matkoniecz** [comment]
@rowanwins Not really, I am looking for a single file that can be imported on html page, but not minified.

 https://cdn.jsdelivr.net/npm/@turf/turf@6/dist/js/index.js is just a header file.

**Comment by matkoniecz** [comment]
@stebogit It is minified. I am looking for way to be able to import JS code in browser that would be readable while debugging/grepping.

So, it seems that it would need to be 

(1) consolidated into one file or maybe importing next ones in some browser-friendly way
(2) not minified

**Comment by stebogit** [comment]
I think your best option is to create your own non-minified build from the project repo.
