### ISSUE TITLE
lineOverlap fails to find multiple overlaps on one segment

### ISSUE THREAD

**Issue by nasmuris** [Turfjs/turf#2068]
if line1 overlaps with line2 multiple times on only one line2's segment, lineOverlap detects only the first overlap, but lineIntersect detects the intersects properly 
```
const l1 = lineString([[0, 1], [1, 1], [1, 0], [2, 0], [2, 1], [3, 1], [3, 0], [4, 0], [4, 1], [4,0]]);
const l2 = lineString([[0, 0], [6, 0]]);
const overlap = lineOverlap(l1,l2);
L.geoJson(overlap).addTo(map);
L.geoJson(lineIntersect(l1,l2)).addTo(map);
```
<img width="155" alt="Screenshot 2021-04-03 at 19 24 04" src="https://user-images.githubusercontent.com/22944924/113486268-29203c00-94b2-11eb-91bf-c6c7fe0c5ba6.png">
when calling lineIntersect with reverted order of lines, it works properply too:

```
const overlap = lineOverlap(l2,l1);
L.geoJson(overlap).addTo(map);
```
<img width="123" alt="Screenshot 2021-04-03 at 19 25 48" src="https://user-images.githubusercontent.com/22944924/113486323-6684c980-94b2-11eb-93ff-19563e667021.png">

```
"@turf/line-overlap": "^6.3.0",
```
[jsfiddle](http://jsfiddle.net/xuszkpqb/)

**Comment by patrickbrett** [comment]
@nasmuris created a PR for this: #2134
