### ISSUE TITLE
[@turf/intersect] Intersection with MultiPolygon returns null

### ISSUE THREAD

**Issue by lrgongora** [Turfjs/turf#2069]
Please provide the following when reporting an issue:

- [x] Turf version: 6.0.0
- [x] GeoJSON data: https://gist.github.com/lrgongora/dbfa68d99f1483f1003476a579c61b39
- [x] Snippet of source code: `const intersect = turf.intersect(polygon, multiPolygon)`

Hello!

I'm using turf-intersect to find the intersection between a Polygon and a MultiPolygon and I ran into an issue where the return is always null. According to the [documentation](http://turfjs.org/docs/#intersect), this method supports MultiPolygon. I checked the source code and realized that this piece of code was added while ago to handle a different issue but seems to be the cause of this problem:

**File**: /@turf/intersect/main.js
**Lines**: 52-53

```
    // Return null if geometry is too narrow in coordinate precision
    // fixes topology errors with JSTS
    // https://github.com/Turfjs/turf/issues/463
    // https://github.com/Turfjs/turf/pull/1004
    if (cleanCoords(truncate(geom2, {precision: 4})).coordinates[0].length < 4) return null;
    if (cleanCoords(truncate(geom1, {precision: 4})).coordinates[0].length < 4) return null;
```

The example MultiPolygon I provided in the gist consists of two polygons. This logic seems to be intended to check the number of points, but it's instead comparing against the number of polygons in the case of a MultiPolygon. Is this correct or am I missing something?

Thank you in advance!

**Comment by rowanwins** [comment]
Resolved since v6.3.0
