### ISSUE TITLE
Question: Get Ellipse Major/Minor and Circle Radius?

### ISSUE THREAD

**Issue by jfuehner** [Turfjs/turf#2073]
Given a GeoJSON polygon `feature` does turf offer functions to get the major/minor axes of an ellipse or the radius of a circle?

Looking at the turf docs I didn't see available functions for this... Unless I missed them.

**Comment by stebogit** [comment]
It doesn't

**Comment by jfuehner** [comment]
@stebogit great 😔! Would you happen to know if any libraries that can?

**Comment by stebogit** [comment]
Nope, sorry
