### ISSUE TITLE
Self-intersection linestring's buffer is not exactly？

### ISSUE THREAD

**Issue by wtusmchen** [Turfjs/turf#2075]
Please provide the following when reporting an issue:

turf 6.3.0
let buffered = turf.buffer(fea, 100, {units:'kilometers'});

![0001](https://user-images.githubusercontent.com/12149282/116022885-ad16af80-a67d-11eb-9ea8-6e38b71991a7.png)

- [ ] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by smallsaucepan** [comment]
Sounds like this was a projection issue, and no updates since, so will consider resolved.
