### ISSUE TITLE
Global squaregrid

### ISSUE THREAD

**Issue by stollc** [Turfjs/turf#2079]
Hi,
Im trying to create a square grid that covers the entire map by using https://turfjs.org/docs/#squareGrid

The default example works great, but if i expand the bbox to `[-180, -90, 180, 90]` it returns an empty feature set.
This is my code:  

```javascript
var bbox = [-180, -90, 180, 90];  
var cellSide = 1;  
var options = { units: "degrees" };  
var squareGrid = turf.squareGrid(bbox, cellSide, options);  
```

Is there a bbox limit or am i doing something wrong?

**Comment by rowanwins** [comment]
Fix underway in https://github.com/Turfjs/turf/pull/2105
