### ISSUE TITLE
Named export 'merge' not found. - related to topojson dependency

### ISSUE THREAD

**Issue by impleotv** [Turfjs/turf#2083]
Hi all.

I've moved from turf 5.1.6 to 6.3.0 and have this issue now.
file:///home/alexc/Work/myserver/node_modules/@turf/concave/dist/es/lib/turf-polygon-dissolve.js:5
import { merge, topology } from "topojson";
         ^^^^^
SyntaxError: Named export 'merge' not found. The requested module 'topojson' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'topojson';
const { merge, topology } = pkg;

I'm not using this module directly and have no idea how to solve this.
Any help?

Thanks,

Alex

**Comment by lmdc45** [comment]
I have same issue when importing in nodejs via
`import turf from '@turf/turf';`

Noting my package.json include 
` "type": "module",`

not sure if this is related

stuck with 5.1.6 for now

**Comment by Bobvantpadje** [comment]
+ 1

**Comment by rowanwins** [comment]
v6.4.0 is now released which should resolve this issue

**Comment by lmdc45** [comment]
Thanks.
What is the correct way to import the all turf library? use to 'import turf from '@turf/turf'; but seems not good anymore with v6.4.0

import turf from '@turf/turf';
       ^^^^
SyntaxError: The requested module '@turf/turf' does not provide an export named 'default'

**Comment by rowanwins** [comment]
You can do something like
````
import * as turf from '@turf/turf';
````

**Comment by lmdc45** [comment]
yes after changing all import with
`git grep -l "import turf" | xargs sed -i "s/import turf/import \* as turf/g"`
works ok again.

I am just noting I could use turf.intersect on polygon/multilinestring with v5.1.6, not working properly any more with v6.4.0. I might just keep turf.intersect_v5 for this
All other test are ok

Thanks
