### ISSUE TITLE
Willing to help

### ISSUE THREAD

**Issue by micaminoff** [Turfjs/turf#2088]
Hey, if any maintainers or contributors see this, I'd like to help this project out. I develop a product that partially relies on this library. I'm fairly well versed in technical writing, project management and of course programming (mainly typescript). So if anyone wants to reach out with hints of how and where to get started I'd be very happy.

I'm thinking things like working on more TS support, tackling the myriad open issues, writing more substantial tests, updating contribution guidelines and maybe even feature development - but mostly I'm interested in the not-so-down-and-dirty geospatial work. I do enough of that as a consumer of the library.

**Comment by rowanwins** [comment]
Hi @micaminoff ,

Thanks for the offer of help. @mfedderly did a ton of work last year getting most of the pieces back up and running into a functional state but there is still plenty to help out on as you've noticed.

If you'd like to put in a some PR's around any of those things tag myself or @mfedderly and we'll try and get a review done. I tend to do more of the spatial algorithm stuff and @mfedderly has been doing more of the packaging & TS stuff.

Cheers
Rowan
