### ISSUE TITLE
Documenting ES6 imports for modules in examples

### ISSUE THREAD

**Issue by sirmspencer** [Turfjs/turf#2091]
The example here uses the full turf package version of length. https://www.npmjs.com/package/@turf/length
Here is one possible correct example

```
import turfLength from "@turf/length";

const lineString = {
  type: "Feature",
  geometry: {
    type: "LineString",
    coordinates: [[115, -32], [131, -22], [143, -25], [150, -34]]
  }
};
const length = turfLength(line, {units: 'miles'});
```

**Comment by rowanwins** [comment]
Hi @sirmspencer 

All our examples using the `turf.` syntax rather than an individual module. 

Working out how to publish docs which cater for both usage patterns requires a bit of thought...

Cheers
Rowan

**Comment by smallsaucepan** [comment]
For the sake of the examples both approaches do still call the same code, so will close this.
