### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by JamesLMilner** [Turfjs/turf#2100]
travis-ci.org is shutting down as per https://blog.travis-ci.com/2021-05-07-orgshutdown . We should migrate turf and the turfjs organisational repositories to travis-ci.com. Long term we should probably also have a discussion around if this is still the right CI provider for us.

Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

**Comment by matkoniecz** [comment]
I heard that new Travis puts heavy limits, making it barely usable for OSS. See https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567

See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing - using Travis as OSS will require case-by-case permission.

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

> When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:

**Comment by rowanwins** [comment]
Hi @matkoniecz

Yeah we're thinking we'll move away from travis hopefully in the near future. We've flagged investigating CircleCI or Github Actions, and we can allocate some of our OpenCollective funds towards that if required.

**Comment by JamesLMilner** [comment]
Indeed CircleCI and GH Actions are on the list to consider - glad we could get this sorted temporarily for now though!
