### ISSUE TITLE
Bezier Spline rendering a straight line instead of a bendy one

### ISSUE THREAD

**Issue by crevulus** [Turfjs/turf#2101]
- [x] "@turf/turf": "^6.3.0"
- [x] https://gist.github.com/crevulus/8ef91b337db85073b070900a75740a42
- [x]
`const line = turf.lineString([
  [-76.091308, 18.427501],
  [-60.695556, 18.729501],
]);

const curved = turf.bezierSpline(line, { sharpness: 0.5 });`

As far as I'm aware, this should output a smooth curved line, right?

But as you can see from the gist, it's straight as an arrow. The lat values don't seem to wildly change, like you'd expect.

`Is this because bezierSpline` doesn't work well when there's only two coordinates? Is there an alternative?

**Comment by rowanwins** [comment]
Hi @crevulus

As far as I know you need more than 2 coordinates to generate a bezier spline. If you're trying to generate a bendy line (for lack of a better term) just for visual effect you might also want to consider [@turf/greatCircle](http://turfjs.org/docs/#greatCircle)

Hope that helps

**Comment by crevulus** [comment]
Thanks for your response. I did try out `greatCircle`, but the curve was disappointingly shallow. At the moment I'm going through the suggestions on this thread: https://github.com/Turfjs/turf/issues/1218

Trying to follow your suggestion from Jan 9 2018.

My suggestion for this package would be to include a radius/offset degrees in `greatCircle` so we can shape the arc.

**Comment by rowanwins** [comment]
A great circle is actually something quite specific so for short distances it won't generate much curve, we can't really add a radius/offset parameter. But glad you've found another option :)
