### ISSUE TITLE
turf-units

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#212]
Internal module for unit conversion. This could be used all over the place for easily supporting many unit types. 

Should support:

- feet
- meters
- miles
- kilometers
- [nautical miles](http://en.wikipedia.org/wiki/Nautical_mile)?

```js

// roughly
  var R;
  switch(units){
    case 'miles':
      R = 3960;
      break;
    case 'kilometers':
      R = 6373;
      break;
    case 'degrees':
      R = 57.2957795;
      break;
    case 'radians':
      R = 1;
      break;
    case undefined:
      R = 6373;
      break;
    default:
      throw new Error('unknown option given to "units"');
  }
```

**Comment by gendronb** [comment]
+1 for Nautical miles

**Comment by tmcw** [comment]
Done in https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js#L269
