### ISSUE TITLE
Isolines ignores first break value

### ISSUE THREAD

**Issue by warrenwyf** [Turfjs/turf#2129]
Please provide the following when reporting an issue:

- [ 6.3.0] The version of Turf you are using, and any other relevant versions.

Just use the sample code like this:

``` javascript
import * as turf from '@turf/turf';

var extent = [0, 30, 20, 50];
var cellWidth = 100;
var pointGrid = turf.pointGrid(extent, cellWidth, { units: 'miles' });

for (var i = 0; i < pointGrid.features.length; i++) {
  pointGrid.features[i].properties.temperature = Math.random() * 10;
}
var breaks = [5, 10];

var lines = turf.isolines(pointGrid, breaks, { zProperty: 'temperature' });
console.log(JSON.stringify(lines.features));
```

Then we get the result, notice the lines with break value '5' are not generated.

``` json
[{"type":"Feature","properties":{"temperature":10},"geometry":{"type":"MultiLineString","coordinates":[]}}]
```

And if the breaks are set as [0, 5, 10], the result will contain lines with break value '5', but lost lines with break value '0'. In a word, the isolines function seems lost the first break lines.

**Comment by stebogit** [comment]
It indeed does, good catch @warrenwyf 
[The code](https://github.com/Turfjs/turf/blob/master/packages/turf-isolines/index.js#L92) simply ignores the first break. 🤦🏻 
It must have been a copy/paste oversight from the isobands code (probably my bad). I'm really surprised it never came up before, but yeah even the tests confirm this behavior. 

As a quick workaround it looks like you can just duplicate the first `break` value and it works as expected:
```js
var breaks = [5, 5, 10];
var lines = turf.isolines(pointGrid, breaks, { zProperty: 'temperature' });
```
