### ISSUE TITLE
turf-regular-grid

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#213]
polygon regular grid - I think this would more specifically be a cartesian grid, but that name might be overloaded in geo-land. http://en.wikipedia.org/wiki/Regular_grid http://en.wikipedia.org/wiki/Cartesian_coordinate_system

The idea here though is turf-hex, but for squares. This should attempt to be geodesic, but we will see how the algorithm shapes up.

**Comment by vlasvlasvlas** [comment]
geohash36 may help here:

http://www.pubnub.com/blog/wp-content/uploads/2014/05/ProximityChat1.jpg

http://en.wikipedia.org/wiki/Geohash-36

**Comment by morganherlocker** [comment]
https://github.com/Turfjs/turf-square-grid

**Comment by vlasvlasvlas** [comment]
great!

**Comment by tchannel** [comment]
@morganherlocker I'm closing this, since turfjs/turf-square-grid exists now. Let me know if there's anything more you think we should capture here.
