### ISSUE TITLE
squareGrid creates rectangles

### ISSUE THREAD

**Issue by paligrudic** [Turfjs/turf#2136]
Hi,
I'm trying to create a square grid using https://turfjs.org/docs/#squareGrid, but instead of squares, it returns rectangles. This is how it looks like: 

![222](https://user-images.githubusercontent.com/75303934/123605532-3bcdb700-d7fc-11eb-9119-ce2d2006b1eb.png)

When I try to decrease cellSide the rectangles become narrower
![555](https://user-images.githubusercontent.com/75303934/123605770-7cc5cb80-d7fc-11eb-97f1-f3be3c03f341.png)

` 
        var coordinates =    [[
        [ 9.628698847753714, -82.659521999370077 ],
        [ 9.628698847753714, -82.654521999370077 ],
        [ 9.509698847753714, -82.579521999370077 ],    
        [ 9.509698847753714, -82.654521999370077 ],  
        [ 9.628698847753714, -82.659521999370077 ],
          ]] 
      var polygon = turf.polygon(coordinates);
      var bbox = turf.bbox(polygon);

      var cellSide = 0.3;
      var options = {units: 'kilometers'};
      var grid = turf.squareGrid(bbox, cellSide,options);`

**Comment by twelch** [comment]
@paligrudic, what version of Turf are you running?  Are you sure your code snippet matches your screenshot?  When I paste it into the Turf sandbox (running latest 6.4.0) I get what looks like squares, and they are in Antarctica, which I suspect there are no green fields like in your screenshot.  Can you try the latest version of Turf?

[Turf Sandbox](https://turf-sandbox.netlify.app/)
```
var coordinates = [[
[ 9.628698847753714, -82.659521999370077 ],
[ 9.628698847753714, -82.654521999370077 ],
[ 9.509698847753714, -82.579521999370077 ],
[ 9.509698847753714, -82.654521999370077 ],
[ 9.628698847753714, -82.659521999370077 ],
]]
var polygon = turf.polygon(coordinates);
var bbox = turf.bbox(polygon);

  var cellSide = 0.3;
  var options = {units: 'kilometers'};
  var grid = turf.squareGrid(bbox, cellSide,options);

console.log(JSON.stringify(grid))

return grid;
```

![image](https://user-images.githubusercontent.com/81816/123863053-f08bd500-d8dd-11eb-81bc-556db16475d2.png)

**Comment by JamesLMilner** [comment]
As there's been no follow up I think it's safe to assume this issue is resolved.

**Comment by twelch** [comment]
See related issue with possible workaround here - https://github.com/Turfjs/turf/issues/2638.  In short, the behavior of this function changed around July/August 2021
