### ISSUE TITLE
Regarding what is the association between 'bboxpolygon' and 'resolution' in turf.shortestpath?

### ISSUE THREAD

**Issue by 361so** [Turfjs/turf#2139]
```
var start = [115.61943703166588,27.397702275786777];
var end = [115.53830302320434,26.999855230270786];
var options = {
	obstacles: turf.bboxPolygon([115.47868651015011, 27.068766868610012, 115.69489045175858, 27.290181181224497]),
	resolution:50
};
turf.shortestPath(start, end, options);
```
After testing, the following error will be reported when resolution > = 50.87442：
```
Uncaught TypeError: Cannot read property 'undefined' of undefined
    at Object.t.shortestPath (turf.min.js:96)
    at <anonymous>:7:6
```
But if you increase the value range of "bboxpolygon", for example, set it to：
```
[115.47868651015011, 27.068766868610012, 117.69489045175858, 29.290181181224497]
```
，then the value of "" resolution "" can be increased at a point without reporting errors.
I would like to consult what is the relation between 'bboxpolygon' and 'resolution' in turf.shortestpath?

**Comment by JamesLMilner** [comment]
resolution for `shortestPath` is defined by "the distance between matrix points on which the path will be calculated". This determined by the `units` property in the options, which defaults to kilometers. Larger resolution results in a less granular grid, smaller resolution will resolution will produce a less granular grid.

**Comment by 361so** [comment]
I know what you said. Maybe I didn't make it clear。
I mean, his error only appears on bboxpolygon. If it's changed to polygon, it's good。
