### ISSUE TITLE
Get linestring rotation to place obj facing the correct way?

### ISSUE THREAD

**Issue by Philip2909** [Turfjs/turf#2140]
Hello! 

I have an object on a 3d map (OSMB), and then I have the coordinates for a line, I need to take this line and calculate its 'rotation' to be able to rotate it to be placed correctly. So the obj is facing the correct way like in real life, if that makes sence. 

Is this even possible to do (which I think because I have seen something simalar ones), if so, can I do it with turf? 

The linestring I am working with:
`{
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            13.183424171656954,
            55.718937767054136
          ],
          [
            13.18343414612173,
             55.7189389945484
          ]
        ]
      }
    }`

**Comment by JamesLMilner** [comment]
Hi @Philip2909 - you can use turf to rotate a given geometry by an angle like so:

```typescript
const linestring= { "type": "Feature", "properties": {}, "geometry": { "type": "LineString", "coordinates": [ [ 13.183424171656954, 55.718937767054136 ], [ 13.18343414612173, 55.7189389945484 ] ] } }
const angle = 10;
const rotatedLinestring = turf.transformRotate(linestring,  angle);
```

If you need to get it's initial bearing you can use [bearing](https://turfjs.org/docs/#bearing) and then also convert that to decimal degrees using [bearingToAzimuth](https://turfjs.org/docs/#bearingToAzimuth).

**Comment by Philip2909** [comment]
Hi James! 

It was the bearing and the bearingToAzimuth functions I was looking for, just didn't know what they were called, thanks for all the help! 

Best regards
Philip M
