### ISSUE TITLE
algorithm used in polygon union 

### ISSUE THREAD

**Issue by killerm250m** [Turfjs/turf#2145]
Hello, I want to port polygon union property but I can not find it in the library (I am new to GitHub).
Thanks.

**Comment by JamesLMilner** [comment]
turf union code is here:

https://github.com/Turfjs/turf/blob/5375941072b90d489389db22b43bfe809d5e451e/packages/turf-union/index.ts#L36

Which is based on `polygon-clipping` package:

https://github.com/mfogel/polygon-clipping/tree/master/src
