### ISSUE TITLE
Clarify bbox description

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#2147]
> Takes a set of features, calculates the bbox of all input features, and returns a bounding box.

This is a pretty messy description, given that bbox takes a single GeoJSON object, not a "set".

Suggest:

> Calculates the bounding box for any GeoJSON object, including FeatureCollection.

**Comment by rowanwins** [comment]
Yep nice rewording

**Comment by Aryan-Mohanty** [comment]
@rowanwins can I know where to find that document?  I would like to fix that, beginner, here!

**Comment by barbalex** [comment]
coming from the future (2024), why is the text still wrong? https://turfjs.org/docs/#bbox

I spent an hour debugging until I finally found out that the docs are wrong.
