### ISSUE TITLE
feature request: turf-filter with comparisons

### ISSUE THREAD

**Issue by thwllms** [Turfjs/turf#215]
Not sure if this is already in the works, but it would be nice to be able to filter using comparison statements ("year >= 1992", etc).  Although maybe the real solution would be "turf-sql-filter"? SQL selects are really useful in desktop GIS programs. Some kind of system for more complex filters would be great.

**Comment by tmcw** [comment]
Yep, definitely an interesting idea... we've got [feature-filter](https://github.com/mapbox/feature-filter) we could possibly use / adapt. Usually I'd be opposed to this sort of metaprogramming but it could open up some possibilities for fully declarative filtering in turf and json

**Comment by thwllms** [comment]
Hopefully there's a way to do this that isn't too clunky or weird. When I brought this up to @morganherlocker at the Fed User BBQ he mentioned a MongoDB-related thing which I've since forgotten the name of.

**Comment by AbelVM** [comment]
I positively know @JosephGF is working on an SQL query builder for TURF... stay tuned!

**Comment by tmcw** [comment]
Closing; turf-filter is removed from turf v3: [Array.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) is the new/better/more/flexible turf-filter.
