### ISSUE TITLE
[Question] How are docs generated?

### ISSUE THREAD

**Issue by Rubix982** [Turfjs/turf#2159]
I would like to ask about how is the documentation of https://turfjs.org/ generated?

**Comment by twelch** [comment]
@Rubix982 you'll find some info in the [CONTRIBUTING.md doc](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#documentation).  I'll leave this issue open to add a link to it from the main readme.

**Comment by twelch** [comment]
The code for publishing the docs is over here in turf-www and [there's a PR](https://github.com/Turfjs/turf-www/pull/174/files) to update those docs.  Again we could link it better.

**Comment by Rubix982** [comment]
Thank you, @twelch.
