### ISSUE TITLE
Turf center documentation not correct?

### ISSUE THREAD

**Issue by pixeliner** [Turfjs/turf#2161]
Hi,

I'm using @turf/center 5.1.5.

In the documentation it states the following: 'Takes a Feature or FeatureCollection and returns the absolute center point of all features.' while in the arguments it accepts a "GeoJSON" (which in turn can also be a geometry type).

Whether I use a Feature or Geometry with a type of Point, Polygon or MultiLineString, all of them return the following error: "Cannot read property 'lat' of null".

Am I missing something?

**Comment by stebogit** [comment]
@pixeliner posting the code causing you the issue, or a link to a jsfiddle or codesandbox or something like that, is always best to allow anyone to try help you out

**Comment by pixeliner** [comment]
@stebogit off-course, my bad :)

Here are a few examples of features I'm trying to center:

`
{"id":"ID","geometry":{"type":"MultiPolygon","coordinates":[[[[4.42402179710715,51.2580461359455],[4.42400620256689,51.258046049554],[4.42398105910555,51.2580446561072],[4.42384068012482,51.2581298838586],[4.42402214625489,51.2581299690263],[4.42402179710715,51.2580461359455]]]]},"type":"Feature","properties":{"name":"NAME"}}
`

`
{"id":"ID","geometry":{"type":"Point","coordinates":[4.4109511,51.2408122]},"properties":{"name":"NAME"}}
`

And here is the code I'm using to center them:
`leaflet.setView(turf.center(feature.geometry));` Here it doesn't matter whether I'm using feature or feature.geometry. Both of them don't work.

Using feature I get : "Uncaught Error: Unknown Geometry Type"
Using feature.geometry, I get: "Cannot read property 'lat' of null"

I get those errors for both, the Point and MultiPolygon feature.

**Comment by stebogit** [comment]
@pixeliner I don't see any error with any feature or geometry. I do agree though the documentation should say:
> Takes a {@link GeoJSON} object and returns the absolute center point of its feature(s).

_**Note**: the current/latest version is 6.5.0_

```js
const pt = {"type": "Feature", "id":"ID","geometry":{"type":"Point","coordinates":[4.42,51.2601]},"properties":{"name":"NAME"}};

const mp = {"id":"ID","geometry":{"type":"MultiPolygon","coordinates":[[[[4.42402179710715,51.2580461359455],[4.42400620256689,51.258046049554],[4.42398105910555,51.2580446561072],[4.42384068012482,51.2581298838586],[4.42402214625489,51.2581299690263],[4.42402179710715,51.2580461359455]]]]},"type":"Feature","properties":{"name":"NAME"}};

const l = {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[4.423415958881378,51.25818524689327],[4.423909485340118,51.257899891024]]}};

const py = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[4.423914849758148,51.258270853308645],[4.424266219139099,51.258082854696866],[4.42449688911438,51.25828260319636],[4.4242554903030396,51.258438708562345],[4.423914849758148,51.258270853308645]]]}};

return turf.featureCollection([
  turf.center(pt.geometry),
  turf.center(l.geometry),
  turf.center(mp.geometry),
  turf.center(py.geometry),
  turf.center(turf.featureCollection([pt, l, mp, py]))
]);

// {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[4.42,51.2601]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[4.423662722110748,51.258042568958636]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[4.423931413189855,51.25808731256675]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[4.424205869436264,51.2582607816296]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[4.42224844455719,51.258999945512]}}]}
```

![Screen Shot 2021-07-30 at 9 59 22 AM](https://user-images.githubusercontent.com/12717225/127686854-f1611793-0e06-49f1-aab0-a8c4ff06b4d8.png)

**Comment by stebogit** [comment]
@pixeliner a not on [your code](https://codesandbox.io/s/billowing-sun-hm0sp): the following is not a [valid GeoJSON](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1) object, for it misses the `type` property (that's causing the error in your script)
```js
const point = {
  id: "ID",
  geometry: { type: "Point", coordinates: [4.4109511, 51.2408122] },
  properties: { name: "NAME" }
};
```
Valid options would be 
```js
const pointGeometry = {
  type: "Point",
  coordinates: [4.4109511, 51.2408122],
};

const pointFeature = {
  id: "ID",
  type: "Feature",
  geometry: { type: "Point", coordinates: [4.4109511, 51.2408122] },
  properties: { name: "NAME" }
};
```
