### ISSUE TITLE
turf.centriod module: request GeometryCollection as an input

### ISSUE THREAD

**Issue by d3netxer** [Turfjs/turf#217]
The turf.centriod module works great, but it did not take my geojson as in input when it contained Geometry Collections. 

I got around this by re-creating my geojson to have FeatureCollections that contain one or more features inside. Then I loop through each FeatureCollection feeding it into the turf.centriod module.

**Comment by tmcw** [comment]
What version of turf or turf-centroid are you using? v1.4.0 should handle centroids of GeometryCollections correctly.

**Comment by tmcw** [comment]
Confirmed in tests that GeometryCollections work properly in turf-centroid. You'll need to update.

**Comment by d3netxer** [comment]
yes, I was using v1.3 You are one step ahead! Thanks @tmcw
