### ISSUE TITLE
Consider removing @turf/turf backwards compatible exports

### ISSUE THREAD

**Issue by mfedderly** [Turfjs/turf#2180]
I'd like to remove the following exported items from @turf/turf, which have been re-exported for backwards compatability.
https://github.com/Turfjs/turf/blob/master/packages/turf/index.mjs#L125-L147

If someone would like to make the argument that we should keep it, that's fine too, but if we're considering doing a bunch of breaks now would be a good time.

**Comment by rowanwins** [comment]
Yeah those renames have existed for several years by now so I reckon we can cull them
