### ISSUE TITLE
Include version in online docs

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#2189]
I'm not sure how the `turfjs.org` website is generated and updated, but it would be helpful if it included a version number to indicate what version the docs refer to. Sometimes it seems the docs don't cover something that's in the codebase, so it'd be helpful as a way of knowing if there's a problem with the docs (ie, something is missing) or it's just that the latest version hasn't been deployed.

**Comment by smallsaucepan** [comment]
Took a little while, though the version number is now shown on the website.
