### ISSUE TITLE
How to get the z-value from transformTranslate?

### ISSUE THREAD

**Issue by dreamworks** [Turfjs/turf#2190]
I use turf.transformTranslate with the zTranslation option, but the Z-Index component is missing in the results, see following example:
```javascript
var newPlaneLocation = turf.transformTranslate(
  point, 
  plane[DATA_INDEX.VELOCITY] / (iTick * 1000), 
  plane[DATA_INDEX.TRUE_TRACK], 
  { zTranslation: plane[DATA_INDEX.VERTICAL_RATE] / (iTick * 1000) }
);
```
newPlaneLocation contains lat,lon parameter, but no altitude.

How can this be achieved? Do I need to use another function?

**Comment by JamesLMilner** [comment]
@dreamworks does your input point have a third coordinate (altitude)? The z transformation operates directly on the coordinate: https://github.com/Turfjs/turf/blob/84110709afda447a686ccdf55724af6ca755c1f8/packages/turf-transform-translate/index.js#L66

**Comment by stebogit** [comment]
@dreamworks looks like this works, note the third coordinate of the points (`0` -> `12`):
```js
const p = turf.point([0, 0, 0]);
const p2 = turf.transformTranslate(p, 1000, 75, { zTranslation: 12 });
console.log(p, p2)
// {"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[0,0,0]}}
// {"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[8.689158008386698,2.327612377804366,12]}}
```

**Comment by dreamworks** [comment]
thx a lot! Great.I didn't add the 3rd coordinate on the point input...  One could argue, if the code should be changed into 
          "if (zTranslation || pointCoords.length === 3)"           
so "stupid" cases like mine would autoheal, but "autohealing" is always a two sided-knife :)

Thx a lot for the clarification.. Planes are flying as expected now..
