### ISSUE TITLE
A grid that accepts a polygon

### ISSUE THREAD

**Issue by xrmx** [Turfjs/turf#220]
Am replicating the walkability estimation applied to a whole italian region which is irregularly shaped. So i ended up doing this:

```
            var grid = turf.grid(polypiemonte.bbox_piemonte, 1000);
            // remove grid points outside the region shape
            grid = turf.featurecollection(grid.features.filter(function(f) {
                return turf.inside(f, polypiemonte.poly_piemonte);
            }));
```

Was wondering if it would be possible to do this in one pass avoiding creating a second collection to save some memory / cpu time.

**Comment by stebogit** [comment]
Implemented with PR #791

**Comment by xrmx** [comment]
Thanks!

**Comment by loaiabdalslam** [comment]
Hey , is That Avaliable RIght now for HexGrid ?

**Comment by stebogit** [comment]
I don't think so
