### ISSUE TITLE
Split a polygon using turfjs

### ISSUE THREAD

**Issue by Zubeyd55** [Turfjs/turf#2202]
I'm in a need to cut polygons with a line and the polygonslice  isn't working as it is not in npm, i was wondering if i can get help.

**Comment by stebogit** [comment]
@Zubeyd55 please include an example of what you already tried

**Comment by Zubeyd55** [comment]
@stebogit first I really want to thank you for your quick replay here is what I have tried so far.......I bundle turf/polygon-slice with web pack and tried it with angular project. 
`import { Component } from '@angular/core';

declare namespace turfSlice {
  function polygonSlice(polygon: any, linestring: any): any;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-first-project';
  constructor(){
    var polygon = {
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [0, 0],
            [0, 10],
            [10, 10],
            [10, 0],
            [0, 0]
        ]]
      }
    };
    var linestring =  {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [5, 15],
            [5, -15]
          ]
        }
      }
    turfSlice.polygonSlice(polygon, linestring);
  }
}`

it gives geometry type error even though I tried it with different polygon coordinates. 
![error](https://user-images.githubusercontent.com/39626504/133150802-3e36cb9f-0ea3-4bd8-9357-d8112f38745c.png)

**Comment by stebogit** [comment]
@Zubeyd55 what package are you using?
it looks like `@turf/polygon-slice` has not yet been released to production because apparently [it is still not robust enough](https://github.com/Turfjs/turf/issues/580#issuecomment-505196520).
So unfortunately I can't be of help much. Maybe [this repo](https://github.com/kdashivantha/turf-polygon-slice) can help you.

**Comment by Zubeyd55** [comment]
@stebogit ok thank you...is there any way to do that? I tried @turf/polygon-slice and turf-cut so far and both are not working.

**Comment by rowanwins** [comment]
@Zubeyd55 you may want to check out https://github.com/rowanwins/polygon-splitter
I'm hoping to bundle this into Turf when I get a chance

**Comment by Zubeyd55** [comment]
@rowanwins  Thanks, it works pretty good :).......can i use it with leafletdraw i want the split to be graphicaly

**Comment by JamesLMilner** [comment]
Since `polygon-splitter` resolves the issue for you and polygon splitting as a package is a known request which we hope to implement in the future, I think we can close this out for now. Thanks!
