### ISSUE TITLE
How can I intersect a line with a polygon, to get a new line? Undocumented breaking change some time since 4.6.0

### ISSUE THREAD

**Issue by tremby** [Turfjs/turf#2221]
I've had some production code using Turf 4.6.0 running for 3 years or so.

One thing it needs to do is intersect a (multi)line(string) with a (multi)polygon. The output it needs is a (multi)line(string).

Example input: the rectangle is a polygon, the bendy line is a linestring.

             \
              |
         +----+--------+
         |    |        |
         |     \       |
         |      \      |
         |       ------+---
         |             |
         +-------------+

Example output: the part of the line which intersected with the polygon.

              |
               \
                \
                 ------

The @turf/intersect function of 4.6.0 did exactly this. It could handle all sorts of geometries being passed in, and gave the lowest common denominator as output. See its old docstring: https://github.com/Turfjs/turf/blob/d050525a2f7cd509fe2f98fb7c60cca5ba7a6c2f/packages/turf-intersect/index.js#L10
My application has been working fine all this time.

I'm now upgrading dependencies.

There's nothing in the changelog about it at all but the latest version, 6.5.0, of the intersect function only allows (multi)polygons to be passed in. This is a feature I was relying on, and I now need to find another way to get the same output.

lineSplit *sort of* does what I want. I have to take extra steps, because it gives me many line segments and I only want the intersecting ones. The best I've come up with so far (I'm running this in https://turf-sandbox.netlify.app/) is this:

```js
const l = turf.lineString(
  [
    [-122.3116, 47.6623],
    [-122.31, 47.664],
    [-122.3052, 47.6650],
    [-122.3052, 47.664],
    [-122.3116, 47.661],
  ],
  {'stroke-width': 6, stroke: '#999'}
);
const poly = turf.polygon([[
    [-122.3104, 47.6627],
    [-122.3071, 47.6627],
    [-122.3071, 47.6644],
    [-122.3104, 47.6644],
    [-122.3104, 47.6627]
  ]],
  {stroke: '#0FF', fill: '#0FF', 'fill-opacity': 0.3, 'stroke-width': 6}
);

const split = turf.lineSplit(l, poly);
const intersecting = [];
turf.flattenEach(split, (f) => {
  if (turf.booleanContains(poly, f)) intersecting.push(f);
});

return turf.featureCollection([poly, l, ...intersecting]);
```

While not *awful* this is more complicated than it used to be, and it leaves me thinking I'm doing something wrong. Is there a better way?

(Side note: I haven't figured out how to turn an array of these line(string) features into a single multiline(string). I would have thought I could do it with union, but no, for some reason that only accepts polygons just like intersect now does.)

**Comment by tremby** [comment]
And as soon as I put the above into my application, thinking "it'll do for now", I find that booleanContains doesn't support a multipolygon, so the code has to get bigger again.

So now I have this:

```js
const l = turf.lineString(
  [
    [-122.3116, 47.6623],
    [-122.31, 47.664],
    [-122.3052, 47.6650],
    [-122.3052, 47.664],
    [-122.3116, 47.661],
  ],
  {'stroke-width': 6, stroke: '#999'}
);
const poly = turf.polygon([[
    [-122.3104, 47.6627],
    [-122.3071, 47.6627],
    [-122.3071, 47.6644],
    [-122.3104, 47.6644],
    [-122.3104, 47.6627]
  ]],
  {stroke: '#0FF', fill: '#0FF', 'fill-opacity': 0.3, 'stroke-width': 6}
);

const split = turf.lineSplit(l, poly);
const intersecting = [];
turf.flattenEach(split, (f) => {
  if (turf.booleanContains(poly, f)) intersecting.push(f);
});

return turf.featureCollection([poly, l, ...intersecting]);
```

**Comment by stebogit** [comment]
@tremby I'm not sure how/why the old code works with a LineString, since - as the docs say - the function expects two (Multi)Polygons as arguments, even in the past. Now though the arguments are validated thanks to TypeScript.
However I noticed the module originally depended on JSTS, which has been decided to (eventually) remove from any turf dependency. That's probably why the behavior, never actually intended, has changed for your case.

Now, I can think of two options in your case: use/copy the old code in your project (probably the easiest and more reliable solution), or use the code you just posted, I don't see anything wrong with it, although you can simplify it a bit.
To convert a set of lines into a multilinestring you can use the dedicated [helpers function](https://github.com/Turfjs/turf/tree/v4.6.1/packages/turf-helpers#multilinestring). 

```js
// ...

const split = turf.lineSplit(l, multipoly);
const intersecting = [];
turf.flattenEach(split, (f) => {
  turf.flattenEach(multipoly, (poly) => {
    if(turf.booleanContains(poly, f)) intersecting.push(turf.getCoords(f)) // <---
  });
});

const multiLine = turf.multiLineString(intersecting, {stroke: '#F00', 'stroke-width': 3}); // <---
return turf.featureCollection([multipoly, l, multiLine]); // <---
```

BTW, your solution would actually work great for a new module, or maybe even better to extend the existing `@turf/intersect` to accept a line and a polygon as inputs. Care to submit a PR for that? 😃

**Comment by tremby** [comment]
Thanks. It makes sense that it changed due to a subdependency change. I missed the fact that the args always asked for polygons. I guess I tried it with other geometries on a whim and was pleased to find it worked, those 3 years ago.

As far as I can tell the only simplification in your version of the code is removing the `contained` flag I was using. This means it doesn't short-circuit if one of the previous pieces of multipolygon contained the line segment, and so then in some cases it will be running `booleanContains` when it needn't, and in some cases it may even lead to duplicate lines in the output (if a multipolygon has polygons overlapping each other, perhaps).

It occurred to me yesterday that `flattenFilter` and `featureFilter` would be useful functions to go along with xEach and xReduce, and it occurs to me now that xSome would be handy in this particular case, and at that point why not complete the set, with xEvery and xReduceRight.

Thanks for pointing out how I can group a bunch of lines/linestrings into a multilinestring.

> BTW, your solution would actually work great for a new module, or maybe even better to extend the existing `@turf/intersect` to accept a line and a polygon as inputs. Care to submit a PR for that? 😃

Ah, with no time constraints, I would like that. However, this is just a short maintenance contract and sadly I don't think I could justify it at the moment.

**Comment by tremby** [comment]
To be clear, by the way, it would make logical and intuitive sense (at least to me) if the existing intersect function were to do more:

- if given polygons, function as it currently does, giving the overlapping areas
- if given polygons and lines, function as above in this ticket
- if given polygons and points, return the set of those points contained in the polygons
- if given lines, do exactly what `lineIntersect` currently does
- if given lines and points, return points found on the lines
- if given points, return the (multi)point where identical ones are found

The above is what I mean by returning the intersecting portions in the "lowest common denominator" geometry type, and I believe this is how it used to work with JSTS.
