### ISSUE TITLE
How to rotate static image in openlayers 6.9 using turf and imageExtent

### ISSUE THREAD

**Issue by carlosjpr-collab** [Turfjs/turf#2223]
I need to create and rotate a static image layer in openlayers 6.

The creation of static image is working using url and imageExtent and i can see the image inside the map.

```javascript
    new ImageLayer({
            source: new Static({
              url,
              imageExtent: [
                extent.west,
                extent.south,
                extent.east,
                extent.north
              ]
            })
```
Now, I need to rotate this image using [Turfjs][1] 

So i did this code that rotate using transformRotate from Turfjs:

```javascript
     const poly = bboxPolygon([
        extent.west,
        extent.south,
        extent.east,
        extent.north
      ])

      const rotatedPoly = transformRotate(poly, -extent.rotation, {})
  

 
      const leftBottom = JSON.parse(JSON.stringify(rotatedPoly.geometry.coordinates[0][0]))
      const rightBottom = JSON.parse(JSON.stringify(rotatedPoly.geometry.coordinates[0][1]))
      const rightTop = JSON.parse(JSON.stringify(rotatedPoly.geometry.coordinates[0][2]))
      const leftTop = JSON.parse(JSON.stringify(rotatedPoly.geometry.coordinates[0][3]))

      const bounds = [leftBottom, leftTop, rightTop, rightBottom]

      return new ImageLayer({
        source: new Static({
          url,
          imageExtent: bounds
        })
      })
```

The last block code is not working, i see nothing inside the map.

mes coordinates are in 'EPSG:4326' 

Any idea please?

  [1]: https://github.com/Turfjs

**Comment by stebogit** [comment]
@carlosjpr-collab would you mind set up an example jsfiddle or codesanbox where we can see some real data and see what's going on?

**Comment by JamesLMilner** [comment]
Because there hasn't been any feedback on this in two weeks I'm going to close. As @stebogit says it would be great to see a Codesandbox replicating the issue.
