### ISSUE TITLE
Issue in bbox-polygon, or limitation of GeoJSON?

### ISSUE THREAD

**Issue by kochis** [Turfjs/turf#2228]
package: `@turf/bbox-polygon: 6.5.0`

I'm running into an issue generating a specific bbox that spans a large area, which sort of leads me to believe this is probably more of a limitation of GeoJSON itself, or possibly some thing else.

The view in question is the following:
![image](https://user-images.githubusercontent.com/814934/143682377-1954e1d0-6a07-483d-896d-a8a9884b00bc.png)

Which gives the following SW and NE coordinates for bbox: `[158.56287805,4.68243354621358,4.226940549999991,63.12795266364328]`

You'll notice when viewing, the map is oriented around the points in the other direction (east -> west, instead of west -> east)
http://geojson.io/#id=gist:kochis/d7874ca44b30c5af7b03c4aa049490ff&map=2/20.0/0.0
![image](https://user-images.githubusercontent.com/814934/143682537-37f45aa0-588d-47bd-8a6c-9c62ecb9c15c.png)

So I guess my questions are:
* Is this an issue of crossing the prime meridian? (coordinate system resetting at 0?)
* Is there a way to specify the order / direction used when creating the bounding box?

**Comment by stebogit** [comment]
@kochis would you please add a snippet of the code generating the unexpected bbox so we can take a look at what exactly is going on?
I believe the GeoJSON specs require the coordinates order you mentioned, although I might be wrong. In that case I'd consider this a bug

**Comment by kochis** [comment]
From the original view, I am getting the sw & ne coordinates from google maps:
```js
const turfBboxPolygon = require('@turf/bbox-polygon');

const sw = map.bounds.getSouthWest(); // { lng: 158.56287805,  lat: 4.68243354621358 }
const ne = map.bounds.getNorthEast();  //  { lng: 4.226940549999991,  lat: 63.12795266364328 }
const polygon = turfBboxPolygon([sw.lng, sw.lat, ne.lng, ne.lat;
```
Which outputs the following polygon:
```
{"type":"Feature","bbox":[158.56287805,4.68243354621358,4.226940549999991,63.12795266364328],"properties":{},"geometry":{"type":"Polygon","coordinates":[[[158.56287805,4.68243354621358],[4.226940549999991,4.68243354621358],[4.226940549999991,63.12795266364328],[158.56287805,63.12795266364328],[158.56287805,4.68243354621358]]]}}
```

**Comment by kochis** [comment]
I also noticed on geojson.io if you draw the polygon for the bbox:
http://geojson.io/#id=gist:kochis/d7874ca44b30c5af7b03c4aa049490ff&map=2/34.0/247.3

![image](https://user-images.githubusercontent.com/814934/143683094-f3d820c0-a9f0-4249-ba05-ec2435312bbf.png)

it results in a polygon with the following coordinates:
```json
{
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [159.2578125,3.8642546157214084],
            [365.2734375,3.8642546157214084],
            [365.2734375,63.39152174400882],
            [159.2578125,63.39152174400882],
            [159.2578125,3.8642546157214084]
          ]
        ]
      }
    }
```

Here the position is `[365..., 63...]` instead of `[4..., 63...]`. 

Is `365` a valid longitude position?

**Comment by stebogit** [comment]
@kochis Yes, 365 (as well as -365 for example) is a valid longitude value in the web map which, as you certainly know, can horizontally display multiple/continuous/infinite earth projections:
![Screen Shot 2021-11-28 at 5 57 07 PM](https://user-images.githubusercontent.com/12717225/143797277-02486d74-fa35-48cc-80f2-a70863c2f2bc.png)

I see the issue though: you're expecting the green polygon instead bboxPolygon computes the red one. 
![Screen Shot 2021-11-28 at 6 09 40 PM](https://user-images.githubusercontent.com/12717225/143798120-f66c3c53-feb8-4f4b-a0fa-67fe160461e4.png)

However, as per GeoJSON specs, a [Bounding Box](https://datatracker.ietf.org/doc/html/rfc7946#section-5) should contain _"all axes of the most southwesterly point followed by all axes of the more northeasterly point"_, which is not what you provided to bboxPolygon. In fact the coordinates you provided to Turf are in the same "section" (longitude [0˚:360˚]) of the returned polygon, therefore the NE coords are not "more northeasterly" than the SW coords.
If you want to generate the polygon on the expected section (say longitude [90˚:450˚]) you need to "move" your coordinates in that section (see point `p`), therefore pass a valid bbox.

```js
const sw = {lng: 158.56287805, lat: 4.68243354621358};
const ne = {lng: 4.226940549999991, lat: 63.12795266364328};

const boxpolygon = turf.bboxPolygon([sw.lng, sw.lat, ne.lng, ne.lat], {properties: {stroke: 'red', fill: 'red'}});
console.log(JSON.stringify(boxpolygon));
// {"type":"Feature","bbox":[158.56287805,4.68243354621358,4.226940549999991,63.12795266364328],"properties":{"stroke":"red","fill":"red"},"geometry":{"type":"Polygon","coordinates":[[[158.56287805,4.68243354621358],[4.226940549999991,4.68243354621358],[4.226940549999991,63.12795266364328],[158.56287805,63.12795266364328],[158.56287805,4.68243354621358]]]}}

const pSW = turf.point([sw.lng, sw.lat], {"marker-color": "red", "marker-symbol": "s"});
const pNE = turf.point([ne.lng, ne.lat], {"marker-color": "blue","marker-symbol": "n"});

const p = turf.point([ne.lng + 360, ne.lat], {"marker-color": "green","marker-symbol": "p"});

const expected = turf.bboxPolygon([
  sw.lng, sw.lat,
  ...p.geometry.coordinates
], {properties: {stroke: 'green', fill: 'green'}});
console.log(JSON.stringify(expected));
// {"type":"Feature","properties":{"stroke":"green","fill":"green"},"geometry":{"type":"Polygon","coordinates":[[[158.56287805,4.68243354621358],[158.56287805,63.12795266364328],[364.22694055,63.12795266364328],[364.22694055,4.68243354621358],[158.56287805,4.68243354621358]]]}}
```
All in all I would not mark this as a bug, cause the alternative would probably be reject the invalid bbox input and throw an error.

**Comment by kochis** [comment]
Makes sense, thanks for looking into this!
