### ISSUE TITLE
Opposite of turf.along (aka turf.pointAt??)

### ISSUE THREAD

**Issue by gendronb** [Turfjs/turf#223]
Given a linestring and a point located somewhere along this line, return the distance from the beginning of the line.

**Comment by anandthakker** [comment]
I had a similar need recently and found that combining `turf-line-splice` and `turf-line-distance` did the trick.  Not necessarily ideal performance wise, but maybe good enough?

**Comment by morganherlocker** [comment]
@anandthakker's answer is ideal here.
