### ISSUE TITLE
Simplify module "pt1 is undefined" error for empty LineString

### ISSUE THREAD

**Issue by peetjvv** [Turfjs/turf#2232]
When attempting to simplify a `LineString` without any coordinates I receive an error `pt1 is undefined`. Could the error message please be changed to something more descriptive? Or, better yet, can turfSimplify return an empty set of coordinates if the input coordinates are also empty?

Some info:

- Package: `@turf/simplify v6.5.0`
- Geojson data:

```json
{
  "type": "LineString",
  "coordinates": []
}
```

- Source code below or in [codesandbox](https://codesandbox.io/s/turf-simplify-empty-linestring-issue-l1s59)

```js
import turfSimplify from "@turf/simplify";
const emptyLineString = {
  type: "LineString",
  coordinates: [],
};
const simplifiedEmptyLineString = turfSimplify(emptyLineString, {
  tolerance: 0.000005,
});
```

**Comment by JamesLMilner** [comment]
Thanks for your suggestion. For performance and simplicity reasons we tend to avoid doing in depth validation at the module level and suggest that users of the module ensure the geometry is valid before inputting into the function. As such we can suggest that users do something like this:

```javascript
if (!emptyLineString.coordinates || emptyLineString.coordinates.length < 2) {
    throw new Error("LineString requires at least 2 coordinates")
}
```
