### ISSUE TITLE
Uncaught SyntaxError: object-assign in browser (using top-level @turf/turf package, @web/dev-server, Typescript)

### ISSUE THREAD

**Issue by rvt** [Turfjs/turf#2235]
Please provide the following when reporting an issue:

- [6.5.0 ] The version of Turf you are using, and any other relevant versions.

I noticed that object-assign is still used at some places like turf-isolines and turf-isobands.
Is it possible to get rid of these? I believe nowdays we ca  already use the spread operator and there is not a real need anymore for that helper.

I am trying to use turf in a typescript project and getting bugged by 
`:index.js:5 Uncaught SyntaxError: The requested module './../../../../object-assign/index.js' does not provide an export named 'default'`
and unfortunately not yet an idea how to fix this..

**Comment by twelch** [comment]
Hi @rvt, can you provide a code sample and steps for us to reproduce the error?   How are you installing turf?  And what exactly is producing your error, the Typescript compiler?  web browser?

The specific error message regarding object-assign may be a red herring.

**Comment by rvt** [comment]
Hey, I have created an example here: https://github.com/rvt/openwc-clean

- The project was created using openwc and is pretty much same as from initialised.
- turf was added with `npm install @turf/turf`
- Turf was used here : https://github.com/rvt/openwc-clean/blob/master/src/OpenwcClean.ts#L19

to try:
```
git clone https://github.com/rvt/openwc-clean
cd openwc-clean
npm install
npm start
```

**Comment by twelch** [comment]
I think it's an issue with importing the top-level turf package.  I remember seeing at least one other similar issue, but I can't find it.  I'm going to change the title to reflect this and leave it open.

As a workaround I would suggest using individual packages, which is what I do as a typescript user.  It will keep from bloating your build as well.
```
    "@turf/destination": "^6.5.0",
    "@turf/helpers": "^6.5.0",  (contains point function among others)
```

**Comment by twelch** [comment]
More specifically here's what I verified to at least build and display your app:

```
import { point } from '@turf/helpers';
import destination from '@turf/destination';

const thePoint = point([-75.343, 39.984]);
const distance = 50;
const bearing = 90;
const theDestination = destination(thePoint, distance, bearing, {units: 'miles'});
console.log(theDestination)
```

**Comment by twelch** [comment]
A little more info, I didn't dig deeper.  In this use case turf is bundled by Typescript and served up using a web development server for the browser.  `tsc` reports no errors but the browser console on localhost:8000 page load produces the syntax error.

Console output:
```
 ~/src/openwc-clean> npm start

> openwc-clean@0.0.0 start
> tsc && concurrently -k -r "tsc --watch --preserveWatchOutput" "wds"

[3:56:19 PM] Starting compilation in watch mode...

Web Dev Server started...

  Root dir: src/openwc-clean
  Local:    http://localhost:8000/
  Network:  http://192.168.0.30:8000/

[3:56:21 PM] Found 0 errors. Watching for file changes.
```

![image](https://user-images.githubusercontent.com/81816/146695655-208b01e1-6be0-4586-be13-8be9a7286092.png)

**Comment by rvt** [comment]
I think it's just because of this package : https://www.npmjs.com/package/object-assign

Using the spread operator would already solve this and the dependency of object-assign could be removed... unless we want to support old browsers or node versions?

It's used like this: `pt.properties = objectAssign({ dist }, pt.properties, properties);`

That I think can be rewritten as (I have not inspected what each variable really holds, but you get the idea...)
`pt.properties={...dist, ...pt.properties, ...properties}`;

**Comment by JamesLMilner** [comment]
I am not super familiar with the underlying bundling issue but it does seem like this package probably isn't required

**Comment by rvt** [comment]
I found them used here:
https://github.com/Turfjs/turf/blob/master/packages/turf-nearest-point-to-line/package.json#L72
https://github.com/Turfjs/turf/blob/master/packages/turf-nearest-point-to-line/index.ts#L82

https://github.com/Turfjs/turf/blob/master/packages/turf-isolines/package.json#L72
https://github.com/Turfjs/turf/blob/master/packages/turf-isolines/index.js#L95

https://github.com/Turfjs/turf/blob/master/packages/turf-isobands/package.json#L76
https://github.com/Turfjs/turf/blob/master/packages/turf-isobands/index.js#L12

Note: I am not deep enough in the TS/JS complex eco system to understand if the files with the JS extension are really an issue... But understanding that object-assign was once created as a package to fix some corner case issue and that nodejs and browsers nowdays understand the spread operator, I do feel that dependency could be removed?

**Comment by rvt** [comment]
thanks everybody!
