### ISSUE TITLE
grid apis consistency

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#224]
The current grid apis are inconsistent. turf-grid uses a resolution parameter, while turf-hex uses a distance degrees parameter. I think both should use ~~distance~~ cell width + unit.

```js
var bbox = [7.2669410, 43.695307, 7.2862529, 43.706476];
var cellwidth = 1;
var units = 'miles';

grid(bbox, cellwidth, units);
hex(bbox, cellwidth, units);
regular(bbox, cellwidth, units);
triangle(bbox, cellwidth, units);
```

I think we should normalize the names of these modules as well to make their functionality more obvious:

- turf-point-grid
- turf-hex-grid
- turf-square-grid
- turf-triangle-grid

**Comment by tmcw** [comment]
> I think both should use distance + unit.

It should be clearer than that: distance of what? An edge?

**Comment by morganherlocker** [comment]
cell width

**Comment by morganherlocker** [comment]
ok, knocked out:

- [turf-square-grid](https://github.com/Turfjs/turf-square-grid)
- [turf-triangle-grid](https://github.com/Turfjs/turf-triangle-grid)

![](https://dl.dropbox.com/s/99w8tqh31hw68lg/Screenshot%202015-02-17%2018.34.18.png?dl=0)
![](https://dl.dropbox.com/s/in116sxgn3xdjys/Screenshot%202015-02-17%2018.33.48.png?dl=0)

**Comment by tchannel** [comment]
@morganherlocker is this safe to close? seems like you got all the grids worked out awhile back
