### ISSUE TITLE
Fix doc generation

### ISSUE THREAD

**Issue by mfedderly** [Turfjs/turf#2248]
`npm run docs` used to build the README.md files, but that seems to not be working any more, possibly because of all of the package updates over time. There may be an issue in `scripts/generate-readmes.js`

**Comment by markstos** [comment]
I believe this issue is resolved. I just tested `npm run docs` on the master branch and it ran without error. `git status` shows many README.md's were updated and spot-checking one found no errors.

**Comment by smallsaucepan** [comment]
Believe this is resolved. Husky pre-commit hooks run lint-staged, which runs generate-readmes.
