### ISSUE TITLE
learnyouturf

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#225]
This would be a workshopper tutorial that teaches you turf: https://github.com/rvagg/workshopper

**Comment by lyzidiamond** [comment]
What's the benefit of workshopper vs any other tutorial format?

**Comment by tchannel** [comment]
I like the interactive nature of workshopper, but I think something browser based with an integrated map view might be more effective for turf. This way we can facilitate people learning the API as well as learning what terms mean that they may not know yet

**Comment by tmcw** [comment]
This is kind of in the spirit of "trying out a bunch of possibilities": while something browser-based has a tighter write-test-fix loop, it also usually abstracts away the "glue code" like loading JSON files and writing the HTML to prop up your page. Workshopper on the other hand has a somewhat weaker feedback loop but the end product is a standalone, working example. I'm also very interested in the value of breaking this up into 6-10 short chapters, and how that might inspire a structure for in-person tutorials.

**Comment by tchannel** [comment]
@tmcw any further thoughts on what a  step by step turf tut series would cover? We've got general learning tools now, but I've come around to the idea that we could certainly use a sort of "guided tour" to doing things with Turf. It doesn't seem like it'd make sense to cover the whole turf API, but rather some basics of the *type* of things turf can do and then some sections on *how* to integrate turf in various configurations. Something like:

1. Geojson & Turf Helpers
2. Simple API intro - Buffers, Distance, maybe something with grids
3. Using Turf in the Browser w/ Leaflet - Include loading a data set & doing something like generating a TIN
4. Using Turf with Node & JSON files - Cover doing simple operations and outputting results either via stdout or to files. This would clarify how to write one-off data processing programs using turf
5. Using Turf with Express - How to set up a simple server that uses turf
6. Something that ties it all together? A simple express server for processing + a frontend for displaying. Pick some specific analysis problem to have the user build

**Comment by lyzidiamond** [comment]
So the first three there are already (mostly) covered:

1. The [main Turf docs page](http://turfjs.org/static/docs) has a short explanation of the relationship between GeoJSON and Turf helpers, and I'm hoping to soon have time to update the GeoJSON globals page with a bit more of an explanation as well.
2. I wrote the Mapbox [Intro to Turf](https://www.mapbox.com/guides/intro-to-turf/) guide that covers the basics of the API.
3. I also wrote an [Analysis with Turf](https://www.mapbox.com/guides/analysis-with-turf/) Mapbox guide that walks through using Turf in the browser with Leaflet.

The others sound great though!

**Comment by tchannel** [comment]
excellent! I had seen #1 but not the others. Maybe the others are best left for example projects (like turf-node-example) / blog post walkthroughs

**Comment by tmcw** [comment]
⇢ https://github.com/Turfjs/introturf

**Comment by tmcw** [comment]
Further actions in ^
