### ISSUE TITLE
'@turf/isobands@^6.5.0' is not in the npm registry

### ISSUE THREAD

**Issue by gou95275** [Turfjs/turf#2257]
cmd show     '@turf/isobands@^6.5.0 is not in the npm registry'    when I run    'npm install @turf/turf'

**Comment by JamesLMilner** [comment]
`@turf/isobands` at version 6.5.0 is in the npm registry, you can see for yourself here: https://www.npmjs.com/package/@turf/isobands

If you are seeing this image in the console we would need more information about your environment and what you were trying to do when you saw the error.
