### ISSUE TITLE
Precision problem for "booleanPointOnLine"

### ISSUE THREAD

**Issue by meatjam** [Turfjs/turf#2261]
I'm using turf@6.5.0.
For small scale of lines (like several kilometres),if I draw 2 line close with each other and get a point along line2 for about 2km.

```javascript
let line1 = turf.lineString([
    [121.91168456954146,30.278958163610426],
    [121.9102002526951,30.225961662628094]
]);
let line2 = turf.lineString([
        [121.97324544123961,30.277676327739186],
        [121.97275066895708,30.20800475485875]
]);
let pointCoords =turf.along(line2,2).geometry.coordinates;
```

Then use method "booleanPointOnLine" to check if the point is on both 2 lines.
No matter if I use option "epsilon" and no matter how large number I use for "epsilon", the result won't be correct.

```javascript
const line1Result = turf.booleanPointOnLine(pointCoords,line1/*,{epsilon: 14,}*/);
const line2Result = turf.booleanPointOnLine(pointCoords,line2/*,{epsilon: 14,}*/);
const line1Distance = turf.pointToLineDistance(pointCoords,line1);
const line2Distance = turf.pointToLineDistance(pointCoords,line2);`
```

Full example [here](https://codepen.io/meatjam/pen/rNYYMdW?editors=0010).

Don't use option "epsilon":
![image](https://user-images.githubusercontent.com/43535074/154205377-343a4788-bc3c-4a43-9173-3225bc9fa9c2.png)
Use "epsilon" with number 14:
![image](https://user-images.githubusercontent.com/43535074/154205511-a83b7ba6-5beb-46af-98a0-846ce4b0e558.png)
Point and lines on mapbox:
![image](https://user-images.githubusercontent.com/43535074/154205567-37279372-bd9a-4100-8aba-186855fc3e59.png)

**Comment by JamesLMilner** [comment]
I'm assuming  you're expecting the result to be:

```"line1Result:" false "line2Result:" true```

An epsilon of 14 would be 14km which is why both end up being true. If you do:

```
  const line1Result = turf.booleanPointOnLine(pointCoords,line1, {
      epsilon: 0.0001 // 1cm
  });
  const line2Result = turf.booleanPointOnLine(pointCoords,line2,{
      epsilon: 0.0001 // 1cm
  });
```

You will get the result I think you're expecting.

**Comment by meatjam** [comment]
> 

Thanks, that works. It's my fault.
