### ISSUE TITLE
Sector Coordinate Generation Issue

### ISSUE THREAD

**Issue by scottalexgray** [Turfjs/turf#2264]
Issue with generating sectors. If I try generate a sector with 16, 32 or 64 steps and the second bearing is 45 degrees it seems to snap to the nearest step multiple. But if the first bearing is 45 degrees it generates the sector correctly. Also if I use a number of steps that divides 360 degrees into non fractional angles (30 or 60) it works perfectly.
Also if I use 360 steps it doesn't generate the sectors correctly either which is weird. It seems to get the coordinates for the first bearing correct but then snaps to the nearest multiple for the second. 

It's a pretty strange issue and really annoying as it wouldn't be too much work to create a function to generate the coordinates of a sector myself, but also it would be nice for it to just work.

Note: All bearings used are whole/natural numbers. 

I'm using this (https://unpkg.com/@turf/turf@6/turf.min.js) version.

**Comment by JamesLMilner** [comment]
It would be helpful to have some minimal code sample to help reproduce the issue you're describing, this makes it easier to reproduce and examine what is happening and what you're expecting to happen.
