### ISSUE TITLE
Module federation "No version specified" warning

### ISSUE THREAD

**Issue by byv55f5f5** [Turfjs/turf#2268]
I use @turf/turf@6.5.0 with webpack federation. And the warning show on the screen.

```
Compiled with problems:X

WARNING in shared module @turf/turf -> C:\Users\work\repo\my_project\node_modules\@turf\turf\dist\es\index.js

No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.
```

Seems like the version should added in `node_modules\@turf\turf\dist\es\package.json`

- webpack: 5.65.0
- Browser: Microsoft edge v99.0.1150.36
- turf: 6.5.0

**Comment by ajaybhayani741** [comment]
Facing the same issue in turf version 7.0.0-alpha.0

**Comment by smallsaucepan** [comment]
Hi @byv55f5f5 Can you explain how this _should_ work? Viewing the contents of package.json at https://www.npmjs.com/package/@turf/turf?activeTab=code version is definitely set.

**Comment by byv55f5f5** [comment]
Hi @smallsaucepan ,
The file path of package.json I meant is `node_modules\@turf\turf\dist\es\package.json`.
There are only `{"type":"module"}` specified in that file.

I added the version like this comment said: https://github.com/webpack/webpack/issues/13457#issuecomment-1556980850

But now, I looked at the discussions on that issue. It seems like a problem that Webpack should resolve.

**Comment by smallsaucepan** [comment]
Following up on this @byv55f5f5. Doesn't look like webpack is going to fix this, though not really sure that Turf should either. Is it only generating a warning, and you can otherwise use Turf ok? How about you @ajaybhayani741 and @kboul?

**Comment by smallsaucepan** [comment]
Turf v7 made significant changes to the way the library is packaged, including the removal of the `{"type":"module"}` files that caused this problem. Marking as resolved though reopen if this problem persists after an upgrade to v7.
