### ISSUE TITLE
Avoid any type.

### ISSUE THREAD

**Issue by infacto** [Turfjs/turf#2269]
For example `getCoords` returns `any[]` instead of `number[]` or better `[number, number]` (`[lat, lng]`) or an array of it.
Version: 6.5.0

https://github.com/Turfjs/turf/blob/7b43038a9c5f5125af3ce519c145677ee28e6449/packages/turf-invariant/index.ts#L75

The `getCoord` (singular) has return type `number[]`. Can `getCoords` return 1D, 2D or 3D number array?

**Comment by JamesLMilner** [comment]
There's an on going effort to clean up the typings in the project - hopefully this will be noticeable in the next release: https://github.com/Turfjs/turf/pulls?q=is%3Apr+is%3Aclosed+type
