### ISSUE TITLE
turf-denormalize

### ISSUE THREAD

**Issue by knownasilya** [Turfjs/turf#227]
Pass it a feature collection of polygons, and it merges the polygons that are touching. So if you have a FeatureCollection of 5 polygons and two touch, you'd get back a FeatureCollection of 4 polygons.

**Comment by tmcw** [comment]
Is `normalize` a word used for this in other libraries?

**Comment by knownasilya** [comment]
Ops it would be denormalize technically (from relational db land).

**Comment by morganherlocker** [comment]
[turf-merge](https://github.com/Turfjs/turf-merge) does this

**Comment by knownasilya** [comment]
@morganherlocker so it only merges touching polygons?

**Comment by knownasilya** [comment]
https://github.com/Turfjs/turf-merge/blob/master/index.js#L6 looks like it is mentioned in the code..

**Comment by morganherlocker** [comment]
ah, nope, its touching + overlapping

**Comment by knownasilya** [comment]
@morganherlocker that's good enough. Just the readme was outdated..

**Comment by morganherlocker** [comment]
thanks @knownasilya :)
