### ISSUE TITLE
buffer documentation not matching function behavior and buggy output?

### ISSUE THREAD

**Issue by danbjoseph** [Turfjs/turf#228]
In the API docs for [turf.buffer](http://turfjs.org/static/docs/module-turf_buffer.html) the `feature` parameter description includes _"or FeatureCollection of any type"_ and the output is explained as: "_Returns FeatureCollection- a FeatureCollection containing Polygon features representing buffers_"

When I provided a FeatureCollection of  >1 point for `feature` the output was a FeatureCollection containing a single feature (a multipolygon). The output also had some weird issues where with three points at certain buffer distances the multipolygon would only have two polygon coordinate arrays.
Not sure if issues arose also from trying to use the FeatureCollection of a multipolygon in [turf.within](http://turfjs.org/static/docs/module-turf_within.html) since the `polygons` parameter asks for _"a FeatureCollection of Polygon features"_

See http://danbjoseph.github.io/buggy/pumpbuffer_copy/, select at least the eastern three blue water pump points, and then adjust the slider to 90 through 130.
![screen shot 2015-02-19 at 4 58 05 pm](https://cloud.githubusercontent.com/assets/4806884/6264084/1e9f18f8-b85b-11e4-94c4-3d40df8749f1.png)
![screen shot 2015-02-19 at 4 58 11 pm](https://cloud.githubusercontent.com/assets/4806884/6264085/1f794d7a-b85b-11e4-841c-53026874949d.png)
![screen shot 2015-02-19 at 5 05 42 pm](https://cloud.githubusercontent.com/assets/4806884/6264086/25f977d8-b85b-11e4-836a-9344bb7f4b46.png)
![screen shot 2015-02-19 at 5 07 32 pm](https://cloud.githubusercontent.com/assets/4806884/6264088/27090daa-b85b-11e4-88b0-1e16516e3cdf.png)

**Comment by tchannel** [comment]
I believe this should be corrected by turfjs/turf-buffer#12. @morganherlocker?

**Comment by morganherlocker** [comment]
yep, this fix will go out in the next turf master release
