### ISSUE TITLE
Line overlaps not detected by lineOverlap

### ISSUE THREAD

**Issue by samichoulo911** [Turfjs/turf#2282]
Please provide the following when reporting an issue:
Hi, I am having an issue detecting overlaps between 2 lines. 
![image](https://user-images.githubusercontent.com/43357319/163699361-2ef3c882-f608-4b4a-8fc4-4192b62cbd32.png)

(Note that in each example the blue and green lines are overlapping, but for the sake of the example, the lines were separated)
(Also, each line is defined by the points on them)

For the first example, we see that the overlapping section (described by the black indicator) is not detected. 
In the second example, the overlap is detected and results in the pink line. 

Is this behaviour expected? If it is, is there a way to easily detect the black section (same as pink) in the first example?
Example 1
```
var line1 = turf.lineString([[0, 0], [0, 100]]);
var line2 = turf.lineString([[50,0], [150, 0]]);

var overlapping = turf.lineOverlap(line1, line2); // Would like to get the black line (same as pink), but get nothing
```

Example 2
```
var line1 = turf.lineString([[0, 0], [50,0], [0, 100]]);
var line2 = turf.lineString([[50,0], [150, 0]];

var overlapping = turf.lineOverlap(line1, line2); // Results in pink line
```

I am using turfjs version  2.5.2.

I think this issue might be similar to https://github.com/Turfjs/turf/issues/901

**Comment by dpmcmlxxvi** [comment]
@samichoulo911 Double check your coordinates. It looks like you are swapping `x` and `y` between `line1` and `line2`. Plot the lines and you'll see they don't actually overlap.

**Comment by JamesLMilner** [comment]
As @dpmcmlxxvi mentioned, these example LineStrings don't overlap:

```

{ 
    "type": "FeatureCollection", 
    "features": [
        {
            "id": "1",
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "LineString",
                "coordinates": [[0, 0], [0, 100]]
            }
        },
          {
            "id": "2",
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "LineString",
                "coordinates":[[50,0], [150, 0]]
            }
        }
    ]
}
```

Plotted on geojson.io:

![image](https://user-images.githubusercontent.com/8822075/172362500-7bc70a7d-d059-4d17-9430-2e1511b67aa1.png)

As such I'm going to close this out.

**Comment by MuktakMahajan** [comment]
I also agree that the given line string coordinates are definitely not according to the diagram mentioned above, but I am also facing the same issue and my coordinates are exactly according to the diagram.

const line1 = {
      "type": "Feature",
      "properties": {
        "stroke": "#ff0000",
        "stroke-width": 2,
        "stroke-opacity": 1
      },
      "geometry": {
        "coordinates": [
          [
            -5.136302873217162,
            50.1527914496956
          ],
          [
            -5.136281226,
            50.152778443
          ],
          [
            -5.136153711,
            50.152686683
          ],
          [
            -5.135924023,
            50.152561091
          ],
          [
            -5.135924023,
            50.152561091
          ]
        ],
        "type": "LineString"
      }
    }

const line2 = {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            -5.136781233,
            50.15307927
          ],
          [
            -5.136651288,
            50.152998841
          ],
          [
            -5.136460153,
            50.152885951
          ],
          [
            -5.13628975173245,
            50.15278356567262
          ]
        ],
        "type": "LineString"
      }
    }

I am getting the wrong result for the below turf methods 

      1. turf.booleanIntersects(line1, line2) 
             the result is false, but it should be true.
      
      2. turf.lineOverlap(line1, line2)
            the result is "{
          "type": "FeatureCollection",
          "features": []
      }", but there should be one line string in the features array.

@JamesLMilner
