### ISSUE TITLE
PR #1778 and #2142 regarding line-arc bug not in npm package

### ISSUE THREAD

**Issue by PTParta** [Turfjs/turf#2283]
Please provide the following when reporting an issue:

- [6.5.0] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

There has been a bug reported about sector being drawn wrong in a certain case. PRs #1778 and #2142 should have fixed the issue. When i use npm to install the latest version 6.5.0 (npm install @turf/turf@6.5.0) these changes are not included in the package and the bug remains. What is strange that the changes can be seen in the source code but for some reason they are not included in the npm package. Is there something wrong in the packaging? Or am I doing something wrong when installing the package?

Below are the relevant code snippets for the bug fix.

Buggy code snippet from line-arc

```javascript
 if (alfa > arcEndDegree) {
    coordinates.push(
      destination(center, radius, arcEndDegree, options).geometry.coordinates
    );
  }

Fixed code snippet from line-arc
if (alfa >= arcEndDegree) {
    coordinates.push(
      destination(center, radius, arcEndDegree, options).geometry.coordinates
    );
  }
```

**Comment by JamesLMilner** [comment]
Hi @PTParta - the PR is merged but it's changes are not present on npm because that npm package hasn't been published. This change will likely appear in 7.0.0.

**Comment by PTParta** [comment]
Thank you very much for the quick response.

If others have the same issue I got it to work with a workaround by explicitly setting the steps value in the sector options. Not sure why this works but it seemed to fix the issue.

**Comment by PTParta** [comment]
> Hi @PTParta - the PR is merged but it's changes are not present on npm because that npm package hasn't been published. This change will likely appear in 7.0.0.

After a quick search I couldn't find a release date for 7.0.0. Any idea when it will be released? This bug fix would be helpful.

**Comment by JamesLMilner** [comment]
No official ETA yet unfortunately - we're working on it!

**Comment by PTParta** [comment]
> Is there any workaround how to fix this bug?

One way could be to set the steps value in the sector so high (10000 for example) that the mistake is so small that it can't be seen. Not ideal but maybe useful.

**Comment by PTParta** [comment]
Another workaroundd could be to set the steps to some value that doesn't trigger the bug. Steps = 99 seemed to work well for me

**Comment by JamesLMilner** [comment]
I'm going to close this as to my understanding the underlying bug is fixed, it just hasn't been released. Feel free to continue discussing if you have additional points to raise.
