### ISSUE TITLE
@turf/intersect throws error "Each LinearRing of a Polygon must have 4 or more Positions"

### ISSUE THREAD

**Issue by sroettering** [Turfjs/turf#2290]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.
- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Hi,

I created a [stackblitz](https://stackblitz.com/edit/js-s9eypq?file=index.js) with a "minimal" reproduction scenario. I think what is happening is that both polygons intersect only on a lineString which then internally fails the conversion to a polygon which is understandable. However, I would expect that either null is returned or even the resulting lineString. Just letting the polygon helper function throw an error is not a very good DX and hard to debug.

**Comment by JamesLMilner** [comment]
Hey @sroettering - the reason for this is polyA and 'polyB' are not valid GeoJSON Polygon Features. You need to wrap it in a Feature object and then wrap the polygon with the geometry property of the feature. A valid Polygon Feature has the following schema:

```json
   {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
            [100.0, 1.0], [100.0, 0.0]
          ]
        ]
      },
      "properties": {
        "prop0": "value0",
        "prop1": { "this": "that" }
      }
    }
```

You can use this to lint them: https://geojsonlint.com/

**Comment by sroettering** [comment]
Hi @JamesLMilner . Thank you for your reply. The docs indeed say the inputs need to be a feature but we were using intersect for a longer time now and it always worked and still works by just passing in the geometries without a feature wrapper.
We will change it in our code and give it a try. Nonetheless it would improve DX a lot when the intersect function could warn you when you pass in the wrong format.

**Comment by sroettering** [comment]
@JamesLMilner It seems like you did not even try out the proposed solution yourself. I updated the stackblitz example (https://stackblitz.com/edit/js-s9eypq?file=index.js) with your proposed solution and it still does not work.

Please reopen this issue as it is not solved!

**Comment by JamesLMilner** [comment]
I am on holiday at the moment, but will take another look when I get back and see if there's something else going on. I will reopen incase anyone else wants to comment.

**Comment by stebogit** [comment]
@sroettering it looks like the issue is related to the precision of the coordinates.
Try [truncating](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate) the coordinates in your polygons:
```js
const intersection = turf.intersect(turf.truncate(polyA, 9), turf.truncate(polyB, 9));
// null
```
Not sure if there's a formal statement in the docs (maybe there should be one), however Turf - [as per GeoJSON specs](https://github.com/Turfjs/turf/issues/820#issuecomment-319898019) - generally assumes `Feature`s don't have more than 6 decimals, which is like 10cm spatial resolution.
In fact I've seen other [instances](https://github.com/Turfjs/turf/issues/2299) where too many decimals could generate unexpected results like here.

**Comment by sroettering** [comment]
@stebogit Thank you for the hint. We did not know that turf can only handle 6 decimal places "safely".
Truncating seems to be the solution for my problem. I also tried it with a simplified example of two polygons intersecting on a lineString and that does not throw an error. Thanks for the help guys!
