### ISSUE TITLE
Uncaught Error: options.minDistance is not yet implemented

### ISSUE THREAD

**Issue by erikhansenmujica** [Turfjs/turf#2291]
Hello, I am using Turf 6.5.0 which I think is the newest, and I am having this error on minDistance between the path and geoJson as obstacle. It says it is not implemented yet, can you give me some advice on what to do to achieve this or make that function available ?

**Comment by JamesLMilner** [comment]
Hey there! Can you clarify which module you're talking about? Assuming you mean `shortestPath` here, you're right this is not implemented (see https://github.com/Turfjs/turf/blob/84110709afda447a686ccdf55724af6ca755c1f8/packages/turf-shortest-path/index.js#L57). It might make sense to remove this property from the options as it's not currently usable and not sure anyone is looking at a PR to implement it.
