### ISSUE TITLE
Help!  which method for 'road in district' test

### ISSUE THREAD

**Issue by MatthewPosgate** [Turfjs/turf#2295]
Please provide the following when reporting an issue:
turf 6.5

Great library!
I have roads stored as features of type multilinestring, and districts stored as features of type polygon.  I need to know if any part of a road is in a district, ie if any part of a feature/multinelinestring in is a feature/ploygon.
Not sure which method to use
thanks

**Comment by JamesLMilner** [comment]
You can check that the LineString is inside a given Polygon with booleanWithin and then check if it intersects with booleanIntersects. This will cover the case it's fully contained and where it intersects. There may be other ways to achieve the same things using the boolean methods - take a look at the docs: https://turfjs.org/
