### ISSUE TITLE
Create isoband inside my entire polygon

### ISSUE THREAD

**Issue by douglas555666** [Turfjs/turf#2297]
I'm having trouble filling all the spaces in my polygono.

The points used are points with values ​​inside the area of ​​the polygon and in this case I am not able to apply my isoband to the entire area

![Captura de tela de 2022-06-02 12-07-26](https://user-images.githubusercontent.com/106752550/171689480-0e345ec6-b137-4dc2-af4f-03dfb0620e85.png)

![Image 2022-06-02 at 14 38 55](https://user-images.githubusercontent.com/106752550/171692030-194f97a5-64a8-4c7b-bc57-45eb06b82c6d.jpeg)

See [https://jsfiddle.net/doug_b/xbd6Lf74/3/](https://jsfiddle.net/doug_b/xbd6Lf74/3/) for an example.

Could anyone help me with this question?

**Comment by JamesLMilner** [comment]
I'm not sure I have a good solution to this, other than to potentially run turf/interpolate first on the vertices of your Polygon and then to run isobands again on the new interpolated point. In theory I think this should ensure your polygon gets covered.

**Comment by JamesLMilner** [comment]
Let me know how you get on :) If I don't hear back will assume it worked and will close out the issue

**Comment by mumispb** [comment]
Hi @douglas555666 , were you able to test if that solution worked for you? I am facing the exact same issue, but @JamesLMilner I have tried tried running interpolate on the vertices, but (let me know if I'm wrong about these conclusions):

1. Interpolate seems to only run in the bounding box automatically calculated by the provided points;
2. I can't add new points (vertices) that don't have the specific property value (that is being interpolated) on them (and I don't have those values).

**Comment by JamesLMilner** [comment]
I will close this as there was no response and there is a new open issue from @mumispb.
