### ISSUE TITLE
Simplify throws exception on duplicate coordinates

### ISSUE THREAD

**Issue by johnbester** [Turfjs/turf#2298]
Turf version 3.0.14

At first it seemed that turf.simplify fails whenever there were duplicate coordinates in a linestring, but as I put
together test cases for this bug report I found that it seems to be only when the first point is duplicated. From the
exception it would seem that the direction calculated was invalid, which seems to suggest (from my previous 
comments), that a direction is calculated from the first two coordinates and if that fails, then the function fails. In stead,
a (starting) direction should be calculated from the first coordinate to the first coordinate that is different to the
very first one while duplicates of the first coordinate is ignored. But then I found another potential issue in that
the fourth input linestring is supposed to yield a result with two segments, but in stead I get the third leg of a triangle.

I attached a zip file called simplify.zip, but then I found I had to change it and attached it a second time. Unfortunately
I do not seem to be able to delete the first attachment.

Code in bugreport.js inside second upload of simplify.zip file follows:
<pre>
const fs = require("fs-extra")
const path = require("path")
const turf = require('@turf/turf')

function removeDuplicateCoords(feature) {
  let coords = feature?.geometry?.coordinates
  if (coords?.length < 2)
    return feature
  var dups = 0
  let current = coords[0]
  for (var i=1; i<coords.length; i++) {
    let tmp = coords[i]
    if (tmp[0] == current[0] && tmp[1] == current[1]) {
      dups++
      coords[i] = undefined
    }
    current = tmp
  }
  if (dups == 0) return feature
  feature.geometry.coordinates = coords.filter(c => c)
  return feature
}

function runTest() {
  //const opts = { tolerance: 1 }
  let input = JSON.parse(fs.readFileSync(path.join(__dirname, "input.geojson")))
  let expected = JSON.parse(fs.readFileSync(path.join(__dirname, "expected.geojson")))
  for (var i=0; i<input.features.length; i++) {
    let ft = input.features[i]
    let exp = expected.features[i]?.geometry?.coordinates
    let sexp = (exp ? JSON.stringify(exp) : undefined)
    var act;
    try {
      act = turf.simplify(ft)
    } catch (err) {
      console.log("ERROR: turf.simplify failed, attempt remove duplicates first")
      ft = removeDuplicateCoords(ft)
      act = turf.simplify(ft)
      console.log("Simplify succeeded after removing duplicates")
    }
    if (!act?.geometry?.coordinates)
      throw "Simplified returned invalid result"
    let sact = JSON.stringify(act.geometry.coordinates)
    if (sexp && sexp !== sact)
      throw `Simplified returned invalid result: 
   expected ${sexp}
   actual   ${sact}`
    console.log(`Test ${i} succeeded`)
  } 
  console.log("Simplify test passed")
}
</pre>
[simplify.zip](https://github.com/Turfjs/turf/files/8839518/simplify.zip)
[simplify.zip](https://github.com/Turfjs/turf/files/8839589/simplify.zip)

**Comment by JamesLMilner** [comment]
Although it's not technically against the GeoJSON spec for LineString to have duplicate coordinates, it does cause a lot of issues with geo libraries. Simplify's role is to simplify LineStrings,using the Ramer-Douglas-Peucker algorithm, and not to remove duplicate coordinates. The function you're probably looking for is [cleanCoords](https://turfjs.org/docs/#cleanCoords) which will remove the duplicates and any extra points that are not required to draw the segments of the line.

**Comment by tstibbs** [comment]
Just for interest, the recommended solution `cleanCoords` can also fail on duplicate coordinates in version 7.2.0. However the good news is that this is fixed by changes in master, so as soon as the next release comes out this should be all good again.
