### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#230]
breaking changes
---

- turf-grid => turf-point-grid
- turf-hex => turf-hex-grid
- turf-hex-grid adds a `unit` parameter
- remove turf-isobands

added features
---

- turf-square
- turf-triangle

fixes
---

- update turf-isolines to work with turf-point-grid
- constrain turf-point-grid to the bbox

**Comment by lyzidiamond** [comment]
Have these changes been updated in the documentation, or should I update?

**Comment by morganherlocker** [comment]
@lyzidiamond updating docs as I go. Implementations will stay synced to docs.

**Comment by morganherlocker** [comment]
:tada: 2.0.0 is live all over (npm, cdn, turf-www)

**Comment by tchannel** [comment]
out of curiousity, why was isobands removed, and is that permanent?

**Comment by morganherlocker** [comment]
@tchannel not permanent, but I did not feel that the implementation was robust enough to be included. It was super brittle. I would love to see it get improved and brought back though, as the functionality is extremely useful. turf-isolines is still around, although it could use some stabilizing as well.
