### ISSUE TITLE
For small distances between point and line, pointToLineDistance returns 0

### ISSUE THREAD

**Issue by jowcy** [Turfjs/turf#2300]
I recently upgraded from Turf 5.1.6 to 6.5.0

Eventually I noticed that my calls to `turf.pointToLineDistance` were returning `0`, where-as before they had returned very small numbers (well less than 1 meter)

For example the code below returns 0 with turf `6.5.0` and returns 9.894542863421217e-10 with `5.1.6`
(Codesandbox using turf 5.1.6
https://codesandbox.io/s/pointtolinedistance-5-1-6-9msndm

Codesandbox using turf 6.5.0
https://codesandbox.io/s/pointtolinedistance-6-5-0-9q3858)

```javascript
let pt = turf.point([
  -97.03817899620722,
  32.95391705832942
]);

let line = turf.lineString([
  [
      -97.03818273934283,
      32.954184196811006
  ],
  [
      -97.03817548915873,
      32.953666768811544
  ]
]);

console.log(turf.pointToLineDistance(pt, line));
```

**Comment by JamesLMilner** [comment]
Unfortunately the CodeSandbox you linked to seems to be something else. Can you link to the one with this code? 

I also formatted your example as GeoJSON for anyone else looking at this:

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -97.03817899620722,
          32.95391705832942
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -97.03818273934283,
            32.954184196811006
          ],
          [
            -97.03817548915873,
            32.953666768811544
          ]
        ]
      }
    }
  ]
}
```

**Comment by jowcy** [comment]
Codesandbox using turf 5.1.6
https://codesandbox.io/s/pointtolinedistance-5-1-6-9msndm

Codesandbox using turf 6.5.0
https://codesandbox.io/s/pointtolinedistance-6-5-0-9q3858

You can see in the console for each one that the answer goes from 9.894542863421217e-10 to 0

**Comment by smallsaucepan** [comment]
Hi @jowcy. We're currently taking a look at a few _distance from x to y_ issues. It sounds like the implementation of pointToLineDistance changed between 5 and 6 and what used to be a small distance now appears as 0.

Looking at the values you've provided though 9.894542863421217e-10 (km I presumed) is a fraction under a micrometer. Less than the width of a human hair if I've done my math right. On a global scale I don't think we can reasonably expect to distinguish between that and 0.

If I've misunderstood something about the details or impact, please let me know.

**Comment by smallsaucepan** [comment]
No update in a while so closing.
