### ISSUE TITLE
How to create a FeatureCollection from a point and a Polygon

### ISSUE THREAD

**Issue by jdang67** [Turfjs/turf#2301]
Hi,

I'm using  "@turf/turf": "^6.5.0".

Just need to create a FeatureCollection with many polygons and some points and could not find any example to do this.

Thanks,

Jdang

**Comment by stebogit** [comment]
@jdang67 a feature collection is just a GeoJSON object in which its features attribute is an array of GeoJSON features. You can simply use the turf helper `featureCollection` function passing the array of features.

**Comment by jdang67** [comment]
I have tried that but since the featureCollection will contain a point and a polygon, turf does not like it. I can use javascript 
       var fc = { "type": "FeatureCollection", "features": <any>[] }
        fc.features.push(myPoint);
        fc.features.push(myPolygon);
However, the downstream app does not accept the format.

**Comment by stebogit** [comment]
@jdang67 again, please post actual code (ideally in a jsfiddle or similar fashion) so we can run/debug it

**Comment by jdang67** [comment]
Hi @stebogit ,

Here is my point and polygon.  Can you use turf to build a featureCollection from these objects?

```js
const device = turf.point([  12.4566, 45.98765], { name: 'DeviceLoc', color: '#ff0000' });
const polygon = turf.polygon([[
                [12.456500, 45.987569],
                [12.456391, 45.987600],
                [12.456449, 45.987671],
                [12.456782, 45.987750],
                [12.456833, 45.987648],
                [2.4565004, 45.987569]
              ]] , { { name: 'My Polygon', color:'$FFFF00' }});

**Comment by JamesLMilner** [comment]
Here you can use `turf.featureCollection` like so:

```javascript

const featureCollection = turf.featureCollection([device, polygon]);

```

**Comment by jdang67** [comment]
> Here you can use `turf.featureCollection` like so:
> 
> ```js
> const featureCollection = turf.featureCollection([device, polygon]);
> ```
Have you tried to do that, I tried this technique from day one and got this error: 
``` js
Type 'Feature<Polygon, { name: number; }>' is not assignable to type 'Feature<Point, { name: string; color: string; }>'.
  Type 'Polygon' is not assignable to type 'Point'.
    Types of property 'type' are incompatible.
      Type '"Polygon"' is not assignable to type '"Point"'.ts(2322)
```

**Comment by stebogit** [comment]
I bet the error is in the polygon creation: as `option` argument you're passing an object within an object. Try removing a set of curly braces

**Comment by jdang67** [comment]
> 
Have you tried to do that, I tried this technique from day one and got this error:

**Comment by stebogit** [comment]
As I mentioned, just a polygon issue: https://turf-sandbox.netlify.app/?gist=2406a285e28e318f7ecceb919a7aef44

<img width="299" alt="Screen Shot 2022-06-14 at 8 09 42 AM" src="https://user-images.githubusercontent.com/12717225/173612497-a6b0c737-43a8-4a09-b667-8bbb867a0efc.png">

**Comment by jdang67** [comment]
@stebogit, Which version do you use? I can't make it works with "@turf/turf": "^6.5.0",


![image](https://user-images.githubusercontent.com/8005940/173826584-ee2eb522-de85-42c1-9356-e68a0e339c2f.png)

**Comment by stebogit** [comment]
Look at the coordinates of the polygon: that first and last elements must be the same

**Comment by jdang67** [comment]
@stebogit, check this one, check the error message. The message comes from your library 
![image](https://user-images.githubusercontent.com/8005940/173970406-7815d53c-4894-4642-8c6c-35742dffd5af.png)

**Comment by stebogit** [comment]
@jdang67 I really can't debug a picture.
Clearly there is something wrong in how the polygon is instantiated in your code.
I created the above script that, as you can see, runs as expected, so I'd assume the library works fine

**Comment by jasonhibbs** [comment]
I have the same issue, I believe the problem is with typescript. `featureCollection` currently only accepts a single feature type.

In my case I have an array points and linestrings:

```
const features: (Feature<Point, Properties> | Feature<LineString, Properties>)[]
```

When used in `featureCollection`, I get this Typescript warning:

```
Argument of type '(Feature<Point, Properties> | Feature<LineString, Properties>)[]' is not assignable to parameter of type 'Feature<Point, Properties>[]'.
  Type 'Feature<Point, Properties> | Feature<LineString, Properties>' is not assignable to type 'Feature<Point, Properties>'.ts(2345)
```

Here’s the definition of `featureCollection` I see, and [its source](https://github.com/Turfjs/turf/blob/2dd2ef88c44d847989fa0b82089f3f81fe433b83/packages/turf-helpers/index.ts#L438):

```
export declare function featureCollection<G = Geometry, P = Properties>(features: Array<Feature<G, P>>, options?: {
    bbox?: BBox;
    id?: Id;
}): FeatureCollection<G, P>;
```

**Comment by twelch** [comment]
@jasonhibbs it looks like the featureCollection method is trying to infer your geometry type from what you pass but is only picking up the first Point and not the LineString.   It may need a little more help.

You can try a slightly different typing:
```
const features: (Feature<Point | LineString>)[] = []
```

Or telling the featureCollection explicitly what to expect so it doesn't infer from what you pass it.
```
const features: (Feature<Point> | Feature<LineString>)[] = []
const foo = featureCollection<Point | LineString>(features)
```

**Comment by jasonhibbs** [comment]
@twelch thanks for helping me help typescript
