### ISSUE TITLE
@turf/difference: "Unable to find segment"

### ISSUE THREAD

**Issue by pomm0** [Turfjs/turf#2306]
When getting the difference of two specific polygons I'm getting this error:

```
Uncaught Error: Unable to find segment #15 [10.299187924375136, 48.46036112600978] -> [10.299193387184792, 48.460364759343314] in SweepLine tree. Please submit a bug report.
```

So, as the error message says, here is the bug report for it. Find this [JSFiddle](https://jsfiddle.net/Pomm0/7kfrzd6j/2/) and the polygons inside to reproduce this issue.

Using:
@turf/difference: 6.5.0

**Comment by smallsaucepan** [comment]
Retest this as part of removing polygon-clipping. Also see comment at https://github.com/Turfjs/turf/issues/2258#issuecomment-1651781380 for another test case.
