### ISSUE TITLE
turf.isobands result are too sharp

### ISSUE THREAD

**Issue by duoduodady** [Turfjs/turf#2308]
![image](https://user-images.githubusercontent.com/13536089/177346421-716cdc2e-7fdc-4c7b-b802-442b375152eb.png)

The corners are sharp。What should I do to make it smooth??

```js
turf.isobands(points, breaks, {
    zProperty: "speed"
})
```

**Comment by stebogit** [comment]
@duoduodady I'm sure you realize it is quite difficult to think of a possible solution with no specifics on your case, and just a picture... 🤦🏻 
Just by guessing, I'd suggest you to increase the number of grid `points` over which you're interpolating the `speed` value on the plain.

**Comment by JamesLMilner** [comment]
In order to advise better this requires the accompanying underlying data to get a better understanding. Please post the GeoJSON or better a link to a working example (CodePen/CodeSandbox etc)

**Comment by duoduodady** [comment]
turf.bezierSpline Function can smoth the line only.

The Best solution is More PointGrid in the same area. But datas will  become more , and the interpolating need more times.

**Comment by duoduodady** [comment]
[partData.zip](https://github.com/Turfjs/turf/files/9187324/partData.zip)


![image](https://user-images.githubusercontent.com/13536089/180944474-1c57bb0e-7c27-46a1-a131-255752ed494d.png)

 let geojsonLine = turf.isolines(points, colorBreaks, isobands_options);

 let geojsonPoly=  turf.isobands(points, colorBreaks, isobands_options);

let smoothFeatures = TurfSmoothFeatures(geojsonLine.features);

function TurfSmoothFeatures(filterFeatures){
  let smoothFeatures =filterFeatures;
  if(smoothFeatures!=null && smoothFeatures.length>0){
    for (let i = 0; i < smoothFeatures.length; i++) {
        let _coords = smoothFeatures[i].geometry.coordinates;
        let _lCoords = [];
        for (let j = 0; j < _coords.length; j++) {
            let _coord = _coords[j];
            let line = turf.lineString(_coord);
            let curved = turf.bezierSpline(line);
            _lCoords.push(curved.geometry.coordinates);
        }
        smoothFeatures[i].geometry.coordinates = _lCoords;
    }
  }
  return smoothFeatures;
}

![image](https://user-images.githubusercontent.com/13536089/180944566-7c33a491-ff27-4197-86d1-0466f3870433.png)


The line is  turf.bezierSpline result，smooth 。
The color area is turf.isobands result， sharp。
