### ISSUE TITLE
@turf/buffer crashes when processing many closely clustered points

### ISSUE THREAD

**Issue by anstosa** [Turfjs/turf#2311]
Turf version 6.5.0.

I'm making a page that shows a historical location trace with a buffer around it. It works fine in the normal case when the locations are spread out but if they are clustered tightly together buffer completely crashes the tab trying to calculate.

Obviously, I don't expect buffer to give me very useful results here, but I expect it not to take down the whole website. How can I fix this or detect cases where buffer is going to choke?

one-line repro with example data: https://codesandbox.io/s/turf-buffer-crash-9qjof2?file=/src/index.js

**Comment by twelch** [comment]
Turf functions are computationally intensive and if long-running in the browser on the main thread the UI will become unresponsive.  You can try running them in a web worker, it's designed to avoid blocking.

Example - https://github.com/nickpeihl/turf-async
