### ISSUE TITLE
isobands returns an unintended value

### ISSUE THREAD

**Issue by alv1ns** [Turfjs/turf#2329]
Please provide the following when reporting an issue:
I used "@turf/turf": "^6.5.0"
`     let collection = featureCollection(fc)`
    `  let breaks = [0, 30，50, 60, 70, 100]`
      `let result = isobands(collection, breaks, { zProperty: 'value' })`
All values of collection are greater than 30，But the first entry of result has the value like:
![image](https://user-images.githubusercontent.com/111822131/189067942-18a51bf1-3343-48f8-9a0c-defa08056fb4.png)

- [6.5.0 ] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by stebogit** [comment]
@alv1ns how does the "0-30" MultiPolygon look like? Is it empty maybe?

**Comment by rowanwins** [comment]
Closing due to not enough information to followup on, and no response to previous request.
