### ISSUE TITLE
Opposite of turf-merge

### ISSUE THREAD

**Issue by rukku** [Turfjs/turf#234]
Given a multipolygon, return multiple features with single polygons. In GIS parlance, I think it's called multipart to single part

![illustration](http://help.arcgis.com/en/arcgisdesktop/10.0/help/0017/GUID-3D815089-E2EF-49F2-99DC-70E3D095C2BA-web.gif)

image from [ArcGIS Desktop docs](http://help.arcgis.com/en/arcgisdesktop/10.0/help/index.html#//00170000003r000000).

**Comment by tmcw** [comment]
This is [what geojson-flatten does](https://github.com/mapbox/geojson-flatten)

**Comment by rukku** [comment]
Wow. That's awesome! Will we just be point people to it then or will a turf module be needed(for consistency)?

**Comment by morganherlocker** [comment]
I think we should wrap geojson-flatten in a Turf module, so that it can be curated and documented consistently.

**Comment by lyzidiamond** [comment]
So in GIS land I've always seen this as "Explode multipart feature" but we already have turf-explode. FWIW that was confusing to me at first, as I thought turf-explode would have the functionality being discussed here.

**Comment by rukku** [comment]
@lyzidiamond Ditto. turf-explode's acts more like the explode in CAD programs or the [Feature to Points tool](http://resources.arcgis.com/en/help/main/10.1/index.html#//00170000003p000000) in ArcGIS.

![Feature to point tool](http://resources.arcgis.com/en/help/main/10.1/0017/GUID-271F6AEE-921A-4796-A6A1-D2887F749FE3-web.png)

00170000003p000000

**Comment by antoniolocandro** [comment]
I find it interesting the use of explode to convert feature vertices to points, I would expect explode to mean multipart to single part but if documented shouldn't be a problem

**Comment by devTristan** [comment]
:+1: turf module with geojson-flatten dependency would be great

**Comment by rowanwins** [comment]
This module now exists as [turf-flatten](http://turfjs.org/docs/#flatten) thanks to[ geojson-flatten](https://github.com/mapbox/geojson-flatten)
