### ISSUE TITLE
Build error SyntaxError: The requested module 'topojson-client' does not provide an export named 'merge' 

### ISSUE THREAD

**Issue by kylerchin** [Turfjs/turf#2356]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.
`^6.5.0`
Building inside react, got this error
```
22:19:32.698 | > Build error occurred
-- | --
22:19:32.700 | file:///opt/buildhome/repo/node_modules/@turf/concave/dist/es/lib/turf-polygon-dissolve.js:5
22:19:32.701 | import { merge } from "topojson-client";
22:19:32.701 | ^^^^^
22:19:32.701 | SyntaxError: The requested module 'topojson-client' does not provide an export named 'merge'
22:19:32.701 | at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
22:19:32.701 | at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
22:19:32.701 | at async Loader.import (internal/modules/esm/loader.js:179:24) {
22:19:32.701 | type: 'SyntaxError'
22:19:32.702 | }
```

**Comment by tmcw** [comment]
What bundler are you using?

Kind of seems like Turf shouldn't do what it's doing here, yet. `topojson-client` looks like it only provides a CommonJS export, so using a named import for it is going to be risky and it'll use a CJS-ESM compatibility hack. Probably better to just import the default  as `topojson` and use `topojson.merge`.

**Comment by kylerchin** [comment]
Sorry for the late reply! @tmcw  I'm writing a web app interactive map on Next.js

**Comment by kylerchin** [comment]
It seems like the compile works on my local compile but Cloudflare compilation is totally bricked.

**Comment by kylerchin** [comment]
nvm looks like I just had to switch node versions. closing this issue now
