### ISSUE TITLE
turf.area() is incorrect?

### ISSUE THREAD

**Issue by emorling** [Turfjs/turf#2358]
How can the first Polygon be bigger than the second? Its clearly contained within the first one?

```
const turf = require('@turf/turf');

const p1 = turf.polygon([
  [
    [0, 699.51],
    [1, 699.51],
    [1, 709],
    [0, 709],
    [0, 699.51],
  ],
]);
const p2 = turf.polygon([[[0, 198], [1, 198], [1, 709], [0, 709], [0, 198]]]);

console.log(turf.area(p1));
console.log(turf.area(p2));

```

This produces:

```
113058524993.11197
83928975209.03778
```

**Comment by stebogit** [comment]
Turf is based on [WGS84](https://github.com/Turfjs/turf#data-in-turf) coords, so you need to convert your values

**Comment by razzdasari** [comment]
Use **turf.area(plygon_trf)*0.993699583** , This value matches exactly with QGIS area
