### ISSUE TITLE
Missing buffers

### ISSUE THREAD

**Issue by seadour** [Turfjs/turf#236]
I'm trying to draw a 100-meter buffer around each of my points, but some of my points are missing their buffers. See this fiddle: https://jsfiddle.net/fq28yddb/

I can't see anything wrong with the points. Am I missing something?

**Comment by AbelVM** [comment]
Have you tried grouping your points in a [MultiPoint](http://geojson.org/geojson-spec.html#multipoint) type feature?

**Comment by tchannel** [comment]
this looks like it's the same issue as Turfjs/turf-buffer#12 and #228. This has been fixed already and will go out in the next master release of turf, and is already fixed in turf-buffer >= v1.0.2 if you are pulling in dependencies explicitly
