### ISSUE TITLE
opacity of the polygon

### ISSUE THREAD

**Issue by roshni-maheshwari** [Turfjs/turf#2362]
I want to add opacity to the polygon. but it is not working

this is my code 

`var polygon = turf.polygon([
[[-5, 52], [-4, 56], [-2, 51], [-7, 54], [-5, 52]]
],
 {
 color: "#668ac7", 
opacity: 0.5 }
);`

version is '^6.5.0'

**Comment by stebogit** [comment]
How is it not working exactly? What's the result and what would you expect instead?

**Comment by roshni-maheshwari** [comment]
i am giving some color to the polygon. i want to give some transparency

![image](https://user-images.githubusercontent.com/83489945/200157459-0f99bb71-a92b-4180-8397-9e3691aab5e1.png)

**Comment by stebogit** [comment]
The rendering result depends on the map, not turf. Is the property `opacity` present in the `properties` object of the polygon? That's all turf is expected to do.
If so, then check what's required by the map service you're using to change the opacity if the feature
