### ISSUE TITLE
turf.cleanCoords: can not clean the outer point of a polygon

### ISSUE THREAD

**Issue by touchpillow** [Turfjs/turf#2365]
## version
@turf/clean-coords 6.5.0

## case

this is my polygon's data
```javascript
{
  type: 'Feature',
  geometry: {
    type: 'Polygon',
    coordinates: [
      [
        [103.96545003739051, 1.339155872444735],
        [103.95134421483404, 1.3401468860256642],
        [103.95671303979519, 1.364473854034955],
        [103.92698061605779, 1.364473854034955],
        [103.9269292742105, 1.3418621732865432],
      ],
    ],
  },
  properties: {},
}
```
it's show as this 
![image](https://user-images.githubusercontent.com/32736204/200796619-2cb70296-1d07-46d3-abbb-647df9641873.png)

and I think the first point is extra, and I want to delete it , so I use cleanCoords, but it didn't work

## expect
I want to delete the first point ,so what can I do, should I use another function?

**Comment by stebogit** [comment]
Yours is an invalid polygon, in fact I wouldn't expect it rendered at all 
As per GeoJSON specs, a polygon coords array must contain at least four point coordinates where the first and last item must coincide.

At the same time clean-coords does not verify the validity of the input feature - like almost all turf packages that assume the data is valid.

**Comment by JamesLMilner** [comment]
Just to chime in here, as @stebogit mentions this Polygon geometry is invalid. You may want to look at the description and example for cleanCoords to get a better understanding of what it does, as I think even if your Polygon was valid that it may not be doing what you think it is: https://turfjs.org/docs/#cleanCoords

**Comment by touchpillow** [comment]
> Just to chime in here, as @stebogit mentions this Polygon geometry is invalid. You may want to look at the description and example for cleanCoords to get a better understanding of what it does, as I think even if your Polygon was valid that it may not be doing what you think it is: https://turfjs.org/docs/#cleanCoords.
> 
> If you are still having what you perceive to be bugs after fixing your polygon feel free to reopen an issue.

@JamesLMilner  @stebogit  I'm sorry that I provide a wrong data before.

this is a case 

```json
{
    "type": "Polygon",
    "coordinates": [
        [
            [
                100.5742008,
                14.0995467
            ],
            [
                100.5588208,
                14.0483645
            ],
            [
                100.5499477,
                14.054907
            ],
            [
                100.5533028,
                14.059284
            ],
            [
                100.5533028,
                14.0677336
            ],
            [
                100.5456881,
                14.0633165
            ],
            [
                100.5431427,
                14.0599245
            ],
            [
                100.5609054,
                14.0835954
            ],
            [
                100.5426971,
                14.0659637
            ],
            [
                100.5416379,
                14.0803197
            ],
            [
                100.5742008,
                14.0995467
            ]
        ]
    ]
}
```
![SeaTalk_IMG_1683772643](https://github.com/Turfjs/turf/assets/32736204/9b4e7b65-0aa5-46b9-8ce8-8440442c9fa7)

the point `[100.5431427,14.0599245]` is useless, right? and I try to use `cleanCoords` to delete it, but it not work.
I hope `cleanCoords` can resolve this case. or , how can I delete this point?

**Comment by stebogit** [comment]
@touchpillow as much as I can agree that point seems "wrong", I don't think `cleanCoords` should actually remove it as it is part of a valid polygon and it is not redundant to describe the polygon itself. In other words, if you removed the point the resulting polygon would not be equivalent to the original polygon, therefore `cleanCoords` would not simply clean the coordinates, but alter them. 

I can't think of a good way for programmatically identify/removing "outlier" points like that, I would probably look into the way the polygon was generated in the first place, and maybe avoid to create those unexpected points.

**Comment by touchpillow** [comment]
> @touchpillow as much as I can agree that point seems "wrong", I don't think `cleanCoords` should actually remove it as it is part of a valid polygon and it is not redundant to describe the polygon itself. In other words, if you removed the point the resulting polygon would not be equivalent to the original polygon, therefore `cleanCoords` would not simply clean the coordinates, but alter them.
> 
> I can't think of a good way for programmatically identify/removing "outlier" points like that, I would probably look into the way the polygon was generated in the first place, and maybe avoid to create those unexpected points.

yeah, we will change the shape  if we delete the point which I remarked, but this point is useless, right? and we may want to delete this point in some case.

actually, this polygon is generated by `turf/difference`, I guess it's caused by numerical precision. In addition , I think it's a common case, it may happened when user draw a polygon manually, so I want to delete the useless point automatically.

and, I have an idea about it.  if the second point is on the line of first and third point although it not between of those two points, so we can treat it as a redundant point, can I do it with this idea?

**Comment by stebogit** [comment]
Then I'm not sure what point you are referring to..
