### ISSUE TITLE
Question: booleanPointInPolygon

### ISSUE THREAD

**Issue by BekanFenris** [Turfjs/turf#2367]
Hello, I have a question regarding the booleanPointInPolygon. The function can take in multipolygons as an argument and return if a point lies in any of it. Is there a possiblity to have some sort of a callback as to for which polygon the function returns true for?

What I am trying to achieve is to filter my points ( 26k ) to their respective polygons

- Version: 6.5.0
- [](https://gist.github.com/BekanFenris/473e1af5d13dd0689bd80c662df38b2b)

**Comment by JamesLMilner** [comment]
Personally I would say this outside the scope of one of the boolean operations that Turf provides. The code you would need to determine which polygon the point is inside would be reasonably straight forward to implement by iterating through each polygon geometry in the MultiPolygon, turning it to a Polygon feature (You can use the [polygon](https://turfjs.org/docs/#polygon) function to achieve this.) and then running it to through `booleanPointInPolygon`.
