### ISSUE TITLE
PointToLinePoint

### ISSUE THREAD

**Issue by jfoclpf** [Turfjs/turf#2374]
We have point to line distance

```js
var pt = turf.point([0, 0]);
var line = turf.lineString([[1, 1],[-1, 1]]);

var distance = turf.pointToLineDistance(pt, line, {units: 'miles'});
//=69.11854715938406
```

But it would be useful and nice to know also which point is it along the line.

The point on the line corresponding to the shortest distance from point to line.

Something like

```js
var pt = turf.point([0, 0]);
var line = turf.lineString([[1, 1],[-1, 1]]);

var ptLine = turf.pointToLinePoint(pt, line);
//=[0,1]
```

**Comment by JamesLMilner** [comment]
Thanks for your suggestion - what you are asking for is supported by the [nearestPointOnLine](https://turfjs.org/docs/#nearestPointOnLine)

```javascript
var line = turf.lineString([
    [-77.031669, 38.878605],
    [-77.029609, 38.881946],
    [-77.020339, 38.884084],
    [-77.025661, 38.885821],
    [-77.021884, 38.889563],
    [-77.019824, 38.892368]
]);
var pt = turf.point([-77.037076, 38.884017]);

var snapped = turf.nearestPointOnLine(line, pt, {units: 'miles'});
```

It returns a GeoJSON point bu you can get the coordinates as `snapped.geometry.coordinates`. You can get additional information like teh line index, the distance and the distance along the line it was found:

```
 The properties object will contain three values: index : closest point was found on nth line part, dist : distance between pt and the closest point, location : distance along the line between start and the closest point.
```

**Comment by jfoclpf** [comment]
Thank you so much for the info @JamesLMilner
