### ISSUE TITLE
Union of multiple Features/polygons yet in version 6

### ISSUE THREAD

**Issue by jfoclpf** [Turfjs/turf#2377]
`turf-union` in all its docs mentions the union of only _two_ (multi)polygons or geojson's

https://www.npmjs.com/package/@turf/union

It would be nice and useful if we could unite several (multi)polygons or geojson's

```js
let union
union = turf.union(poly1, poly2)
union = turf.union(poly1, poly2, poly3)
union = turf.union(poly1, poly2, poly3, ..., polyn)

const polygons = [poly1, poly2, poly3, ..., polyn]
union = turf.union(...polygons)
```

**Comment by jfoclpf** [comment]
btw, I know I can do that recursively myself, but it would be useful to have that functionality out of the box under the hood

**Comment by jfoclpf** [comment]
apparently it is already possible, although docs in NPM are not that clear

**Comment by jfoclpf** [comment]
doesn't seem to work

**Comment by twelch** [comment]
Please provide a simple reproduceable example of your issue

**Comment by jfoclpf** [comment]
Basically it does not merge 3 or more polygons

```js
var poly1 = turf.polygon([[
    [-82.574787, 35.594087],
    [-82.574787, 35.615581],
    [-82.545261, 35.615581],
    [-82.545261, 35.594087],
    [-82.574787, 35.594087]
]], {"fill": "#0f0"});
var poly2 = turf.polygon([[
    [-82.560024, 35.585153],
    [-82.560024, 35.602602],
    [-82.52964, 35.602602],
    [-82.52964, 35.585153],
    [-82.560024, 35.585153]
]], {"fill": "#00f"});
var poly2 = turf.polygon([[
    [-82.560024, 35.585153],
    [-83.56004, 35.602202],
    [-83.52964, 35.602602],
    [-82.52964, 35.585153],
    [-81.560024, 35.585151]
]], {"fill": "#f00"});

var union = turf.union(poly1, poly2, poly3)
```

**Comment by jfoclpf** [comment]
I realized that in [version 7](https://github.com/Turfjs/turf/tree/master/packages/turf-union) you'll allow union of multiple polygons via `featureCollection`

```js
var poly1 = turf.polygon([[
    [-82.574787, 35.594087],
    [-82.574787, 35.615581],
    [-82.545261, 35.615581],
    [-82.545261, 35.594087],
    [-82.574787, 35.594087]
]], {"fill": "#0f0"});
var poly2 = turf.polygon([[
    [-82.560024, 35.585153],
    [-82.560024, 35.602602],
    [-82.52964, 35.602602],
    [-82.52964, 35.585153],
    [-82.560024, 35.585153]
]], {"fill": "#00f"});

var union = turf.union(turf.featureCollection([poly1, poly2]));

//addToMap
var addToMap = [poly1, poly2, union];
```

I understand it's a breaking change, thus new major version, but it would be much easier, without breaking change, to allow 

```js
let union
union = turf.union(poly1, poly2)
union = turf.union(poly1, poly2, poly3)
union = turf.union(poly1, poly2, poly3, ..., polyn)

const polygons = [poly1, poly2, poly3, ..., polyn]
union = turf.union(...polygons)
```

**Comment by jfoclpf** [comment]
A workaround yet in version 6 is to use `reduce`

```js
const polygons = [poly1, poly2, poly3, ..., polyn]
const union = polygons.reduce((a, b) => turf.union(a, b), polygons[0])
```

But is way too slow

**Comment by JamesLMilner** [comment]
I do not believe there will be any attempts to backport this to version 6, as it is an API breaking change.

**Comment by jfoclpf** [comment]
It is not a breaking change in the way I showed

**Comment by jfoclpf** [comment]
@JamesLMilner maybe I was not clear enough

In version 6 `union` accepts 3 parameters, the first 2 parameters being each a (Multi)Polygon Feature and the third parameter being an `options` JS Object. 

It would be perfectly feasible to detect in a multitude of input parameters whether a certain parameter is the `options` Object or a (Multi)Polygon Feature.

Current function API would perfectly still work

```js
turf.union(poly1, poly2, options)
```

But furthermore this would also work

```js
turf.union(poly1, poly2, poly3, options)
turf.union(poly1, poly2, poly3, ..., polyN, options)
```

Thus, no breaking change, just a minor version change according to Semver.

I would do a PR but I am not versed in Typescript.
