### ISSUE TITLE
Simplify creates invalid polygons with 3 points because cleanCoords removes too many points

### ISSUE THREAD

**Issue by Kilowhisky** [Turfjs/turf#2378]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions (6.5.0)
- [x] GeoJSON data as a https://gist.github.com/Kilowhisky/5f3a5e3b7c3467a7913a19785c702cc3
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

```
simplify(feature, {
            tolerance: 0.01,
            highQuality: true,
            mutate: true
});
```

```
Error: invalid polygon
    at file:///C://node_modules/@turf/simplify/dist/es/index.js:257:13
    at Array.map (<anonymous>)
    at simplifyPolygon (file:///C://node_modules/@turf/simplify/dist/es/index.js:252:22)
    at file:///C://node_modules/@turf/simplify/dist/es/index.js:215:16
    at Array.map (<anonymous>)
    at simplifyGeom (file:///C://node_modules/@turf/simplify/dist/es/index.js:214:45)
    at file:///C://node_modules/@turf/simplify/dist/es/index.js:169:5
    at geomEach (file:///C://node_modules/@turf/meta/dist/es/index.js:590:13)
    at simplify$1 (file:///C://node_modules/@turf/simplify/dist/es/index.js:168:3)
    at _getAlertFeatureCollection (file:///C://handler.js:113:9)   
```

It seems that internally `turf.simplify` calls `cleanCoords`. It appears that `cleanCoords` will remove duplicates so much that it will make polygons invalid by reducing them below the 4 point minimum.  

As a bonus here is the raw GeoJSON that the above Gist was constructed out of by the `truncate` and `union` function. What I was attempting to do was combine all polygons and simplify to make the object easier to render.
https://gist.github.com/Kilowhisky/bd1b46f162aac622c5a77dfebb709d5e

**Comment by smallsaucepan** [comment]
Hi @Kilowhisky. Realise it's been a while. However, were you aware the first polygon in your example might be problematic?

```
[
  [
    [
      [
        -135.7173, 59.73 <--- same
      ],
      [
        -135.7207, 59.7291
      ],
      [
        -135.7173, 59.73 <--- same
      ],
      [
        -135.7173, 59.73 <--- same
      ]
   ]
]
```

Remove that and the simplification proceeds:

![Screenshot 2024-10-13 at 10 42 16 PM](https://github.com/user-attachments/assets/47eb8b10-93d8-4dc0-b7c1-d7df8ae65e18)

**Comment by smallsaucepan** [comment]
Closing as believe this is an issue with bad data i.e. passing an invalid polygon a-b-a-a. Please reopen if further test cases come to light.
