### ISSUE TITLE
CDN link out of date

### ISSUE THREAD

**Issue by duncangraham** [Turfjs/turf#238]
The CDN link on http://turfjs.org/ says 1.4.0 though turf is at v2.0.0 now.

It'd be super helpful to add something like the npm version badge to the github readme too a la https://github.com/teelaunch/npm-version-badge

**Comment by lyzidiamond** [comment]
Updated the website to 2.0.0.

@morganherlocker what do you think about the npm version badge?

**Comment by morganherlocker** [comment]
Great idea. Done:

![](https://dl.dropbox.com/s/brfkmwntakxrpa7/Screenshot%202015-03-18%2014.30.24.png?dl=0)

**Comment by enjalot** [comment]
Is there a 3.0 cdn link yet?
