### ISSUE TITLE
Self-intersecting polygon has wrong area

### ISSUE THREAD

**Issue by sigorilla** [Turfjs/turf#2383]
Self-intersecting polygon has wrong area. It cannot be zero:

- [x] Version: `@turf/area@6.5.0`.
- [x] GeoJSON data as a [gist file](https://gist.github.com/): https://gist.github.com/sigorilla/e0f97a91e579bc1f27e4a950352a29ae
- [x] Snippet of source code: https://runkit.com/sigorilla/turf-area-self-intersecting/2.0.0

**Comment by JamesLMilner** [comment]
Interesting - I'm not sure what the deal is in terms of if `area` supports self intersecting polygons. Would probably defer to @rowanwins on this one.

**Comment by sigorilla** [comment]
I think we can close this issue, because I found `@turf/unkink-polygon`.

```
import * as turf from '@turf/turf';
import unkinkPolygon from '@turf/unkink-polygon';

// Define a self-intersecting polygon
const polygon = turf.polygon([[
    [0, 0],
    [5, 0],
    [2.5, 5],
    [0, 0]
]]);

// Split the polygon into non-self-intersecting polygons
const nonIntersectingPolygons = unkinkPolygon(polygon);

// Calculate the total area
const totalArea = turf.area(nonIntersectingPolygons);

console.log(totalArea);
```
