### ISSUE TITLE
Undefined length error when using booleanPointInPolygon function

### ISSUE THREAD

**Issue by secondl1ght** [Turfjs/turf#2388]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions. - **6.5.0**
- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`). - https://gist.github.com/secondl1ght/a902b36dac2379fead3452af49a77973
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/). - 
```
booleanPointInPolygon([long, lat], community.geo_json)
```

Hello, I am attempting to use the `booleanPointInPolygon` Turf function to determine if a point is inside a polygon. I am passing it a lat/long as the first parameter and a GeoJSON polygon as the second. I am getting the following error when running the code:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
```

It is happening in this file in the node module: `@turf/boolean-point-in-polygon/dist/es/index.js` at line 52 which is this code: 
```
for (var i = 0; i < polys.length && !insidePoly; i++) {
```

Am I doing something wrong when calling this function? Please see the attached GeoJSON to see what I am passing into the polygon parameter. Somehow `polys` does not have a `length` key.

Any help would be appreciated, thanks!

**Comment by JamesLMilner** [comment]
By the looks of it you are passing in a FeatureCollection when `booleanPointPolygon` expects a Feature<Polygon> or Feature<MultiPolygon>

You will need to access the features property, probably something like the following in your case:

```javascript
booleanPointInPolygon([long, lat], featureCollection.features[0])
```

Where featureCollection is the root object in the GeoJSON you posted

**Comment by benjosua** [comment]
I'm encountering the same error when running the following code:

```
booleanPointInPolygon([Longitude, Latitude], [
  [-81, 41],
  [-81, 47],
  [-72, 47],
  [-72, 41],
  [-81, 41]
]);
```

Is there anything I am missing?
