### ISSUE TITLE
Turf JS in Web worker Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by hrishiballal** [Turfjs/turf#239]
Hello, 
I am using Turfjs in a web worker and I am getting a maximum call stack size exceeded (both in Firefox and Chrome) in some laptops with 4GB RAM. I reviewed my code to check for any recursion but there does not seem to be an issue there since it is working on larger more powerful computers. 

I was wondering if there is a way to split up turf for the browser in to different modules like you enable on npm. 

Any guidance how to avoid this error?

**Comment by morganherlocker** [comment]
This is most likely an issue with a large dataset. Do you mind posting the code that is causing the issue along with the dataset in a gist?

**Comment by hrishiballal** [comment]
Thanks for your help. I am working with 10 1MB geoJSON files (gj) and another file that has just one feature (f) inside it also in Geojson. The single feature file needs to intersect with the 10. so the following: 
each of gj1 gj2 gj3 gj4 gj5 gj6 gj7 gj8 gj9 gj10 intersects with f1. 

**Impacted Browser**: Chrome 
OK on IE and Firefox

More Details: 
1) Works on more powerful computers, seems like it is a RAM issue. e.g. it works on i7 with 8GB RAM, i5 / 8GB iMac but does not work on i5 with 4GB RAM or i7 with 4GB RAM. 
2) Its works fine when not in a web worker i.e. the main window. Of course the User interface locks up. 
Chrome Error window: 
![turfjs](https://cloud.githubusercontent.com/assets/1588744/6749867/83c76738-ceec-11e4-97db-a142b9cde458.png)

What I have tried: 
1) Used browserify to build a standalone module with turf-intersect and turf-area, but because of the JSTS dependency, the standalone is not that much smaller, it is giving the same issue. 
2) Used inline webworkers to see if it makes a difference, no such luck. 
3) I tried to pass reduced data one 1MB geoJSON and the feature (to reduce data footprint) and even two small geojson files but again it is not working on Chrome but OK on IE and Firefox. 

Maybe it is a Chome web worker issue? Can someone try to use importScript() in webworker in Chrome and repro this on "slower" computers?

**Comment by tmcw** [comment]
@hrishiballal happy to debug this if you can provide a testcase, like a jsfiddle or gist, that demonstrates it. Otherwise this is hard for me or other maintainers to generate the error ourselves and work to fix it.

**Comment by kekscom** [comment]
Hi,
I'm hit by the same issue. Find a test case here: `http://keks.com/dev/cm/` Check console.
Thanks for looking into it.

**Comment by morganherlocker** [comment]
> ReferenceError: javascript is not defined ---  turf.min.js:3

Thanks for posting the example @kekscom. Looks like you possibly have a dependency or browserify issue going on with your turf build? I am getting an undefined module error.

**Comment by kekscom** [comment]
Ok I'm pulling my example.
Had a bug in my code and I'm using the unpkg 3.5.2 version now.
All fine for me. Thanks!

**Comment by rowanwins** [comment]
Closing due to age and lack of details to followup on
