### ISSUE TITLE
Add booleanTouches to docs

### ISSUE THREAD

**Issue by bloigge** [Turfjs/turf#2398]
Hi,

This is more a feature request than an issue. Following a question I wrote a few days ago on [gis.stackexchange](https://gis.stackexchange.com/questions/451921/detect-if-features-are-next-to-each-other-but-not-overlapping-using-turf-js/452034#452034) , I would like to detect if two features are only sharing one or more edges but do not overlap using Turf.js.

An already working answer was given. Maybe it is worth integrating it as a boolean function "booleanTouches".

**Comment by rowanwins** [comment]
There is actually a [boolean-touches module](https://www.npmjs.com/package/@turf/boolean-touches) in turf that's published on NPM, it's just not shown in the docs so I'll create a PR to add it in.
