### ISSUE TITLE
booleanEqual reports false for equal coordinates

### ISSUE THREAD

**Issue by Tomalak** [Turfjs/turf#2401]
I'm using Turf 6.5.0.

The [documentation for `booleanEqual`](https://turfjs.org/docs/#booleanEqual) states

> `booleanEqual`  
> 
> Determine whether two geometries of the same type have identical X,Y coordinate values. 

And yet:

```js
const p1 = turf.point([0, 0], {prop: 'A'});
const p2 = turf.point([0, 0], {prop: 'B'});

console.log(turf.booleanEqual(p1, p2)); // -> false
```

The way I understand it, properties should not be taken into account when comparing point equality.

That, or the documentation needs a clarification.

**Comment by smallsaucepan** [comment]
Thanks for raising this @Tomalak. Fix for this should be in the latest v7 alpha if you'd like to try it out.
