### ISSUE TITLE
Coordinates are not included in the features returned by the isobands method

### ISSUE THREAD

**Issue by rd-atmosphericg2** [Turfjs/turf#2405]
There are no coordinates in the features that are returned by the isobands method. Having the coordinates would allow for labels to be placed near the isolines that are between the isobands. For example, the value for an isoline is frequently included in a plot of temperature isobands. If the coordinates were present in the returned feature, then they could be used to generate labels for the isolines as was suggested as a solution to [Discussion #2404](https://github.com/Turfjs/turf/discussions/2404).

**Comment by stebogit** [comment]
@rd-atmosphericg2 please add a snippet of code highlighting the issue

**Comment by rd-atmosphericg2** [comment]
[snippet.html.gz](https://github.com/Turfjs/turf/files/10863771/snippet.html.gz)

**Comment by smallsaucepan** [comment]
Hi @rd-atmosphericg2 Would you mind describing how you see this behaving in relation to the example map below? The geojson to produce this is generated from the bigMatrix test case, and can be found [here](https://github.com/Turfjs/turf/blob/e5afd5c38b0f8422172a3c64ca14118bd138b54e/packages/turf-isobands/test/out/bigMatrix.geojson).

<img width="781" alt="Screenshot 2023-11-01 at 10 42 07 pm" src="https://github.com/Turfjs/turf/assets/5403628/9124f8d6-7548-423d-9842-f92318b012f3">

What would you need visible on the map or available in the geojson that would meet your need?

**Comment by rd-atmosphericg2** [comment]
Hi @smallsaucepan , if I navigate to your "[here](https://github.com/Turfjs/turf/blob/e5afd5c38b0f8422172a3c64ca14118bd138b54e/packages/turf-isobands/test/out/bigMatrix.geojson)" address, click the Code button, and examine the geojson, then I believe the geojson shows the coordinates of the polygons. The outer edges of the polygons can now be labeled with the pressure that is encapsulated in the geojson, e.g.:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "stroke-width": 4,
        "fill-opacity": 0.4,
        "stroke": "grey",
        "fill": "grey",
        "pressure": "0-0.24"
```

The dark/bold blue isoline (between grey and blue polygons) represents pressure 0.24, so a label of 0.24 would be placed close to the blue isoline.
The dark/bold green isoline (between blue and green polygons) represents pressure 0.5, so a label of 0.5 would be placed close to the green.
...
The dark/bold red isoline (between yellow and red polygons) represents pressure 2.5, so a label of 2.5 would be placed close to the red line.

Those labels tell the viewer what the pressure is along the isoline (along that edge of the polygon). For example, see the magenta label at the top of the graphic that appears below. The graphic is from https://origin.wpc.ncep.noaa.gov/basicwx/basicwx_ndfd.php, and the black isolines in the graphic represent mean sea level pressure. The magenta label indicates that the mean sea level pressure along that edge of the polygon is 1012 (millibars).

The placement of the labels would be done as suggested by twelch in the [original discussion](https://github.com/Turfjs/turf/discussions/2404).

![image](https://github.com/Turfjs/turf/assets/87216464/c2acd521-dccc-43bb-9308-05b0a3f281d8)

**Comment by smallsaucepan** [comment]
Thanks for providing that detail. So, is the crux of your problem that _your_ data doesn't look like the test case data above? I haven't been able to get your code snippet to work. Are you able to provide a minimal code snippet (that doesn't depend on mapbox, etc)?

Perhaps post a simple snippet of code that shows the values you are passing in to the isoBands function, and the raw geojson that comes out.

**Comment by smallsaucepan** [comment]
Closing this as haven't heard any further on it, and it appears to be a presentation issue that is out of Turf's hands. Please reopen if more info becomes available.
