### ISSUE TITLE
turf-constrainedtin

### ISSUE THREAD

**Issue by AbelVM** [Turfjs/turf#241]
Looking for a constrained Voronoi/Delaunay method to get tin grids within polygons, found [poly2tri](https://code.google.com/p/poly2tri/), based on the paper **"Sweep-line algorithm for constrained Delaunay triangulation"** by V. Domiter and and B. Zalik. This library takes into account concavities and holes, and once you have this tin, its *easy* to get the constrained Voronoi diagram for your polygon.

There is a JavaScript port called [poly2tri.js](https://github.com/r3mi/poly2tri.js), and I have made a simple wrapper to make it work with GeoJSON. This is my proposal as a module, but it may/should be merged with [turf-tin](https://github.com/Turfjs/turf-tin) as an overload:
![restrictedtin](http://i62.tinypic.com/9fo7r9.png)

```javascript
/**
*	turf.constrainedtin
*	Function that gets a {@link Polygon} and make a tin constrained to it
* @requires	http://r3mi.github.io/poly2tri.js/dist/poly2tri.js
* @param {Feature<(Polygon)>} poly - single Polygon Feature
* @return {FeatureCollection<(Polygon)>} 
* @author	Abel Vázquez
* @version 1.0.0
*/
turf.constrainedtin = function(poly){
	
	// check poly is a polygon
	if (poly.geometry === void 0 || poly.geometry.type !== 'Polygon' ) throw('"constrainedtin " only accepts polygon type input');
	
	var	triangles,
			ctx =  input.geometry.coordinates.map(function(a){
				var c = a.map(function(b){
					return new poly2tri.Point(b[0], b[1])
					});
				c.pop();
				return c;
				}),
			swctx = new poly2tri.SweepContext(ctx.shift()),
			features;
			
	if (ctx.length>0) swctx.addHoles(ctx);
	
	triangles = swctx.triangulate().getTriangles();
	
	features = triangles.map(function(t){
		var points =[];
		 t.getPoints().forEach(function(p) {
			points.push([p.x, p.y]);
		});
		points.push([t.getPoint(0).x, t.getPoint(0).y])
		return turf.polygon([points]);
	});
	
	return turf.featurecollection(features);
	
}
```

**Comment by morganherlocker** [comment]
Very awesome work @AbelVM! Have you looked at wrapping @mourner's [earcut](https://github.com/mapbox/earcut), instead of poly2tri? The [benchmarks and tests comparing the two](https://github.com/mapbox/earcut#why-another-triangulation-library) seem to put earcut on top.

Also, it works a bit differently, but [turf-concave](http://turfjs.org/static/docs/module-turf_concave.html) does an edge distance filter for tight control on a set of points, as opposed to a polygon (possibly helpful).

**Comment by AbelVM** [comment]
**You're right!** :pensive: 
I already did know earcut, but... you know when you're so focused looking for something so specific that you miss the landscape? Something like tunnel vision. Well, may be that sounds a bit psycho, but that was the reason I didn't think of earcut at first. I was looking for a solution for a very different problem, and I found poly2tri in my way.

With @mourner 's earcut, the wrapper is even cleaner:
```javascript
/**
*	Function that gets a {@link Polygon} and make a tin constrained to it using [earcut.js]{@link https://github.com/mapbox/earcut}
* @requires	earcut.js
* @param {Feature<(Polygon)>} poly - single Polygon Feature
* @return {FeatureCollection<(Polygon)>} 
* @author	Abel Vázquez
* @version 1.0.0
*/
turf.earcut = function(poly){
	// check poly is a polygon
	if (poly.geometry === void 0 || poly.geometry.type !== 'Polygon' ) throw('"earcut" only accepts polygon type input');
	var 
		t = earcut(poly.geometry.coordinates),
		p,
		f=[];
	for (var i=0; i<t.length-2; i+=3){
		p = [t[i], t[i+1],t[i+2], t[i]];
		f.push(turf.polygon([p]));
	}
	return turf.featurecollection(f);
}

```
 With my testcase:
```javascript
var input = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-0.9427527769617423,38.08430116991525],[-0.9427452685370704,38.084368506535974],[-0.9427416004878013,38.08439686415331],[-0.9427402899960862,38.084396841202945],[-0.9427361729759206,38.084397697273275],[-0.9427317521356767,38.084430132867716],[-0.9427301805160633,38.08443576448326],[-0.9427284953454541,38.08444015955275],[-0.9427259196178825,38.08444541312866],[-0.9427231235197967,38.084449986992574],[-0.9427189896589614,38.08445551065594],[-0.9427149195264595,38.08445998110519],[-0.9427116745738647,38.08446307825502],[-0.942705806747771,38.08446782360734],[-0.9426960100992162,38.08447403208582],[-0.9426900210799745,38.08447700007537],[-0.9426840003654643,38.08447947188428],[-0.9426868275525654,38.08445548807934],[-0.9426515099339366,38.084452932103545],[-0.9426484239850931,38.08447760525101],[-0.9426820654532861,38.0844801679184],[-0.9426718355048703,38.08448312471385],[-0.9426610531658872,38.084485044538184],[-0.9426505419495464,38.08448583367749],[-0.9426414135743397,38.08448569182948],[-0.9426303547006231,38.08448446184048],[-0.9426184810543683,38.08448179378453],[-0.9426072596375722,38.084477821490815],[-0.9425984198680014,38.084473485396686],[-0.9425888797556935,38.08446728970565],[-0.9425832084348772,38.084462585568566],[-0.9425789707187581,38.084458393153476],[-0.9425831514013416,38.084423952835884],[-0.9425847328622783,38.08442407064745],[-0.9425860850289219,38.084413253653956],[-0.9425977736455919,38.084413981028355],[-0.942597950224223,38.08441174930172],[-0.9425984571524803,38.08441115441842],[-0.9425995294123436,38.084399341271954],[-0.9425879476508997,38.084398462575955],[-0.9425665362704758,38.08439683499311],[-0.9425659575629763,38.08439917682447],[-0.9425597573254594,38.08439869876556],[-0.9425678062557649,38.08433364249022],[-0.9427527769617423,38.08430116991525]],[[-0.9426585021528952,38.08439547192084],[-0.9426937739094717,38.08439803610242],[-0.942698823635133,38.08435740216687],[-0.942663488321896,38.08435466565792],[-0.9426585021528952,38.08439547192084]],[[-0.9426179689178278,38.0843674846249],[-0.9426201824146914,38.08434831115516],[-0.9426082681692844,38.084347498729144],[-0.9426061941938553,38.08436657551714],[-0.9426179689178278,38.0843674846249]]]}};
```
Same number of cells (54), both looks topologically valid, but... we different cells set:
![poly2tri vs earcut](http://i60.tinypic.com/2rykkgi.png)
If we need this tin to get Voronoi cells, maybe we need some validity check first. Not sure if earcut algorithm strictly meets the Delaunay Condition. As far as I know, the solution is unique, so both grids should be the same.

**Comment by mourner** [comment]
@AbelVM it doesn't meet Delaunay — it's an advanced form of ear clipping.

**Comment by AbelVM** [comment]
@mourner , then, briefly:
1. **earcut** => constrained tin, fast as :zap:
2. **poly2tri** => constrained Delaunay => constrained Voronoi

I find both of them very useful, each one has its own target and would be nice to have them in TURF ecosystem.

**Comment by morganherlocker** [comment]
Ok, how does this sound?

- poly2tri is wrapped for turf-tin-constrained
- earcut gets wrapped with turf-tesselate

@AbelVM I will send you an invite to the Turfjs github org so you can create repos. Ping me when you feel things good for review, and I will assist getting this merged into the turf master lib.

**Comment by AbelVM** [comment]
What about a merge?
```javascript
/**
*	turf.constrainedtin
*	Function that gets a {@link Polygon} and make a tin constrained to it using Poly2tri or Earcut
* @requires	[poly2tri.js]{@link http://r3mi.github.io/poly2tri.js/dist/poly2tri.js}
* @requires	 [earcut.js]{@link https://github.com/mapbox/earcut}
* @param {Feature<(Polygon)>} poly - single Polygon Feature
* @param {Boolean} delaunay - retrieves a Delaunay triangulation
* @return {FeatureCollection<(Polygon)>} 
* @author	Abel Vázquez
* @version 1.0.0
*/
turf.constrainedtin = function(poly, delaunay){
	if (poly.geometry === void 0 || poly.geometry.type !== 'Polygon' ) throw('"polygonreduce" only accepts polygon type input');
	delaunay = (delaunay!==void 0)? delaunay : false;
	var features =[];
	if (delaunay===true){
		var	triangles,
				ctx =  input.geometry.coordinates.map(function(a){
					var c = a.map(function(b){
						return new poly2tri.Point(b[0], b[1])
						});
					c.pop();
					return c;
					}),
				swctx = new poly2tri.SweepContext(ctx.shift());		
		if (ctx.length>0) swctx.addHoles(ctx);
		triangles = swctx.triangulate().getTriangles();
		features = triangles.map(function(t){
			var points =[];
			 t.getPoints().forEach(function(p) {
				points.push([p.x, p.y]);
			});
			points.push([t.getPoint(0).x, t.getPoint(0).y])
			return turf.polygon([points]);
		});
	}else{
		var 
			t = earcut(poly.geometry.coordinates),
			p;
		for (var i=0; i<t.length-2; i+=3){
			p = [t[i], t[i+1],t[i+2], t[i]];
			features.push(turf.polygon([p]));
		}
	}	
	return turf.featurecollection(features);
}
```

**Comment by AbelVM** [comment]
@morganherlocker Ok, thanks

**Comment by morganherlocker** [comment]
@AbelVM merging is a possibility, but I tend to lean towards discrete functions. It reduces size at the module level for people doing pick-and-choose dependencies, plus it makes the api a bit cleaner and easier to document IMO. With algorithm-specific flags, many people will choose at random without understanding the implications, so I prefer functions to self-document if possible.

**Comment by AbelVM** [comment]
Right

**Comment by tchannel** [comment]
:+1: awesome work @AbelVM

**Comment by AbelVM** [comment]
I have lost all this week' work due to a series of unfortunate events (HD fail, backup fail,  local sync repo fail...) before I commit to GitHub... I was working in a Voroni implementation for Turf... :weary:

By the way, looks like poly2tri still can't get proper constrained Delaunay tin, at least with my test case. And due tu Turfjs#248, I can't test if simplifying could help or not. So... as soon I manage to start up my Delorean to get to the point I before everything crashed, I will post some interesting code.

**Comment by AbelVM** [comment]
Got most of my code back! 

But, not last tweaks... I'm missing something
![voronoi](http://i61.tinypic.com/nq8oyg.png)

Waiting for Turfjs#248 to make further testing. Meanwhile, I will keep on tweaking.

**Comment by AbelVM** [comment]
Almost there:
![voro2](http://i57.tinypic.com/sdi54h.png)
Restricted (conformed) Delaunay grid (red) and its dual form, Restricted Voronoi (blue)
Just a "little" issue with some concavities/holes, as you can see, will fix it next. As well as peformance issues: now it's not as fast as I would like.

**Comment by morganherlocker** [comment]
whoa, this looks awesome!

**Comment by AbelVM** [comment]
**...it's getting better!**

And faster! But due to its improved accuracy it needs to manage a lot of Delaunay triangles now (today I generate ~700 Delaunay cells where yesterday we had ~40 cells), so it takes a while to retrieve the Voronoi diagram .
![voro](http://i58.tinypic.com/2iagbwn.png)
Limitations of poly2tri itself and the logic behind, force to set aside some of the cells. There are cells that need further proccessing, but **poly2tri** tells me that some points are collinear and that's all, folks. This test case gives me 18 triangles out of 697 that, being Delaunay compliant, can't be used to generate the constrained Voronoi (green cells).

As soon as I clean the code, and do some fine tuning, I will commit all this abracadabra stuff and I hope that someone could find the way to refine it even more.

I'm thinking about init the polygon with midpoints in each segment. That's cheating, I know, but...

**Comment by AbelVM** [comment]
Commited **turf-tin-constrained** and **turf-tesselate**

Next step: clean turf-voronoi-constrained

**Comment by tchannel** [comment]
I'm closing this, as the proposed modules have been created. We'll look at working these into a release once they're all cleaned up and tested.

Thanks @AbelVM for the awesome work :metal:
