### ISSUE TITLE
[security] Set minimum permissions for workflows

### ISSUE THREAD

**Issue by gabibguti** [Turfjs/turf#2413]
Setting minimum permissions for workflows is important to keep your repository safe against supply-chain attacks. Workflows are given a GITHUB_TOKEN to run actions. The issue is that this [GITHUB_TOKEN is granted higher permissions than necessary by default](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), making way to attacks.

I see you have one workflow in the repository, `turf.yml`, and it needs only `contents: read` permission to read the repository code to perform `actions/checkout`, `actions/setup-node` and `actions/cache`. If you agree with setting this minimum permissions, I can open a PR!

This setting is considered good-practice and recommended by GitHub itself and by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional context
About me, I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

I'm not providing required informations such as version of Turf, GeoJSON and code snippets because this is a security related issue not a bug.

**Comment by JamesLMilner** [comment]
Hi @gabibguti - thank you for raising this. This sounds sensible to me, please feel free to raise a PR with the intended changes.

Let me know if there's anything we need to do on our side to assist.

**Comment by JamesLMilner** [comment]
This is merged now. Thank you @gabibguti !

I found this reference helpful for anyone trying to get a better understanding of this change:

https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
