### ISSUE TITLE
Error with TypeScript 5

### ISSUE THREAD

**Issue by httpete** [Turfjs/turf#2414]
Seems that something would be easy to fix:

```
error TS7016: Could not find a declaration file for module '@turf/turf'. 'node_modules/@turf/turf/dist/es/index.js' implicitly has an 'any' type.
  There are types at 'node_modules/@turf/turf/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/turf' library may need to update its package.json or typings.

**Comment by httpete** [comment]
Note the latest PR that merged would fix this.

**Comment by JamesLMilner** [comment]
Agree that in theory releasing a new version of 7.x would now fix this issue after this PR: https://github.com/Turfjs/turf/pull/2400

**Comment by Radik24** [comment]
Hi, any ETA for 7.x? Thanks

**Comment by rumsky** [comment]
Adding  "noImplicitAny": false in tsconfig.json,  fixes things for me temporarily.
` "noImplicitAny": false,`

**Comment by studnitz** [comment]
If you are using `pnpm`, you can use `pnpm patch` to patch the dependencies yourself, it is a bit tedious though (but could be automated further).

To patch for example `@turf/bbox` you run 
`pnpm patch @turf/bbox`

Then you add the missing `types` specifier to the `package.json` `exports`.

```diff
"exports": {
     "./package.json": "./package.json",
     ".": {
+      "types": "./dist/js/index.d.ts",
       "import": "./dist/es/index.js",
       "require": "./dist/js/index.js"
     }
```

Finally you run the provided `pnpm patch-commit ...` command that `pnpm patch` gave you. 

Give your IDE a reload and it should work then.

**Comment by kevinschaich** [comment]
`npm i @turf/turf@7.0.0-alpha.2` did the trick for me

**Comment by emekaokoli** [comment]
> ```diff
> "types": "./dist/js/index.d.ts"
> ```

pnpm worked, how can I do it with npm? I have another project using turf with the same issue but using npm.

**Comment by studnitz** [comment]
> > ```diff
> > "types": "./dist/js/index.d.ts"
> > ```
> 
> pnpm worked, how can I do it with npm? I have another project using turf with the same issue but using npm.

You could use https://github.com/ds300/patch-package instead

**Comment by wmonecke** [comment]
@kevinschaich how do you import the type `Point` in 7.0.0? Cant manage to do it.

**Comment by twelch** [comment]
@wmonecke you can import base types from @types/geojson
