### ISSUE TITLE
Docs site isn't working well on mobile

### ISSUE THREAD

**Issue by HarelM** [Turfjs/turf#2418]
I love turf, it's great!
When I want to read its docs using a mobile device it's almost impossible though... 😪

**Comment by HarelM** [comment]
![Screenshot_20230325_175543_Chrome](https://user-images.githubusercontent.com/3269297/227724934-a8c1a1f5-8895-4af8-934b-5460b55e2e5f.jpg)

**Comment by JamesLMilner** [comment]
Thanks for raising, yes it is unfortunate that the site does not currently work well on mobile. We would appreciate a PR to resolve this if anyone is open to raising one.

**Comment by HarelM** [comment]
Shouldn't this ticket be transferred to www-turf repo then? I got confused when I tried to find how the docs are being created using this repo...

**Comment by JamesLMilner** [comment]
Yeah, there is actually an existing issue there (https://github.com/Turfjs/turf-www/issues/136) so I will close this. Thanks!
