### ISSUE TITLE
All submodules which have a nested dependency on javascript.util are broken for fresh installs

### ISSUE THREAD

**Issue by robludwig** [Turfjs/turf#242]
The latest build of bjornharrtell/javascript.util has a [breaking bug](https://github.com/bjornharrtell/javascript.util/issues/10) that was missed by tests. Any submodule which uses jsts depends on javascript.util which has a floating dependency "~0.12.5" in their package.json  that installs the latest version, which means they are broken. It appears that the developer is on vacation but should be back next week.

Since this is a dependency of a dependency, I don't believe there's any fix that can be done to turf modules to fix the bug. Please correct me if I'm wrong on that point.

As a workaround, the following steps fixed my install of turf-buffer:

1) rm -rf the node_modules folder found in turf-buffer/node_modules/jsts/
2) edit turf-buffer/node_modules/jsts/package.json to change the javascript.util dependency version from  "~0.12.5" to  "0.12.5", removing the tilde.
3) cd turf-buffer/node_modules/jsts/ and run npm install with the new package.json. this will install javascript.util version 0.12.5 instead of the broken 0.12.7.

This should work, mutatis mutandis, with any other turf sub-modules.

**Comment by robludwig** [comment]
A more effective/permanent solution is also to use [npm-shrinkwrap](http://blog.nodejs.org/2012/02/27/managing-node-js-dependencies-with-shrinkwrap/) on the repo and set the specific (sub)dependencies to working versions

**Comment by deromemont** [comment]
Same problem with
* turf-intersect
* turf-union
* turf-buffer

**Comment by morganherlocker** [comment]
yep, working on shrinkwrapping this. I'll update when it's ready

**Comment by morganherlocker** [comment]
ok we are back up and running with turf@2.0.2. https://travis-ci.org/Turfjs/turf/builds/55564541

The issue was with the latest version of javascript.utils, which is doing some black magic with bower, the closure compiler, grunt, and node. That should be fixable upstream, but this solution works for now in turf. I locked all versions to 0.12.5.

**Comment by deromemont** [comment]
Thx
