### ISSUE TITLE
booleanIntersects returns false even though features visually intersect 

### ISSUE THREAD

**Issue by noisyneuron** [Turfjs/turf#2424]
In using `booleanIntersects` for a line and polygon, it appears that the geodesic/rhumb(?) line is used for calculation rather than the visual line 

In the screenshot, the smaller polygon (poly1) returns `false` where as the larger one (poly2) returns `true`. Code sandbox: https://codesandbox.io/s/turftests-zbnhot?file=/src/index.js

<img width="798" alt="Screen Shot 2023-04-04 at 12 30 50 PM" src="https://user-images.githubusercontent.com/1571964/229857691-6f0412e3-09b2-452b-af87-5bf494f598b4.png">

Turf v6.5.0

**Comment by JamesLMilner** [comment]
I don't think this is an issue with geodesics as the LineString still intersects in a globe view:
![Screenshot_20230425_205525](https://user-images.githubusercontent.com/8822075/234388940-782d02f1-8396-49d1-a9f9-d03c3026b967.png)

The issue can be simplified to this CodeSandbox: https://codesandbox.io/s/turf-issue-2424-p1w4pe?file=/src/index.js

**Comment by smallsaucepan** [comment]
Dug into this a bit further. Looking at the test data using one reference system ([EPSG:3395](https://epsg.io/3395)) "WGS 84 / World Mercator" shows intersections for both:

<img width="1023" alt="Screenshot 2024-05-08 at 12 02 15 am" src="https://github.com/Turfjs/turf/assets/5403628/c514e3b0-ad39-4599-9e83-b330077128bf">


Using another reference system ([EPSG:4326](https://epsg.io/4326)) "WGS 84" shows only an intersection with the large rectangle:

<img width="1076" alt="Screenshot 2024-05-08 at 12 02 41 am" src="https://github.com/Turfjs/turf/assets/5403628/cd74d7f6-6a6b-43a7-93ac-74859e0e153d">

I'm going to guess the math sweepline-intersections uses is matched more closely by the latter projection.

It raises the question of how should Turf interpret a line between two points: as a constant bearing rhumb line projected on a flat surface, or as a great circle segment on a sphere? Given it's your use case @noisyneuron, what were you expecting with the data you had?

FYI this is what the great circle path looks like:

![Screenshot 2024-05-07 at 5 39 59 pm](https://github.com/Turfjs/turf/assets/5403628/fc4b4e29-f70d-45c6-880a-ce95fa09d79c)

**Comment by smallsaucepan** [comment]
Closing in lieu of further background from OP. Please reopen if more details come to light.
