### ISSUE TITLE
[security] Set security policy

### ISSUE THREAD

**Issue by gabibguti** [Turfjs/turf#2426]
Adding a Security Policy is important because it provides clear instructions on how to report security vulnerabilities. It also sets expectations of when vulnerabilities will be disclosed.

I previously recommended https://github.com/Turfjs/turf/issues/2413, which is also related to security and recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

If you agree, I can open a PR to suggest a Security Policy. We can then work together to communicate how the repo can best handle vulnerability reports.

##### Additional context
Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

I am not including the regular issue template information, such as version of Turf, GeoJSON, and code snippets, because this is a security-related issue. I understand that the template would not be appropriate for this type of issue.

**Comment by JamesLMilner** [comment]
Hi @gabibguti, thanks for raising this. I agree a security policy probably makes sense for a project operating at the size of Turf.js. Do you have any examples of what this might look like? One issue I'm foreseeing is we do not have a way to currently contact the maintainers privately - I'm not sure if this would be a requirement?

**Comment by gabibguti** [comment]
Hi @JamesLMilner!

Yes, here are a few examples:
https://github.com/emscripten-core/emscripten/security/policy
https://github.com/dustin/go-humanize/security/policy
https://github.com/Cyan4973/xxHash/security/policy

About contacting the maintainers privately, GitHub has a [Private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) feature, currently in public beta. Private reports are not mandatory but strongly recommended.

**Comment by gabibguti** [comment]
Hi! Friendly ping here. Do you still plan on considering this change? Otherwise we can close as not planned for now :)

**Comment by JamesLMilner** [comment]
Hi @gabibguti  - thanks for providing the detailed examples. They look great and I am sure we could produce something similar. My main concern is we don't have a sensible way to contact the maintainers privately as it stands - in theory we have an email address but it is mostly unchecked. I would suggest private vulnerability reporting would make the most sense here. Let me see how to go about setting that up for the project. Thanks!

**Comment by smallsaucepan** [comment]
Thanks for your help with this @gabibguti. Have enabled private vulnerability reporting, and added a security policy.
