### ISSUE TITLE
Detect adjacent polygons

### ISSUE THREAD

**Issue by jfoclpf** [Turfjs/turf#2427]
Any tip to detect adjacent polygons?

![image](https://user-images.githubusercontent.com/3984909/233792260-c2d74505-c660-4b37-9151-0704ce2a4913.png)

Not that I want any special attention, but you have a great job there for which I just contributed ;)

![image](https://user-images.githubusercontent.com/3984909/233792382-6fa64ef2-f440-4d04-a783-890e0f56d920.png)

**Comment by JamesLMilner** [comment]
Hi @jfoclpf - firstly thanks for your donation. With regards to your question, I don't think there is anything explicit in Turf that will handle this. Potentially your best bet would be to index them using something like https://github.com/mourner/rbush and then you can quickly work out polygons with overlapping bounding boxes. You could then check the resulting polygons to see if they have shared coordinates with the target polygon.

**Comment by jfoclpf** [comment]
No problem, I eventually solved this using [topojson](https://github.com/topojson/topojson) library, and its function neightbors

```js
var topoJSON = topojson.topology([geoJsonFeatureCollection], 1e4);
var neighbors = topojson.neighbors(topoJSON.objects[0].geometries);
```

**Comment by rowanwins** [comment]
@jfoclpf yep topojson is a good format for these sort of neighbour operations - it comes at some overhead of translating your data into the topojson format, but once in that format it can do some quite interesting things.
