### ISSUE TITLE
turf-mean-center

### ISSUE THREAD

**Issue by cwhite911** [Turfjs/turf#243]
Hi, I wrote a module that calculates the mean center or weighted mean center for a feature collection of points. I would like to add it to turf if you all want it to use it.

https://github.com/cwhite911/turf-mean-center.git

![meancenter](https://cloud.githubusercontent.com/assets/3803800/6794258/1940e7b0-d1a6-11e4-9f90-bce56abe0766.png)

**Comment by morganherlocker** [comment]
Very cool @cwhite911. This seems pretty similar to turf-centroid:

http://turfjs.org/static/docs/module-turf_centroid.html
https://github.com/Turfjs/turf-centroid

**Comment by cwhite911** [comment]
Yeah I didn't notice that module when I started writing this because I was looking to calculate a weighted mean, I could add the weighting capability to that if you want.

**Comment by morganherlocker** [comment]
A dedicated weighted centroid module would be awesome in turf. Would you mind changing the name to `turf-weighted-centroid` to avoid confusion?

Next steps:

1. I will send you an invite to be a contributor to the Turfjs organization
2. transfer the repo to the Turfjs org (you can do this through the setting pane on the right)
3. when the repo is ready to go, we can do a quick review of code, tests, docs, etc.
4. add travis integration https://travis-ci.org/
4. publish the module to npm
5. run [turf-owners](https://github.com/Turfjs/turf-owners) so other people in the org can publish updates
6. I will add the module to the master turf library at the next minor release (2.x.0)

Sound good @cwhite911?

**Comment by cwhite911** [comment]
Sounds good.

**Comment by cwhite911** [comment]
Transferred the repo, right now it can calculate both a weighted an arithmetic mean. @morganherlocker do you want me to rewrite it so it just calcs the weighted?

**Comment by morganherlocker** [comment]
@cwhite911 since turf-centroid already covers non-weighted, I think weighted should be required

**Comment by cwhite911** [comment]
I changed the module to only run the weighted centroid so it should be good to go.

**Comment by tchannel** [comment]
closing, as Turfjs/turf-weighted-centroid has been created.
