### ISSUE TITLE
lineOffset screenspace offset distance ?

### ISSUE THREAD

**Issue by vrman** [Turfjs/turf#2433]
I want to clone my line with fixed distance offset in every zoom level on map , for example i want to have 40 pixel offset in zoom 16 and also 40 pixel offset at zoom level 2. is this possible to do this in turf ?

**Comment by smallsaucepan** [comment]
Hi @vrman. Thanks for suggesting this. This is probably too specific for Turf to be able to do, as it might depend on the zoom level of your map provided, or the pixel density of the device.

You would need to determine how far (in meters for example) 40 pixels equates to at each zoom level with your particular app, and then provide that to the existing lineOffset function.
