### ISSUE TITLE
'@turf/union@^6.5.0' is not in this registry.

### ISSUE THREAD

**Issue by lgln-mw** [Turfjs/turf#2436]
https://registry.npmjs.org/@turf%2funion returns {"error":"Not found"}

**Comment by globsecure** [comment]
+1

**Comment by alenocera** [comment]
Seems closed as per https://status.npmjs.org/incidents/drj38qn6qm59 shown.
I've retried a few minutes ago and seems all ok

**Comment by GregorSondermeier** [comment]
Duplicate of https://github.com/Turfjs/turf/issues/2437 and seems to be already resolved :)
