### ISSUE TITLE
turf/angle missing from https://turfjs.org

### ISSUE THREAD

**Issue by eric-g-97477** [Turfjs/turf#2439]
I just noticed a function I would find useful, [turfs/angle ](https://github.com/Turfjs/turf/tree/master/packages/turf-angle) is not mentioned on the documentation page at https://turfjs.org

Can the documentation page be regenerated easily? I am wondering what other functions may exist that I am not aware of.

**Comment by JamesLMilner** [comment]
Does indeed look like it is missing! I think looking at the history of the module it looks like this was deliberately never included in the core turf module: https://github.com/Turfjs/turf/pull/1192 

@stebogit do you have any thoughts about this?

**Comment by stebogit** [comment]
I think it was just an oversight, good catch @eric-g-97477

**Comment by smallsaucepan** [comment]
This has been resolved - https://turfjs.org/docs/api/angle
