### ISSUE TITLE
combine turf-vincenty-direct in to turf-destination

### ISSUE THREAD

**Issue by jrzimmerman** [Turfjs/turf#244]
Combine turf-vincenty-direct with turf-destination so that turf-destination will accept an additional optional parameter (planar,haversine,vincenty). This could also be done on turf-vincenty-inverse with turf-distance, along with a few other modules.

**Comment by morganherlocker** [comment]
Stale. Swapping between coordinate systems never took off. Instead, choosing whatever is fast and most accurate has been the going API strategy.
