### ISSUE TITLE
Support for calculating the center of mass

### ISSUE THREAD

**Issue by zerotower69** [Turfjs/turf#2440]
The method `turf.centroid` can accurately calculate the center point of the polygon. However, when the polygon is irregular, perhaps like city region, I want to get the position of the center of mass rather than  the position of geometric center. Can turf provide method to complete it? Thanks for your hard work!

**Comment by stebogit** [comment]
[@turf/center-of-mass](https://github.com/Turfjs/turf/tree/master/packages%2Fturf-center-of-mass)

**Comment by JamesLMilner** [comment]
Indeed [@turf/center-of-mass](https://github.com/Turfjs/turf/tree/master/packages%2Fturf-center-of-mass) should solve your issue!

**Comment by zerotower69** [comment]
Thanks
