### ISSUE TITLE
Unable to accurately determine the position of longitude and latitude when using the area() function

### ISSUE THREAD

**Issue by 995231030** [Turfjs/turf#2457]
@turf/area^6.5.0

Below is a closed polygonal area in China. When the longitude and latitude exchange positions, the area() method can still be used to calculate the area, but the area will be reduced by about half. This problem has been bothering me for a long time because I use turf in leaflet, and the default latitude and longitude of leaflet are opposite to the area() method

[[31.223169567460907,113.62363100051881],[31.217462660470964,113.62032651901247],[31.21603129213837,113.63099098205568],[31.222398879887102,113.63150596618654]]

I hope to use the form of an object (key value pair) to pass parameters, or modify it to the commonly used method of longitude first and latitude last

**Comment by twelch** [comment]
Hi @995231030, I can understand the frustration.  Turf follows the geojson spec which specifies that Positions have a defined order:

```
A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.
```
https://datatracker.ietf.org/doc/html/rfc7946

My suggestion is that it's up to your code to keep track of order and conversion.  [This stackoverflow post](https://gis.stackexchange.com/questions/244651/leafletgeojson-why-are-lat-lng-coordinates-in-the-wrong-order#:~:text=Leaflet%20uses%20lat%2Dlng%20(or,(or%20easting%2Dnorthing%20).) mentions a conversion utility built into Leaflet -- 

I'm going to go ahead and close this as an issue that is not actionable for Turf to fix.
