### ISSUE TITLE
https://registry.npmjs.org/@turf/triangle-grid/-/triangle-grid-6.5.0.tgz is 404'ing

### ISSUE THREAD

**Issue by colemars** [Turfjs/turf#2458]
https://registry.npmjs.org/@turf/triangle-grid/-/triangle-grid-6.5.0.tgz

This is causing pipeline failures.

Is this an NPM problem?

other deps e.g. https://registry.npmjs.org/@turf/transform-translate/-/transform-translate-6.5.0.tgz are returning as expected

**Comment by ryanhugh** [comment]
Were having the same issue

**Comment by jhartzell** [comment]
+1 so are we

**Comment by ImanMahmoudinasab** [comment]
It seems the issue is with npm registry servers. It is fixed now.
