### ISSUE TITLE
turf.deviation not returning correct standard deviation/variance

### ISSUE THREAD

**Issue by jhollist** [Turfjs/turf#246]
I am helping on a [R package that wraps turf.js](https://github.com/ropensci/lawn) and while working on deviation, think I have found a bug.

If you look at the northernmost polygon in the [deviation example](http://turfjs.org/static/docs/module-turf_deviation.html) it lists three points with values of 400, 600, and 500.

The standard deviation for these should be 100 and a variance 10000.  The turf.deviance example reports a standard deviation of 81.65.

It is entirely possible I am missing something here and apologies if I am...

Thanks for a great project.  It is cool seeing a lot of the geospatial tools getting built in js!

**Comment by AbelVM** [comment]
Hmmm... Variance should be 6666.66, not 10000. But, yes, stdDev should be 100.

It would be easy to implement the full set of Statistics methods of [av.arrays](https://github.com/AbelVM/av.arrays) in a **turf-statistics** module. Let's make a proposal :wink:

**Comment by jhollist** [comment]
Wow, I'm a bonehead...  Should've known that one.

Would work for me, but I am not much of a js guy so could just provide moral support!

Thanks for pointing this out for me.

**Comment by jhollist** [comment]
@AbelVM I'm going to go ahead and close this issue since it is calc'ing the pop sd correctly.
