### ISSUE TITLE
Turf sprint goals

### ISSUE THREAD

**Issue by tcql** [Turfjs/turf#249]
@morganherlocker mentioned the idea of organizing a Turf sprint to knock out some big outstanding issues and features. I think that's an awesome idea, and there's no time like now to plan what stuff is high priority :smile: 

The way I see it, we've got a couple of really big things we can focus on:

1. Get rid of JSTS once and for all
  - buffer
  - intersect
  - union
  - erase 
2. Integrate / polish new additions - We've had a lot of submissions in the past few months. I think it'd be a good idea to sort those out, and figure out what needs to be done to get them all ready for prime-time, then prioritize working those into upcoming releases. I don't have a full list put together yet, but I know @AbelVM has added like 5 or 6, and there are probably others
3. Make some progress on supporting Geometries everywhere that it makes sense (per #209). I think this will be much more doable once we do some more work on turf-meta (like Turfjs/turf-meta#10)
4. I've been trying to clean up our github issues, but there's still a whole lot there. I'd like to see some definite milestones / plans for any outstanding feature requests, and some action or decision on outstanding bug reports. I think this will make future development a lot simpler and much more focused if we can have a better view of what's a problem and what we actually have plans to do.

cc @morganherlocker @tmcw

**Comment by lyzidiamond** [comment]
If y'all decide to hit anything related to examples or doc, let me know! Otherwise, carry on. :smiley:

**Comment by AbelVM** [comment]
I have some more :rabbit2: in the :tophat: ...

**Comment by tchannel** [comment]
@lyzidiamond thanks! I suspect we might have some changes between those first few items, but I'll be sure to ping you if / whenever there are some specifics on that
