### ISSUE TITLE
320 stale greenkeeper bot branches in the repo

### ISSUE THREAD

**Issue by smallsaucepan** [Turfjs/turf#2490]
There are currently 320 stale greenkeeper bot generated branches in the repo. They clutter up the view and make it almost impossible to view and make sense of the 45 actually meaningful branches.

Would be good to remove them, especially in preparation for doing an upcoming where branching and merging in the repo will need to take place. Happy to put my hand up to do the work, though recognise that would require some repo permissions be granted.

![greenkeeper-1](https://github.com/Turfjs/turf/assets/5403628/b59ff991-e024-44ba-adfa-0797a2b21169)

![greenkeeper-2](https://github.com/Turfjs/turf/assets/5403628/22832282-7a74-4e91-9450-8ec8b725d989)

**Comment by smallsaucepan** [comment]
Stale branches removed. This is about as deep as the branch hierarchy gets now:

<img width="639" alt="Screenshot 2023-09-19 at 12 37 02 pm" src="https://github.com/Turfjs/turf/assets/5403628/0ae5a0c8-f217-4209-a8a5-e631f947a5f9">

**Comment by JamesLMilner** [comment]
Thanks! 🎉
