### ISSUE TITLE
turf-clusters-dbscan looks very slow

### ISSUE THREAD

**Issue by TadaTeruki** [Turfjs/turf#2492]
I am using [turf-clusters-dbscan](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-dbscan) and I found it looks very slow.

The performance does not appear to be O(NlogN) or anywhere close to it (reference: https://en.wikipedia.org/wiki/DBSCAN). In my project, I eventually used python and scikit-learn to do clustering and write to GeoJSON. That was significantly faster.

Can this be improved?

Thank you.

**Benchmark code**
```
const turf = require('@turf/turf');

function generateRandomPoints(count) {
    const side = Math.sqrt(count);
    return turf.randomPoint(count, {bbox: [0, 0, side, side]});
}

function measureDBSCANTiming(points) {
    const startTime = process.hrtime();
    const count = points.features.length;

    const clustered = turf.clustersDbscan(points, 0.01*Math.sqrt(count), {units: 'kilometers', minPoints: 2});

    const endTime = process.hrtime(startTime);
    const elapsedTimeMs = endTime[0] * 1000 + endTime[1] / 1e6;

    return {
        elapsedTimeMs: elapsedTimeMs,
    };
}

const N = [100, 1000, 10000, 30000];

for (const n of N) {
    console.log(`Calculating DBSCAN timing for N = ${n}...`);
    const randomPoints = generateRandomPoints(n);
    const result = measureDBSCANTiming(randomPoints);
    console.log(`Elapsed time (ms):`, result.elapsedTimeMs);
    console.log('--------------------------');
}
```

**Result**
```
Calculating DBSCAN timing for N = 100...
Elapsed time (ms): 4.708837
--------------------------
Calculating DBSCAN timing for N = 1000...
Elapsed time (ms): 67.439824
--------------------------
Calculating DBSCAN timing for N = 10000...
Elapsed time (ms): 7375.219881
--------------------------
Calculating DBSCAN timing for N = 30000...
Elapsed time (ms): 92009.078819
--------------------------
```

**Environment**
CPU: 11th Gen Intel i7-11390H (8) @ 5.000GHz 
Memory: 16GB (15741MiB)

**Comment by stebogit** [comment]
@TadaTeruki this module simply uses the  `density-clustering` npm package, if there is any possible optimization it needs to happen there

**Comment by TadaTeruki** [comment]
Do this package depends on [`density-clustering`](https://github.com/uhho/density-clustering)?

According to the [implementation of `density-clustering`](https://github.com/uhho/density-clustering/blob/master/lib/DBSCAN.js), this package doesn't use any spatial data structures. 

I will report it to `density-clustering` later, but the package looks not maintained from 8 years ago.

**Comment by TadaTeruki** [comment]
@stebogit Yes, it looks

**Comment by TadaTeruki** [comment]
I think this should be replaced by other packages or eventually integrated into `turf.js`. I'm willing to offer my assistance if needed.

**Comment by stebogit** [comment]
Feel free to submit a PR with a better/faster implementation! 👍🏻
