### ISSUE TITLE
turf-rewind

### ISSUE THREAD

**Issue by AbelVM** [Turfjs/turf#250]
Tiny module that transform arbitrary winding of Polygon rings to fit in the traditional standard:
- outer - > CW
- inner -> CCW 

Reversed is possible.

https://github.com/Turfjs/turf-rewind

**Comment by AbelVM** [comment]
Ooops... didn't see **turf-is-clockwise** module. We use the same Shoelace Formula, so I could make this module even tinier with just an import.

**Comment by DenisCarriere** [comment]
👍 Thanks @AbelVM , currently implemented your rewind module into TurfJS mono repo.
Going to be released in TurfJS v4.3
