### ISSUE TITLE
Angular complaining on commonjs optimization bailouts

### ISSUE THREAD

**Issue by Harpush** [Turfjs/turf#2510]
Version: 6.5

When installed in an angular project - it complains that importing commonjs can cause optimization bailouts.
The following packages are the culprits:
1. geojson-rbush
2. geojson-equality
3. density-clustering
4. skmeans
5. rbush
6. concaveman
7. deep-equal

Is there any chance somehow to tackle it?

**Comment by smallsaucepan** [comment]
Hi @Harpush. Could you please try one of the recent alpha releases to see if they fix this issue for you? We've changed around the way Turf is packaged for esmodules and commonjs.

**Comment by Harpush** [comment]
@smallsaucepan I somehow didn't see the comment. I will check it.
Anyway brush is now esm:
https://github.com/mourner/rbush/issues/134#issuecomment-2194104597
Maybe an update is needed

**Comment by smallsaucepan** [comment]
Thanks @harpush. We will definitely check that out. Reopen this issue if this problem still occurs with v7.
