### ISSUE TITLE
Turf buffer isn't tree shaked

### ISSUE THREAD

**Issue by Harpush** [Turfjs/turf#2514]
Version 6.5.0
I have a library importing turf buffer and exporting a function that uses it.
Even if the app doesn't use that function turf-jsts is in the bundle.
I suspect it is because turf-jsts isn't marked as side effects free.

**Comment by Harpush** [comment]
Any news?

**Comment by smallsaucepan** [comment]
Hi @Harpush. Can you please see if the behaviour has changed with the latest alpha? We have changed bundlers which may have had an effect.

**Comment by smallsaucepan** [comment]
Haven't heard any further news on this, so will mark as fixed. Please reopen if any evidence to the contrary.
