### ISSUE TITLE
Turf latest release on NPM CDN cannot be found

### ISSUE THREAD

**Issue by kuanb** [Turfjs/turf#2526]
Expectation: https://npmcdn.com/@turf/turf/turf.min.js returns latest version of turf package, minified.
Current behavior: "Cannot find package @turf/turf@latest" returned alongside a 404.

Same for https://npmcdn.com/@turf/turf/turf.js or using https://unpkg.com/@turf/turf/turf.min.js

**Comment by smallsaucepan** [comment]
Thanks @kuanb. Looks like it was a temporary issue as two of the three links you mention are working now:

https://npmcdn.com/@turf/turf/turf.min.js OK
https://unpkg.com/@turf/turf/turf.min.js OK

Is the non-minified link mentioned somewhere in the docs (https://npmcdn.com/@turf/turf/turf.js) or were you attempting to guess at another link that might work?

**Comment by kuanb** [comment]
@smallsaucepan apologies this looks like an NPM issue as you note. A few years ago there was a deploy change that broke the latest NPM release (when the different functions were broken into individual components). I reflexively thought something like that had occurred then. Will close issue.
