### ISSUE TITLE
CRS check

### ISSUE THREAD

**Issue by AbelVM** [Turfjs/turf#253]
Looks like we are not checking CRS info of GeoJSON inputs ([CRS property](http://geojson.org/geojson-spec.html#coordinate-reference-system-objects)) and it could lead to errors in any and all modules where haversine calcs are performed if CRS is UTM. We shouldn't use spherical geometry while using a planar projection!

**Comment by morganherlocker** [comment]
Turf [always assumes WGS84 geometry](http://turfjs.org/static/docs/). Essentially, if you can view your data in geojson.io, it will work; if not, then it won't. This keeps things simple, and runs in line with the future of the geojson spec, which discourages alternate projections.

**Comment by AbelVM** [comment]
I learned it the hard way... I checked the docs line by line before opening this issue, but I should jump over that line :pensive:
```javascript
for(var i=0; i<500;i++) {blackboard.log("Will not code at 3am again")}
```
