### ISSUE TITLE
turf.convex failed in points beside 0°(lon)

### ISSUE THREAD

**Issue by jackdsl** [Turfjs/turf#2540]
- [ I use npm install @turf/turf to install turf, so i think the turf should be the latest version. My cesium is 1.88.]
When I try to use **turf.convex** to find convex polygon of several points beside 0° (lon), I found that when the number of points need bounding exceeds four, the resulted convex will only return five points(ABCDA), namely a quadrangle.

**Comment by smallsaucepan** [comment]
@jackdsl , could you please provide some sample data? For example, the geojson passed to convex() that gives the quadrangle you describe.

**Comment by smallsaucepan** [comment]
Haven't received any further details on this. Closing, though please re-open if more info can be provided.
