### ISSUE TITLE
is there a new version release plan?

### ISSUE THREAD

**Issue by nanmobei** [Turfjs/turf#2545]
as the  tittle say ,the new version(v6.5.0) has released 2 years ago ,is there a new version release plan?

**Comment by cmcnicholas** [comment]
same question, there are a number of bug fixes that haven't made it out yet that are causing issues.

**Comment by smallsaucepan** [comment]
Hi @nanmobei and @cmcnicholas. Thanks for getting in touch. We're gearing up to a v7 release and there are a couple of alphas available - 7.0.0-alpha.2 is the latest. Want to try one of those to see if they help?

Otherwise please add a thumbs up to any existing issues that affect you so we know what to prioritise.

**Comment by smallsaucepan** [comment]
Hi @3zzy, @cmcnicholas and @nanmobei. Have taken on board your comments, and chatted with the rest of the team about when we can get v7 out. As Tim mentioned fixing high value bugs is always desirable. However we do need to balance that against how long our users have been waiting for an official update.

What I've proposed is we knock over a couple more maintenance PRs, and release alpha 3. If there aren't any major *new* issues arising out of that after a few weeks, we cut a v7 release.

Hopefully once v7 is out the door we can return to fixing bugs one at a time. If anything requires a breaking change we backlog it until v8, and release that sometime next year. Hope that aligns with what you are hoping for!

Quietly, I'm hoping we could v7 done by the end of the month.

**Comment by 3zzy** [comment]
@smallsaucepan Thanks for the update! I fully support the plan. When I asked for an update, it was with the understanding that a release had to be cut at some point, especially since v7 has been in the works for months. I'd be glad to assist with testing at least and bug fixes where I can.

**Comment by maral** [comment]
Hi @smallsaucepan, thanks for a clear answer. Is there a chance the alphas could be coming out more frequently? There has been so many fixes (including the one I am waiting for) in the last three months and they would deserve more frequent updates. If it's too expensive to create a new version, could you please direct me to how I can use the current `master` in my project?

**Comment by smallsaucepan** [comment]
Hi @maral. Each merged PR now generates a new alpha release. Currently alpha 110 is the latest: https://www.npmjs.com/package/@turf/turf/v/7.0.0-alpha.110

That's probably your easiest way to keep up with the latest changes. Also helps us if you do and report any issues you see.

**Comment by cmcnicholas** [comment]
> Hi @maral. Each merged PR now generates a new alpha release. Currently alpha 110 is the latest: https://www.npmjs.com/package/@turf/turf/v/7.0.0-alpha.110
> 
> That's probably your easiest way to keep up with the latest changes. Also helps us if you do and report any issues you see.

Thanks very much for this, updated to alpha, will keep an eye out for any issues 👍

**Comment by smallsaucepan** [comment]
v7 has now been released! Give it a try @nanmobei @cmcnicholas @3zzy @maral
