### ISSUE TITLE
turf-union "Unable to complete output ring starting at" error

### ISSUE THREAD

**Issue by yangchangqu** [Turfjs/turf#2549]
my version: 6.5.0
I made an error using the function [turf.union] :

`Uncaught Error: Unable to complete output ring starting at [119.26792227000003, 26.09133855399999]. Last matching segment found ends at [119.279599867, 26.085852784999986].
    at Function.factory (polygon-clipping.esm.js:1246:21)
    at Operation2.run (polygon-clipping.esm.js:1770:30)
    at Object.union2 [as union] (polygon-clipping.esm.js:1786:20)
    at Module.union8 (index.js:38:35)
    at AutoDrawPlugin.unionGeometries (cesium-base-plugin.ts:452:30)
    at AutoDrawPlugin.unionOfPolygonHierarchy (cesium-base-plugin.ts:471:35)
    at cesium-base-plugin.ts:370:37
    at Array.forEach (<anonymous>)
    at AutoDrawPlugin.splitOfPolygonHierarchy (cesium-base-plugin.ts:366:26)
    at AutoDrawPlugin.handleGeometries (split-plugin.ts:350:25)`
polygon1：
`{
    "type": "Feature",
    "properties": {},
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    119.26792227000003,
                    26.09133855399999
                ],
                [
                    119.26827343900003,
                    26.091289528000004
                ],
                [
                    119.268373409,
                    26.091262625999995
                ],
                [
                    119.268373463,
                    26.091262593999986
                ],
                [
                    119.26851724000005,
                    26.091171713999987
                ],
                [
                    119.26918610999996,
                    26.090842504
                ],
                [
                    119.26919957700002,
                    26.090865310999995
                ],
                [
                    119.26943968,
                    26.091271921999976
                ],
                [
                    119.26962150899998,
                    26.091529384000022
                ],
                [
                    119.26966249500005,
                    26.091587418000014
                ],
                [
                    119.27003378300003,
                    26.09192920999999
                ],
                [
                    119.27041757200007,
                    26.092110158000033
                ],
                [
                    119.27091753499998,
                    26.09231781900001
                ],
                [
                    119.270981785,
                    26.09234426599999
                ],
                [
                    119.27113544199995,
                    26.092407525999985
                ],
                [
                    119.27139502100002,
                    26.092449202
                ],
                [
                    119.271933239,
                    26.092572995000015
                ],
                [
                    119.27294777500005,
                    26.092688886
                ],
                [
                    119.27359170800003,
                    26.092905836
                ],
                [
                    119.27366611599997,
                    26.092919462999983
                ],
                [
                    119.27370475199997,
                    26.092896025000012
                ],
                [
                    119.27370482000008,
                    26.092895977999987
                ],
                [
                    119.27388310000008,
                    26.092771592000016
                ],
                [
                    119.27398498100004,
                    26.09271955899999
                ],
                [
                    119.27410025500002,
                    26.09270411799997
                ],
                [
                    119.27443945799996,
                    26.092623322000012
                ],
                [
                    119.27446330299995,
                    26.09248727800002
                ],
                [
                    119.27457582199996,
                    26.09250312
                ],
                [
                    119.27467098600005,
                    26.092153184999976
                ],
                [
                    119.27470517500001,
                    26.092093467999966
                ],
                [
                    119.27473463099999,
                    26.09204201699998
                ],
                [
                    119.27485925799999,
                    26.091922878999984
                ],
                [
                    119.27489255600005,
                    26.091891044999993
                ],
                [
                    119.27528952800004,
                    26.09167620099998
                ],
                [
                    119.27565197900006,
                    26.09208567399996
                ],
                [
                    119.27590847199998,
                    26.09214010999999
                ],
                [
                    119.27646200599996,
                    26.092176559999988
                ],
                [
                    119.27667630999998,
                    26.09216992299997
                ],
                [
                    119.27702867400001,
                    26.092095195999985
                ],
                [
                    119.27734837000004,
                    26.09204297000003
                ],
                [
                    119.27733686700003,
                    26.091840850999972
                ],
                [
                    119.27740100999996,
                    26.090045427999996
                ],
                [
                    119.27740185600003,
                    26.09002172800001
                ],
                [
                    119.27740308300001,
                    26.089987430000008
                ],
                [
                    119.27740528000004,
                    26.089925934000004
                ],
                [
                    119.27743051499999,
                    26.08921948400001
                ],
                [
                    119.27749059500002,
                    26.088078816999996
                ],
                [
                    119.27753907600004,
                    26.08750046199999
                ],
                [
                    119.27756799600004,
                    26.08715545299998
                ],
                [
                    119.277579687,
                    26.087015983999997
                ],
                [
                    119.27774168200007,
                    26.085083374999986
                ],
                [
                    119.279599867,
                    26.085852784999986
                ],
                [
                    119.27964342400003,
                    26.08587082000002
                ],
                [
                    119.27966465500003,
                    26.085879610999992
                ],
                [
                    119.27985183500009,
                    26.085957113000003
                ],
                [
                    119.28082740200003,
                    26.086361044999983
                ],
                [
                    119.28120701700007,
                    26.086518220999988
                ],
                [
                    119.28280495700005,
                    26.087179541999998
                ],
                [
                    119.283082874,
                    26.087294557
                ],
                [
                    119.28359686099998,
                    26.087507265
                ],
                [
                    119.28390780700002,
                    26.087590218
                ],
                [
                    119.283996207,
                    26.087613800999964
                ],
                [
                    119.28400513400004,
                    26.087616181999977
                ],
                [
                    119.28447277299996,
                    26.087740930999985
                ],
                [
                    119.285337701,
                    26.087874160000005
                ],
                [
                    119.28569185100004,
                    26.087928712000014
                ],
                [
                    119.28636738499996,
                    26.088032763999976
                ],
                [
                    119.28686264700004,
                    26.08810904500001
                ],
                [
                    119.28688445399996,
                    26.088112405000007
                ],
                [
                    119.28740812299998,
                    26.088193061000027
                ],
                [
                    119.28744890300008,
                    26.088200452999995
                ],
                [
                    119.28747632199997,
                    26.088205424000016
                ],
                [
                    119.288289687,
                    26.088352864999987
                ],
                [
                    119.28857068200003,
                    26.088403801000027
                ],
                [
                    119.28939130000003,
                    26.08855254899998
                ],
                [
                    119.28940446399997,
                    26.08855493499999
                ],
                [
                    119.28953208300005,
                    26.088578068999993
                ],
                [
                    119.29001057200006,
                    26.088664795999996
                ],
                [
                    119.29004381799999,
                    26.088671143999992
                ],
                [
                    119.29010271699998,
                    26.08868238799999
                ],
                [
                    119.29028644799995,
                    26.08871746199997
                ],
                [
                    119.29029319700001,
                    26.088718749000012
                ],
                [
                    119.29032127800001,
                    26.088724108999997
                ],
                [
                    119.29106401700005,
                    26.088865881000004
                ],
                [
                    119.29144868799996,
                    26.088890004000007
                ],
                [
                    119.29145798699996,
                    26.08889058800003
                ],
                [
                    119.29147025600001,
                    26.088891262999994
                ],
                [
                    119.29448168600004,
                    26.089056912999975
                ],
                [
                    119.29475537500002,
                    26.087851934000014
                ],
                [
                    119.29476505900004,
                    26.087809299000014
                ],
                [
                    119.29477158500005,
                    26.087780598
                ],
                [
                    119.29480424400005,
                    26.087636948000018
                ],
                [
                    119.29480721000007,
                    26.087623896000018
                ],
                [
                    119.29480912400007,
                    26.087615481999975
                ],
                [
                    119.29481181300002,
                    26.087603648000023
                ],
                [
                    119.29498015099999,
                    26.086862591
                ],
                [
                    119.29498124700001,
                    26.08685776499998
                ],
                [
                    119.29501659100004,
                    26.086702160999987
                ],
                [
                    119.29503741600001,
                    26.08661048699997
                ],
                [
                    119.295190372,
                    26.086087195999994
                ],
                [
                    119.29519121400008,
                    26.086084304999975
                ],
                [
                    119.29520515599995,
                    26.08603660500001
                ],
                [
                    119.295400463,
                    26.085368404999983
                ],
                [
                    119.29540177700007,
                    26.085363916
                ],
                [
                    119.29540819700004,
                    26.085341946000025
                ],
                [
                    119.29552614299996,
                    26.08493841500001
                ],
                [
                    119.29576637400001,
                    26.084116497000025
                ],
                [
                    119.29576696599999,
                    26.084114479999965
                ],
                [
                    119.29584204900004,
                    26.083873901999993
                ],
                [
                    119.298732505,
                    26.084446225000008
                ],
                [
                    119.29886870400004,
                    26.084473193000004
                ],
                [
                    119.29899598099999,
                    26.08449839500003
                ],
                [
                    119.30148191,
                    26.084990560999987
                ],
                [
                    119.30167684900003,
                    26.08408462599998
                ],
                [
                    119.30193896900005,
                    26.084062775999996
                ],
                [
                    119.302088432,
                    26.084015709000028
                ],
                [
                    119.30211186099996,
                    26.084008331000007
                ],
                [
                    119.30245265600003,
                    26.083700234999988
                ],
                [
                    119.30259336600002,
                    26.083699799999973
                ],
                [
                    119.30360708600006,
                    26.083679443999984
                ],
                [
                    119.30428010499998,
                    26.083462051000026
                ],
                [
                    119.304297636,
                    26.083456387000002
                ],
                [
                    119.30451040100002,
                    26.083418869000013
                ],
                [
                    119.30516094200004,
                    26.08352380399998
                ],
                [
                    119.30527010900006,
                    26.083087960999986
                ],
                [
                    119.30609187799995,
                    26.08324918400001
                ],
                [
                    119.30614589200005,
                    26.08325978099997
                ],
                [
                    119.30617918600005,
                    26.08326631199997
                ],
                [
                    119.30747144700003,
                    26.083519831999972
                ],
                [
                    119.30814750900002,
                    26.083559037999976
                ],
                [
                    119.30817862900005,
                    26.083560843999958
                ],
                [
                    119.30894618500001,
                    26.083605346999995
                ],
                [
                    119.30897813000001,
                    26.083607201999996
                ],
                [
                    119.30899601800002,
                    26.083608237999997
                ],
                [
                    119.31036787799997,
                    26.08370109600003
                ],
                [
                    119.31049752900002,
                    26.08370987699999
                ],
                [
                    119.31186102799998,
                    26.083802155000004
                ],
                [
                    119.31284842800007,
                    26.083861716999998
                ],
                [
                    119.31293800399999,
                    26.08386712200001
                ],
                [
                    119.31416202800006,
                    26.083940944000005
                ],
                [
                    119.31417288700005,
                    26.083941600000006
                ],
                [
                    119.31517620000001,
                    26.084002102999982
                ],
                [
                    119.31514259899996,
                    26.08407781199997
                ],
                [
                    119.31484726999997,
                    26.08474323799997
                ],
                [
                    119.31353783300007,
                    26.086738449
                ],
                [
                    119.31313363499999,
                    26.087354318999978
                ],
                [
                    119.31305608599999,
                    26.087472479999974
                ],
                [
                    119.31273692800005,
                    26.087958765999986
                ],
                [
                    119.31256064800006,
                    26.088556896
                ],
                [
                    119.31256063100001,
                    26.088556949999987
                ],
                [
                    119.31253415100002,
                    26.088702188000013
                ],
                [
                    119.31212274699999,
                    26.090958447000002
                ],
                [
                    119.31212269599997,
                    26.090958619999977
                ],
                [
                    119.312085575,
                    26.091084587000008
                ],
                [
                    119.31201279300001,
                    26.091495786999975
                ],
                [
                    119.311894876,
                    26.09216196699998
                ],
                [
                    119.31177712900002,
                    26.092827178999983
                ],
                [
                    119.31164283299995,
                    26.093585881000024
                ],
                [
                    119.31153050800003,
                    26.094220441000008
                ],
                [
                    119.31151263100004,
                    26.094317014999994
                ],
                [
                    119.31151012199997,
                    26.09433057299998
                ],
                [
                    119.31129391399998,
                    26.095498737000014
                ],
                [
                    119.311246248,
                    26.095756271000035
                ],
                [
                    119.31111729500003,
                    26.09645296500002
                ],
                [
                    119.31108367300001,
                    26.096634611999995
                ],
                [
                    119.31092776000004,
                    26.097476958000016
                ],
                [
                    119.31074179500001,
                    26.098481644000003
                ],
                [
                    119.31070430499997,
                    26.098684192999983
                ],
                [
                    119.310701948,
                    26.098696933999967
                ],
                [
                    119.31063682000006,
                    26.099048783
                ],
                [
                    119.31063240100002,
                    26.099074847999987
                ],
                [
                    119.31055972099999,
                    26.099503630999997
                ],
                [
                    119.31052681300005,
                    26.09969775399998
                ],
                [
                    119.31035327400006,
                    26.100327902999986
                ],
                [
                    119.310237271,
                    26.100589915999986
                ],
                [
                    119.31001505999996,
                    26.101091823999976
                ],
                [
                    119.30963210899998,
                    26.10195676699998
                ],
                [
                    119.30962586099997,
                    26.101970891999983
                ],
                [
                    119.309610776,
                    26.10200495800001
                ],
                [
                    119.30940705600008,
                    26.102465086
                ],
                [
                    119.30924338,
                    26.102834764000026
                ],
                [
                    119.30923976300008,
                    26.102842939000027
                ],
                [
                    119.30857120899998,
                    26.104352902000016
                ],
                [
                    119.30847835899999,
                    26.104562610000016
                ],
                [
                    119.30841339999996,
                    26.104709318999987
                ],
                [
                    119.308368417,
                    26.104810914999963
                ],
                [
                    119.30833914300001,
                    26.10487702699999
                ],
                [
                    119.30750594999995,
                    26.10675876200003
                ],
                [
                    119.30749660100004,
                    26.106779883999987
                ],
                [
                    119.30597177300001,
                    26.106411965999996
                ],
                [
                    119.305952973,
                    26.106407429
                ],
                [
                    119.305903341,
                    26.106395453
                ],
                [
                    119.30510922900002,
                    26.106204389000016
                ],
                [
                    119.30434964899997,
                    26.106021624999997
                ],
                [
                    119.304202092,
                    26.10598612400002
                ],
                [
                    119.304163951,
                    26.105976946999984
                ],
                [
                    119.304147589,
                    26.105973011
                ],
                [
                    119.30396597699998,
                    26.10592931100001
                ],
                [
                    119.30311475500002,
                    26.105724494000018
                ],
                [
                    119.30305377900007,
                    26.10570982100001
                ],
                [
                    119.30269559299997,
                    26.105623632000004
                ],
                [
                    119.30134310999996,
                    26.105348354000004
                ],
                [
                    119.30140594600006,
                    26.10424925
                ],
                [
                    119.30141243100002,
                    26.10413581599999
                ],
                [
                    119.30144344200005,
                    26.103593376
                ],
                [
                    119.301477438,
                    26.10299870799997
                ],
                [
                    119.30147935599997,
                    26.102965155999975
                ],
                [
                    119.301498788,
                    26.102625284000005
                ],
                [
                    119.30149879400007,
                    26.10262514999998
                ],
                [
                    119.30155428700007,
                    26.101654460000024
                ],
                [
                    119.30158182499999,
                    26.101172729999973
                ],
                [
                    119.30164042300001,
                    26.100062831999978
                ],
                [
                    119.30164396600001,
                    26.09999582400002
                ],
                [
                    119.30164591300003,
                    26.09995891599999
                ],
                [
                    119.30167080599998,
                    26.099487694
                ],
                [
                    119.30168516249151,
                    26.09921588003469
                ],
                [
                    119.30157350999384,
                    26.10116897056351
                ],
                [
                    119.30148804155813,
                    26.102651681148387
                ],
                [
                    119.30133489504965,
                    26.105344191491753
                ],
                [
                    119.2995770252021,
                    26.10498130378754
                ],
                [
                    119.29917638368264,
                    26.104898690308694
                ],
                [
                    119.29766313833464,
                    26.1045860742631
                ],
                [
                    119.2957679372748,
                    26.10419363718654
                ],
                [
                    119.29569109087862,
                    26.103727349157232
                ],
                [
                    119.29574826294841,
                    26.102924937871634
                ],
                [
                    119.29571437469058,
                    26.102133471638474
                ],
                [
                    119.29571168336672,
                    26.102073236312435
                ],
                [
                    119.29665560939513,
                    26.100835883817965
                ],
                [
                    119.29479793505608,
                    26.100042483347874
                ],
                [
                    119.29436350685195,
                    26.099857009381875
                ],
                [
                    119.29370790546564,
                    26.099658147687336
                ],
                [
                    119.29222800371282,
                    26.099405729816166
                ],
                [
                    119.29224878147363,
                    26.099299730556208
                ],
                [
                    119.29296858645722,
                    26.09563821197875
                ],
                [
                    119.29172982499996,
                    26.09542004299999
                ],
                [
                    119.291548166,
                    26.09538804699997
                ],
                [
                    119.29147919100002,
                    26.09537589799999
                ],
                [
                    119.29092879400005,
                    26.09527896299999
                ],
                [
                    119.290861736,
                    26.095267149999984
                ],
                [
                    119.29083662400001,
                    26.09526272800002
                ],
                [
                    119.289772184,
                    26.09507523899998
                ],
                [
                    119.28976558500005,
                    26.095074079000018
                ],
                [
                    119.28976121500001,
                    26.095073307999996
                ],
                [
                    119.28883611400002,
                    26.094874480999977
                ],
                [
                    119.28879492500006,
                    26.094865389999992
                ],
                [
                    119.28865346900001,
                    26.094801206000003
                ],
                [
                    119.28821295099999,
                    26.095722943999988
                ],
                [
                    119.288176617,
                    26.09579861399998
                ],
                [
                    119.28795602599996,
                    26.096258008999996
                ],
                [
                    119.28762952600006,
                    26.09708954600001
                ],
                [
                    119.28719542900002,
                    26.097248298999986
                ],
                [
                    119.286943029,
                    26.09746719399998
                ],
                [
                    119.286784678,
                    26.09774015900002
                ],
                [
                    119.28666949000001,
                    26.097938716999963
                ],
                [
                    119.28627131300006,
                    26.098625089999974
                ],
                [
                    119.285836732,
                    26.09920938699998
                ],
                [
                    119.28542934799998,
                    26.099757109999977
                ],
                [
                    119.28526723699997,
                    26.099975060000013
                ],
                [
                    119.28517774600006,
                    26.100134378000007
                ],
                [
                    119.28513023300002,
                    26.100344265999972
                ],
                [
                    119.28510031300004,
                    26.100605428999984
                ],
                [
                    119.28509363700003,
                    26.100841851999974
                ],
                [
                    119.28509584799998,
                    26.101470849999984
                ],
                [
                    119.28518487300005,
                    26.101774998999982
                ],
                [
                    119.28541082200003,
                    26.102118226000023
                ],
                [
                    119.28497389899997,
                    26.10275779300002
                ],
                [
                    119.28460118500006,
                    26.102778033000007
                ],
                [
                    119.28457926900002,
                    26.103068271999966
                ],
                [
                    119.28429292199999,
                    26.103701686999997
                ],
                [
                    119.28420452399999,
                    26.103923237999993
                ],
                [
                    119.28418653200004,
                    26.10394198199998
                ],
                [
                    119.28417865100005,
                    26.104082022
                ],
                [
                    119.28413037600001,
                    26.104080791999994
                ],
                [
                    119.28412894300006,
                    26.104136270000023
                ],
                [
                    119.28409585300005,
                    26.10413805799999
                ],
                [
                    119.28403167199998,
                    26.104137579999986
                ],
                [
                    119.28396366100003,
                    26.104137460999993
                ],
                [
                    119.28394906200003,
                    26.103910285999962
                ],
                [
                    119.28437865599996,
                    26.10338549300002
                ],
                [
                    119.28449004000004,
                    26.103015801000026
                ],
                [
                    119.28383831400002,
                    26.102447643999987
                ],
                [
                    119.28334218600003,
                    26.102179993999982
                ],
                [
                    119.28330546999996,
                    26.102062236999977
                ],
                [
                    119.28343273500002,
                    26.101705144
                ],
                [
                    119.28329874799999,
                    26.10102850099996
                ],
                [
                    119.28335355599995,
                    26.10027773600001
                ],
                [
                    119.28396047900003,
                    26.09910991699999
                ],
                [
                    119.28400039300007,
                    26.098942828000016
                ],
                [
                    119.28400837599996,
                    26.098856662999996
                ],
                [
                    119.28401123000002,
                    26.098631735000026
                ],
                [
                    119.28400563100001,
                    26.098559797999993
                ],
                [
                    119.28252444800002,
                    26.09799482499999
                ],
                [
                    119.28103801000002,
                    26.09726104999997
                ],
                [
                    119.280739339,
                    26.09652067899998
                ],
                [
                    119.27997057699999,
                    26.096583657999975
                ],
                [
                    119.27985074200001,
                    26.096896754
                ],
                [
                    119.27910538599996,
                    26.09783521399997
                ],
                [
                    119.27793710799995,
                    26.09854491200002
                ],
                [
                    119.27693595100007,
                    26.098456449999986
                ],
                [
                    119.27693682600001,
                    26.098453353000025
                ],
                [
                    119.27717338699998,
                    26.097615093999995
                ],
                [
                    119.27746324500004,
                    26.096757853999964
                ],
                [
                    119.27758203400005,
                    26.096399650000023
                ],
                [
                    119.27761161800005,
                    26.096098638
                ],
                [
                    119.27725976800002,
                    26.096006373000026
                ],
                [
                    119.27724631000002,
                    26.096040566999985
                ],
                [
                    119.27713601400002,
                    26.096013003999982
                ],
                [
                    119.27714704100005,
                    26.095976813999982
                ],
                [
                    119.27651605799998,
                    26.095811351999988
                ],
                [
                    119.275653337,
                    26.095736605000003
                ],
                [
                    119.27495428400006,
                    26.095676043000008
                ],
                [
                    119.273803544,
                    26.095374116000013
                ],
                [
                    119.273463622,
                    26.095328902000002
                ],
                [
                    119.272790181,
                    26.095132858
                ],
                [
                    119.27186121900002,
                    26.09489626499998
                ],
                [
                    119.27154874800003,
                    26.094802835
                ],
                [
                    119.27133072599997,
                    26.09467379900002
                ],
                [
                    119.27066023900004,
                    26.094224418000017
                ],
                [
                    119.27035268700001,
                    26.09403649699999
                ],
                [
                    119.27035264500003,
                    26.094036472000006
                ],
                [
                    119.26863135300003,
                    26.092673284999993
                ],
                [
                    119.26839284799996,
                    26.09253755999999
                ],
                [
                    119.26810974900006,
                    26.092259415999976
                ],
                [
                    119.26810976700007,
                    26.09225939800001
                ],
                [
                    119.26825405200002,
                    26.09210043399997
                ],
                [
                    119.26825405000002,
                    26.09210040300002
                ],
                [
                    119.268231282,
                    26.091870476999983
                ],
                [
                    119.26792227000003,
                    26.09133855399999
                ]
            ]
        ]
    }
}`
polygon2：
`{
    "type": "Feature",
    "properties": {},
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    119.28447277299996,
                    26.087740930999985
                ],
                [
                    119.285337701,
                    26.08787416000001
                ],
                [
                    119.28569185100004,
                    26.087928712000007
                ],
                [
                    119.28636738499996,
                    26.088032763999983
                ],
                [
                    119.28686264700004,
                    26.08810904500001
                ],
                [
                    119.28688445399996,
                    26.088112405000007
                ],
                [
                    119.28740812299998,
                    26.088193061000027
                ],
                [
                    119.28744890300005,
                    26.088200453000006
                ],
                [
                    119.28747632199997,
                    26.088205424000016
                ],
                [
                    119.288289687,
                    26.088352864999994
                ],
                [
                    119.28857068200001,
                    26.088403801000023
                ],
                [
                    119.28939130000003,
                    26.08855254899998
                ],
                [
                    119.28940446399997,
                    26.08855493499999
                ],
                [
                    119.28953208300005,
                    26.088578068999993
                ],
                [
                    119.29001057200006,
                    26.088664795999993
                ],
                [
                    119.29004381799999,
                    26.088671143999992
                ],
                [
                    119.29010271699998,
                    26.08868238799999
                ],
                [
                    119.29028644799995,
                    26.088717461999973
                ],
                [
                    119.29029319700001,
                    26.088718749000012
                ],
                [
                    119.29032127800001,
                    26.088724108999997
                ],
                [
                    119.29106401700005,
                    26.088865881000004
                ],
                [
                    119.29144868799996,
                    26.088890004000007
                ],
                [
                    119.29145798699996,
                    26.08889058800003
                ],
                [
                    119.29147025600001,
                    26.088891262999994
                ],
                [
                    119.29448168600004,
                    26.089056912999975
                ],
                [
                    119.29475537500002,
                    26.087851934000014
                ],
                [
                    119.29476505900004,
                    26.087809299000014
                ],
                [
                    119.29477158500005,
                    26.087780598
                ],
                [
                    119.29480424400005,
                    26.087636948000018
                ],
                [
                    119.29480721000004,
                    26.087623896000018
                ],
                [
                    119.29480912400007,
                    26.08761548199998
                ],
                [
                    119.29481181300002,
                    26.087603648000023
                ],
                [
                    119.29498015099999,
                    26.086862591
                ],
                [
                    119.29498124700001,
                    26.086857764999987
                ],
                [
                    119.29501659100004,
                    26.086702160999998
                ],
                [
                    119.29503741600001,
                    26.08661048699997
                ],
                [
                    119.295190372,
                    26.086087195999994
                ],
                [
                    119.29519121400008,
                    26.08608430499998
                ],
                [
                    119.29520515599995,
                    26.086036605000007
                ],
                [
                    119.295400463,
                    26.085368404999986
                ],
                [
                    119.29540177700007,
                    26.085363916000002
                ],
                [
                    119.29540819700004,
                    26.085341946000025
                ],
                [
                    119.29552614299996,
                    26.08493841500001
                ],
                [
                    119.29576637400001,
                    26.08411649700002
                ],
                [
                    119.29576696599999,
                    26.084114479999975
                ],
                [
                    119.29584204900004,
                    26.083873901999993
                ],
                [
                    119.295167775,
                    26.08366118399999
                ],
                [
                    119.29455955699996,
                    26.083469300999983
                ],
                [
                    119.29388822199998,
                    26.083264799999988
                ],
                [
                    119.29356201300007,
                    26.083165427999976
                ],
                [
                    119.29352399300004,
                    26.08315390600001
                ],
                [
                    119.29266532800001,
                    26.08289364900003
                ],
                [
                    119.29314036800001,
                    26.081207388
                ],
                [
                    119.29302534900002,
                    26.08115973100001
                ],
                [
                    119.29249488000004,
                    26.08106307499996
                ],
                [
                    119.29199401000008,
                    26.080972540000005
                ],
                [
                    119.29136559200003,
                    26.080871537000007
                ],
                [
                    119.29113559600002,
                    26.080841222000004
                ],
                [
                    119.29113210000003,
                    26.080840760999983
                ],
                [
                    119.29097417000003,
                    26.080726428
                ],
                [
                    119.290930272,
                    26.08069553799998
                ],
                [
                    119.29085149199999,
                    26.080540573000007
                ],
                [
                    119.290518517,
                    26.08003612300001
                ],
                [
                    119.29047453299995,
                    26.07996948499999
                ],
                [
                    119.29034672200001,
                    26.079949881999998
                ],
                [
                    119.29029318100005,
                    26.07994166999998
                ],
                [
                    119.28949736100006,
                    26.079819612999977
                ],
                [
                    119.28943621400003,
                    26.079810232000007
                ],
                [
                    119.28903911400003,
                    26.079768845999975
                ],
                [
                    119.28900435900003,
                    26.079765220000013
                ],
                [
                    119.28885292999996,
                    26.079749439000004
                ],
                [
                    119.28885289100003,
                    26.07974940100001
                ],
                [
                    119.28809546699996,
                    26.07952285499999
                ],
                [
                    119.28713699000004,
                    26.079334507999988
                ],
                [
                    119.287066762,
                    26.07930869900002
                ],
                [
                    119.28701893100003,
                    26.079291119
                ],
                [
                    119.28610159899996,
                    26.079238470000014
                ],
                [
                    119.28611796200006,
                    26.079101594000004
                ],
                [
                    119.28615825199996,
                    26.078927819000004
                ],
                [
                    119.28616068400005,
                    26.078917363000016
                ],
                [
                    119.28616069099998,
                    26.07891733000002
                ],
                [
                    119.28547518799999,
                    26.078877547999983
                ],
                [
                    119.28508176200002,
                    26.078836285000026
                ],
                [
                    119.28482341200004,
                    26.078777521000003
                ],
                [
                    119.28439674000003,
                    26.078680471999974
                ],
                [
                    119.28445328600004,
                    26.07811491400002
                ],
                [
                    119.28446478599994,
                    26.078032192000023
                ],
                [
                    119.28335089400002,
                    26.077821433999986
                ],
                [
                    119.28341639799999,
                    26.077392630000023
                ],
                [
                    119.28324177499996,
                    26.077382264999983
                ],
                [
                    119.28297829999997,
                    26.077326976000002
                ],
                [
                    119.283034348,
                    26.076808007000004
                ],
                [
                    119.282957982,
                    26.076717181999978
                ],
                [
                    119.28282427000002,
                    26.076753122000014
                ],
                [
                    119.282704135,
                    26.07664956500003
                ],
                [
                    119.28275328300003,
                    26.076519449999978
                ],
                [
                    119.282530598,
                    26.07630241700001
                ],
                [
                    119.28230909499997,
                    26.076278419999998
                ],
                [
                    119.28187985800002,
                    26.076394515000004
                ],
                [
                    119.28187259900005,
                    26.07648242300002
                ],
                [
                    119.28186935400005,
                    26.076538104000008
                ],
                [
                    119.28187371700007,
                    26.076620633999998
                ],
                [
                    119.28191131400001,
                    26.076718883000012
                ],
                [
                    119.28190801599999,
                    26.076784131000004
                ],
                [
                    119.28189076700005,
                    26.07678172599998
                ],
                [
                    119.28186454900002,
                    26.076924373
                ],
                [
                    119.28184189499996,
                    26.076971404000002
                ],
                [
                    119.281795494,
                    26.076998112000012
                ],
                [
                    119.28124538400004,
                    26.07695633100002
                ],
                [
                    119.28073570900008,
                    26.07688780799998
                ],
                [
                    119.28072823699996,
                    26.076951188000006
                ],
                [
                    119.28070882300008,
                    26.077097228000014
                ],
                [
                    119.28019503300006,
                    26.07701174200001
                ],
                [
                    119.279794294,
                    26.076934321999996
                ],
                [
                    119.27969403500005,
                    26.076929843000013
                ],
                [
                    119.279597611,
                    26.077295248999974
                ],
                [
                    119.27951207399997,
                    26.077657567000017
                ],
                [
                    119.279245135,
                    26.078788229000008
                ],
                [
                    119.27922207999994,
                    26.07889336800003
                ],
                [
                    119.27921921599999,
                    26.07890642199998
                ],
                [
                    119.279218714,
                    26.078908712999972
                ],
                [
                    119.27896359200001,
                    26.08007220399998
                ],
                [
                    119.27895592499998,
                    26.080107171000005
                ],
                [
                    119.27880070500002,
                    26.080815044000012
                ],
                [
                    119.27878032000001,
                    26.080897214000004
                ],
                [
                    119.27873174800003,
                    26.081092991999977
                ],
                [
                    119.278598356,
                    26.081630636000007
                ],
                [
                    119.27859539200008,
                    26.081642573999996
                ],
                [
                    119.278473641,
                    26.08213329
                ],
                [
                    119.278421053,
                    26.082345246999967
                ],
                [
                    119.27840012399997,
                    26.082429605000012
                ],
                [
                    119.278111814,
                    26.083591618999996
                ],
                [
                    119.27810495300002,
                    26.083619285999987
                ],
                [
                    119.27809264899997,
                    26.083668857000017
                ],
                [
                    119.27805475900004,
                    26.08382156900001
                ],
                [
                    119.27774168200007,
                    26.085083375000007
                ],
                [
                    119.279599867,
                    26.085852784999986
                ],
                [
                    119.27964342400003,
                    26.08587082000002
                ],
                [
                    119.27966465500003,
                    26.085879610999992
                ],
                [
                    119.27985183500009,
                    26.085957113000006
                ],
                [
                    119.280827402,
                    26.086361044999993
                ],
                [
                    119.28120701700007,
                    26.086518221
                ],
                [
                    119.28280495700005,
                    26.087179541999998
                ],
                [
                    119.283082874,
                    26.087294557
                ],
                [
                    119.28359686099998,
                    26.087507265
                ],
                [
                    119.28390780700002,
                    26.087590218
                ],
                [
                    119.283996207,
                    26.087613800999968
                ],
                [
                    119.28400513400004,
                    26.087616181999977
                ],
                [
                    119.28447277299996,
                    26.087740930999985
                ]
            ]
        ]
    }
}`

**Comment by yangchangqu** [comment]
nobody follow with this bug

**Comment by yangchangqu** [comment]
![20231201183807](https://github.com/Turfjs/turf/assets/45128970/c9fddac7-abcf-4cfc-aa5c-327d92f6418b)
![20231201183647](https://github.com/Turfjs/turf/assets/45128970/e3f3f3c9-23f3-46c0-b326-8e391614388a)
![20231201183704](https://github.com/Turfjs/turf/assets/45128970/c091e07e-8c07-4d11-ac4a-9df217f46825)

**Comment by smallsaucepan** [comment]
Hi @yangchangqu. Thank you for reporting this bug. Parts of this issue might be duplicates of #2317, #2479, and #1983.

One suggestion as a workaround is to run turf.truncate() on your polygons to address a precision issue in the ```polygon-clipping``` library. Can you please try that and let us know if it helps?
