### ISSUE TITLE
Module Import/Types Issues

### ISSUE THREAD

**Issue by charlieforward9** [Turfjs/turf#2559]
Turf Versions: ^6.5.0

I followed the basic instructions of installing the individual Turf modules, but kept getting this error:

`Could not find a declaration file for module '@turf/XXX'. '/XXX/node_modules/@turf/XXX/dist/es/index.js' implicitly has an 'any' type.
  There are types at '/XXX/node_modules/@turf/XXX/dist/js/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/XXX' library may need to update its package.json or typings.`

I found [this SO discussion](https://stackoverflow.com/a/76212193/14193416) that mentioned a minor syntactical shift in the `package.json` of the module. I performed this change and the linting error went away. 

```diff
"exports": {
    "./package.json": "./package.json",
    ".": {
+     "types": "./dist/js/index.d.ts",
      "import": "./dist/es/index.js",
      "require": "./dist/js/index.js"
    }
  },
- "types": "/dist/js/index.d.ts",
```

This seems to be a necessary change for the library, which I would be happy to contribute to if it is not already being addressed.

**Comment by smallsaucepan** [comment]
Thanks for logging this issue @charlieforward9. We've made some changes to address this and a few other type issues. I took at look at the StackOverflow thread you included, and I think the changes will help, although they're not exactly the same.

Would you mind taking a look and seeing if you can spot any potential problems or improvements? An example of the changes are in https://github.com/Turfjs/turf/blob/d0f5cd76ccf91e8bcc004172a5ced71d0f2bb879/packages/turf-along/package.json#L26-L42

If that looks like it might help, those changes will go out with 7.0.0-alpha.3, hopefully in a week or so.

**Comment by charlieforward9** [comment]
@smallsaucepan  Seems like you linked [this branch](https://github.com/smallsaucepan/turf/tree/pnpm-migration) that you'd like me to test which, when merged should close this issue?

**Comment by twelch** [comment]
> Seems like you linked [this branch](https://github.com/smallsaucepan/turf/tree/pnpm-migration) that you'd like me to test which, when merged should close this issue?

@charlieforward9 i think he was just asking if you could scan that code change and provide feedback on if you think it's the type of change you would expect to fix the issue. When the alpha.3 comes can test to be sure

**Comment by charlieforward9** [comment]
The code looks valid, I would like to be able to test it in my repo and use this branch until the alpha.3 release is available. Can I replace "^6.5.0" with "smallsaucepan/turf#pnpm-migration" or do I need to do something else as I am importing the turf modules like this: 

``` json
    "@turf/area": "^6.5.0",
    "@turf/bbox": "^6.5.0",
    "@turf/boolean-point-in-polygon": "^6.5.0",
    "@turf/helpers": "^6.5.0",
```

I have a continuous deployment pipeline that is breaking because I have manually changed the dependencies in node_modules/ to work as specified in the Issue Description, so I need a solution as soon as possible. Thank you.

**Comment by charlieforward9** [comment]
@twelch @smallsaucepan  The code looks valid, I would like to be able to test it in my repo and use this branch until the alpha.3 release is available. Can I replace "^6.5.0" with "smallsaucepan/turf#pnpm-migration" or do I need to do something else as I am importing the turf modules like this: 

``` json
    "@turf/area": "^6.5.0",
    "@turf/bbox": "^6.5.0",
    "@turf/boolean-point-in-polygon": "^6.5.0",
    "@turf/helpers": "^6.5.0",
```

I have a continuous deployment pipeline that is breaking because I have manually changed the dependencies in node_modules/ to work as specified in the Issue Description, so I need a solution as soon as possible. Thank you.

**Comment by twelch** [comment]
@charlieforward9 it doesn't quite work that way. A build isn't in the repo itself for you to just grab from any branch, it's published separately to npm.  That pnpm branch is just one of many going into the next alpha and doesn't necessarily have the fix you're looking for.  I think you'll just have to be patient.

**Comment by charlieforward9** [comment]
@twelch I was afraid this would be the case... it was mentioned earlier that alpha.3 is supposed to be coming out this week, but it seems that is not the case anymore. Is there a new projected release date?

**Comment by twelch** [comment]
I hear you.  I think @smallsaucepan was hopeful. This is a library maintained by volunteers so I would suggest there is no release date, even when one is hinted.  There's work happening on the very machinery that produces and publishes the builds so once that's stable I think it will get done.

**Comment by charlieforward9** [comment]
@twelch Thanks for the explanation. I have worked a bit with open source projects and have had many discussions with their volunteers so I know its not as streamlined and predictable as a business operation. As I am working on a team that depends very much on this engine, I will likely become a volunteer myself down the road. Is there a location where this work/discussions are discussed or tracked?

**Comment by twelch** [comment]
Outside of issues, Github discussions is the best place to ask and interact - https://github.com/Turfjs/turf/discussions.

**Comment by twelch** [comment]
@charlieforward9 if you already were able to patch it in a way that resolves the issue, you can try this patching technique mentioned here - https://github.com/Turfjs/turf/issues/2498#issuecomment-1737825117

**Comment by smallsaucepan** [comment]
Hi @charlieforward9. Another approach you could try would be to build Turf from source, deploy to a local node repo, and install from there. It's more infrastructure work up front, though less impact on your client code.

It's not as bad as it sounds. Half an hour ball park. Take a look at the wiki for a how to:
https://github.com/Turfjs/turf/wiki/Contributing#deploy-to-a-local-node-registry

**Comment by smallsaucepan** [comment]
News flash @charlieforward9! Since I responded above an even easier option has opened up. The VERY talented @mfedderly has configured the repo to generate a new alpha with every merged PR. For example, the still hot out of the oven [@turf/area 7.0.0-alpha.110](https://www.npmjs.com/package/@turf/area/v/7.0.0-alpha.110) should have the most up to date Turf code, able to be installed directly from npmjs.com. No need to set up local npm repos.

Please give it a try and see how you go!

**Comment by charlieforward9** [comment]
Hey @smallsaucepan , I realize I never you back to you on this. I can confirm that this works with [7.0.0-alpha.113](https://www.npmjs.com/package/@turf/area/v/7.0.0-alpha.113). 

Assuming this is how v7 will be by default, I will assume that this is fixed moving forward and close the issue. Thank you very much for the detailed response.
