### ISSUE TITLE
rhumbBearing returns NaN for certain coordinates

### ISSUE THREAD

**Issue by jellyedwards** [Turfjs/turf#2569]
Hi, it seems `rhumbBearing` returns `NaN` for certain coordinates. I'm not calling this directly but just trying to rotate a polygon & stepped through while debugging. `bearing` works but `transformRotate` uses `rhumbBearing`.

repro code:

```
const pivot = [0, 91];
const pointCoords = [0, 0];
console.log(turf.rhumbBearing(pivot, pointCoords)); // NaN
```

Thanks!

**Comment by NSUSpray** [comment]
I found that there is a problem in the _calculateRhumbBearing_ function: when I try to apply rotation with arguments _from_ (_pivot_) [325, 212.5] and _to_ (_pointCoords_) [375.5, 313], then _phi1_ becomes 3.7 and _phi2_ becomes 5.5, then the logarithm argument in the expression _deltaPsi_ is equals -0.75, i.e. less than zero!

**Comment by smallsaucepan** [comment]
Hi @jellyedwards and @NSUSpray. Taking a look at some of your input points - [0, 91], [325, 212.5], [375.5, 313] - they are outside the bounds of what Turf would typically expect. Longitudes go from -180 to 180, and latitudes from -90 to 90.

Can you please explain a bit more about what you're trying to achieve and what your desired coordinates represent? What are your inputs into transformRotate that are causing these values to end up in rhumbBearing? Thanks!

**Comment by NSUSpray** [comment]
I use the library to create compound paths within _Euclidean_ geometry. Perhaps I’ve chosen the wrong remedy. If you can suggest a better choice, I'll be grateful.

**Comment by smallsaucepan** [comment]
Quite possibly Turf isn't the best choice then. I haven't done a lot in that area, though did find the article below: https://www.akselipalen.com/2021/06/10/2d-geometry-libraries-for-javascript/

flatten-js might be a good candidate? It seems like it's still being maintained and has a [polygon rotate transformation](https://alexbol99.github.io/flatten-js/Polygon.html#rotate) (among others).

**Comment by NSUSpray** [comment]
Thank you, @smallsaucepan, I'll check it out someday! In the meantime I use my own reinvented wheel to rotate the polygons (:

**Comment by smallsaucepan** [comment]
Closing as all the examples included at least one out of bounds element. Please reopen if anything between -180 to 180 / -90 to 90 gives a weird result.
