### ISSUE TITLE
SvelteKit & Typescript 5: Could not find a declaration file for module

### ISSUE THREAD

**Issue by sutanAE** [Turfjs/turf#2570]
# Issues

similar issue to #2565 

Failed to import turf with typescript. How to replicate over [here](https://github.com/sutanAE/svelte-turf-issues).

1. git clone the repo
2. npm install
3. checkout the ```src/routes/+page.server.ts``` file.

It seems like we cannot import turf under typescript 5. The declaration files and package.json need to be updated. Is this an issue that you are aware of?

I'd love to contribute to resolving the issue, but I'm not sure how to provide some. If there's a guide or rough idea, I'd love to look it up and spend some time creating a PR.

(Nevertheless, I'd like to say thank you for this awesome free and open-source repo! It is very helpful to have this tool at hand).

---

# Resolving the issue

modifying the ```tsconfig.json``` file ```moduleResolution``` configuration to ```node``` or ```node10```. This works but it is [deprecated](https://www.typescriptlang.org/tsconfig#moduleResolution) as we are moving towards newer ```node``` versions.

```json
// tsconfig.json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"moduleResolution": "node10" // change this from "bundler" or "Node16"
	}
}

```
---

# Error Message:

```
'turf' is declared but its value is never read.ts(6133)

Could not find a declaration file for module '@turf/turf'. '/projectPath/node_modules/@turf/turf/dist/es/index.js' implicitly has an 'any' type.
  There are types at '/projectPath/node_modules/@turf/turf/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/turf' library may need to update its package.json or typings.ts(7016)
```

---

Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by smallsaucepan** [comment]
Thanks for report @sutanAE. Can you please try with the latest Turf alpha? If the problem still exists with the newer version we can work through what still needs to happen for SvelteKit.

**Comment by sutanAE** [comment]
Hi @smallsaucepan, importing turf alpha worked, `npm i @turf/area@7.0.0-alpha.110`. Many thanks for the solution!
