### ISSUE TITLE
Next.js + TypeScript - Error TS7016

### ISSUE THREAD

**Issue by Fedec96** [Turfjs/turf#2575]
| Component | Version |
| --- | --- |
| **Turf** | 6.5.0 |
| **Next.js** | 14.1.0 |
| **TypeScript** | 5.3.3 |

This simple import is not working:

```ts
import * as turf from "@turf/turf";
```

I'm getting the following error:

> There are types at '/home/user/project/node_modules/@turf/turf/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/turf' library may need to update its package.json or typings. ts(7016)

I installed Turf with this line:

```console
npm i @turf/turf
```

Here's my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "process.d.ts",
    "next-auth.d.ts",
    "mantine-colors.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
```
Any help is appreciated.
Thanks!

**Comment by twelch** [comment]
Please try the latest 7.x alpha version
