### ISSUE TITLE
FeatureCollection (type) not longer exported form @turf/turf (alpha 7.0.0)

### ISSUE THREAD

**Issue by pcace** [Turfjs/turf#2578]
Hi there, i have a project here using Turf 6.5.0 and need to swich to alpha 7.0.0. 
what is the way to the the typings back? for now i was using this: for example: 

import { FeatureCollection, booleanContains, buffer, featureCollection, point } from '@turf/turf'

but i get this error: 

`'"@turf/turf"' has no exported member named 'FeatureCollection'. Did you mean 'featureCollection'?ts(2724)
`

Any help would be awesome! Thanks a lot!

**Comment by twelch** [comment]
You get your types from the @types/geoson package directly.

**Comment by pcace** [comment]
Perfect! Thanks!
