### ISSUE TITLE
Buffer, possibly doesn't buffer all points

### ISSUE THREAD

**Issue by gregorydgarcia** [Turfjs/turf#258]
Stackover explanation of issue

http://stackoverflow.com/questions/30020511/turfjs-buffer-feature-does-not-buffer-every-point-in-geojson

I  am using turfJS's turf.buffer function and interestingly; when I pass it a collection of geojson points only some of them have a buffer generated around them. I have tested this data with other turf methods and have only seen this issue with turf.buffer

Here is a link to a code pen with an example: http://codepen.io/gregorydgarcia/pen/XbbQqB

Here is the JS file

    //INIT MAP
    L.mapbox.accessToken = 'pk.eyJ1IjoiZ3JlZ29yeWRnYXJjaWEiLCJhIjoiNGRMNU13NCJ9.eYlvRKV4vrpXMGBPAs_Amw';
    var map = L.mapbox.map('map', 'gregorydgarcia.m187akkn');
    map.setView([51.513333, -0.136667], 16);

    var pumps = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":1,"name":"Oxford Market"},"geometry":{"type":"Point","coordinates":[-0.13964,51.51628]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":2,"name":"Castle Street East"},"geometry":{"type":"Point","coordinates":[-0.13775,51.51655]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":3,"name":"Malborough News"},"geometry":{"type":"Point","coordinates":[-0.13964,51.51488]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":4,"name":"Oxford Street and Beaners Street"},"geometry":{"type":"Point","coordinates":[-0.13587,51.51602]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":5,"name":"Newman Street"},"geometry":{"type":"Point","coordinates":[-0.13467,51.5162]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":6,"name":"Carnaby Street"},"geometry":{"type":"Point","coordinates":[-0.13955,51.51386]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":7,"name":"Broad Street"},"geometry":{"type":"Point","coordinates":[-0.13661,51.51334]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":8,"name":"Dean Street"},"geometry":{"type":"Point","coordinates":[-0.13164,51.51232]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":9,"name":"Rupert Street"},"geometry":{"type":"Point","coordinates":[-0.13358,51.5121]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":10,"name":"Bridle Street"},"geometry":{"type":"Point","coordinates":[-0.13591,51.51149]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":11,"name":"Warwick Street"},"geometry":{"type":"Point","coordinates":[-0.1382,51.51126]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":12,"name":"Saville Row and Vigo Street"},"geometry":{"type":"Point","coordinates":[-0.13956,51.51009]}},{"type":"Feature","properties":{"marker-color":"#ff8519","marker-size":"medium","marker-symbol":"triangle","id":13,"name":"Tighborne Street"},"geometry":{"type":"Point","coordinates":[-0.134,51.50998]}}]};

    function onEachFeature(feature, layer) {
        // does this feature have a property named popupContent?
        if (feature.properties && feature.properties.id) {
            layer.bindPopup(feature.properties.name);
        }
    }

    L.geoJson(pumps, {
        onEachFeature: onEachFeature
    }).addTo(map);

    function genBuf() {
        var buffer = turf.buffer(pumps, 100, 'feet');
        L.geoJson(buffer).addTo(map);
    };

    $('#buffer').on('click', genBuf);

**Comment by morganherlocker** [comment]
@gregorydgarcia thanks for reporting. This issue has actually been fixed in the latest version of turf-buffer. https://github.com/Turfjs/turf-buffer/issues/12#issuecomment-82547261

[I am releasing](https://github.com/Turfjs/turf/issues/257) turf v3.0.0 this week, and the fix will be included.
