### ISSUE TITLE
Typings doesn't work when `moduleResolution` is `bundler`

### ISSUE THREAD

**Issue by joaoprocopio** [Turfjs/turf#2581]
### Context

I'm on a Vite React project.  
When any modules are imported from `@turf/turf`, or even from its modules, like `@turf/random` I don't get any typing.

When I change the `moduleResolution` to `Node16` I get the Turf typings, but it breaks the Vite typing.

#### Package version

`@turf/turf@6.5.0`

#### Code

```ts
import { randomPoint, tin, clustersDbscan, bbox, centroid } from "@turf/turf"
```

#### TsConfig

Source: https://github.com/tsconfig/bases/blob/main/bases/vite-react.json

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Vite React",
  "_version": "3.0.0",

  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  }
}
```

#### Error

```
Could not find a declaration file for module '@turf/turf'.
'node_modules/@turf/turf/dist/es/index.js' implicitly has an 'any' type.

There are types at 'node_modules/@turf/turf/index.d.ts',
but this result could not be resolved when respecting package.json "exports".

The '@turf/turf' library may need to update its package.json or typings.

ts(7016)
```

**Comment by twelch** [comment]
Please try the 7.0 beta

**Comment by joaoprocopio** [comment]
Thank you @twelch!

It worked! :smile:

**Comment by twelch** [comment]
You can try this patch workaround in this past issue - https://github.com/Turfjs/turf/issues/2438#issuecomment-1624930234.  There are no current plans to do additional 6.x releases that I know of.

Closing this for now, reopen if there is still an active issue.
