### ISSUE TITLE
merge vs union

### ISSUE THREAD

**Issue by amenadiel** [Turfjs/turf#259]
At this point, both merge and union do basically the same. They take N * Feature.Polygon and return one Feature.Polygon or Feature.Multipolygon. The only difference is that union takes the input features from arguments  0 and 1, whereas merge takes the input features from the `features` property of the single argument it expects.

For the sake of simplicity I'd make these two methods into one single variadic method:
- Discard any parameters that are not Feature nor FeatureCollection
- If I get one argument, and it's a Feature, return itself
- If I get one argument, and it's a FeatureCollection, return its merge.
- If I get two arguments and they're both Features, create a collection containing both and return its merge
- If I get two arguments and at least one of them is a FeatureCollection, create a new collection containing every feature inside any of the args, then return its merge.

With this same logic, the variadic method might accept N features or featurecollections, discarding any argument that isn't Feature or FeatureCollection and operating on the result of joining the rest. 

PD: Documentation should mention what happens to properties.

**Comment by tmcw** [comment]
In #307, we removed turf.merge from turf because it's not a true cascaded merge but uses inefficient .union under the hood.
