### ISSUE TITLE
Could not find a declaration file for module '@turf/mask'

### ISSUE THREAD

**Issue by alamenai** [Turfjs/turf#2592]
**Version :** 

![image](https://github.com/Turfjs/turf/assets/20143684/88c02649-fcc5-4156-8dc8-2ff4decb8840)

I installed the mask package using this command:

`
 npm install @turf/mask
`

However, I could not find the package for the Typescript types:

![image](https://github.com/Turfjs/turf/assets/20143684/58509f48-6f6c-45b7-b0ad-4bc4fd57545c)

**Comment by smallsaucepan** [comment]
Hi @alamenai Try the alpha version - [7.0.0-alpha.114](https://www.npmjs.com/package/@turf/mask/v/7.0.0-alpha.114) - which should have better typescript support. Let us know if this helps.

**Comment by kudlav** [comment]
It's because e.g. `@turf/bbox` has the `d.ts` file in `bbox/dist/js/` subfolder, but the `@turf/mask` has it in the root folder `mask/`.

**Comment by alamenai** [comment]
Yes, the alpha version worked as expected.
