### ISSUE TITLE
There was a loss of accuracy when using the turf.intersect function

### ISSUE THREAD

**Issue by x935080361** [Turfjs/turf#2594]
When I was using the turf-intersect function to calculate the intersection of irregular surfaces, due to the high accuracy of the latitude and longitude used, the turf-intersect function automatically truncated 6 decimal places, resulting in self intersection errors
part of the latitude and longitude have 8 decimal places

**Comment by twelch** [comment]
@x935080361 can you please provide a small code sample that demonstrates?  Have you confirmed this behavior with the latest turf release 7.0?

I know that [truncating input](https://github.com/mfogel/polygon-clipping/issues/153) is used to workaround floating point precision issues with the `polygon-clipping` library used by turf for the intersect function.  I'm not aware that truncating is done by default however.

**Comment by twelch** [comment]
Closing without an example to reproduce.  Please feel free to provide and this can be reopened
