### ISSUE TITLE
Property 'booleanPointInPolygon' does not exist on type 'TurfStatic'

### ISSUE THREAD

**Issue by alamenai** [Turfjs/turf#2596]
Versions:

```
 "@turf/buffer": "^6.5.0",
 "@turf/collect": "^6.5.0",
 "@turf/mask": "^7.0.0-alpha.114",
 "@turf/nearest-point-to-line": "^6.5.0",
 "@turf/point-to-line-distance": "^6.5.0",
 "@turf/turf": "^6.5.0",
```

![image](https://github.com/Turfjs/turf/assets/20143684/eaa918aa-2037-4b32-9a18-f02d438513b0)

**Comment by smallsaucepan** [comment]
Hi @alamenai. Can you please show how you're importing @turf/turf?

Also, does your build step fail as well? Or does that work ok, and the only place you see the error is in your editor?

**Comment by smallsaucepan** [comment]
Received no further info after a couple of months. Please re-open with more details if still an issue.
