### ISSUE TITLE
Different values given on not found inField variable for median, max, etc

### ISSUE THREAD

**Issue by sckott** [Turfjs/turf#260]
To not clutter up the issue put code in a gist https://gist.github.com/sckott/7632418964396bb807fe

The math functions give back different things when the `inField` variable is not found, some giving back `NaN` and some `undefined`

Is this intended? I'd naively assume these would behave the same way.

**Comment by tmcw** [comment]
Closing; aggregate functions are replaced by turf-collect, which lets you choose your own statistical routines.
