### ISSUE TITLE
turf.convex does not wrap the polygons as expected

### ISSUE THREAD

**Issue by huco95** [Turfjs/turf#2608]
Truf version: 7.0.0-alpha.116
GeoJson: [https://gist.github.com/huco95/7d40d02a9fe3e7a0f235e6d76a02e037](https://gist.github.com/huco95/7d40d02a9fe3e7a0f235e6d76a02e037)

I am trying to generate a single polygon from a geometry collection using convex, it wraps the polygons as expected on the left side, but it doesn't do the same in the right side. Is this the expected behavior?
![image](https://github.com/Turfjs/turf/assets/2738365/3253f60c-07f3-45e3-80cb-af841ec8647e)

**Comment by smallsaucepan** [comment]
Hi @huco95. I believe this is the correct behaviour. Not an expert in this area, so I'll have to lean on [wikipedia](https://en.wikipedia.org/wiki/Convex_set), which says:

> ... is convex if, given any two points in the subset, the subset contains the whole line segment that joins them.

If the encompassing polygon "hugged" the inner curve, you could draw a line between two points in your input and it would violate the above.

Might [concave](https://turfjs.org/docs/api/concave) do what you want instead?
