### ISSUE TITLE
Point Icons in TURF Sand-box does not have access token 

### ISSUE THREAD

**Issue by l-sola** [Turfjs/turf#2611]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.
- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).
- [x] Verify this issue hasn't already been reported, or resolved in the latest alpha pre-release.

Turf Sand-Box: 
![image](https://github.com/Turfjs/turf/assets/72909751/76ee4fd5-ed3d-4746-a5c6-92db63f08e69)

Turf Doc: 
![image](https://github.com/Turfjs/turf/assets/72909751/96bcc6a7-5713-4f42-8b56-5e0f8d280b9b)

The access token is missing in the sandbox resulting in a broke img

**Comment by twelch** [comment]
@l-sola are you talking about this website? (https://turf-sandbox.netlify.app/)

As far as I know it is not an official project of Turf so I will close this issue, feel free to reopen if you think I misunderstood.  @stebogit do you maintain this project by chance?

**Comment by stebogit** [comment]
@twelch @l-sola I created the turf sandbox when I was more active contributing to Turf essentially to have an easier way of showing issues or solutions using the library. I haven't worked on it for quite a while (and I know it could be very well improved), but I'd be happy to accept PRs for improving it.
