### ISSUE TITLE
Type Error Using Turf.js

### ISSUE THREAD

**Issue by bitcooker** [Turfjs/turf#2614]
I have some typescript error.
- [ ] The version of Turf : "@turf/turf": "^6.5.0"

I installed turf.js following the doc.
![image](https://github.com/Turfjs/turf/assets/128102810/e5640018-ce73-4a22-8a16-28ff83b48d40)

But when I try to use it on my Next.js app (v14), I got a typescript error.

![image](https://github.com/Turfjs/turf/assets/128102810/24414877-5617-41bb-9fc5-791c7410769f)

This is an error :
```
Could not find a declaration file for module '@turf/point-on-feature'. '[...Path...]/node_modules/@turf/point-on-feature/dist/es/index.js' implicitly has an 'any' type.
  There are types at '[...Path...]/node_modules/@turf/point-on-feature/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/point-on-feature' library may need to update its package.json or typings.
```

**Comment by smallsaucepan** [comment]
Hi @bitcooker. This was a known issue with v6.5.0. Try upgrading to v7 where these type definitions have been fixed.
