### ISSUE TITLE
Problem installation of v2.0.1+ when running with meteor // npm shrinkwrap

### ISSUE THREAD

**Issue by TomFreudenberg** [Turfjs/turf#262]
Hi since your shrinkwrap update on v2.0.1 this npm cannot be installed with meteors npm-packages.

![image](https://cloud.githubusercontent.com/assets/410087/7915245/a05e9f64-087c-11e5-9410-701ba8671bcd.png)

In case that no features are changed since v2.0.0 I can run this fine. Would be nice if you could fix that.

Cheers
Tom

**Comment by tmcw** [comment]
Closing; after v3, we don't use shrinkwrap in the same way. Please re-open if you reencounter this issue.

**Comment by TomFreudenberg** [comment]
Thanks Tom @tmcw 

I will check it next time.

Cheers
Tom
