### ISSUE TITLE
FeatureCollection Type

### ISSUE THREAD

**Issue by pdfabbro** [Turfjs/turf#2620]
Where can I import the FeatureCollection type from turf?  After the update to 7.0 

`import { FeatureCollection } from "@turf/turf";`

 does not work.  Similar with GeometryCollection

**Comment by twelch** [comment]
See the CHANGELOG for breaking changes, you need to import these types from the `@types/geojson` package

**Comment by pdfabbro** [comment]
@twelch Thanks!  I looked around but couldn't find the change log

**Comment by twelch** [comment]
You'll find it at the top-level of the repo, it could be made more visible.  I'll reopen this as a documentation task.

**Comment by pdfabbro** [comment]
@twelch It worked, thanks!  I was looking for the change log here https://github.com/Turfjs/turf/releases/tag/v7.0.0 and then here https://github.com/Turfjs/turf/releases

**Comment by twelch** [comment]
Thanks, the release message is automated, maybe an automatic reference to the changelog can get added

**Comment by twelch** [comment]
Resolved by #2621, changelog has been deprecated and starting with next release, the release notes with any migration steps should be found in the Github release notes.
