### ISSUE TITLE
Turf Intersect returns "Error:  Must specify at least 2 geometries"

### ISSUE THREAD

**Issue by Ali5937** [Turfjs/turf#2630]
I'm using version 7.0.0 of turf, and I have the following issue when using intersect: I am unable get the intersection. Instead I get the error: 
"Error:  Must specify at least 2 geometries"

Here is an [example](https://stackblitz.com/edit/solidjs-templates-7fqe5b?file=src%2FApp.tsx)

I tried it with and without using the polygon import in addition to intersect, but that did not make a difference.

**Comment by twelch** [comment]
I believe the 7.0 function takes a FeatureCollection as input which is a change from 6.5, see the new 7.0 docs - https://turfjs.org/docs/api/intersect

`intersect(polygon1, polygon2) -> intersect([polygon1, polygon 2])`

**Comment by CchenQ** [comment]
Uncaught Error: Unknown Geometry Type
