### ISSUE TITLE
turf-union no longer functions as intended

### ISSUE THREAD

**Issue by SortaZach** [Turfjs/turf#2642]
With the new 7.0.0 patch I noticed the union was giving the error that there needed to be at least two geometries, even when two were presented. Tested with the 6.0.0 just to make sure I wasn't crazy and it had been working at this point.

**Comment by twelch** [comment]
Code sample please

**Comment by SortaZach** [comment]
Sure, here's a self-contained, super simple example for ya: 

<!DOCTYPE html>
<html>
<head>
    <title>Two Polygons Broken Example</title>
    <script src="https://cdn.jsdelivr.net/npm/@turf/turf"></script>
</head>
<body>
    <script>
        let polygon1 = {
            type: 'Feature',
            properties: {},
            geometry: {
                type: 'Polygon',
                coordinates: [
                    [
                        [-114.055795, 51.043545],
                        [-114.055816, 51.043702],
                        [-114.055881, 51.043853],
                        [-114.055987, 51.043995],
                        [-114.05613, 51.044124],
                        [-114.056306, 51.044235],
                        [-114.05651, 51.044325],
                        [-114.056737, 51.044391],
                        [-114.056978, 51.044432],
                        [-114.057226, 51.044445],
                        [-114.057475, 51.044432],
                        [-114.057716, 51.044391],
                        [-114.057942, 51.044325],
                        [-114.058146, 51.044235],
                        [-114.058323, 51.044124],
                        [-114.058466, 51.043995],
                        [-114.058571, 51.043853],
                        [-114.058636, 51.043702],
                        [-114.058658, 51.043545],
                        [-114.058636, 51.043389],
                        [-114.058571, 51.043237],
                        [-114.058466, 51.043095],
                        [-114.058323, 51.042967],
                        [-114.058146, 51.042856],
                        [-114.057942, 51.042766],
                        [-114.057716, 51.0427],
                        [-114.057475, 51.042659],
                        [-114.057226, 51.042645],
                        [-114.056978, 51.042659],
                        [-114.056737, 51.0427],
                        [-114.05651, 51.042766],
                        [-114.056306, 51.042856],
                        [-114.05613, 51.042967],
                        [-114.055987, 51.043095],
                        [-114.055881, 51.043237],
                        [-114.055816, 51.043389],
                        [-114.055795, 51.043545]
                    ]
                ]
            }
        };

        let polygon2 = {
            type: 'Feature',
            properties: {},
            geometry: {
                type: 'Polygon',
                coordinates: [
                    [
                        [-114.03944419388338, 51.036473408441495],
                        [-114.03946593765002, 51.03662969195768],
                        [-114.03953050827664, 51.036781226878304],
                        [-114.03963594381739, 51.0369234088915],
                        [-114.03977904066672, 51.03705191786872],
                        [-114.03995545089928, 51.03716284912974],
                        [-114.04015981437944, 51.03725283208433],
                        [-114.04038592162624, 51.037319132645926],
                        [-114.04062690248541, 51.03735973630553],
                        [-114.0408754348755, 51.0373734093415],
                        [-114.04112396726559, 51.03735973630553],
                        [-114.04136494812477, 51.037319132645926],
                        [-114.04159105537157, 51.03725283208433],
                        [-114.04179541885172, 51.03716284912974],
                        [-114.04197182908429, 51.03705191786872],
                        [-114.04211492593362, 51.0369234088915],
                        [-114.04222036147436, 51.036781226878304],
                        [-114.04228493210098, 51.03662969195768],
                        [-114.04230667586762, 51.036473408441495],
                        [-114.04228493210098, 51.03631712492531],
                        [-114.04222036147436, 51.036165590004686],
                        [-114.04211492593362, 51.03602340799149],
                        [-114.04197182908429, 51.03589489901427],
                        [-114.04179541885172, 51.03578396775325],
                        [-114.04159105537157, 51.03569398479866],
                        [-114.04136494812477, 51.03562768423706],
                        [-114.04112396726559, 51.03558708057746],
                        [-114.0408754348755, 51.03557340754149],
                        [-114.04062690248541, 51.03558708057746],
                        [-114.04038592162624, 51.03562768423706],
                        [-114.04015981437944, 51.03569398479866],
                        [-114.03995545089928, 51.03578396775325],
                        [-114.03977904066672, 51.03589489901427],
                        [-114.03963594381739, 51.03602340799149],
                        [-114.03953050827664, 51.036165590004686],
                        [-114.03946593765002, 51.03631712492531],
                        [-114.03944419388338, 51.036473408441495]
                    ]
                ]
            }
        };

        let union = turf.union(polygon1, polygon2);
        console.log('Poly after union: ' + union);
    </script>
</body>
</html>

**Comment by SortaZach** [comment]
Sorry, didn't realize that would break everything. Here's the bit that matters.

        let polygon1 = {
            type: 'Feature',
            properties: {},
            geometry: {
                type: 'Polygon',
                coordinates: [
                    [
                        [-114.055795, 51.043545],
                        [-114.055816, 51.043702],
                        [-114.055881, 51.043853],
                        [-114.055987, 51.043995],
                        [-114.05613, 51.044124],
                        [-114.056306, 51.044235],
                        [-114.05651, 51.044325],
                        [-114.056737, 51.044391],
                        [-114.056978, 51.044432],
                        [-114.057226, 51.044445],
                        [-114.057475, 51.044432],
                        [-114.057716, 51.044391],
                        [-114.057942, 51.044325],
                        [-114.058146, 51.044235],
                        [-114.058323, 51.044124],
                        [-114.058466, 51.043995],
                        [-114.058571, 51.043853],
                        [-114.058636, 51.043702],
                        [-114.058658, 51.043545],
                        [-114.058636, 51.043389],
                        [-114.058571, 51.043237],
                        [-114.058466, 51.043095],
                        [-114.058323, 51.042967],
                        [-114.058146, 51.042856],
                        [-114.057942, 51.042766],
                        [-114.057716, 51.0427],
                        [-114.057475, 51.042659],
                        [-114.057226, 51.042645],
                        [-114.056978, 51.042659],
                        [-114.056737, 51.0427],
                        [-114.05651, 51.042766],
                        [-114.056306, 51.042856],
                        [-114.05613, 51.042967],
                        [-114.055987, 51.043095],
                        [-114.055881, 51.043237],
                        [-114.055816, 51.043389],
                        [-114.055795, 51.043545]
                    ]
                ]
            }
        };

        let polygon2 = {
            type: 'Feature',
            properties: {},
            geometry: {
                type: 'Polygon',
                coordinates: [
                    [
                        [-114.03944419388338, 51.036473408441495],
                        [-114.03946593765002, 51.03662969195768],
                        [-114.03953050827664, 51.036781226878304],
                        [-114.03963594381739, 51.0369234088915],
                        [-114.03977904066672, 51.03705191786872],
                        [-114.03995545089928, 51.03716284912974],
                        [-114.04015981437944, 51.03725283208433],
                        [-114.04038592162624, 51.037319132645926],
                        [-114.04062690248541, 51.03735973630553],
                        [-114.0408754348755, 51.0373734093415],
                        [-114.04112396726559, 51.03735973630553],
                        [-114.04136494812477, 51.037319132645926],
                        [-114.04159105537157, 51.03725283208433],
                        [-114.04179541885172, 51.03716284912974],
                        [-114.04197182908429, 51.03705191786872],
                        [-114.04211492593362, 51.0369234088915],
                        [-114.04222036147436, 51.036781226878304],
                        [-114.04228493210098, 51.03662969195768],
                        [-114.04230667586762, 51.036473408441495],
                        [-114.04228493210098, 51.03631712492531],
                        [-114.04222036147436, 51.036165590004686],
                        [-114.04211492593362, 51.03602340799149],
                        [-114.04197182908429, 51.03589489901427],
                        [-114.04179541885172, 51.03578396775325],
                        [-114.04159105537157, 51.03569398479866],
                        [-114.04136494812477, 51.03562768423706],
                        [-114.04112396726559, 51.03558708057746],
                        [-114.0408754348755, 51.03557340754149],
                        [-114.04062690248541, 51.03558708057746],
                        [-114.04038592162624, 51.03562768423706],
                        [-114.04015981437944, 51.03569398479866],
                        [-114.03995545089928, 51.03578396775325],
                        [-114.03977904066672, 51.03589489901427],
                        [-114.03963594381739, 51.03602340799149],
                        [-114.03953050827664, 51.036165590004686],
                        [-114.03946593765002, 51.03631712492531],
                        [-114.03944419388338, 51.036473408441495]
                    ]
                ]
            }
        };

        let union = turf.union(polygon1, polygon2);
        console.log('Poly after union: ' + union);

**Comment by twelch** [comment]
@SortaZach  turf/union expects a feature collection as input as of v7.  Try turf.union(turf.featureCollection([polygon1, polygon2, ...])

There is already an issue to improve the docs - https://github.com/Turfjs/turf/issues/2657.  Please feel free to close this if your issue is resolved.
