### ISSUE TITLE
@turf/helpers": "6.5.0" - Allows a package to be used in a project with --moduleResolution bundler

### ISSUE THREAD

**Issue by Misinin** [Turfjs/turf#2647]
@turf/helpers": "6.5.0"

`tsconfig.json` my project

```json
{
  "compilerOptions": {
    ...
    "module": "ESNext",
    "moduleResolution": "Bundler",
    ...
    }
}
```

<img width="1536" alt="Screenshot 2024-07-08 at 17 42 59" src="https://github.com/Turfjs/turf/assets/56192086/36dc12f5-a35f-4277-b2b2-0a6f55a33aa7">

I solved this problem by adding a line in `package.json` package a line with the path to the types
```json
{
  "name": "@turf/helpers",
  "version": "6.5.0",
  ...
  "types": "dist/js/index.d.ts",
  "exports": {
    ".": {
      ...
      "types": "./dist/js/index.d.ts"
    },
    ...
}
```

Is this the right decision or am I doing something wrong?

**Comment by cristianmadularu** [comment]
This fix would also help us. We currently are having to keep the module resolution to Node just for this reason.

**Comment by cristianmadularu** [comment]
Thank you @Misinin!
