### ISSUE TITLE
aggregate problem

### ISSUE THREAD

**Issue by ChouGary** [Turfjs/turf#265]
aggregate cant not intersect Greenland
http://fiddle.jshell.net/4erwehmx/

![image](https://cloud.githubusercontent.com/assets/8294943/8470406/605efeb4-20bd-11e5-8c5e-33edf2cddc2b.png)

![image](https://cloud.githubusercontent.com/assets/8294943/8469703/005c7bc8-20b2-11e5-9cb1-345aebd84e6a.png)

**Comment by tmcw** [comment]
Can you view the data in EPSG:4326 and confirm that the point still lies within the polygon?

**Comment by ChouGary** [comment]
the country vector(EPSG:4326) transform Mercator projection(EPSG:3857) 
the image is resize
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mercator_projection_SW.jpg/800px-Mercator_projection_SW.jpg
i try QGIS  , it is not intersect .
![image](https://cloud.githubusercontent.com/assets/8294943/13625321/7b3011e8-e5f1-11e5-9c12-299bd1a48232.png)
![image](https://cloud.githubusercontent.com/assets/8294943/13625345/bb1e55b2-e5f1-11e5-9889-041c9ec49fde.png)
