### ISSUE TITLE
Error: Must specify at least 2 geometries

### ISSUE THREAD

**Issue by qiangliu2017** [Turfjs/turf#2658]
Please provide the following when reporting an issue:

- [ ] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).
- [ ] Verify this issue hasn't already been reported, or resolved in the latest alpha pre-release.

**Comment by smallsaucepan** [comment]
Hi @qiangliu2017 and @asdofindia. The interface of `intersect` changed with the update to v7. Instead of passing in each feature separately, you pass in a single feature collection containing multiple features.

https://turfjs.org/docs/api/intersect
