### ISSUE TITLE
Turf don't Work Why ? 

### ISSUE THREAD

**Issue by snak31** [Turfjs/turf#266]
Hi , I try to use a Javascript page Turf on so I download the file turf.min.js and I add the script in my web page , but none of turf function works .
Thank you for your help

**Comment by morganherlocker** [comment]
I will need  more info to help you out here. At a minimum, please post a code sample and list any errors you are receiving.

**Comment by snak31** [comment]
I is not error the script does not execute it blocks further on turf.point

 var features = [];
    for (i = 0; i<pntzonepolaine.length;i++){
        var pointteste = turf.point([pntzonepolaine[i].lng(), pntzonepolaine[i].lat()]);
           features.push(pointteste)
    }
    var fc = turf.featurecollection(features);

**Comment by morganherlocker** [comment]
@snak31 everything looks normal there as far as turf is concerned. Can you post some sample data for `pntzonepolaine`?

**Comment by snak31** [comment]
7.5130328354837275/48.611156879868396;
7.513062358092839/48.61118142043744;
7.513092524017566/48.61120561660169;
7.513123324069397/48.61122946099024;
7.513154748866555/48.61125294633939;
7.513186788836947/48.611276065494735;
7.5132194342209/48.61129881141348;
7.513252675074568/48.61132117716645;
7.513286501272432/48.61134315594035;
7.5133209025107135/48.61136474103969;
7.513355868310327/48.61138592588896;
7.513391388020182/48.61140670403452;
...

it is the coordonners draw a polygon on Google Maps

**Comment by morganherlocker** [comment]
I would try a script with nothing but the following:

```js
console.log(turf.point([0,0]))
```

If that outputs a geojson point, then you at least know the script is wired up correctly. If it does not, then make sure you are linking to the correct CDN location: https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.0/turf.min.js

**Comment by snak31** [comment]
I just tried and still does not work
I also replace <script src="turf.min.js" charset="utf-8"></script> by <script src="https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.0/turf.min.js" charset="utf-8"></script> and so is :(

**Comment by morganherlocker** [comment]
> I just tried and still does not work

Tried which suggestion? Both? I'm happy to help out, but I'll need more info and/or code here to walk you through the problem. The turf code you posted should definitely work fine, provided everything is wired up correctly.

**Comment by snak31** [comment]
http://pastebin.com/3DUmzEKm That part of my code or I put the script

**Comment by snak31** [comment]
http://pastebin.com/3DUmzEKm That part of my code or I put the script

**Comment by snak31** [comment]
http://pastebin.com/XscHvTBv and it is the function or would like to use turf

**Comment by morganherlocker** [comment]
Try moving your script tag for turf up above the script you are using it in. [modified example](https://gist.github.com/morganherlocker/eb8d1fe80d32a13ef594)

**Comment by snak31** [comment]
i have 
![image](https://cloud.githubusercontent.com/assets/13276528/8625418/f4574e8c-273e-11e5-9733-7e26a41bff15.png) and 
![image](https://cloud.githubusercontent.com/assets/13276528/8625432/04257334-273f-11e5-92ed-292002da1a53.png)

**Comment by snak31** [comment]
If i use turf.min.js in local file i have 
![image](https://cloud.githubusercontent.com/assets/13276528/8625941/03bbd836-2742-11e5-8007-a7189a81d5b6.png)

**Comment by snak31** [comment]
i think i found the problem i use IE7.0 if i use a superior version you think the problem will be correct ?

**Comment by morganherlocker** [comment]
@snak31 That would cause a problem for sure. Turf requires a browser engine with [ES5 or later](http://kangax.github.io/compat-table/es5/).

**Comment by snak31** [comment]
The problem is solved lthough it was a version of IE that was too basic

**Comment by morganherlocker** [comment]
Glad to hear it @snak31! :smile:

**Comment by snak31** [comment]
@morganherlocker  Thank you :D but a new problem with buffer :(
