### ISSUE TITLE
Intersect returns multilinestring / close a polygon

### ISSUE THREAD

**Issue by tfarneau** [Turfjs/turf#268]
Hello,

I've got 2 polygons, a square and a complex one. I would like to get the intersection of them, to calculate the area of the complex one in this square.

The blue square is the "container", and the red polygon is the polygon I want to cut.

<img width="703" alt="capture d ecran 2015-07-20 a 10 34 01" src="https://cloud.githubusercontent.com/assets/3899690/8772280/28d5083c-2ecb-11e5-993c-88d6fb222da9.png">

I've made a `turf.intersect`, it worked as you can see : 

<img width="732" alt="capture d ecran 2015-07-20 a 10 33 01" src="https://cloud.githubusercontent.com/assets/3899690/8772294/5aece5f6-2ecb-11e5-997d-db42042b5165.png">

But the problem is that the returning polygon is multilinestring, and not a polygon / multipolygon. Here is the multilinestring returned.

<img width="705" alt="capture d ecran 2015-07-20 a 10 35 22" src="https://cloud.githubusercontent.com/assets/3899690/8772313/7842cdbe-2ecb-11e5-9111-4d3ced9f63b1.png">

Is there a way to force turf to return a multipolygon ? Or a method which can close this multilinestring, and transform it to polygon or multipolygon ? 

Thank you

**Comment by morganherlocker** [comment]
@tfarneau Can you post a gist with your polygons' geojson? I have never seen this behavior before.

**Comment by rowanwins** [comment]
Closing for to a lack of information. If you'd like us to look at it further it would be great if you could prove a jsfiddle or a gist containing the Groudon.
