### ISSUE TITLE
booleanIntersects between v6 and v7 return different values

### ISSUE THREAD

**Issue by aaronkyle** [Turfjs/turf#2700]
Please provide the following when reporting an issue:

I was using Turf@7 when I discovered this issue.  I can verify that it doesn't happen with Turf@6.

Here are two Observable notebooks with the same code, but different Turf.js versions:

- Turf@7: https://observablehq.com/d/7c4d04a94a359361
- Turf@6: https://observablehq.com/d/979097a9b1512042

With Turf@6, my bounding box allows me to filter a source data file by objects correctly.  

![Screenshot from 2024-08-12 20-25-15](https://github.com/user-attachments/assets/db03692f-dad7-4ebe-999e-1ac100947ea9)

In Turf@7, I am seeing returns from the opposite side of the globe.

![Screenshot from 2024-08-12 20-24-37](https://github.com/user-attachments/assets/28e7b371-1415-412f-9f12-03b634d11bfe)

**Comment by smallsaucepan** [comment]
Hi @aaronkyle. Thanks for reporting this. Can't actually view your examples unless I log in, which I'd rather not have to :) Can you post to a https://jsfiddle.net instead?

Can you also please attach the Geojson data going in to and returned from booleanIntersects? And if not a JSFiddle, a snippet of the surrounding code as well.

**Comment by aaronkyle** [comment]
Hi @smallsaucepan .  Thank you for looking into this. I apologize that I missed making one of those notebooks public.  I fixed them so that you can review without logging in.  The source .geojson is 40MB, so rather large to attached, however it is included as a file attachment on the notebook.  I'll also link to it from a GitHub repo.

To decrease all the clutter from the notebook where I discovered the issue, I have created a minimal notebook example here:
https://observablehq.com/d/ae03f49d4dd9b456

In this example, I load both versions of Turf (6 and 7) and use them in otherwise identical functions, where they return different outputs.  These outputs are attached (and can also be pulled from the notebook).
[visibleFeatures_turf7.json](https://github.com/user-attachments/files/16620483/visibleFeatures_turf7.json)
[visibleFeatures_turf6.json](https://github.com/user-attachments/files/16620484/visibleFeatures_turf6.json)

Here's the link to the source .geojson:  https://github.com/aaronkyle/kba-table-view/blob/master/src/kba-2022-10-poly-simp.geojson

Hope this helps!

**Comment by aaronkyle** [comment]
Looking back at the returned features, the geometries do indeed have negative values, so my original assumption about what is happening to cause these differences is incorrect.  I'll update the title of this issue.
