### ISSUE TITLE
along - incorrect result if coords on LineString are in Australia

### ISSUE THREAD

**Issue by mallbeury** [Turfjs/turf#271]
When using LineStrings of coords in Australia then 'along' returns an incorrect result.

It appears to return correct latitudes but returns longitudes not on the LineString.

When I test with LineStrings in Europe all works as expected.

With the example LineString below recorded in Australia then using:
**turf.along(routeLine, 0, 'kilometers');** gives:

{"type":"Feature","geometry":{"type":"Point","coordinates":[-34.95117,138.67244]},"properties":{}}

Whereas using:
**turf.along(routeLine, 1, 'kilometers');** gives:

{"type":"Feature","geometry":{"type":"Point","coordinates":[-34.95255389154767,41.31979543863804]},"properties":{}}

Which is not a valid point!

**This is the LineString:**

{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-34.95117,138.67244],[-34.95117,138.67244],[-34.951183,138.67255],[-34.95118,138.67258],[-34.951122,138.67268],[-34.95104,138.67278],[-34.950985,138.67287],[-34.950928,138.67297],[-34.950882,138.6731],[-34.950832,138.6732],[-34.950768,138.67331],[-34.950687,138.67337],[-34.950615,138.67345],[-34.95054,138.67355],[-34.95048,138.67368],[-34.950436,138.6738],[-34.950462,138.6739],[-34.950462,138.6739],[-34.950462,138.6739],[-34.95053,138.67413],[-34.950466,138.67424],[-34.950375,138.67433],[-34.950375,138.67433],[-34.950375,138.67433],[-34.950375,138.67445],[-34.950375,138.67445],[-34.950375,138.67445],[-34.950233,138.67451],[-34.950123,138.67455],[-34.950027,138.67458],[-34.949932,138.67465],[-34.949852,138.67473],[-34.949776,138.67482],[-34.949715,138.67491],[-34.94967,138.67503],[-34.949657,138.67514],[-34.949726,138.67532],[-34.949757,138.67542],[-34.949795,138.67555],[-34.949814,138.67569],[-34.949814,138.67583],[-34.94984,138.67596],[-34.949852,138.67609],[-34.949833,138.67621],[-34.94986,138.67635],[-34.949883,138.67645],[-34.949917,138.67657],[-34.94992,138.67671],[-34.94992,138.67671],[-34.94992,138.67671],[-34.95001,138.6771],[-34.950024,138.67722],[-34.950024,138.67722],[-34.950043,138.67735],[-34.95006,138.6775],[-34.950108,138.67763],[-34.950165,138.67772],[-34.95024,138.67781],[-34.950302,138.6779],[-34.950367,138.67801],[-34.950417,138.67812],[-34.950493,138.6782],[-34.95053,138.67834],[-34.95059,138.67845],[-34.950665,138.67853],[-34.950745,138.67859],[-34.950825,138.67867],[-34.950916,138.67874],[-34.951015,138.67879],[-34.951084,138.67888],[-34.951084,138.67888],[-34.951084,138.67888],[-34.951084,138.67888],[-34.951084,138.67888],[-34.951084,138.67888],[-34.951214,138.67896],[-34.951317,138.67899],[-34.951317,138.67899],[-34.951412,138.67903],[-34.951504,138.67903],[-34.951607,138.67903],[-34.951706,138.67906],[-34.951782,138.67914],[-34.95189,138.67918],[-34.951977,138.67923],[-34.95204,138.6793],[-34.952106,138.67941],[-34.95218,138.67949],[-34.952255,138.67957],[-34.95234,138.67966],[-34.952385,138.67976],[-34.952427,138.6799],[-34.952477,138.68001],[-34.95252,138.68013],[-34.95257,138.68024],[-34.952644,138.68031],[-34.9527,138.68044],[-34.952763,138.68053],[-34.95284,138.6806],[-34.952904,138.68071],[-34.952976,138.68079],[-34.952976,138.68079],[-34.952976,138.68079],[-34.95304,138.6809],[-34.95304,138.6809],[-34.95304,138.6809],[-34.95313,138.68094],[-34.953217,138.68086],[-34.953217,138.68086],[-34.95338,138.68086],[-34.95348,138.68088],[-34.95348,138.68088],[-34.95348,138.68088],[-34.95359,138.68097],[-34.95359,138.68097],[-34.95359,138.68097],[-34.953632,138.68085],[-34.953564,138.68074],[-34.953564,138.68074],[-34.95349,138.68066],[-34.953392,138.68065],[-34.953297,138.68065],[-34.953297,138.68065],[-34.953297,138.68065],[-34.953156,138.68047],[-34.95314,138.68036],[-34.95314,138.68036],[-34.953144,138.68025],[-34.953144,138.68011],[-34.95317,138.68001],[-34.9532,138.6799],[-34.953236,138.6798],[-34.953236,138.6798],[-34.9533,138.6797],[-34.95333,138.67958],[-34.953358,138.67946],[-34.953384,138.67935],[-34.95333,138.67923],[-34.953247,138.67917],[-34.953167,138.67911],[-34.953056,138.67903],[-34.952972,138.67897],[-34.95286,138.679],[-34.952766,138.67903],[-34.95267,138.67902],[-34.95267,138.67902],[-34.95267,138.67902],[-34.95267,138.67902],[-34.95271,138.67892],[-34.95271,138.67892],[-34.95271,138.67892],[-34.952667,138.67868],[-34.952682,138.67856],[-34.952682,138.67856],[-34.95269,138.67844],[-34.952667,138.67831],[-34.952587,138.67825],[-34.952587,138.67825],[-34.952503,138.6782],[-34.952503,138.6782],[-34.952503,138.6782],[-34.952324,138.67802],[-34.952324,138.67802],[-34.952324,138.67802],[-34.952236,138.67795],[-34.95216,138.6779],[-34.952072,138.67786],[-34.952072,138.67786],[-34.95196,138.67781],[-34.951862,138.67778],[-34.95177,138.67775],[-34.95169,138.67769],[-34.951637,138.67758],[-34.951656,138.67746],[-34.95175,138.67741],[-34.95185,138.67738],[-34.951946,138.67734],[-34.952038,138.67732],[-34.95214,138.6773],[-34.952244,138.67728],[-34.95235,138.67726],[-34.952454,138.67722],[-34.95253,138.67714],[-34.952606,138.67708],[-34.952675,138.677],[-34.95277,138.67693],[-34.95282,138.67683],[-34.952877,138.67673],[-34.95293,138.67664],[-34.95298,138.67651],[-34.95304,138.6764],[-34.95311,138.67633],[-34.95324,138.67632],[-34.953327,138.67624],[-34.953403,138.67616],[-34.953403,138.67616],[-34.953403,138.67616],[-34.95349,138.67603],[-34.95349,138.67603],[-34.95349,138.67603],[-34.95354,138.67592],[-34.95354,138.67592],[-34.95354,138.67592],[-34.95354,138.67592],[-34.95354,138.67592],[-34.95354,138.67592],[-34.953674,138.67586],[-34.953766,138.67583],[-34.953766,138.67583],[-34.953766,138.67583],[-34.953945,138.67581],[-34.95404,138.67583],[-34.95404,138.67583],[-34.95412,138.67589],[-34.954197,138.67596],[-34.954292,138.67603],[-34.954388,138.67606],[-34.95447,138.67609],[-34.95457,138.67612],[-34.954655,138.67615],[-34.95474,138.67622],[-34.954826,138.6763],[-34.954906,138.67636],[-34.954987,138.67644],[-34.95504,138.67653],[-34.95504,138.67653],[-34.95504,138.67653],[-34.955143,138.67659],[-34.955227,138.67665],[-34.9553,138.67676],[-34.95538,138.67683],[-34.95542,138.67697],[-34.955437,138.67708],[-34.95544,138.67722],[-34.955444,138.67734],[-34.95543,138.67746],[-34.955402,138.6776],[-34.95537,138.67772],[-34.95535,138.67786],[-34.95532,138.67798],[-34.955307,138.67809],[-34.95531,138.6782],[-34.955303,138.67831],[-34.955288,138.67842],[-34.955265,138.67854],[-34.955223,138.67865],[-34.955223,138.67876],[-34.955235,138.67888],[-34.955223,138.67899],[-34.95525,138.67911],[-34.95526,138.67923],[-34.955265,138.67937],[-34.95525,138.67947],[-34.95525,138.67961],[-34.955265,138.67973],[-34.955265,138.67973],[-34.955265,138.67973],[-34.955265,138.67973],[-34.955357,138.68008],[-34.955376,138.68019],[-34.955418,138.6803],[-34.955475,138.68039],[-34.95553,138.68051],[-34.955566,138.68062],[-34.955612,138.68073],[-34.955647,138.68086],[-34.955673,138.68097],[-34.95572,138.68109],[-34.955757,138.68121],[-34.955822,138.6813],[-34.95586,138.68143],[-34.955894,138.68153],[-34.955894,138.68153],[-34.955933,138.68164],[-34.955982,138.68175],[-34.95601,138.68187],[-34.956055,138.68199],[-34.956112,138.68207],[-34.95616,138.68219],[-34.9562,138.6823],[-34.956226,138.68242],[-34.95626,138.68254],[-34.956306,138.68265],[-34.956352,138.68275],[-34.956394,138.68288],[-34.956394,138.68288],[-34.956417,138.68298],[-34.956436,138.6831],[-34.956436,138.6831],[-34.956463,138.68323],[-34.9565,138.68333],[-34.956516,138.68346],[-34.956543,138.68356],[-34.956543,138.68356],[-34.956566,138.68369],[-34.956566,138.68369],[-34.956566,138.68369],[-34.956566,138.68369],[-34.95658,138.68384],[-34.9566,138.68396],[-34.9566,138.68396],[-34.95662,138.68408],[-34.956646,138.6842],[-34.956665,138.68431],[-34.95669,138.68443],[-34.956715,138.68454],[-34.95674,138.68466],[-34.95676,138.68478],[-34.95678,138.6849],[-34.956814,138.68504],[-34.95684,138.68513],[-34.956863,138.68524],[-34.95689,138.68536],[-34.95692,138.6855],[-34.95694,138.68562],[-34.956955,138.68573],[-34.956963,138.68587],[-34.95697,138.68599],[-34.956963,138.6861],[-34.956947,138.68622],[-34.95694,138.68634],[-34.95693,138.68646],[-34.956917,138.6866],[-34.95695,138.6867],[-34.956955,138.68684],[-34.956974,138.68695],[-34.957005,138.68707],[-34.957005,138.68718],[-34.957005,138.6873],[-34.95699,138.68741],[-34.95698,138.68753],[-34.957016,138.68764],[-34.957016,138.68764],[-34.95708,138.68771],[-34.95712,138.68784],[-34.957157,138.68796],[-34.957157,138.68796],[-34.957184,138.68806],[-34.957184,138.68806],[-34.95723,138.68817],[-34.957275,138.68826],[-34.957336,138.68837],[-34.957394,138.68846],[-34.957394,138.68846],[-34.957436,138.68857],[-34.95748,138.68867],[-34.95748,138.68867],[-34.95748,138.68867],[-34.957508,138.68886],[-34.957516,138.68898],[-34.95753,138.6891],[-34.95753,138.6891],[-34.95757,138.68922],[-34.957645,138.68929],[-34.95772,138.68936],[-34.957798,138.68942],[-34.957874,138.68951],[-34.957962,138.68959],[-34.958054,138.68967],[-34.95814,138.68974],[-34.95823,138.68983],[-34.958294,138.68991],[-34.958336,138.69002],[-34.958374,138.69016],[-34.958412,138.69028],[-34.95845,138.69038],[-34.958485,138.69048],[-34.958523,138.69061],[-34.958576,138.6907],[-34.95864,138.6908],[-34.95869,138.69095],[-34.958733,138.69106],[-34.95878,138.69115],[-34.958836,138.69125],[-34.95889,138.69135],[-34.958935,138.69147],[-34.95897,138.69157],[-34.959015,138.69168],[-34.959076,138.69179],[-34.95914,138.6919],[-34.959198,138.692],[-34.959267,138.69211],[-34.95933,138.69218],[-34.959393,138.69228],[-34.95944,138.69237],[-34.95948,138.69247],[-34.959553,138.69258],[-34.959633,138.69269],[-34.959694,138.69276],[-34.95978,138.69284],[-34.95985,138.69292],[-34.95992,138.693],[-34.959976,138.6931],[-34.960064,138.69313],[-34.960064,138.69313],[-34.960144,138.69318],[-34.960144,138.69318],[-34.960144,138.69318],[-34.96028,138.6931],[-34.96039,138.69312],[-34.96048,138.69313],[-34.96059,138.69313],[-34.960682,138.69313],[-34.960785,138.69315],[-34.960876,138.69316],[-34.960957,138.6932],[-34.96102,138.6933],[-34.961086,138.69339],[-34.961143,138.69351],[-34.9612,138.6936],[-34.96128,138.6937],[-34.961338,138.6938],[-34.961353,138.69392],[-34.961384,138.69405],[-34.961414,138.69418],[-34.961445,138.69429],[-34.961487,138.6944],[-34.961544,138.6945],[-34.961605,138.69458],[-34.961678,138.69469],[-34.96176,138.69478],[-34.961872,138.69489],[-34.961956,138.69498],[-34.962032,138.69508],[-34.96209,138.69518],[-34.96215,138.69528],[-34.962177,138.69539],[-34.962204,138.6955],[-34.962227,138.6956],[-34.96225,138.69572],[-34.96226,138.69586],[-34.962303,138.696],[-34.96234,138.69612],[-34.96237,138.69623],[-34.962418,138.69637],[-34.96245,138.69647],[-34.96245,138.69647],[-34.96245,138.69647],[-34.962475,138.69664],[-34.962463,138.69675],[-34.962463,138.69675],[-34.962463,138.69675],[-34.96249,138.6969],[-34.96245,138.697],[-34.962482,138.69711],[-34.962498,138.69725],[-34.962498,138.69725],[-34.96248,138.69739],[-34.962452,138.69751],[-34.96243,138.69763],[-34.9624,138.69775],[-34.962368,138.69789],[-34.96233,138.69801],[-34.96223,138.69803],[-34.962124,138.69806],[-34.962067,138.69818],[-34.96208,138.69829],[-34.962097,138.69844],[-34.96216,138.69856],[-34.962196,138.69867],[-34.962246,138.69878],[-34.96233,138.69885],[-34.962387,138.69896],[-34.962452,138.69905],[-34.96258,138.6991],[-34.962677,138.69914],[-34.962765,138.69919],[-34.962868,138.69923],[-34.962967,138.69928],[-34.963062,138.69931],[-34.963062,138.69931],[-34.963062,138.69931],[-34.963245,138.69931],[-34.96334,138.69933],[-34.963425,138.6994],[-34.963516,138.69943],[-34.963516,138.69943],[-34.963627,138.6995],[-34.963737,138.69954],[-34.963825,138.6996],[-34.96389,138.69968],[-34.963966,138.69975],[-34.964035,138.69986],[-34.96408,138.69998],[-34.964134,138.70009],[-34.964184,138.70021],[-34.964214,138.70032],[-34.96428,138.70044],[-34.964367,138.70049],[-34.964397,138.70059],[-34.964447,138.7007],[-34.9645,138.70082],[-34.964554,138.70091],[-34.964645,138.70096],[-34.96472,138.70105],[-34.964783,138.70113],[-34.964813,138.70126],[-34.964855,138.70139],[-34.964897,138.7015],[-34.964924,138.70161],[-34.96494,138.70174],[-34.96497,138.70187],[-34.964996,138.70198],[-34.96506,138.70209],[-34.96513,138.70218],[-34.96519,138.7023],[-34.965256,138.70242],[-34.9653,138.70255],[-34.96533,138.70267],[-34.965397,138.70274],[-34.965496,138.7028],[-34.9656,138.70287],[-34.965714,138.7029],[-34.965828,138.7029],[-34.965942,138.70291],[-34.96605,138.70291],[-34.96615,138.70294],[-34.966244,138.703],[-34.966286,138.70311],[-34.96629,138.70322],[-34.96625,138.70335],[-34.966164,138.70343],[-34.966164,138.70343],[-34.96607,138.70341],[-34.96607,138.70341],[-34.96607,138.70341],[-34.965843,138.70338],[-34.965763,138.70345],[-34.965725,138.70355],[-34.965725,138.70355],[-34.965687,138.70367],[-34.9657,138.7038],[-34.96569,138.70392],[-34.965668,138.70404],[-34.965645,138.70416],[-34.965645,138.70427],[-34.965633,138.70439],[-34.9656,138.7045],[-34.96557,138.70439],[-34.965515,138.70428],[-34.965466,138.70418],[-34.965466,138.70418],[-34.965466,138.70418],[-34.965496,138.70389],[-34.965458,138.70377],[-34.96543,138.70363],[-34.965424,138.70349],[-34.96541,138.70335],[-34.965343,138.70325],[-34.965305,138.70314],[-34.965263,138.70303],[-34.96519,138.70296],[-34.96509,138.70287],[-34.96503,138.70277],[-34.964943,138.70268],[-34.96488,138.70259],[-34.964806,138.70245],[-34.96472,138.70236],[-34.96464,138.70226],[-34.964584,138.70215],[-34.96456,138.70204],[-34.964535,138.70193],[-34.96448,138.70183],[-34.96441,138.70172],[-34.964336,138.70164],[-34.96427,138.70152],[-34.964203,138.70142],[-34.964115,138.70134],[-34.964024,138.70131],[-34.963943,138.70122],[-34.963943,138.70122],[-34.963905,138.70108],[-34.963867,138.70094],[-34.963787,138.70085],[-34.963787,138.70085],[-34.963722,138.70073],[-34.963657,138.70062],[-34.96361,138.70053],[-34.963554,138.70044],[-34.963554,138.70044],[-34.963554,138.70044],[-34.963436,138.70038],[-34.963356,138.7003],[-34.96326,138.70027],[-34.963165,138.70023],[-34.963062,138.70016],[-34.96297,138.70012],[-34.962887,138.70007],[-34.962788,138.70006],[-34.962696,138.70004],[-34.962578,138.70004],[-34.962486,138.70004],[-34.96239,138.70006],[-34.96228,138.7001],[-34.96219,138.70015],[-34.96211,138.70021],[-34.962086,138.70035],[-34.962086,138.70035],[-34.962063,138.70047],[-34.961987,138.70055],[-34.9619,138.70059],[-34.961807,138.70064],[-34.96173,138.70071],[-34.961636,138.70076],[-34.961536,138.70079],[-34.961445,138.70074],[-34.961365,138.70067],[-34.961365,138.70067],[-34.961365,138.70067],[-34.961334,138.70052],[-34.96127,138.70042],[-34.96127,138.70042],[-34.96118,138.7004],[-34.961086,138.70033],[-34.960995,138.70027],[-34.960915,138.70023],[-34.96081,138.70021],[-34.960697,138.70021],[-34.960594,138.70021],[-34.96052,138.70027],[-34.960438,138.70038],[-34.960392,138.70047],[-34.960384,138.7006],[-34.96036,138.70073],[-34.960316,138.70084],[-34.960236,138.70088],[-34.960194,138.70074],[-34.960136,138.70065],[-34.96005,138.70055],[-34.959984,138.70044],[-34.95988,138.70033],[-34.959805,138.70026],[-34.95974,138.70016],[-34.959656,138.70009],[-34.959602,138.69998],[-34.959545,138.69987],[-34.959488,138.69975],[-34.95942,138.69963],[-34.959354,138.6995],[-34.959305,138.69939],[-34.95926,138.69926],[-34.95919,138.69916],[-34.959145,138.69904],[-34.95909,138.69894],[-34.95904,138.69882],[-34.95897,138.69873],[-34.958904,138.69864],[-34.958862,138.69852],[-34.958828,138.69841],[-34.95879,138.6983],[-34.958755,138.69818],[-34.958717,138.69809],[-34.9587,138.69795],[-34.95875,138.69783],[-34.958763,138.69771],[-34.95878,138.69759],[-34.958786,138.69743],[-34.958767,138.69731],[-34.95873,138.6972],[-34.95869,138.6971],[-34.958637,138.69696],[-34.95859,138.69682],[-34.958565,138.69672],[-34.958534,138.69661],[-34.958485,138.69652],[-34.95841,138.69641],[-34.95834,138.69632],[-34.958267,138.69621],[-34.95822,138.6961],[-34.95817,138.696],[-34.95817,138.696],[-34.958115,138.69588],[-34.958096,138.69576],[-34.958008,138.69574],[-34.958008,138.69574],[-34.958042,138.69563],[-34.95804,138.69551],[-34.95801,138.69539],[-34.95795,138.69527],[-34.957905,138.69514],[-34.957863,138.69502],[-34.95782,138.69492],[-34.957767,138.69481],[-34.957714,138.69467],[-34.957676,138.69456],[-34.957623,138.69447],[-34.95754,138.69438],[-34.95743,138.69432],[-34.95734,138.69427],[-34.95726,138.69418],[-34.95718,138.69408],[-34.957104,138.694],[-34.957027,138.69391],[-34.956947,138.6938],[-34.95684,138.69376],[-34.95675,138.69371],[-34.95664,138.69368],[-34.95654,138.69366],[-34.95645,138.6936],[-34.956394,138.69353],[-34.956375,138.6934],[-34.956337,138.69328],[-34.956257,138.69318],[-34.956196,138.69307],[-34.956146,138.69295],[-34.956093,138.69286],[-34.95602,138.69276],[-34.955936,138.69267],[-34.955875,138.69258],[-34.955822,138.69249],[-34.955772,138.69238],[-34.955784,138.69223],[-34.955776,138.69212],[-34.955727,138.69202],[-34.955666,138.69194],[-34.955597,138.69186],[-34.955517,138.69176],[-34.955467,138.69167],[-34.955467,138.69167],[-34.955467,138.69167],[-34.955467,138.69167],[-34.955456,138.69151],[-34.955418,138.6914],[-34.955353,138.69133],[-34.955265,138.69127],[-34.955177,138.69122],[-34.95508,138.69116],[-34.95498,138.69112],[-34.954884,138.69106],[-34.954815,138.69096],[-34.95475,138.69087],[-34.954685,138.69077],[-34.954628,138.69066],[-34.954544,138.69057],[-34.954487,138.69048],[-34.9544,138.69038],[-34.954338,138.69028],[-34.954323,138.69017],[-34.95435,138.69006],[-34.954384,138.68993],[-34.954407,138.6898],[-34.954338,138.68971],[-34.954254,138.68962],[-34.954163,138.68959],[-34.95406,138.68956],[-34.954018,138.68944],[-34.953957,138.68935],[-34.953903,138.68922],[-34.95386,138.6891],[-34.953846,138.689],[-34.953846,138.68887],[-34.953842,138.68874],[-34.95382,138.6886],[-34.953804,138.68846],[-34.95382,138.68835],[-34.953815,138.68823],[-34.953815,138.68823],[-34.953815,138.68823],[-34.953743,138.68806],[-34.953743,138.68806],[-34.953743,138.68806],[-34.953655,138.68799],[-34.9536,138.68785],[-34.95356,138.68776],[-34.95348,138.68768],[-34.953438,138.68758],[-34.953423,138.68745],[-34.95343,138.68732],[-34.95346,138.6872],[-34.953476,138.68706],[-34.95351,138.68692],[-34.95355,138.68681],[-34.95353,138.68669],[-34.95349,138.68658],[-34.95349,138.68646],[-34.95351,138.68633],[-34.95355,138.68622],[-34.95361,138.68613],[-34.953697,138.68602],[-34.953773,138.68594],[-34.953846,138.68587],[-34.953896,138.68578],[-34.953903,138.68564],[-34.953907,138.68553],[-34.95392,138.68541],[-34.953957,138.68529],[-34.95403,138.6852],[-34.954082,138.68509],[-34.954117,138.68495],[-34.954174,138.68486],[-34.954174,138.68486],[-34.954205,138.68471],[-34.95416,138.68457],[-34.954197,138.68446],[-34.954178,138.68434],[-34.95418,138.68423],[-34.95418,138.68423],[-34.954197,138.68411],[-34.95418,138.68399],[-34.954163,138.68385],[-34.95414,138.68373],[-34.954098,138.68361],[-34.954063,138.6835],[-34.954037,138.68338],[-34.95403,138.68326],[-34.954018,138.68312],[-34.954,138.683],[-34.953987,138.68285],[-34.95398,138.68274],[-34.953976,138.6826],[-34.953983,138.68245],[-34.953987,138.68233],[-34.953964,138.68217],[-34.953934,138.68207],[-34.953903,138.68195],[-34.953888,138.68181],[-34.95388,138.6817],[-34.953865,138.68156],[-34.953846,138.68143],[-34.953808,138.68129],[-34.95379,138.68118],[-34.953754,138.68108],[-34.953754,138.68108],[-34.953754,138.68108],[-34.953575,138.68094],[-34.953575,138.68094],[-34.953575,138.68094],[-34.95344,138.68088],[-34.95344,138.68088],[-34.95344,138.68088],[-34.953297,138.68083],[-34.9532,138.68085],[-34.95311,138.68082],[-34.95308,138.68068],[-34.95306,138.68057],[-34.953026,138.68044],[-34.95297,138.68034],[-34.95288,138.68024],[-34.952812,138.6801],[-34.95272,138.68001],[-34.95266,138.67992],[-34.952602,138.67984],[-34.952522,138.67973],[-34.952465,138.67963],[-34.952396,138.67953],[-34.952324,138.67943],[-34.952267,138.67934],[-34.9522,138.67921],[-34.95212,138.67912],[-34.952023,138.67908],[-34.95192,138.67905],[-34.951824,138.67902],[-34.951744,138.67896],[-34.95165,138.6789],[-34.951553,138.67885],[-34.95146,138.6788],[-34.951374,138.67877],[-34.951263,138.67873],[-34.95116,138.67867],[-34.951065,138.67862],[-34.950966,138.67856],[-34.95087,138.67848],[-34.95076,138.6784],[-34.95067,138.6783],[-34.950584,138.6782],[-34.9505,138.6781],[-34.950443,138.67798],[-34.950382,138.67787],[-34.950348,138.67776],[-34.9503,138.67764],[-34.950237,138.67755],[-34.950184,138.67744],[-34.950134,138.67735],[-34.950104,138.67725],[-34.950104,138.67725],[-34.950077,138.67714],[-34.95005,138.677],[-34.95005,138.677],[-34.950016,138.67685],[-34.95003,138.67671],[-34.950027,138.6766],[-34.950005,138.67648],[-34.949974,138.67635],[-34.949955,138.67621],[-34.949947,138.67607],[-34.949944,138.67592],[-34.949944,138.6758],[-34.949924,138.67566],[-34.949913,138.67554],[-34.949898,138.67542],[-34.949886,138.6753],[-34.949886,138.67517],[-34.9499,138.67505],[-34.94995,138.67493],[-34.950035,138.67484],[-34.950108,138.67474],[-34.950195,138.67468],[-34.95027,138.6746],[-34.950314,138.67451],[-34.95037,138.67442],[-34.950428,138.6743],[-34.9505,138.67421],[-34.950554,138.67412],[-34.950623,138.67403],[-34.950676,138.67392],[-34.950745,138.67378],[-34.95079,138.67368],[-34.950844,138.67352],[-34.95088,138.67337],[-34.95092,138.67323],[-34.95095,138.67313],[-34.951004,138.67302],[-34.951073,138.67294],[-34.951153,138.67284],[-34.95123,138.67274],[-34.951286,138.67264]]}}

**Comment by rowanwins** [comment]
Hi @mallbeury 

It looks like the root of your problem ould be the order of your linestring lat/lngs. GeoJSON puts the lat lng's in a different order. If in doubt paste your geojson into (http://geojson.io/)[http://geojson.io/].

A valid point in Adelaide
````
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      138.67244, -34.95117
    ]
  },
  "properties": {}
}
````
An invalid point in the middle of nowhere
````
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      -34.95117, 138.67244
    ]
  },
  "properties": {}
}
````

Hope that helps,

Cheers
Rowan

**Comment by mallbeury** [comment]
Thanks so much for your help Rowan, I did indeed have the points around the wrong way!
