### ISSUE TITLE
Request for iImproved instructions to build a modular version

### ISSUE THREAD

**Issue by stev-0** [Turfjs/turf#272]
Some instructions about how to build a package with only specific modules in would be good. I managed to build using the command `browserify 'path/to/module/index.js' -s turf-buffer > output.js` but I couldn't work out how to package multiple modules in one.

**Comment by rowanwins** [comment]
Gday @stev-0 

Agreed that some more doco would be handy. I'm no browserify expert but this is what I've come up with and it seems to be working for multiple modules...

#### Step 1
Create a folder and install whatever modules you are interested in via npm
````
npm install turf-aggregate turf-featurecollection
````
This will create a new directory called node_modules 

#### Step 2
Create a file called main.js , in this include your required modules within a modules.exports statement
````
module.exports = {
  aggregate: require('turf-aggregate'),
  featurecollection: require('turf-featurecollection'),
};
````

#### Step 3
Run the following browserify command
````
browserify main.js -s turf >output.js
````

#### Hooray
You can now use your output.js file where you want just like normal
````
var fc = turf.featurecollection(polys);	
````

Dont forget to minify your output file to help get the size down. I gather you can do this via browserify by chaining in something like uglify.js but getting this far was enough for one day :) 

Hope that helps,

Cheers
Rowan

**Comment by morganherlocker** [comment]
Thanks @rowanwins, great answer.

**Comment by rowanwins** [comment]
Gday @morganherlocker 

Just as a followup idea I've started work on a build tool UI which would let users tick some boxes to generate a custom browserify package. Its a simple node/express based app. 

Current approach is
- it resides in a folder called build.
- it scans the node_modules folder in the directory above and grabs anything containing "turf"
- the list of modules is used to generate the checkbox columns in the UI
- User checks some boxes and hits a build button which calls express and runs some browserify command and writes to file (haven't done this bit yet but hoping it's not too hard!)

Anyway Im happy to take any guidance or ideas. If and when I get it to a more usable state I'll open up a proper ticket and pull request.

Cheers
Rowan

![buildtool](https://cloud.githubusercontent.com/assets/6735870/9293265/3adb4f6c-4467-11e5-942f-138073a24375.jpg)
