### ISSUE TITLE
Great circle

### ISSUE THREAD

**Issue by turban** [Turfjs/turf#273]
Great library! Any plans to add a function returning a great circle polyline from two points?

**Comment by morganherlocker** [comment]
Thanks @turban! I had not considered it yet. I typically recommend people use: https://www.mapbox.com/mapbox.js/example/v1.0.0/arcjs/

**Comment by DenisCarriere** [comment]
Implemented with [`@turf/great-circle`](https://github.com/Turfjs/turf/pull/607)
