### ISSUE TITLE
turf clean-coords fails to remove redundant coordinates

### ISSUE THREAD

**Issue by ventralnet** [Turfjs/turf#2730]
@turf/clean-coords 7.1.0

With the given input 
```
const latlngs = [
    [-180, -18.15942123021],
    [-142.3828125, -17.807876978977],
    [-153.468530967904, -9.370851446924],
    [-69.9609375, -9.370851446924],
    [-69.9609375, 36.681445464573],
    [-180, 36.681445464573],
    [-180, 20.186244484817],
    [-180, 30.353685439917],
    [-180, -18.15942123021],
]
```

Clean coords fails to remove the redundant coordinates of 
```
    [ -180, 20.186244484817 ],
    [ -180, 30.353685439917 ],
```

For an example showing these please see 
https://github.com/ventralnet/turfjs-clean-coords-bug
```
npm install
npm run exec
```

For a work around I found a documented side effect of @turf/union to be the removal of redudant coordinates on shapes.  So I am basically unioning the polygon above with itself which gives correct results.

#  Sample Code
```
const cleanCoords = require('@turf/clean-coords').cleanCoords;
const union = require('@turf/union').union;
const helpers = require('@turf/helpers');

const latlngs = [
    [-180, -18.15942123021],
    [-142.3828125, -17.807876978977],
    [-153.468530967904, -9.370851446924],
    [-69.9609375, -9.370851446924],
    [-69.9609375, 36.681445464573],
    [-180, 36.681445464573],
    [-180, 20.186244484817],
    [-180, 30.353685439917],
    [-180, -18.15942123021],
]

const turfPolygon = helpers.polygon([latlngs]);

console.log('original coordinates');
console.log(turfPolygon.geometry.coordinates);

let cleanCoordsResult = cleanCoords(turfPolygon);

console.log('clean coordinates results');
console.log(cleanCoordsResult.geometry.coordinates);

const featureCollection = helpers.featureCollection([turfPolygon, turfPolygon]);

let unionResult = union(featureCollection);

console.log('union shape with self (side effect of removing superfluous points). This is expected');
console.log(unionResult.geometry.coordinates);
```

# Sample output
```
original coordinates
[
  [
    [ -180, -18.15942123021 ],
    [ -142.3828125, -17.807876978977 ],
    [ -153.468530967904, -9.370851446924 ],
    [ -69.9609375, -9.370851446924 ],
    [ -69.9609375, 36.681445464573 ],
    [ -180, 36.681445464573 ],
    [ -180, 20.186244484817 ],
    [ -180, 30.353685439917 ],
    [ -180, -18.15942123021 ]
  ]
]
clean coordinates results
[
  [
    [ -180, -18.15942123021 ],
    [ -142.3828125, -17.807876978977 ],
    [ -153.468530967904, -9.370851446924 ],
    [ -69.9609375, -9.370851446924 ],
    [ -69.9609375, 36.681445464573 ],
    [ -180, 36.681445464573 ],
    [ -180, 20.186244484817 ],
    [ -180, 30.353685439917 ],
    [ -180, -18.15942123021 ]
  ]
]
union shape with self (side effect of removing superfluous points). This is expected
[
  [
    [ -180, -18.15942123021 ],
    [ -142.3828125, -17.807876978977 ],
    [ -153.468530967904, -9.370851446924 ],
    [ -69.9609375, -9.370851446924 ],
    [ -69.9609375, 36.681445464573 ],
    [ -180, 36.681445464573 ],
    [ -180, -18.15942123021 ]
  ]
]
```

**Comment by smallsaucepan** [comment]
Hi @ventralnet. Thanks for reporting this. I think I have a reasonably compelling argument those points ***in that order*** are not redundant. Considering the relevant points:

'''
[-180, 36.681445464573], <-- start point
[-180, 20.186244484817], <-- heads south a fair way
[-180, 30.353685439917], <-- heads back NORTH a bit, retracing the path
[-180, -18.15942123021], <-- resumes heading SOUTH again to end point
'''

This is actually three lines travelling in opposite directions drawn over the top of one another. Is that an intentional feature of this polygon?

**Comment by ventralnet** [comment]
@smallsaucepan Interest catch here.  I could see this happening in my use case, but is preventable.  In my application this could happen when joining and trimming two user drawn shape to the 'world bounds'.

I think I consider this a bug on my side with the logic that is trimming the polygon to fit within -180,180/90,-90

We could close this unless this is a case you think clean-coords should handle?

**Comment by smallsaucepan** [comment]
I would agree. That trimming approach might cause the effect we see here. In that regard it would be something to handle from your side.

From Turf's point of view (looking at the original example) it wouldn't  be right for cleanCoords to handle removing those points. The visible shape might not change, but the perimeter would.

I will go ahead and close this issue. Thanks for working through it with us, and please sing out if you run into any other issues.
