### ISSUE TITLE
turf-tin is behaving weird

### ISSUE THREAD

**Issue by AbelVM** [Turfjs/turf#2731]
Using turf-tin `7.1.0`, I get weird super weird results in my app

From these points
![image](https://github.com/user-attachments/assets/a3ff1b5f-2872-4ae9-a110-2ec2990ee78d)

To these cells (`cells = tin(points, 'COTA')`), 
![image](https://github.com/user-attachments/assets/7dec0f8f-30e9-4548-b53e-157714e93425)

Using [TurfJS playground](https://turf-sandbox.netlify.app/), I get the same results, so this behaviour is not caused by my custom code
![image](https://github.com/user-attachments/assets/e5b286a6-21b4-431c-ad15-735858e6d224)

The points GeoJSON: 
[test.json](https://github.com/user-attachments/files/17349735/test.json)

Any idea?

**Comment by smallsaucepan** [comment]
Thanks @AbelVM. Did a little troubleshooting by zooming in on the point where most of the additional lines seemed to originate from and deleting it. Only to find another point right underneath!

In that spot there are two identical points (search for COTA of 532.5087719298245) with ids 54 and 1227. De-duplicating that point (located in the yellow circle) led to the improvement below:

![Screenshot 2024-10-12 at 10 40 28 PM](https://github.com/user-attachments/assets/3ceea5d8-f0a9-44a2-b495-e64a5b0db10c)

Looks like there are several more duplicates for you to find, though hopefully this will set you on the correct path.

**Comment by AbelVM** [comment]
Holy Toledo! The data was processed with Tippecanoe to produce PMTiles, and it's clustered, so there shouldn't be any dups at all!! So,once added some forced dedup...
![image](https://github.com/user-attachments/assets/7a7d6bd8-c8b9-4a22-8420-96aa5258837f)

Thanks for the heads up, I'm closing this
