### ISSUE TITLE
dotDensity module

### ISSUE THREAD

**Issue by jseppi** [Turfjs/turf#275]
Hey @morganherlocker - I made a module for creating the points for dot density maps: https://github.com/jseppi/turf-dot-density
Would you be interested in having this in Turf?

**Comment by morganherlocker** [comment]
@jseppi I'm a bit on the fence with this one. It seems like more of a visualization technique than a typical geospatial processing function. @vtcraghead proposed something similar recently though, so maybe its something many people need. My other concern is that there are [more scalable](https://www.mapbox.com/tilemill/docs/guides/styling-polygons/#patterns-and-textures) [ways](http://linfiniti.com/2011/08/new-hatching-modes-in-qgis-master-line-pattern-fill/) to accomplish this effect without actually encoding all the point geometries. ie: pattern fills, shaders, etc. It might cause a lot of headaches if people are guided down paths that hurt their performance.

**Comment by jseppi** [comment]
Yeah, I'm with you on those points.
The functionality of generating a number of random points within a polygon could potentially be brought into [turf-random](https://github.com/turfjs/turf-random), perhaps when `options.feature` is specified instead of `options.bbox`.

**Comment by jseppi** [comment]
Maybe stuff like this could go on turfjs.org in a Recipes section on the Learn page.
