### ISSUE TITLE
featureCollection disregards properties

### ISSUE THREAD

**Issue by VipSaran** [Turfjs/turf#2763]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using: [7.1.0](https://unpkg.com/@turf/turf@7.1.0/turf.min.js)
- [x] GeoJSON data: https://gist.github.com/VipSaran/a1efe5e65b32877a3f3cd7a223652a46/raw/fe9a11d86708fa26a69be7664d83ed289ab1faa5/featureCollection.geojson
- [x] Snippet of source code:
```
  const boatGeoJsonProps = {
    "class": boatClass,
    "boat": boatName,
    "color": boatColor
  };
// {
//     "class": "Cruisers",
//     "boat": "Buri",
//     "color": "gray"
// }
  const boatGeoJsonPoint = turf.point([position.coords.latitude, position.coords.longitude]);
  const boatGeoJsonLines = turf.lineString(boatGeoPositions);
  const boatGeoJson = turf.featureCollection([boatGeoJsonPoint, boatGeoJsonLines], boatGeoJsonProps);
```
- [x] Verify this issue hasn't already been reported, or resolved in the latest alpha pre-release (tested also with 7.1.0-alpha.70)

A FeatureCollection is created correctly with the 2 Features (Point & LineString) specified, but the specified properties object (`boatGeoJsonProps`) is simply omitted. This is not according to current docs:
![image](https://github.com/user-attachments/assets/d24addd2-bcc6-4a34-91c7-20fdb6126934)

**Comment by smallsaucepan** [comment]
Thanks for reporting this @VipSaran. That's not quite how that parameter works though. It only allows certain options (bbox and id) to be passed to the function, which are then set for specific elements of the featureCollection. Other entries (in your example class, boat, color) are ignored.

Please let us know if that doesn't explain what you're seeing.

**Comment by VipSaran** [comment]
@smallsaucepan thanks for the quick response and clarification.
