### ISSUE TITLE
Custom browserify build tool

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#277]
Gday @morganherlocker 

Well I've had a go at creating a custom [Browserify build tool](https://github.com/rowanwins/turf-builder) for Turf.  

I suspect it could be optimised and improved a bit, I'm not a node or Browserify expert by any stretch but I thought I'd make a start and put something on the table so happy for any feedback.

I'm happy to keep it standalone or if you'd like to incorporate it under the Turf banner that's cool as well.

Anyway I hope it helps,
Cheers
Rowan

**Comment by morganherlocker** [comment]
This is really cool. I think it makes sense to be standalone, but we should link to it from the docs once its up and running.

**Comment by rowanwins** [comment]
@morganherlocker  when you say up and running it there anything inparticular you'd like to see added? 

In an ideal world it would be awesome just to have this as available as a website rather than forcing people to download it but Im not sure how feasible that is....  I'll have a think.

**Comment by rowanwins** [comment]
Gday @tcql and @morganherlocker 

Well this is up and running properly now.
https://turfjs-builder.herokuapp.com/

Im hosting it from Heroku with their cheapest not-free plan and it seems to be working well. 

I've also added a turf version number to it so users which is handy. I guess we'll just need to update the app every now and again as turf gets updated.

Do you have a suggestion on the best way to add something to the turf documentation? In turf-www? Somewhere else?

Cheers,
Rowan

PS I've also whacked some google analytics on there so that'll be interesting to see how many people use the thing :)

**Comment by tcql** [comment]
For now lets just put a note somewhere in the README in this repo, probably in / around the section about using turf in the browsere / with Browserify

**Comment by morganherlocker** [comment]
I linked to the app with an explanation in the docs https://github.com/Turfjs/turf/commit/759607c115dccbbd6b05fa8f1d1699c7e00fe83e

Thanks @rowanwins, the UI looks great!

**Comment by Tazaf** [comment]
This. Is. Awesome !
Thanks a lot !
