### ISSUE TITLE
Buffering MultiPolygons

### ISSUE THREAD

**Issue by MateoV** [Turfjs/turf#279]
Using `turf.buffer` on a MultiPolygon sometimes results in missing polygons.

Example: https://gist.github.com/MateoV/ce1ad0c6cd8368db540e

_before buffer_
![geojson io-3](https://cloud.githubusercontent.com/assets/843058/9421197/f2397cf0-4823-11e5-88d3-96f56dd50c5c.jpg)

_after buffer_
![geojson io-4](https://cloud.githubusercontent.com/assets/843058/9421222/46603710-4824-11e5-8d3a-4edc4deb2c3e.jpg)

**Comment by rowanwins** [comment]
Hi @MateoV 

Testing with the latest version of turf this appears to be resolved. 
https://jsfiddle.net/npp8zr4y/2/

Let me know if you continue to have issues otherwise I'll close this.

Cheers
