### ISSUE TITLE
Transit Walk Shed

### ISSUE THREAD

**Issue by stevepepple** [Turfjs/turf#284]
I wanted to know if you've considered a feature or function for calculating a walk shed based upon a origin Point. 

I have a few ideas for an implementation using Turf-only libraries: 

1. Given a point, find interecting LineStrings or PolyLines
2. Using a constant or variable pedestrian walk time and distance, calculate the distance along each path. 
3. Add the end point of each walk path to a polygon.
4. Return polygon. 

Of course, many other factors could be considered in the method.

**Comment by morganherlocker** [comment]
I think that road networks are out of scope for turf. It would require us to extend the GeoJSON spec in brittle ways, and could not return reliable objective results (GeoJSON does not support conncected graphs, which is a foundational data structure for routing problems). I can think of many ways a user might approximate this, such as the method you described, but I think that should be up to them to implement and decide on tradeoffs.
