### ISSUE TITLE
Turf.Along() seems not to be working right

### ISSUE THREAD

**Issue by TimoRuetten** [Turfjs/turf#287]
I have a problem with the along() method of turfJS. It seems that turfJS has problems with my coordinates.

```javascript
    var alongLine = {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [-37.86902659740041, 144.6185302734375],
          [-37.86902659740041, 145.57159423828125]
        ]
      }
    };
    
    var newPoint = Turf.along(alongLine, 1, 'miles');
    console.log('Walked 1 miles', newPoint);
```
After the code was running this is the console log I get:
```javascript
      Walked 1 miles { type: 'Feature',
    geometry: { 
      type: 'Point',
      coordinates: [ -37.86902659740041, 35.367001095372345 ] },
      properties: {} 
    }
```

As you can see the coordinates are -37. and 35. But when walking 1 mile along this line (which is -37 and 145) I cant understand why its this far away point  (its like the half of the earth away of the line!).

When working with the test coordinates in the docs of TurfJS it seems to work fine, but with my coordinates its breaking. How can this be ?

The docs with the along example you can find here:
http://turfjs.org/static/docs/module-turf_along.html

When using their example coordinates 
```javascript
    [-77.031669, 38.878605],
    [-77.029609, 38.881946],
    ...
```
the result is (even when only using 2 points and using less then a mile: its always the right point which is returned):
```javascript
    Walked 1 miles { type: 'Feature',
    geometry: { 
      type: 'Point',
      coordinates: [ -77.02417351582903, 38.885335546214506 ] },
      properties: {} 
    }
```

Stackoverflow reference: http://stackoverflow.com/questions/33151191/turfjs-along-method-not-working-as-expected

**Comment by jseppi** [comment]
I think you might have your coordinates reversed. GeoJSON expects `[lon, lat]` (ref http://www.macwright.org/lonlat/)

**Comment by TimoRuetten** [comment]
Thanks @jseppi - I've expected that Turf is working with lat lng. I've calculated the hole time in this ordering ... so now I have to rewrite my script :) Thanks for the answer!
