### ISSUE TITLE
quick question about grids.

### ISSUE THREAD

**Issue by nikolinsko** [Turfjs/turf#290]
Hi there! 

Not sure if this is the right place to ask this kind of question, but stackoverflow does not seem to be very active regarding turf (yet).
Im currently working on visualizing behaviour of users on maps. It would be great to use your hex/point/square grids. Im currently doing the following:

1) get a bbox with turf.extend of my FeatureCollection of Points -> turf.extent
2) span a hexgrid over the coordinates, with units changing dynamically with the zoom level. -> turf.hexGrid
3) aggregate my Points against the hexgrid ->turf.aggregate
4) remove any Features that do not have a count > 0 -> turf.remove

this works well on low zoomLevels or Data that does not span over a large area. But im obviously running into trouble. Im also using crossfilter/dc exensively so i need to minimize computing power.

I guess i could loop through the array containing the points and delete any points that do not poccess close neighbours using turf.nearest. But this seems pretty inefficient.. (-edit- aaand does not work, ill still be left with a huge bbox in the worst case)
Has anybody done this and could give me some advice of a better solution?

I know this is a pretty general question, but im kind of lost right now. 

greets!

**Comment by jvail** [comment]
Not sure if this helps: If the bottleneck is in calc. if a point is in a cell or not something like https://github.com/mourner/rbush might help you. As far as I understand you already adjust the total no. of grid cells by in-/decreasing the width...

**Comment by morganherlocker** [comment]
As @jvail pointed out, rbush or a similar spatial indexing library will be needed to make this efficient.
