### ISSUE TITLE
turf.difference is not a function

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Turfjs/turf#291]
Documentation fails to: http://turfjs.org/static/docs/module-turf_difference.html. It seems that difference is still exposed as .erase while the docs state that it should be difference. I'm using turf 2.0.2, and can confirm that .erase works but .difference doesn't

**Comment by zvaraondrej** [comment]
Can confirm as well. Any progess?

**Comment by davinkevin** [comment]
Same thing : 
![image](https://cloud.githubusercontent.com/assets/1970922/11951233/8669e858-a88f-11e5-9a84-2a0089ee382d.png)

**Comment by tcql** [comment]
We're actively working now on wrapping everything up for a turf release sometime soon - probably shortly after the holidays. This will be resolved then. For now, keep using `turf.erase`. If you want to future-proof your code you could do something simple like this: 

```
if (turf.erase) turf.difference = turf.erase;
```

and start using `turf.difference` now.

**Comment by wboykinm** [comment]
@tcql Note the docs are still throwing this error.

**Comment by tmcw** [comment]
Difference is now uniformly exposed as difference, not erase, and [same with docs](http://turfjs.org/docs/#difference).
