### ISSUE TITLE
Using EPSG:3857

### ISSUE THREAD

**Issue by mcbaker256** [Turfjs/turf#292]
I wanted to get the area given a polygon that was EPSG:3857 coordinates.  I set the CRS property correctly but the function always returned 0.  I transformed my coordinates to lat, lon and ran the area function and it returned the correct value.  Is using 3857 not possible?  How should I define CRS? Anything special I should do?  I don't really want to have to transform to geographic and back all the time.

Thanks in advanced

**Comment by tmcw** [comment]
Turf only supports EPSG:4326 and alternative projection support is unlikely. You can project your files just-in-time with a tool like [proj4js](http://proj4js.org/) if you'd like to keep your data in EPSG:3857.
