### ISSUE TITLE
turf.concave() returned undefined at high precision

### ISSUE THREAD

**Issue by roblav96** [Turfjs/turf#294]
Currently I'm using the turf.concave method to convert a feature of points to a polygon.
```javascript
var hull = turf.concave( fc, 1, 'miles' )
```
Although I can't make the polygon concave on points lower than 1 mile. If I try:
```javascript
var hull = turf.concave( fc, 0.001, 'miles' )
```
hull returns undefined.

Any ideas? I need to get a better accuracy reading here. Thank you!!!

**Comment by roblav96** [comment]
This is how I achieved this before turf:
```javascript
var latLngBounds = new plugin.google.maps.LatLngBounds( this.d.bound )
var center = latLngBounds.getCenter()

// this.d.bound is my array of points
_.forEach( this.d.bound, function ( v, i ) {
	this.d.bound[ i ].bearing = this.computeHeading( center, v )
} )

this.d.bound.sort( function ( a, b ) {
	return ( a.bearing - b.bearing )
} )

this.computeHeading = function ( start, end ) {
	var lat1 = start.lat * Math.PI / 180;
	var lat2 = end.lat * Math.PI / 180;
	var lng1 = start.lng * Math.PI / 180;
	var lng2 = end.lng * Math.PI / 180;
	return Math.atan2( Math.sin( lng2 - lng1 ) * Math.cos( lat2 ), Math.cos( lat1 ) * Math.sin( lat2 ) - Math.sin( lat1 ) * Math.cos( lat2 ) * Math.cos( lng2 - lng1 ) ) * 180 / Math.PI;
}
```
Basically I want to sort out an exploded polygon of points. I'm very excited about using turf and I look forward to moving all my geo to it. Thank you!!!

**Comment by rowanwins** [comment]
Gday @roblav96 , could you send some sample points? 

There is nothing wrong with going into the decimals as evidenced by [this example](http://turfjs.party/#/c9fe2a99d4d681d65861) , I'm guessing the issue is around the spacing of the points and the size of the edge you're setting...

Cheers
Rowan

**Comment by roblav96** [comment]
Sorry I was not able to get back to you sooner. Hold on let me put something together for you.

**Comment by roblav96** [comment]
Here are the points for this demo:
http://geojson.io/#id=gist:anonymous/165bdfb1b1e396c6dbe7&map=15/42.3369/-71.1686

Here is the code:
```javascript
turTurfItRealGoooood: function () {
	var features = []
	_.forEach( this.markers, function ( value, index ) {
		var point = turf.point( [ value.point.lng, value.point.lat ] )
		features.push( point )
	} )
	console.log( 'features >', features )

	var fc = turf.featurecollection( features )
	console.log( 'fc >', fc )

	var hull = turf.concave( fc, 0.001, 'miles' )
	console.log( 'hull >', hull )
},
```
The variable 'fc' are the points on the map I posted.

**Comment by rowanwins** [comment]
Gday @roblav96 

So it looks like it is the maxEdge setting that it throwing things out for you
http://turfjs.party/#/de35288c26dd7d456ff9

By setting the maxEdge at .001 miles you are basically saying each polygon edge should only be .001miles however your points are not spaced that closely together. 

So basically if your points are close together you can set a very small maxEdge however if your points are far apart you need to increase your maxEdge setting.

That's probably the best I can offer without knowing more about your use case...

Cheers
Rowan
