### ISSUE TITLE
`turf.within` doc example maps are confusing

### ISSUE THREAD

**Issue by nickidlugash** [Turfjs/turf#296]
http://turfjs.org/static/docs/module-turf_within.html

This example shows three maps: one map for each of the two input feature collections, and one for the returned collection. The zoom level of the map for the returned collection is higher than the other two, which makes it confusing to compare:

![turfwithin](https://cloud.githubusercontent.com/assets/5607844/11488743/e3f4af80-9796-11e5-8e8b-93e3e6c79949.png)

Per @morganherlocker, mapbox.js automatically fits the bounds to whatever the geometry needs to be displayed. To get around this issue, the example data might be able to be manipulated to always fit the same zoom.

**Comment by tcql** [comment]
If we change the `searchWithin` geometry to 

```js
 var searchWithin = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-46.653,-23.543],
          [-46.624,-23.53],
          [-46.613,-23.543],
          [-46.614,-23.559],
          [-46.631,-23.567],
          [-46.653,-23.560],
          [-46.653,-23.543]
        ]]
      }
    }
  ]
};
```

it should look better

<img width="957" alt="screen shot 2015-12-03 at 11 28 55 am" src="https://cloud.githubusercontent.com/assets/348805/11566616/2f474a26-99b1-11e5-9614-53fbe4988a4e.png">
<img width="953" alt="screen shot 2015-12-03 at 11 29 18 am" src="https://cloud.githubusercontent.com/assets/348805/11566618/30b5fc54-99b1-11e5-8026-03729d756cab.png">
<img width="948" alt="screen shot 2015-12-03 at 11 29 29 am" src="https://cloud.githubusercontent.com/assets/348805/11566623/333a57cc-99b1-11e5-8be8-a212ba7ea8d7.png">

**Comment by tmcw** [comment]
We no longer have comparison maps of this type.
