### ISSUE TITLE
Union vector polygons and count overlapping areas

### ISSUE THREAD

**Issue by mapbaker** [Turfjs/turf#298]
Is it possible to combine / union multiple vector polygons using Turf.js and add up the number of intersecting polygons?

For example, I might buffer 3 points and create 3 polygons.

I then want to add up how many buffers overlap.

The output would be an intersect or union type of result, but with polygons split up where there are intersects, and values given to each polygon for how many overlapping polygons were part of the intersect.

**Comment by morganherlocker** [comment]
There is no explicit function for this (it is a pretty unique/specific usecase), but it would be straight forward to wire this up with existing modules.

Pseudocode for counting number of overlaps for each polygon:

```
given: a list of polygons

foreach polygon (poly1):
  poly1.properties.overlap = 0
  foreach polygon (poly2):
    overlap = turf.intersect(poly1, poly2)
    if(overlap) poly1.properties.overlap++
```

Expect this to be slow on large/dense datasets. If you need to run this against large datasets, I would recommend creating a spatial index via [rbush](https://github.com/mourner/rbush) or [tile-cover](https://github.com/mapbox/tile-cover) to minimize the number of comparisons computed.
