### ISSUE TITLE
buffer as ellipsis

### ISSUE THREAD

**Issue by beckerIGG** [Turfjs/turf#300]
hi,

i am wondering about the elliptical buffer issue. is that currently solved? i used the npm install and got the newest turf. however the buffer is still elliptical. do you have a solution for that? I use the buffer for an analysis what is inside a radius of e.g. 500 m around a specific point. in my case some points on the left and right to the point are not found, but it should. so the buffer is created wrong. Any ideas?

**Comment by tmcw** [comment]
The ticket for that is https://github.com/Turfjs/turf-buffer/issues/7 and given that it's open, the issue is not yet fixed.
