### ISSUE TITLE
iso-bands not in release.

### ISSUE THREAD

**Issue by derricksimpson** [Turfjs/turf#302]
I noticed that some older builds included iso-bands, (https://github.com/Turfjs/turf-isobands), but it isn't included in the final build... (turf.min.js).  From looking at some of the samples, I assume it's due to the fact that it may contain some bugs (artifacts of joined lines).  

Could it possibly be refined and add it back to the dist? 

Thanks!

**Comment by morganherlocker** [comment]
>  From looking at some of the samples, I assume it's due to the fact that it may contain some bugs (artifacts of joined lines). 

Correct, my isobands implementation was not up to snuff, so we decided to deprecate it for now.

**Comment by StefanoGitHub** [comment]
Hi @morganherlocker,
I implemented my `isoband` function using [`MarchingSquaresJS.js`](https://github.com/RaumZeit/MarchingSquares.js) and the contouring works just fine.
However occasionally I'm seeing some overlapping issues in the final data layer (I'm rendering the contour on a Google Map).
Would you mind considering a PR on the `turf-isoband` module and have a look to my solution?
I believe the issue might be in the MarchingSquares algorithm, though.

Thanks
