### ISSUE TITLE
using "no" coordinate system

### ISSUE THREAD

**Issue by ju-ien** [Turfjs/turf#305]
Was wondering if there was a way to use turf for general geometry and not just geography, e.g. that
var polygonTest = turf.polygon([
          [
            [ 0.0, 0.0 ],
            [ 0.0, 1.0 ],
            [ 1.0, 1.0 ],
            [ 1.0, 0.0 ],
            [ 0.0, 0.0 ]
          ]
        ], {
    "fill": "#6BC65F",
    "stroke": "#6BC65F",
    "stroke-width": 5
});
console.log(turf.area(polygonTest))

would return 1.0

**Comment by tmcw** [comment]
This is a neat suggestion, but I don't think that it lines up with the vision for Turf - geographical points aren't just points in a coordinate system, but on a sphere - distance, for instance, would need an entirely different algorithm to work on the cartesian plane. [mikolalysenko's code](https://github.com/mikolalysenko) will likely be useful for many of the common geometric problems instead, and it would be cool to see a cartesian-plane turf equivalent sprout up at some point.

**Comment by mourner** [comment]
I agree with Tom. Adding support for generic coordinates could make implementations significantly more complicated. Let's keep Turf focused on geospatial problems.

**Comment by charlieforward9** [comment]
> cartesian-plane turf equivalent 

https://github.com/alexbol99/flatten-js ?

Is there a better one? 

I am a growing vis.gl developer and am looking for a solution to coordinate system math that would interoperate with turf for cartesian projections.
