### ISSUE TITLE
aggregable functions not working with compost propertie object

### ISSUE THREAD

**Issue by carolgit** [Turfjs/turf#308]
example: feature.properties.units.gas

**Comment by tmcw** [comment]
Please give more information to make this issue clearer. What turf function are you using, what is the desired effect, what happens instead?

**Comment by carolgit** [comment]
I'm using an  aggregation array and two geojson with polygons

2016-02-16 13:00 GMT-02:00 Tom MacWright <notifications@github.com>:

**Comment by tmcw** [comment]
What turf function are you using, what is the desired effect, what happens instead? Please answer these questions.

**Comment by carolgit** [comment]
does not find propertie fields and return a FeatureCollection with no
features

2016-02-16 18:31 GMT-02:00 Tom MacWright <notifications@github.com>:

**Comment by carolgit** [comment]
Sorry, it does return features but not make the math of anything like this:

   1. pa_biogas_avg: NaN
   2. pa_biogas_deviation: null
   3. pa_biogas_max: undefined
   4. pa_biogas_median: null
   5. pa_biogas_min: undefined
   6. pa_biogas_sum: 0
   7. pa_biogas_variance: null


2016-02-17 8:04 GMT-02:00 Ana Caroline Ferreira <
ana.caroline.ferreir@gmail.com>:

**Comment by tmcw** [comment]
These aggregate functions are now replaced by turf-combine, which exposes a simpler interface and allows you to optionally change the way nulls are calculated.

**Comment by wondie** [comment]
How can I aggregate points in polygon using sum, average, etc in turf combine?

"Combines a FeatureCollection of Point, LineString, or Polygon features into MultiPoint, MultiLineString, or MultiPolygon features." source https://www.npmjs.com/package/@turf/combine
