### ISSUE TITLE
not possible aggregable functions with polygons 

### ISSUE THREAD

**Issue by carolgit** [Turfjs/turf#309]
some times the FeatureCollection that contains the data is polygon type

**Comment by tmcw** [comment]
Please give more information to make this issue clearer. What turf function are you using, what is the desired effect, what happens instead?

**Comment by morganherlocker** [comment]
@carolgit It's up to you to make sure your second parameter is a FeatureCollection of Point Features.

<img width="747" alt="screenshot 2016-02-26 15 28 25" src="https://cloud.githubusercontent.com/assets/814300/13368251/98704136-dc9d-11e5-8194-622066e58a3d.png">

**Comment by carolgit** [comment]
It is possible if you use the centroind of the polygons

2016-02-26 20:29 GMT-03:00 Morgan Herlocker <notifications@github.com>:
