### ISSUE TITLE
check circle within polygon

### ISSUE THREAD

**Issue by ultrasonicsoft** [Turfjs/turf#312]
Hi There,

I am using leaflet and turf for drawing shapes on map.

I am trying to check whether a circle is within a polygon/rectangle/circle. Basically I want to restrict circle to be drawn in it's parent shape which could be either polygon/rectangle/circle.

Could you please let me know, how can I check this?

Thanks in advance.

Best Regards,
Balram

**Comment by antoniolocandro** [comment]
I asked this question before maybe this would help? 

`if(turf.area(turf.intersect(poly1, poly2)) - turf.area(poly1) < verySmallNumber)` << to deal with float issues

**Comment by morganherlocker** [comment]
@antoniolocandro's answer is what I would go with as well @ultrasonicsoft. Hope that helps!
