### ISSUE TITLE
new module: fix kinks

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#320]
> Add an automagically fixed poly collection to the results object. This is pretty subjective, so it should be noted to only use this for low-risk tasks. Tasks where correct data is important should be handled more robustly, or even manually.

https://github.com/Turfjs/turf-kinks/issues/1

**Comment by tcql** [comment]
cc @mourner we've discussed the need for fixing in some algorithms like clipping, also would be necessary if/when [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) happens

**Comment by tmcw** [comment]
Merging into previous issue #87
