### ISSUE TITLE
tape -> tap, set minimum coverage

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#328]

**Comment by tmcw** [comment]
Going to stay with tape for 3.x, only switch to tap once we figure some other details out.

**Comment by DenisCarriere** [comment]
@tmcw Looking to hear your feedback, `tap` seems like a good solution for Turf.
Can I ask what those details to figure out were?

https://github.com/Turfjs/turf/pull/713

**Comment by DenisCarriere** [comment]
Just found out that `tap` seamlessly integrates with `coveralls.io` without any additional configurations or changes in the `package.json`.

http://www.node-tap.org/cli/

> If a COVERALLS_REPO_TOKEN environment variable is set, then coverage is captured by default and sent to the coveralls.io service.

**package.json** - no change (other than `node test.js` => `tap test.js`)
```json
  "scripts": {
    "test": "tap test.js",
    "bench": "node bench.js"
  },
```

**test.js** - only require changes (NodeJS >=6)

```javascript
const {test} = require('tap');
```

**Comment by DenisCarriere** [comment]
Woot! It works! level of effort **Zero**!

![image](https://cloud.githubusercontent.com/assets/550895/26460657/538ef9b6-4148-11e7-8948-dc3c677ae271.png)

**Comment by DenisCarriere** [comment]
Added tap as main testing suite, using `tap` in each repo is optional, both `tape` or `tap` works.
