### ISSUE TITLE
Inverse Distance Weight (IDW) Interpolation

### ISSUE THREAD

**Issue by alperdincer** [Turfjs/turf#329]
Is it possible to add IDW to TurfJS? This is most common scientific interpolation method for points to raster conversion.

**Comment by miccferr** [comment]
Hi there,

I've implemented a version of IDW (see #366).
It's not optimised by any means, but it's a starting point.

**Comment by JoranBeaufort** [comment]
If it is of any interest: I have created a small leaflet plugin for IDW based on the leaflet-heatmap plugin. It also is not optimised in any way, but may provide some further insight: https://github.com/JoranBeaufort/Leaflet.idw

**Comment by miccferr** [comment]
@JoranBeaufort awesome! nice idea to build it extending the heatmap plugin.
I was tinkering with WebGL to achieve something similar but this is way more straightforward.

**Comment by JoranBeaufort** [comment]
@miccferr Thanks! I have no experience with WebGL yet, so i cant really comment, but would webGL also speed up the calculations? Or will it just outsource the rendering from the cpu to the gpu? My implementation reaches its limits quite fast depending on number of points and cell size.

**Comment by miccferr** [comment]
Yeah I was merely aiming at rendering via WebGL.  Don't know/don't think it will speed up the calculation itself (but I'll gladly be proven wrong).
Mine also maxes out quite soon btw. 
Would love to see more spatial stats in Turf though!

**Comment by rowanwins** [comment]
[turf.idw](http://turfjs.org/docs/#idw) now exists as a module and is in the docs. Thanks for the work @miccferr !

**Comment by JoranBeaufort** [comment]
Great! Thx @miccferr 😃👍
