### ISSUE TITLE
centroid vs mean centre

### ISSUE THREAD

**Issue by jamaps** [Turfjs/turf#334]
Greetings turf people,

I think turf's centroid method doesn't actually calculate the true centroid of a polygon.   It seems to calculate the mean of all the vertices of a polygon rather than the mean of all the points that fall within the polygon.  Thus, if there are lots of vertices on one side of the shape, it pulls the centroid point towards that edge.

Centroid calculated by turf:
![image](https://cloud.githubusercontent.com/assets/11054490/13865781/76553dca-ec85-11e5-803a-dda34ab664c2.png)

Centroid calculated in QGIS (using "polygon centroids" under geometry tools)
![image](https://cloud.githubusercontent.com/assets/11054490/13865773/625565ac-ec85-11e5-942d-296383e36e92.png)

I think what turf is calculating is actually the mean centre, which can be quite useful for cluster analysis, but it's not the same as the centroid of a polygon. (https://www.wikiwand.com/en/Centroid)

Maybe this is just semantics, but I found the output of turf's centroid function confusing as I expected one result and received another.

All the best,

**Comment by antoniolocandro** [comment]
Just checking this myself and was about to ask the same question, the doc says " calculates the centroid using the arithmetic mean of all vertices" which is what the function is doing, qgis I believe is calculating the weighted mean. Have you tried postgis but apparently it would give the same answer as turf for centroid. I think adding the weighted option as a switch/parameter would be nice instead of having to add the module https://github.com/Turfjs/turf-weighted-centroid maybe check with that module see if its similar to Qgis

**Comment by morganherlocker** [comment]
The turf-weighted-centroid module implements an algorithm that weights the centroid of a collection of features by some external heuristic (ie: population, median income, etc.).

> I think what turf is calculating is actually the mean centre, which can be quite useful for cluster analysis, but it's not the same as the centroid of a polygon. 

There are *many* different centroid algorithms that are used in different analysis contexts. I would be open to a module that implements the desired behavior here, provided a generic, concrete algorithm to follow (the same goes for other types of centroid algorithms). I'm going to close this ticket, but feel free to open another one with a reference to a specific algorithm that is needed.

**Comment by kachkaev** [comment]
Same issue here - can't figure out how to achieve QGIS-like centroids with Turf. [`turf-weighted-centroid`](https://github.com/Turfjs/turf-weighted-centroid) seems to be solving a different problem.

Have you found the solution @jamaps?

**Comment by morganherlocker** [comment]
@kachkaev I would give @mourner's new Polylabel module a spin.

- [blog post](https://www.mapbox.com/blog/polygon-center/)
- [source code](https://github.com/mapbox/polylabel)

Polylabel implements a fast centroid algorithm (modified [pole of inaccessibility](https://sites.google.com/site/polesofinaccessibility/)) aimed at *visual rendering* (unlike any of the turf centroid algorithms, which have different design goals).
