### ISSUE TITLE
GeoJSON fixtures should be a dev dependency

### ISSUE THREAD

**Issue by dmfenton** [Turfjs/turf#337]
https://github.com/Turfjs/turf/blob/master/packages/turf-centroid/package.json#L30

I think this is adding about 11MB of extra weight onto the Turf-Centroid package. Doesn't effect browser builds but it does make server builds bigger.

**Comment by tmcw** [comment]
Already ticketed at https://github.com/mapbox/geojson-fixtures/issues/2

**Comment by dmfenton** [comment]
Thanks Tom. That will help, but it's not quite the same. Even if you remove idaho from geojson fixtures, you're still adding extra weight onto this package by including a testing module in the dependencies.

**Comment by tmcw** [comment]
Ah, this should be in devDependencies.

**Comment by dmfenton** [comment]
:+1: Thank you!

**Comment by Turbo87** [comment]
@tmcw is there a reason for b89cfa7 never being merged into master?
