### ISSUE TITLE
possible website bug: turf-difference

### ISSUE THREAD

**Issue by mollymerp** [Turfjs/turf#338]
I'm getting an error when I visit the [turf-difference](http://turfjs.org/static/docs/module-turf_difference.html) documentation
![screen shot 2016-03-25 at 12 19 10 pm](https://cloud.githubusercontent.com/assets/2425307/14051992/0730acf4-f284-11e5-9071-89c96646b3e5.png)

**Comment by tmcw** [comment]
Please search for existing issues: https://github.com/Turfjs/turf/issues/291
