### ISSUE TITLE
turf-buffer breaks turfjs builder

### ISSUE THREAD

**Issue by monkeytroy** [Turfjs/turf#339]
Using the turfjs-builder app to generate a custom client that includes turf-buffer returns application error page. 

https://turfjs-builder.herokuapp.com/

**Comment by rowanwins** [comment]
Gday @monkeytroy ,

The turf builder is an app built by me that isn't maintained by the turf team. 

Having said that I've just tested a build using turf-buffer and it worked fine for me. Can you post a screenshot of what you get?

Cheers
Rowan

**Comment by krem06** [comment]
Hi there,

I'm also getting an error, I tried to include buffer, distance, concave and convex modules

![screen shot 2016-04-26 at 11 00 51](https://cloud.githubusercontent.com/assets/1758990/14812615/30250500-0b9e-11e6-8542-f9edef190ab3.png)

Best regards,
Clem

**Comment by rowanwins** [comment]
Hi @monkeytroy & @krem06 

I've updated Turf Builder to use Turf v3 and it appears to be working now.

Let me know if you encounter any further issues but please do so over at the turf biulder repo - https://github.com/rowanwins/turf-builder

Cheers
Rowan

cc @tcql - you can close this issue too :)
