### ISSUE TITLE
Integrate turf with openstreetmap

### ISSUE THREAD

**Issue by baditaflorin** [Turfjs/turf#340]
I would like to create in such a way that i will get my data from OSM, and then i use turf to filter that data. Do you have a idea how i cauld do this ?

**Comment by tmcw** [comment]
Sure, you could use [any of the many ways of getting data out of openstreetmap](https://github.com/tmcw/mapmakers-cheatsheet#openstreetmap), convert to GeoJSON using something like osmium or osm2geojson, and then use turf.
