### ISSUE TITLE
How buffer method works?

### ISSUE THREAD

**Issue by malcommac** [Turfjs/turf#342]
Hi,
I have a GEOJSON polygon specified by pair of coordinates.
You can see it here:
http://www.darrinward.com/lat-long/?id=1865944
![Map1](http://i.imgur.com/B8AG8ka.png "Map1")

I've tried to enlarge it by using buffer method:
That's the code:
`var expandedPolygon = m_turf.buffer(boundingBox, 10, 'kilometers');`

While this is my source JSON (`boundingBox`):
```
{
  "type": "Polygon",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          12.2344266,
          41.6558738
        ],
        [
          12.2344266,
          42.140959
        ],
        [
          12.8558641,
          42.140959
        ],
        [
          12.8558641,
          41.6558738
        ],
        [
          12.2344266,
          41.6558738
        ]
      ]
    ]
  }
}
```
The result is this:
http://www.darrinward.com/lat-long/?id=1865948
![Map1](http://i.imgur.com/qa4Fo2D.jpg "Map1")

Is there something wrong?
Resulting area seems bigger than 10km (in each direction) and contains 37 different points (from 4) in such strange positions.
Am I missing something?

**Comment by tmcw** [comment]
> Resulting area seems bigger than 10km (in each direction) 

Please confirm this.

> contains 37 different points (from 4) in such strange positions.

The buffer of a square is a rounded square: at each corner, the furthest point from the edge is a semi-circle. This matches the behavior of all other geospatial buffer algorithms, as well as buffering in image processing software. If you want instead a 'make this bigger' algorithm, https://github.com/turf-junkyard/turf-size is the answer.
