### ISSUE TITLE
How to determine a orthogonal line

### ISSUE THREAD

**Issue by thipages** [Turfjs/turf#343]
Hi,

I have two geo points P1,P2 and I want to determine a point P3 which belong to an orthogonal line of the first point.
The way I do it
1. I determine the bearing of the two geo points P1, P2
2. I use turf.destination for finding P3 with the following arguments
- firstPoint P1
- the distance between P1 and P3
- "an orthogonal bearing"

Here is the issue I tried bearing-45 but it seems to be something like bearing -150

Can you help me?
Thank you

**Comment by tmcw** [comment]
On a map in equirectangular projection, the orthogonal line will either be + or - 90° from the straight line. If you're using another map projection, an orthogonal line can be at nearly any angle from the original line.
