### ISSUE TITLE
point-on-line results are distorted

### ISSUE THREAD

**Issue by mourner** [Turfjs/turf#344]
The `point-on-line` module doesn't return correct results. Take a look at the official example with a connection line added:

![image](https://cloud.githubusercontent.com/assets/25395/14594708/ad0213dc-0541-11e6-8693-57e7d0923c77.png)

As you can see, the line isn't perpendicular, so the snapped point isn't actually the closest one. This happens because the `lineIntersects` routine that's used to calculate the intersection point between a line segment and a line perpendicular to it from the point does the calculation on latitude/longitude values as if they were cartesian coordinates, while they are not — at a local scale, the ratio between latitude and longitude deltas is approximately `cos(latitude)`, not `1`. 

On higher latitudes, the distortion will be more pronounced. Here's how the same example looks on latitude ~78:

![image](https://cloud.githubusercontent.com/assets/25395/14594849/f5c5f9b6-0542-11e6-8679-3464b7fadacc.png)

cc @morganherlocker @tmcw @tcql

**Comment by DenisCarriere** [comment]
@mourner Would refactoring [`@turf/point-on-line` lineIntersects()](https://github.com/Turfjs/turf/blob/master/packages/turf-point-on-line/index.js#L116-L159) with [`@turf/line-intersect`](https://github.com/Turfjs/turf/tree/master/packages/turf-line-intersect) solve this issue?

**Comment by rowanwins** [comment]
Gday @DenisCarriere & @mourner 

It looks like replacing the `lineIntersects` function with `@turf/line-intersect` will address the issue. The screenshot below is taken at 80degs latitude.

![Repalced](https://www.dropbox.com/s/9u7tjiali56t5um/at80degs.jpeg?dl=1).

Will tidy up the rejigged code and will put in a pull request

**Comment by DenisCarriere** [comment]
👍 Good catch, `@turf/line-intersect` does sound like it would fix this issue (with some "rejigging").

**Comment by DenisCarriere** [comment]
👍 Looks like this got fixed in https://github.com/Turfjs/turf/issues/689.

Added a test case for it: [`test/in/line-northern-latitude-#344.geojson`](https://github.com/Turfjs/turf/blob/86d9ed14a456cbd585b4b89bf213687a3716c19b/packages/turf-point-on-line/test/in/line-northern-latitude-%23344.geojson)

![image](https://cloud.githubusercontent.com/assets/550895/25388771/b41f49ca-299c-11e7-85f8-70504efe3a97.png)
