### ISSUE TITLE
Support for more fundamental units

### ISSUE THREAD

**Issue by lgreenlee** [Turfjs/turf#345]
Currently functions such as distance and along allow values to be returned for miles and kilometers. It would be nice if the library also supported more "basic" units such as inches, yards and meters, centimeters. Also another major unit in use for aviation and maritime applications is the nautical mile. The new units should also feature the global standards for abbreviations instead of 'miles' which is ambiguous.

**Comment by trevorpburke** [comment]
I took a look at the turf-distance index.js file and used the existing function that includes miles and kilometers and converted it to yards, inches, and meters. I'm not sure if I'm correct, but I thought I'd just throw the code out there. 

`module.exports = function (point1, point2, units) {
    var coordinates1 = getCoord(point1);
    var coordinates2 = getCoord(point2);
    var dLat = toRad(coordinates2[1] - coordinates1[1]);
    var dLon = toRad(coordinates2[0] - coordinates1[0]);
    var lat1 = toRad(coordinates1[1]);
    var lat2 = toRad(coordinates2[1]);

    var a = Math.pow(Math.sin(dLat / 2), 2) +
          Math.pow(Math.sin(dLon / 2), 2) * Math.cos(lat1) * Math.cos(lat2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

    switch (units) {
    case 'miles':
        return c * 3960;
    case 'kilometers':
    case 'kilometres':
        return c * 6373;
    case 'degrees':
        return c * 57.2957795;
    case 'radians':
        return c;
    case 'inches':
        return c * 250905600;
    case 'yards':
        return c * 6969600
    case 'meters':
    case 'metres':
        return c * 637300;
    case undefined:
        return c * 6373;
    default:
        throw new Error('unknown option given to "units"');
    }
};
`

**Comment by tmcw** [comment]
Basic additions in https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js#L269 - open a PR for any additional units you want.

**Comment by trevorpburke** [comment]
@tmcw This makes more sense. Nice job. I'll add [these](https://en.wikipedia.org/wiki/List_of_unusual_units_of_measurement#Length) in my next pull request. You'll never know if someone needs Siriometers for their GIS project

**Comment by lgreenlee** [comment]
Thank you! This was very helpful.
