### ISSUE TITLE
Combine binaries

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#364]

**Comment by morganherlocker** [comment]
What does this mean?

**Comment by tmcw** [comment]
The idea is that many of the turf libraries had binaries that would include minimist and provide a turf-buffer cli, for instance. This meant that a lot of low-level libraries needed cli dependencies and there was a bunch of code duplication.

I think it'd be useful to have a single turf cli module that allows something like `turf buffer file.json` or `turf hexGrid 10 20` and so on. If that was useful and someone had the time to do it.

The first part of this ticket is complete - I'll retitle it to match

**Comment by tmcw** [comment]
We've removed binaries. Holding off on a unified binary for now.
