### ISSUE TITLE
hex-grid scaling factor for higher / lower lattitudes

### ISSUE THREAD

**Issue by kayakwest** [Turfjs/turf#367]
![image](https://cloud.githubusercontent.com/assets/558172/14904190/b95edc1c-0d63-11e6-8216-66ce25232df4.png)

When creating hex-bins in wgs84 they visually stretch as we go north (when displayed in a web-mercator mapping tool).

Since Hexbins are often used as a visual tool it would be nice to adjust them so they look proportional for the study area.  The same might be true for the other grid generating tools.

Is there appetite for this?  If so we might be able to help.  Alt... am I doing it wrong?

**Comment by geraldstanje** [comment]
Hi,
could you show how you render your grid and color each cell? is there a way to render the grid with WebGL?

I currently use the following to create my grid:
http://jsfiddle.net/ts4oyyn0/10/

Thanks.

**Comment by boriscosic** [comment]
@geraldstanje I've forked your example and replaced the bounding box and center with northern coordinates, http://jsfiddle.net/s8f4ks9m/. Same issue.

**Comment by geraldstanje** [comment]
@boriscosic look here: http://jsfiddle.net/s8f4ks9m/1/

**Comment by stebogit** [comment]
Using the latest version of Turf (currently v4.4) the hexagons are not distorted:
http://jsfiddle.net/jStefano/zpn4ssfs/

![screen shot 2017-06-22 at 8 36 16 am](https://user-images.githubusercontent.com/12717225/27442937-7e1ec046-5726-11e7-9c7f-260b2187e750.png)
 
cc: @DenisCarriere

**Comment by DenisCarriere** [comment]
👍 Agreed, doesn't seem to be distorted anymore (even in high latitudes).
