### ISSUE TITLE
Implement parallel_offset

### ISSUE THREAD

**Issue by danvk** [Turfjs/turf#368]
Turf has a [buffer method](http://turfjs.org/static/docs/module-turf_buffer.html). It would be great if it had a [parallel_offset method](http://toblerity.org/shapely/manual.html#object.parallel_offset) as well, ala shapely.

cc @nrathi

**Comment by danvk** [comment]
This might be as simple as calling [`setSingleSided`][1] on a `BufferParameters` object.

[1]: http://bjornharrtell.github.io/jsts/1.1.1/apidocs/org/locationtech/jts/operation/buffer/BufferParameters.html#setSingleSided-boolean-

**Comment by clhenrick** [comment]
Related recent question on gis.stackexchange: http://gis.stackexchange.com/questions/85358/how-to-add-an-offset-to-a-geojson-layer-in-leaflet/

**Comment by rowanwins** [comment]
I needed this so I've made v1 - just finalising a few tests etc but should have a pull request soon!

**Comment by DenisCarriere** [comment]
👍 Sweet! That's awesome

**Comment by DenisCarriere** [comment]
Implemented in PR https://github.com/Turfjs/turf/issues/729.

Will be available in the next minor release `v4.4.0`
