### ISSUE TITLE
Duplicated functions pointOnLine and lineIntersects

### ISSUE THREAD

**Issue by zugaldia** [Turfjs/turf#370]
I'm seeing implementations for `pointOnLine` and `lineIntersects` in both [`turf-line-slice`](https://github.com/Turfjs/turf/blob/master/packages/turf-line-slice/index.js) and [`turf-point-on-line`](https://github.com/Turfjs/turf/blob/master/packages/turf-point-on-line/index.js). The code is fairly similar but not identical.

Not sure if there's a good reason for this. Ticketing in case the code in `turf-line-slice` needs to be removed and use the one from `turf-point-on-line` instead.

**Comment by tmcw** [comment]
As of https://github.com/Turfjs/turf/commit/636b34b4d4f90053ae5609171d9520820f179619 turf-line-slice uses turf-point-on-line.

**Comment by zugaldia** [comment]
@tmcw Thanks for clarifying.
