### ISSUE TITLE
new modules

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#374]
Gday,

Nice work on the refactor turf team! I need to have a good luck at the workings to see how you're managing it all.

I have a couple of potential modules which I worked on a while ago which I think could be beneficial within turf
- [nearest point to line](https://github.com/rowanwins/turf-nearestPointToLine) which identifies the point from a collection that is nearest to an input line
- [completely within ](https://github.com/rowanwins/turf-completelyWithin) which identifies polygons from a collection which are within an input polygon
- [overlaps](https://github.com/rowanwins/turf-overlap) which returns a featurecollection of features which overlap with an input feacturecollection
- [dissolve](https://github.com/rowanwins/turf-dissolve) which dissolves an input set of polys based on an attribute

All of them need doco and tests but if there is some interest is seeing them added I'm happy to work towards getting them in there.

Cheers
Rowan

**Comment by DenisCarriere** [comment]
@rowanwins I would recommend you try implementing a `dissolve` module, that would be very much needed. Every time I need need to dissolve polygons by geometry or by attributes I need to go to QGIS for this.

👍 Open another Issue for just that one module or send a PR.

**Comment by rowanwins** [comment]
Gday @DenisCarriere funny you should mention that, I took another look at my old dissolve code yesterday and started refactoring it. It's working on small datasets fine but on larger ones I seem to be running into some issues, the logic is proving to be quite complicated at the moment, might need another pair of eyes.

**Comment by DenisCarriere** [comment]
I bet it's pretty complicated, is the process running out of memory? Well at least you've got a small dataset working, only improvements can happen from that point on.
