### ISSUE TITLE
Cannot find module 'turf-collect'

### ISSUE THREAD

**Issue by Turbo87** [Turfjs/turf#375]
It looks like `turf-collect` is missing from https://github.com/Turfjs/turf/blob/master/packages/turf/package.json

**Comment by Turbo87** [comment]
but I just noticed that `turf-collect` isn't published on NPM, so maybe https://github.com/Turfjs/turf/blob/master/packages/turf/index.js#L16 is actually wrong?

**Comment by tmcw** [comment]
Yep, package name in turf-collect hadn't been updated. Just published a fix.

**Comment by wprater** [comment]
having a similar issue with `turf-distance` running on Node 8.  any more input I can provide to help determine the cause?

**Comment by DenisCarriere** [comment]
@wprater not getting any errors using Node 8, can you provide a code snippet of what's not working.

**Example (is working)**

```javascript
const turf = require('@turf/turf');
turf.distance([0, 0], [1,1])
//= 157.2987453847275
```

**Comment by wprater** [comment]
I installed turf like such

`yarn add turf`

then tried to load the distance module like so:
`const turfDistance = require('@turf/distance');`

```
Error: Cannot find module '@turf/distance'
    at Function.Module._resolveFilename (module.js:485:15)
[...]
```
using `"turf": "^3.0.14"

**Comment by DenisCarriere** [comment]
Yes Turf is now namespaced `@turf/turf` for the recent releases.
