### ISSUE TITLE
Turf builder Heroku error

### ISSUE THREAD

**Issue by hrishiballal** [Turfjs/turf#378]
When I try to build a custom file with the following options, it is giving a application error in download. 
Selected options: 
![screen shot 2016-05-18 at 17 09 34](https://cloud.githubusercontent.com/assets/1588744/15366260/64b0e738-1d1b-11e6-9018-f4bfafceb145.png)

Error: 
![screen shot 2016-05-18 at 17 10 05](https://cloud.githubusercontent.com/assets/1588744/15366263/67fddbe4-1d1b-11e6-8d75-34d16c365c85.png)

**Comment by tcql** [comment]
This isn't actually hosted by turf, it's https://github.com/rowanwins/turf-builder

I've opened an issue over there https://github.com/rowanwins/turf-builder/issues/5

cc @rowanwins

**Comment by rowanwins** [comment]
Hi @hrishiballal 

I've updated Turf Builder to use Turf v3 and it appears to be working now.

Let me know if you encounter any further issues but as @tcql suggests please do so over at the turf biulder repo - https://github.com/rowanwins/turf-builder

Cheers
Rowan
