### ISSUE TITLE
Update turf.min.js in docs, turfjs.org and npmjs.com to 3.0.5 

### ISSUE THREAD

**Issue by kristfal** [Turfjs/turf#379]
Hey,

[Installation documentation](https://github.com/Turfjs/turf#installation) for this repo still point to:

`https://raw.githubusercontent.com/Turfjs/turf/v2.0.2/turf.min.js`

additionally outdated versions are linked at:

`https://www.npmjs.com/package/turf`
`http://turfjs.org/`

**Comment by DavidHequet** [comment]
while we wait for turf.min.js, how do you build it?

**Comment by orangemug** [comment]
@DavidHequet you can use <https://wzrd.in> to build npm packages using browserify. For example to get the latest version of turfjs just go to <https://wzrd.in/standalone/turf@latest>

**Comment by tmcw** [comment]
Finishing a new version publish once https://github.com/Turfjs/turf/pull/396 is completed

**Comment by tmcw** [comment]
All of the Installation docs now point to the right versions: https://github.com/Turfjs/turf#installation
