### ISSUE TITLE
Turf 3.0 features

### ISSUE THREAD

**Issue by hrishiballal** [Turfjs/turf#380]
I missed the threads about refactoring but it seems like Turf 3.0 does not have all the functions present in 2.0 (and in the documentation) e.g. turf.erase 

Am I correct? I am assuming that there is a plan to migrate these features over time. 

Thanks again and keep up the good work!

**Comment by tmcw** [comment]
Hi @hrishiballal!

Yep, you're right that 3.x does remove some modules, things that we decided weren't necessary in the core. The full list of removals, as well as instructions on how to replace removed modules with smaller abstractions, is [in the changelog under 3.x](https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#301). In the case of turf-erase, that module was renamed turf-difference to bring it in line with traditional GIS naming of its functionality.

Hope that helps! Let me know if you have any other questions.

**Comment by hrishiballal** [comment]
Thanks for this, I am guessing for turf.extent should be turf.bbox.

**Comment by morganherlocker** [comment]
I noted the `extent=>bbox` name change in the [changelog's upgrade guide](https://github.com/Turfjs/turf/commit/3ead28bd9008ab766cefff2a682dbf7b1313062d). Thanks for flagging @hrishiballal!
