### ISSUE TITLE
Error in example in documentation

### ISSUE THREAD

**Issue by Edward17** [Turfjs/turf#382]
Hi!

First, excuse me if I write in wrong place.

I'm browsing documentation at http://turfjs.org/ and in page about [difference](http://turfjs.org/static/docs/module-turf_difference.html) function I see error in Example:
> TypeError: turf.difference is not a function

Screenschot:
![image](https://cloud.githubusercontent.com/assets/11292985/15613043/c77c9d86-2431-11e6-9599-71e1cc7772c2.png)

It happens in Google Chrome 50.0.2661.102 m and Opera Developer 39.0 at Windows 7. In IE I don't see the error message, but I also don't see maps below the code.

**Comment by tmcw** [comment]
Hi Eduard!

Thanks for posting this issue! It's a valid concern, and we're already
tracking it in a previous issue, #291. I'm going to close your issue
now to keep the discussion in one place. If you have any further input
on the main issue, please post it there.

Thanks!

**Comment by Edward17** [comment]
Wow. Sorry. I scrolled a bit down to search similar issues but haven't found anything, so I posted this issue. But I haven't used search...

Thanks for quick reaction!
