### ISSUE TITLE
Buffer

### ISSUE THREAD

**Issue by flightsurvey** [Turfjs/turf#387]
I have implemented turf.buffer around a polygon with a distance of 50 metres and the polygon returned  varies in size between 30 - 50 metres approx greater than the original.

![buffer](https://cloud.githubusercontent.com/assets/13222323/15684246/24910f82-275e-11e6-9d20-1f9a29126725.png)

**Comment by morganherlocker** [comment]
This is because buffer operations are non-geodesic. The current implementation is only capable of flat-plane buffers. It is a [known limitation](https://github.com/Turfjs/turf-buffer/issues/7) I would love to fix when I have the time, but it is a significant algorithmic lift.
