### ISSUE TITLE
add all helpers to turf.* ?

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#393]
@tmcw We currently give access to some of the [turf feature geometry functions](https://github.com/Turfjs/turf/blob/master/packages/turf/index.js#L56-L61). Should we expose the rest of the turf-helper functions (or am I missing something and they are already exposed somewhere)?

**Comment by tcql** [comment]
Any thoughts on `turf.helpers = require('turf-helpers');` instead of manually mapping?

**Comment by morganherlocker** [comment]
@tcql I am 👎 on having multi-level namespacing, especially for the most commonly used functions like these. I think it adds mental overhead at the API level without much benefit (maybe exacerbated because "helpers" is not a self-describing namespace).

**Comment by tmcw** [comment]
Yeah, I can see benefits to both approaches but keeping the namespace flat introduces the least change. @morganherlocker want to PR a change exposing the rest of the methods?
