### ISSUE TITLE
turf.multipoint cannot be found

### ISSUE THREAD

**Issue by kochizufan** [Turfjs/turf#395]
Hi, I just started to use turf today.
Using in browser, with require.js shim.

In document, 
http://turfjs.org/docs/#multiPoint

> var multiPt = turf.multipoint([[0,0],[10,10]]);
> 
> //=multiPt

But browser shows

> Uncaught TypeError: Cannot read property 'multipoint' of undefined

turf.multipoint looks undefined.

Is this error? or, I forgot to do some initialize or so?

**Comment by tcql** [comment]
hi @kochizufan, we've got a pull request in to fix this : #394. Once this is merged and a new release is created, you should be able to switch to the newest version and have access to `turf.multiPoint`

**Comment by kochizufan** [comment]
Oh I'm sorry because of lack of knowledge I didn't realize #394 include this issue.
Thank you!

**Comment by tmcw** [comment]
Turf 3.0.12 is out and fixes this problem: all helpers are exposed.
