### ISSUE TITLE
How to make a patch

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#399]
The recommended publishing docs from [CONTRIBUTING.md](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#publishing) are a bit incomplete. Let's try to make a list of steps for publishing a patch.

Here's an incomplete starting point:
1. Make a PR with your changes (be sure to modify relevant jsdocs to reflect the change)
2. Merge PR after a code review from someone else in the Turfjs organization
3. decide which version increment to use (`major|minor|patch`) based on [semver rules](http://semver.org/#summary)
4. `lerna publish` (need details)
5. Add list of changes with the new version number to the top of CHANGELOG.md
6. generate new docs (need details)
7. publish docs (need details)
### ?s
- `lerna publish --canary` (suggested by our current docs) appears to be broken or deprecated by lerna (`"Too many arguments."`). 
- `lerna publish` asks for a VERSION file. It seems to default to `0.0.0`.
- `turf/package.json` has a version and `turf/packages/turf/package.json` has a version. Should we delete `turf/package.json` or modify it somehow?
- how are docs generated? how are they published?

cc @tmcw 

![](https://lesterandcharlie.files.wordpress.com/2012/02/im-just-a-bill.jpg)

**Comment by tmcw** [comment]
(quick notes, gotta run in a moment)

> lerna --publish

This is still documented on their official repo.

https://github.com/lerna/lerna#--canary--c

Lerna has been a little weird about perferring global to local installs. That might be part of the cause.

turf/package.json is where i've been managing global dependencies and global tests: see the [stragglers pr for instance](https://github.com/Turfjs/turf/pull/383) - we can use it to run assertions over all the package.jsons

> how are docs generated? how are they published?

in turf-www, by running `npm run docs` https://github.com/Turfjs/turf-www/blob/gh-pages/package.json - this is still imperfect and we still need a fancy template

**Comment by DenisCarriere** [comment]
I believe there's enough documentation on how to publish a new patch/minor release on [the official Lerna GitHub repo](https://github.com/lerna/lerna).
