### ISSUE TITLE
Uncaught TypeError: i.intersection is not a function

### ISSUE THREAD

**Issue by ingfdoaguirre** [Turfjs/turf#400]
Hi, I have this code, I´m trying to verify if one buffered point iintersects another buffered point, when I tyy the code i get this error on console 

> Uncaught TypeError: i.intersection is not a function

What I´m doing wrong if the buffered points are converted to polygons after applying the turf.buffer function?

Thank you

`var poly1 = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [-122.801742, 45.48565]
  }
};
var poly2 = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [-122.801742, 45.48565]
  }
};

var bufer = turf.buffer(poly2, 1, 'miles');
var bufer1 = turf.buffer(poly1, .5, 'miles');

var intersection = turf.intersect(bufer1, bufer);

console.log(intersection);`

**Comment by morganherlocker** [comment]
Which version of turf are you running? I copy/pasted your code exactly, ran `npm install turf`, and it ran without a hitch.

**Comment by tmcw** [comment]
Closing; turf is now at `@turf/turf` and this bug isn't present in the current version.

**Comment by stepankuzmin** [comment]
Hi there! It seems that `@turf/intersect` is still broken.

```shell
npm install @turf/turf
```

```js
var fs = require('fs');
var intersect = require('@turf/intersect');

var poly1 = JSON.parse(fs.readFileSync('test1.geojson'));
var poly2 = JSON.parse(fs.readFileSync('test2.geojson'));
var result = intersect(poly1, poly2);
console.log(JSON.stringify(result, null, 2));
```

```shell
/Users/stepan/tmp/node_modules/@turf/intersect/index.js:68
    var intersection = a.intersection(b);
                         ^

TypeError: a.intersection is not a function
    at intersect (/Users/stepan/tmp/node_modules/@turf/intersect/index.js:68:26)
    at Object.<anonymous> (/Users/stepan/tmp/test.js:8:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

@turf v3.5.2

**Comment by morganherlocker** [comment]
Hm, this may be an upstream bug in jsts. This code is straight from the docs, but maybe there was a deeper change somewhere else in the jsts API.

`var intersection = a.intersection(b)`

**Comment by DenisCarriere** [comment]
For any issues related to `@turf/intersect` submit a PR with a new GeoJSON Feature Collection with two polygons that should or should not intersect.

**Step 1:** Add polygon to [test/in](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect/test/in)

**Step 2:** Run tests `npm test`

**Step 3:** If an error occurs, submit PR with new GeoJSON causing the error.
