### ISSUE TITLE
npm turfjs organization

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#402]
https://docs.npmjs.com/orgs/what-are-orgs

Let's look into setting up an npm org so we can scale our permission management. My understanding is that npm orgs work pretty similarly to github orgs, which have worked well for us so far.

**Comment by tmcw** [comment]
I set up the new organization and:

* We can piece-by-piece grant people access to packages https://docs.npmjs.com/orgs/preexisting-packages#granting-team-access-to-a-package
* But the better way is to scope them. That would mean renaming packages like `turf-concave` to `@turf/concave` which imho is pretty cool anyway.
* orgs cost $7/user/month, which i'm fine with

Doing this with granting access feels hacky to me. Scoping packages means another version bump. Current mood is that that's fine. Thoughts?
