### ISSUE TITLE
Incorrect download link

### ISSUE THREAD

**Issue by ingfdoaguirre** [Turfjs/turf#403]
Hi.

I was wondering that the minifield turfjs file link takes you to

> https://raw.githubusercontent.com/Turfjs/turf/v2.0.2/turf.min.js

And the latest release is 3.0.5, can you please update the link to download 3.0.5 minifield? thank you in advance (I dont want to use npm) thank you.

**Comment by DavidHequet** [comment]
Hi,
this is a duplicate (with working answer) : [https://github.com/Turfjs/turf/issues/379](https://github.com/Turfjs/turf/issues/379)

**Comment by morganherlocker** [comment]
Closing as dupe
