### ISSUE TITLE
turf-concave not on the docs page

### ISSUE THREAD

**Issue by mourner** [Turfjs/turf#407]
For some reason, http://turfjs.org/docs/ doesn't have `concave` after recent docs changes, although I remember it being there earlier. @tmcw

**Comment by tmcw** [comment]
concave docs don't have an explicit or implicit name - https://github.com/Turfjs/turf/blob/master/packages/turf-concave/index.js#L84

this can be fixed by adding a `@name` tag to the docs or by naming the function `concave` - the latter is the prevailing pattern in Turf.

**Comment by tmcw** [comment]
First change in 0c940354e017338f000336332c6038835c59cf53

**Comment by tmcw** [comment]
Fixed in https://github.com/Turfjs/turf-www/commit/939797f313f958d627d37885464179afd431e283
