### ISSUE TITLE
krige

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#41]
kriging contours

**Comment by tchannel** [comment]
Has there been any progress / further thought on this? I'm interested in potentially using kriging

**Comment by morganherlocker** [comment]
@tchannel Totally want this, but my focus has been less on predictive algorithms and more on core geometry algorithms for a while. Happy to help with any PRs if you would like to contribute.

**Comment by tchannel** [comment]
Thanks for the feedback. I'll probably have some time this week, so maybe I'll take a look.

**Comment by loganpowell** [comment]
👍 for kriging

**Comment by DenisCarriere** [comment]
👍 Same here, however this doesn't seem like this will be implemented anytime soon unless someone helps out to get a first draft ready.

**Comment by njriordan** [comment]
👍

**Comment by morganherlocker** [comment]
I no longer plan to build this. When I first opened this issue way back in 2013, Turf was more focused on predictive raster statistics, but the API design ended up going in a different direction, for which kriging is not well suited. This makes more sense in a geospatial scijs ndarray style framework.
