### ISSUE TITLE
turf-area always equals zero

### ISSUE THREAD

**Issue by StefanoGitHub** [Turfjs/turf#413]
Hi,
why do I always get `0`, no matter what polygon I use?
```js
var points = [
  [10, 10], [10, 11], [11, 11], [12, 10], [10, 10]
];
var p = turf.polygon(points);
console.log('area: ', turf.area(p)); //logs: 'area:  0'
```
What am I doing wrong?
Thanks

**Comment by tcql** [comment]
Hi @StefanoGitHub, the issue here is that geojson polygons are an *array of rings* (first ring is outer, others are holes), so your points should actually be 
```js
var points = [
 [
   [10, 10], [10, 11], [11, 11], [12, 10], [10, 10]
 ]
];
```

**Comment by StefanoGitHub** [comment]
Thanks!
