### ISSUE TITLE
Cannot install turf as a dependency

### ISSUE THREAD

**Issue by BradEwing** [Turfjs/turf#414]
Cloning turf from its repo and running and installing locally works fine, but when trying to install it to my project as a dependency (whether locally or on Elastic Beanstalk), it fails to install. I have not had issues with installing turf before today.

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: turf-helpers@^3.0.7
npm ERR! Valid install targets:
npm ERR! 3.0.7-canary.ae89c8b3, 3.0.5, 3.0.1, 3.0.0-canary.7879bf6c, 3.0.0-canary.2f5f7167, 1.0.0
```

My apologies if this is an npm issue.

**Comment by BradEwing** [comment]
FWIW also getting a similar issue on [tonicdev](https://tonicdev.com/npm/turf)

**Comment by royhobbstn** [comment]
Same (similar) issue:
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "turf" "--save"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! No compatible version found: turf-circle@^3.0.7
npm ERR! Valid install targets:
npm ERR! 3.0.7-canary.ae89c8b3, 3.0.6, 3.0.5

**Comment by stepankuzmin** [comment]
Similar with 3.0.9

```shell
$ npm i turf@3.0.9

npm ERR! No compatible version found: turf-isolines@^3.0.7
npm ERR! Valid install targets:
npm ERR! 3.0.7-canary.ae89c8b3, 3.0.5, 3.0.1, 3.0.0-canary.7879bf6c, 3.0.0-canary.2f5f7167, 1.0.2, 1.0.1, 1.0.0, 0.1.1, 0.1.0, 0.0.3, 0.0.2, 0.0.1
```

node v5.11.1
npm  v3.8.6

**Comment by tmcw** [comment]
Try out Turf 3.0.10 - was running into a lerna issue, it should be fixed now

**Comment by stepankuzmin** [comment]
It works with 3.0.10! 🚀

**Comment by royhobbstn** [comment]
Yep, it works again.  Thanks for the quick turnaround!

**Comment by tmcw** [comment]
👍 thanks for confirming!
