### ISSUE TITLE
How to build a custom Turf? 

### ISSUE THREAD

**Issue by hrishiballal** [Turfjs/turf#416]
I am new to the node world. I know that with the migration to v3, the repository uses lerna to manage the individual packages within the repository. Can someone please help as to how a browser file  (using browserify ?) can be generated that has some modules but not all? The turf builder ui project has a error and I have submitted bugs on that repository. I wanted to know how to build via command line. Thanks!

**Comment by morganherlocker** [comment]
@hrishiballal For reference, check out how we build the browserify package here: https://github.com/Turfjs/turf/blob/master/packages/turf/package.json#L8

One way to do this would be to comment out the [export functions you don't need here](https://github.com/Turfjs/turf/blob/master/packages/turf/index.js), then run npm run build in `./turf/packages/turf`.

I would also take a look at the browserify docs, particularly the [`-s,--standalone` flag](https://github.com/substack/node-browserify#usage), which turf uses.

**Comment by domiSchenk** [comment]
I think the build is a little messed up right now.
There seems to be 2 errors:

**frist:** 
_Cannot find module 'turf-isolines' from 'C:\_dev\turf\packages\turf'_

Shouldn't the requires be like this require('../turf-isolines')?

and the **second**:
the module turf-grid is missing inside turf-isolines

or do i miss something?

**Comment by sylvainpolletvillard** [comment]
Have you seen this : https://github.com/rowanwins/turf-builder

**Comment by domiSchenk** [comment]
nope 
thanks @sylvainpolletvillard

**Comment by rowanwins** [comment]
Gday @domiSchenk ,

I also wrote up some documentation here for how to create custom builds manually
https://github.com/Turfjs/turf/issues/272

I haven't tested with turf 3 but it might be enough to get you started.

Cheers
Rowan

**Comment by rowanwins** [comment]
I think there is enough info here in this issue to get people on their way. I've also added some documentation to the official ['Getting Started'](http://turfjs.org/getting-started.html) docs page.
