### ISSUE TITLE
CDN for turf 3.0 + update turf on npm

### ISSUE THREAD

**Issue by lyzidiamond** [Turfjs/turf#421]
unless this is already done? cc @morganherlocker @tcql @tmcw

**Comment by lyzidiamond** [comment]
ref https://github.com/Turfjs/turf/issues/238#issuecomment-228572764

**Comment by tcql** [comment]
✋ I'm on it @lyzidiamond. New release is at https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js, I'll work on updating documentation

**Comment by tcql** [comment]
Website is updated per https://github.com/Turfjs/turf-www/pull/88

We'll still need to update the README here with the new CDN url and then it'll be updated on NPM next time we publish

**Comment by lyzidiamond** [comment]
Thanks @tcql! Super appreciated.

**Comment by codeofsumit** [comment]
Defenitely confused the heck out of me.

**Comment by blueonrails** [comment]
+1

**Comment by DenisCarriere** [comment]
Closing:

The most recent CDN is https://npmcdn.com/@turf/turf/turf.min.js
