### ISSUE TITLE
update collect function docs

### ISSUE THREAD

**Issue by moklick** [Turfjs/turf#424]
It seems that you replaced the `aggregate` function with the `collect` function. The docs are still the old ones. That is very confusing. I couldn't find a repo with the current docs. If you tell me where it is, I can make a PR there.

**Comment by tmcw** [comment]
Turf docs are generated from code comments - if you fix the [comment in the turf-collect module](https://github.com/Turfjs/turf/blob/master/packages/turf-collect/index.js#L3), we can update the generated documentation.

**Comment by tmcw** [comment]
Will be resolved by #425
