### ISSUE TITLE
turf-union throwing an unexpected error.

### ISSUE THREAD

**Issue by mcwhittemore** [Turfjs/turf#429]
`turf-uion` is throwing `[object Object]` when I make this request.

```js
turfUnion({"type":"Feature","properties":{"id":"d6c679524d8c921960f8605fb3680159","meta":"feature","meta:type":"Polygon","active":"true","mode":"draw_polygon"},"geometry":{"coordinates":[[[0,0],[15,15],[30,30],[0,0]]],"type":"Polygon"}}, {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[43,43],[47,43],[47,47],[43,47],[43,43]]]}});
```

I'm pretty sure the GeoJSON is valid: https://gist.github.com/mcwhittemore/9944bce82fce056a9f5b5fd364f6ff0d

But not being able to read the error message is making debugging this pretty hard.

**Comment by tmcw** [comment]
Can you use Pause on exceptions to narrow it down?

**Comment by mcwhittemore** [comment]
Yea, the exception coming from `jsts`.

The grabbed error message is `"found non-noded intersection between LINESTRING ( 0 0, 15 15 ) and LINESTRING ( 30 30, 0 0 ) [ (0, 0, undefined) ]"`

Per #412, it looks like is due to JSTS thinking this is self intersecting geometry. I'm assuming this is a precision problem in JSTS and will file upstream.
