### ISSUE TITLE
Turf.union throws OperationNotSupported

### ISSUE THREAD

**Issue by nikolauskrismer** [Turfjs/turf#437]
It seems that for some cases turf.union throws an OperationNotSupported exception from within JSTS.
I observed that behavior with @turf/union and I debugged it with version 3.3.3 a bit...
...but if I remember correctly I also saw it with 3.0.x and 3.1.x versions.

Although I tried to fix this issue, I do not have a clue whats going wrong here...
... for most of my polygons union work great, but obviously not with all of them.
The behavior can be seen with chrome 51, firefox 47.0 and phantomjs 1.9.8 (that's all I tested)
I simplified my test as much as possible, so that I can now provide some test data (which can be found in the [this zip file](https://github.com/Turfjs/turf/files/362401/testData.zip))

I hope that someone can help me in resolving this issue, since I am stuck with my old implementation based on jsclipper otherwise (and I really want to switch to turfjs :-))

**Comment by nikolauskrismer** [comment]
I just tried to build the union with turf-union@v1.0.2.   
Using the old version everything works as expected -> so there is at least _no_ non-noded intresection

**Comment by DenisCarriere** [comment]
For any issues related to `@turf/union` submit a PR with a new GeoJSON Feature Collection with two or more polygons that should or should not union.

**Step 1:** Add `FeatureCollection<Polygon>` to [test/in](https://github.com/Turfjs/turf/tree/master/packages/turf-union/test/in)

**Step 2:** Run tests `npm test`

**Step 3:** If an error occurs, submit PR with new GeoJSON causing the error.
