### ISSUE TITLE
kinks for a lineString

### ISSUE THREAD

**Issue by nickbroon** [Turfjs/turf#441]
It would be useful to also be able to determine the self-intersections of a lineString, but kinks currently only supports polygon.

**Comment by tmcw** [comment]
@nickbroon yep, that's be a useful change, for turf-kinks to support both. Want to try implementing this functionality? The relevant code is here: https://github.com/Turfjs/turf/blob/master/packages/turf-kinks/index.js#L47

**Comment by mclaeysb** [comment]
[This](https://github.com/mclaeysb/geojson-polygon-self-intersections) package could also help..

**Comment by dpmcmlxxvi** [comment]
Recommend closing with commit 3033364.
