### ISSUE TITLE
turf.min.js:16 Uncaught TypeError: o.intersection is not a function

### ISSUE THREAD

**Issue by ShenbagaRajanV** [Turfjs/turf#445]
[function calculateBuffer() {
    var fc1 = turf.featureCollection(fc1Layer.getLayers().map(function(f){
            return f.toGeoJSON()
        }));

```
var buffer = turf.buffer(fc1, 5, 'kilometers');
buffer.properties = {
    "fill": "#6BC65F",
    "stroke": "#25561F",
    "stroke-width": 2
};
bufferLayer.setGeoJSON(buffer);
```

   //var bufferGeojson=bufferLayer.setGeoJSON(buffer);
    var fc = turf.featureCollection(fcLayer.getLayers().map(function(g){
            return g.toGeoJSON()
        }));
     var buff = turf.featureCollection(bufferLayer.getLayers().map(function(h){
            return h.toGeoJSON()
        }));

```
var polygon = turf.intersect(fc, buff);
```

polygon.properties = {
    "fill": "#25561F",
    "stroke": "#25561F",
    "stroke-width": 10
};
intersectLayer.setGeoJSON(polygon);
}
Im running buffer and then intersection of the buffer to another polygon.
Im getting the above error o.intersection is not a function. Could any one help me on this?](url)

**Comment by clluiz** [comment]
Same problem here.

**Comment by joongtang** [comment]
Another problem here.

```
var poly = turf.bboxPolygon(map.getBounds().toBBoxString().split(','));
var bufferd = turf.buffer(poly, 10, 'kilometers');
```
Result is **Uncaught TypeError: O.isDigit is not a function(…)**
