### ISSUE TITLE
Easy way to download turf.js not minified

### ISSUE THREAD

**Issue by nboisteault** [Turfjs/turf#448]
Hi,
I'd like to debug my code but it creates an error in turf.min.js which obviously is hard to read.
It would be easier to have a turf.js not minified ready to download or via the CDN.
Thank you for this nice work.

**Comment by tmcw** [comment]
Hi Nicolas,

Sure, you can download a uncompressed version at https://npmcdn.com/@turf/turf@3.5.1/turf.js

**Comment by nboisteault** [comment]
Great! Thank you.

**Comment by marie15** [comment]
Thank you for this link help me too :)
