### ISSUE TITLE
Polygonize from linestrings

### ISSUE THREAD

**Issue by gagan-bansal** [Turfjs/turf#449]
What is the way to polygonize the lines. I have borders in the form of lines (intersecting) and want to create polygons with these lines. 
Is this correct forum for QnA or there is any other place also for Turf.js QnA?

**Comment by tmcw** [comment]
Hi Gagan,

There's no built-in Turf functionality for that problem. If the lines intersect precisely, you may want to write a bit of JavaScript to take their coordinates and place them verbatim in a coordinate ring of a GeoJSON Polygon object.

**Comment by gagan-bansal** [comment]
Thanks @tmcw for update. Right now I used PostGIS ST_Polygonize.

**Comment by maphew** [comment]
Polygonize added in #767
