### ISSUE TITLE
turf.circle not in minified js

### ISSUE THREAD

**Issue by joeyklee** [Turfjs/turf#456]
Hi there!

(first of all Turf.js is awesome! thanks so much for all the great work here)

Just noticed that `turf.circle()` is not in the [minified version of the lib](https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js)

perhaps it just needs an update?

Many thanks!

**Comment by tmcw** [comment]
Hi Joey,

That link is a bit outdated; the latest build is at https://npmcdn.com/@turf/turf@3.5.1/turf.min.js

**Comment by joeyklee** [comment]
Hi Tom,

Ah-ha! Right on. Thanks for that. I'll close this issue up. 👍
