### ISSUE TITLE
turf.filter is not a function

### ISSUE THREAD

**Issue by charliedotau** [Turfjs/turf#457]
Hi there,

I'm a bit confused as to whether the filter function is part of the Turfjs library or not?   There is an example here - http://turfjs.org/examples/turf-filter/ - that implies the filter function is part of the library but I have a feeling that's no longer accurate?

I'm getting a 'TypeError: turf.filter is not a function' regardless of whether I install the turf-filter package.  

Thanks
Charlie

**Comment by morganherlocker** [comment]
👋  Hey @charliedotau, turf-filter has been deprecated. Please refer to the latest docs here (the ones you linked to are >1 year out of date and not linked from turfjs.org) http://turfjs.org/docs/

If you want to replicate this functionality, I recommend using javascript's built in [Array.filter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter). For example:

```js
// psuedocode: fill this in with real data
var polys = // a featurecollection of polygons
var points = // a featurecollection of points

points.features = points.features.filter(function(point){
  polys.features.forEach(function(poly){
    // check if the point is in this polygon
    if(turf.inside(point, poly)) return true
  })
  // if the function makes it here, then the point wasnt in any of the polygons, and can be removed
  return false
})
```

If you are trying this with lots and lots of data, I recommend also adding a bbox collision check before running turf.inside, or using [rbush](https://github.com/mourner/rbush) for an rtree collision check, which will allow this to scale to very large datasets.

Hope that helps! Please reopen if you have more questions related to this one.

**Comment by tmcw** [comment]
^ That code example won't quite work, because a return in a `forEach` closure doesn't return from the containing function. You can instead do `return polys.features.some(function(poly){` with the same code and it should work
