### ISSUE TITLE
Uncaught TopologyException: found non-noded intersection between LINESTRING and LINESTRING

### ISSUE THREAD

**Issue by codeofsumit** [Turfjs/turf#463]
I'm getting this error when doing a lot of intersect and difference calls on two polygons.

```
Uncaught TopologyException: found non-noded intersection between LINESTRING ( -0.06986182563364439 51.51023450894928, -0.07004291534423829 51.51005341923869 ) and LINESTRING ( -0.07004291534423829 51.51010683860267, -0.06992667398091246 51.51016495928433 ) [ (-0.06993607661627625, 51.510160257966646, undefined) ]
```

![image](https://cloud.githubusercontent.com/assets/2399810/17927378/b3f551fe-69f5-11e6-97c9-5fea25892e7e.png)

Any ideas how I could prevent this or what I'm doing wrong?

**Comment by codeofsumit** [comment]
ok I think it's a self intersection. Seems like I have to disallow self-intersections as turf doesn't seem to support it.

**Comment by codeofsumit** [comment]
Turf definitely throws self-intersection errors even if there are no self intersection sometimes.

**Comment by rowanwins** [comment]
Sorry for the late reply but are you able to post a jsfiddle or something so that we can see the data you're working with? 

Thanks

**Comment by morganherlocker** [comment]
> Turf definitely throws self-intersection errors even if there are no self intersection sometimes.

I have not seen any cases where this has been true, but would love a test case.

**Comment by DenisCarriere** [comment]
For any issues related to `@turf/intersect` submit a PR with a new GeoJSON Feature Collection with two polygons that should or should not intersect.

**Step 1:** Add polygon to [test/in](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect/test/in)

**Step 2:** Run tests `npm test`

**Step 3:** If an error occurs, submit PR with new GeoJSON causing the error.

**Comment by 1994sunshine** [comment]
Maybe this answer will solve your problem（https://stackoverflow.com/questions/61926747/topologyexception-when-using-turf-intersect）。
Here's how I managed to make it work:

var options = {tolerance: 0.0001, highQuality: true};
poly = turf.cleanCoords(turf.simplify(poly, options));

I also checked for kinks, and divided the polygon if it returned true:

var kinks = turf.kinks(poly);
if (kinks.features.length){
  polys = turf.unkinkPolygon(poly);
...
