### ISSUE TITLE
Turf on nashorn engine.

### ISSUE THREAD

**Issue by lrodriguez2002cu** [Turfjs/turf#465]
Hi, my question is related to the possibility of using Turf on nashorn engine. I have done some tests, based on some examples,  and in principle, the browser version works. Nervertheless, I have found an  issue while iterating with the arrays. 

```
   load("http://api.tiles.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js");

    var arr = ['a b c', 'd e f'];

    print('length: ' + arr.length);
    for (var el in arr) {
        print(arr[el]);
    }

    print("end array printed foreach");
    for (var el = 0; el< arr.length; el++) {
        print("at index: "+ el + "-> " + arr[el]);
       
    }

    print("array printed for");

    return arr;

```

In this case the 'for in' prints:

length: 2
a b c
d e f
function(t){for(var e=Object(this),n=parseInt(e.length,10),i=arguments[1],r=parseInt(i,10)||0,s=0>r?Math.max(n+r,0):Math.min(r,n),o=arguments[2],a=void 0===o?n:parseInt(o,10)||0,u=0>a?Math.max(n+a,0):Math.min(a,n);u>s;s++)e[s]=t;return e}
end array printed foreach  

while IMHO, the expected behavior would be (as the in the second for block):
length: 2
a b c
d e f

Would be possible to use it on nashorn  or it is simply not compatible and thats the reason of this issue?

Thanks in advance.

**Comment by tmcw** [comment]
I'm very confused by this example: what does this code have to do with turf? You aren't calling any turf functions in the example.

**Comment by lrodriguez2002cu** [comment]
Wright, not using any Turf function in the example, but if the Turf is not loaded, the example works as expected. I didnt add any  Turf related functionality intentionally, not to add extra code. I do am using Turf in my working/testing code.

**Comment by tmcw** [comment]
Sorry, this is an upstream issue in jsts, and they have the opinion that `for in` loops are an antipattern: https://github.com/bjornharrtell/jsts/issues/239
