### ISSUE TITLE
turf-is-complex for identifying complex polygons

### ISSUE THREAD

**Issue by quadcopteryoga** [Turfjs/turf#492]
I'm happy to write this feature. Would it be accepted if I wrote a package to do this? Will provide test coverage as well.

Goal of the feature would be to determine if a polygon has any lines that self-intersect.

e.g.

```
     0
     |
0--------0
     |  /
     0
```

forgive my awful ascii art

Thanks # #

**Comment by rowanwins** [comment]
Gday @quadcopteryoga 
Thanks for the offer and sorry its taken a long while for anyone to respond.
Is the goal just to provide a boolean true or false back? [Turf Kinks](http://turfjs.org/docs/#kinks) already provides the actual self-intersections.

**Comment by quadcopteryoga** [comment]
@rowanwins Yeah the goal would be to validate that a polygon is not self-intersecting without having to run through all of the kinks.

I probably don't **really** need this as a feature, but it could speed some things up for me down the road
