### ISSUE TITLE
mask

### ISSUE THREAD

**Issue by andrewharvey** [Turfjs/turf#493]
Feature request for a mask function.

Given a geojson create the inverse/mask. Currently you need to manually create a polygon stretching the globe and do turf.difference for each polygon to get the mask.

**Comment by tmcw** [comment]
For simple, non-intersecting polygons, this can be a lot faster and easier than using turf.difference: take the WGS84 bounding rectangle and make it the outer ring of a polygon, and you get the correct result:

![invert](https://cloud.githubusercontent.com/assets/32314/19193207/351dcf6a-8c77-11e6-8f51-c73da7d72a1a.gif)

**Comment by andrewharvey** [comment]
@tmcw Thanks for that recommendation.
