### ISSUE TITLE
deprecation warnings still exist

### ISSUE THREAD

**Issue by contra** [Turfjs/turf#501]
Just letting you know, a fresh install of `@turf/turf` yields:

``` js
$ npm install @turf/turf
npm WARN deprecated turf-distance@3.0.12: Turf packages are now namespaced: please use @turf/distance instead
npm WARN deprecated turf-helpers@3.0.12: Turf packages are now namespaced: please use @turf/helpers instead
npm WARN deprecated turf-bearing@3.0.12: Turf packages are now namespaced: please use @turf/bearing instead
npm WARN deprecated turf-destination@3.0.12: Turf packages are now namespaced: please use @turf/destination instead
npm WARN deprecated turf-invariant@3.0.12: Turf packages are now namespaced: please use @turf/invariant instead
```

They all seem to be coming from one dep, `turf-line-slice-along`.

```
$ npm ls turf-helpers turf-distance turf-bearing turf-destination turf-invariant
staeco@0.0.1 /Users/contra/Projects/staeco
└─┬ @turf/turf@3.5.2
  └─┬ @turf/line-slice-along@3.5.2
    ├─┬ turf-bearing@3.0.12
    │ └── turf-invariant@3.0.12
    ├── turf-destination@3.0.12
    ├── turf-distance@3.0.12
    └── turf-helpers@3.0.12
```

Updating the package.json of that module should fix all of these errors and make installs clean.

**Comment by ath0mas** [comment]
I have a PR to come that deal with those deps to 3.0.x (except maybe turf-isolines dependency to turf-grid 1.0.1)

**Comment by contra** [comment]
@ath0mas Thanks!

**Comment by DenisCarriere** [comment]
Re-opening Issue: Still might have a few more warnings from @ath0mas comment.

> Fix #501 removing deps to v3.0.x modules
> Still have a dep to "turf-grid" in turf-isolines though (vs turf-point-grid 3.0.x / @turf/point-grid 3.5.x ?)

**Comment by morganherlocker** [comment]
The isolines warnings have been eliminated. Remaining warnings:

```
npm WARN deprecated turf-bearing@3.0.12: Turf packages are now namespaced: please use @turf/bearing instead
npm WARN deprecated turf-helpers@3.0.12: Turf packages are now namespaced: please use @turf/helpers instead
npm WARN deprecated turf-destination@3.0.12: Turf packages are now namespaced: please use @turf/destination instead
npm WARN deprecated turf-distance@3.0.12: Turf packages are now namespaced: please use @turf/distance instead
npm WARN deprecated turf-invariant@3.0.12: Turf packages are now namespaced: please use @turf/invariant instead
```

**Comment by gajus** [comment]
These warning are still present:

> npm WARN deprecated turf-bearing@3.0.12: Turf packages are now namespaced: please use @turf/bearing instead
> npm WARN deprecated turf-destination@3.0.12: Turf packages are now namespaced: please use @turf/destination instead
> npm WARN deprecated turf-distance@3.0.12: Turf packages are now namespaced: please use @turf/distance instead
> npm WARN deprecated turf-helpers@3.0.12: Turf packages are now namespaced: please use @turf/helpers instead
> npm WARN deprecated turf-invariant@3.0.12: Turf packages are now namespaced: please use @turf/invariant instead

**Comment by DenisCarriere** [comment]
This is fixed on the master branch, just need to release a patch or minor release and these will go away.

Close for now since this is fixed.

**Comment by tmcw** [comment]
I'll roll a release and add you to the npm owners group!

**Comment by tmcw** [comment]
3.5.3 published.

**Comment by gajus** [comment]
> I'll roll a release and add you to the npm owners group!

Instead of handling release manually, I highly recommend looking into https://github.com/semantic-release/semantic-release. It just saves so much time. As an example, I am using it here https://github.com/gajus/swing

**Comment by tmcw** [comment]
I'm afraid that'd be an abstraction on an abstraction: turf.js already uses lerna to organize its versions and sub-versions dependently. semantic-release looks quite nice, but doesn't look like it's geared for or tolerant of monorepos.

**Comment by gajus** [comment]
If you are feeling adventures, it is quite straightforward to implement a version of semantic-release using shell scripts, e.g. https://github.com/gajus/gitinfo/blob/master/.scripts/release.sh

**Comment by n1k0p0l** [comment]
Hi,

Apparently there are again deprecated "issues" with turf

```
npm WARN deprecated geojson-area@0.2.1: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
npm WARN deprecated geojson-normalize@0.0.0: This module is now under the @mapbox namespace: install @mapbox/geojson-normalize instead
```

```
$ npm ls geojson-area geojson-normalize
`-- @turf/turf@3.7.0
  +-- @turf/area@3.6.3
  | `-- geojson-area@0.2.1
  `-- @turf/buffer@3.7.0
    `-- geojson-normalize@0.0.0

```
mapbox changed it some week ago. Those are the only warning from a clean install. Latest 3.7.0 turf version

**Comment by privateOmega** [comment]
` npm install --save @turf/turf
npm WARN deprecated turf-area@3.0.12: Turf packages are now namespaced: please use @turf/area instead
npm WARN deprecated turf-helpers@3.0.12: Turf packages are now namespaced: please use @turf/helpers instead
npm WARN deprecated turf-within@3.0.12: Turf packages are now namespaced: please use @turf/within instead
npm WARN deprecated geojson-area@0.2.1: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
npm WARN deprecated turf-inside@3.0.12: Turf packages are now namespaced: please use @turf/inside instead
npm WARN deprecated turf-invariant@3.0.12: Turf packages are now namespaced: please use @turf/invariant instead
`

issue still persist on a fresh install of turf 3.14.1

**Comment by DenisCarriere** [comment]
@privateOmega I don't seem to get any deprecated warning messages using `npm` or `yarn`.

Also no messages are showing up in the [travis build](https://travis-ci.org/Turfjs/turf/builds/214203954).

Is anyone else getting warning messages?

**Comment by privateOmega** [comment]
@DenisCarriere  I was hoping someone could help me with this.
