### ISSUE TITLE
Is the library able to enlarge a polygon ?

### ISSUE THREAD

**Issue by cyrilchapon** [Turfjs/turf#507]
Hey.

This module looks great ! =)

However I'm trying to enlarge a GeoJSON polygon, and I can't figure out if the library is able to do this.

I also opened a [SO question](http://stackoverflow.com/questions/40381747/enlarge-a-geojson-polygon)

Thanks =)

**Comment by tmcw** [comment]
The function you're looking for is `buffer`, which is available as `turf.buffer` in this module. For your example, there will be a slight difference from the solution you propose: a mathematically enlarged polygon will have rounded sides rather than sharp.

**Comment by cyrilchapon** [comment]
Thanks @tmcw. I figured it out thanks to you. I'll use a combination of `buffer` and `simplify`.

Something like `turf.simplify(turf.buffer(polygon, '0.2', 'kilometers'), 0.005)` looks ok for my scale :)

**Comment by iamtekson** [comment]
Hey, thank you for your comment. But you are missing something in your answer. I think you have to replace your code `turf.simplify(turf.buffer(polygon, '0.2', 'kilometers'), 0.005)` with `turf.simplify(turf.buffer(polygon, '0.2', {units : 'kilometers'}), 0.005)`. Otherwise it will open an error [option must be an object](https://stackoverflow.com/questions/52626810/turf-buffer-leaflet-geojson-ajax).

**Comment by skol-pro** [comment]
Should now be replaced with `turf.simplify(turf.buffer(polygon, 0.2, {units : 'kilometers'}), { tolerance: 0.005 })`, same error (as mentionned by @iamtekson) occures otherwise.

**Comment by stebogit** [comment]
I'd throw also the more recent [`@turf/transform-scale`](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-scale) package for this task.
Although the scale factor is not expressed in units, one might be able to calculate it, something like this should work (not tested):
```js
const poly = turf.polygon([[[0,29],[3.5,29],[2.5,32],[0,29]]]);
const originalWidth = getWidthInKm(poly); // somehow define the dimension of interest
const factor = (originalWidth + 0.2) / originalWidth;
const larger = turf.transformScale(poly, factor);
```
