### ISSUE TITLE
Callback with index in propEach and featureEach

### ISSUE THREAD

**Issue by kkukielka** [Turfjs/turf#513]
Hi,

Can you add index into callback in `turf-meta` functions?

Now you have:
```js
function propEach(layer, callback) {
    var i;
    switch (layer.type) {
    case 'FeatureCollection':
        for (i = 0; i < layer.features.length; i++) {
            callback(layer.features[i].properties);
        }
        break;
    case 'Feature':
        callback(layer.properties);
        break;
    }
}
```

But you can change it to:

```js
function propEach(layer, callback) {
    var i;
    switch (layer.type) {
    case 'FeatureCollection':
        for (i = 0; i < layer.features.length; i++) {
            callback(layer.features[i].properties, i);
        }
        break;
    case 'Feature':
        callback(layer.properties, 0);
        break;
    }
}
```

So using this function would be really **similar** (as you said in doc) to `Array.forEach` :)

**Comment by DenisCarriere** [comment]
Other alternatives in ES6 would be using `map` `filter` `reduce` functions.

**Examples**
```javascript
// fc => GeoJSON.FeatureCollection
// Loop each feature within a FeatureCollection 
fc.features.map(feature => feature)

// Filter only features with a name property
fc.features = fc.features.filter(feature => feature.properties.name)
```

**Comment by tmcw** [comment]
I'm okay with this suggestion and will bring up a patch. For FeatureCollections, @DenisCarriere's suggestions work, but my intent in turf-meta is to ensure that implementations handle the valid case of the GeoJSON root object being something other than a FeatureCollection - something that I think not enough implementations do. And turf-meta's implementation is heavily optimized so people won't think twice to use it.
