### ISSUE TITLE
Buffer feet Invalid unit error

### ISSUE THREAD

**Issue by DinakaranS** [Turfjs/turf#519]
Using turf i am trying to get the buffer in older version, but in the latest version i am facing invalid unit error.

I am passing the point geometry, distance and feet as unit. While looking into the issue i found in turf-helper this issue is occurring here

```javascript
module.exports.distanceToDegrees = function (distance, units) {
    var factor = factors[units || 'kilometers'];
    if (factor === undefined) {
        throw new Error('Invalid unit');
    }
    return (distance / factor) * 57.2958;
}; 

In detail to that the factors has only 
var factors = {
    miles: 3960,
    nauticalmiles: 3441.145,
    degrees: 57.2957795,
    radians: 1,
    inches: 250905600,
    yards: 6969600,
    meters: 6373000,
    metres: 6373000,
    kilometers: 6373,
    kilometres: 6373
};
```

Here i don't see feet, how to fix this invalid unit error.

**Comment by DenisCarriere** [comment]
Based on an example found in [`cheap-ruler`](https://github.com/mapbox/cheap-ruler).
```javascript
var factors = cheapRuler.units = {
    kilometers: 1,
    miles: 1000 / 1609.344,
    nauticalmiles: 1000 / 1852,
    meters: 1000,
    metres: 1000,
    yards: 1000 / 0.9144,
    feet: 1000 / 0.3048,
    inches: 1000 / 0.0254
};
```
We could add the feet factor to `@turf/helpers`.
```javascript
var factors = {
    feet: 20908792.65
};
```
I don't think all of these distance calculations are mathematically accurate since you need to take into consideration the latitude degrees, but this can be used as a SWAG (Scientific wild-ass guess).

**Comment by DinakaranS** [comment]
Thanks Denis.

**Comment by DenisCarriere** [comment]
I submitted a PR for this, I'm going to re-open this issue until the PR gets merged/rejected.
