### ISSUE TITLE
Heavy distances calculation

### ISSUE THREAD

**Issue by inteliti** [Turfjs/turf#529]
Hi, i am working in my project calculating distances betwen points along line strings. But this calculation turn slow. I am talking about 30 or 50 point along a line string of 1000 or 2000 miles. Is there any best practice or function to improve this requirment?

Thanks

**Comment by DenisCarriere** [comment]
@inteliti For speed, you can try using [`cheap-ruler`](https://github.com/mapbox/cheap-ruler), the documentation is easy to follow and follows the same TurfJS syntax.

**cheap-ruler**
https://github.com/mapbox/cheap-ruler

In depth description of the library
https://www.mapbox.com/blog/cheap-ruler/

**Comment by rowanwins** [comment]
It might help to see a jsfiddle @inteliti so that we can see your code and better help. How slow are we talking?

**Comment by rowanwins** [comment]
Closing due to a lack of additional information.
