### ISSUE TITLE
Turf.js not rendering polygons

### ISSUE THREAD

**Issue by ahay-agile6** [Turfjs/turf#530]
Hi all,
I'm having trouble rendering polygons, lines, or anything of that nature on my Mapbox map using Turf.js.
I am using this set up:

<link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
<script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
<script src='https://api.mapbox.com/mapbox.js/plugins/turf/v2.0.2/turf.min.js'></script>

and trying to plop in some examples that are already made on the turf.js site, such as the polygon example:
http://turfjs.org/examples/turf-polygon/

L.mapbox.accessToken = <myaccesstoken>;

var polygon = turf.polygon([
    [
        [-97.42675781249999, 33.82023008524739], [-97.2125244140625, 33.89321737944089 ],
        [-97.086181640625, 33.706062655101206], [-96.94335937499999, 33.920571528675104],
        [-96.295166015625, 33.696922692957685], [-96.1029052734375, 33.83848275599514],
        [-95.7843017578125, 33.8521697014074], [-95.5810546875, 33.925129700072],
        [-95.3887939453125, 33.87041555094183], [-95.20751953125, 33.95247360616282],
        [-94.493408203125, 33.64663552343713], [-94.43161010742188, 35.39576704533903],
        [-94.61700439453125, 36.49418152677429], [-94.6142578125, 37.01132594307015],
        [-102.996826171875, 37.00693943418586], [-103.0078125, 36.49638952000399],
        [-100.008544921875, 36.48755716938579], [-100.008544921875, 34.57442951865274],
        [-99.931640625, 34.57442951865274], [-99.66796875, 34.36611072883117],
        [-99.591064453125, 34.3751788753353], [-99.5635986328125, 34.42503613021334],
        [-99.4097900390625, 34.36611072883117], [-99.39880371093749, 34.447688696497444],
        [-99.327392578125, 34.447688696497444], [-99.195556640625, 34.32529192442733],
        [-99.195556640625, 34.243594729697406], [-99.1461181640625, 34.21634468843465],
        [-98.96484375, 34.22088697429016], [-98.7451171875, 34.14363482031264],
        [-98.54187011718749, 34.13454168193739], [-98.514404296875, 34.07086232376631],
        [-98.349609375, 34.161818161230386], [-98.1024169921875, 34.13908837343849],
        [-98.118896484375, 33.99802726234877], [-97.9595947265625, 34.00713506435885],
        [-97.96508789062499, 33.87953701355924], [-97.767333984375, 33.897777013859475],
        [-97.646484375, 33.97980872872457], [-97.42675781249999, 33.82023008524739]
    ]
], {
    "fill": "#6BC65F",
    "stroke": "#6BC65F",
    "stroke-width": 5
});
var map = L.mapbox.map('map', 'morganherlocker.kgidd73k')
    .setView([35.463453, -97.514914], 6)
    .featureLayer.setGeoJSON(polygon);

I can render a point just fine, but rendering polygons does not fly.
Am I missing something?

**Comment by tmcw** [comment]
Given that the example is working, this is the code from the example, and your code isn't working, we'd need more information to debug this: what's different between the example and your code? Do you see errors in the console? Does the web inspector show SVG or canvas elements in the map? Have you include the required CSS for Mapbox.js?

**Comment by ahay-agile6** [comment]
After scouring through the interwebs, I found that the problem was occurring because I am using Angular. I didn't realize I need the leaflet-directive in order for the draw to work.
Thanks all :)
