### ISSUE TITLE
Lost in versions

### ISSUE THREAD

**Issue by kekscom** [Turfjs/turf#545]
Hi there,

I'm facing issues with versioning, features and documentation.
Intetion is to use turf.min.js in a browser environment. browserify is not desired.

1. using an old, given, but unknown version worked well with count() and an implicit merge after buffer(). But this version crashed in web workers.
2. I've tried built versions 3.0.11, 3.5.1, 3.5.2, a custom built of 3.5.2 as well as did an attempt on loading modules from 3.7.4. None of these provided an implicit or explicit merge(), Although source code indicates so. I didn't find a count() anymore.
3. Documentation doesn't really reflect this. Neither under mapbox nor under turf.js sites.
4. Links to build versions vary from turf.js site to github. Also within a single site.
5. package.json's didn't give me real version hints whatsoever.

Please point me to a latest working built version.
I'm fine with a monstrous all in package for the moment, but custom building sees to be best bet.
However, I'm missing count() and merge() there.

Thank you very much.

**Comment by tmcw** [comment]
Hi Jan,

Could you clarify about

>  None of these provided an implicit or explicit merge(), Although source code indicates so

The [documentation](http://turfjs.org/docs/) doesn't include count() or merge() - I'm not sure where you're seeing that the documentation promises the existence of those methods. The removal of merge is [documented in the changelog](https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#301), including a code example of an equivalent method in the current source. Count, likewise, is now represented by the `collect` method - also covered under that 'Upgrading from v2' section.

I'm not sure what your desire is; you're looking for outdated methods and the changelog covers their removal; the API documentation of this project & most others doesn't include removed functionality.

The latest minified version is at:

    https://npmcdn.com/@turf/turf@3.7.4/turf.min.js

The GitHub readme is outdated, unfortunately that's my bad but we've been pressed for time. If you see any other outdated references to locations, let me know and hopefully I can rope in someone to help out on the Mapbox side.

> package.json's didn't give me real version hints whatsoever.

I'm not sure what you mean: package.json includes a version field. Are you looking at the [right one](https://github.com/Turfjs/turf/blob/master/packages/turf/package.json)?

**Comment by kekscom** [comment]
Hi Tom,

Your reply made things a lot clearer. Thank you.

> None of these provided an implicit or explicit merge(), Although source code indicates so
A search showed occurences of 'merge' in source code. But as minified, I didn't dig deeper.

Documentation I was referring to is this: http://turfjs.org/examples/turf-merge/ Not sure how I got there.

Most helpful thing for me is the changelog. Didn't expect answers there.

Regarding package.json I was also looking at the wrong place. Module based versioning makes sense but maybe a global numbering being on par would help as well. However, not really a concern.

Thanks again,
Jan
