### ISSUE TITLE
turf-intersect erroneously picking up features that cross dateline

### ISSUE THREAD

**Issue by scbytron** [Turfjs/turf#549]
Hi

I've come across an issue where turf-intersect picks up features that cross the dateline even though they don't intersect with a bounding box.  I think the following examples show why this happens.

If you load the attached FeatureCollection into:
  https://google-developers.appspot.com/maps/documentation/utils/geojson/
and
  http://geojson.io/#map=2/53.4/-0.9

you will see that google-developers displays all features in the collection correctly, note however how there a number of features outside of the bounding box which have been selected by turf-intersect.

now look at the features as displayed in geojson.io.  This shows the features shown outside of the bounding box in google-developers, actually crossing through it.  My assumption is that turf-intersect is working more like geojson.io than google-developers.

My question is, is this how turf-intersect is working and why these erroneous features are being selected and if so is there any way to work around it?

i'm using nodejs @turf/turf v3.7.4

thanks
[test2.txt](https://github.com/Turfjs/turf/files/710929/test2.txt)

**Comment by rowanwins** [comment]
Hi @scbytron 

Unfortunantly those links to the data don't work. Perhaps you can save the geojson as a [gist file](https://gist.github.com/). 
Even better though would be a [jsfiddle](https://jsfiddle.net/) of your problem using the data and the showing us how you're using turf.

**Comment by scbytron** [comment]
Hi,

Thanks for replying.  You can just copy the contents of the test2.txt file (attached) into the panels in both websites to see the effect.

My code is basically doing a turf-intersect against the bounding box (shaded area shown on websites) against each of the other features displayed.

cheers

**Comment by rowanwins** [comment]
Hi @scbytron 

Ah ok I think I understand your issue. If I understand correctly you're wondering why geojson.io shows the features one way and the google site shows it a different way. 
This is actually to do with the way the mapping libraries on the respective sites use (eg the [google maps api](https://developers.google.com/maps/) vs [leaflet](http://leafletjs.com/)) render the geojson data, it doesnt actually have anything to do with turf.

For a good writeup on understanding the challenges around data which crosses the meridian check out [this blog post](http://www.macwright.org/2016/09/26/the-180th-meridian.html) by @tmcw who helps maintain Turf. Long story short is that data crossing the meridian is complicated!

Hope that helps

**Comment by scbytron** [comment]
Hi

Apologies i don't think i'm explaining the issue correctly.  Hopefully the attached image will help clarify.  The features highlighted in red on the geojson-io-incorrect image are being selected by turf-intersect even though they don't in reality cross the bounding box.  I believe that geojson.io is reflecting the same issue that turf-intersect is displaying.  The google-developer-correct image shows the same features highlighted in red and in their correct positions on the map.  What i am suggesting is that turf-intersect has the same issue as geojson-io in that it cannot work out the correct position of a feature if it crosses the dateline?  If that is the case is there anyway to resolve this.

Thanks for your help.

regards
Simon
![google-developers-correct](https://cloud.githubusercontent.com/assets/924936/22099510/8a31ddb8-de23-11e6-9290-1fb42dc4b5bd.png)
![geojson-io-incorrect](https://cloud.githubusercontent.com/assets/924936/22099511/8a51635e-de23-11e6-97bd-5a71d1ef20c2.png)

**Comment by rowanwins** [comment]
Ah I think I'm finally understanding @scbytron  , it's certainly an interesting one. I'll take a look into the code base and see if I can work out what is going wrong and report back

**Comment by scbytron** [comment]
Hi

I've created a fiddle which will hopefully show what's happening.  [https://jsfiddle.net/8048e98L/1/](url)

The **fc** var holds the subset of features that are being pulled from our main featureCollection based on using turf-intersect in nodejs.

The **bad** var holds one of the features (also in the the main fc feature collection) that 'shouldn't', based on human inspection be selected by turf-intersect.  This is highlighted in red on the map.  Note i've only highlighted one of the 'bad' features, there are several other features that are being selected 'incorrectly'.

The fiddle has a simple loop that goes around each feature checking with turf-intersect whether the feature intersects with the bounding box (**bbox** var).  The features and bounding box are then drawn on the map.

Thanks for your help

**Comment by rowanwins** [comment]
So the turf-intersect module is just a wrapper around the [jsts](https://github.com/bjornharrtell/jsts) library so there isn't actually much code that we can change. It is high on the priority list to remove the jsts dependencies but unfortunantly we're not quite there yet.

**Comment by DenisCarriere** [comment]
For any issues related to `@turf/intersect` submit a PR with a new GeoJSON Feature Collection with two polygons that should or should not intersect.

**Step 1:** Add polygon to [test/in](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect/test/in)

**Step 2:** Run tests `npm test`

**Step 3:** If an error occurs, submit PR with new GeoJSON causing the error.
