### ISSUE TITLE
does turf.intersect work for spatially querying more than 2 polygons OR what library OR workaround is recommended?

### ISSUE THREAD

**Issue by shawnmgoulet** [Turfjs/turf#567]
I have a [GeoJSON](https://gist.github.com/shawnmgoulet/e96b2110f71f1efbd9542eb90a3d49b0) of meshed/connected/neighboring polygons and want to onclick of a single polygon, select those polygons that interesect (a.k.a. border) the clicked polygon.

I was thinking of using `turf.intersect` to do this.  However, the [docs](http://turfjs.org/docs.html#intersect) only describe 2 polygons as being the arguments.

OR I _**think**_ (if needed as a workaround using TurfJS) I could use `turf.buffer` buffering the polygon centroid to select the neighboring polygons? [turf.buffer](http://turfjs.org/docs.html#buffer)

Hoping to get a nudge in the right direction here.  I haven't had luck finding my use case in open issues, GIS SE or SOflow.  Any recommendations would be super appreciated.

- [1] GeoJSON data as a [gist file](https://gist.github.com/shawnmgoulet/e96b2110f71f1efbd9542eb90a3d49b0).

**Comment by DenisCarriere** [comment]
Well unfortunately TurfJS doesn't have the ability to do large scale intersects like you are describing, however... you can pair Turf intersect with [RBush](https://github.com/mourner/rbush).

1. Build index with Rbush
2. Find all polygons and loop using intersect.

This would be very nice to have `@turf/intersect` do this in Turf.

**Comment by shawnmgoulet** [comment]
@DenisCarriere I added the .geojson extension (unfortunately GH returned an error trying to visualize), then removed hyphens in the name, still returning an error.

This is a valid geojson, however.  You can visualize it and/or download it directly from [NOAA Tool dd](http://gis.cccommission.opendata.arcgis.com/datasets/38f152366141480a8f09f493587fdb2c_0) - click on the "APIs" dropdown to get the geojson.  Showing fine in my web app shown here.
![noaa-screen-shot](https://cloud.githubusercontent.com/assets/3179974/22746083/bdb2b1a8-edf0-11e6-8b7a-e8dd82cb3aef.png)

**Comment by shawnmgoulet** [comment]
Yes, it would be, for my needs at least.  Thanks @DenisCarriere.  I'll work on your described workaround.  I don't _**need**_ to use TurfJS for this, however I haven't seen this functionality baked into any other JS spatial query libs.  Closing for now, I would think it would be a useful enhancement if & when.

**Comment by shawnmgoulet** [comment]
@DenisCarriere being that this would be my 1st time pairing `@turf/intersect + RBush`, are there any examples that I might be able to reference/build upon to do what I need to do that you know of?

**Comment by DenisCarriere** [comment]
@shawnmgoulet Well I have a pretty complex example from one of my public repos.

https://github.com/osmottawa/data-research/blob/master/Ottawa-Buildings/align-address.js

The data is not provided in the repo, however you can [preview the data here](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ#16.14/45.26171/-75.92567).

What the script does:
- Selects an address
- Finds the property parcel inside that address
- Finds all the buildings inside that parcel
- Align address with largest building inside parcel

Might be useful to look at the syntax

**Comment by shawnmgoulet** [comment]
@DenisCarriere so far as your code, please correct me if I'm wrong, but it looks like you're using your `geojson-writer` [geojson-writer](https://www.npmjs.com/package/geojson-writer) package to accomplish the bulk loading of bboxes into retree instead of using `rbush.load`?

Is this also accomplishing the insertion of bbox + parcel polygon indexes into an array of bboxes or is that unnecessary for your application here?

Apologies for any misunderstandings here, I'm trying to replicate your general workflow against @morganherlocker 's suggested approach [described here](https://github.com/Turfjs/turf-line-slice-at-intersection/issues/1).

Also, I am pulling my geojson file from a URL, through the execution of the jQuery `getJSON` method.  Can the package work upon the method execution in my case or does it have to be an actual file somewhere within the web application architecture (on the same machine)?
