### ISSUE TITLE
License clarification for turf/center-of-mass package

### ISSUE THREAD

**Issue by vlna** [Turfjs/turf#568]
Folder `packages/turf-center-of-mass` contains file `LICENSE` with MIT license inside but file `package.json` in the same folder contains line `"license": "ISC",`

@aurelien-defossez should answer what is correct - to fix `LICENSE` or to fix `package.json`

**Comment by DenisCarriere** [comment]
TurfJS is under the MIT license and it seems like the `turf-center-of-mass` is MIT based on the LICENSE file, I believe ISC is the default license when you `npm init`, looks like a simple mistake.

**Comment by aurelien-defossez** [comment]
I didn't look too closely into the licenses when I created the package, so I may have set the wrong license somewhere.

Feel free to correct it to MIT if it's turf standard license.
