### ISSUE TITLE
turfjs within not working

### ISSUE THREAD

**Issue by Kamparia** [Turfjs/turf#572]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Returns an empty json

**Comment by tmcw** [comment]
Please follow the template and provide details, and open a new issue with enough details for someone to figure out what's going on.
