### ISSUE TITLE
Turf donut feature

### ISSUE THREAD

**Issue by dhivehi** [Turfjs/turf#573]
Need a turf donut feature in turfjs. Its already in https://github.com/Turfjs/turf-donuts
But i'm wondering why it's not available in turfjs

**Comment by rowanwins** [comment]
Gday @dhivehi 

Unfortunantly that module is a fair way out of date and would need a bit of work to update it. It was part of the core once upon a time but was taken out for a [few reasons](https://github.com/Turfjs/turf/issues/157).

If you'd like to see it reincluded I'm sure people would be open to a pull request.

Cheers
