### ISSUE TITLE
hexGrid typings want "units" to be a number

### ISSUE THREAD

**Issue by magnolo** [Turfjs/turf#575]
Shouldn't it be a string?

I just updated to 3.10.1 and finally could kick out the seperated typings definition. Thx for that. 
But in the hexGrid function the third parameter "units" is defined as number.
Luckily i just need it to be "kilometers", which is already predefined.

**Comment by DenisCarriere** [comment]
@magnolo You are absolutely correct, minor mistake in the Typescript definition. I've submitted a patch to fix this.

**Comment by DenisCarriere** [comment]
Turf `3.10.2` should have the Typescript definitions fixed.
