### ISSUE TITLE
Add utility method to load and validate geojson from remote source

### ISSUE THREAD

**Issue by scottsfarley93** [Turfjs/turf#577]
Feature request for adding a method that gets loads and validates a remote geojson file via ajax. 

Turf expects geojson to be already validated and stored as a JS variable. Working with the library would be made simpler if there was a method that creates and executes the xmlhttprequest, validates the source against the geojson specification, and returns the validated data as an object. The validated object could then be passed to future turf calls.

**Comment by morganherlocker** [comment]
A validation module would make a lot of sense in turf, but anything touching loading sources is out of scope in my opinion. There are many excellent javascript modules that solve this problem very well already (for example, [requestjs](https://github.com/request/request) or [browser-request](https://github.com/iriscouch/browser-request)), and many http oriented libs are not compatible with both browser and server/desktop environments. 

Additionally, loading/saving requirements change quite a bit depending on the use case. For example, working with large datasets would work best with a streaming API, whereas small datasets can use a simple callback API. One of the core design goals of Turf is to make as few judgements as possible about the final implementation or runtime environment, and to leave those considerations up to the developer. The first version of Turf actually did not support browsers at all until we settled on this design approach and removed the `load` and `save` functions that interacted with the filesystem.

Here is the issue for implementing a `valid` module: https://github.com/Turfjs/turf/issues/64

```js
// example usage
request('http://mydata.com/data.geojson', (err, res, body) => {
  var data = JSON.parse(body)
  if(!turf.valid(data)) throw Error('invalid geojson data detected')
  // do stuff
})
```
