### ISSUE TITLE
Convert packages to Rollup

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#583]
Previous discussion: https://github.com/Turfjs/turf/issues/576

After many failed rollup attempts, I think this solution is a winner.

## Rollup packages

Progress tracker for converted Rollup modules/packages.

- [x] [`turf-union`](https://github.com/Turfjs/turf/tree/rollup/packages/turf-union)
- [x] [`turf-truncate`](https://github.com/Turfjs/turf/tree/rollup/packages/turf-truncate)
- [x] `turf-line-intersect`

## Pros

- for modules without dependencies`index.js` & `index.es6.js` have identical LOCs 1=1 match (easy to debug when testing).
- rollup builds are really fast `lerna run rollup`
  - [`turf-truncate`](https://github.com/Turfjs/turf/tree/rollup/packages/turf-truncate) 0.60s user 0.09s system 100% cpu 0.689 total
  - [`turf-union`](https://github.com/Turfjs/turf/tree/rollup/packages/turf-union) (uses jsts) 1.36s user 0.18s system 110% cpu 1.395 total
- works with CommonJS dependencies using [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs)
- works VERY well with ES6 modules ([`jsts`](https://github.com/bjornharrtell/jsts) is using ES6)
- Enforce good dependency practice by only importing small amounts of code (not entire libraries for a single function).
- In some scenarios it might be better simply include the specific function in the source code instead of using it as a dependency.
- Source code structure remains the same (`index.js` === CommonJS).
- Browserify `npm run build` does not break (will keep using browserify until all turf modules are completely converted to Rollup)

## Cons

- **ONLY** use the ES6 import/export syntax, the rest of the code should remain ES5 to continue supporting IE 9 and other legacy browsers (for now).
- Modules with large dependencies make it confusing to test since lines of codes don't match.
  **Solutions:**
  - When creating a new module, simply create it as ES5 and when you are done you can switch to ES6 export/import syntax.
  - Drop the `nodeResolve` rollup plugin and treat dependencies as external modules.

## Rollup Checklist

- Add `rollup` to your `devDependencies`.
```bash
$ yarn add --dev rollup
```
-  Convert filename `index.js` to `index.es6.js`
- Replace `require` dependencies with `import`
```javascript
var jsts = require('jsts');
var reader = new jsts.io.GeoJSONReader();

//=import entire library
import * as jsts from 'jsts';
var reader = new jsts.io.GeoJSONReader();

//=(perfect world) only import the specific module needed
import {io} from 'jsts/src/jsts';
var reader = new io.GeoJSONReader();
```
- Replace `module.exports` to `export` & `export default`
```javascript
module.exports = function (points, polygons) {

//=converts to
export default function (points, polygons) {
```
- Add rollup config (with dependencies will be treated as an externally)
   **Examples:**
  - [`turf-truncate`](https://github.com/Turfjs/turf/blob/rollup/packages/turf-truncate/rollup.config.js)
  - [`turf-union`](https://github.com/Turfjs/turf/blob/rollup/packages/turf-union/rollup.config.js)
```javascript
const pkg = require('./package.json');

export default {
    entry: 'index.es6.js',
    format: 'cjs',
    dest: pkg['main']
};
```
- Define entry points in `package.json`
```javascript
  "main": "index.js",
  "jsnext:main": "index.es6.js",
  "types": "index.d.ts",
```
- Add build & tests to `package.json` **scripts**
```
  "scripts": {
    "test": "tape test.js",
    "pretest": "npm run rollup",
    "rollup": "rollup -c rollup.config.js"
  },
```
- Remove any `.npmignore` in favor of **files** in `package.json`
```javascript
  "files": [
    "index.js",
    "index.es6.js",
    "index.d.ts"
  ],
```
- Delete current `index.js` and add `.gitignore` (`index.es6.js` should be the only source code in the git repo)
```
index.js
```
- Add `'use strict';` at the top of your `index.es6.js` to make the ES6 rollup build have exactly 1:1 source code line matching.

CC: @tmcw @mourner @morganherlocker

**Comment by DenisCarriere** [comment]
So far so good, I've got the latest commit https://github.com/Turfjs/turf/commit/50094df62d3b9942ed3e4125296239447d974518 passing an entire TurfJS build (lint, build, test, publish with browserify) .

Before moving forward too far with this, I'd like to merge the `rollup` branch and see how Lerna deals with publishing the new rollup format.

This should only be publish two modules `turf-truncate` (no dependencies) & `turf-union` (uses jsts).

**Comment by rowanwins** [comment]
Good work @DenisCarriere looks like your making great progress, thanks for the detailed doco as well

So our of interest for the union module, can you give us an idea of browserify build sizes between the original version and your es6 rollup version?

**Comment by DenisCarriere** [comment]
Well at the moment the final browserify build will be the same, however if we continuously hammer away at each individual module like this I'm sure we can downsize the bundle.

I'm also noticing that `jsts` is very heavy (we all knew that) and there's no way to import only the ES6 modules since many of the functions depend on the root package to be entirely imported (`jsts` kinda defeats the purpose of using rollup ES6 import/export modules).

We also don't want to make our life more complicated... so this is just the "first round" of converting Turf to Rollup (however still being ES5 syntax compliant).

**Comment by DenisCarriere** [comment]
From the small attempts I've done so far with converting modules to ES6, there's almost minimal advantage since TurfJS is already organized in a "Rollup" efficient way by using Lerna, each module can be loading individually.

The main library we are having issues with is `jsts` and it's not friendly at all for specific method imports. For `jsts` to work properly, you need to import the entire library (which then defeats the purpose of converting it to Rollup).

I've been using the `[rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs)` and so far it's been really great with TurfJS with the "commonjs" format.

Even the folks at Facebook are still using `module.exports` (using Rollup to simply create the browser bundle) for their latest [`Prettier`](https://github.com/prettier/prettier) library. 

@tmcw You were right all the time! 👍 

Going to close this issue & convert the ES6 library back to vanilla ES5 (we can use it as reference later if we decide to go back to converting Turf to Rollup).
