### ISSUE TITLE
Drawing perpendicular lines using turf library

### ISSUE THREAD

**Issue by marie15** [Turfjs/turf#585]
Hi, I want to draw orthogonal lines on map using leaflet, I research for leaflet geodesic plugin but I couldn't find function for doing that, so my question is turf library provide this kind of function and can I use it with leaflet?
Any help is appreciated. Thank you

**Comment by rowanwins** [comment]
Hi @marie15 

Unfortunately there is nothing available at the moment, someone has previously requested something similar however no-one has had the time to implement it yet.

I am aware of this [leaflet plugin](https://github.com/bbecquet/Leaflet.PolylineOffset) which may do what you want.

**Comment by stebogit** [comment]
@marie15 you could use `@turf-bearing` or `@turf-rhumb-bearing` to get the slope of one line and add 90 degrees to draw the orthogonal one.
