### ISSUE TITLE
New module @turf/line-intersect

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#586]
Proposing to create a new core module **`@turf/line-intersect`**

**Description:** Takes two GeoJSON LineStrings and returns the intersecting point(s).

**Future use:** Need to use this functionality in [`@turf/polygon-slice`](https://github.com/Turfjs/turf/issues/580).

**Branch:** [`line-intersect`](https://github.com/Turfjs/turf/tree/line-intersect/packages/turf-line-intersect)

**Geometry Support**
- LineString & MultiLine
- Feature & FeatureCollection

**Dependencies**

- [RBush](https://github.com/mourner/rbush) (to quickly detect intersecting lines divided into pairs of 2 coordinates)
- `@turf/helpers`
- `@turf/meta` (using coordReduce & featureEach)
- `@turf/bbox-polygon` (debugging purposes)

![image](https://cloud.githubusercontent.com/assets/550895/23461869/a284eb34-fe59-11e6-8497-15c44b7cf98e.png)

**Benchmark**

```
double-intersect x 76,313 ops/sec ±0.86% (87 runs sampled)
feature-collection x 34,139 ops/sec ±1.80% (89 runs sampled)
multi-linestring x 23,185 ops/sec ±2.06% (84 runs sampled)
simple x 237,005 ops/sec ±1.41% (86 runs sampled)
```

**JSDocs**

```javascript
/**
 * Takes two GeoJSON LineStrings and returns the intersecting point(s).
 *
 * @name lineIntersect
 * @param {Feature<LineString>} line1 GeoJSON LineString Feature
 * @param {Feature<LineString>} line2 GeoJSON LineString Feature
 * @returns {FeatureCollection<Point>} point(s) that intersect both lines
 * @example
 * var line1 = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "LineString",
 *     "coordinates": [
 *       [126, -11],
 *       [129, -21]
 *     ]
 *   }
 * };
 * var line2 = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "LineString",
 *     "coordinates": [
 *       [123, -18],
 *       [131, -14]
 *     ]
 *   }
 * };
 * var points = turf.lineIntersect(line1, line2);
 * //= points
 */
export default function (line1, line2) {
```

**Comment by DenisCarriere** [comment]
## Line Intersect - New Module! 🎉 
**[`@turf/line-intersect`](https://www.npmjs.com/package/@turf/line-intersect)** module is now published under **Turf `3.11.x`**.

More details on PR https://github.com/Turfjs/turf/pull/590

CC: @Turfjs/ownership

**Comment by mourner** [comment]
You're on fire Denis, keep it up!

**Comment by marie15** [comment]
Hi, thank you @DenisCarriere for this new modul, but I'm trying to use it and I got error: "turf.lineIntersect is not a function". I'm using turf 3.5.1.

**Comment by DenisCarriere** [comment]
@marie15, you have to upgrade to the latest version.

**Comment by marie15** [comment]
Yep I forgot that, thank you

**Comment by marie15** [comment]
Hi, I'm trying to use this module, it's working good when I try that: 
`var line1 = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates": [
      [126, -11],
      [129, -21]
    ]
  }
};
var line2 = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates": [
      [123, -18],
      [131, -14]
    ]
  }
};
var point = turf.lineIntersect(line1, line2);`
But when I tried with my real data, the intersection point is empty. Here is the code:
`path1 = new L.Polyline(line1);
path2 = new L.Polyline(line2);
var interLines = turf.lineIntersect(path1, path1);
	if (interLines
       { console.log(interLines);
       }`
In the console I got this result: 
Objectfeatures: Array[0]
length: 0
__proto__: Array[0]
type: "FeatureCollection"
__proto__: Object

**Comment by DenisCarriere** [comment]
@marie15 I don't think you're using the proper way to load a GeoJSON into a Leaflet layer, try using this: http://leafletjs.com/examples/geojson/

**Comment by marie15** [comment]
I fixed the problem, but now I'm facing more complicated problem. I have multiple parallel lines and perpendicular lines to those lines ( like a matrix), I want to add intersect points between all this points, I tried to do that, but it display on map only the orthogonal. Here is a screenshot: 

![goutteurs](https://cloud.githubusercontent.com/assets/14139375/24256933/695d947a-0fe1-11e7-97af-d91d7ee88251.PNG)

**Comment by shawnmgoulet** [comment]
@DenisCarriere in the **Geometry support** above, you mention that `@turf/line-intersect` supports:
- listLineString & MultiLine
- Feature & FeatureCollection

My understanding of the `@turf/line-intersect` [documentation](http://turfjs.org/docs/#lineintersect) is that the geojson geometry needs either be:
- FeatureCollection or Feature
- LineString or MultiLineString or Polygon or MultiPolygon

I was planning that it could be used for selecting polygons of a multipolygon feature that intersect with a single polygon feature.  Is that possible or is converting to lines or something else necessary to achieve?

**Comment by DenisCarriere** [comment]
@shawnmgoulet Thanks for pointing this out, I believe we decided to drop the Polygon support since it would create a bit of confusion on how the Polygons are being handle.

Easy solution that you can do right now is use the [`@turf/polygon-to-linestring`](http://turfjs.org/docs/#polygontolinestring) module which will do exactly what the name of the module will do.

**Note:** Handling Multi-Polygons with holes will return a FeatureCollection of MultiLineStrings.

**Comment by DenisCarriere** [comment]
@shawnmgoulet Let me know if you have any issues when using Polygons, works for me.

**Comment by shawnmgoulet** [comment]
@DenisCarriere thanks for sharing @DenisCarriere - this is great.

My use case includes a polygon & multipolygon geojson.

What I'm having to do is using a polygon to select the intersecting polygons (of a multipolygon) to then manipulate properties of those intersecting based on properties of the polygon feature.

![polygon-select-polygons-multipolygon](https://user-images.githubusercontent.com/3179974/30673790-9f03696a-9e43-11e7-9732-1cd15da2626c.png)

**Comment by shawnmgoulet** [comment]
Looking more into this, it might have something to do with the multipolygon issues of `JSTS` mentioned in [issue 702](https://github.com/Turfjs/turf/issues/702) by @rowanwins.  I am getting the below error when running:

`var polyIntersects = turf.lineIntersect(thePolygon, hexPolygons)`
where `thePolygon` is the polygon feature and `hexPolygons` is the multipolygon feature collection

I'm going to have to continue testing alternative approaches.

**Comment by DenisCarriere** [comment]
@shawnmgoulet interesting findings, feel free to send a PR with your failing test data.

Only thing you need to do is drop a GeoJSON with 2 features:
https://github.com/Turfjs/turf/tree/master/packages/turf-line-intersect/test/in

If it's the FeatureCollection handling, you could look into iterating over each feature using `featureEach` in [`@turf/meta`](https://github.com/Turfjs/turf/tree/master/packages/turf-meta), it's not the most efficient way to do things, but at least you won't have errors.

**Comment by DenisCarriere** [comment]
@shawnmgoulet another option would be to use [`@turf/combine`](https://github.com/Turfjs/turf/tree/master/packages/turf-combine) to merge your entire feature Collection into a MultiPolygon/MultiLineString... let me know if that works or not!

**Comment by shawnmgoulet** [comment]
Thank you for the suggestions @DenisCarriere.  I'll update once I get an approach to do to solve this case.
