### ISSUE TITLE
Remove difference between two Geojson layers using Turfjs

### ISSUE THREAD

**Issue by marie15** [Turfjs/turf#591]
I've draw line programmatically (not using leaflet draw) inside polygone using leaflet draw plugin on map, I want to keep only the points of polyline that are inside of polygone and remove those are outside. Using **difference** method of **Turfsjs** library, I can get the "difference" layer between the polygon and line, now I want to remove the difference between this layers from map and keep only the polygone and part of line that is inside the polygon. Any help is much appreciated. Thank you.
Here is a code snippet:

var line = path.toGeoJSON(); var polygon = selectedPoly.toGeoJSON(); var difference, result = []; difference = turf.difference(line, polygon); if (difference) { result.push(difference); var inter = L.geoJson(result).addTo(map); }

Here is a screenshot of difference method :
![capturedifference](https://cloud.githubusercontent.com/assets/14139375/23579256/6849b4d8-00e1-11e7-8f69-52e8657fff6a.JPG)

This is what I want to get: 
![capturebefore](https://cloud.githubusercontent.com/assets/14139375/23579263/8b2e9554-00e1-11e7-9bef-daac091d2414.JPG)

**Comment by rowanwins** [comment]
Gday @marie15 if you could provide a jsfiddle of where you're up to that would be great, we can probably provide more assistance then

**Comment by marie15** [comment]
@rowanwins I add screenchot to the post to be more clear

**Comment by DenisCarriere** [comment]
@marie15 You could use [`@turf/line-slice`](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice) to cut the line & [`@turf/line-intersect`](https://github.com/Turfjs/turf/tree/master/packages/turf-line-intersect) to find the point the `stop` point which will be where to cut.

Best of luck!

This doesn't seem to be an issue with `TurfJS`, closing for now until any issues come up by doing this calculation.

**Comment by marie15** [comment]
Oki Thank you for your help, I will try that

**Comment by DenisCarriere** [comment]
👍 It should work (that's what I would do)

**Comment by marie15** [comment]
I hope so :+1:

**Comment by marie15** [comment]
@DenisCarriere I tried with @turf/line-slice, it make slice of the line at the given start and stop points but it just highlight ths slice line not remove it from map, the same problem as difference method. What I have to do to remove the slice line outside of polygon?

**Comment by rowanwins** [comment]
Hi @marie15 - turf will not do things like remove the old parts of the polygon from the map, turf does not tied to any particular mapping library (eg leaflet or open layers) etc, it only concerns itself with spatial operations on geojson. 

As suggested above a jsfiddle might help us give you the best assistance.

**Comment by marie15** [comment]
Oki I understand you @rowanwins, I'm using turf with Leaflet. I will try to create a jsfiddle code snippet. Thank you :+1:

**Comment by marie15** [comment]
[Here](http://jsfiddle.net/LnzN2/744/) is a jsfiddle example, it's not my real code but it show the same issue, sorry I can't post my real code. So as you observe in the jsfiddle, the difference part is highlight but I want to remove this part of line usinf turf and leaflet

**Comment by marie15** [comment]
Hi, do you have idea how to do that, please?

**Comment by marie15** [comment]
I found [this](https://github.com/Turfjs/turf/issues/580) post in github, it treat the same issue, so @DenisCarriere Can you help me do fix this probelm, it took me a long time

**Comment by rowanwins** [comment]
Hi @marie15 , please be aware that both @DenisCarriere & myself maintain this repo in our spare time so please be patient, we will provide support when we can.

**Comment by marie15** [comment]
Oki I understand, Thank you :+1:

**Comment by marie15** [comment]
Hi guys, I fix the issue using intersect method of turf, but I'm still want to wait your new module @DenisCarriere and @rowanwins , good luck :+1:

**Comment by DenisCarriere** [comment]
👍 Good stuff
