### ISSUE TITLE
bearing is initial bearing

### ISSUE THREAD

**Issue by espinielli** [Turfjs/turf#597]
The implementation of `bearing` is about the *initial* bearing as from cited [URL](http://www.movable-type.co.uk/scripts/latlong.html) in the sources.
IMHO this should be explicitly mentioned in the API. 
Maybe even implement *final* bearing as per above [URL](http://www.movable-type.co.uk/scripts/latlong.html)

> For final bearing, simply take the initial bearing from the end point to the start point and reverse it (using θ = (θ+180) % 360).

**Comment by rowanwins** [comment]
Thanks for the report @espinielli , I'll get the docs updated to make that clearer. 

@DenisCarriere - what do you think about adding an optional third argument which flags to return the final bearing...

**Comment by DenisCarriere** [comment]
I think adding an additional param would work.

This picture was helpful figuring out the difference between intial bearing (29 Deg) & final bearing (150 Deg).
![image](https://cloud.githubusercontent.com/assets/550895/23592786/edea6a90-01d3-11e7-9caf-08cae4fac336.png)

**Proposed JSDocs**

```javascript
/**
 * Takes two {@link Point|points} and finds the geographic bearing between them.
 *
 * @name bearing
 * @param {Feature<Point>} start starting Point
 * @param {Feature<Point>} end ending Point
 * @param {boolean} [final=false] calculates the final bearing if true
 * @returns {number} bearing in decimal degrees
```

**Comment by espinielli** [comment]
I love the additional picture to explain it.
Also the additional, *optional* param is a good idea.

I forgot to mention that what is returned is angle east of North (see the [footnote link](http://mathforum.org/library/drmath/view/55417.html) in [URL](http://www.movable-type.co.uk/scripts/latlong.html) mentioned above).

![image](https://cloud.githubusercontent.com/assets/891692/23605112/af3954a4-025b-11e7-9f34-028b89572268.png)

**Comment by DenisCarriere** [comment]
Fixed, will be released in the next Turf minor release.

You can do some cool stuff with final bearing! 👍 

@rowanwins This opens up a new potential module, `@turf/line-arc` which creates a "fake" line which represents a line based on a the great circle. It would be almost be the same as `@turf/line-chunk` except it has initial bearings & final bearings in the mix.

**Start**=Red
**End**=Blue
![image](https://cloud.githubusercontent.com/assets/550895/23670554/13f98316-0336-11e7-9250-e8a9db762df3.png)

**Comment by rowanwins** [comment]
@DenisCarriere a great circle has been [raised before](https://github.com/Turfjs/turf/issues/273), it looks like morgans recommendation was using this [existing repo](https://www.npmjs.com/package/arc). ANd it looks like @stepankuzmin has even gone to the effort of [packaging](https://github.com/stepankuzmin/turf-arc) it up for turf already!

**Comment by DenisCarriere** [comment]
Amazing!! 👍 Creating great circle arcs are very fancy!

Put that one on a To-Do list

**Comment by DenisCarriere** [comment]
Weee!!!! 🎉 

![image](https://cloud.githubusercontent.com/assets/550895/23681703/0b054d9e-035e-11e7-8fdf-6e447f9cf914.png)

**Comment by stepankuzmin** [comment]
We can merge https://github.com/stepankuzmin/turf-arc into turf repo too

**Comment by DenisCarriere** [comment]
We can, since the repo is only 4 lines of code, it might be best to simply use `arc` as a dependency.
