### ISSUE TITLE
Minor release published 3.13

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#610]
# Minor Release Turf 3.13 🎉 

## New Modules

- [`@turf/line-chunk`](https://github.com/Turfjs/turf/issues/601)
- [`@turf/mask`](https://github.com/Turfjs/turf/issues/594)
- [`@turf/great-circle`](https://github.com/Turfjs/turf/pull/607)
- [`@turf/unkink-polygon`](https://github.com/Turfjs/turf/pull/579)

## Improvements

- [`@turf/bearing`](https://github.com/Turfjs/turf/pull/603) add final bearing
- [`@turf/flatten`](https://github.com/Turfjs/turf/issues/595) performance increase
- [`@turf/invariant`](https://github.com/Turfjs/turf/pull/606) add `getCoords()`
- [`@turf/helpers`](https://github.com/Turfjs/turf/pull/602) performance increase for `point()`

CC: @Turfjs/ownership

**Comment by rowanwins** [comment]
Nice one @DenisCarriere - you're going so fast the rest of us can't keep up :)

**Comment by DenisCarriere** [comment]
I got bored over the weekend :) Netflix and TurfJS
