### ISSUE TITLE
Array prototype modified by turf causes problems in for ... in iterations

### ISSUE THREAD

**Issue by mdomnita** [Turfjs/turf#621]
Loading turf.js in a page modifies the javascript Array prototype by adding two functions: 
getUnique
isUnique
Whenever doing a for...in on any array these values come out as indexes causing lots of javascript code to have issues. 

Sample code, in any page with turf.js loaded (tested in Chrome and Firefox):
`var arr = [1,2,3,4,5];
for (it in arr) { console.log(it); }`

logs to console:

> 0
> 1
> 2
> 3
> 4
> getUnique
> isUnique

Fiddle:
[https://jsfiddle.net/mdomnita/7batkx5s/](https://jsfiddle.net/mdomnita/7batkx5s/)

I noticed problems both in my code and in other libraries loaded together with turf.js (for example [Leaflet.LinearMeasurement](https://github.com/NLTGit/Leaflet.LinearMeasurement) )

**Comment by DenisCarriere** [comment]
👍 That looks like a real issue.

Doesn't seem to come from [TurfJS](https://github.com/Turfjs/turf/search?utf8=%E2%9C%93&q=isUnique&type=Code) or [jsts](https://github.com/bjornharrtell/jsts/search?utf8=%E2%9C%93&q=getUnique&type=Code)... Must be coming from another dependency.

**Comment by DenisCarriere** [comment]
It seems to be coming from [`simplepolygon`](https://github.com/mclaeysb/simplepolygon/blob/master/index.js#L420-L445)

```javascript
// Function to get array with only unique elements. From http://stackoverflow.com/questions/1960473/unique-values-in-an-array
Array.prototype.getUnique = function(){
 var u = {}, a = [];
 for(var i = 0, l = this.length; i < l; ++i){
    if(u.hasOwnProperty(this[i])) {
       continue;
    }
    a.push(this[i]);
    u[this[i]] = 1;
 }
 return a;
}

// Function to check if array is unique (i.e. all unique elements, i.e. no duplicate elements)
Array.prototype.isUnique = function(){
 var u = {}, a = [];
 var isUnique = 1;
 for(var i = 0, l = this.length; i < l; ++i){
    if(u.hasOwnProperty(this[i])) {
      isUnique = 0;
      break;
    }
    u[this[i]] = 1;
 }
 return isUnique;
}
```

**Comment by mdomnita** [comment]
I only loaded turfjs in the fiddle and same in my code. I didn't get the chance to look deeper in the problem yet, I hope someone gives me a hint on this before changing all the loops in the code.

I see these as anonymous functions in the Chrome developer tools and this is what caused problems in several Leafletjs plugins

```
__proto__:Array[0]
copyWithin:copyWithin()
entries : entries()
every : every()
fill : fill()
...
getUnique : ()
includes : includes()
...
isUnique : ()
```

**Comment by DenisCarriere** [comment]
👍 @mdomnita thanks for reporting this, these types of behaviors shouldn't happen.

@rowanwins We need to fix [`turf-unkink-polygon`](https://github.com/Turfjs/turf/tree/master/packages/turf-unkink-polygon).

**Comment by ozomer** [comment]
This issue also makes funny things when using [clone](https://www.npmjs.com/package/clone).

**Comment by mdomnita** [comment]
It's now working, thanks. This can be closed from my point of view.

**Comment by DenisCarriere** [comment]
Let's try to remove those other Array functions before we close.

**Comment by stebogit** [comment]
@DenisCarriere is this issue solved or still Array.prototype is being polluted? Don't see undesired Array methods though

**Comment by DenisCarriere** [comment]
@stebogit Looks like it is resolved, I don't see any no-standard `Array.prototype` anymore.

```bash
> const turf = require('@turf/turf')
> Array.prototype.
Array.prototype.__defineGetter__      Array.prototype.__defineSetter__
Array.prototype.__lookupGetter__      Array.prototype.__lookupSetter__
Array.prototype.__proto__             Array.prototype.constructor
Array.prototype.hasOwnProperty        Array.prototype.isPrototypeOf
Array.prototype.propertyIsEnumerable  Array.prototype.toLocaleString
Array.prototype.toString              Array.prototype.valueOf

Array.prototype.concat                Array.prototype.copyWithin
Array.prototype.entries               Array.prototype.every
Array.prototype.fill                  Array.prototype.filter
Array.prototype.find                  Array.prototype.findIndex
Array.prototype.forEach               Array.prototype.includes
Array.prototype.indexOf               Array.prototype.join
Array.prototype.keys                  Array.prototype.lastIndexOf
Array.prototype.length                Array.prototype.map
Array.prototype.pop                   Array.prototype.push
Array.prototype.reduce                Array.prototype.reduceRight
Array.prototype.reverse               Array.prototype.shift
Array.prototype.slice                 Array.prototype.some
Array.prototype.sort                  Array.prototype.splice
Array.prototype.unshift
```
