### ISSUE TITLE
Error: Cannot find module 'geojson-polygon-self-intersections

### ISSUE THREAD

**Issue by bkowshik** [Turfjs/turf#625]
- Node version: `v4.4.0`
- Turf version: `^3.14.0`

```sh
# Install turf with npm
npm install --save @turf/turf

# Create a JavaScript file and import turf.
$ vim index.js
var turf = require('@turf/turf');


$ node  index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'geojson-polygon-self-intersections'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/user/repos/temp/turf-test/node_modules/@turf/turf/node_modules/@turf/unkink-polygon/simplepolygon.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

---

cc: @DenisCarriere

**Comment by bkowshik** [comment]
An explicit install of `geojson-polygon-self-intersections` solved the error.

**Comment by DenisCarriere** [comment]
👍 Thanks for reporting this.. it came from [@turf/unkink-polygon](https://github.com/Turfjs/turf/tree/master/packages/turf-unkink-polygon)

CC: @rowanwins

**Comment by DenisCarriere** [comment]
👍 Fixed in Turf `3.14.1`
Feel free to open this issue again if this happens again.

**Comment by bkowshik** [comment]
Thank you @DenisCarriere 👍

**Comment by rowanwins** [comment]
Hi @DenisCarriere 

I might've missed something but why is `simplepolygon.js` [loaded as a file directly in the repo](https://github.com/Turfjs/turf/blob/master/packages/turf-unkink-polygon/simplepolygon.js) and then referenced from the index.js , rather than pulling it as a dependency from the node_modules?

Any ideas? 

Cheers

**Comment by DenisCarriere** [comment]
Hey @rowanwins, the dependency hasn't been updated on npm yet with the new `Array.isUnique` issue https://github.com/Turfjs/turf/issues/621 resolved here (https://github.com/mclaeysb/simplepolygon/commit/0f4648c194b9317bc5e7f11d6efa18d0ab47ca31).

In this specific scenario, the `simplepolygon.js` was just used as a patch until the npm module got released.

@mclaeysb Any chance you can publish a patch to npm of `simplepolygon`?

**Comment by mclaeysb** [comment]
Hi all

Forgot to `npm patch` and `npm publish` the accepted PR - my bad. Just did so!

Glad to see `simplepolygon` finds usage.

**Comment by DenisCarriere** [comment]
👍 Awesome, thanks @mclaeysb

**Comment by DenisCarriere** [comment]
@mclaeysb Still broken... 👎 https://unpkg.com/simplepolygon@1.1.2/index.js

The patch might not of included the latest commit, did you do a `git pull` before you patched it?

The code still contains

```javascript
Array.prototype.isUnique = function(){
 var u = {}, a = [];
 var isUnique = 1;
 for(var i = 0, l = this.length; i < l; ++i){
    if(u.hasOwnProperty(this[i])) {
      isUnique = 0;
      break;
    }
    u[this[i]] = 1;
 }
 return isUnique;
}
```

**Comment by mclaeysb** [comment]
Ah, forgot..

Just a second, I'm having persion issues with my .git folder..

**Comment by mclaeysb** [comment]
Should be ok now!

**Comment by DenisCarriere** [comment]
👍 @mclaeysb Thanks, yep it works now. Patching TurfJS right now.
