### ISSUE TITLE
New module @turf/line-split

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#626]
## New module 🎉  @turf/line-split (Proposal)

**Description:** Split a LineString at the intersections of another LineString.

I've accidentally [built this module](https://github.com/Turfjs/turf/blob/0f678ff0545fd8b8d78a0f231e0a5fad0c76c5ff/packages/turf-polygon-slice/index.js#L58-L127) trying to get [`@turf/polygon-slice`](https://github.com/Turfjs/turf/issues/580) to work.

Not to be confused with [`@turf/line-slice`](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice) or [`@turf/line-segment`](https://github.com/Turfjs/turf/tree/master/packages/turf-line-segment).

**JSDocs**

```javascript
/**
 * Split a LineString at the intersections of another LineString.
 *
 * @param {Feature<LineString>} source Line Feature to split
 * @param {Feature<LineString>} target Line Feature used to find intersections
 * @returns {FeatureCollection<LineString>} Split lines
 */
```

**Example**

Give two lines that criss-cross each and return the segments that intersect them.
- Blue & Red lines (source - split into segments)
- Black line (target linestring)
![image](https://cloud.githubusercontent.com/assets/550895/24223741/ecd328c4-0f2d-11e7-85d0-b0d817e05da5.png)

**Example**
Using a Polygon outer as LineString and a Line to split the polygon into two segments.

- Blue & Red lines (source - polygon outer)
- Black line (target linestring)

![image](https://cloud.githubusercontent.com/assets/550895/24223790/262ccdd2-0f2e-11e7-90a4-7bfed0beaea5.png)

**Dependencies:**
```json
{
    "@turf/helpers": "^3.13.0",
    "@turf/invariant": "^3.13.0",
    "@turf/line-intersect": "^3.14.0",
    "@turf/line-segment": "^3.14.0",
    "@turf/meta": "^3.14.0",
    "clone": "^2.1.1",
    "geojson-rbush": "^1.0.1"
  }
```
**Benchmark**

No results yet (~2000-3000/ops/sec)

**Comment by marie15** [comment]
Congratulations for this new module. Good job :+1:

**Comment by DenisCarriere** [comment]
Thanks @marie15 it's not published yet, however it's already 95% done, just need to bundle it.

**Comment by marie15** [comment]
Good continuation

**Comment by DenisCarriere** [comment]
As I add more and more test cases, this is becoming less and less stable.. (not surprised).

Going to use [`shapely`](https://github.com/Toblerity/Shapely/blob/master/shapely/ops.py#L330-L475) as a starting point for performing the specific operations.

------
## Shapely Docs
Splits a geometry by another geometry and returns a collection of geometries. This function is the theoretical opposite of the union of the split geometry parts. If the splitter does not split the geometry, a collection with a single geometry equal to the input geometry is returned.
The function supports:

  - Splitting a (Multi)LineString by a (Multi)Point or (Multi)LineString or (Multi)Polygon
  - Splitting a (Multi)Polygon by a LineString

It may be convenient to snap the splitter with low tolerance to the geometry. For example in the case of splitting a line by a point, the point must be exactly on the line, for the line to be correctly split.

When splitting a line by a polygon, the boundary of the polygon is used for the operation.
When splitting a line by another line, a ValueError is raised if the two overlap at some segment.

### Parameters
- geom : geometry
  - The geometry to be split
- splitter : geometry
  - The geometry that will split the input geom

**Comment by DenisCarriere** [comment]
PR https://github.com/Turfjs/turf/pull/634 implements this module.
