### ISSUE TITLE
Can't calculate altitude of point using turf

### ISSUE THREAD

**Issue by marie15** [Turfjs/turf#627]
I have a set of points, I can get latitude and longitude of this points but can't find function in turf library for calculating altitude(position z). Is turf able to do that?

Thank you

**Comment by DenisCarriere** [comment]
Altitudes would be the 3rd coordinate of your point [x, y, z (altitude)]. More on info on [coordinate positions](http://geojson.org/geojson-spec.html#positions).

Calculating altitudes is pretty vague as a request, there's already lots of different interpolation functions in Turf that helps you figure out what you want to do with your altitude results.

Check out the interpolation functions, maybe one of them might be useful for you.
http://turfjs.org/docs/#interpolation

**Comment by marie15** [comment]
I already read this link. For instance, I want the altitude to integrate it on a mathematical formula also to create Triangulated Irregular Network (tin).

**Comment by DenisCarriere** [comment]
Currently the `z` value is pulled from an attribute found in your GeoJSON Feature `properties`.

You would need to add this attribute to your `properties` before loading your features into `@turf/tin`.

http://turfjs.org/docs/#tin

**Comment by marie15** [comment]
I don't have this attribute. I'm not trying to load GeoJSON feature, I'm trying to draw set of points directly on map using Leaflet draw plugin and get their altitudes values.

**Comment by marie15** [comment]
I think I can use planepoint function to get z-value, but I can't understand what is "a", "b" and "c" parameters.

**Comment by DenisCarriere** [comment]
Please try to use the TurfJS issue system for Turf related issues and not Leaflet maps or custom built applications.

These types of questions might be better suited for [StackOverflow](stackoverflow.com).

**Comment by marie15** [comment]
I have already post this issue in stackoverflow but I didn't get any helpful answer. They tell me to augment behavior of leaflet with an external datasource, but I can't find any other api.
