### ISSUE TITLE
Modules to support z coordinate from geometry

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#628]
### Proposing

Enable modules that require having a `z` coordinate be able to retrieve this altitude data from the 3rd coordinate of the GeoJSON geometry `[x,y,z]`. The `z` param would still be available to retrieve the altitude from properties, however this would now be optional.

### Modules

List of modules that should be able to manipulate `z` coordinate directly from geometry.

- [x] [@turf/isobands](https://github.com/Turfjs/turf/pull/619)
- [x] [@turf/planepoint](https://github.com/Turfjs/turf/tree/master/packages/turf-planepoint)
- [ ] [@turf/tin](https://github.com/Turfjs/turf/tree/master/packages/turf-tin)
- [x] [@turf/isolines](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines)
- [ ] [@turf/idw](https://github.com/Turfjs/turf/tree/master/packages/turf-idw)
- [ ] Missed modules??

Any thoughts?

CC: @marie15 @morganherlocker @tmcw @stebogit @rowanwins

**Comment by marie15** [comment]
You didn"t miss any modules, nice. But my problem is I don't have z coordinate, so how can I get this coordinate?

**Comment by DenisCarriere** [comment]
@marie15 Z coordinates is defined by elevation/altitude, that would be retrieved from your own personal datasets, TurfJS won't be able to help you calculate datasets without this information.

**Comment by marie15** [comment]
As I said before I don't have this information, how can I get this
coordinate from latitude and longitude?
Thank you

2017-03-28 17:51 GMT+00:00 Denis <notifications@github.com>:

**Comment by morganherlocker** [comment]
@marie15 You will need to source this information yourself and implement your own method of querying the value at a coordinate. This is outside the scope of Turf, but I would do some web searching and check out datasets like those provided by [USGS](https://nationalmap.gov/elevation.html). This data is normally delivered in a bulk raster format like a [DEM](https://en.wikipedia.org/wiki/USGS_DEM), which is not the type of data that Turf is designed to handle.

**Comment by marie15** [comment]
I understood, thank you for clarification, I will do research about what
you suggested.

2017-04-05 0:48 GMT+00:00 Morgan Herlocker <notifications@github.com>:

**Comment by DenisCarriere** [comment]
Ref: https://github.com/Turfjs/turf/issues/628 https://github.com/Turfjs/turf/issues/2

**Comment by rowanwins** [comment]
My only general comment on this is that there are probably a stack of modules that simply override the coordinates that come in, discarding any data that may be within the 3rd position in the array.

**Comment by DenisCarriere** [comment]
Agreed, however if your data does contain [x,y,z] then this would be useful, both properties & the 3rd coordinate should work for these modules, so you can always fallback to GeoJSON properties if the data gets stripped.

**Comment by dpmcmlxxvi** [comment]
@DenisCarriere I looked over `@turf/idw` and it doesn't seem to use the z-coordinate as a parameter. It is assigning the output of the interpolation to a new property [`properties.z`](https://github.com/Turfjs/turf/blob/master/packages/turf-idw/index.js#L46). However, that doesn't seem to have anything to do with the z coordinate.

I think it is a bad property name. The value is not the z coordinate and the documentation states that the new property should be called `IDW`. So that appears to be a bug. Will add bug report if you agree. Fixing it would require renaming the output property name which wouldn't be backward compatible.

**Comment by DenisCarriere** [comment]
@dpmcmlxxvi 👍 sounds like a plan

**Comment by dpmcmlxxvi** [comment]
@DenisCarriere Unless there are other modules I think this can be closed. `tin` is done per #772 and `idw` doesn't apply per #774.
