### ISSUE TITLE
New module proposal `@turf/line-share`

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#638]
## New module proposal `@turf/line-share`

Returns a collection of intersecting lines that are mutually shared between two lines and/or polygons.

**Reason for module:** One step closer to removing `jsts` as a dependency ([`@turf/intersect` test -  linestring.geojson](https://github.com/Turfjs/turf/blob/master/packages/turf-intersect/test/in/linestring.geojson)) & used to detect if Inner polygons are sharing the same borders of outer polygons when applying `@turf/polygon-slice`.

### Valid input Geometry

- LineString
- MultiLineString
- Polygon
- MultiPolygon
- FeatureCollection

### JSDocs

```javascript
/**
 * @name lineShare
 * @param {FeatureCollection|Feature<LineString|Polygon|MultiLineString|MultiPolygon>} line1 any LineString or Polygon
 * @param {FeatureCollection|Feature<LineString|Polygon|MultiLineString|MultiPolygon>} line2 any LineString or Polygon
 * @returns {FeatureCollection<LineString>} intersecting lines that share borders between both features
**/
```

### Examples

- **Blue lines** (GeoJSON inputs)
- **Red lines** (intersections/line that share borders)

![image](https://cloud.githubusercontent.com/assets/550895/24584439/2b8cff84-173c-11e7-99bd-c60a51b17d98.png)

![image](https://cloud.githubusercontent.com/assets/550895/24584508/3f35a1a6-173e-11e7-81a9-ed35a1431429.png)

Any thoughts?

CC: @rowanwins

**Comment by rowanwins** [comment]
Nice work @DenisCarriere , I imagine this could be handy in a number of cases (although none of them come to me right now!), I'll get it added into the docs when it gets merged in.

Re removing JSTS the [martinez](https://github.com/w8r/martinez) repo got an update the other day so it's more stable than it used to be (although don't look at the online demo as that hasn't been updated) so it's a contender for modules like intersection, union, difference, xor.

**Comment by DenisCarriere** [comment]
👍 Thanks for your feedback @rowanwins , this module might be slightly on the abstract side, however one scenario that comes to mind is:
- Detecting if one road overlaps another roads (JOSM warning - **Overlapping highways**)

**Comment by DenisCarriere** [comment]
Really cool! The martinez library looks pretty solid (from the readme)
