### ISSUE TITLE
Major Release Turf v4.0

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#642]
# Major Release Turf v4.0

## New Modules

- `@turf/line-split` https://github.com/Turfjs/turf/pull/634 Split a LineString by another GeoJSON Feature.

## Major changes

- `@turf/helpers` Update earth radius https://github.com/Turfjs/turf/issues/635 (heavily changes `@turf/distance` calculation results)

## Minor changes

- `@turf/truncate` Handle precision=0 https://github.com/Turfjs/turf/pull/641
- `@turf/line-segment` Add id/index https://github.com/Turfjs/turf/pull/633
- `@turf/line-segment` Add `bbox` https://github.com/Turfjs/turf/pull/632
- `@turf/line-segment` Issue with Polygons with holes https://github.com/Turfjs/turf/issues/629

CC: @Turfjs/ownership

**Comment by mourner** [comment]
Do you know why a few packages did not get a version bump? Specifically `intersect`, `planepoint`, `random`, `simplify` and `union` are still on v3.14.0.

**Comment by DenisCarriere** [comment]
All of these libraries weren't affected by the `@turf/helpers` & `@turf/distance` changes.

I didn't include `--force-publish` when publishing with Lerna, makes sense for a Major release to have every package updated.

Just published a patch for those libraries.

```
$ lerna publish --force-publish="@turf/union,@turf/simplify,@turf/random,@turf/planepoint,@turf/intersect"
```
