### ISSUE TITLE
Feature request: finding tangents to polygon from a point

### ISSUE THREAD

**Issue by dhivehi** [Turfjs/turf#648]
It would be very useful to have a feature to find two possible tangents from a point to polygon.
![polytangents](https://cloud.githubusercontent.com/assets/18715293/24792727/9edf790c-1b98-11e7-8afb-a5e7d3bbbc47.png)

**Comment by rowanwins** [comment]
Hi @dhivehi 

Are you aware of any algorithms that exist that could be used for this calculation?

Cheers

**Comment by rowanwins** [comment]
This page might provide some good guidance
http://geomalgorithms.com/a15-_tangents.html

**Comment by dhivehi** [comment]
The only algorithms i found is from this link http://geomalgorithms.com/a15-_tangents.html
But I donno how to write it in js

**Comment by rowanwins** [comment]
Got a first cut of this functioning, just writing up some tests before I send through the pull request.

**Comment by rowanwins** [comment]
Now available
