### ISSUE TITLE
Deprecate module @turf/polygon-unkink

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#654]
Noticing a lot of issues with `@turf/polygon-unkink`.

- Not handling complex polygons.
https://github.com/Turfjs/turf/blob/master/packages/turf-unkink-polygon/test/out/complex.geojson

![image](https://cloud.githubusercontent.com/assets/550895/24841038/a28d73a4-1d48-11e7-8b78-3c948fdb44d2.png)

- Polygon with holes (holes get converted to outers)
https://github.com/Turfjs/turf/blob/master/packages/turf-unkink-polygon/test/out/polygon-with-holes.geojson

![image](https://cloud.githubusercontent.com/assets/550895/24841044/b66df1fa-1d48-11e7-8812-4f2cf20fc97a.png)

CC: @rowanwins

**Comment by rowanwins** [comment]
Yeah it does seem to be causing a few issues so I'm happy if we deprecate it for the timebeing. 

That said it doesn't have to be 100% perfect to at least be somewhat useful. For example if we weren't handling that top case I wouldn't be that sad, that's an extremely bad poly. But we should be handling that poly with hole example.

**Comment by DenisCarriere** [comment]
I would still prefer to keep `@turf/unkink-polygon`, however it's not really doing it's job at the moment if it can't handle complex shapes or polygons with holes. Definitely need more tweaking around to make it work.

**Comment by amenadiel** [comment]
It would sad news indeed. I use unkink polygon to repair the rings that would result from using google.maps directions API. You know, the routes  loop over themselves at several points, so when I try to get the contained surface I have to unkink the resulting polygon, then return the union of the resulting featurecollection.

I used to be able to do this with a buffer, but now it complains about self intersections either for positive or negative distances.

**Comment by DenisCarriere** [comment]
@amenadiel Thanks for your concerns, however this module got fixed by the Author and no longer has issues, we are going to be keeping this module.

Going to close this issue since it's no longer "true"
