### ISSUE TITLE
reverse

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#66]
function to reverse all rings in a polygon feature.

**Comment by tchannel** [comment]
@morganherlocker is the goal to reverse all rings or put all rings in the appropriate winding order for canvas etc? (or do we want a module for each?)

if we want to just reverse rings we could build something using turf-meta

**Comment by AbelVM** [comment]
This evening (GMT+1), you will have a tiny module for this :)

**Comment by AbelVM** [comment]
Done. No external dependences.

Check: https://github.com/Turfjs/turf-rewind

**Comment by DenisCarriere** [comment]
Going to be released in TurfJS v4.3
