### ISSUE TITLE
`degreesToDistance` different for Latitude and Longitude

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#684]
Looking at `@turf/helpers` `distanceToRadians` and `distanceToDegrees` methods I noticed that if you move a point E-W or N-S of the same amount of degrees and calculate the distance between the original point and the moved point, you actually get two different distances.
Is that for some reason correct?
If so, why? 
Then, how could you create for example a square from a `point' that actually looks like a square? Using `@turf/bearing`, due to #681, at 90˚ the end points are not at the same latitude, while varying the coordinates you don't get a square:

![screen shot 2017-04-22 at 12 14 46 am](https://cloud.githubusercontent.com/assets/12717225/25302428/a08e966a-26f2-11e7-9117-4e8c828bb98a.png)

I added also some [test on `@turf/helpers`](https://github.com/Turfjs/turf/commit/709eff00c1de771c39b04932ab5c55f93d60a6ee) to highlight the issue.

**Comment by DenisCarriere** [comment]
## Web Mercator

>  if you move a point E-W or N-S of the same amount of degrees and calculate the distance between the original point and the moved point, you actually get two different distances.

The Leaflet map you have in the background is using [Web Mercator projection](https://en.wikipedia.org/wiki/Web_Mercator) which is an equidistance projection (distances are equal only in meters NOT degrees).

Because of the earth's curvature, calculating the distance of 1 degree North does NOT equal 1 degree West. The map you are showing is **accurate** to represent those points the way they are. 

If you decided to visualize the same thing using a Geodetic map projection ([WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System)) then those two points will "look" like they have an equal distance.

## Square

> how could you create for example a square from a point' that actually looks like a square?

I don't think using `@turf/bearing` would be the appropriate tool to create a square. You could convert your [LatLng coordinates to Meters](https://github.com/DenisCarriere/global-mercator#lnglattometers), apply your distance calculations to get your 4 corners and then convert your 4 coordinates back [Meters to LatLng](https://github.com/DenisCarriere/global-mercator#meterstolnglat).

**Comment by DenisCarriere** [comment]
Going to close this issue, however feel free to continue the discussion if you have more questions/comments.

**Comment by stebogit** [comment]
@DenisCarriere so the output of `@turf/point-grid`, which creates new points by coordinates (i.e. degrees right?), if represented on a Geodetic map would not result to be a square?
In fact the [`xFactor` and the `yFactor`](https://github.com/Turfjs/turf/blob/distance-conversion/packages/turf-point-grid/index.js#L38-L41) used to generate new points are different.

**Comment by DenisCarriere** [comment]
Those tests are not really failing, it's just a precision issue, converting degrees to meters and meters back to degrees will have some very minor different decimals (< 10cm).

Also the distance measurement of `0.5` degree from West to East is NOT the same distance as `0.5` degree from South to North at based on the given latitude.

The higher/lower in latitude, the greater the distortion (curvature of the earth).

## Solution

You might want to consider using [`cheap-ruler`](https://github.com/mapbox/cheap-ruler) and add an extra `latitude` param, this library is only intended for city scale distance measurements (not across oceans). We can bring this up as it's own separate issue (would require a major version change to `@turf/distance`).

## Tests Failing

https://github.com/Turfjs/turf/commit/709eff00c1de771c39b04932ab5c55f93d60a6ee#diff-53d607b71ed5b9cdaec1b6400fb83a8eR327

```javascript
const dx = distance(point([-120, 47]), point([-120.5, 47]));
const dy = distance(point([-120, 47]), point([-120, 47.5]));

t.equal(distanceToDegrees(dx), .5, 'degrees conversion fails');
//=0.34099
t.equal(distanceToDegrees(dy), .5, 'degrees conversion fails');
//=0.5
```

```
# distanceToDegrees
not ok 51 degrees conversion fails
  ---
    operator: equal
    expected: 0.5
    actual:   0.34099872320736135
    at: Test.t (/home/travis/build/Turfjs/turf/packages/turf-helpers/test.js:327:7)
  ...
not ok 52 degrees conversion fails
  ---
    operator: equal
    expected: 0.5
    actual:   0.5000001787820836
    at: Test.t (/home/travis/build/Turfjs/turf/packages/turf-helpers/test.js:328:7)
```

## Test Passing with latitude 0

```
const dx = distance(point([-120, 0]), point([-120.5, 0]));
const dy = distance(point([-120, 0]), point([-120, 0.5]));
```

**Comment by stebogit** [comment]
@DenisCarriere I'm still not sure about the result of the function.
If we assume the earth is a sphere (do we?) then any variation in degrees on a meridian (North-South) should correspond to an equal distance, as meridians are always equals circles. However the distance between two meridians (East-West variations in degrees) should actually depend on the latitude, as parallels are circles with different radii (smaller at higher latitudes).   
Therefore I'd say the conversion `distanceToDegrees` (and also `degreesToDistance`) should actually depend on the latitude as well, i.e. it should have it as input.
Otherwise the output of these `turf-helpers` functions is only valid at 0 latitude (like [the modified test](https://github.com/Turfjs/turf/commit/fd299ad20cecb3ad07d6b7192a302d9ffc98f568#diff-53d607b71ed5b9cdaec1b6400fb83a8eR314)) or for North-South variations.
I added few [tests](https://github.com/Turfjs/turf/commit/3bcd573568a3dc8b0d2b0e736f8272d0af2687b6) in `turf-distance` to support this.

Any thoughts?

**Comment by DenisCarriere** [comment]
@stebogit Totally agree that including a latitude as parameter is a must to calculate the distance properly (distances that span large areas will have distortions).

👍 Including a new `latitude` param with default value of `0`, that way there should be no issues with backwards compatibility (future major releases could be changed to a required param).

**Comment by DenisCarriere** [comment]
I don't remember if I've had this conversation with someone before, but why aren't we using [`@mapbox/cheap-ruler`](https://github.com/mapbox/cheap-ruler) in Turf?

@mourner Any objections to this?

**Comment by stebogit** [comment]
@DenisCarriere 👍  
Meanwhile should we maybe create a `bug` issue for `degreesToDistance` and `distanceToDegrees` to point out this unexpected behaviour to users?

**Comment by DenisCarriere** [comment]
Yep, we can reopen this issue and tag it as a bug.

**Comment by stebogit** [comment]
@DenisCarriere I believe the issue here is just the name of the function(s), and also some confusion on my side.
The concept of *distance*, by [definition](https://en.wikipedia.org/wiki/Distance), implies the presence of two points, while here `distanceToDegrees`, `distanceToRadians` and `radiansToDistance` simply convert a *length* (on a sphere) to a different unit of measurement.
In fact we are just passing to the functions a length (not two points), and the result of the conversion (like any unit conversion) does not depend on the position on the surface.

What causes confusion (at least to me, sorry) is the name of the functions and the fact that in the additional test I added I was actually measuring a distance (in fact using `turf-distance`) between two points, apart of a certain angle in degrees, and I was expecting *the conversion* to give me back the result in degrees. In this case though the distance between two points (along the geodesics of the spherical Earth) does depend on the latitude, but not necessarily the conversion of its length in degrees (that is true only on meridians or the equator).
Also, my bad, there is no `degreesToDistance` function, because that would actually be `turf-distance`.

Therefore the values returned by the functions under discussion are correct, but I would strongly suggest (in the next major release) to change the names for example to `lengthToDegrees`, `lengthToRadians` and `radiansToLength`.

What do you think?

While I was thinking about this whole thing and trying to understand the issue I [modified `turf-helpers`](https://github.com/Turfjs/turf/commit/f978a1fcc6174ab2103fac0be4b82f7b93063b3b) and added `radians2degrees` and `degrees2radians` which I found useful.
Let me know if you'd like me to create a PR for that.

cc: @mourner @rowanwins

**Comment by stebogit** [comment]
@DenisCarriere any thoughts on the conversion to `lengthToDegrees`, `lengthToRadians` and `radiansToLength` on a future major release?
I'd remove the bug label here btw.

**Comment by DenisCarriere** [comment]
@stebogit I'm 👍 with the method renaming, pretty sure these methods are only used internally. We can include these changes in v5.0 and update the `earthRadiusIn` factor at the same time.

**Comment by guanzo** [comment]
Hey guys i tried to follow this conversation but geospatial discussion goes over my head :/. If I had a lat/lng pair and wanted to offset the position by 1 mile in any direction, which function should i use? I need to convert 1 mile to the appropriate degrees.

**Comment by stebogit** [comment]
@guanzo if you have just a point you can use [`@turf/destination`](http://turfjs.org/docs/#destination)
```js
var pt = turf.point([lng, lat]); // note the order
var destinationPoint = turf.destination(pt, 1, yourAngle, 'miles');
```

**Comment by stebogit** [comment]
- `lengthToDegrees`, `lengthToRadians` and `radiansToLength` renamed in #1055
- `earthRadius` converted with #1012

**Comment by Gefyaqiilah** [comment]
@stebogit  can you tellme how you create a line with arrow like that ?

**Comment by stebogit** [comment]
@Gefyaqiilah I just edited a screenshot with Preview on Mac, nothing done with turf
