### ISSUE TITLE
Add mutate param @turf/flip

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#693]
This issue is opened for reference purposes.

## Added `mutate` param to [`@turf/flip`](https://github.com/Turfjs/turf/tree/master/packages/turf-flip)

Allows the ability to mutate geojson input in place, significantly increases performance (60x) if `mutate=true`. This behavior will be similar to [`Array.prototype.reverse()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse).

```javascript
var geojson = point([120, 40])

flip(geojson)
//= Does NOT mutate geojson => point([120, 40])

flip(geojson, true)
//= Does mutate geojson => point([40, 120])
```

Added via commit https://github.com/Turfjs/turf/commit/63df660bd1d5b7c9e37046ca24fbb966bc0d3630

**Comment by mourner** [comment]
Hmm, I thought @morganherlocker was against any mutating Turf functions...

**Comment by DenisCarriere** [comment]
By default this is off (does not mutate), one would need to explicitly define `mutate=true`.

There's only a few modules (2-3 so far) that this will be a available as an option. There could be scenarios where you need to apply multiple mutating methods but you wouldn't want to apply JSON.parse() every time.

@morganherlocker I'm open to any direction
