### ISSUE TITLE
Validation - Minimum 2 points in lineString `@turf/helper`

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#695]
[GeoJSON spec of LineString](http://geojson.org/geojson-spec.html#linestring) & [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.1.4)
> For type "LineString", the "coordinates" member must be an array of two or more positions.

Should we throw an error with [`lineString()`](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js#L125-L132) to reflect this GeoJSON spec.

Similar validation as [`point()`](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js#L47).

**Proposed Change:**
```javascript
if (coordinates.length < 2) {
  throw new Error('coordinates must be an array of two or more positions.');
}
```

This might be a bit disruptive for backwards compatibility and should only be implemented in the next Major release.

@morganherlocker @rowanwins @stebogit @mourner thoughts?

**Comment by rowanwins** [comment]
Yeah I'd agree that it makes sense to have this validate against the spec. And agree that it it might break backwards compatibility so Im happy if it only get included in the next major release.

**Comment by DenisCarriere** [comment]
Validation added when major release (v5.0) is published.
