### ISSUE TITLE
inside: expose ignoreBoundary in API

### ISSUE THREAD

**Issue by dpmcmlxxvi** [Turfjs/turf#699]
The current implementation of `@turf/inside` returns true if the point is on the boundary (see [jsfiddle](https://jsfiddle.net/dk5w6qsn/)). It would be helpful to be able to exclude the boundary.

The fix seems simple enough by exposing `ignoreBoundary` and passing it to `inRing` and inverting it when passing it to the inner rings. Can submit a PR if desired.

Not sure if the current behavior was intended but the term **inside** in the [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) sense does not include the boundary.

Changing the default behavior would break backward compatibility but if including DE-9IM functionality is a longer term goal it might be worth changing it in the next major release.

**Comment by rowanwins** [comment]
Gday @dpmcmlxxvi 

I've just started work on a set of DE-9IM boolean operations so stay tuned for those, they are still a little while off but hopefully in the next month you'll see something.

In regards to extending the current `@turf/inside` I'd be supportive, I'd suggest it could be an optional parameter which may not break anything in terms of compatability. Thoughts @DenisCarriere ?

Cheers
Rowan

**Comment by DenisCarriere** [comment]
👍 Adding an extra param for `ignoreBoundary`, @dpmcmlxxvi feel free to send over a PR with your proposed solution.
