### ISSUE TITLE
smooth for polygons

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#70]
Uses the bezier curve algo on all arcs within a polygon or set of polygons, then transforms the results into valid topology.

**Comment by andrewharvey** [comment]
@MarkItzero added a PR at https://github.com/turf-junkyard/turf-bezier/pull/7 which looks like it's trying to solve the same problem as this.

**Comment by stebogit** [comment]
Implemented with [`@turf/bezier`](https://github.com/Turfjs/turf/tree/master/packages/turf-bezier)

Ref #582, #360 and [`turf-junkyard/turf-bezier#7`](https://github.com/turf-junkyard/turf-bezier/pull/7)

**Comment by andrewharvey** [comment]
@stebogit I'm not sure I understand why this was closed, https://github.com/Turfjs/turf/tree/master/packages/turf-bezier still says "Takes a line".

**Comment by stebogit** [comment]
@andrewharvey you're right, my bad, I didn't notice this was actually referring to polygons! Sorry

**Comment by dhivehi** [comment]
Hope this might be helpful: http://viglino.github.io/ol3-ext/examples/map.geom.cspline.html

**Comment by DenisCarriere** [comment]
👍 Very cool example @dhivehi Thanks for sharing

**Comment by rowanwins** [comment]
Implemented by #1077
