### ISSUE TITLE
Add turf-is-clockwise to @turf mono repo

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#701]
Add [turf-is-clockwise](https://github.com/Turfjs/turf-is-clockwise) to Turf mono repo.

Might be worth starting a `boolean` category of modules, we could name this module as `@turf/boolean-clockwise` and it could be integrated in a future parent module `@turf/boolean`.

## Support Inputs

- Feature LineString
- Geometry Object LineString
- LineString Coordinates `Array<Array<number>>`

@morganherlocker Thanks for the initial work done 3 years ago 👍

**Comment by stebogit** [comment]
Added with PR #789
