### ISSUE TITLE
Getting error while finding intersection between a multipolygon and a polygon

### ISSUE THREAD

**Issue by amishas157** [Turfjs/turf#702]
I am getting following error while finding intersection between a multipolygon and a polygon:

```
/Users/AmishaSingla/Documents/node_modules/turf-intersect/node_modules/jsts/dist/jsts.min.js:14
this.resultGeom=this.computeGeometry(this.resultPointList,this.resultLineList,this.resultPolyList,t)},labelIncompleteNode:function(t,e){var n=this.ptLocator.locate(t.getCoordinate(),this.arg[e].getGeometry());t.getLabel().setLocation(e,n)},copyPoints:function(t){for(var e=this.arg[t].getNodeIterator();e.hasNext();){var n=e.next(),i=this.graph.addNode(n.getCoordinate());i.setLabel(t,n.getLabel().getLocation(t))}},findResultAreaEdges:function(t){for(var e=this.graph.getEdgeEnds().iterator();e.hasNext();){var n=e.next(),i=n.getLabel();i.isArea()&&!n.isInteriorAreaEdge()&&ii.isResultOfOp(i.getLocation(0,cn.RIGHT),i.getLocation(1,cn.RIGHT),t)&&n.setInResult(!0)}},computeLabelsFromDepths:function(){for(var t=this.edgeList.iterator();t.hasNext();){var e=t.next(),n=e.getLabel(),i=e.getDepth();if(!i.isNull()){i.normalize();for(var r=0;2>r;r++)n.isNull(r)||!n.isArea()||i.isNull(r)||(0===i.getDelta(r)?n.toLine(r):(f.isTrue(
```

The two polygons are : 
  - https://gist.github.com/amishas157/b7604c9021c0b49ec8c3dd237d4b0a80
  - https://gist.github.com/amishas157/21f43cbbdad585839ee0b155fb5defd0

Source Code:
https://jsfiddle.net/ob0b6w0g/1/

Looks like something is wrong with Multipolygon.

**Comment by rowanwins** [comment]
Hi @amishas157 

Yes this is a known issue, unfortunately `JSTS` (on which the @turf/intersect module relies) does not handle MultiPolygons very well. We're currently working on a replacement which is hopefully only a few weeks away.

Cheers
Rowan

**Comment by DenisCarriere** [comment]
👍 @amishas157 Thanks reporting this, will be sure to include these test fixtures in the next `@turf/intersect`.

**Comment by amishas157** [comment]
Thanks @rowanwins and @DenisCarriere for taking care of this. 🙇‍♀️

**Comment by DenisCarriere** [comment]
Fixed in the latest PR
