### ISSUE TITLE
Explain bearingToAngle

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#703]
Question from @cbeddow:

Can you explain `bearingToAngle` to me some more? `Converts any bearing angle from the north line direction (positive clockwise) and returns an angle between 0-360 degrees (positive clockwise), 0 being the north line` - it says it takes a number as input, but to me sounds like it's trying to say NNW will be converted to a number?

@stebogit Can you elaborate on this?

**Comment by DenisCarriere** [comment]
From my understanding it was a helper function that will convert your bearings +/- 180 with negative values to 0-360 positive values. (ex: East, 90 => 90, West -90 => 270)

**Comment by stebogit** [comment]
@DenisCarriere 
> From my understanding it was a helper function that will convert your bearings +/- 180 with negative values to 0-360 positive values. (ex: East, 90 => 90, West -90 => 270)

Correct. It is also for instance:
East, 410 => 50, West -395 => 325

I guess your example makes it much more clear 😅

**Comment by cbeddow** [comment]
Okay I understand now! Quick converts it. Thanks!

**Comment by DenisCarriere** [comment]
Yes very simple quick conversion, this type of method is basic however it seems to repeat itself MANY times in all sorts of different repos.
