### ISSUE TITLE
near

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#71]
a function that returns all points within a certain distance of another set of points.

To find trees near houses, assuming both were point collections, you would do:

```js
t.near(houses, trees, 1, 'mile', function(err, closeTrees){
  console.log(closeTrees)
})
```

**Comment by tchannel** [comment]
Do we need anything more than buffer + within, or is there benefit in optimizing it more? I threw together a quick sample using the buffer+within approach [here](http://turfjs.party/#/494251fc26892cc48dee)

**Comment by tmcw** [comment]
Same as #180 and the answer's the same - this is something you can implement with sorting by distance.
