### ISSUE TITLE
New module proposal - Rhumb line

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#714]
# New module proposal - Rhumb Line

Variations of Rhumb Line implementations.

- `@turf/rhumb-bearing`
- `@turf/rhumb-destination`
- `@turf/rhumb-distance`

![image](https://cloud.githubusercontent.com/assets/550895/25773667/9479b450-324f-11e7-8947-ec289f5a27d3.png)

## `@turf/rhumb-destination`

Similar to [`@turf/destination`](https://github.com/Turfjs/turf/blob/master/packages/turf-destination/index.js), however instead of using the Haversine formula it uses the Rhumb Line path. Can be implemented using [`rhumbDestinationPoint` from `geodesy`](https://github.com/chrisveness/geodesy).

## `@turf/rhumb-bearing`

Similar to [`@turf/bearing`](https://github.com/Turfjs/turf/blob/master/packages/turf-bearing/index.js), however instead of using the Haversine formula it uses the Rhumb Line path. Can be implemented using [`rhumbBearingTo ` from `geodesy`](https://github.com/chrisveness/geodesy).

## `@turf/rhumb-distance`

Similar to [`@turf/distance`](https://github.com/Turfjs/turf/blob/master/packages/turf-distance/index.js), however instead of using the Haversine formula it uses the Rhumb Line path. Can be implemented using [`rhumbDistanceTo ` from `geodesy`](https://github.com/chrisveness/geodesy).

![image](https://cloud.githubusercontent.com/assets/550895/25774118/8a5bf318-3257-11e7-9e77-4cb35efd677d.png)

CC: @stebogit 
Ref: https://github.com/Turfjs/turf/issues/681 https://github.com/Turfjs/turf/issues/684

**Comment by stebogit** [comment]
@DenisCarriere I'm gonna work on this. 
Should I create a branch for each module, or just one is ok?

**Comment by DenisCarriere** [comment]
They seem pretty easy to implement, one branch should be good enough.

**Comment by stebogit** [comment]
Implemented with PR #728
