### ISSUE TITLE
isoband

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#72]
An alternative to the contours algorithm (it may replace it). This will add a few features to the algo, such as dealing with holes, grid artifacts, and other issues with the conrec algo. Basic steps:
1. use square function to get a bbox around the points
2. size x 1.1
3. create a grid using the bbox
4. sum or average point's z value within grid cells 
5. group cells by break level
6. foreach group, buffer slightly
7. foreach group, perform a union
8. smooth all polygons
9. perform a cascading clip from high to low; this corrects overlaps from buffering and smoothing

**Comment by StefanoGitHub** [comment]
Hi @morganherlocker,
I implemented my `isoband` function using `MarchingSquaresJS.js` and the contouring works just fine.
However occasionally I'm seeing some overlapping issues in the final data layer (I'm rendering the contour on a Google Map).
Would you mind considering a PR on the turf isoband module and have a look to my solution?
I believe the issue might be in the MarchingSquares algorithm, though.

Thanks
