### ISSUE TITLE
pointOnLine.location does not return correct distance

### ISSUE THREAD

**Issue by Andi-Lo** [Turfjs/turf#722]
I currently wonder if the @turf/pointOnLine package does return a wrong location value. 
Here is a short fiddle of the problem:

http://jsfiddle.net/andi_lo/95q4Lgqc/

I would like to set a point (which is a train station in my project) onto the polyline (representing the routes shape) via `turf.pointOnLine` and use the returning location property as of how far the train traveled. However if I use turf.along with the distance provided by `turf.pointOnLine(...).properties.location` I will get a point that does not match my expectations. I would expect to get a point that lays onto the station but I get a point that is positioned falsely.

![turf_pointonline](https://cloud.githubusercontent.com/assets/7545568/25802370/5ac2c874-33f2-11e7-89b6-f7c0e6e9512b.jpg)

The used geojson is inside the fiddle. Feel free to ask for clarification if needed.

**Comment by DenisCarriere** [comment]
@Andi-Lo Thanks for reporting this issue. I've managed to get the result closer to the station point by applying `reverse()` to the LineString's coordinates, however it's still a bit off, one would assume that doing `pointOnLine`+ `along` would result in nearly the same location.

We should try to replicate this behavior in the TurfJS tests.

## Example - `reverse()`

```javascript
lineString.features[0].geometry.coordinates.reverse();
```
![image](https://cloud.githubusercontent.com/assets/550895/25817242/be7611e4-33f4-11e7-89b1-10025d8b26fe.png)

**Comment by DenisCarriere** [comment]
Related To-Do on `@turf/along`: https://github.com/Turfjs/turf/issues/691

**Comment by Andi-Lo** [comment]
Thanks for reply,

until it is fixed I will use a workaround (measuring all sub-segments with turfs lineDistance module)

**Comment by DenisCarriere** [comment]
@Andi-Lo Feel free to send a PR if you do find a solution for the `@turf/point-on-line` issue you mentioned.

**Comment by dpmcmlxxvi** [comment]
@Andi-Lo Can you double check that this is resolved with PR #750 so the issue can be closed?

**Comment by Andi-Lo** [comment]
@dpmcmlxxvi not sure how to validate.

I would need to checkout the turf master branch and get myself a bundled turf.min.js file and include that in my project to see if results are not as expected or is there a faster way?

**Comment by dpmcmlxxvi** [comment]
@Andi-Lo That's what I do. Check out, install, and build. Then you can use `packages/turf/turf.min.js`. Not sure if there is a nightly build of the master branch built somewhere online. Maybe @DenisCarriere would know.

**Comment by DenisCarriere** [comment]
There isn't any nightly builds, however it might be a good idea. The process would need to be automated and be based on the master branch.

**Comment by Andi-Lo** [comment]
With the latest release I updated the version of my fiddle:

https://jsfiddle.net/andi_lo/95q4Lgqc/

As you can see the result seems now correct to me. Nice work @dpmcmlxxvi !

**Comment by DenisCarriere** [comment]
👍 Glad that it works, definitely nice work from @dpmcmlxxvi
