### ISSUE TITLE
Update changelog for v4.0.0

### ISSUE THREAD

**Issue by Tapppi** [Turfjs/turf#733]
What is the changelog for v4.0.0? Cannot find it anywhere.

**Comment by DenisCarriere** [comment]
Unfortunately I've only been tracking changes from v4.0.0 and above (previous to v4.0.0 is not very clear).
- To see compact release descriptions:  https://github.com/Turfjs/turf/issues?q=is%3Aissue+label%3Arelease+is%3Aclosed
- To see all Issues & PR: https://github.com/Turfjs/turf/milestones?state=closed

**Comment by Tapppi** [comment]
So what is the breaking change that forced v4.0.0? There is no Note of that anywhere..

**Comment by DenisCarriere** [comment]
Oh I remember now, it was the attempt to change the "earth radius" (which required a major release), however this has been reverted and no longer caused any breaking changes.

You can more read more here: https://github.com/Turfjs/turf/issues/635#issuecomment-290489207

**Comment by Tapppi** [comment]
Thank you. Even reverted Major changes should be in a changelog. Not telling the reason there causes unnecessary friction. We do auto generated changelog tooling in `conventional-commit` if you are interested. Great work with turf otherwise. Still the best lib to use even if I don't really like geojson 😉

**Comment by rowanwins** [comment]
Gday @Tapppi 

Thanks for the positive feedback and yep agreed we could do more in way of change logs, unfortunately turf is mostly a labour of love conducted after hours and so things slip through the cracks, an automated approach sounds great!

Cheers
