### ISSUE TITLE
Add bbox-clip to turfjs-builder.herokuapp.com

### ISSUE THREAD

**Issue by waissbluth** [Turfjs/turf#738]
I don't know if this is the correct place to post this, but how can I generate a custom build to use `turf-bbox-clip`, given that turfjs-builder.herokuapp.com does not have that option?

How does one use `npm install` to create a distributable js file?

Thanks

**Comment by DenisCarriere** [comment]
This is outside the scope of TurfJS and mostly a Javascript bundling question:

Here's a few resources that can help you:
- [Browserify](http://browserify.org/) ([TurfJS currently uses this](https://github.com/Turfjs/turf/blob/master/packages/turf/package.json#L17))
- [Webpack](https://webpack.github.io/)
- [Rollup](https://rollupjs.org/)

Pick your flavor, all of these are widely adopted in the Javascript community.

**Comment by rowanwins** [comment]
Gday @waissbluth 

Turf builder is my project that I don't really maintain much sorry, that said I'll try and get it updated. 

There are also some instructions in the [turf doco](http://turfjs.org/getting-started/) which explain how to create your own bundled file, see the bottom of the page for the section **'Creating custom builds for use in the browser'** (turf builder is pretty much following this process)
