### ISSUE TITLE
Add turf-is-clockwise to core modules as @turf/boolean-clockwise

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#740]
Noticed we are using [`turf-is-clockwise`](https://github.com/Turfjs/turf-is-clockwise) as a dependency in [`@turf/rewind`](https://github.com/Turfjs/turf/tree/master/packages/turf-rewind), might be worth including this as a core TurfJS module as `@turf/boolean-clockwise` as part of the "boolean" themed modules.

Ref: https://github.com/Turfjs/turf-is-clockwise
CC: @rowanwins (will most likely be useful in some of the DE-9IM modules)

**Comment by stebogit** [comment]
Implemented in PR #789
