### ISSUE TITLE
@turf/dissolve doesn't completely dissolve all geometries

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#742]
Notice in the example below the two strangling polygons, whenever a geometry is completely within the dissolved outer ring some geometries seem to be excluded.

@rowanwins With many recent changes, we might want to revisit the source code for [`@turf/dissolve`](https://github.com/Turfjs/turf/blob/master/packages/turf-dissolve/index.js).

**Buffered points**
https://gist.github.com/490c0e00536ecc3ef1c98b74c40d2c29

![image](https://cloud.githubusercontent.com/assets/550895/26029213/25cc50bc-37fe-11e7-994f-5d566b6da482.png)

**Dissolved points**
https://gist.github.com/7ad5ef7316f2a0a4a2578e9696902886
![image](https://cloud.githubusercontent.com/assets/550895/26029229/4da6d9ea-37fe-11e7-82b8-ef52caca269c.png)

**Comment by rowanwins** [comment]
Roger that @DenisCarriere, I'll take a look

**Comment by andrewharvey** [comment]
@DenisCarriere did you want to try this again with dissolve from v7 alpha? I had a similar issue which was fixed in v7.
