### ISSUE TITLE
turf.featureCollection() cannot Determine whether Parameter isn't Array

### ISSUE THREAD

**Issue by brianbancroft** [Turfjs/turf#751]
Hi there, 

I've found a bit of an issue with your `turf.featureCollection()` function with regards to inputs, and I'd like to share as it might be a heartache for beginners of your library. It was for me.

## Setup
I'm currently trying determine the number of points within a radius of another point in a node environment where I chain a `turf.featureCollection()` to a `turf.buffer()` function. When  I do this, my output is not compliant with the geojson spec, and any attempt at carrying out the `turf.within()` function gets me zero, even though one of the compare points is the point used to generate the buffer.  Here is some setup, if someone wishes to replicate: 

- In my `package.json` file, the version I'm using is current, I believe. `"@turf/turf": "^4.1.0"
- Here is a [single point](https://gist.github.com/brianbancroft/dcfdb8a04e6637ac451059c00e3716e5). 

The remainder of this example takes place in the node repl. Go to a node project with turf. 
From the shell:
```shell
mkdir jsontest && cd jsontest
yarn init
(...)
yarn add @turf/turf
node
```

```javascript
const turf = require('@turf/turf')
const point = {"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[-79.419281,43.795368]}}
// using a silly buffer for now
const buffer = turf.buffer(point, 1000, 'kilometers')
const bufferCollection = turf.featuresCollection(buffer)
```
[Here is the output](https://gist.github.com/brianbancroft/4c2e94486f2fa7812c076acffec79a5a). 

## The actual problem
When I look at the docs for [`featureCollection`](http://turfjs.org/docs/#featurecollection), I find that the desired input is an array, but in my case, I'm laying down an object. But instead of offering a warning or throwing an error, It just carries on producing faulty geoJSON without warning.

## Possible solution

The solution may be as easy as either forcing an array if the parameter is a geojson feature, or throwing an error in [line 150](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js) if the parameter isn't array. Would using the [`Array.isArray(arr)`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray?v=example) fit the bill as a condition to throw an exception? Just in case, here's a [compatability table](http://kangax.github.io/compat-table/es5/#test-Array.isArray) for the JS method.

Thanks for building and maintaining such a lovely library! If you think this is a solution to the problem I have, I would love to contribute.

**Comment by dpmcmlxxvi** [comment]
Why not just call `turf.featureCollection` with an array as the documentation describes?

    const bufferCollection = turf.featuresCollection([buffer])

While there could be an additional validation performed but IMHO I think a function building a collection would clearly expect an array as input and not a single object. Maybe others could chime in and if there's enough support it could be added.

**Comment by DenisCarriere** [comment]
👍 @brianbancroft Thanks for reporting this, I've also ran into this problem when I would accidentally add a FeatureCollection with another FeatureCollection.

**Added input validation**
```javascript
if (!Array.isArray(features)) throw new Error('features must be an Array');
```
