### ISSUE TITLE
Add properties param to @turf/centroid

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#755]
Allow properties from GeoJSON input or properties param to be translated down to point.

End state would be to do the following:

```javascript
centroid(geojson, {'marker-symbol': 'circle'})
```

Other related modules to apply properties param:
- [x] [`@turf/centroid`](https://github.com/Turfjs/turf/tree/master/packages/turf-centroid)
- [x] [`@turf/center`](https://github.com/Turfjs/turf/tree/master/packages/turf-center)
- [x] [`@turf/center-of-mass`](https://github.com/Turfjs/turf/tree/master/packages/turf-center-of-mass)

**Comment by stebogit** [comment]
@DenisCarriere I noticed this issue when working on `transform-scale`! 👍 
I'll submit a PR with the fix.

**Comment by DenisCarriere** [comment]
Fixed in https://github.com/Turfjs/turf/pull/769
