### ISSUE TITLE
eslint fails on types.js

### ISSUE THREAD

**Issue by dpmcmlxxvi** [Turfjs/turf#761]
## Issue
When `npm test` is run twice from the root directory the linter fails on the generated `types.js` files on the second run. Multiple errors of the following form:
```shell
  1:1   error  Strings must use singlequote         quotes
  2:32  error  Strings must use singlequote         quotes
  2:46  error  There should be no space after '{'   object-curly-spacing
  2:60  error  There should be no space before '}'  object-curly-spacing
  3:25  error  Strings must use singlequote         quotes
  4:21  error  Strings must use singlequote         quotes
```
## Possible fixes
 - [ ] At a minimum `types.js` should be added to the `.eslintignore` file.
 - [ ] Check if there is a way for `tsc` to generate eslint compliant code, not sure if possible.
 - [ ] Lint the original typescript files with something like `tslint`.

**Comment by DenisCarriere** [comment]
👍 We should add `types.js` to `.eslintignore`.

**Comment by DenisCarriere** [comment]
Fixed by https://github.com/Turfjs/turf/pull/764
Thanks @dpmcmlxxvi
