### ISSUE TITLE
@turf/idw bad property name

### ISSUE THREAD

**Issue by dpmcmlxxvi** [Turfjs/turf#774]
The documentation for [IDW](http://turfjs.org/docs/#idw) states that the output interpolated value property for each grid cell will be added to a point property called `IDW`. However, the implementation is actually saving it to a property named `z`. Fixing this would break the API so should be targeted for next major release.

A short term fix could be to change the docs to reflect the name of the actual parameter. However, the name `z` is misleading since the interpolated value doesn't need ot have anything with the `z` coordinate. So long term the property name should be fixed.

**Comment by DenisCarriere** [comment]
Agreed that the docs aren't correct.

Instead of using `z` or `IDW` as the new property, why not return the same given `valueField` as the IDW value.

**Example:** Provide points using a `population` value => apply IDW => Polygons with `population` IDW value.

**Comment by dpmcmlxxvi** [comment]
Yeah, the `valueField` is good too.

**Comment by stebogit** [comment]
Fixed by PR #800
