### ISSUE TITLE
Add BBox property to bbox-polygon

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#776]
Would be ideal to translate the `bbox` property to the Feature when using [`@turf/bbox-polygon`](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox-polygon).

```javascript
const bbox = [-180, -90, 180, 90];
const polygon = turf.bboxPolygon(bbox);
//= polygon.bbox => undefined
```

**Comment by morganherlocker** [comment]
👎 This seems like behavior that is only occasionally desirable, in which case a user can replicate the behavior with a oneliner `polygon.bbox = bbox;`. I think we should avoid any unnecessary performance and memory overhead.

**Comment by DenisCarriere** [comment]
👍 sounds good, it is extra memory overhead.
