### ISSUE TITLE
turf.buffer incorrect?

### ISSUE THREAD

**Issue by mcdeurloo** [Turfjs/turf#783]
When creating a (25 meter) buffer around a very simple polygon, the result seems "off". I am trying to demonstrate the problem by:

- drawing the original polygon (red)
- drawing the buffered polygon (blue)
- drawing a (25 meter) buffered shape around the left-most point in the polygon (green)
- drawing a (25 meter) buffered shape around the right-most point in the polygon (yellow)

In the resulting image,
<img width="931" alt="screen shot 2017-06-09 at 11 20 10" src="https://user-images.githubusercontent.com/29302748/26969956-da47ccd8-4d07-11e7-9b6e-fcd0e3752c8a.png">
 you can clearly see that the circles are not inside the buffered polygon.

Coordinates of the object in this gist:
https://gist.github.com/mcdeurloo/b840ba8d4672acd5289a7a2b47430751#file-turf-buffer-geojson

**Comment by rowanwins** [comment]
Gday @mcdeurloo 

Thanks for the report. Different processes are being followed depending on the input. In the case of a single point then we're currently using `@turf/circle` , where a polygon is input then `jsts` is used. 

I'm probably not best placed to comment on which one to generating the more accurate shape, @DenisCarriere might have some thoughts.

Cheers
Rowan

PS. We're currently in the process of trying to remove the `jsts` dependency as it's very large and hard to debug.

**Comment by DenisCarriere** [comment]
@mcdeurloo @rowanwins Should be fixed now, mixing the operations using `circle` & `jsts` has mixed results. I dropped the circle operation (only 40% slower - better to have consistent results).

![image](https://user-images.githubusercontent.com/550895/27034686-a02009de-4f4c-11e7-9c95-c47b9a1e5ab0.png)

**Comment by DenisCarriere** [comment]
Fixed in next release `v4.5`
