### ISSUE TITLE
npm page for turf has obsolete install command

### ISSUE THREAD

**Issue by psnider** [Turfjs/turf#784]
https://www.npmjs.com/package/turf lists the install command as:
```
npm install turf
```
but when I did that, I was greeted with a long list of deprecation notices such as:
> npm WARN deprecated turf-convex@3.0.12: Turf packages are now namespaced: please use @turf/convex instead

Please update the npm page to show the correct command and reference the updated np modules.

**Comment by rowanwins** [comment]
Ah good pick up thanks @psnider , I'll get that updated. 

Mental note - also need to update the API page to include some of the latest modules

**Comment by DenisCarriere** [comment]
Turf is now namespaced, should install it via `npm install @turf/turf`.
