### ISSUE TITLE
New module @turf/shortestPath

### ISSUE THREAD

**Issue by dhivehi** [Turfjs/turf#788]
Requesting for a feature to find shortest path from point A to point B without colliding with any polygon
![screenshot-dhivehi mv-2017-06-14-10-52-11](https://user-images.githubusercontent.com/18715293/27117444-0b02d9a8-50f0-11e7-9151-4dd8b6055bec.png)

**Comment by rowanwins** [comment]
Gday @dhivehi 

That would be a nifty module. There is an interesting answer here that might help get someone started.
https://stackoverflow.com/a/6793562

**Comment by DenisCarriere** [comment]
👍 That's awesome! I think the module name sounds appropriate `@turf/shortestPath`

**Comment by dhivehi** [comment]
Hope this link would also be useful: https://github.com/TaipanRex/pyvisgraph

**Comment by rowanwins** [comment]
Thanks for the link @dhivehi that is helpful.

My only other question is should the person be able to pass on a buffer distance as a parameter? Or alternatively they could pass in buffered polygons...

If I was a betting man I'd say your interest is shipping given this module request and the tangents request as well  :)

**Comment by DenisCarriere** [comment]
> My only other question is should the person be able to pass on a buffer distance as a parameter?

👎 I don't think we should mix another module into this, the user can easily apply the buffer to the obstacle polygons before using `shortestPath`.

**Comment by dhivehi** [comment]
I think adding a 4th parameter as buffer distance would be nice.

**Comment by dpmcmlxxvi** [comment]
@rowanwins Depending on which algorithm gets implemented there might be a "buffer" like parameter needed. Some shortest path algorithms use a gridding approach, so the size of the grid cells is a buffer like parameter. Some algorithms don't. Pros and cons to both approaches.

**Comment by dhivehi** [comment]
I think adding buffer parameter is useful.

**Comment by DenisCarriere** [comment]
That works for me if you feel it would be useful to have, you would have two extra params (distance & units)

**Comment by bulutkartal** [comment]
from a ship captain perspective; distance to polygons parameter would be great. So they can use it for boat/ship routing. They can get the lands as polygons, set a safe distance and create their routes by using this module.

**Comment by DenisCarriere** [comment]
@bulutkartal 👍 Great feedback, if you have some sample data you'd like to provide for Ship examples, feel free to send a PR with your GeoJSON examples.

You can simply add them to the `turf/packages/turf-shortest-path/test/in` folder.

This module will be published in the next Major release `v5.0`, (very soon 🤞).
https://github.com/Turfjs/turf/pull/956

**Comment by DenisCarriere** [comment]
> They can get the lands as polygons, set a safe distance

The module provides a few Optional parameters.

- `options.obstacles` => Can be used for land
- `options.minDistance` => Can be used for safe distance ( ⚠️ NOT IMPLEMENTED YET)

@stebogit Do you think adding a `minDistance` would be too difficult? This would define the minimum "safe" distance from obstacles.

**Comment by bulutkartal** [comment]
@DenisCarriere I am really not good on coding, but good with math and maritime industry :) Mine was just an idea to be able to make it useful for maritime industry. [Land polygons](http://openstreetmapdata.com/data/land-polygons) can be implemented on maps and with min safe distance to polygons can be used for marine routing. This way they will be able to set how far their boat/ship will be from the closest land. Very useful for marine industry.

**Comment by DenisCarriere** [comment]
👍 What I was proposing wasn't coding, all you need to do is provide test sample data, this is a simple example that @stebogit created:

## test/in
https://github.com/Turfjs/turf/blob/c72d0c3825b9110b552440c6a32531c448058752/packages/turf-shortest-path/test/in/simple.json

```json
{
	"start": [5.625, 40.763],
	"end": [11.931, 39.147],
	"obstacles": {
		"type": "Feature",
		"properties": {},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[
						8.206787109375,
						40.730608477796636
					],
					[
						8.5693359375,
						39.8928799002948
					],
					[
						8.349609375,
						39.257778150283364
					],
					[
						8.843994140625,
						38.90813299596705
					],
					[
						9.085693359375,
						39.257778150283364
					],
					[
						9.591064453125,
						39.16414104768742
					],
					[
						9.591064453125,
						40.271143686084194
					],
					[
						9.82177734375,
						40.47202439692057
					],
					[
						9.283447265625,
						41.253032440653186
					],
					[
						8.206787109375,
						40.730608477796636
					]
				]
			]
		}
	}
}
```

## test/out

https://github.com/Turfjs/turf/blob/c72d0c3825b9110b552440c6a32531c448058752/packages/turf-shortest-path/test/out/simple.geojson

![image](https://user-images.githubusercontent.com/550895/32021961-f9ba6a6e-b9a2-11e7-97ca-dff2d2039557.png)

**Comment by DenisCarriere** [comment]
This module is now published under `@turf/shortest-path`.

A few extra enhancements were noted from some of these comments, will submit a new issue for those.

**Comment by bulutkartal** [comment]
Do you still planning on adding minDistance? It shows on new documentation but minDistance is not working for now. 

Also algorithm creates extra waypoints and make the path longer than it supposed to be.

[jsfiddle example](http://jsfiddle.net/bulutkartal/jhozk8jj/) based on documentation example.
