### ISSUE TITLE
passing the result of pointOnLine into pointOnLine returns a different point

### ISSUE THREAD

**Issue by grundid** [Turfjs/turf#794]
When I pass a point that was returned by the pointOnLine into the same function again, a different point is returned. I would assume that in this case the same point would be returned.

```javascript 
  const southLine = turf.lineString([[9.2368973, 49.1364072], [9.237684, 49.1363735]]);
  const result1 = turf.pointOnLine(southLine, turf.point([9.237267673015593, 49.136346850829064]));
  console.log("result1: ", JSON.stringify(result1, null, 1));
  const result2 = turf.pointOnLine(southLine, result1);
  console.log("result2: ", JSON.stringify(result2, null, 1));
```

First output: 
```json
{
 "type": "Feature",
 "properties": {
  "dist": 0.004937314122820035,
  "location": 0.027334223717436185,
  "index": 0
 },
 "geometry": {
  "type": "Point",
  "coordinates": [
   9.23727210542306,
   49.13639114439716
  ]
 }
}
```

Second output:

```json
{
 "type": "Feature",
 "properties": {
  "dist": 1.0669196418415465e-8,
  "location": 0.027334234386632603,
  "index": 0
 },
 "geometry": {
  "type": "Point",
  "coordinates": [
   9.237272105569355,
   49.13639114439089
  ]
 }
```

**Comment by DenisCarriere** [comment]
The coordinate difference from these two points is in nanometers  (1/1000cm) => `0.000000000146295`.

Depending on the version of NodeJS these numbers will be slightly difference, I don't think this is an issue/bug.

You can use [`@turf/truncate`](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate) to trim the GeoJSON coordinates to 6 decimals and then apply your compare operations.
