### ISSUE TITLE
Turf buffer buffer distance slightly off

### ISSUE THREAD

**Issue by mclaeysb** [Turfjs/turf#801]
Buffering points creates circles with the required radius, but buffering polygons seems to create buffers with a wrong radius. Here's an example on a very small polygon, buffered with radius 1 miles:

![screen shot 2017-06-18 at 18 45 16](https://user-images.githubusercontent.com/2920134/27262442-1dc9327a-5457-11e7-9571-ba47ccf8281c.png)

*Radius of @turf/buffer output is to small*

![screen shot 2017-06-18 at 18 45 12](https://user-images.githubusercontent.com/2920134/27262441-1b9fbea6-5457-11e7-9b2f-158414910d8d.png)

*Buffer with correct radius*

Inner object made with @turf/buffer, outer object made with [this](https://github.com/Turfjs/turf-buffer/pull/33) old PR of turf-buffer (but same can be made using @turf/destination).

I used [this](https://gist.github.com/mclaeysb/da0648b4ef81963b2cde085373e6c809) data as input.

Not sure what this is due to..

**Comment by mclaeysb** [comment]
Judging from the initial picture in #786, it seems like this might be related to that issue..

**Comment by DenisCarriere** [comment]
Definitely looks like there's a bug somewhere... looks like it might be the reprojection.

**Comment by shongololo** [comment]
I'm running into the same issue, it appears to happen for both buffering and circles. Probably a projection issue:

```
let p1 = point([-0.12, 51.2])
let p2 = point([-0.13, 51.8])
let l1 = lineString([[-0.12, 51.2], [-0.13, 51.8]])
let d1 = lineDistance(l1, 'kilometers')
console.log('distance 1: ' + d1)
// distance 1: 66.74149167617327
let b = buffer(p1, d1, 'kilometers')
let e1 = envelope(b)
let l2 = lineString([e1.geometry.coordinates[0][0], e1.geometry.coordinates[0][1]])
let d2 = lineDistance(l2, 'kilometers')
console.log('distance 2: ' + d2 / 2)
// distance 2: 58.858493793982554
let c = circle(p1, d1, 64, 'kilometers')
let e2 = envelope(b)
let l3 = lineString([e2.geometry.coordinates[0][0], e2.geometry.coordinates[0][1]])
let d3 = lineDistance(l3, 'kilometers')
console.log('distance 3: ' + d3 / 2)
// distance 3: 58.858493793982554
```

**Comment by stebogit** [comment]
@shongololo it seems actually that `d2` and `d3` are equals in your example because `e1` and `e2` are both "enveloping" `b`.
`@turf/circle` doesn't seem to have issues.
![screen shot 2017-08-14 at 11 15 02 pm](https://user-images.githubusercontent.com/12717225/29304708-566fd9b6-8149-11e7-8896-634533859e4a.png)

Also, you might want to measure the vertical side of the envelop (`lineString([e2.geometry.coordinates[0][1], e2.geometry.coordinates[0][2]])`) to compare with the vertical radius of the circle (`lineString([[-0.12, 51.2], [-0.13, 51.8]])`), because the projection does cause some small difference (see #684).

**Comment by shongololo** [comment]
@stebogit thanks, corrected the typo, circles now are close though still appear a tad off?

**Comment by stebogit** [comment]
:+1:

**Comment by jaapster** [comment]
How do you guys get this circle? Turf returns an oval when I use buffer.

**Comment by DenisCarriere** [comment]
Which version of turf are you using?

**Comment by jaapster** [comment]
@DenisCarriere package.json version is 3.14.3

**Comment by DenisCarriere** [comment]
Yep that will help, I think the buffet got fixed in 4.5 or so

**Comment by jaapster** [comment]
@DenisCarriere Is there any documentation on how to import turf? I updated to he latest version and import turf from '@turf/turf' gets me 'undefined' now.

**Comment by jaapster** [comment]
@DenisCarriere Yes, that solved it, thanks!

**Comment by omar-alnayme** [comment]
Hi, where to get the latest version of turf?

**Comment by omar-alnayme** [comment]
I get the oval buffer as well.
