### ISSUE TITLE
Proposal new module distance-clustering

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#811]
Continuing the discussion started in #787, ref. also #33 

@cyrilchapon as @DenisCarriere said we should not merge the two clustering strategies, but rather create a new module.
My question about the use of the distance clustering was not on the API, but more about an example of application, to try to understand better how to design input and output.
Reading the [article](https://www.mapbox.com/blog/supercluster/) provided by @DenisCarriere, [`kdbush`](https://github.com/mourner/kdbush) seems to be a great tool to index the points, but then you need to query the generated tree to perform the clustering.
What I don't quite get yet is how you would exactly use `maxDistance` to group the points...
Or maybe for each point you want a `FeatureCollection` of points that are within that distance?

Once we defined that we might want to define two clustering modules:
- [x]  `@turf/clusters-kmeans` (currently `@turf/clusters`)
- [x]  ~~`@turf/clusters-distance`~~ `@turf/clusters-dbscan`

**Comment by cyrilchapon** [comment]
@stebogit, my original use-case was [this one](https://stackoverflow.com/questions/40806348/aggregate-by-geonear). It was db-oriented question but the main purpose is now I'm using to preprocess some stuff for insert/updates on mongo. In that particular case, it's a common use-case tu aggregate some location points from IOT networks for example.
maxDistance (actualité this is lire like minDistance) factor would be the "maximal distance between 2 points before jumping to a new cluster". Or maybe the "minimal distance between 2 points to be considered as a cluster". But it shouldn't "jump" from point to point, it would be more like the mac radius of a circle containing all points of a cluster.

**Comment by DenisCarriere** [comment]
Another library that might be useful to create the distance cluster is [`geokdbush`](https://github.com/mourner/geokdbush) which will allow you to find the closest points using [`geokdbush.around`](https://github.com/mourner/geokdbush#geokdbusharoundindex-longitude-latitude-maxresults-maxdistance-filterfn).

**Comment by DenisCarriere** [comment]
Lets develop both for now, and lets see at the end if we should combine them together or not.

@stebogit I'll be working on `clusters-distance` today, I've got an idea how I can tackle it.

**Comment by stebogit** [comment]
Implemented with #812

@cyrilchapon maybe you want to check the brend new [`@turf/clusters-dbscan`](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-dbscan) out, I believe it might help with [your use-case](https://stackoverflow.com/questions/40806348/aggregate-by-geonear)

**Comment by cyrilchapon** [comment]
Hello, and thanks about this.
I realy don't know why I'm not receiving any notification anymore oO.

It looks amazing, and I'm glad to have a brand new use-case to test it : I'm willing to display accidentology data, and I think I'm going to aggregate it to create "accident zones" rather than "accident points". This is gonna be exiting to test that feature.

I have to say I'm very impressed, by turf community. I find it pretty rare when you take some time to express a need, but you don't explicitly have time to dedicate to an opensource repo, to get a real feedback from a community. Plus feature and bug tracking on turf repo is fantastic.

If I get to have time to contribute, soon, I'll definately start with turf.

**Comment by DenisCarriere** [comment]
@cyrilchapon Thanks for the great positive feedback 😍 

If you want to check out a live example of the "density cluster" library (`@turf/clusters-dbscan`).

https://github.com/DenisCarriere/turf-example-clusters-dbscan

checkout the source code here:

https://github.com/DenisCarriere/turf-example-clusters-dbscan

![image](https://user-images.githubusercontent.com/550895/30664371-70367cda-9e1b-11e7-9bdb-ab6692eabea3.png)
