### ISSUE TITLE
Buffer for lineString not consistent width

### ISSUE THREAD

**Issue by stephanbogner** [Turfjs/turf#815]
I recently had the need to outline a lineString and it seems that using 'buffer' is not doing it as I expected.
I expected it to be like a stroke, so width is everywhere the same, which it clearly isn't:
<img width="670" alt="bildschirmfoto 2017-06-22 um 17 13 32" src="https://user-images.githubusercontent.com/7897006/27441562-32fc7aa2-576e-11e7-982f-25a2f5b6d198.png">

You can see [here](https://gist.github.com/anonymous/5a9d5be2204451e4001b75890406c70e) my implementation vs. buffer.

- Red is created using 'buffer'
- Blue by [my own implementation](https://gist.github.com/stephanbogner/8a2216817ad143b6c455311355733041)
- Line is original geometry

→ So my question is if that is intended behaviour and if so for what reason?

**Comment by rowanwins** [comment]
Thanks @stephanbogner for highlighting the issue, it does indeed look like something is a bit off... 

Currently the buffer functionality is provided by the `jsts` library so we have limited control over that. However it's been a longstanding task/dream to remove that dependency. This is another helpful reason to keep us pursue that so thank you :)

**Comment by stephanbogner** [comment]
Thank you very much for explaining this dependency – I was not aware.

**Comment by DenisCarriere** [comment]
The main issue with `buffer` was applying a buffer which is equidistant (ref issue https://github.com/Turfjs/turf/issues/660).

Before it use to do this:
![image](https://user-images.githubusercontent.com/550895/27871275-2d541da8-6173-11e7-9eff-5733b9bacdf2.png)

To fix this, we applied a project & reproject to the decimal degrees coordinates.

https://github.com/Turfjs/turf/blob/master/packages/turf-buffer/index.js#L105-L110

There's definitely room for improvement in the `@turf/buffer`.

**Comment by stebogit** [comment]
Fixed with #938
