### ISSUE TITLE
Using turfjs with nodejs streams

### ISSUE THREAD

**Issue by pietrovismara** [Turfjs/turf#816]
Here and there on the web i see someone occasionally mentioning using turfjs with nodejs streams, but i can't find any code example or explanation.

At the moment, im using mongoDB to work on datasets which are too large to fit in a nodejs process memory. I'd like to use turfjs for all the spatial analysis and mongodb only as a storage.

For example, i want to use functions like turf.inside or turf.within with a readable stream of points.
Obviously buffering them and then using turf would defeat the point of using streams.

Can anyone tell me if this is possible, or point me to resources which could help?

**Comment by rowanwins** [comment]
Hi @pietrovismara 

Im a bit confused as to what the question is. The short answer is yes you can use turf within streams. 

Do you have a stream process setup yet? Using something like `mongoose` you can connect to your mongodb and then [create a stream](http://mongoosejs.com/docs/api.html#querystream_QueryStream) of your data
````
var stream = Model.find().stream();

stream.on('data', function (doc) {
  turf.inside(doc, somePoly)
}).on('error', function (err) {
  // handle the error
}).on('close', function () {
  // the stream is closed
});
````
In regards to how to setup the streaming a lot will depend on your data structure within mongodb

**Comment by DenisCarriere** [comment]
Answered by @rowanwins
