### ISSUE TITLE
ConvertArea similar to convertDistance

### ISSUE THREAD

**Issue by wnordmann** [Turfjs/turf#817]
The area functions return Square Meters, is there a convertArea function similar to convertDistance?  

If it doesn't exist is there a plan to add one?  I would be happy to tackle this function if any guidance could be offered.

**Comment by DenisCarriere** [comment]
👍 Currently there's no plan to add `convertArea`, however it would be beneficial to add this type of feature to [`@turf/helpers`](https://github.com/Turfjs/turf/tree/master/packages/turf-helpers) which could be implemented very similar to [`convertDistance`](https://github.com/Turfjs/turf/blob/9ca43a059ab06331f3fc9e0787056af343f993cd/packages/turf-helpers/index.js#L387-L402)

**Comment by rowanwins** [comment]
I reckon that would be a handy addition thanks @wnordmann ! The reference @DenisCarriere is hopefully a starting point but feel free to sing out if you need more assistance.

**Comment by wnordmann** [comment]
I understand the code / algorithm fine.  Just wondering if you have a
recommend source of area conversion factors.  I see the attention to
accuracy used for the distance measure.

**Comment by DenisCarriere** [comment]
👍 Thanks @wnordmann
