### ISSUE TITLE
Not found : @turf/boolean-crosses

### ISSUE THREAD

**Issue by vicvolk** [Turfjs/turf#818]
This is probably not a bug. but something that I do wrong. So, when I run this in the command line on my Windows machine:

`npm install @turf/collect`

I get no error messages. When, however, I run this:

`npm install @turf/boolean-crosses`, I get a bunch of error messages. This is how it looks like, when it's ok:

`C:\turf-master>npm install @turf/collect
@4.0.0 C:\turf-master
`-- @turf/collect@4.4.0
  +-- @turf/bbox@4.4.0
  | `-- @turf/meta@4.4.0
  +-- @turf/inside@4.4.0
  | `-- @turf/invariant@4.4.0
  `-- rbush@2.0.1
    `-- quickselect@1.0.0`

And this is how it looks like, when it goes wrong:

`C:\turf-master>npm install @turf/boolean-crosses
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "@turf/boolean-crosses"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @turf/boolean-crosses
npm ERR! 404
npm ERR! 404  '@turf/boolean-crosses' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\turf-master\npm-debug.log`

So, what is wrong with that and how can I fix it? Thanks in advance!

**Comment by DenisCarriere** [comment]
This is normal since `@turf/boolean-crosses` hasn't been published yet. This will become available when `v4.5.0` is published.

https://github.com/Turfjs/turf/pull/796

I'd like to close the 3/4 PR's before we publish the next release.

https://github.com/Turfjs/turf/pulls
