### ISSUE TITLE
New Module proposal `@turf/subdivide`

### ISSUE THREAD

**Issue by stephanbogner** [Turfjs/turf#828]
Maybe I missed a module, because I thought more people should have that problem.

I wanted to draw a lineString/polygon on a map with its respective curvage along the great arc (is that how you express something like that). So I wrote a script which adds intermediate points.

**Example on Gist:** http://geojson.io/#id=gist:anonymous/34fd7cce1fe4aaa7093dddd9854ec5db&map=3/34.52/-41.48
About: White outlines are the result, the dark ones are the input (polygon was not converted to lineString, I just outlined it for display purposes)

![bildschirmfoto 2017-07-06 um 12 13 22](https://user-images.githubusercontent.com/7897006/27906598-8bcd93e2-6244-11e7-8dc7-0caad9a76d40.png)

**Code I used:** https://gist.github.com/stephanbogner/8777bb7fb4377dc39deda6d41be53e85
Principle: I wanted all segments to be the same length, so you define a maximum gap size. I could also imagine that you specify the number of subdivisions.

**Comment by DenisCarriere** [comment]
Have you seen the [`@turf/great-circle`](https://github.com/Turfjs/turf/pull/607) module? It only applies to point => point, however the same logic could be applied to LineString & Polygon by breaking them out into 2 vertex line segments using [`@turf/line-segment`](https://github.com/Turfjs/turf/pull/611).

I'm not too sure if `@turf/subdivide` would be the correct name for this type of module, seems like this would fit better using `@turf/<GeometryType>-great-circle` (ex: `@turf/line-great-circle`).

**Comment by DenisCarriere** [comment]
> That module now finally makes sense to me!

🤣 That's funny, yea that module is a bit abstract, however it is useful in many scenarios (like this one).

> I am neither developer nor geographer :)

Most of us aren't either, we just fell into it. Most of the TurfJS modules are pretty straight forward, just have a look at a few [`index.js`](https://github.com/Turfjs/turf/blob/master/packages/turf-flip/index.js) in the [`packages`](https://github.com/Turfjs/turf/blob/master/packages) and you can get familiar with the code style & flow pretty quickly.

**Comment by stephanbogner** [comment]
Thanks already for being very kind and welcoming – this means a lot to me.
I am now trying to make this a proper module (alongside a few other things) and was wondering:

How do you create new modules that are dependent on each other?

E.g. I write two modules A and B. B uses module A, but neither of them is yet on npm. How can you access the code from A in module B? Do you HAVE to publish module A first and then develop B?
I googled a lot, but haven't found anything about that ...

I know this question is not directly related to the module proposal, but I stumbled about that problem while working on it.

**Comment by stebogit** [comment]
@stephanbogner if you want to import/require a module I believe you _have_ to [publish it on npm](https://docs.npmjs.com/getting-started/publishing-npm-packages). It is not difficult (I learned in a day!), [this great tutorial](https://egghead.io/lessons/javascript-publishing-to-npm) gives you the bases on how to manage code and releases with git(hub).

It is in general good practice to separate concerns among functions/objects/modules, it helps to reduce the overall complexity and thus to solve bigger problems. So I think it would be a good idea to develop and test one module and then develop the other, knowing the first will behave exactly as you expect.
You can use the [`create-new-module`](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#structure-of-a-turf-module) script to quickly set up with a new module.

However, you could just include module A as a function in module B. You can always extract the function in a separate module and publish later, like it happened [here](https://github.com/Turfjs/turf/issues/809).

**Comment by DenisCarriere** [comment]
Developing two modules at the same time can get complex at times, but we can publish module A immediately once everything is approved, that way you can work on module B right away. Also you can use the suggested comment to include Module A as an internal function to module B and remove afterwards once we publish them.

**Comment by DenisCarriere** [comment]
Not too sure if changing the decimal points of truncate would be the solution here, I think better handling of the exact start & end points would be a better approach.

Seems like it's having difficulties with exact coordinates, not too sure if we can exclude points from generating lines which are less then 10cm (0.000001 degrees) apart.

**Comment by stebogit** [comment]
@DenisCarriere wrong issue 😄 . I bet you were referring to #892

**Comment by DenisCarriere** [comment]
Was on my mobile device... kept switching back and forth... 👍 I know

**Comment by stephanbogner** [comment]
Thank you folks very much for this explanation – greatly appreciated, since these kind of thing help beginners like me a lot :)
