### ISSUE TITLE
turf official tutorial doesn't work on chrome Linux

### ISSUE THREAD

**Issue by uptonking** [Turfjs/turf#830]
Sorry, I don't know where to report the bug, so I post it here.  
  
When I follow your [Analysis with Turf.js](https://www.mapbox.com/help/analysis-with-turf/)  tutorial on [EXAMPLES](http://turfjs.org/examples/) page. 

The hospitals and libraries points doesn't show on Chrome and Opera, but it works well on Firefox.  

My dev env is CentOS 7.3, Chrome 58.0, Opera 45.0 , Firefox 52.1.

the console doesn't show any error on Chrome, the base map displayed, but no point markers.  
the console error on Opera is as follow, but the base map is not complete, just 2 tiles:
```
evented.js:104  
 The layer 'hospitals' does not exist in the map's style and cannot be queried for features.  
```

It surprises me that  the tutorial on your website doesn't work well itself.  
 the picture below is the [Analysis with Turf.js](https://www.mapbox.com/help/analysis-with-turf/)  tutorial on Chrome and Firefox.  
![tutorial_error_on_chrome.png](https://uptonking.github.io/assets/issues/turf/tutorial_error_on_chrome.png)

please do reply to me, I loves your turf.  
if this is not the problem of your lib, maybe it's the problem of the mapbox-gl-js, if you cannot solve it, just directly tell me so that I get the issue closed.

**Comment by DenisCarriere** [comment]
Looks like this would be a slightly outdated help website, doesn't seem to be TurfJS that's causing the issue but the Data not being able to load via Mapbox GL.

![image](https://user-images.githubusercontent.com/550895/27971723-bfab002c-6321-11e7-912a-61b3123deef6.png)

Getting the same error for the demo websites.
```
evented.js:104 The layer 'hospitals' does not exist in the map's style and cannot be queried for features.
Evented.fire @ evented.js:104
t.queryRenderedFeatures @ style.js:758
e.queryRenderedFeatures @ map.js:739
(anonymous) @ demo-four.html:96
Evented.fire @ evented.js:87
h @ bind_handlers.js:139
a @ bind_handlers.js:75
demo-four.html:97 Uncaught TypeError: Cannot read property 'length' of undefined
    at e.<anonymous> (demo-four.html:97)
    at e.Evented.fire (evented.js:87)
    at h (bind_handlers.js:139)
    at HTMLDivElement.a (bind_handlers.js:75)
```

@lyzidiamond Maybe you can help out with this one?

**Comment by stebogit** [comment]
It seems the issue has been fixed.
**Chrome:**
![screen shot 2017-09-17 at 11 04 23 am](https://user-images.githubusercontent.com/12717225/30529675-b3db2cc0-9bf4-11e7-98e1-c9e78c30d21c.png)

**Comment by DenisCarriere** [comment]
👍
