### ISSUE TITLE
Isobands commonProperites issue

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#831]
Just noticed the TurfJS website has errors related to `@turf/isobands`.

```javascript
Uncaught TypeError: Cannot read property 'commonProperties' of undefined
    at Object.e.exports [as isobands] (turf.min.js:19)
    at turfjs.org/:9738
```

**Comment by DenisCarriere** [comment]
Ahhh.. gotcha, got fixed via https://github.com/Turfjs/turf/commit/1663f077c075c8902dbeff4acf68b1c8e0151853

**Comment by stebogit** [comment]
This will be fixed when publishing the new release, I guess

**Comment by DenisCarriere** [comment]
👍 Should be fixed
