### ISSUE TITLE
@turf/point-grid - change centered param default to True

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#833]
## [`@turf/point-grid`](https://github.com/Turfjs/turf/tree/master/packages/turf-point-grid) - change `centered` param default to True
Seems like the `centered` property should default to `True` instead of `False`/`undefined` since this option would be most useful all the time.

```javascript
poinGrid(box, cellSize, units)
//= centered param would equal True (even if defined as undefined)
```

## JSDocs

```javascript
/**
 * Creates a {@link Point} grid from a bounding box, {@link FeatureCollection} or {@link Feature}.
 *
 * @name pointGrid
 * @param {Array<number>|FeatureCollection|Feature<any>} bbox extent in [minX, minY, maxX, maxY] order
 * @param {number} cellSide the distance between points
 * @param {string} [units=kilometers] used in calculating cellSide, can be degrees, radians, miles, or kilometers
 * @param {boolean} [centered=true] adjust points position to center the grid into bbox
 * @param {boolean} [bboxIsMask=false] if true, and bbox is a Polygon or MultiPolygon, the grid Point will be created
 * only if inside the bbox Polygon(s)
 * @returns {FeatureCollection<Point>} grid of points
 */
module.exports = function (bbox, cellSide, units, centered, bboxIsMask) {
```

Ref: Issue https://github.com/Turfjs/turf/issues/613
CC: @stebogit

**Comment by stebogit** [comment]
@DenisCarriere 👍  that make sense, but why not just have the output always centered, removing the parameter?
Why/when should the output ever be off?

**Comment by DenisCarriere** [comment]
> Why/when should the output ever be off?

Agreed, dropping the parameter would be fine, there's really no benefit of having an inconsistent offset grid.

We can change the value to True for the minor release, and if we remember, we can drop it in the next major release (whenever that happens).
