### ISSUE TITLE
turf-area produces wrong result

### ISSUE THREAD

**Issue by harsh-a1** [Turfjs/turf#839]
Please provide the following when reporting an issue:

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
    `https://gist.github.com/harsh-a1/51885002365adc7666bf83a6e2df9783`
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).
`var mergedCircle = turf.union.apply(this,circles);`
 `mergedCircle.properties.area = (parseFloat(turf.area(mergedCircle))/1000000);`

There were two points 0.81Km apart. I made a circle around each of 0.81Km radius. Then merged them together. Please see gist above. Then calculated area but it is giving wrong result.

Area is coming out to be 1.03 sqKm which is wrong as per formula of pi*r^2. It should be around ~4.

Please help! Am I doing something wrong?

**Comment by stebogit** [comment]
@harsh-a1 the radius of your circles seems to be ~440yd => ~0.4km, which brings to an area of ~0.50sqkm for each circle; thus a total area of ~1sqkm seems to about right.

![screen shot 2017-07-12 at 5 35 12 pm](https://user-images.githubusercontent.com/12717225/28145688-0c2042a4-6729-11e7-889e-bdf4b950e134.png)

**Comment by harsh-a1** [comment]
Yes, Sorry my bad.... 1 sqKm is correct.
Thanks for reviewing.

**Comment by DenisCarriere** [comment]
👍 I'm glad we didn't have to fix this one, I wouldn't even know where to start.
