### ISSUE TITLE
Fix license template in create-new-module script

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#861]
Running the test at the root level threw an error because my license in my new module wasn't the same as the root license even though I created it using the script. I noticed the script has the license manually hardcoded, perhaps it should be a copy/paste operation? At the moment I can't even tell why it's failing, they look exactly the same to me :)

PS Im on windows, so perhaps there is something in the tests that isn't working on windows...

**Comment by DenisCarriere** [comment]
👍 Agreed, might be better to Copy-Paste the LICENSE file instead of hardcoding it.

**Comment by DenisCarriere** [comment]
@rowanwins Copies the license file now, this script is very rough, but it handles 90% of the module boilerplate.

**Comment by rowanwins** [comment]
Awesome, I'll just test on my machine to make sure the tests pass locally, it might be one of those stupid windows or node version bugs

**Comment by stebogit** [comment]
@DenisCarriere @rowanwins 
in `README.md` shouldn't [this](https://github.com/Turfjs/turf/commit/df6986ec0a5c353babb60836ec97c21923913e79#diff-0b8f1081465023072e327284806eaed9R175) be actually `# ${camelcaseName}`?

**Comment by DenisCarriere** [comment]
@stebogit Yes it should 👍

**Comment by DenisCarriere** [comment]
> Awesome, I'll just test on my machine to make sure the tests pass locally, it might be one of those stupid windows or node version bugs

@rowanwins If that's the case, lets try to figure out what's the issue... I agree it's very annoying going back and forth between Windows/Mac.

**Comment by stebogit** [comment]
I agree WINDOWS is very annoying! 🤣  😜
