### ISSUE TITLE
Can we have a ts definition guide?

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#862]
As a contributor I never know how to write the ts definitions. I don't use typescript, I just loving go along with it because it makes @DenisCarriere happy :) 

Could we get some sort of guidance as to what any of it means rather than me blindly copying and pasting and making tests fail?

**Comment by DenisCarriere** [comment]
Lol I third this... I'll write something when I have the time to dedicate to it

**Comment by rowanwins** [comment]
no worries @DenisCarriere - would just be a nice to have, particuarly given that the tests now rely on them being correct. Until we get them I'll just keep blindly pasting!

**Comment by DenisCarriere** [comment]
@rowanwins During the `v5.0` re-work I'm going to refactor all the Typescript definitions to reflect the "future" 🚀  Typescript guide.

**Comment by mfedderly** [comment]
I'm going to close this, I think we've got a decent amount of prior art here now in the repo and anything written in typescript already publishes its types automatically. If you still think there's something we should write up at this point please reopen the ticket @rowanwins @stebogit
