### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#87]
Identify and fix crossed polygon rings, and whatever other issues can be identified with geometries.

Use the functionality in mapshaper as a reference:

http://www.mapshaper.org/

**Comment by vlasvlasvlas** [comment]
love to have the st_makevalid solution

**Comment by yauh** [comment]
I'd love to see something added to Turf that fixes polygon geometries!

**Comment by rowanwins** [comment]
Related to #145 so just dropping a note here to about this library - https://github.com/mclaeysb/simplepolygon

**Comment by morganherlocker** [comment]
@rowanwins Looks like a pretty robust solution to me.

**Comment by rowanwins** [comment]
Now available as [turf.unkinkPolygon](http://turfjs.org/docs/#unkinkpolygon) using [simplepolygon](https://github.com/mclaeysb/simplepolygon) under the hood
