### ISSUE TITLE
Improve linting tests

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#879]
# Improve linting tests

Based on https://github.com/Turfjs/turf/pull/873#issuecomment-318890019 & https://github.com/Turfjs/turf/pull/873#issuecomment-319229572.

## To-Do
- [ ] add `@name` linting to tests
- [ ] investigate how to tackle linting new modules

**Comment by mfedderly** [comment]
ESLint and Typescript are doing a bunch of good work when it comes to linting these days.
