### ISSUE TITLE
ringEach Proposal

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#881]
So just wanted to continue the discussion from [this pull request](https://github.com/Turfjs/turf/pull/876).

I'd find it quite handy to have a module that looped through interior and exterior rings of polys easily.

````
turf.ringEach(feature, function (ringCoords, ringIndex, isExterior) {
  //=ringCoords = [[0,0], [1,1], [1, 0], [0, 0]]
  //=ringIndex = 0
  //=isExterior = true
});
````
@DenisCarriere you proposed splitting the module into interior and exterior versions, I'm just trying to think through whether it would be better to have them together in a single module and how I'd use them....

In an ideal world I'd then love to be able to pass a coord array into one of the other meta functions, eg `coordEach` without having to first turn into a geojson feature or geometry.

Anyway just starting the discussion rolling in a more trackable place than a vaguely related pull request :)

**Comment by DenisCarriere** [comment]
> you proposed splitting the module into interior and exterior versions

👍 I like your approach better, combining both of them prevents doing a 2nd iteration over the GeoJSON.

> In an ideal world I'd then love to be able to pass a coord array into one of the other meta functions, eg coordEach without having to first turn into a geojson feature or geometry.

Agreed, the only thing that we would need to figure out is the depth of the coord Array. Using a Feature or Geometry the depth can be figured out by the Geometry Type, but with an Array it could be a bit trickier (but not impossible).

> ringIndex

- [ ] We might want to include `ringSubIndex` to capture MultiPolygon.

**Comment by stebogit** [comment]
@rowanwins @DenisCarriere based on GeoJSON specs the `Polygon` outer ring has to be the first one. Should we follow and enforce that rule (assuming the input is a valid GeoJSON)? We wouldn't need the `isExterior` index.

**Comment by DenisCarriere** [comment]
👍 Agreed, since the OuterRing will always be `ringIndex=0`

@stebogit How should we handle `MultiPolygon` Geometries?

Also we should add `LineString` & `MultiLineString` as valid inputs (might as well throw in Points as well to support all Geometry types).

**Comment by DenisCarriere** [comment]
> How should we handle MultiPolygon Geometries?

- `ringIndex` will always be the "inner/outer" rings of the Polygons

- `ringSubIndex` will be the index for the MultiParts, if Feature only has 1 part then `ringSubIndex=0` (maybe call it `multiPartIndex`?)

**Comment by rowanwins** [comment]
> Also we should add  LineString  &  MultiLineString  as valid inputs (might as well throw in Points as well to support all Geometry types).

I wasn't thinking about lines or points at all, rings are a polygon thing in my opinion. What would the use case be for lines or points?

> How should we handle MultiPolygon Geometries?
Yes this is ought to be a key consideration, obviously this is where you have multiple outer rings so looping becomes useful :)

Maybe rather than talking about `ringIndex` perhaps we should use the term `ringDepth` or something like that
````
turf.ringEach(feature, function (ringCoords, ringDepth, multiPartIndex) {
   //ringDepth=0 means exterior
   //ringDepth=1 means interior
  //multipartIndex
})
````
Although if ringDepth is always 0 or 1 I'd possibly be inclined to go `true` or `false` (which take us back almost to my original suggestion :) )

Anyway thanks for your thoughts gents, I think I'll find this module very useful for a lot of polygon related modules and issues around polys with holes

**Comment by DenisCarriere** [comment]
> Maybe rather than talking about ringIndex perhaps we should use the term ringDepth or something like that

I'd still rather use `ringIndex`, the word `index` indicates the position that the `ring` is located in the Geometry.

> I wasn't thinking about lines or points at all, rings are a polygon thing in my opinion. What would the use case be for lines or points?

Well we could abstract it even more and call it `lineEach` & `lineReduce` which iterates over (Multi)LineString & (Multi)Polygon to retrieve a single `LineString`.

Using the word `ring` we now have to define what `ring` is... if we call it `lineEach` then it's a bit self-explanatory.

> Although if ringDepth is always 0 or 1 I'd possibly be inclined to go true or false (which take us back almost to my original suggestion :) )

Using `isExterior` might be too specific for a use case, I'd rather use the `lineIndex=0` or `ringIndex=0` approach.

**Comment by rowanwins** [comment]
my only concern with a name like `lineEach` would be that it's potentially confusing if you don't know what you're looking for, looking through a list of modules I wouldn't necessarily expect that to be relevant to polygons...

Happy to bow to pressure on the index naming :)

**Comment by DenisCarriere** [comment]
Both `lineEach` or `ringEach` are both super valid, we can stick with `ringEach` since `flattenEach` would solve the use case for doing that same thing for `MultiLineString`.

- [x] 👍 `ringEach` & `ringReduce`
- [x] 👍 Only support for (Multi)Polygon  (`flattenEach` can be used for (Multi)LineString & (Multi)Point have nothing to do with this 😄 )

## Next Discussion topic:
### `Feature<LineString>` Callback
Since all the input/output of TurfJS is using Feature/Geometry and not `Array<number>` (except for Point `[number, number]`). Shouldn't we return a `Feature<LineString>` that way it's easier to apply that new Line to all the other TurfJS modules, we're currently doing this for `segmentEach`.

Since you know 100% that the callback is returning a `Feature<LineString>` then you can simply call `feature.geometry.coordinates` without it ever breaking.

- [ ] Line Callback should be `Feature<LineString>` instead of `Array<number>`

**Comment by DenisCarriere** [comment]
Any comments?
```js
turf.ringEach(poly, function (currentRing, ringIndex, multiPartIndex) {
  //=currentRing = lineString([[0,0], [1,1], [1, 0], [0, 0]])
  //=ringIndex = 0
  //=multiPartIndex = 0
});
```

**Comment by rowanwins** [comment]
Done!

Now re the callback I like you're idea of it being a feature, my only question would be is it a line or a polygon? I'd argue it's a polygon because the end vertices are purposefully joined... Calling it a line is a tad misleading.

**Comment by DenisCarriere** [comment]
🤓 Touché! These would be best defined as Polygons since you can't have an open LineString as an inner ring.

- [x] 👍 `Feature<Polygon>` callback

**Comment by rowanwins** [comment]
@stebogit is going to wake up in the morning in whatever timezone he is in and everything will be decided without him :)  Or perhaps we can just allocate it to him to make the module!

**Comment by DenisCarriere** [comment]
Haha! 🤣 No this is good, the more we talk about it helps define the module, instead of writing code and then changing it 20 commits later.

**Comment by stebogit** [comment]
Sorry guys, I followed almost all the conversation and I have a couple of suggestions, but I don't have my computer with me! :) I'll join the conversation in a few

**Comment by DenisCarriere** [comment]
👍 All good, I'll probably end up sleeping on it, so far I don't have anymore comments, looking forward to see what @stebogit has to say.

**Comment by stebogit** [comment]
So, in my understanding the goal of this module is to loop through the various items represented in the `coordinates` field of the `geometry`, being them points, lines or rings. Correct?
With that assumption:
```js
var point, turf.point([5,9]);
turf.geomItemEach(point, function (currentItem, itemIndex, collectionIndex) {
  //=currentItem = point
  //=itemIndex = 0
  //=collectionIndex = undefined
});

var line = turf.lineString([[-0.3,-0.35],[1.45,-0.35],[1.45,1.15],[-0.3,1.15],[-0.3,-0.35]]);
turf.geomItemEach(line, function (currentItem, itemIndex, collectionIndex) {
  //=currentItem = line
  //=itemIndex = 0
  //=collectionIndex = undefined
});

var polygon = turf.poygon([
    [[-0.3,-0.35],[1.45,-0.35],[1.45,1.15],[-0.3,1.15],[-0.3,-0.35]],
    [[0,0],[1,0],[1,1],[0,0]]
]);
turf.geomItemEach(polygon, function (currentItem, itemIndex, collectionIndex) {
  //=currentItem = ring, ring
  //=itemIndex = 0, 1
  //=collectionIndex = undefined
});

//------------

var multiPoint = turf.multiPoint([
   [0,0],[1,1],[2,2]
]);
turf.geomItemEach(multiPoint, function (currentItem, itemIndex, collectionIndex) {
  //=currentItem = point, point, point
  //=itemIndex = 0 | 0 | 0
  //=collectionIndex = 0, 1, 2
});

var multiLine = turf.multiLineString([[
    [[-0.3,-0.35],[1.45,-0.35],[1.45,1.15],[-0.3,1.15],[-0.3,-0.35]],
    [[0,0],[1,0],[1,1],[0,0]] ,
    [[-1.45,-0.95],[-0.90,-2.15],[-0.25,-0.95],[-1.45,-0.95]]
]]);
turf.geomItemEach(multiLine, function (currentItem, itemIndex, collectionIndex) {
  //=currentItem = line | line | line
  //=itemIndex = 0 | 0 | 0
  //=collectionIndex = 0, 1, 2
});

var multiPoly = turf.multiPolygon([[
    [[-0.3,-0.35],[1.45,-0.35],[1.45,1.15],[-0.3,1.15],[-0.3,-0.35]],
    [[0,0],[1,0],[1,1],[0,0]] 
], [
    [[-1.45,-0.95],[-0.90,-2.15],[-0.25,-0.95],[-1.45,-0.95]]
]]);
turf.geomItemEach(multiPoly, function (currentItem, itemIndex, collectionIndex) {
  //=currentItem = ring, ring |  ring
  //=itemIndex = 0, 1 | 0
  //=collectionIndex = 0, 1
});
```
Does it make sense?

**Comment by DenisCarriere** [comment]
Well this method would only really apply for polygons, a way to iterate over the inner/outer rings.

At the moment, flattenEach does a lot of the heavy lifting, it would be one level down.

It wouldn't be much logic, but would make iterating over polygons a bit cleaner.

**Comment by stebogit** [comment]
Which method are you referring to?

**Comment by DenisCarriere** [comment]
Well I think what @rowanwins wants to get is something like this:

> Getting interior/exterior rings of polygons
```js
const {flattenEach} = require('@turf/meta')
const {polygon} = require('@turf/helpers')

var poly = polygon([
    [[-0.3,-0.35],[1.45,-0.35],[1.45,1.15],[-0.3,1.15],[-0.3,-0.35]],
    [[0,0],[1,0],[1,1],[0,0]]
])

flattenEach(poly, (feature, featureIndex, featureSubIndex) => {
    feature.geometry.coordinates.forEach((ringCoords, ringIndex) => {
        const isExterior = ringIndex === 0
        //= isExterior = true, false
        //= ringCoords = Array<number>, Array<number>
        //= ringIndex  = 0, 1
    })
})
```

After writing this... why are we making a 3 line module which only applies to polygons? lol...

@rowanwins 🤔 Reconsidering this entire module proposal.

**Comment by stebogit** [comment]
Probably I am missing something here.
As @DenisCarriere  said, why would we need a module for only iterating through the rings of a `polygon`?
You don't even actually need any Turf module:
```js
var poly = polygon([ [[...]], [[...]], [[...]] ]);
poly.geometry.coordinates.forEach((ringCoords, ringIndex) => {
    const isExterior = ringIndex === 0
    //= ringCoords = Array<number>, Array<number>
    //= ringIndex  = 0, 1
    //= isExterior = true, false
})
```

Maybe we could have a `lineEach` that applies to `(Multi)LineString` and `(Multi)Polygons` that allows to iterate through each line in the feature (a ring is by [definition](https://tools.ietf.org/html/rfc7946#section-3.1.6) a close `LineString`):

```js
turf.lineEach(multiPoly, function (currentLine, lineIndex, multiIndex) {
  //=currentLine
  //=lineIndex (poly's exterior ring => 0)
  //=multiIndex (undefined for LineString)
});
```

**Comment by rowanwins** [comment]
I'd argue the same could be said for most of the meta or helper modules, they are simplistic but helpful :)

The reason I'd find it helpful is that when it comes to writing any polygon module it's a pain to repeat those lines when wanting to support polys with holes or multipolys. It's one less chunk of code I have to remember or think about writing which gives me more headspace to support those use cases.

I think @stebogit snippet above is probably the most helpful in achieving what I want so perhaps I'll give that a whirl and report back.

**Comment by DenisCarriere** [comment]
👍 @stebogit I like `lineEach`, seems a bit more flexible.

Great back and forth discussions :)

**Comment by stebogit** [comment]
@rowanwins should we close this?

**Comment by rowanwins** [comment]
Consider it closed - thanks @stebogit !
