### ISSUE TITLE
Deprecate `@turf/idw` ?

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#887]
Since we implemented the new `@turf/interpolate`, which uses the same [Inverse Distance Weighting (IDW) method](https://en.wikipedia.org/wiki/Inverse_distance_weighting) algorithm and can output different types of grids, we should probably deprecate `@turf/idw`.
Ref https://github.com/Turfjs/turf/pull/832#issuecomment-313992569.

I'd suggest however a performance tune of `interpolate`, which seems to be a little slower than `idw`, probably due to the use of `featureEach`.

Maybe we could add now a warning message like we did for `@turf/clusters` https://github.com/Turfjs/turf/pull/846

**Comment by DenisCarriere** [comment]
👍 Sounds like a plan!

You need to use `npm` to deprecate a module, more info here:
https://docs.npmjs.com/cli/deprecate

However you would need `npm` publishing rights to do that.

**Comment by DenisCarriere** [comment]
Added `deprecated` warning message.

```sh
$ npm install @turf/idw
npm WARN deprecated @turf/idw@4.6.1: module will be replaced with @turf/interpolate
/Users/mac/Github/test
└─┬ @turf/idw@4.6.1 
  ├─┬ @turf/bbox@4.6.0 
  │ └── @turf/meta@4.6.0 
  ├─┬ @turf/centroid@4.6.1 
  │ └── @turf/helpers@4.6.0 
  ├─┬ @turf/distance@4.6.0 
  │ └── @turf/invariant@4.6.0 
  └── @turf/square-grid@4.6.0 
```

**Comment by DenisCarriere** [comment]
Implemented
