### ISSUE TITLE
inside fails on polygon that transits the anti-meridian

### ISSUE THREAD

**Issue by leandroz** [Turfjs/turf#888]
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

The following point is inside that polygon, Google Maps is returning the expected result but `inside` is returning false.

```js
var latlng = [
  -41.24437,
  174.7618546
]
var poly = [
  [ -33.063924, 172.792969],
  [ -37.020098, -179.648438],
  [ -44.150681, -174.287109],
  [ -53.383328, 169.804688],
  [ -51.124213, 164.267578],
  [ -43.644026, 166.552734],
  [ -32.990236, 172.089844],
  [ -33.063924, 172.792969]
];
```

**Comment by DenisCarriere** [comment]
You've got your coordinates flipped, it should be `[lng, lat]`.

You're poly & point looks like this using http://geojson.io/:

![image](https://user-images.githubusercontent.com/550895/28937087-c1c8aae4-7857-11e7-9e39-a931ec5cd6ac.png)

Going to close this issue.
