### ISSUE TITLE
Distance discrepancies in buffer created from point

### ISSUE THREAD

**Issue by monitz87** [Turfjs/turf#893]
Hi. I'm new to everything geospatial so this question may be irrelevant/wrong.

I made a very simple experiment. Create a 1km buffer from a point and then calculate the distance between that point and each point of the resulting polygon. The resulting distances are all less than 1km (about 0.874km in fact). Shouldn't the distances be closer to 1km or am I getting the whole buffer concept wrong?

I'm using turf 4.6.1

```
const initCoords = [-71.24490379999997, -34.98295599999999];

const point = turf.point(initCoords);

const buffered = turf.buffer(point, 1, 'kilometers');
const coords = buffered.geometry.coordinates[0];

let sum = 0;
coords.forEach(function (coord, index) {
  if (!index) {
    return;
  }
  const distance = turf.distance(point, turf.point(coord), 'kilometers');
  console.log(distance);
  sum += distance;
});

console.log('AVERAGE:', sum/(coords.length - 1));
```

This results in the following output:

```
0.8747623086528354
0.8747604162761806
0.8747573432019707
0.8747532074937557
0.8747481680468953
0.8747424184888005
0.8747361797395968
0.8747296915328604
0.8747232031956567
0.8747169640794132
0.8747112139720432
0.8747061738778954
0.874702037522086
0.874698963895611
0.8746970711556483
0.874696432051432
0.8746970711550605
0.8746989638979049
0.8747020375214969
0.8747061738784271
0.8747112139729385
0.8747169640805378
0.874723203196181
0.8747296915324471
0.8747361797403587
0.8747424184895958
0.8747481680472178
0.874753207493317
0.874757343201496
0.8747604162755113
0.8747623086533391
0.874762947626725
AVERAGE: 0.8747296906857884
```

Cheers

**Comment by rowanwins** [comment]
Hi @monitz87 

The buffer module currently relies on another library called `jsts` which we don't really have any control over, we're looking at replacing this but it's taking a fair bit of work.

If you're primary interested in buffering points then perhaps take a look at the `@turf/circle` [module ](http://turfjs.org/docs/#circle), I think this will generate a more accurate result (although it would be great if you could run your little script for comparison).

Hope that helps

**Comment by stebogit** [comment]
Just for reference, this duplicates #801

**Comment by DenisCarriere** [comment]
like @stebogit mentioned, we'll use the previous issue https://github.com/Turfjs/turf/issues/801 to track this:
