### ISSUE TITLE
Turf simplify creates invalid geometries.

### ISSUE THREAD

**Issue by Jordonkopp** [Turfjs/turf#894]
While using turf.simplify() it creates line crosses, which are invalid geometries.

I am using turf 4.6.1; downloaded from: https://npmcdn.com/@turf/turf@4.6.1/turf.min.js

Here is the original geometry's gist before simplification: https://gist.github.com/Jordonkopp/2d6f9cee9ac5146c449c96312c8771fb

Here it is after running simplification, which causes the line crosses marked by the pins (There may be more): https://gist.github.com/Jordonkopp/c1237d29b769dcd0b1a88b77526037c4

Here is a screen capture of one of the line crosses: 
![image](https://user-images.githubusercontent.com/2439096/29141509-2149a8ae-7d14-11e7-8843-78cea95fa9d5.png)

The broken geometry is generated by simply calling the simplify function.

```javascript
turf.simplify(feature, tolerance, true);
```

Where feature is the first posted gist.
Where tolerance is 0.01.
With the highQuality flag set to true.

I am also running geojsonhint (https://github.com/mapbox/geojsonhint) on the simplified geometry and not getting any errors about the lines crossing. 

Is there a way to prevent this or check for this? 

Thanks in advance.

**Comment by rowanwins** [comment]
Gday @Jordonkopp 

`turf/simplify` uses [simplify.js](http://mourner.github.io/simplify-js/) internally however as you've noted there is no guarantee that it will create non-overlapping geometries.

Geojsonhint doesn't really check for things for overlaps or self-intersections, its more about checking the geojson is structure correctly in terms of the json format and geojson spec.

We've got it on [our radar](https://github.com/Turfjs/turf/issues/64) to have a `validate` style module but it requires a fair bit of work so I wouldn't expect anything soon sorry.

So no short-term answer sorry :(

**Comment by Jordonkopp** [comment]
@rowanwins 

I greatly appreciate your response.

For this case changing the tolerance to 0.001 removed all the self-intersections, and still simplified it into the acceptable size range.

I am also looking into using turf.kinks() to remove the self-intersecting points from the geometry, but this could also cause more intersections by doing so.

I will keep an eye out for the validate module.

-Thanks again

**Comment by DenisCarriere** [comment]
@Jordonkopp Thanks for reporting this issue, unfortunately I don't think this will be fixed since this type of error/issue is out of our control and this type of behavior wouldn't be fixed in `simplify.js` since it won't be doing any such validation.

Going to close this issue for now, however once we have a `validate` module this might help your use case.
