### ISSUE TITLE
buffer issue

### ISSUE THREAD

**Issue by sc-keyzo** [Turfjs/turf#900]
Hi 

Using the following lines of code with @turf/turf 4.6.0 results in a buffer with kinks

`var buffer = turf.buffer(route, 100,  'miles');`

'route' in the above code is the linestring defined in the attached geojson file.  This geojson file also shows the result of the turf.buffer call.

[buffer-error.geojson.zip](https://github.com/Turfjs/turf/files/1222713/buffer-error.geojson.zip)

Have i specified something incorrectly?

regards
Simon

**Comment by DenisCarriere** [comment]
The kinks are definitely causing some issues in the Buffer operations, both in `jsts` & the newly proposed https://github.com/Turfjs/turf/pull/876.

Wouldn't know what to do for temporary solution, I've tried `@turf/clean-coords` & `@turf/simplify` and nothing seems to fix that LineString.

## JSTS

![image](https://user-images.githubusercontent.com/550895/29280937-1398944c-80eb-11e7-8410-1a69a79a480c.png)

**Comment by stebogit** [comment]
Fixed with #938

**Comment by sc-keyzo** [comment]
Hi guys, thanks for your work on this, would it be possible to provide me with an example of how i would use turf/projection to fix my issue?

thanks
Simon

**Comment by DenisCarriere** [comment]
I'll publish a patch release with this fix
