### ISSUE TITLE
`@turf/concave` improvements 

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#910]
- [x] set `maxEdge` parameter optional and by default to `Infinity`.
A common expected output of a `concave` function (like [`concaveman`](https://github.com/mapbox/concaveman)) is always to return a single concave hull `Polygon`. `@turf/concave` has the capability to return a multipolygon (with holes! 👍 ), but this should not be the default behaviour.

- [x] remove Error output if there is no hull to return, it should return an empty `Feature` (`helpers.feature(null)`). (done [here](https://github.com/Turfjs/turf/commit/acbe77d44cb4427d2773802a26b4c681cbc6b617#diff-0da3d3c7e07d2320e0a04705049ec3b0L53)).
Currently the Error "too few polygons found to compute concave hull" is likely due to a small maxEdge. This shouldn't be considered an error, because an error should mean a misuse of the module (which isn't the case here).

Ref. #907.

**Comment by DenisCarriere** [comment]
👍

**Comment by stebogit** [comment]
@DenisCarriere are we sure we should return a `helpers.feature(null)` if no concave hull is possible?
I'd say it should return `null`, for the same reasons why we have now [`null` from `@turf/difference` and `@turf/intersect`](https://github.com/Turfjs/turf/issues/951)

**Comment by DenisCarriere** [comment]
Also seems like the `@turf/great-circle` is doing the same:
https://github.com/Turfjs/turf/blob/fa7acb5cbd75a61353c988395c7c258ae5c7ce20/packages/turf-great-circle/arc.js#L38

**Comment by stebogit** [comment]
Implemented with #1020 and https://github.com/Turfjs/turf/pull/991/commits/acbe77d44cb4427d2773802a26b4c681cbc6b617
