### ISSUE TITLE
booleanContains incorrect when checking 2 polygons

### ISSUE THREAD

**Issue by arnederuwe** [Turfjs/turf#915]
Hello,

First of all, thanks for creating this great lib, it took me 4 hours to program what I wanted in turf after banging my head against the wall with Esri for 2 days...

I think I found an issue with the `turf.booleanContains` functionality, see the following 2 polygons:
https://gist.github.com/arnederuwe/4a71e09b1a2bb6f8d11b3c0d7545fb7d

I could be mistaken, but when reading the docs about `booleanContains` I would expect false from this function when I check if the Parallelogram is fully contained by the other polygon. It returns true, but you can clearly see one edge being outside the border of the other polygon.

When I use `booleanContains` in a for loop to check each point of the parallelogram individually against the other polygon, all works fine and the one outer point is correctly returning a false value.

Am I reading the docs wrong, or is this a bug? (I'm just using a for loop and iterating the points now, so it's not a blocking issue for me)

**Comment by rowanwins** [comment]
Hey @arnederuwe 

Glad you've found turf useful 👍 

Thanks for picking up this issue, it does indeed look like a bug so we'll take a look, hopefully it shouldn't take long to resolve so we'll keep you posted. These boolean modules are relatively new and have a stack of variations to test so I fingers crossed we'll slowly weed out any of these bugs.

Thanks!

**Comment by DenisCarriere** [comment]
> it took me 4 hours to program what I wanted in turf after banging my head against the wall with Esri for 2 days...

❤️ 😄 love it!
