### ISSUE TITLE
Buffer zone transform

### ISSUE THREAD

**Issue by ArtCodeKarine** [Turfjs/turf#916]
Hello everybody, 
I wish to know how i can resolve my problem :
when the buffer zone touches itself, it makes only one area instead of making a "hole" in the middle. Even if the zone is not close. Do you have a solution for it to overlap and it does not merge?
![buffer1](https://user-images.githubusercontent.com/17497949/29664758-5a52ba6e-88d1-11e7-9ded-4ed3847429a5.PNG)
![buffer2](https://user-images.githubusercontent.com/17497949/29664760-5b6170a8-88d1-11e7-9d54-de866e38b68b.PNG)

**Comment by rowanwins** [comment]
Hi @ArtCodeKarine 

Short answer is there is probably no a answer at the moment.

Unfortunately the buffer module currently uses the `jsts` library under the hood so we had limited ability to apply fixes for bugs like these. We're currently attempting to remove that dependency but as Im sure you can see it's quite complicated so it's still a little way off sorry :(

**Comment by ArtCodeKarine** [comment]
@rowanwins  Thank's for your answer :D

**Comment by stebogit** [comment]
@ArtCodeKarine have you tried with [`@turf/transform-scale`](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-scale)? It might work for you, just know you'll have to calculate your `factor` and define the `origin` (see #849).

**Comment by DenisCarriere** [comment]
Thanks for reporting this @ArtCodeKarine , never knew about this strange behavior, this is definitely a bug in `jsts` which we can't control 😢.

**Comment by stebogit** [comment]
Fixed with #938
