### ISSUE TITLE
Clarifying booleanContains definition

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf#919]
Gday @DenisCarriere & @stebogit 

I was doing some investigation into #915 last night, what started as a simple bug fix uncovered a few things...

So it turns out (probably unsuprisingly) that different libraries define `contains` differently.
### Turf definition (which is taken in turn from [Esri-land](http://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/shapes/spatial_relations/predicates.htm#Contains))
> boolean-contains returns True if the second geometry is completely contained by the first geometry. The interiors of both geometries must intersect and, the interior and boundary of the secondary (geometry b) must not intersect the exterior of the primary (geometry a).

### PostGIS [definition](https://postgis.net/docs/ST_Contains.html)
> Returns true if and only if no points of B lie in the exterior of A, and at least one point of the interior of B lies in the interior of A

### Shapely definition
> Returns True if the object’s interior contains the boundary and interior of the other object and their boundaries do not touch at all.

The key difference here is that we and postgis allow boundaries to touch, while shapely does not. [Issues](https://github.com/Toblerity/Shapely/issues/290) have been posted in shapely suggesting that their definition doesn't quite align with the more broadly used definition which does allow boundary touching...

There is lots more info on that postgis page including a link to [this article](http://lin-ear-th-inking.blogspot.com.au/2007/06/subtleties-of-ogc-covers-spatial.html) which talks about things in a bit more detail.

So my feeling is that for this module it's probably best not to test against shapely but rather that we use something else... Thoughts?

**Comment by stebogit** [comment]
👍  good point @rowanwins 

I am no expert here, so I can't make any suggestion on which one might be the best reference, but I definitely agree we (you guys 😄 ) should decide which one to follow (or make a Turf one!) and then make sure all related Turf modules comply with that standard.

I'm quite interested in your opinions about differences, pros and cons of the different standards.

**Comment by rowanwins** [comment]
I don't think any of us are experts @stebogit , but then again there are probably only 100 people in the world that can make that claim geuinely  :) 

I think adopting industry standards where we can is a good approach. It appears to me that shapely is probably out on it's own on this one. 

If we wanted to formally align ourselves to some standards we'd probably need to look at aligning to the [OGC Simple Feature Access standards](http://www.opengeospatial.org/standards/sfa). These are implemented in things like `jts`, `geos` (which is a C++ port of jts) and `postgis` (which uses geos!). Shapely is supposedly built on geos so I've got no idea why there is this anomoly. I'm not sure how feasible it would be to set up a test suite against some of those other options (eg jts or geos)

**Comment by rowanwins** [comment]
So I'm taking a bit of a quick look at creating a `boolean-jsts` test module similar to `boolean-shapely`, we'll see what sort of results that spits out...

**Comment by DenisCarriere** [comment]
👍 Great work @rowanwins , very helpful references you brought up.

Strange that there's differences between PostGIS & Shapely... odd 🤔 

As long as we test our `boolean` modules against another library to make sure we are not "out to lunch", for those slight different implementations we can deal with that as they come up, my vote would be to follow PostGIS's implementation since it's widely used in the Geo open source community (bit more than Shapely).

**Comment by rowanwins** [comment]
Can you think of an easy way to get test against `postgis` @DenisCarriere ?

It's funny how everything (eg postgis, geos, shapely etc etc) is really just an implementation of `jts` either directly or indirectly :) ,except for turf of course :)

**Comment by DenisCarriere** [comment]
🤔 not too sure how we could test for PostGIS... that doesn't sound like an easy one.
