### ISSUE TITLE
New module proposal @turf/filter

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#921]
# New module proposal `@turf/filter`

This module should return `true/false` if the Feature should be filtered based on the GeoJSON properties.

This type of behavior is already being used in `@turf/clusters` & `@turf/dissolve`, this module would replace the `filter` functionality within these two modules and act as a stand alone module with it's own independent testing.

> Could also call this module `@turf/boolean-filter` since the output will strictly be a `boolean`.

## How to use module

```js
const {point} = require('@turf/helpers')
const filter = require('@turf/filter')

const pt = point([10, 20], {foo: 'bar'})
filter(pt, {foo: 'bar'})
//=true
filter(pt, {hello: 'world'})
//=false
```

## Source code

- [@turf/clusters](https://github.com/Turfjs/turf/blob/master/packages/turf-clusters/index.js#L220-L289)
- [@turf/dissolve](https://github.com/Turfjs/turf/blob/master/packages/turf-dissolve/index.js#L80-L84)

## Tests

- [@turf/clusters](https://github.com/Turfjs/turf/blob/master/packages/turf-clusters/test.js#L54-L84)

Ref: https://github.com/Turfjs/turf/pull/907#issuecomment-324851611

**Comment by stebogit** [comment]
@DenisCarriere what would be an application where you would need to process a feature only to check if a feature has one or more properties (which is a pretty simple check actually)? I mean a use that would "justify" a separate module?
Maybe this could be a `helpers` function, probably mainly used internally?

My initial [suggestion](https://github.com/Turfjs/turf/pull/907#issuecomment-324851611) was more along the line of a `filter` parameter (in a possible [new version of `@turf/union`](https://github.com/Turfjs/turf/pull/907#issuecomment-323099974) merging the current `union` and `dissolve` behaviour) accepting a user-defined function like in `Array.filter()`: if the test returns `false` the feature would be filtered (in the specific case not "unified"). A custom function would allow the user to filter based on anything about the feature, not just properties.
This could be applied to `@turf/clusters` as well.
Like:
```js
var features = turf.featureCollection([
  turf.polygon([[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]], {'combine': 'yes'}),
  turf.polygon([[[0, -1], [0, 0], [1, 0], [1, -1], [0,-1]]], {'combine': 'yes'}),
  turf.polygon([[[1,-1],[1, 0], [2, 0], [2, -1], [1, -1]]], {'combine': 'no'}),
]);

var dissolved = turf.union(features, function(f) {
    if (f.properties && f.properties.combine === 'yes') return true;
    return false;
});
```
cc: @rowanwins

**Comment by DenisCarriere** [comment]
Oh a `filter` callback would be interesting...

I still think a `@turf/boolean-filter` module would be useful, the example I provided was pretty basic, however there's a few scenarios which can get pretty complex.

```js
const filter = require('@turf/boolean-filter')

const pt = point([10, 20], {foo: 'bar', value: 10})
// Feature contains key (string)
filter(pt, 'foo')
//=true
// Feature contains key (Array of strings)
filter(pt, ['foo', 'hello'])
//=true
// Feature contains key (string) or Object equals exact match
filter(pt, ['foo', {value: 10}])
//=true
// Feature does not contain any of these keys (Array of String)
filter(pt, ['hello', 'world'])
//=false
// Feature does not contain key (string)
filter(pt, 'hello')
//=false
```

I still support the `filter` param 👍 looks like a good idea.

**Comment by DenisCarriere** [comment]
You could also pair this `boolean-filter` module really nicely with the additional filter param.

```js
const filter = require('@turf/boolean-filter')

const dissolved = turf.union(features, f => filter(f, {combine: 'yes'});
```

**Comment by rowanwins** [comment]
interesting idea @DenisCarriere , some of those more extended uses could certainly be nifty

**Comment by DenisCarriere** [comment]
@rowanwins 👍 Yep, the module is already 80% done from all the existing source code that's in `@turf/clusters`, just need to piece it together.

**Comment by andrewharvey** [comment]
I'd rather not call this `filter`. I came here to suggest we implement the equivalent of the [JS filter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).

    var onlyPoints = turf.filter(geojson, (feature) => {
        return turf.getType(feature) === 'Point';
    })

along with map

    var ids = turf.map(geojson, (feature, index) => {
        feature.id = index;
        return feature;
    })

The advantage of doing this with turf rather than straight JS is the corner cases of where GeoJSON is just one feature rather than a feature collection is abstracted.

**Comment by stebogit** [comment]
I definitely support the `filter` and `map` modules similar to the Array functions.
We could call the original module here `@turf/boolean-has` or `@turf/boolean-has-ptoperty` (which could be used as filter function :smile:)

**Comment by tmcw** [comment]
I'm a 👎 here: this is not a worthwhile abstraction when featureEach can do the same as all with barely any additional code:

Filter:

```js
var fc = {type:'FeatureCollection',features:[]};
turf.featureEach(features, function (currentFeature, featureIndex) {
  if (currentFeature.properties.someProp === 'someValue') {
    fc.features.push(currentFeature);
  }
});
```

**Comment by stebogit** [comment]
@tmcw isn't that true also for the JS Array functions, where you don't really need `.map`, `.filter` and `.reduce` since you could just use `.forEach` instead? They do provide though sometimes a more clear way of writing code and they don't mutate the source array.
Wouldn't it be nice and useful having a `.featureMap` and a `.featureFilter` helper (I mean, meta) functions in addition to the already available `.featureEach` and `.featureReduce` to complete the set?

Just to make sure, are you suggesting the above is still not worth the amount of work necessary to develop, test and maintain those functions?

**Comment by stebogit** [comment]
BTW I see this has been already an issue when [`turf-filter` was removed in v3](https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#301). I wonder then what was the rationale for having `.featureEach` and `.featureReduce` since, as then correctly suggested, you can easily use any `Array` function on the `features` array of a `FeatureCollection`.

**Comment by tmcw** [comment]
>  I wonder then what was the rationale for having .featureEach and .featureReduce since, as then correctly suggested, you can easily use any Array function on the features array of a FeatureCollection.

It was the same rationale as most of the rest of turf-meta: to make sure Turf keeps its promise of supporting 'all GeoJSON' - it [handles the root-level feature case](https://github.com/Turfjs/turf/blob/master/packages/turf-meta/index.mjs#L313).

**Comment by morganherlocker** [comment]
I'm with @tmcw, and may be of the opinion we should go even further in the future, cleaning out other iterators as well, but we can leave that debate for another ticket.
