### ISSUE TITLE
Inconsistent turf.inside results when point is on edge of polygon

### ISSUE THREAD

**Issue by psi-gh** [Turfjs/turf#926]
Subject. You can check it in my simple example:
https://runkit.com/psi-gh/turf.inside-test
GeoJson from example: https://gist.github.com/psi-gh/710d21d98dc50bae57d3306b5bc863b9

**Comment by stebogit** [comment]
@psi-gh just a note, does this mean you are loading Turf `v3.0.14`?
![screen shot 2017-08-31 at 12 42 09 pm](https://user-images.githubusercontent.com/12717225/29942240-02517034-8e4a-11e7-9c57-ebf50b5a527d.png)

If so could you please test it with the latest `v4.6.1`?

**Comment by rowanwins** [comment]
Good pickup @stebogit 

See this [alternate notebook](https://runkit.com/rowanwins/turf-inside). @psi-gh you should be requiring either `@turf/turf` (for everything) or `@turf/inside` . the old `turf` is legacy, all the turf modules now use `@turf`

**Comment by psi-gh** [comment]
Thanks guys, it is working now!
I'm curious, which algorithm is used in `inside` function and how is "boundary case" achieved?

**Comment by stebogit** [comment]
@psi-gh you can take a look [here](https://github.com/Turfjs/turf/blob/master/packages/turf-inside/index.js) 😃
