### ISSUE TITLE
`kinks` gives false negatives for certain LineString intersections

### ISSUE THREAD

**Issue by senritsu** [Turfjs/turf#934]
During refactoring of the `kinks` package to also support `LineString`s (3033364e24a67d6eec65ad82f4e1af0c9c9565be) the logic to prevent intersections of the start and end point of the rings of a polygon (see last condition on [line 52](https://github.com/Turfjs/turf/blob/master/packages/turf-kinks/index.js#L52)) was not changed. 

Due to this, intersections between the first and last segments of a `LineString` are not detected by the `kinks` function.

Visual example of affected `LineString`s:

![linestring_kinks](https://user-images.githubusercontent.com/790689/30109864-4010c33a-9308-11e7-97fd-1200096902f0.png)

In these cases, no self-intersection is reported.

**Comment by rowanwins** [comment]
Thanks for the report @senritsu . Given that you've done some digging would you like to submit a pull request with a fix?

**Comment by senritsu** [comment]
Yes, that shouldn't be problem. As we need this feature at work as well, my employer should have no objections :)

**Comment by rowanwins** [comment]
awesome, thanks @senritsu  , sing out if you need any help!
