### ISSUE TITLE
`kinks` package reports self-intersections twice

### ISSUE THREAD

**Issue by senritsu** [Turfjs/turf#935]
The `kinks` function uses a nested loop to detect intersections between coordinate pairs (starting in [line 47](https://github.com/Turfjs/turf/blob/master/packages/turf-kinks/index.js#L47)). 

If two segments `i` and `k` (for `i < k`) intersect, the call to `lineIntersects` with (simplified) parameters `(k, i)` will return the same intersection as the previously (in loop order) processed `(i, k)`.

There is no check present to skip already processed equivalent index pairs, therefore the same self-intersection is always added to the result set twice.

**Comment by rowanwins** [comment]
Hi @senritsu 

Funny you should mention this issue, I just resolved it yesterday in #931 , although it probably hasnt been released to npm yet so stay tuned.

Thanks

**Comment by senritsu** [comment]
Yeah, i just noticed that while checking out the sources to fix it myself, so i guess this is good timing 👍
