### ISSUE TITLE
Adopt `options` object for optional parameters

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#944]
Formalizing @DenisCarriere's elegant [proposal](https://github.com/Turfjs/turf/pull/876#issuecomment-319070336), which I really like. 😄 
I would actually include **all** the optional parameters in the `options` object, making it more consistent throughout the library.

```js
/**
 * @param {Object} [options={}] Optional parameters
 * @param {string} [options.units="kilometers"] can be degrees, radians, miles, kilometers, ...
 * @param {number} [options.steps=64] number of steps on a rounded corner
 */
module.exports = function (feature, distance, options) {
    options = options || {};
    var units = options.units;
    var steps = options.steps;
```
As suggested, we might formally adopt this for new modules and refactor the existing modules in the new major release.

cc: @rowanwins 

## Single optional parameter (Backwards compatible with v4.0)

```js
/**
 * @param {Feature<LineString>} line input line
 * @param {number} distance distance along the line
 * @param {Object} [options] Optional parameters
 * @param {string} [options.units="kilometers"] can be degrees, radians, miles, or kilometers
 */
export default function (line, distance, options) {
    // Backwards compatible with v4.0
    var units = (typeof options === 'object') ? options.units : options;
```

**index.d.ts**

```ts
interface Options {
    units?: Units;
}
export default function along(line: LineString, distance: number, options?: Options): Point;
```

## Multiple optional parameters (❗️ breaking change)

```js
/**
 * @param {Feature<LineString>} line input LineString
 * @param {Object} [options] Optional parameters
 * @param {number} [options.resolution=10000] time in milliseconds between points
 * @param {number} [options.sharpness=0.85] a measure of how curvy the path should be between splines
*/
export default function (line, options) {
    // Optional params
    options = options || {};
    var resolution = options.resolution || 10000;
    var sharpness = options.sharpness || 0.85;

    // validation
    if (typeof options !== 'object') throw new Error('options must be an object');
    if (typeof resolution !== 'number') throw new Error('options must be an number');
    if (typeof sharpness !== 'number') throw new Error('sharpness must be an number');
```

**index.d.ts**

```ts
interface Options {
    resolution?: number;
    sharpness?: number;
}
export default function bezier(line: LineString, options?: Options): LineString;
```

## Apply to the following modules:

- [x] [@turf/along](https://github.com/Turfjs/turf/tree/master/packages/turf-along) (@DenisCarriere)
- [x] [@turf/bearing](https://github.com/Turfjs/turf/tree/master/packages/turf-bearing) (@DenisCarriere)
- [x] [@turf/bezier](https://github.com/Turfjs/turf/tree/master/packages/turf-bezier) (@DenisCarriere)
- [x] [@turf/boolean-point-on-line](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-point-on-line) (@DenisCarriere)
- [x] [@turf/buffer](https://github.com/Turfjs/turf/tree/master/packages/turf-buffer) (@DenisCarriere)
- [x] [@turf/circle](https://github.com/Turfjs/turf/tree/master/packages/turf-circle) (@DenisCarriere)
- [x] [@turf/clean-coords](https://github.com/Turfjs/turf/tree/master/packages/turf-clean-coords) (@DenisCarriere)
- [x] [@turf/clusters-dbscan](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-dbscan) (@DenisCarriere)
- [x] [@turf/clusters-kmeans](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-kmeans) (@DenisCarriere)
- [x] [@turf/concave](https://github.com/Turfjs/turf/tree/master/packages/turf-concave) (@DenisCarriere)
- [x] [@turf/destination](https://github.com/Turfjs/turf/tree/master/packages/turf-destination) (@DenisCarriere)
- [x] [@turf/dissolve](https://github.com/Turfjs/turf/tree/master/packages/turf-dissolve) (@DenisCarriere)
- [x] [@turf/distance](https://github.com/Turfjs/turf/tree/master/packages/turf-distance) (@DenisCarriere)
- [x] [@turf/flip](https://github.com/Turfjs/turf/tree/master/packages/turf-flip) (@DenisCarriere)
- [x] [@turf/great-circle](https://github.com/Turfjs/turf/tree/master/packages/turf-great-circle)
- [x] [@turf/helpers](https://github.com/Turfjs/turf/tree/master/packages/turf-helpers)
- [x] [@turf/hex-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-hex-grid)
- [x] ~@ turf/idw~  this is going to be [deprecated](https://github.com/Turfjs/turf/issues/887)
- [x] [@turf/inside](https://github.com/Turfjs/turf/tree/master/packages/turf-inside)
- [x] [@turf/interpolate](https://github.com/Turfjs/turf/tree/master/packages/turf-interpolate)
- [x] [@turf/isobands](https://github.com/Turfjs/turf/tree/master/packages/turf-isobands)
- [x] [@turf/isolines](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines)
- [x] [@turf/line-arc](https://github.com/Turfjs/turf/tree/master/packages/turf-line-arc)
- [x] [@turf/line-chunk](https://github.com/Turfjs/turf/tree/master/packages/turf-line-chunk)
- [x] [@turf/line-distance](https://github.com/Turfjs/turf/tree/master/packages/turf-line-distance)
- [x] [@turf/line-offset](https://github.com/Turfjs/turf/tree/master/packages/turf-line-offset)
- [x] [@turf/line-overlap](https://github.com/Turfjs/turf/tree/master/packages/turf-line-overlap)
- [x] [@turf/line-slice-along](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice-along)
- [x] [@turf/linestring-to-polygon](https://github.com/Turfjs/turf/tree/master/packages/turf-linestring-to-polygon)
- [x] [@turf/meta](https://github.com/Turfjs/turf/tree/master/packages/turf-meta)
- [x] [@turf/nearest-point-to-line](https://github.com/Turfjs/turf/tree/master/packages/turf-nearest-point-to-line)
- [x] [@turf/point-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-point-grid) (@stebogit)
- [x] [@turf/point-on-line](https://github.com/Turfjs/turf/tree/master/packages/turf-point-on-line)
- [x] [@turf/point-to-line-distance](https://github.com/Turfjs/turf/tree/master/packages/turf-point-to-line-distance)
- [x] [@turf/projection](https://github.com/Turfjs/turf/tree/master/packages/turf-projection)
- [x] [@turf/random](https://github.com/Turfjs/turf/tree/master/packages/turf-random)
- [x] [@turf/rewind](https://github.com/Turfjs/turf/tree/master/packages/turf-rewind)
- [x] [@turf/rhumb-bearing](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-bearing) (@stebogit)
- [x] [@turf/rhumb-destination](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-destination) (@stebogit)
- [x] [@turf/rhumb-distance](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-distance) (@stebogit)
- [x] [@turf/sector](https://github.com/Turfjs/turf/tree/master/packages/turf-sector)
- [x] [@turf/simplify](https://github.com/Turfjs/turf/tree/master/packages/turf-simplify)
- [x] [@turf/square-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-square-grid)
- [x] [@turf/transform-rotate](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-rotate)
- [x] [@turf/transform-scale](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-scale)
- [x] [@turf/transform-translate](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-translate)
- [x] [@turf/triangle-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-triangle-grid)
- [x] [@turf/truncate](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate)

**Comment by DenisCarriere** [comment]
+1 agreed!

**Comment by stebogit** [comment]
@DenisCarriere @rowanwins I copied the todo list in here, so we can keep track of our progress even if we create multiple branches to complete this.

**Comment by DenisCarriere** [comment]
👍 Make sense!

**Comment by DenisCarriere** [comment]
🎉 All done.. now just need to review the remaining errors that were caused by the refactoring.

https://github.com/Turfjs/turf/pull/993

**Comment by DenisCarriere** [comment]
Done
