### ISSUE TITLE
ES6 Export modules (experimental trial)

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#955]
# ES6 Export modules

A few attempts have already been made to include the new Import & Export syntax from ES6, none of these attempts were very minimalistics and required the TurfJS developers to compile the code before they can perform any tests.

## Proposal

Continue to write pure ES5 modules, except have a pre-publishing script that would convert the ES5 code (`index.js`) to include ES6's `export` & `import` syntax (`module.js`).

The `module.js` will be hidden using `.gitignore` and would be used prior to publishing new releases.

## First modules to implement

Going to implement experimental trial with only a few modules at first before we go ahead with the entire library, the ones will be available to test with the newest ES6 export "module" syntax will be:

- `@turf/meta`
- `@turf/helpers`
- `@turf/invariant`

## Rollup Configuration

Once this is completed, using Rollup or other ES6 bundlers should become a bit easier to use and without any complicated configurations.

**test.js**
```js
import {point} from '@turf/helpers'

point([12, 1])
```

**rollup.config.js**
```js
export default {
    input: 'index',
    output: {
        extend: true,
        sourcemap: true,
        file: 'dist/index.js',
        format: 'cjs'
    }
};
```

```bash
$ rollup -c rollup.config.js
```

The [**output.js**](https://gist.github.com/DenisCarriere/6fe0a6c9a9ed05b54e294c5a078cedbc) bundle only contains  76 lines of code (45 of them are comments).

### Single Method Modules

**ES5**
```js
const point = require('@turf/helpers').point;

/**
 * main module
 */
module.exports = function () {
  return point([0, 0]);
}
```

**ES6**
```js
import {point} from '@turf/helpers';

/**
 * main module
 */
export default function () {
  return point([0, 0]);
}
```

### Mutli Method Modules

**ES5**
```js
const helpers = require('@turf/helpers');
const point = helpers.points;
const lineString = helpers.lineString;

/**
 * foo method
 */
module.exports.foo = function foo () {
  return point([0, 0]);
}

/**
 * bar method
 */
module.exports.bar = function bar () {
  return point([20, 30]);
}
```

**ES6**
```js
import {point, lineString} from '@turf/helpers';

/**
 * foo method
 */
export function foo () {
  return point([0, 0]);
}

/**
 * bar method
 */
export function bar () {
  return lineString([[40, 30], [20, 30]]);
}
```

## Add module to `package.json`

To support this new syntax, we will also need to add `module.js` to the `package.json`.

```json
{
  "name": "@turf/helpers",
  "version": "4.7.3",
  "description": "turf helpers module",
  "main": "dist/index.js",
  "module": "index",
  "jsnext:main": "index",
  "types": "index.d.ts",
  "files": [
    "index.js",
    "index.d.ts",
    "dist"
  ],
...
}
```

**Comment by rowanwins** [comment]
Hi @DenisCarriere 

The challenge I had previously when looking at this with @tmcw and `simple-statistics` was how to manage testing. I think tape freaks out on es6 modules, unless we test on the compiled code, which is doable, but requires a compilation step. Although looking at the tape doco it might be possible to do something with this https://github.com/substack/tape#preloading-modules 

Anyway this would be cool if we can get it going!

**Comment by stebogit** [comment]
@DenisCarriere @rowanwins what would be the big advantage of just using ES6 `export`/`import`?
I mean, why not moving entirely to ES6 for development, if we are going to compile the code for publishing? _That_ would be a big improvement.

**Comment by amenadiel** [comment]
@DenisCarriere @stebogit  keeping an ES5 script would allow test tools (karma, tape) to pass, as they do not understand ES6 modules.

Having ES6 modules alongside would allow for tree shaking during builds when you're working with @turf modules as dependencies. For example, I have a tool that depends on `@turf/helpers` but only uses `lineString` function, so my build would eventually be leaner if I could leave aside the rest of the functions in `@turf/helpers`.

**Comment by tmcw** [comment]
I'm very pro-ES6 modules - they're a boon for documentation, static analysis, and tree-shaking-related optimizations.

This is an interesting proposal: it goes kind of the opposite of what most folks are doing. Stuff like [5to6](https://github.com/5to6/5to6-codemod) also tries to do this dance.

Whether this is the right strategy... well, it's not what I would do. [ES6 modules are not just syntax sugar](https://macwright.org/2017/04/18/bindings-not-values.html), and I'd be very concerned about writing ES5 code that works with require, but when converted into ES6 import/export, would fail because it's expecting values instead of bindings. Or if an author is using, for instance, a dynamic require method.

Unfortunately import/export support for node.js doesn't seem like it'll happen this year (hope I'm wrong about that), but... well, one of the reasons I've perceived with turf avoiding ES6 for now is that if it relied on Babel/Jest/or a more 'heavyweight' test library, it'd install 50 versions of it. That's no longer a strong limitation - [workspaces in yarn](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) _should_ eliminate that concern and let all 50 turf packages rely on the same shared devDependencies. So you'd write ES6 import/exporty code, rely on rollup to build bundles in a `pretest` task... testing wouldn't be as dead-simple as if the main code was in ES5, but it'd eliminate some potential corner-casey issues with transpilation.

**Comment by DenisCarriere** [comment]
Thanks all for the comments and feedback! I don't know how many times this topic has been brought up in TurfJS, but it's been a real personal goal of mine to try to figure out what the best way to approach this.

> That's no longer a strong limitation - workspaces in yarn should eliminate that concern and let all 50 turf packages rely on the same shared devDependencies. So you'd write ES6 import/exporty code, rely on rollup to build bundles in a pretest task... testing wouldn't be as dead-simple as if the main code was in ES5, but it'd eliminate some potential corner-casey issues with transpilation.

This is a great point! The reason why we never had pre-tests was because it would be too painful to install devDependencies in each TurfJS module. This approach sounds like a winner, I'm sure we could find a creative way to include a `pretest` script which could easily be applied to all `package.json` modules.

> So you'd write ES6 import/exporty code, rely on rollup to build bundles in a pretest task... testing wouldn't be as dead-simple as if the main code was in ES5, but it'd eliminate some potential corner-casey issues with transpilation.

👍 Eliminating those potential transpilation issues is a big concern, I agree with the ES6 "import/exporty" code.

> @amenadiel allow for tree shaking during builds when you're working with @Turf modules as dependencies

Tree shaking is my personal favorite benefits of including ES6 code, using Rollup (and Webpack) really showcases the power of that benefit.

> > This is an interesting proposal: it goes kind of the opposite of what most folks are doing. Stuff like 5to6 also tries to do this dance.

Agreed! 😃 Definitely in the opposite direction then the majority, it's so nice being able to run tests by simply running `node test.js` and it just works! I really hope NodeJS can finally support import/exports.

@tmcw Have you tried out `@std/esm` yet? What's your thoughts on that? I've successfully been able to get something working for `@turf/helpers`, I'll send a PR with the proposed change (this might be a better route then using the `pretest` Rollup solution).

**Comment by DenisCarriere** [comment]
Implemented ES6 modules using Rollup.

**Comment by rowanwins** [comment]
Hey @DenisCarriere 

So I've attempted pulling down the master branch and taking a look, however when I run `npm run test` at the module level it fails, eg

````
> @turf/difference@4.7.4 pretest C:\code\turf\packages\turf-difference
> rollup -c ../../rollup.config.js

index.mjs → index.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
@turf/area (imported by index.mjs)
@turf/helpers (imported by index.mjs)
@turf/invariant (imported by index.mjs)
@turf/meta (imported by index.mjs)
created index.js in 51ms
````

Have I missed something or have we got a windows bug?

**Comment by DenisCarriere** [comment]
@rowanwins I'd do a fresh clone of the TurfJS repo. (`index.mjs` was a previous branch)

I just did a fresh install and it works for me:

```bash
$ git clone git@github.com:Turfjs/turf.git
$ cd turf/packages/turf-difference
$ yarn
$ npm t
```
