### ISSUE TITLE
Remove Geodesy as dependency (rhumb modules)

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#971]
# Remove Geodesy as dependency

Looking at our no-ES6 libraries, noticed [Geodesy](https://github.com/chrisveness/geodesy) is only used in the [`@turf/rhumb-bearing`](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-bearing) & other rhumb modules.

This seems like it would be easy enough to [include directly](https://github.com/chrisveness/geodesy/blob/d78c067211b35a4c755ba122a5df63ebbdbe364c/latlon-spherical.js#L452-L477) in TurfJS, this would eliminate a 268KB dependency (minified would be smaller).

CC: @stebogit

**Comment by stebogit** [comment]
Agreed!! 👍  ✂️ 📄

**Comment by stebogit** [comment]
Man! I want you coffee machine @DenisCarriere! ☕️  🤣

**Comment by DenisCarriere** [comment]
🎉 Implemented
