### ISSUE TITLE
Support ES modules with `@std/esm`

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#974]
### PR used in this proposal: https://github.com/Turfjs/turf/pull/975

Using [`@std/esm`](https://github.com/standard-things/esm) seems to work perfectly with NodeJS (4+ compatible) and works well with our `tape` testing suite, ~unfortunately... it doesn't like it when you use `.js` for ES Modules~ (Added `@std/esm` to fix this)

```
SyntaxError: 'import' and 'export' may only be used in ES modules
```

~😢 ... Going to refactor everything back to `.js` => `.mjs` (dropping `.es5.js` files) once this is done, a fresh git clone would be required.~

## 🥇 Easy to use

When `@std/esm` is included as a devDependency, you can easily execute the `tape` tests using the following:

```
$ node -r @std/esm test.js
$ node -r @std/esm bench.js
$ node -r @std/esm index.js
```

🎉 🚀 Omg...! No Rollup pretest was required for this test to run successfully.

## Publishing

The Rollup `pretest` will be changed to => `prepublish` to transpile the `index.js` (ES Modules) => `dist/index.js` (CommonJS) before publishing a new release.

## ❌ Not happening 

- No Babel on index files
- No Rollup on test files (tests can be ES Modules or CommonJS 🎉 )

This is such a pain 😢 ... (it will be worth it at the end of this madness)

CC: @Turfjs/ownership

**Comment by DenisCarriere** [comment]
☕️ ☕️ ...

**Comment by rowanwins** [comment]
🍻

**Comment by stebogit** [comment]
@DenisCarriere I don't know if it is related to this specific issue, but I noticed right now some sort of cache (`.esm-cache`) is created when running `npm test`.
Why is that?
While developing it seems this doesn't allow you to iteratively modify the code and rerun the tests without deleting the cached files.
Am I using it in the wrong way?

**Comment by DenisCarriere** [comment]
The `.esm-cache` is what `@std/esm` creates when executing `node -r @std/esm test.js` (essentially it compiles the ES Module code 🤦‍♂️ ).

This approach makes it so NodeJS 4+ is compatible with ES Modules, the compile time is very short so you shouldn't need to wait for that process.

>While developing it seems this doesn't allow you to iteratively modify the code and rerun the tests without deleting the cached files.

🤔 You shouldn't have to delete the cache files manually, every time you run `npm test` it should recreate the cache and run the "newer" version of your code (if it doesn't.. let me know).

**Comment by DenisCarriere** [comment]
So I did a test on the `master` branch, seems to work fine:

**index.js** (unmodified)

```
$ node -r @std/esm index.js
```

**index.js** (added `console.log('foo')`)

```
$ node -r @std/esm index.js
foo
```

@stebogit Let me know if that behavior is the same for you

**Comment by stebogit** [comment]
@DenisCarriere this kinda work, meaning that if I run `npm test` at the module level it does compile the changes.
However the PHPStorm node debug does not see the changes, I have to manually run the script first to be able to debug the code... Also the import/export clearly do not run in node, so I need to replace them with `require` if I want to use the PHPStorm debugger 😢 
Is this how I should expect to develop with the new configuration?
Maybe I need to find a better setup for my IDE, ideas?

**Comment by DenisCarriere** [comment]
@stebogit Ideally in the "future" 🚀 this export/import syntax will be native to NodeJS and then PHPStorm should just "work" without any `@std/esm` if you are using a latest version of Node (maybe v9?).

Closing this issue since `@std/esm` is now implemented across all Turf modules.

**Comment by jdalton** [comment]
Thanks 🙇 for using `@std/esm`, let me know if you run into any issues or have feedback!

**Comment by DenisCarriere** [comment]
@jdalton Sorry for the 17+ day response, I still haven't forgotten about your comment. As for feedback, so far `@std/esm` is working out just great!

I'll make sure to send some feedback on `@std/esm` issues, so far it looks great! 👍
