### ISSUE TITLE
Opinion: Website scrolling slightly offputting?

### ISSUE THREAD

**Issue by ChrisBellew** [Turfjs/turf#983]
Hello,

Firstly, what a great library this is. Thanks a lot!

Just wanted to make a (very low priority :)) comment about the documentation site here http://turfjs.org/docs/

I'm not sure if it's just me but it feels slightly offputting that the live example next to each section seems to appear as you uncover the section, as soon as it is right at the bottom of the viewport.

I have this behavior of moving the thing I am focusing to the middle of the page, and I'm sure others do too? But in these docs this would cause the thing I am focusing on to lose its live example, until I push it to the bottom of my viewport by scrolling.

I'm just interested to know what the idea behind this behavior is?

(I won't be offended if you don't reply and think this is a waste of time haha)

Thanks
Chris

**Comment by stebogit** [comment]
Hey @ChrisBellew, you're not alone in that!
@rowanwins in particular is already thinking about [how to improve it](https://github.com/Turfjs/turf-www/issues/115). 😃 
So stay tune! 👍 
And feel free to share ideas 💡 

Gonna close this, but you can add more in the [Turf/www](https://github.com/Turfjs/turf-www) project.

**Comment by rowanwins** [comment]
Hi @ChrisBellew

Yeah unfortunately we had to apply some trickery to avoid loading 100 maps on the page, hence why it moves with the scroll. This issue will go away when I release the new docs.

Cheers

**Comment by ChrisBellew** [comment]
Happy times :)
