### ISSUE TITLE
Use a single version of JSTS

### ISSUE THREAD

**Issue by AABoyles** [Turfjs/turf#984]
Turf presently requires specific versions of jsts in difference, union, intersect, and buffer. While I see that [factoring JSTS out of turf](https://github.com/Turfjs/turf/issues?q=is%3Aissue+is%3Aopen+jsts+label%3Aremove-jsts) has been on the agenda for awhile now, I'd like to request a simpler change: just use one version of it. That way, if nothing else, a turf user will only need to download it once (20MB) instead of five times (100MB). I didn't do extensive checking or testing, but a cursory peek at the code leads me to believe there isn't anything special requiring the specific versions of jsts that are named in these modules.

**Comment by DenisCarriere** [comment]
There is a test to make sure we don't use multiple versions of jsts.

Thanks for reporting this issue regardless. It was an issue in earlier versions.
https://github.com/Turfjs/turf/blob/master/packages/turf/test.js#L52

**Comment by AABoyles** [comment]
Hey Dennis, thanks for responding!

The test is contradictory. It checks for jsts v1.4.0 and if it isn't there, it fails with the message that the module must use jsts v.1.3.0. So which is correct? Should modules be using jsts 1.3.0 or 1.4.0?

Also, if you're confident this is resolved, was it resolved recently? I discovered this based on the latest release on npm, which is only three weeks old.

**Comment by DenisCarriere** [comment]
Ops the test does contradict itself, but it should be version `1.4.0`, the console message it different.

This validation has been present since 5 months ago. So it doesn't look like it's TurfJS that has multiple `jsts` versions, might come from a 3rd party dependency.

https://github.com/Turfjs/turf/blame/09027fe0639783ffdb03e486a66f5b89583bda5e/packages/turf/test.js#L52

**Comment by DenisCarriere** [comment]
@AABoyles Feel free to add more tests in the main package for global checks, however I'm confident that there's nothing more TurfJS can do about the `jsts` dependency.
