### ISSUE TITLE
lineSplit location is different depending on which line is first

### ISSUE THREAD

**Issue by alexgleith** [Turfjs/turf#990]
Please provide the following when reporting an issue:

- [https://gist.github.com/alexgleith/7d6312821911c4b49ff6ec735c6d021c](Split results)
- [https://github.com/Turfjs/turf/pull/989](PR with test reproducing the issue is here)

The issue is that when splitting a line, featureOne, with another line, featureTwo, the location of the split can be different. This'll be a hairy issue around coordinate precision, I guess, but it makes a difference in some situations.

Issue can be visualised here:

![image](https://user-images.githubusercontent.com/3445853/31101590-26a27f2a-a81a-11e7-946e-95a50a56b82c.png)

**Comment by DenisCarriere** [comment]
Doesn't this say 2.4 mm (millimeters?)

**Comment by DenisCarriere** [comment]
Going to close this until we can get another test fixture which has a greater error than 2mm.

**Comment by alexgleith** [comment]
Hey @DenisCarriere, I probably didn't explain it well enough...

I think this is the root cause of [this issue](https://github.com/Turfjs/turf/issues/580#issuecomment-333418924).

And in looking at that issue with the `polygon-split` function, I did try the `truncate` operation, but it breaks the 'point on line' test (I guess due to precision again).

So, perhaps I should write it up differently, as there's no neat solution that will work for all cases of the polygon splitter, I don't think.

**Comment by DenisCarriere** [comment]
🤔 It's definitely a painful one... I would suggest you test your `polygon-slice` method using 6 decimal precision.

There's also `@turf/clean-coords` which might help to apply before you perform any operations:

https://github.com/Turfjs/turf/tree/master/packages/turf-clean-coords
