### ISSUE TITLE
Update API Docs

### ISSUE THREAD

**Issue by bwyss** [Turfjs/turf#992]
A small thing, the API docs under Meta / getGeom reads:

`var geom = turf.getGeom(point)`

Should be:

`var geom = turf.invariant.getGeom(point)`

**Comment by DenisCarriere** [comment]
When using `@turf/turf` it exposes all the sub methods.

**is valid**
```js
var geom = turf.getGeom(point)
```
**won't work in v5.0** (maybe it should.. 🤔 )

```js
var geom = turf.invariant.getGeom(point)
```
Ref: https://github.com/Turfjs/turf/blob/master/packages/turf/index.js#L101

**Comment by bwyss** [comment]
thx! I absolutely love the library by the way!!!

**Comment by DenisCarriere** [comment]
👍 @bwyss Thanks, don't hesitate to submit more issues if something isn't conforming to the GeoJSON spec.
