### ISSUE TITLE
Rework @turf/random

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#994]
# Rework `@turf/random`

Looking at the `@turf/random` module and it seems like it could use a revamp for the next major release (v5.0).

## Reasons for rework

- [`geojson-random`](https://github.com/node-geojson/geojson-random)  dependency doesn't include ES modules
- Make it behave exactly like `geojson-random`.
- Extend `lineString` & `Position` support.
- Each random method will have it's own dedicated JSDocs (at the moment it's all grouped and causes confusion).

## Before

```js
import random from '@turf/random';

const bbox = [-70, 40, -60, 60]
const points = random('point', 100, {bbox})
```

## Proposed

```js
import * as random from '@turf/random';

const bbox = [-70, 40, -60, 60]
const points = random.point(100, {bbox})
```

## Alternate ES module import

This allows tree shaking to exclude any source code which isn't relevant to the `random.point` method.

```js
import { point as randomPoint } from '@turf/random';

const bbox = [-70, 40, -60, 60]
const points = randomPoint(100, {bbox})
```

**Comment by DenisCarriere** [comment]
# ⚠️  Change to proposal

To prevent any method name duplication from `@turf/helpers` (point, lineString, polygon).

Going to change the method names to `randomPoint`, `randomLineString` & `randomPolygon` that way it's easier to expose them in `@turf/turf` without manually defining them with `as`.

**Comment by stebogit** [comment]
Reworked via #995
