### ISSUE TITLE
turf.circle (Polygons) should follow the right-hand rule

### ISSUE THREAD

**Issue by bwyss** [Turfjs/turf#997]
When creating a circle the resulting polygon violates the right-hand rule.

eg: 

`{
      "features": [
        {
          "geometry": {
            "coordinates": [
              [
                [
                  -95.214561936440190948,
                  29.814460843464615891
                ],
                [
                  -95.214464164386669154,
                  29.814453208504897219
                ],
                [
                  -95.214369534851002186,
                  29.814430549023057893
                ],
                [
                  -95.214281089342350128,
                  29.814393593323348597
                ],
                [
                  -95.214201670599791782,
                  29.814343529207391725
                ],
                [
                  -95.21413383122073526,
                  29.814281965795366602
                ],
                [
                  -95.214079751616679914,
                  29.814210881805180975
                ],
                [
                  -95.214041169933125275,
                  29.814132561952447986
                ],
                [
                  -95.214019326186544845,
                  29.814049523515574691
                ],
                [
                  -95.214014922412999908,
                  29.813964435426584032
                ],
                [
                  -95.2140281001092319,
                  29.813880032488395244
                ],
                [
                  -95.2140584356905606,
                  29.813799027475766934
                ],
                [
                  -95.214104954110553081,
                  29.813724023945162855
                ],
                [
                  -95.2141661602045275,
                  29.813657432555721982
                ],
                [
                  -95.214240086748404224,
                  29.81360139359074779
                ],
                [
                  -95.214324357688170153,
                  29.813557708169632576
                ],
                [
                  -95.214416264507491405,
                  29.813527780360832509
                ],
                [
                  -95.214512853278947091,
                  29.813512572056094285
                ],
                [
                  -95.214611019601434805,
                  29.813512572056094285
                ],
                [
                  -95.214707608372890491,
                  29.813527780360832509
                ],
                [
                  -95.214799515192211743,
                  29.813557708169632576
                ],
                [
                  -95.214883786131991883,
                  29.81360139359074779
                ],
                [
                  -95.214957712675854395,
                  29.813657432555721982
                ],
                [
                  -95.215018918769828815,
                  29.813724023945162855
                ],
                [
                  -95.215065437189835507,
                  29.813799027475766934
                ],
                [
                  -95.215095772771149996,
                  29.813880032488395244
                ],
                [
                  -95.215108950467396198,
                  29.813964435426584032
                ],
                [
                  -95.215104546693837051,
                  29.814049523515574691
                ],
                [
                  -95.215082702947270832,
                  29.814132561952447986
                ],
                [
                  -95.215044121263716193,
                  29.814210881805180975
                ],
                [
                  -95.214990041659646636,
                  29.814281965795366602
                ],
                [
                  -95.214922202280590113,
                  29.814343529207391725
                ],
                [
                  -95.214842783538031767,
                  29.814393593323348597
                ],
                [
                  -95.214754338029393921,
                  29.814430549023057893
                ],
                [
                  -95.214659708493712742,
                  29.814453208504897219
                ],
                [
                  -95.214561936440190948,
                  29.814460843464615891
                ]
              ]
            ],
            "type": "Polygon"
          },
          "properties": {
            "foo": "bar"
          },
          "type": "Feature"
        }
      ],
      "type": "FeatureCollection"
    }
`

Can be tested here [geojsonlint](http://geojsonlint.com/)

Using 'rewind' makes the GeoJson valid.

**Comment by DenisCarriere** [comment]
👍 Good catch! This should be fixed

**Comment by stebogit** [comment]
Fixed with #998
